force-app/main/default/objects/Actions__c/Actions__c.object-meta.xml
<CustomObject>
    <description>Object that captures actions to be taken when the usr hits a specific URL/type of page.</description>
    <label>Actions</label>
    <nameField>
        <label>Guideme Actions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Actions__c/fields/Image_Carousel_Config__c.field-meta.xml
<CustomField>
    <fullName>Image_Carousel_Config__c</fullName>
    <label>Image Carousel Config</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Actions__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Actions__c/fields/Page_Type__c.field-meta.xml
<CustomField>
    <fullName>Page_Type__c</fullName>
    <label>Page Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Record Home</fullName>
            </value>
            <value>
                <fullName>Record Detail</fullName>
            </value>
            <value>
                <fullName>Record Update</fullName>
            </value>
            <value>
                <fullName>Record Create</fullName>
            </value>
            <value>
                <fullName>Reports Home</fullName>
            </value>
            <value>
                <fullName>Dashboards Home</fullName>
            </value>
            <value>
                <fullName>Task home</fullName>
            </value>
            <value>
                <fullName>Task Detail From List</fullName>
            </value>
            <value>
                <fullName>Chatter</fullName>
            </value>
            <value>
                <fullName>Chatter Group Detail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Actions__c/recordTypes/Image_Carousel.recordType-meta.xml
<RecordType>
    <fullName>Image_Carousel</fullName>
    <active>true</active>
    <label>Image Carousel</label>
</RecordType>

force-app/main/default/objects/Carousel_Image__c/Carousel_Image__c.object-meta.xml
<CustomObject>
    <label>Carousel Image</label>
    <nameField>
        <label>Carousel Image Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Carousel Images</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Carousel_Image__c/fields/Actions__c.field-meta.xml
<CustomField>
    <fullName>Actions__c</fullName>
    <label>Actions</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Actions__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Image Carousel</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Actions__c</referenceTo>
    <relationshipLabel>Carousel Images</relationshipLabel>
    <relationshipName>Carousel_Images</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Carousel_Image__c/fields/Image_Url__c.field-meta.xml
<CustomField>
    <fullName>Image_Url__c</fullName>
    <label>Image Url</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/UpdateImageConfigJsonHandlerTest.cls
@IsTest
public class UpdateImageConfigJsonHandlerTest {
    @testSetup static void setup() {
        Schema.DescribeSObjectResult sObjDesc = Actions__c.sObjectType.getDescribe();
        Map<String, Schema.RecordTypeInfo> recTypes = sObjDesc.getRecordTypeInfosByDeveloperName();
        System.debug('>>>>>> recordTypes : '+recTypes);
        Actions__c action = new Actions__c(RecordTypeId=recTypes.get('Image_Carousel').getRecordTypeId(),
                                           Name='Test Image Carousel',
                                           Object__c='Home',
                                           Page_Type__c='Home');
        insert action;
    }
    public static testmethod void testUpdateJsonConfig(){
        Actions__c action = [select Id,Name,Image_Carousel_Config__c from Actions__c limit 1];
        System.assertEquals(null, action.Image_Carousel_Config__c,'Image JSON is not null');
        Carousel_Image__c img = new Carousel_Image__c(Name='Test',
                                                      Description__c='Test',
                                                      Image_Url__c='Test',
                                                      Actions__c=action.Id);
        insert img;
        action = [select Id,Name,Image_Carousel_Config__c from Actions__c limit 1];
        //System.assert(action.Image_Carousel_Config__c!=null, 'Image JSON is null');
        String expectJson = '[{"imgSrc":"Test","cardTitle":"Test","cardDescription":"Test"}]';
        //System.assertEquals(expectJson,action.Image_Carousel_Config__c, 'Image JSON not matching');
    }
    
    public static testmethod void testUpdateJsonConfigMultiple(){
        Actions__c action = [select Id,Name,Image_Carousel_Config__c from Actions__c limit 1];
        System.assertEquals(null, action.Image_Carousel_Config__c,'Image JSON is not null');
        Carousel_Image__c img = new Carousel_Image__c(Name='Test',
                                                      Description__c='Test',
                                                      Image_Url__c='Test',
                                                      Actions__c=action.Id);
        insert img;
        img = new Carousel_Image__c(Name='Test2',
                                    Description__c='Test2',
                                    Image_Url__c='Test2',
                                    Actions__c=action.Id);
        insert img;
        action = [select Id,Name,Image_Carousel_Config__c from Actions__c limit 1];
        //System.assert(action.Image_Carousel_Config__c!=null, 'Image JSON is null');
        String expectJson = '[{"imgSrc":"Test","cardTitle":"Test","cardDescription":"Test"},{"imgSrc":"Test2","cardTitle":"Test2","cardDescription":"Test2"}]';
        //System.assertEquals(expectJson,action.Image_Carousel_Config__c, 'Image JSON not matching');
    }
    
    public static testmethod void testUpdateJsonConfigDelete(){
        Actions__c action = [select Id,Name,Image_Carousel_Config__c from Actions__c limit 1];
        System.assertEquals(null, action.Image_Carousel_Config__c,'Image JSON is not null');
        Carousel_Image__c img = new Carousel_Image__c(Name='Test',
                                                      Description__c='Test',
                                                      Image_Url__c='Test',
                                                      Actions__c=action.Id);
        insert img;
        img = new Carousel_Image__c(Name='Test2',
                                    Description__c='Test2',
                                    Image_Url__c='Test2',
                                    Actions__c=action.Id);
        insert img;
        action = [select Id,Name,Image_Carousel_Config__c from Actions__c limit 1];
        //System.assert(action.Image_Carousel_Config__c!=null, 'Image JSON is null');
        String expectJson = '[{"imgSrc":"Test","cardTitle":"Test","cardDescription":"Test"},{"imgSrc":"Test2","cardTitle":"Test2","cardDescription":"Test2"}]';
        //System.assertEquals(expectJson,action.Image_Carousel_Config__c, 'Image JSON not matching');

        delete img;
        action = [select Id,Name,Image_Carousel_Config__c from Actions__c limit 1];
        //System.assert(action.Image_Carousel_Config__c!=null, 'Image JSON is null');
        expectJson = '[{"imgSrc":"Test","cardTitle":"Test","cardDescription":"Test"}]';
        //System.assertEquals(expectJson,action.Image_Carousel_Config__c, 'Image JSON not matching');

    }

}