force-app/main/default/objects/Actions__c/Actions__c.object-meta.xml
<CustomObject>
    <description>Object that captures actions to be taken when the usr hits a specific URL/type of page.</description>
    <label>Actions</label>
    <nameField>
        <label>Guideme Actions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Actions__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Actions__c/fields/Page_Type__c.field-meta.xml
<CustomField>
    <fullName>Page_Type__c</fullName>
    <label>Page Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Record Home</fullName>
            </value>
            <value>
                <fullName>Record Detail</fullName>
            </value>
            <value>
                <fullName>Record Update</fullName>
            </value>
            <value>
                <fullName>Record Create</fullName>
            </value>
            <value>
                <fullName>Reports Home</fullName>
            </value>
            <value>
                <fullName>Dashboards Home</fullName>
            </value>
            <value>
                <fullName>Task home</fullName>
            </value>
            <value>
                <fullName>Task Detail From List</fullName>
            </value>
            <value>
                <fullName>Chatter</fullName>
            </value>
            <value>
                <fullName>Chatter Group Detail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Actions__c/fields/Record_Update_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Record_Update_Criteria__c</fullName>
    <label>Record Update Criteria</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Actions__c/recordTypes/Welcome_Mat.recordType-meta.xml
<RecordType>
    <fullName>Welcome_Mat</fullName>
    <active>true</active>
    <label>Welcome Mat</label>
</RecordType>

force-app/main/default/objects/Record_Criteria__c/Record_Criteria__c.object-meta.xml
<CustomObject>
    <label>Record Criteria</label>
    <nameField>
        <displayFormat>ARC-{000000}</displayFormat>
        <label>Record Criteria Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Record Criteria</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Record_Criteria__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Action</label>
    <referenceTo>Actions__c</referenceTo>
    <relationshipLabel>Record Criteria</relationshipLabel>
    <relationshipName>Record_Criteria</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Record_Criteria__c/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <label>Field Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Record_Criteria__c/fields/Field_Value__c.field-meta.xml
<CustomField>
    <fullName>Field_Value__c</fullName>
    <label>Field Value</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UpdateRecordJSONConfigHandlerTest.cls
@IsTest
public class UpdateRecordJSONConfigHandlerTest {
    @testSetup static void setup() {
        Schema.DescribeSObjectResult sObjDesc = Actions__c.sObjectType.getDescribe();
        Map<String, Schema.RecordTypeInfo> recTypes = sObjDesc.getRecordTypeInfosByDeveloperName();
        System.debug('>>>>>> recordTypes : '+recTypes);
        Actions__c action = new Actions__c(RecordTypeId=recTypes.get('Welcome_Mat').getRecordTypeId(),
                                                                           Name='Test Welcome Mat',
                                                                           Object__c='Home',
                                                                           Page_Type__c='Home');
        insert action;
    }
    public static testmethod void testUpdateJsonConfig(){
        Actions__c action = [select Id,Name,Record_Update_Criteria__c from Actions__c limit 1];
        System.assertEquals(null, action.Record_Update_Criteria__c,'1:Criteria Config JSON is not null');
        Record_Criteria__c criteria = new Record_Criteria__c(Field_Name__c='Test',
                                                                                             Field_Value__c='Test',
                                                                                             Action__c=action.Id);
        insert criteria;
        action = [select Id,Name,Record_Update_Criteria__c from Actions__c limit 1];
        //System.assert(action.Record_Update_Criteria__c!=null, '2:Criteria Config JSON JSON is null');
        String expectJson = '[{"fieldValue":"Test","fieldName":"Test"}]';
        //System.assertEquals(expectJson,action.Record_Update_Criteria__c, '3:Criteria Config JSON not matching');
    }
    
    public static testmethod void testUpdateJsonConfigMultiple(){
        Actions__c action = [select Id,Name,Record_Update_Criteria__c from Actions__c limit 1];
        System.assertEquals(null, action.Record_Update_Criteria__c,'4:Criteria Config JSON is not null');
        Record_Criteria__c criteria = new Record_Criteria__c(Field_Name__c='Test',
                                                                                             Field_Value__c='Test',
                                                                                             Action__c=action.Id);
        insert criteria;
        criteria = new Record_Criteria__c(Field_Name__c='Test2',
                                                          Field_Value__c='Test2',
                                                          Action__c=action.Id);
        insert criteria;
        action = [select Id,Name,Record_Update_Criteria__c from Actions__c limit 1];
        //System.assert(action.Record_Update_Criteria__c!=null, '5:Criteria Config JSON is null');
        String expectJson = '[{"fieldValue":"Test","fieldName":"Test"},{"fieldValue":"Test2","fieldName":"Test2"}]';
        system.debug('6: JSON =  '+action.Record_Update_Criteria__c);
        //System.assertEquals(expectJson,action.Record_Update_Criteria__c, '6:Criteria Config JSON not matching');
    }
    
    public static testmethod void testUpdateJsonConfigDelete(){
        Actions__c action = [select Id,Name,Record_Update_Criteria__c from Actions__c limit 1];
        System.assertEquals(null, action.Record_Update_Criteria__c,'4:Criteria Config JSON is not null');
        Record_Criteria__c criteria = new Record_Criteria__c(Field_Name__c='Test',
                                                                                             Field_Value__c='Test',
                                                                                             Action__c=action.Id);
        insert criteria;
        criteria = new Record_Criteria__c(Field_Name__c='Test2',
                                                          Field_Value__c='Test2',
                                                          Action__c=action.Id);
        insert criteria;
        action = [select Id,Name,Record_Update_Criteria__c from Actions__c limit 1];
        //System.assert(action.Record_Update_Criteria__c!=null, '5:Criteria Config JSON is null');
        String expectJson = '[{"fieldValue":"Test","fieldName":"Test"},{"fieldValue":"Test2","fieldName":"Test2"}]';
        system.debug('6: JSON =  '+action.Record_Update_Criteria__c);
        //System.assertEquals(expectJson,action.Record_Update_Criteria__c, '6:Criteria JSON not matching');

        delete criteria;
        action = [select Id,Name,Record_Update_Criteria__c from Actions__c limit 1];
        expectJson = '[{"fieldValue":"Test","fieldName":"Test"}]';
        system.debug('7: JSON =  '+action.Record_Update_Criteria__c);
        //System.assertEquals(expectJson,action.Record_Update_Criteria__c, '7:Delete Criteria Config JSON not matching');

    }
}