force-app/main/default/objects/Email_Template__mdt/Email_Template__mdt.object-meta.xml
<CustomObject>
    <label>Email Template</label>
    <pluralLabel>Email Templates</pluralLabel>
</CustomObject>

force-app/main/default/objects/Email_Template__mdt/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
                <default>true</default>
                <label>English</label>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
            <value>
                <fullName>Dutch</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Email_Template__mdt/fields/Template_Id__c.field-meta.xml
<CustomField>
    <fullName>Template_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Template Id</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Email_Template__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Free Trail</fullName>
                <default>true</default>
                <label>Free Trail</label>
            </value>
            <value>
                <fullName>Express Agreement</fullName>
            </value>
            <value>
                <fullName>Return Label</fullName>
            </value>
            <value>
                <fullName>Trial Acceptance</fullName>
            </value>
            <value>
                <fullName>Return Label - Remorse Refund</fullName>
            </value>
            <value>
                <fullName>Return Label - Warranty/Exchange</fullName>
            </value>
            <value>
                <fullName>Return Label - Reminder Email</fullName>
            </value>
            <value>
                <fullName>Return Label - Second Reminder Email</fullName>
            </value>
            <value>
                <fullName>Free Trial Return</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TemplateSelectionHelper.cls
public without sharing class TemplateSelectionHelper {

    public static Map<String, Id> getTemplates(String type){

        Map<String, Id> langugeTemplateIdMap = new Map<String, Id>();      
        List<Email_Template__mdt> templateCustomData = [SELECT Language__c, Template_Id__c from Email_Template__mdt where Type__c =: type];

        for(Email_Template__mdt template : templateCustomData){
            langugeTemplateIdMap.put(template.Language__c, template.Template_Id__c);
        }

        return langugeTemplateIdMap;
    }

}