force-app/main/default/objects/gslib_Log__e/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <label>Class Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/gslib_Log__e/fields/Context_User__c.field-meta.xml
<CustomField>
    <fullName>Context_User__c</fullName>
    <label>Context User</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/gslib_Log__e/fields/Exception_Message__c.field-meta.xml
<CustomField>
    <fullName>Exception_Message__c</fullName>
    <description>The exception message</description>
    <label>Exception Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/gslib_Log__e/fields/Exception_Type__c.field-meta.xml
<CustomField>
    <fullName>Exception_Type__c</fullName>
    <description>The logged exception type.</description>
    <label>Exception Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/gslib_Log__e/fields/LogLevel__c.field-meta.xml
<CustomField>
    <fullName>LogLevel__c</fullName>
    <label>Log Level</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/gslib_Log__e/fields/Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Method_Name__c</fullName>
    <label>Method Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/gslib_Log__e/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Response</label>
    <length>131071</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/gslib_Log__e/fields/Session_Key__c.field-meta.xml
<CustomField>
    <fullName>Session_Key__c</fullName>
    <label>Session Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/gslib_Log__e/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <description>The exception stack trace.</description>
    <label>Stack Trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/gslib_Log__e/fields/Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Timestamp__c</fullName>
    <description>The log timestamp.</description>
    <label>Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Samsara Log</label>
    <nameField>
        <displayFormat>LOG-{0000}</displayFormat>
        <label>Samsara Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Samsara Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/Context_User__c.field-meta.xml
<CustomField>
    <fullName>Context_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Context User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Samsara_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/ExceptionMessage__c.field-meta.xml
<CustomField>
    <fullName>ExceptionMessage__c</fullName>
    <label>Exception Message</label>
    <length>131071</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/LogLevel__c.field-meta.xml
<CustomField>
    <fullName>LogLevel__c</fullName>
    <label>Log Level</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <description>This is used to log object other than exception passed to the logger framework</description>
    <label>Record Informations</label>
    <length>131071</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Severity__c.field-meta.xml
<CustomField>
    <fullName>Severity__c</fullName>
    <label>Severity</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/StackTrace__c.field-meta.xml
<CustomField>
    <fullName>StackTrace__c</fullName>
    <label>Stack Trace</label>
    <length>131071</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/gslib_LogService.cls
/**
 * Created by vikasmishra on 2021-07-14.
 */

public with sharing class gslib_LogService implements IService{

    @TestVisible
    static gslib_ILoggerAppender thisAppender = new Samsara_DatabaseAppender();
    public void processLogEvents(List<gslib_Log__e> eventList){
        List<Log__c> thisLogList = new List<Log__c>();
        for(gslib_Log__e thisLogEvent : eventList){
            thisLogList.add(getLogInstanceFromEventRecord(thisLogEvent));
        }
        thisAppender = new Samsara_DatabaseAppender(thisLogList);
        thisAppender.dispatch();
    }

    private Log__c getLogInstanceFromEventRecord(gslib_Log__e thisEvent){
        Log__c thisLog = new Log__c();
        thisLog.ClassName__c = thisEvent.Class_Name__c;
        thisLog.Method__c = thisEvent.Method_Name__c;
        thisLog.Context_User__c = thisEvent.Context_User__c;
        thisLog.Message__c = thisEvent.Message__c;
        thisLog.SessionKey__c = thisEvent.Session_Key__c;
        thisLog.StackTrace__c = thisEvent.Stack_Trace__c;
        thisLog.Timestamp__c = thisEvent.Timestamp__c;
        thisLog.LogLevel__c = thisEvent.LogLevel__c;
        thisLog.Severity__c = thisEvent.Severity__c;
        thisLog.ExceptionMessage__c = thisEvent.Exception_Message__c;
        thisLog.Exception_Type__c = thisEvent.Exception_Type__c;
        thisLog.Response__c = thisEvent.Response__c;
        return thisLog;
    }

    public interface IService{
        void processLogEvents(List<gslib_Log__e> eventList);
    }

}