force-app/main/default/objects/gslib_Log__e/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <label>Class Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/gslib_Log__e/fields/Context_User__c.field-meta.xml
<CustomField>
    <fullName>Context_User__c</fullName>
    <label>Context User</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/gslib_Log__e/fields/Exception_Message__c.field-meta.xml
<CustomField>
    <fullName>Exception_Message__c</fullName>
    <description>The exception message</description>
    <label>Exception Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/gslib_Log__e/fields/Exception_Type__c.field-meta.xml
<CustomField>
    <fullName>Exception_Type__c</fullName>
    <description>The logged exception type.</description>
    <label>Exception Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/gslib_Log__e/fields/LogLevel__c.field-meta.xml
<CustomField>
    <fullName>LogLevel__c</fullName>
    <label>Log Level</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/gslib_Log__e/fields/Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Method_Name__c</fullName>
    <label>Method Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/gslib_Log__e/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Response</label>
    <length>131071</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/gslib_Log__e/fields/Session_Key__c.field-meta.xml
<CustomField>
    <fullName>Session_Key__c</fullName>
    <label>Session Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/gslib_Log__e/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <description>The exception stack trace.</description>
    <label>Stack Trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/gslib_Log__e/fields/Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Timestamp__c</fullName>
    <description>The log timestamp.</description>
    <label>Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/gslib_Log__e/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <defaultValue>&quot;Error&quot;</defaultValue>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Samsara_AsyncDatabaseAppender.cls
/**
 * Created by vikasmishra on 2021-07-14.
 * TODO: Retry logic for failed publish
 */

public with sharing class Samsara_AsyncDatabaseAppender implements gslib_ILoggerAppender{

    List<gslib_Log__e> logs ;
    public Samsara_AsyncDatabaseAppender() {
        logs = new List<gslib_Log__e>();
    }
    public void log(gslib_Log log, Object obj) {
        logs.add(mapGSLIBLogToLogEvent(log, obj));
    }

    public void dispatch() {
        try {
            List<Database.SaveResult> saveResults = EventBus.publish(this.logs);
            logs = new List<gslib_Log__e>();
            // Print debug publishing statistics.
            printStatistics(saveResults);
        } catch (Exception ex) {
            System.debug(LoggingLevel.WARN, 'Logger Framework. Error publishing logs events. Error: ' +
                    ex.getMessage());
        }
    }

    private static void printStatistics(List<Database.SaveResult> saveResults) {
        Integer totalSuccess = 0;
        Integer totalFailed = 0;
        for (Database.SaveResult saveResult : saveResults) {
            if (saveResult.isSuccess()) {
                totalSuccess++;
            } else {
                for (Database.Error error : saveResult.errors) {
                    System.debug(LoggingLevel.FINE, 'Error on insert log: ' + error.message);
                }
                totalFailed++;
            }
        }
        System.debug(LoggingLevel.DEBUG, ' statistics => Success: ' +
                totalSuccess + ' | Failed: ' + totalFailed);
    }

    /**
     * @description Gets the log info list and flushes the log cache.
     * @return The log event instance with data mapped from the given  gslibLog.
     */
    private gslib_Log__e mapGSLIBLogToLogEvent(gslib_Log log, Object obj) {
        Exception ex ;
        Object MVP ;
        if(obj == null){
            //Do nothing
        }
        else if( obj instanceof SamsaraLoggerObjectMVP){
            SamsaraLoggerObjectMVP thisObjectMVP = (SamsaraLoggerObjectMVP) obj;
            ex = thisObjectMVP.exceptionObject != null && thisObjectMVP.exceptionObject instanceof Exception ? (Exception) thisObjectMVP.exceptionObject : null;
            MVP = thisObjectMVP.MVP;
        }
        else if( obj instanceof Exception ){
            ex = obj != null && obj instanceof Exception ? (Exception) obj : null;
        }
        else{
            MVP = obj;
        }

        return new gslib_Log__e(
                Class_Name__c = log.className,
                Method_Name__c = log.method,
                Type__c = log.type,
                Severity__c = String.valueOf(log.severity),
                Message__c = log.message.left(255),
                Response__c = MVP !=null ? String.valueOf(MVP).left(131071) : null,
                Context_User__c = log.contextUser,
                Session_Key__c = log.sessionKey,
                Timestamp__c = System.now(),
                LogLevel__c = log.logLevel.name(),
                Exception_Message__c = ex == null ? null : ex.getMessage(),
                Exception_Type__c = ex == null ? null : String.valueOf(ex),
                Stack_Trace__c = ex == null ? log.stackTrace : ex.getStackTraceString().left(32768)
        );
    }




}