force-app/main/default/objects/Rollup_Switch__mdt/Rollup_Switch__mdt.object-meta.xml
<CustomObject>
    <label>Rollup Switch</label>
    <pluralLabel>Rollup Switches</pluralLabel>
</CustomObject>

force-app/main/default/objects/Rollup_Switch__mdt/fields/Aggregate_Result_Field__c.field-meta.xml
<CustomField>
    <fullName>Aggregate_Result_Field__c</fullName>
    <label>Aggregate Result Field</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rollup_Switch__mdt/fields/Child_Object__c.field-meta.xml
<CustomField>
    <fullName>Child_Object__c</fullName>
    <label>Child Object</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RollUpSwitchService.cls
/**
 * @author Groundswell - Vikasm - vikas@gscloudsolutions.com
 * @date 2020-09-03
 * @lastModified 2020-09-08
 */
public with sharing class RollUpSwitchService 
{
    
 public static List<Rollup_Switch__mdt> rollUpList{
        get{
            if(rollUpList == null){
               rollUpList  = Rollup_Switch__mdt.getAll()?.values(); 
                if(rollUpList == null){
                   rollUpList = new List<Rollup_Switch__mdt>(); 
                }
            } 

            return rollUpList;
        }
        set{ rollUpList = value; }
    }   
   public static Map<String,Rollup_Switch__mdt> getRollupSwitchMetadata(String parentObject, String ChildObject)
   {
        
        Map<String,Rollup_Switch__mdt> mapOFRollupFieldVsMetadata = new  Map<String,Rollup_Switch__mdt> ();
       
         for(Rollup_Switch__mdt rollupSwitchMdt:rollUpList)                                          
        {
            if(rollupSwitchMdt.Active__c == true && rollupSwitchMdt.MasterLabel == parentObject && rollupSwitchMdt.Child_Object__c == ChildObject ){
                  mapOFRollupFieldVsMetadata.put(rollupSwitchMdt.Aggregate_Result_Field__c, rollupSwitchMdt);   
            }

        }

        return mapOFRollupFieldVsMetadata;
   } 
}