force-app/main/default/objects/SamsaraLogEntries__c/SamsaraLogEntries__c.object-meta.xml
<CustomObject>
    <label>Samsara Log Entries</label>
    <nameField>
        <displayFormat>LogEntry-{0000}</displayFormat>
        <label>Samsara Log Entries Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Samsara Log Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SamsaraLogEntries__c/fields/CPU_Time__c.field-meta.xml
<CustomField>
    <fullName>CPU_Time__c</fullName>
    <description>Captures the CPU time taken by the process</description>
    <label>CPU Time (in ms)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SamsaraLogEntries__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NONE</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
                <label>⛔ ERROR</label>
            </value>
            <value>
                <fullName>WARN</fullName>
                <label>⚠️ WARN</label>
            </value>
            <value>
                <fullName>INFO</fullName>
                <label>ℹ️ INFO</label>
            </value>
            <value>
                <fullName>DEBUG</fullName>
                <label>🐞 DEBUG</label>
            </value>
            <value>
                <fullName>FINE</fullName>
                <label>👍 FINE</label>
            </value>
            <value>
                <fullName>FINER</fullName>
                <label>👌 FINER</label>
            </value>
            <value>
                <fullName>FINEST</fullName>
                <label>🌟 FINEST</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SamsaraLogEntries__c/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <description>Related record id of the logging if applicable</description>
    <label>RecordId</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SamsaraLogEntries__c/fields/sourceApiName__c.field-meta.xml
<CustomField>
    <fullName>sourceApiName__c</fullName>
    <label>Source API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SamsaraLogEntries__c/fields/SourceMetadataType__c.field-meta.xml
<CustomField>
    <fullName>SourceMetadataType__c</fullName>
    <label>Source Metadata Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FlowCpuLogger.cls
public with sharing class FlowCpuLogger {
    // Static variable to temporarily hold start time during one transaction
    public static Long startCpuTime;
    public static set<string> logExecution = new set<string>();

    public class CpuTrackingInput {
        @InvocableVariable(required=true description='Action type: START or END')
        public String action;
        @InvocableVariable(description='Opportunity Record/SObject Record')
        public Id objId; 
        @InvocableVariable(description='Functionality Name')
        public String functionalityName;
    }

    @InvocableMethod(label='CPU Time Tracker' description='Tracks Apex CPU time for a Flow. Use START or END as action.')
    public static void trackCpuTime(List<CpuTrackingInput> requests) {
        SamsaraLogEntries__c log = new SamsaraLogEntries__c(); 
        Long usedCpu;
        Set<Id> sobjIds = new Set<id>();
        for (CpuTrackingInput req : requests) {
            if (req.action == null) continue;
            
            String actionType = req.action.trim().toUpperCase();

            if (actionType == 'START') {
                startCpuTime = Limits.getCpuTime();
            } 
            else if (actionType == 'END' && startCpuTime != Limits.getCpuTime()) {
                usedCpu = (startCpuTime != null) ? (Limits.getCpuTime() - startCpuTime) : Limits.getCpuTime();
                
                if(usedCpu != null){
                    Logger logRec = new Logger();
                    Logger.LogContext logContext = logRec.createLogContext((System.LoggingLevel.INFO));
                    log.RecordId__c = req.objId;
                    log.sourceApiName__c = req.functionalityName==null ? 'Flow' : req.functionalityName;
                    log.SourceMetadataType__c = 'Flow';
                    log.CPU_Time__c = usedCpu;
                    log.Level__c = 'INFO';
                    logContext.stageLog(log);
                    sobjIds.add(req.objId);
                }
            }
        }

        try{
            Logger.setRecordIds(sobjIds);
            Logger.insertMasterLogs();
        }catch(Exception e) {
                LOGGER.atError().setClassName('FlowCPULogger').setExceptionOrMessage(e);
                Logger.setFunctionalityType('Flow'); 
                Logger.insertMasterLogs();
            }
        }
    }