force-app/main/default/objects/acideasULT__brIdea__c/acideasULT__brIdea__c.object-meta.xml
<CustomObject>
    <description>Main object used for creating ideas in AC Ultimate Ideas</description>
    <label>AC Idea</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AC Ideas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/acideasULT__brIdea__c/fields/acideasULT__brIdea__c.field-meta.xml
<CustomField>
    <fullName>acideasULT__brIdea__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AC Idea</label>
    <referenceTo>acideasULT__brIdea__c</referenceTo>
    <relationshipLabel>AC Ideas</relationshipLabel>
    <relationshipName>brIdeas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/acideasULT__brIdea__c/fields/acideasULT__brZone__c.field-meta.xml
<CustomField>
    <fullName>acideasULT__brZone__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>AC Zone</label>
    <referenceTo>acideasULT__brZone__c</referenceTo>
    <relationshipLabel>AC Ideas</relationshipLabel>
    <relationshipName>brIdeas</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/acideasULT__brZone__c/acideasULT__brZone__c.object-meta.xml
<CustomObject>
    <description>Represents a zone that contains AC Idea object</description>
    <label>Idea Zone</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ideas Zones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/FeedItemTriggerHandlerHelper_Test.cls
@isTest(SeeAllData=true)
public class FeedItemTriggerHandlerHelper_Test {
	@isTest
    static void CreateTestAllUsers(){
        /*acideasULT__brZone__c zone = [SELECT Id from acideasULT__brZone__c WHERE Name = 'Samsara Default FR Zone'];
        acideasULT__brIdea__c fr = new acideasULT__brIdea__c();
        fr.Name = 'Samsara Default FR Zone';
        fr.acideasULT__brZone__c = zone.Id;
        insert fr;*/
        acideasULT__brIdea__c fr = [SELECT Id FROM acideasULT__brIdea__c where RecordType.Name = 'Internal Feature Request' limit 1];
        FeedItem fi = new FeedItem();
        fi.Body='@Shravan Govindaraja test';
        fi.Status = 'Published';
        //fi.Visibility = 'AllUsers';
        fi.Type = 'TextPost';
        fi.NetworkScope='AllNetworks';
        fi.ParentId = fr.Id;
        insert fi;
        FeedItemTriggerHandlerHelper.getChatterMentionSlackId(New List<Id>{fi.Id});
    }
    @isTest
    static void CreateTestInternalUsers(){
        /*acideasULT__brZone__c zone = [SELECT Id from acideasULT__brZone__c WHERE Name = 'Samsara Default FR Zone'];
        acideasULT__brIdea__c fr = new acideasULT__brIdea__c();
        fr.Name = 'Samsara Default FR Zone';
        fr.acideasULT__brZone__c = zone.Id;
        insert fr;*/
        acideasULT__brIdea__c fr = [SELECT Id FROM acideasULT__brIdea__c where RecordType.Name = 'Internal Feature Request' limit 1];
        FeedItem fi = new FeedItem();
        fi.Body='@Shravan Govindaraja test';
        fi.Status = 'Published';
        fi.Visibility = 'InternalUsers';
        fi.Type = 'TextPost';
        fi.NetworkScope='AllNetworks';
        fi.ParentId = fr.Id;
        insert fi;
        FeedItemTriggerHandlerHelper.getChatterMentionSlackId(New List<Id>{fi.Id});
        FeedItemTriggerHandlerHelper SlackUserIds;
    }
    /*10:36:17:395 USER_DEBUG [4]|DEBUG|feeditem FeedItem:{Id=null, ParentId=aDJS00000008h1DOAQ, Type=TextPost, 
        CreatedById=null, CreatedDate=null, IsDeleted=false, LastModifiedDate=null, SystemModstamp=null, CommentCount=null, 
        LikeCount=null, Title=null, Body=@Shravan Govindaraja test, LinkUrl=null, IsRichText=false, RelatedRecordId=null, InsertedById=null, 
        NetworkScope=AllNetworks, Visibility=AllUsers, BestCommentId=null, HasContent=false, 
        HasLink=false, HasFeedEntity=false, HasVerifiedComment=false, IsClosed=false, Status=Published}*/
}