force-app/main/default/objects/acideasULT__brIdea__c/acideasULT__brIdea__c.object-meta.xml
<CustomObject>
    <description>Main object used for creating ideas in AC Ultimate Ideas</description>
    <label>AC Idea</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AC Ideas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/acideasULT__brIdea__c/fields/acideasULT__brIdea__c.field-meta.xml
<CustomField>
    <fullName>acideasULT__brIdea__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AC Idea</label>
    <referenceTo>acideasULT__brIdea__c</referenceTo>
    <relationshipLabel>AC Ideas</relationshipLabel>
    <relationshipName>brIdeas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/acideasULT__brIdeaSubscription__c/acideasULT__brIdeaSubscription__c.object-meta.xml
<CustomObject>
    <description>Store users which were subscribed to an idea</description>
    <label>Idea Subscription</label>
    <nameField>
        <displayFormat>IS-{000000}</displayFormat>
        <label>Subscription Num</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ideas Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/acideasULT__brIdeaSubscription__c/fields/acideasULT__brIdea__c.field-meta.xml
<CustomField>
    <fullName>acideasULT__brIdea__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AC Idea</label>
    <referenceTo>acideasULT__brIdea__c</referenceTo>
    <relationshipLabel>Ideas Subscriptions</relationshipLabel>
    <relationshipName>Ideas_Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/acideasULT__brIdeaSubscription__c/fields/acideasULT__User__c.field-meta.xml
<CustomField>
    <fullName>acideasULT__User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>IdeasSubscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LeanData__Round_Robin_Schedule_Setting__c/LeanData__Round_Robin_Schedule_Setting__c.object-meta.xml
<CustomObject>
    <label>Schedule Setting</label>
    <nameField>
        <label>Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LeanData__Round_Robin_Schedule_Setting__c/fields/LeanData__Vacation_User__c.field-meta.xml
<CustomField>
    <fullName>LeanData__Vacation_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vacation User</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>User</relationshipLabel>
    <relationshipName>User</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FR_IdeaSubcriptions.cls
/**********************************************************************
Name: FR_IdeaSubcriptions
Test Class: FR_IdeaSubcriptions_Test
=======================================================================
Purpose: This class contains the logic to fetch feature request subscriber emails of CE/SE profiles                                                       
=======================================================================
History  

VERSION     AUTHOR               			DATE               DETAIL                       
1.0        vijaychandra AMARANENI        2023-Aug-28        INITIAL DEVELOPMENT FOR GTMS-14263

***********************************************************************/
public class FR_IdeaSubcriptions {
	/*****************************************8
	 * @Description:this method will be called from Feature_Request_After_Update flow to send emails to subscribers
	 * @Param : frIdList - feature request record i
	 * @return : this method will return the list of subscribers emails  
	*/
    @InvocableMethod(label='Fetch Idea Subscription records' description='fetching user subscription records related to idea')
    public static List<List<String>> fetchSubscriberEmails(List<String> frIdList){
        string profileIds = System.Label.FR_Subs_CE_SE_Profile_Ids;//profile ids stored in custom label
        List<String> cs_se_profileIds = profileIds.split(';');//splitting profile ids to list
        List<string> userIdList = new List<string>();
        for(acideasULT__brIdeaSubscription__c subscription:[SELECT Id,acideasULT__User__c,acideasULT__User__r.Email FROM acideasULT__brIdeaSubscription__c WHERE acideasULT__brIdea__c IN :frIdList AND acideasULT__User__r.Profile.UserType ='Standard' AND acideasULT__User__r.ProfileId IN :cs_se_profileIds]){
            userIdList.add(subscription.acideasULT__User__r.Email);
        }
        
        return new List<List<String>>{userIdList};
    }
}