force-app/main/default/objects/Order/fields/Shipping_Contact__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request_Tracker__c/Request_Tracker__c.object-meta.xml
<CustomObject>
    <label>Request Tracker</label>
    <nameField>
        <displayFormat>RT-{0000}</displayFormat>
        <label>Request Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request Tracker</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Request_Tracker__c/fields/Shipping_Address_Id__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Address_Id__c</fullName>
    <label>Shipping Address Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipping_Address__c/Shipping_Address__c.object-meta.xml
<CustomObject>
    <label>Shipping Address</label>
    <nameField>
        <label>Shipping Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipping Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipping_Address__c/fields/Shipping_Contact__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Shipping Addresses</relationshipLabel>
    <relationshipName>Shipping_Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/InsertShippingAddress.cls
public class InsertShippingAddress extends QueueableChainJob {
    private Request_Tracker__c tracker;
    private OrderPayload payload;
    private String stepStatus;
    
    public InsertShippingAddress(Request_Tracker__c tracker, String stepStatus, OrderPayload payload, Integer retryCount) {
        super(retryCount, stepStatus, tracker);
        this.tracker = tracker;
        this.payload = payload;
        this.stepStatus = stepStatus;
    }
    
    public override void processJob() {
        createLog('Started processing: Insert ShippingAddress Job.');
        OrderUtil.initializeUnitOfWork();

        // Define all old records
        Shipping_Address__c oldShippingAddress = OrderProcessorSingleton.getInstance().queryShippingAddress(payload);
        
        if (oldShippingAddress != null && String.isNotBlank(oldShippingAddress.Id)) {
            createLog('Shipping Address already exists. Skipping creation.'+oldShippingAddress.Id);
            tracker.Shipping_Address_Id__c = oldShippingAddress.Id;
            return ;
        }

        // Create new Shipping Address
        Shipping_Address__c shippingAddress = processShippingAddress();
        if (shippingAddress == null) {
            createLog('No Shipping Address created. Ending job.');
            return;
        }
        
        DMLWrapper.publishDML();
        
        // Update tracker with shipping address ID after DML 
        tracker.Shipping_Address_Id__c = shippingAddress?.Id;
        
        createLog('Finished processing: Create Shipping Address.'+shippingAddress?.Id);
    }
    
    private Shipping_Address__c processShippingAddress() {
        Shipping_Address__c newAddress = JsonToSFDCMapper.mapShippingAddress(payload);
        
        if (newAddress == null) {
            createLog('Shipping Address mapping returned null. Skipping creation.');
            return null;
        }
        
        Contact cnt = OrderProcessorSingleton.getInstance().queryContact(payload.order.account_id); 
        if (cnt != null) {
            newAddress.Shipping_Contact__c = cnt.Id;
            createLog('Mapped Contact to Shipping Address: ' + cnt.Id);
        } else {
            createLog('No Contact found for AccountId: ' + payload.order.account_id);
        }
        
        DMLWrapper.doInsert(newAddress);
        return newAddress;
    }
    
    @TestVisible
    protected override Queueable newInstanceWithRetry(Integer retryCount) {
        return new InsertShippingAddress(tracker, stepStatus, payload, retryCount);
    }
    
    private void createLog(String logMessage) {
        transactionFinalizer.createLog(stepStatus + ': Info', logMessage, DateTime.now(), DateTime.now());
    }
}