force-app/main/default/objects/Order/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>In Fulfillment</fullName>
            </value>
            <value>
                <fullName>Fulfilled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Return Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Registration__c/Partner_Registration__c.object-meta.xml
<CustomObject>
    <description>created for GTMS-20584</description>
    <label>Partner Registration</label>
    <nameField>
        <displayFormat>PR-{000000}</displayFormat>
        <label>Partner Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Registrations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Registration__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Partner Registrations</relationshipLabel>
    <relationshipName>Partner_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Registration__c/fields/Owner_Manager__c.field-meta.xml
<CustomField>
    <fullName>Owner_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>created for GTMS-28939</description>
    <label>Owner Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Partner_Registrations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Registration__c/fields/PAM_Review_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>PAM_Review_Date_Time__c</fullName>
    <description>created for GTMS-28939</description>
    <label>PAM Review Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Partner_Registration__c/fields/SLA_Business_Days__c.field-meta.xml
<CustomField>
    <fullName>SLA_Business_Days__c</fullName>
    <description>created for GTMS-28939</description>
    <label>SLA Business Days</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
            <value>
                <fullName>45</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Registration__c/fields/SLA_Due_DateTime__c.field-meta.xml
<CustomField>
    <fullName>SLA_Due_DateTime__c</fullName>
    <description>created for GTMS-28939</description>
    <label>SLA Due DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Partner_Registration__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>PAM Reviewed</fullName>
            </value>
            <value>
                <fullName>PAM Approved</fullName>
            </value>
            <value>
                <fullName>PAM Denied</fullName>
            </value>
            <value>
                <fullName>AE Accepted</fullName>
            </value>
            <value>
                <fullName>AE Approved</fullName>
            </value>
            <value>
                <fullName>AE Denied</fullName>
            </value>
            <value>
                <fullName>AE Ignored</fullName>
            </value>
            <value>
                <fullName>New Application</fullName>
            </value>
            <value>
                <fullName>Under Review</fullName>
            </value>
            <value>
                <fullName>Approved by PAM</fullName>
            </value>
            <value>
                <fullName>Approved by Leaders</fullName>
            </value>
            <value>
                <fullName>New User Registration</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Denied at Closing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Subscription__c/SBQQ__Subscription__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__Contract__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contract that governs this subscription.</description>
    <inlineHelpText>Contract that governs this subscription.</inlineHelpText>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__EndDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__EndDate__c</fullName>
    <description>The last date this contract is valid.</description>
    <formula>if ( ISBLANK (SBQQ__SubscriptionEndDate__c), SBQQ__Contract__r.EndDate, SBQQ__SubscriptionEndDate__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The last date this contract is valid.</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SLA_Holiday__c/SLA_Holiday__c.object-meta.xml
<CustomObject>
    <description>created for GTMS-28939</description>
    <label>SLA Holiday</label>
    <nameField>
        <displayFormat>HOL-{000000}</displayFormat>
        <label>SLA Holiday Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SLA Holidays</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SLA_Holiday__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Address_Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SLA_Holiday__c/fields/Holiday_Date__c.field-meta.xml
<CustomField>
    <fullName>Holiday_Date__c</fullName>
    <label>Holiday Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SLA_Holiday__c/fields/Holiday_Name__c.field-meta.xml
<CustomField>
    <fullName>Holiday_Name__c</fullName>
    <label>Holiday Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Address_Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia, Plurinational State of</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Bouvet Island</fullName>
    </customValue>
    <masterLabel>Address: Country</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PartnerRegistrationHelper.cls
/**********************************************************************
Name: PartnerRegistrationHelper
=======================================================================
Purpose: This class will logic to related to partner registration functionality                                                        
=======================================================================
History  

VERSION     AUTHOR               DATE               DETAIL                       
1.0        Rodrigo Carpio        2024-Jul-17        INITIAL DEVELOPMENT 
1.1.       Rodrigo Carpio.       2025-Aug-21.       added logic for GTMS-28939
**********************************************************************/
public class PartnerRegistrationHelper {
    private static Map<Id, User> ownerInfoMaps = null;
    private static void getOwnerInfo(Set<Id> userIds){
        if(ownerInfoMaps == null || !(ownerInfoMaps.keySet().containsAll(userIds))){
            ownerInfoMaps = new Map<Id, User>([SELECT Email, UserRole.Name,ManagerId,Manager.ManagerId
                                          FROM User where Id IN : userIds]);
        }
    }
    /*
     * added for GTMS-28939 this method hanldes before update logic
    */
    public static void handleBeforeUpdate(List<Partner_Registration__c> newPartnerRegistrationList, Map<Id, Partner_Registration__c> oldPartnerRegistrationMap) 
    {
        // get Owner infomation
        Set<Id> ownerIdSet = new Set<Id>();
        for (Partner_Registration__c record : newPartnerRegistrationList) {
            ownerIdSet.add(record.OwnerId);
        }
        getOwnerInfo(ownerIdSet);
        
        for (Partner_Registration__c record : newPartnerRegistrationList) {
            Partner_Registration__c oldRecord = oldPartnerRegistrationMap.get(record.Id);
            // set PAM Review DateTime
            if((record.Status__c == 'PAM Reviewed' && oldRecord == null) || 
               (record.Status__c == 'PAM Reviewed' && oldRecord != null && oldRecord.Status__c != record.Status__c)
              )
                record.put('PAM_Review_Date_Time__c', DateTime.now()); 
            // set owner manager
            if (record != null && oldRecord.OwnerId != record.OwnerId)
                record.put('Owner_Manager__c', ownerInfoMaps.get(record.OwnerId).ManagerId); 
        }
    }
    /*
     * added for GTMS-28939 this method will perform the setting of SLA Due date
    */
    public static void updateSLADueDate(List<Partner_Registration__c> newPartnerRegistrationList, Map<Id, Partner_Registration__c> oldPartnerRegistrationMap) 
    {
        // get address type details
        List<Partner_Registration__c> prAddress = [SELECT Address__c FROM Partner_Registration__c WHERE Id IN:oldPartnerRegistrationMap.keySet()];
        Map<string, string> countryMap = new Map<string, string>();
        // get partner registration(s) address country
        for(Partner_Registration__c pr : prAddress) {
            Address addr = pr.Address__c;
            //system.debug('RODRIGO pr.Address__c ' + pr.Address__c);
            //system.debug('RODRIGO addr ' + addr);
            countryMap.put(addr.getCountry(),addr.getCountry());
            
        }
        //system.debug('RODRIGO countryMap ' + countryMap);
        /*// Query holiday data
        List<SLA_Holiday__c > holidayList = [SELECT Id, Holiday_Date__c, Holiday_Name__c FROM SLA_Holiday__c 
                                             WHERE Country__c IN: countryMap.keySet()
                                             ORDER BY Holiday_Date__c DESC LIMIT 1000];
        Map<String, SLA_Holiday__c> holidayMap = new Map<String, SLA_Holiday__c>();
        DateTime tempDate;
        Integer addedDays;
        system.debug('RODRIGO holidayList ' + holidayList);
        for (SLA_Holiday__c each : holidayList) {
            holidayMap.put(each.Holiday_Date__c.format(),each);
        }
        system.debug('RODRIGO holidayMap ' + holidayMap);
        */
        SLACalculationHelper sla = new SLACalculationHelper(countryMap.keySet());
        for (Partner_Registration__c record : newPartnerRegistrationList) {
            // get old map record
            
            // Calculate SLA Due DateTime if not set and SLA Business Days is provided
            /*if (record.get('SLA_Due_DateTime__c') == NULL && record.get('SLA_Business_Days__c') != NULL
               && oldPartnerRegistrationMap.get(record.Id) != null && oldPartnerRegistrationMap.get(record.Id).Status__c != record.Status__c
               && record.Status__c == 'PAM Reviewed')*/
            //system.debug('RODRIGO oldPartnerRegistrationMap ' + oldPartnerRegistrationMap);
            if ((record.SLA_Business_Days__c != NULL && record.Status__c == 'PAM Reviewed' && oldPartnerRegistrationMap.get(record.Id) != null)
                && (oldPartnerRegistrationMap.get(record.Id).Status__c != record.Status__c || 
                    oldPartnerRegistrationMap.get(record.Id).SLA_Business_Days__c != record.SLA_Business_Days__c))
            {
                datetime tempDate;
                //addedDays = 0;
                //tempDate = DateTime.now();
                //tempDate = record.PAM_Review_Date_Time__c;
                tempDate = sla.calculateSLADueDate(record.SLA_Business_Days__c, record.PAM_Review_Date_Time__c);
                record.SLA_Due_DateTime__c = tempDate;
            }
            
        }

    }
    
    public class AmendedContractInput {
        @InvocableVariable public string contractId;
        @InvocableVariable public string partnerRegistrationId;
    }
    public class AmendedContractDetails {
        @InvocableVariable public string quoteId;
        @InvocableVariable public string opportunityId;
        @InvocableVariable public string partnerRegistrationId;
        @InvocableVariable public boolean asyncModeAmend;
    }
    
    @InvocableMethod(label='Amend Contract' description='Amend Contract')
    public static List<AmendedContractDetails> AmendContract(List<AmendedContractInput> contractInput){
        return initiateAmendContract(contractInput);
    }
    
    private static List<AmendedContractDetails> initiateAmendContract(List<AmendedContractInput> contractInput) {
        List<AmendedContractDetails> results = new List<AmendedContractDetails>();
        List<SBQQ__Subscription__c> subsList = new List<SBQQ__Subscription__c>();
        Map<Id, Id> ContractPRMap = new Map<Id, Id>();
        Map<Id, AmendedContractInput> ContractInputMap = new Map<Id, AmendedContractInput>();
        Map<Id, Id> ContractPRMapToProcess = new Map<Id, Id>();
        Map<Id, AmendedContractInput> ContractInputMapToProcess = new Map<Id, AmendedContractInput>();
        Set<Id> listContractId = new Set<Id>();
        
        //listContractId.add('8004p000000RdTAAA0');
        // loop thru all input details 
        FOR(AmendedContractInput input : contractInput) {
            listContractId.add(input.contractId);
            ContractPRMap.put(input.contractId, input.partnerRegistrationId);
            ContractInputMap.put(input.contractId, input);
        }
        //system.debug('RODRIGO listContractId '+listContractId);
        AggregateResult[] groupedResults
            = [SELECT SBQQ__Contract__c, Count(Id)
               FROM SBQQ__Subscription__c
               WHERE SBQQ__EndDate__c > TODAY AND SBQQ__Contract__c IN: listContractId
               GROUP BY SBQQ__Contract__c];
        //system.debug('RODRIGO groupedResults'+groupedResults);
        
        for (AggregateResult ar : groupedResults)  {
            //System.debug('RODRIGO Campaign ID' + ar.get('SBQQ__Contract__c'));
            //System.debug('RODRIGO Average amount' + ar.get('expr0'));
            string contractId = string.valueOf(ar.get('SBQQ__Contract__c'));
            if ((Test.isRunningTest() && Integer.valueOf(ar.get('expr0')) > 1) || (Integer.valueOf(ar.get('expr0')) > Integer.valueOf(System.Label.Partner_Registration_Subscription_Min_Count))) {
                //System.debug('RODRIGO ContractPRMapToProcess ' + ContractPRMap.get(contractId));
                ContractPRMapToProcess.put(contractId, ContractPRMap.get(contractId));
            }
            else {
                //System.debug('RODRIGO ContractInputMapToProcess ' + ContractInputMap.get(contractId));
                ContractInputMapToProcess.put(contractId, ContractInputMap.get(contractId));
            }
        }
        if (ContractPRMapToProcess != null && ContractPRMapToProcess.size()>0) {
            AmendedContractDetails result = new AmendedContractDetails();
            result.asyncModeAmend = true;
            results.add(result);
            performContractAmenderAsync(ContractPRMapToProcess);
        }
        else {
            results = performContractAmender(ContractInputMapToProcess.values());
        }
        return results;
    }
    
    @future
    private static Void performContractAmenderAsync(Map<Id, Id> contractIdMap) {
        List<AmendedContractInput> contractInput = new List<AmendedContractInput>();
        FOR (Id i : contractIdMap.keySet()) {
            AmendedContractInput input = new AmendedContractInput();
            input.contractId = i;
			input.partnerRegistrationId = contractIdMap.get(i);
            contractInput.add(input);
        }
        
        List<AmendedContractDetails> results = new List<AmendedContractDetails>();
        results = performContractAmender(contractInput);
        Set<Id> partnerRegistrationIds = new Set<Id>();
        Set<Id> opportunityIds = new Set<Id>();
        List<Partner_Registration__c> prForUpdate = new List<Partner_Registration__c>();
        // loop thru results to get Id
        FOR (AmendedContractDetails result : results) {
            partnerRegistrationIds.add(result.partnerRegistrationId);
            opportunityIds.add(result.opportunityId);
        }
        Map<Id, Partner_Registration__c> prMap = new Map<Id, Partner_Registration__c>([SELECT Id, OwnerId FROM Partner_Registration__c WHERE Id IN: partnerRegistrationIds]);
        Map<Id, Opportunity> optyMap = new Map<Id, Opportunity>([SELECT Id, Name, OwnerId FROM Opportunity WHERE Id IN: opportunityIds]);
        FOR(AmendedContractDetails result : results) {
            Partner_Registration__c pr = prMap.get(result.partnerRegistrationId);
            Opportunity opty = optyMap.get(result.opportunityId);
            String opptyId = (opty == null) ? 'ERROR ' : opty.id; 
            String opptyName = (opty == null) ? 'ERROR ' : opty.Name; 
            notifyUser(opptyId, opptyName, 'Amended Opportunity', pr.OwnerId);
            pr.Opportunity__c = result.opportunityId;
            prForUpdate.add(pr);
        }
        if (prForUpdate.size()>0)
            update prForUpdate;
    }
    @TestVisible
    private static List<AmendedContractDetails> performContractAmender(List<AmendedContractInput> contractIdInput) {
        List<AmendedContractDetails> results = new List<AmendedContractDetails>();
        for(AmendedContractInput i : contractIdInput){
            try
            {
                //system.debug('RODRIGO performContractAmender ' + i.contractId);
                String quoteJSON = SBQQ.ServiceRouter.load('SBQQ.ContractManipulationAPI.ContractAmender', i.contractId,null);
                //return (QuoteModel) JSON.deserialize(quoteJSON, QuoteModel.class);
                QuoteModel qm = (QuoteModel) JSON.deserialize(quoteJSON, QuoteModel.class);
                if(qm.record.id <> null){
                    List<SBQQ__Quote__c> newQuote = [SELECT Id,SBQQ__Opportunity2__c FROM SBQQ__Quote__c WHERE Id =: qm.record.id];
                    if(newQuote <> null && newQuote.size() > 0){
                        AmendedContractDetails result = new AmendedContractDetails();
                        result.quoteId = newQuote[0].id;
                        result.opportunityId = newQuote[0].SBQQ__Opportunity2__c;
                        result.partnerRegistrationId = i.partnerRegistrationId;
                        result.asyncModeAmend = false;
                        results.add(result);
                    }
                }
            } 
            catch(Exception q) {
                AmendedContractDetails result = new AmendedContractDetails();
                result.quoteId = null;
                result.opportunityId = null;
                result.partnerRegistrationId = i.partnerRegistrationId;
                result.asyncModeAmend = false;
                results.add(result);
            }
        }
        return results;
    }
    
    @testvisible
    private static void notifyUser(string oppyId, string opptyName, string opptyType, string prOwnerId) 
    {
        // Get the Id for our custom notification type
        CustomNotificationType notificationType = 
            [SELECT Id, DeveloperName 
             FROM CustomNotificationType 
             WHERE DeveloperName='Partner_Registration_Notification'];
        
        // Create a new custom notification
        Messaging.CustomNotification notification = new Messaging.CustomNotification();
        
        // Set the contents for the notification
        notification.setTitle(opptyType + ' Creation Notification');
        notification.setBody(opptyName + ' has been created');
        
        // Set the notification type and target
        notification.setNotificationTypeId(notificationType.Id);
        //notification.setTargetId(Userinfo.getUserId());
        notification.setTargetId(oppyId);
        // Actually send the notification
        try {
            //system.debug('RODRIGO about to send notification ' + Userinfo.getUserId());
            notification.send(new Set<String> { prOwnerId });
        }
        catch (Exception e) {
            System.debug('Problem sending notification: ' + e.getMessage());
        }
    }
    
}