force-app/main/default/objects/OpportunityContractAccount__c/OpportunityContractAccount__c.object-meta.xml
<CustomObject>
    <description>Used by Opportunity Contract Batch to record which Accounts were handled</description>
    <label>Opportunity Contract Account</label>
    <nameField>
        <displayFormat>A{0000000000}</displayFormat>
        <label>OpportunityContractAccount Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Contract Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityContractAccount__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunity Contract Accounts</relationshipLabel>
    <relationshipName>Opportunity_Contract_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OpportunityContractDeleteStage.cls
global class OpportunityContractDeleteStage implements Database.Batchable<sObject> {

    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'select Id, (select Id from Opportunities limit 1) from Account';
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<sObject> objects) {

        // get all account lookups in the staging object that lookup up to accounts that have opportunities
        // keep account lookups that do not have opportunties to optimize batch performance so that we aren't querying accounts that do not have opportunities
        Set<Id> accountIds = new Set<Id>();
        for (Account acct : (List<Account>) objects) {
            if (!acct.Opportunities.isEmpty()) {
                accountIds.add(acct.Id);
            }
        }

        delete [select Id from OpportunityContractAccount__c where Account__c IN :accountIds];
    }

    global void finish(Database.BatchableContext BC){}

}