force-app/main/default/objects/Api_Logger__c/Api_Logger__c.object-meta.xml
<CustomObject>
    <label>Api Logger</label>
    <nameField>
        <label>Api Logger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Api Logger</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Api_Logger__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <label>Transaction Type</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Request_Tracker__c/Request_Tracker__c.object-meta.xml
<CustomObject>
    <label>Request Tracker</label>
    <nameField>
        <displayFormat>RT-{0000}</displayFormat>
        <label>Request Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request Tracker</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Request_Tracker__c/fields/OrderId__c.field-meta.xml
<CustomField>
    <fullName>OrderId__c</fullName>
    <externalId>true</externalId>
    <label>OrderId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Request_Tracker__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <isActive>false</isActive>
                <label>Open</label>
            </value>
            <value>
                <fullName>Success</fullName>
                <isActive>false</isActive>
                <label>Success</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request_Tracker__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>WEBSTORE_ADD_ON_PURCHASE</fullName>
            </value>
            <value>
                <fullName>WEBSTORE_FIRST_PURCHASE</fullName>
            </value>
            <value>
                <fullName>WEBSTORE_COMMERCIAL_CHECKOUT_LINK</fullName>
            </value>
            <value>
                <fullName>WEBSTORE_DIGITAL_RENEWAL</fullName>
            </value>
            <value>
                <fullName>WEBSTORE_MIDMARKET_PLUS_CHECKOUT_LINK</fullName>
            </value>
            <value>
                <fullName>WEBSTORE_FREE_TRIAL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OrderService.cls
public class OrderService {
    
    // Save the Request Tracker record and return the Tracker ID
    public static Request_Tracker__c findRequestTrackerCount(String orderId) {
        if(String.isBlank(orderId)) return null;
        
        List<Request_Tracker__c> trackerList = [SELECT Id,Retry_Count__c FROM Request_Tracker__c WHERE OrderId__c = :orderId and Status__c!='Completed' LIMIT 1];
        return trackerList.isEmpty() ? null : trackerList[0];
    }
    
    // Save the Request Tracker record and return the Tracker ID
    public static Id saveRequestTracker(Request_Tracker__c requestTracker) {
        try {
            // Insert the Request Tracker record
            Database.UpsertResult upsertResult = Database.upsert(requestTracker);
            
            if (upsertResult.isSuccess()) {     
                // Log entry for the request
                createLogEntry(upsertResult.getId(), requestTracker.Transaction_Type__c, requestTracker.Status__c, OrderUtil.STEP_1 + ': Info');
                
                // Return the ID of the newly created Request Tracker record
                return upsertResult.getId();
            } else {
                throw new RequestTrackerException(OrderUtil.ERROR_SAVING_REQUEST);
            }
        } catch (DMLException ex) {
            throw new RequestTrackerException(OrderUtil.ERROR_DATABASE + ex.getMessage());
        } catch(Exception ex){
            throw new RequestTrackerException(ex.getMessage());
        }
    }
    
    // Create a log entry in the Api_Logger__c object
    public static void createLogEntry(Id requestTrackerId, String transactionType, String message,String stepStatus) {
        LogManager.log(requestTrackerId,transactionType,stepStatus,message,DateTime.now(), DateTime.now()); 
        LogManager.flushLogs();
    }
}