force-app/main/default/objects/Contract/fields/Contract_Renewable_ACV__c.field-meta.xml
<CustomField>
    <fullName>Contract_Renewable_ACV__c</fullName>
    <inlineHelpText>Sum of all expiring license ACV. Does not include HW or select products like…</inlineHelpText>
    <label>Contract Renewable ACV</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/SBQQ__Subscription__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__Contract__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contract that governs this subscription.</description>
    <inlineHelpText>Contract that governs this subscription.</inlineHelpText>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__CustomerPrice__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__CustomerPrice__c</fullName>
    <description>Price the end user paid for this subscription.</description>
    <inlineHelpText>Price paid for this subscription.</inlineHelpText>
    <label>Customer Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__Product__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product used to sell this subscription.</description>
    <inlineHelpText>Product used to sell this subscription.</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__Quantity__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quantity__c</fullName>
    <description>Quantity of this subscription product purchased by the customer.</description>
    <inlineHelpText>Quantity of this subscription product purchased by the customer.</inlineHelpText>
    <label>Quantity</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__RenewalPrice__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__RenewalPrice__c</fullName>
    <description>Define the price of quote lines that appear on the renewal quote when you renew this subscription. This field overrides the result of price calculations from your account’s renewal pricing method. If renewal pricing method is Uplift, uplift will be applied to the Renewal Price.</description>
    <inlineHelpText>Override the default calculated price of this subscription on a renewal quote. If your account&apos;s renewal pricing method is Uplift, the uplift applies to this renewal price.</inlineHelpText>
    <label>Renewal Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/Batch_UpdateContractRenewableACV.cls
/*
* @Author : Siddharth Kumar Mishra
* @Description : GTMS - 12367  -   Modify logic to account for negative lines
* @note : to run the batch class Database.executebatch((new Batch_UpdateContractRenewableACV()),1);
*/
public class Batch_UpdateContractRenewableACV implements Database.Batchable<sObject>,Database.Stateful
{
    //START METHOD
    public Database.QueryLocator start(Database.BatchableContext BC)
    { 
        String query = 'SELECT id,Contract_Renewable_ACV__c from Contract';
        //List<Id> testids = new List<Id>{'8001P000000cZQvQAM'};
        //String query = 'SELECT id,Contract_Renewable_ACV__c FROM Contract WHERE id in:testids';
        
        
        return Database.getQueryLocator(query);
    }
    
    //EXECUTE METHOD
    public void execute(Database.BatchableContext BC, List<Contract> contractList)
    {
        updateContracts(contractList);
    }
    
    //FINISH METHOD
    public void finish(Database.BatchableContext BC)
    { 
        
    }
    
    
    public void updateContracts(List<Contract> contractList)
    {       
        Map<id,list<SBQQ__Subscription__c>> contractidSubListMap = new Map<id,list<SBQQ__Subscription__c>>();
        //Map<Id,Contract> subIdContractMap = new Map<Id,Contract>();
        //Map<Id,Id> SubIdProductMap = new Map<Id,Id>();
        //Map<Id,decimal> SubIdQuantityMap = new Map<Id,decimal>();
        Map<Id,Map<String,List<SBQQ__Subscription__c>>> conIdProdCodeSubListMap = new Map<Id,Map<String,List<SBQQ__Subscription__c>>>();
        Map<Id,Map<String,Map<String,List<SBQQ__Subscription__c>>>> conIdProdCodeQuantSubListMap = new Map<Id,Map<String,Map<String,List<SBQQ__Subscription__c>>>>();
        Map<String,List<SBQQ__Subscription__c>> prodCodeSubListMap = new Map<String,List<SBQQ__Subscription__c>>();
        Map<String,List<SBQQ__Subscription__c>> PosOrNegQuantitySubListMap1 = new Map<String,List<SBQQ__Subscription__c>>();
        Map<String,List<SBQQ__Subscription__c>> PosOrNegQuantitySubListMap2 = new Map<String,List<SBQQ__Subscription__c>>();
        
        List<Contract> contractsList = new List<Contract>();
        List<Id> contractIdsList = new List<Id>();
        for(contract c: contractList)
        {
            contractIdsList.add(c.id);
            
        }
        List<SBQQ__Subscription__c> sbqqSubscriptionList = [Select id,SBQQ__Quantity__c,SBQQ__RenewalPrice__c,SBQQ__CustomerPrice__c,SBQQ__Contract__c,SBQQ__Product__r.ProductCode,createdDate from SBQQ__Subscription__c WHERE SBQQ__Contract__c IN:contractIdsList order by CreatedDate desc];
        if(sbqqSubscriptionList!=null && sbqqSubscriptionList.size()>0)
        {
            for(SBQQ__Subscription__c s:sbqqSubscriptionList)
            {
                List<SBQQ__Subscription__c> subsList = new List<SBQQ__Subscription__c>();
                if(!contractidSubListMap.containsKey(s.SBQQ__Contract__c))
                {
                    contractidSubListMap.put(s.SBQQ__Contract__c,new List<SBQQ__Subscription__c>{s});
                }
                else 
                {
                    contractidSubListMap.get(s.SBQQ__Contract__c).add(s);
                }
            }
            
            contractsList = [Select id,Contract_Renewable_ACV__c from Contract where id in:contractidSubListMap.KeySet()];
            PosOrNegQuantitySubListMap2.put('POSITIVE',new List<SBQQ__Subscription__c>());
            PosOrNegQuantitySubListMap2.put('NEGATIVE',new List<SBQQ__Subscription__c>());
            for(Contract Con : contractsList)
            {
                Map<String,Map<String,List<SBQQ__Subscription__c>>> tempMap2 = new Map<String,Map<String,List<SBQQ__Subscription__c>>>();
                for(SBQQ__Subscription__c s:contractidSubListMap.get(Con.id))
                {
                    System.debug('s.SBQQ__Quantity__c ---->'+s.SBQQ__Quantity__c);
                    if(s.SBQQ__Quantity__c > 0)
                    {
                        
                        if(!tempMap2.containsKey(s.SBQQ__Product__r.ProductCode))
                        {
                            Map<String,List<SBQQ__Subscription__c>> tempQtyMap = new Map<String,List<SBQQ__Subscription__c>>();
                            tempQtyMap.put('POSITIVE',new List<SBQQ__Subscription__c>{s}); 
                            tempMap2.put(s.SBQQ__Product__r.ProductCode,tempQtyMap);
                        }
                        else
                        {
                            if(!tempMap2.get(s.SBQQ__Product__r.ProductCode).containsKey('POSITIVE'))
                            {
                                tempMap2.get(s.SBQQ__Product__r.ProductCode).put('POSITIVE',new List<SBQQ__Subscription__c>{s});
                            }
                            else
                            {
                                tempMap2.get(s.SBQQ__Product__r.ProductCode).get('POSITIVE').add(s);
                            }
                        }
                    }
                    else if(s.SBQQ__Quantity__c < 0)
                    {
                        if(!tempMap2.containsKey(s.SBQQ__Product__r.ProductCode))
                        {
                            Map<String,List<SBQQ__Subscription__c>> tempQtyMap = new Map<String,List<SBQQ__Subscription__c>>();
                            tempQtyMap.put('NEGATIVE',new List<SBQQ__Subscription__c>{s}); 
                            tempMap2.put(s.SBQQ__Product__r.ProductCode,tempQtyMap);
                        }
                        else
                        {
                            if(!tempMap2.get(s.SBQQ__Product__r.ProductCode).containsKey('NEGATIVE'))
                            {
                                tempMap2.get(s.SBQQ__Product__r.ProductCode).put('NEGATIVE',new List<SBQQ__Subscription__c>{s});
                            }
                            else
                            {
                                tempMap2.get(s.SBQQ__Product__r.ProductCode).get('NEGATIVE').add(s);
                            }
                        }
                        
                    }
                }
                for(String s: tempMap2.keySet())
                {
                    System.debug('tempMap2 prodCode ---->'+s);
                    System.debug('tempMap2 Inner Map ---->'+tempMap2.get(s));
                }
                conIdProdCodeQuantSubListMap.put(Con.Id,tempMap2);
            }
            
            /*------------------------------------------------------*/            
            Contract Con = contractsList[0];
            
            for(String prodCode: conIdProdCodeQuantSubListMap.get(Con.Id).keySet())
            {
                System.debug('prodCode ---->'+prodCode);
                System.debug('Negative subscriptions ---->'+conIdProdCodeQuantSubListMap.get(Con.Id).get(prodCode).get('NEGATIVE'));
                System.debug('Positive subscriptions ---->'+conIdProdCodeQuantSubListMap.get(Con.Id).get(prodCode).get('POSITIVE'));
                if(conIdProdCodeQuantSubListMap.get(Con.Id).get(prodCode).get('NEGATIVE')!=null && !conIdProdCodeQuantSubListMap.get(Con.Id).get(prodCode).get('NEGATIVE').isEmpty())
                {                   
                   
                    for(SBQQ__Subscription__c N:conIdProdCodeQuantSubListMap.get(Con.Id).get(prodCode).get('NEGATIVE'))
                    {
                        for(SBQQ__Subscription__c P:conIdProdCodeQuantSubListMap.get(Con.Id).get(prodCode).get('POSITIVE'))
                        {
                            if((P.SBQQ__Quantity__c !=0) && (Math.abs(N.SBQQ__Quantity__c) == P.SBQQ__Quantity__c))
                            {
                                P.SBQQ__Quantity__c = 0;
                                N.SBQQ__Quantity__c = 0;
                                break;
                            }
                            else if((P.SBQQ__Quantity__c !=0) && (Math.abs(N.SBQQ__Quantity__c) > P.SBQQ__Quantity__c))
                            {
                                N.SBQQ__Quantity__c = N.SBQQ__Quantity__c + P.SBQQ__Quantity__c;
                                if(P.SBQQ__RenewalPrice__c!=NULL)
                                {
                                    N.SBQQ__RenewalPrice__c = P.SBQQ__RenewalPrice__c;
                                }
                                else if(P.SBQQ__RenewalPrice__c==NULL && P.SBQQ__CustomerPrice__c!=NULL)
                                {
                                    N.SBQQ__CustomerPrice__c = P.SBQQ__CustomerPrice__c;
                                }
                                else
                                {
                                    N.SBQQ__RenewalPrice__c = NULL;
                                    N.SBQQ__CustomerPrice__c = NULL;
                                }
                                P.SBQQ__Quantity__c = 0;
                                Continue;
                            }
                            else if((P.SBQQ__Quantity__c !=0) && (Math.abs(N.SBQQ__Quantity__c) < P.SBQQ__Quantity__c))
                            {
                                
                                P.SBQQ__Quantity__c = N.SBQQ__Quantity__c + P.SBQQ__Quantity__c;
                                N.SBQQ__Quantity__c = 0;
                            }
                        }
                    }
                    System.debug('After Cancelling Negative subscriptions ---->'+conIdProdCodeQuantSubListMap.get(Con.Id).get(prodCode).get('NEGATIVE'));
                    System.debug('After Cancelling Positive subscriptions ---->'+conIdProdCodeQuantSubListMap.get(Con.Id).get(prodCode).get('POSITIVE'));
                    
                }
                
            }
            /*------------------------------------------------------*/
            //Populating the contract Renewable ACV Field
            Con.Contract_Renewable_ACV__c = 0;
            for(String prodCode: conIdProdCodeQuantSubListMap.get(Con.Id).keySet())
            {
                System.debug('ProdCode ---->'+prodCode);
                System.debug('+ve subs for '+prodCode+' ---->'+conIdProdCodeQuantSubListMap.get(Con.Id).get(prodCode).get('POSITIVE'));
                for(SBQQ__Subscription__c P:conIdProdCodeQuantSubListMap.get(Con.Id).get(prodCode).get('POSITIVE'))
                {
                    if(P.SBQQ__Quantity__c!=0)
                    {
                        if(Con.Contract_Renewable_ACV__c == Null)
                        {
                            Con.Contract_Renewable_ACV__c = (P.SBQQ__Quantity__c*(P.SBQQ__RenewalPrice__c!=null?P.SBQQ__RenewalPrice__c:(P.SBQQ__CustomerPrice__c!=null?p.SBQQ__CustomerPrice__c:0)));
                        }
                        else
                        {
                            Con.Contract_Renewable_ACV__c += (P.SBQQ__Quantity__c*(P.SBQQ__RenewalPrice__c!=null?P.SBQQ__RenewalPrice__c:(P.SBQQ__CustomerPrice__c!=null?p.SBQQ__CustomerPrice__c:0)));
                        }                        
                    }
                }
            }
            
            List<Contract> conToBeUpdated = new List<Contract>{};
            conToBeUpdated.add(Con);
            
            Database.update(conToBeUpdated,False);
        }
    }
    
}