force-app/main/default/objects/Contract/fields/Contract_C_R_In_Progress__c.field-meta.xml
<CustomField>
    <fullName>Contract_C_R_In_Progress__c</fullName>
    <defaultValue>false</defaultValue>
    <description>https://samsaradev.atlassian.net/browse/GTMS-25723</description>
    <inlineHelpText>A Cancel and Replace (C&amp;R) process is in progress for this account. In-flight opportunities tied to the contract being canceled/replaced may be restricted from quote approval or submission to Closing. Please complete the C&amp;R process before proceeding with other opportunities.</inlineHelpText>
    <label>Contract C&amp;R In Progress</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Flex_Is_Rebook__c.field-meta.xml
<CustomField>
    <fullName>Flex_Is_Rebook__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Rebook</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Flex_Log__c/Flex_Log__c.object-meta.xml
<CustomObject>
    <label>Flex Log</label>
    <nameField>
        <displayFormat>Log-{00000}</displayFormat>
        <label>Flex Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flex Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Flex_Log__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the related Account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Flex Logs</relationshipLabel>
    <relationshipName>Flex_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flex_Log__c/fields/AmendedOpportunityId__c.field-meta.xml
<CustomField>
    <fullName>AmendedOpportunityId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the amended Opportunity.</description>
    <label>Amended Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Flex Logs</relationshipLabel>
    <relationshipName>Flex_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flex_Log__c/fields/AmendedQuoteId__c.field-meta.xml
<CustomField>
    <fullName>AmendedQuoteId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cancellation Quote</description>
    <inlineHelpText>Cancellation Quote</inlineHelpText>
    <label>Amended Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Flex Logs (Amended Quote)</relationshipLabel>
    <relationshipName>Flex_Logs1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flex_Log__c/fields/ContractId__c.field-meta.xml
<CustomField>
    <fullName>ContractId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the related Contract</description>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Flex Logs</relationshipLabel>
    <relationshipName>Flex_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flex_Log__c/fields/ErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>ErrorMessage__c</fullName>
    <description>Stores the error message if any.</description>
    <label>Error Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Flex_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the log (In Progress, Failed, Completed)</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>In Fulfillment</fullName>
            </value>
            <value>
                <fullName>Fulfilled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Return Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FlexCancelAndReplaceHandler.cls
/****************************************************************************************************************************
 * @Test class: FlexAccountCancelReplaceControllerTest
* Date      	- Project#       - Developer/ Company      	       - Description
* -----------------------------------------------------------------------------------------------------------------------------------------
* 01/06/2025    - GTMS-25705     - Anas Siddiquee/ Accenture 	   - Handles Cancel & Replace Upgraded & Amendment Quotes, QLIs, Opp creation
* 01/20/2025    - GTMS-25970     - Anas Siddiquee/ Accenture 	   - Added Logging for C&R processing
*/
public without sharing class FlexCancelAndReplaceHandler {

    /**
     * @description - Calls the Amender API to create and update the amendment quote and related records
    * @param - Each Contract Id, start date for the cancelled quote, Upgraded opportunity Id
    */
    @future(callout = true)
    public static void callAmenderApi(String contractId, Date startDate, String replacementOppId, Boolean isRebook) {
        Savepoint sp = Database.setSavepoint(); // Set a savepoint to rollback in case of error
        try {
            Id relatedOppId;
            QuoteModel model = FlexCancelReplaceHelper.load(contractId); // Call CPQ Amendment API returning created quote
            System.debug('Enter model '+ model);
            // Update the cancellation opportunity with relevant details like Type, Stage, Close Date, etc.
            if (model.record.SBQQ__Opportunity2__c != null) {
                relatedOppId = FlexCancelReplaceHelper.updateCancellationOpp(model.record.SBQQ__Opportunity2__c, replacementOppId, startDate);          
            }
            model = (model != null) ? FlexCancelReplaceHelper.updateCancellationQuote(model, startDate, isRebook, relatedOppId) : null; // Update the cancellation quote and qli
            System.debug('Enter outside updateCancellationQuote '+contractId);

            // Update replacement quote with the Related opp Id
            // if(relatedOppId != null && replacementQuoteId != null){
            //     FlexCancelReplaceHelper.updateReplacementQuote(replacementQuoteId, relatedOppId);
            // }

            // Update the log records with the amended opp and quote
            Flex_Log__c queueableLog = [SELECT Id FROM Flex_Log__c WHERE ContractId__c = :contractId ORDER BY CreatedDate DESC LIMIT 1];
            System.debug('Enter model.record.Id '+ model.record.Id);
            queueableLog.AmendedQuoteId__c = model.record.Id;
            queueableLog.AmendedOpportunityId__c = model.record.SBQQ__Opportunity2__c;
            queueableLog.AccountId__c = model.record.SBQQ__Account__c;
            update queueableLog;
            
            //Update the Contract_C_R_In_Progress__c on the contract to true
            TriggerHandler.bypass('ContractTriggerHandler');
            Contract contract = [SELECT Id, Contract_C_R_In_Progress__c FROM Contract WHERE Id = :contractId LIMIT 1];
            contract.Contract_C_R_In_Progress__c = true;
            System.debug('Enter isRebook '+isRebook);
            if(isRebook){
                contract.Flex_Is_Rebook__c = true;
            }
            update contract;
            
        } catch (Exception e) {
            System.debug('Error in callAmenderApi: ' + e.getMessage());
            // Rollback to the savepoint
            Database.rollback(sp);
            
            // Update the log with the error message
            handleApiError(e, contractId);
        }
    }

    private static void handleApiError(Exception e, String contractId) {
        System.debug('Failed in FlexCancelAndReplaceHandler: ' + e.getMessage() + ' ' + 'Stack Trace: ' + e.getStackTraceString());
        Flex_Log__c queueableLog = [SELECT Id, ErrorMessage__c, Status__c FROM Flex_Log__c WHERE ContractId__c = :contractId ORDER BY CreatedDate DESC LIMIT 1];
        queueableLog.Status__c = 'Failed';
        if (queueableLog.ErrorMessage__c != null) {
            queueableLog.ErrorMessage__c += '. ' + '\n\n' + 'Failed in FlexCancelAndReplaceHandler: ' + '\n' + e.getMessage() + '\n' + 'Stack Trace: ' + e.getStackTraceString();
        } else {
            queueableLog.ErrorMessage__c = 'Failed in FlexCancelAndReplaceHandler: ' + '\n' + e.getMessage() + '\n' + 'Stack Trace: ' + e.getStackTraceString();
        }
        update queueableLog;
    }



}