force-app/main/default/objects/Contract/fields/Renewal_Data_Clean__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Data_Clean__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Renewal Data Clean</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Sales_Ops_Notes__c.field-meta.xml
<CustomField>
    <fullName>Sales_Ops_Notes__c</fullName>
    <label>Sales Ops Notes</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/License_Term__c.field-meta.xml
<CustomField>
    <fullName>License_Term__c</fullName>
    <defaultValue>36</defaultValue>
    <description>The license term of the opportunity.</description>
    <label>License Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sales_Ops_Notes__c.field-meta.xml
<CustomField>
    <fullName>Sales_Ops_Notes__c</fullName>
    <description>Internal Sales Ops notes for any notes, approvals, etc.</description>
    <inlineHelpText>Internal Sales Ops notes for any notes, approvals, etc.</inlineHelpText>
    <label>Sales Ops Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/License_Term_Copy__c.field-meta.xml
<CustomField>
    <fullName>License_Term_Copy__c</fullName>
    <description>Deprecated: Copy License Term to enable rollup and formulas on oppty.</description>
    <label>License Term</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/NS_Unit_Rate__c.field-meta.xml
<CustomField>
    <fullName>NS_Unit_Rate__c</fullName>
    <formula>UnitPrice  * (1-Discount )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>NS Unit Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Prior_OLI_Id__c.field-meta.xml
<CustomField>
    <fullName>Prior_OLI_Id__c</fullName>
    <description>Captures the Opportunity Line Item Id that created this subscription record. This field will be passed over to QLI for Amendments for Remorse Refund Logic to figure out the specific line for refunding.</description>
    <label>Prior OLI Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Prior_OppId__c.field-meta.xml
<CustomField>
    <fullName>Prior_OppId__c</fullName>
    <description>Captures the prior oppId from the original deal. This field is twinned from Subscription.</description>
    <inlineHelpText>Captures the prior oppId from the original deal. This field is twinned from Subscription.</inlineHelpText>
    <label>Prior OppId</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__NetPrice__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__NetPrice__c</fullName>
    <description>Net unit price for the product quoted by this line item.</description>
    <inlineHelpText>Net unit price for the product quoted by this line item.</inlineHelpText>
    <label>Net Unit Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/SBQQ__Subscription__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Subscription__c/fields/NS_Unit_Rate__c.field-meta.xml
<CustomField>
    <fullName>NS_Unit_Rate__c</fullName>
    <description>NS Unit Rate from Opportunity Products</description>
    <label>NS Unit Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/Prior_OLI_Id__c.field-meta.xml
<CustomField>
    <fullName>Prior_OLI_Id__c</fullName>
    <description>Captures the Opportunity Line Item Id that created this subscription record. This field will be passed over to QLI for Amendments for Remorse Refund Logic to figure out the specific line for refunding.</description>
    <label>Prior OLI Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/Prior_OppId__c.field-meta.xml
<CustomField>
    <fullName>Prior_OppId__c</fullName>
    <description>Captures the prior OppId</description>
    <formula>IF( 
SBQQ__QuoteLine__c != null, CASESAFEID(SBQQ__QuoteLine__r.SBQQ__Quote__r.SBQQ__Opportunity2__c),
CASESAFEID(Prior_OppId_Legacy__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Prior OppId</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__AdditionalDiscountAmount__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__AdditionalDiscountAmount__c</fullName>
    <description>Additional Discount for this Subscription, if expressed as an amount</description>
    <inlineHelpText>Additional Discount for this Subscription, if expressed as an amount</inlineHelpText>
    <label>Additional Disc. (Amt)</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__Contract__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contract that governs this subscription.</description>
    <inlineHelpText>Contract that governs this subscription.</inlineHelpText>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__CustomerPrice__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__CustomerPrice__c</fullName>
    <description>Price the end user paid for this subscription.</description>
    <inlineHelpText>Price paid for this subscription.</inlineHelpText>
    <label>Customer Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__Discount__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Discount__c</fullName>
    <description>Additional Discount for this Subscription, if expressed as a percentage</description>
    <inlineHelpText>Additional Discount for this Subscription, if expressed as a percentage</inlineHelpText>
    <label>Additional Disc. (%)</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__ListPrice__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__ListPrice__c</fullName>
    <description>List price for this subscription product.</description>
    <inlineHelpText>List price for this subscription product.</inlineHelpText>
    <label>List Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__NetPrice__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__NetPrice__c</fullName>
    <description>Net price for this subscription.</description>
    <inlineHelpText>Net price for this subscription.</inlineHelpText>
    <label>Net Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__ProrateMultiplier__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__ProrateMultiplier__c</fullName>
    <description>Calculated ratio used to compute prorated price.</description>
    <inlineHelpText>Calculated ratio used to compute prorated price.</inlineHelpText>
    <label>Prorate Multiplier</label>
    <precision>8</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__QuoteLine__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__QuoteLine__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Quote line that generated this subscription.</description>
    <inlineHelpText>Quote line that generated this subscription.</inlineHelpText>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__RegularPrice__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__RegularPrice__c</fullName>
    <description>Regular Price for this Subscription.</description>
    <inlineHelpText>Regular Price for this Subscription.</inlineHelpText>
    <label>Regular Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__RenewalPrice__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__RenewalPrice__c</fullName>
    <description>Define the price of quote lines that appear on the renewal quote when you renew this subscription. This field overrides the result of price calculations from your account’s renewal pricing method. If renewal pricing method is Uplift, uplift will be applied to the Renewal Price.</description>
    <inlineHelpText>Override the default calculated price of this subscription on a renewal quote. If your account&apos;s renewal pricing method is Uplift, the uplift applies to this renewal price.</inlineHelpText>
    <label>Renewal Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__SpecialPrice__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__SpecialPrice__c</fullName>
    <description>Special Price for this Subscription.</description>
    <inlineHelpText>Special Price for this Subscription.</inlineHelpText>
    <label>Special Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/LegacySubscriptionsFixBatch.cls
/*
* TestClass = LegacySubscriptionsFixBatchTest

* This Class must be processed with batch size 1, as we are hardcoding the index

* database.executebatch(new LegacySubscriptionsFixBatch(),1);

* Dec-21-2022 Rajesh :- GTMS-10518
*/
global class LegacySubscriptionsFixBatch 
implements Database.Batchable<sObject> {

    static gslib_IModuleLogger thisModuleLogger = gslib_LoggerService.getModuleLogger('GTMS');
    static gslib_ILogger thisLogger = thisModuleLogger.getLogger();

    global Database.QueryLocator start(Database.BatchableContext bc) {
        if(Test.isRunningTest()){
            return Database.getQueryLocator('SELECT id, ContractTerm, SBQQ__RenewalTerm__c, CreatedDate, StartDate, EndDate FROM Contract');
         }
         else{
            return Database.getQueryLocator(Label.LegacySubscriptionsFixBatchQuery);
         }
    }

    global void execute(Database.BatchableContext bc, List<Contract> records){
        Set<Id> contractsSet = new Set<Id>();
        Map<Id,Contract> contracts = new Map<Id,Contract>();
        //List<SBQQ__Subscription__c> subscriptions = new List<SBQQ__Subscription__c>();

        for(Contract c : records){
            contractsSet.add(c.id);
        }
        List<SBQQ__Subscription__c> subscriptions = [SELECT Id, SBQQ__Contract__c, 
                                        SBQQ__Contract__r.ContractTerm, SBQQ__Contract__r.SBQQ__RenewalTerm__c, 
                                        SBQQ__Contract__r.CreatedDate, SBQQ__Contract__r.StartDate, SBQQ__Contract__r.EndDate,
                                        SBQQ__ListPrice__c,SBQQ__ProrateMultiplier__c,NS_Unit_Rate__c,
                                        SBQQ__QuoteLine__r.SBQQ__SubscriptionTerm__c,
                                        SBQQ__QuoteLine__r.SBQQ__Quote__r.SBQQ__SubscriptionTerm__c,
                                        SBQQ__QuoteLine__r.SBQQ__ListPrice__c,
                                        SBQQ__QuoteLine__r.SBQQ__NetPrice__c,
                                        SBQQ__Contract__r.Sales_Ops_Notes__c,
                                        SBQQ__QuoteLine__c,Prior_OppId__c,Prior_OLI_Id__c
                                        FROM SBQQ__Subscription__c WHERE SBQQ__Contract__c IN : contractsSet];

        if(subscriptions.size() > 0){
            Set<Id> OppsSet = new Set<Id>();
            Set<Id> OLIsSet = new Set<Id>();
            for(SBQQ__Subscription__c s : subscriptions){
                if(s.SBQQ__QuoteLine__c == NULL){
                    if(s.Prior_OLI_Id__c <> NULL){
                        OLIsSet.add(s.Prior_OLI_Id__c);
                    }
                    else if(s.Prior_OppId__c <> NULL){
                        OppsSet.add(s.Prior_OppId__c);
                    }
                }
            }
            
            Map<Id,OpportunityLineItem> priorOLIs =new Map<Id,OpportunityLineItem>([SELECT ID,License_Term_Copy__c,ListPrice, NS_Unit_Rate__c
                                                    FROM OpportunityLineItem 
                                                    WHERE ID IN : OLIsSet]);
            Map<Id,Opportunity> priorOpps = new Map<Id,Opportunity>([SELECT ID,License_Term__c
                                            FROM Opportunity
                                            WHERE ID IN : OppsSet]);

            for(SBQQ__Subscription__c s : subscriptions){
                
                if(s.SBQQ__QuoteLine__c == NULL){
                    if(priorOLIs.containsKey(s.Prior_OLI_Id__c)){
                        s.SBQQ__ProrateMultiplier__c = priorOLIs.get(s.Prior_OLI_Id__c).License_Term_Copy__c / 12;
                        s.SBQQ__ListPrice__c = priorOLIs.get(s.Prior_OLI_Id__c).ListPrice * s.SBQQ__ProrateMultiplier__c;
                        s.SBQQ__SpecialPrice__c = priorOLIs.get(s.Prior_OLI_Id__c).ListPrice;
                    }
                    else if(priorOpps.containsKey(s.Prior_OppId__c)){
                        s.SBQQ__ProrateMultiplier__c = priorOpps.get(s.Prior_OppId__c).License_Term__c / 12;
                        s.SBQQ__SpecialPrice__c = s.SBQQ__ListPrice__c;
                        s.SBQQ__ListPrice__c = s.SBQQ__SpecialPrice__c * s.SBQQ__ProrateMultiplier__c;
                    }
                }
                else{
                    s.SBQQ__ProrateMultiplier__c = s.SBQQ__QuoteLine__r.SBQQ__Quote__r.SBQQ__SubscriptionTerm__c / 12;
                    s.SBQQ__ListPrice__c = s.SBQQ__QuoteLine__r.SBQQ__ListPrice__c * s.SBQQ__ProrateMultiplier__c;
                    s.SBQQ__SpecialPrice__c = s.SBQQ__QuoteLine__r.SBQQ__ListPrice__c;
                }
                    
                if(s.NS_Unit_Rate__c == NULL){
                    if(s.SBQQ__QuoteLine__c <> NULL){
                        s.NS_Unit_Rate__c = s.SBQQ__QuoteLine__r.SBQQ__NetPrice__c;
                    }
                    else if(priorOLIs.containsKey(s.Prior_OLI_Id__c)){
                        s.NS_Unit_Rate__c = priorOLIs.get(s.Prior_OLI_Id__c).NS_Unit_Rate__c;
                    }
                }

                s.SBQQ__NetPrice__c = s.NS_Unit_Rate__c;
                s.SBQQ__CustomerPrice__c = s.NS_Unit_Rate__c;
                s.SBQQ__RenewalPrice__c = s.NS_Unit_Rate__c / s.SBQQ__ProrateMultiplier__c;
                s.SBQQ__RegularPrice__c = s.SBQQ__ListPrice__c;
                s.SBQQ__Discount__c = (1 - (s.NS_Unit_Rate__c / s.SBQQ__ListPrice__c)) * 100;
                s.SBQQ__AdditionalDiscountAmount__c = NULL;
                
                if(contracts.containsKey(s.SBQQ__Contract__c) == false){
                    Contract c = new Contract();
                    
                    c.Id = s.SBQQ__Contract__c;
                    c.SBQQ__RenewalPricebookId__c = '01s4p000004cVodAAE';

                    if(string.isBlank(s.SBQQ__Contract__r.Sales_Ops_Notes__c)){
                        c.Sales_Ops_Notes__c ='Renewal Legacy Data Update';
                    }
                    else{
                        c.Sales_Ops_Notes__c = s.SBQQ__Contract__r.Sales_Ops_Notes__c +  ', Renewal Legacy Data Update';
                    }   
                    

                    if(s.SBQQ__Contract__r.ContractTerm <= 12)
                        c.SBQQ__RenewalTerm__c = 12;
                    if(s.SBQQ__Contract__r.ContractTerm > 12 && s.SBQQ__Contract__r.ContractTerm <= 36)
                        c.SBQQ__RenewalTerm__c = 36;
                    else if(s.SBQQ__Contract__r.ContractTerm > 36 && s.SBQQ__Contract__r.ContractTerm <= 60)
                        c.SBQQ__RenewalTerm__c = 60;
                    else if(s.SBQQ__Contract__r.ContractTerm > 60 && s.SBQQ__Contract__r.ContractTerm <= 72)
                        c.SBQQ__RenewalTerm__c = 72;
                    else if(s.SBQQ__Contract__r.ContractTerm > 72)
                        c.SBQQ__RenewalTerm__c = 84;
                    
                    contracts.put(s.SBQQ__Contract__c, c);
                }
            }

            Set<Id> contractsWithErrors = new Set<Id>();
            if(subscriptions.size() > 0){
                Database.SaveResult[] updatedSubscriptions = Database.update(subscriptions,false);
                for(Integer i = 0; i < updatedSubscriptions.size(); i++){
                    if(!updatedSubscriptions[i].isSuccess() ){
                        for(Database.Error err : updatedSubscriptions[i].getErrors())
                        {
                            thisLogger.logError(err.getStatusCode() + ': ' + err.getMessage() + ', Subscription fields that affected this error: ' + err.getFields());
                        }
                        if(contractsWithErrors.contains(subscriptions[i].SBQQ__Contract__c) == false){
                            contractsWithErrors.add(subscriptions[i].SBQQ__Contract__c);
                        }
                    }
                }
            }
            
            if(contracts.size() > 0){
                Database.SaveResult[] updatedContracts = Database.update(contracts.values(),false);
                for(Integer i = 0; i < updatedContracts.size(); i++){
                    if(!updatedContracts[i].isSuccess()){
                        for(Database.Error err : updatedContracts[i].getErrors())
                        {
                            thisLogger.logError(err.getStatusCode() + ': ' + err.getMessage() + ', Contract fields that affected this error: ' + err.getFields());
                        }
                        if(contractsWithErrors.contains(contracts.values()[i].Id) == false){
                            contractsWithErrors.add(contracts.values()[i].Id);
                        }
                    }
                }  
            }
            
            List<Contract> contractsCorrected = new List<Contract>();
            for(Contract c : contracts.values()){
                if(contractsWithErrors.contains(c.Id) == false){
                    contractsCorrected.add(new Contract(Id = c.Id,Renewal_Data_Clean__c = true));
                }
            }

            if(contractsCorrected.size() > 0){
                update contractsCorrected;
            } 

            if(contractsWithErrors.size() > 0){
                thisLogger.dispatch();
            }
        }
    }

    global void finish(Database.BatchableContext bc){
        // execute any post-processing operations
    }
}