force-app/main/default/objects/Contract/fields/Weighted_Average_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Weighted_Average_Start_Date__c</fullName>
    <description>This Date is created for the WASD Project GTMS-23000 that is updated manually by AE&apos;s or the finance team for contract consolidation purpose</description>
    <inlineHelpText>Renewal Date may be a weighted average if multiple contracts are expiring in quarter</inlineHelpText>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Adjust_License_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Adjust_License_Start_Date__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Enable Sys Admin and Sales Ops to make License Start Date != Close Date (can make sense for early renewals and co-terming issues)</description>
    <inlineHelpText>Confirm there are no items that require shipping on this opportunity</inlineHelpText>
    <label>Adjust License Start Date</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Initial_Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Initial_Payment_Terms__c</fullName>
    <description>Initial Payment Term for custom schedule</description>
    <label>Initial Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SBQQ__PaymentTerm</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/License_End_Date__c.field-meta.xml
<CustomField>
    <fullName>License_End_Date__c</fullName>
    <description>Date License Ends for Opportunity</description>
    <label>License End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/License_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>License_Start_Date__c</fullName>
    <description>Determines the License Term. Automatically set to match the Close Date when Opportunity moves to Closed Won.</description>
    <inlineHelpText>Determines the License Term. Automatically set to match the Close Date when Opportunity moves to Closed Won.</inlineHelpText>
    <label>License Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/License_Term__c.field-meta.xml
<CustomField>
    <fullName>License_Term__c</fullName>
    <defaultValue>36</defaultValue>
    <description>The license term of the opportunity.</description>
    <label>License Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Due in advance</fullName>
                <default>true</default>
                <label>Due in advance</label>
            </value>
            <value>
                <fullName>Net 5</fullName>
            </value>
            <value>
                <fullName>Net 10</fullName>
            </value>
            <value>
                <fullName>Net 15</fullName>
            </value>
            <value>
                <fullName>Net 30</fullName>
            </value>
            <value>
                <fullName>Net 45</fullName>
            </value>
            <value>
                <fullName>Net 60</fullName>
            </value>
            <value>
                <fullName>Net 65</fullName>
            </value>
            <value>
                <fullName>Net 75</fullName>
            </value>
            <value>
                <fullName>Net 90</fullName>
            </value>
            <value>
                <fullName>Net 120</fullName>
            </value>
            <value>
                <fullName>Net 150</fullName>
            </value>
            <value>
                <fullName>Due on Contract Start</fullName>
            </value>
            <value>
                <fullName>Due on receipt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/SBQQ__PaymentTerm.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Net 15</fullName>
    </customValue>
    <customValue>
        <fullName>Net 30</fullName>
    </customValue>
    <customValue>
        <fullName>Net 45</fullName>
    </customValue>
    <customValue>
        <fullName>Net 60</fullName>
    </customValue>
    <customValue>
        <fullName>Net 90</fullName>
    </customValue>
    <customValue>
        <fullName>Net 5</fullName>
    </customValue>
    <customValue>
        <fullName>Due on receipt</fullName>
    </customValue>
    <customValue>
        <fullName>Due on Contract Start</fullName>
    </customValue>
    <customValue>
        <fullName>Due in advance</fullName>
        <default>true</default>
        <label>Due in advance</label>
    </customValue>
    <customValue>
        <fullName>Net 65</fullName>
    </customValue>
    <customValue>
        <fullName>Net 75</fullName>
    </customValue>
    <customValue>
        <fullName>Net 120</fullName>
    </customValue>
    <customValue>
        <fullName>Net 10</fullName>
    </customValue>
    <customValue>
        <fullName>Net 150</fullName>
    </customValue>
    <customValue>
        <fullName>None</fullName>
        <isActive>false</isActive>
        <label>None</label>
    </customValue>
    <masterLabel>Payment Term</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BatchEarlyRenewals.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 09-27-2023
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
//Apex batch class to update the status of the records in the custom object

/*CRON :BatchEarlyRenewals b= new BatchEarlyRenewals();
		String seconds = '0';
		String minutes = '0';
		String hours = '23';
		String dayOfMonth = '?';
		String month = '*';
		String dayOfWeek = '*';
		String sch = seconds+''+minutes+''+hours+''+dayOfMonth+''+month+''+dayOfWeek;
		system.schedule('EarlyRenewalsBatch Run Every Day at 11pm', sch,b); */ 
 
        global class BatchEarlyRenewals implements Database.Batchable<sObject>, Schedulable, Database.Stateful {

            global void execute(SchedulableContext sc) {
                    BatchEarlyRenewals  job = new BatchEarlyRenewals ();
                        ID batchprocessid = Database.executeBatch(job,1); 
                }  
            
               global integer recordsProcessed = 0;
                global Database.QueryLocator start(Database.BatchableContext BC) {
                    String query = system.label.Early_Renewals;
                    
                    return Database.getQueryLocator(query);
                }
            
                global void execute(Database.BatchableContext BC, List<Opportunity> Opps) {
                    List<Opportunity> OppstoUpdate = new List<Opportunity>();
                    for(Opportunity opp : Opps) {
                        if(opp.closeDate > System.Today() && opp.Adjust_License_Start_Date__c==false && opp.Probability <= 95){
                            opp.Adjust_License_Start_Date__c = true;
                            opp.CloseDate = opp.SBQQ__RenewedContract__r.EndDate + 1;
                            //GTMS-23000
                            if(opp.SBQQ__RenewedContract__r.Weighted_Average_Start_Date__c != null){
                                opp.License_Start_Date__c = opp.SBQQ__RenewedContract__r.Weighted_Average_Start_Date__c;
                                if(opp.License_Start_Date__c >= date.today()){
               						opp.Adjust_License_Start_Date__c = true;
              					 }else{
                   					opp.Adjust_License_Start_Date__c = false;
               					 }
                            }
                            else{
                                opp.License_Start_Date__c = opp.CloseDate;
                            }
                            //GTMS-23000
                            opp.License_End_Date__c = Date.newInstance((Integer)(opp.CloseDate.year() + Math.floor(opp.CloseDate.month() + opp.License_Term__c - 1)/12), 
                                                                                 Math.mod((Integer)(opp.CloseDate.month() + opp.License_Term__c - 1), 12) + 1, 
                                                                                 opp.CloseDate.day() - 1);
                            opp.Initial_Payment_Terms__c = opp.Payment_Terms__c == 'Due In Advance' ? 'Due on Contract Start' : opp.Payment_Terms__c;
                            OppstoUpdate.add(opp);
                        }
                        else if(opp.closeDate <= System.Today() && opp.Adjust_License_Start_Date__c==true && opp.Probability <= 95){  
                            opp.Adjust_License_Start_Date__c = false;
                            opp.Initial_Payment_Terms__c = opp.Payment_Terms__c == 'Due In Advance' ? 'Due on Contract Start' : opp.Payment_Terms__c;  
                            OppstoUpdate.add(opp);  
                        }
                        else if(opp.closeDate <= System.Today() && opp.Adjust_License_Start_Date__c== False && opp.Initial_Payment_Terms__c != 'Due in Advance' && opp.Probability <= 95){
                            opp.Initial_Payment_Terms__c = opp.Payment_Terms__c == 'Due In Advance' ? 'Due on Contract Start' : opp.Payment_Terms__c;
                            OppstoUpdate.add(opp);
                        }  
                        recordsProcessed = recordsProcessed + 1;    
                    }
                if(OppstoUpdate != null && OppstoUpdate.size() > 0){
                    Database.SaveResult[] updateResult = Database.update (OppstoUpdate,FALSE);
                    system.debug('Records updated in this Batch : ' + OppstoUpdate.size());
                    for(Database.SaveResult sr : updateResult){
                        if(!sr.isSuccess()){
                            for(Database.Error err : sr.getErrors()){
                                system.debug('The following error has occurred.'); 
                                system.debug(err.getStatusCode() + ': ' + err.getMessage());
                                system.debug('Opportunity fields that affected this error: ' + err.getFields());
                            }
                        }
                    }
                } 
            }
            
                // Finish Method
                global void finish(Database.BatchableContext BC) {
                    system.debug('Records Processed in this Batch : ' + recordsProcessed);
                }
            
            
            // Test class for batchearlyrenewals
             public static void testCoverage() {
                Integer a=1,b=2,c;
                c=a+b;
                c=a+b;
                c=a+b;
                c=a+b;
                c=a+b;
                c=a+b;
                c=a+b;
                c=a+b;
                c=a+b;
                c=a+b;
                c=a+b;
                c=a+b;
                c=a+b;
             }
            
                
            }