force-app/main/default/objects/Account/fields/Account_Assignment_Date__c.field-meta.xml
<CustomField>
    <fullName>Account_Assignment_Date__c</fullName>
    <description>This field stores the date time in which this account was last assignment to the current owner from the pool or viceversa.</description>
    <label>Account Assignment Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Account_with_Owner__c.field-meta.xml
<CustomField>
    <fullName>Account_with_Owner__c</fullName>
    <description>Account name with account owner</description>
    <formula>Name &amp; &quot; (Owned By: &quot; &amp; Owner.FirstName &amp; &quot; &quot; &amp; Owner.LastName &amp; &quot;)&quot;</formula>
    <label>Account with Owner</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Current_Owner_Email__c.field-meta.xml
<CustomField>
    <fullName>Current_Owner_Email__c</fullName>
    <label>Current Owner Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Domain_Name__c.field-meta.xml
<CustomField>
    <fullName>Domain_Name__c</fullName>
    <description>Saves the domain, considering first the name after the email and then the website.</description>
    <label>Domain Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Enterprise_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Enterprise_Assignment__c</fullName>
    <description>Assignment for Enterprise Lists.</description>
    <label>Enterprise Assignment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Abbey Wilson</fullName>
            </value>
            <value>
                <fullName>Aldon Ortego</fullName>
            </value>
            <value>
                <fullName>Alexander Lethen</fullName>
            </value>
            <value>
                <fullName>Alexander Sharp</fullName>
            </value>
            <value>
                <fullName>Alex Fisher</fullName>
            </value>
            <value>
                <fullName>Alex Kauth</fullName>
            </value>
            <value>
                <fullName>Alex McCall</fullName>
            </value>
            <value>
                <fullName>Alyssa Unterreiner</fullName>
            </value>
            <value>
                <fullName>Amanda Reid</fullName>
            </value>
            <value>
                <fullName>Amber Roork</fullName>
            </value>
            <value>
                <fullName>Amir Bhagwandin</fullName>
            </value>
            <value>
                <fullName>Andrew Kendall</fullName>
                <isActive>false</isActive>
                <label>Andrew Kendall</label>
            </value>
            <value>
                <fullName>Andrew Kimbrough</fullName>
            </value>
            <value>
                <fullName>Andrew Meese</fullName>
            </value>
            <value>
                <fullName>Andrew Tate</fullName>
            </value>
            <value>
                <fullName>Ann Garber</fullName>
            </value>
            <value>
                <fullName>Ashley Cookas</fullName>
                <isActive>false</isActive>
                <label>Ashley Cookas</label>
            </value>
            <value>
                <fullName>Austin Smith</fullName>
            </value>
            <value>
                <fullName>Bart Pickett</fullName>
            </value>
            <value>
                <fullName>Becky Devin</fullName>
            </value>
            <value>
                <fullName>Bency Beals</fullName>
            </value>
            <value>
                <fullName>BENELUX TBH 2</fullName>
                <isActive>false</isActive>
                <label>BENELUX TBH 2</label>
            </value>
            <value>
                <fullName>Bobby Boyle</fullName>
            </value>
            <value>
                <fullName>Brett Gascoine</fullName>
            </value>
            <value>
                <fullName>Brian Glowiak</fullName>
            </value>
            <value>
                <fullName>Brian Hanlon</fullName>
            </value>
            <value>
                <fullName>Canada 1</fullName>
            </value>
            <value>
                <fullName>Canada 2</fullName>
            </value>
            <value>
                <fullName>Canada 3</fullName>
            </value>
            <value>
                <fullName>Canada East TBH</fullName>
                <isActive>false</isActive>
                <label>Canada East TBH</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Inside_Sales_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Inside_Sales_Assignment__c</fullName>
    <description>Assignment of Named Accounts for AEs</description>
    <label>Inside Sales Assignment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Core</fullName>
            </value>
            <value>
                <fullName>Adam Regos</fullName>
            </value>
            <value>
                <fullName>Alexander Gnädig</fullName>
            </value>
            <value>
                <fullName>Alex Fisher</fullName>
            </value>
            <value>
                <fullName>Alex Kane</fullName>
            </value>
            <value>
                <fullName>Angel Ashcraft</fullName>
            </value>
            <value>
                <fullName>Anton Cardenas</fullName>
            </value>
            <value>
                <fullName>Ben Osman</fullName>
            </value>
            <value>
                <fullName>Brendon Lanouette</fullName>
            </value>
            <value>
                <fullName>Brett Kirkendall</fullName>
            </value>
            <value>
                <fullName>Brian Broe</fullName>
            </value>
            <value>
                <fullName>Chase Turay</fullName>
            </value>
            <value>
                <fullName>Chris Fisher</fullName>
            </value>
            <value>
                <fullName>Chris Killeen</fullName>
            </value>
            <value>
                <fullName>Chris McMurtagh</fullName>
            </value>
            <value>
                <fullName>Ciaran O Neill</fullName>
            </value>
            <value>
                <fullName>Cindy Townsend</fullName>
            </value>
            <value>
                <fullName>Curtis Holcombe</fullName>
            </value>
            <value>
                <fullName>DACH TBH 1</fullName>
            </value>
            <value>
                <fullName>Dante Selvitella</fullName>
            </value>
            <value>
                <fullName>Devin Hamner</fullName>
            </value>
            <value>
                <fullName>Evan Richards</fullName>
            </value>
            <value>
                <fullName>Forest Chapman</fullName>
            </value>
            <value>
                <fullName>France TBH 1</fullName>
            </value>
            <value>
                <fullName>Greg Muender</fullName>
            </value>
            <value>
                <fullName>Harry Lal</fullName>
            </value>
            <value>
                <fullName>IS Pool</fullName>
            </value>
            <value>
                <fullName>Jacqueline Gregory</fullName>
            </value>
            <value>
                <fullName>Jason Alumbaugh</fullName>
            </value>
            <value>
                <fullName>Jay Chokshi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Master_Account_for_Dupe__c.field-meta.xml
<CustomField>
    <fullName>Master_Account_for_Dupe__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master Account for Dupe</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Master Account for Dupe)</relationshipLabel>
    <relationshipName>Accounts2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Number_of_Vehicles__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Vehicles__c</fullName>
    <label>Number of Vehicles (Field Input)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Original_Owner_for_Recycling_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Original_Owner_for_Recycling_Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original Owner for Recycling Campaign</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Original_Owner_for_Recycling_Campaign</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;New&quot;</defaultValue>
    <description>This is a roll up from the status of the contacts of the account. 
Eg. If there is any disqualified contact -&gt; Disqualified and so on.</description>
    <label>Account Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DedupeAccounts.cls
public class DedupeAccounts {
    
	@InvocableMethod(label='De-Dupe Accounts' description='When an account ID is added, this will return a list of duplicate accounts in Salesforce.')
    public static List<List<Account>> getDuplicateAccountsForProcessing(List<Account> accounts){
        List<List<Account>> result = new List<List<Account>>(); //create the final wrapper variable so that an empty list may be returned if there are no results
		List<DuplicateRecordItem> duplicate_set = new List<DuplicateRecordItem>(); //create a list variable for duplicate sets that we will search for
        //get the IDs of duplicate sets that this account is a part of 
        if(accounts.size() > 0){
           	duplicate_set = [SELECT  DuplicateRecordSetId
                       			FROM DuplicateRecordItem 
                       			WHERE RecordId = :accounts[0].Id
                            	AND DuplicateRecordSet.RecordCount<=8];      
        }
        if(duplicate_set != null ){
            List<String> duplicate_set_ids = new List<String>(); //create a string list to store the duplicate set IDs for the next query
            //use a loop to get all of the IDs
            for (DuplicateRecordItem dri :duplicate_set){
                duplicate_set_ids.add(dri.DuplicateRecordSetId);
            }
            List<DuplicateRecordItem> duplicate_records = new List<DuplicateRecordItem>(); //create a list for the duplicate set items that have record Ids

            //get the record ids of all account ids in the duplicate sets
            if(duplicate_set_ids.size() > 0){
              duplicate_records = [SELECT RecordId
                           FROM DuplicateRecordItem 
                           WHERE DuplicateRecordSetId IN :duplicate_set_ids];
            }
            Set <String> duplicate_record_ids = new Set<String>(); //create a list for the record IDs that will be used for the last query
            //check to see if any of the record Ids appear multiple times, if not push them to the list
            for(DuplicateRecordItem dr :duplicate_records){
                duplicate_record_ids.add(dr.RecordId);
            }
            List<Account> duplicate_accounts = new List<Account>(); //create a list for the account records that will be returned to the flow
            //run query to get all accounts
            if(duplicate_record_ids.size() > 0){
                duplicate_accounts = [SELECT Name, Phone, Website, BillingStreet, Domain_Name__c, BillingState, 
                                  	  	BillingPostalCode, BillingCity,Enterprise_Assignment__c, 
                                  	  	Inside_Sales_Assignment__c, Account_Assignment_Date__c, Original_Owner_for_Recycling_Campaign__c, 
                                  	  	Account_with_Owner__c, Number_of_Vehicles__c, Current_Owner_Email__c, Status__c, Master_Account_for_Dupe__c, Alternative_Domains__c 
                           			  FROM Account
                           			  WHERE Id IN :duplicate_record_ids
                          	 		  AND Id != :accounts[0].Id
                                      AND RecordTypeId = :accounts[0].RecordTypeId];
            }
            
            //add duplicate accounts to result wrapper
            result.add(duplicate_accounts);
        }
        return result;
    }
}