force-app/main/default/objects/Account/fields/Account_Book_Owner__c.field-meta.xml
<CustomField>
    <fullName>Account_Book_Owner__c</fullName>
    <formula>Books_Of_Business__r.AE__r.FirstName + &apos; &apos; + Books_Of_Business__r.AE__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Book Owner</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Event_Lead__c.field-meta.xml
<CustomField>
    <fullName>Event_Lead__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This lead has been uploaded to Salesforce by using the Events Uploader tool. The lead has special restrictions for this reason (eg. Time that must pass before it can be unloaded by a rep)</description>
    <label>Event Lead</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Hashtag__c.field-meta.xml
<CustomField>
    <fullName>Hashtag__c</fullName>
    <description>Tag the account with the concept you prefer. Useful for mass transfering, as the actual tool does not allow the description field to be used for that.</description>
    <label>Account Hashtag</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Number_of_Calls_by_Current_Owner__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Calls_by_Current_Owner__c</fullName>
    <description>These are the number of calls that have been logged by the current owner. It is a rollup from the contacts, by using the Rollup Helper.</description>
    <label>Number of Calls by Current Owner</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Original_Owner_for_Recycling_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Original_Owner_for_Recycling_Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original Owner for Recycling Campaign</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Original_Owner_for_Recycling_Campaign</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;New&quot;</defaultValue>
    <description>This is a roll up from the status of the contacts of the account. 
Eg. If there is any disqualified contact -&gt; Disqualified and so on.</description>
    <label>Account Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Fleet.recordType-meta.xml
<RecordType>
    <fullName>Fleet</fullName>
    <active>true</active>
    <description>Fleet account</description>
    <label>Fleet</label>
</RecordType>

force-app/main/default/objects/Async_Request__c/Async_Request__c.object-meta.xml
<CustomObject>
    <description>Use to queue up an Asynchronous Request for processing</description>
    <label>Async Request</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Async Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Async Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Async_Request__c/fields/Params__c.field-meta.xml
<CustomField>
    <fullName>Params__c</fullName>
    <label>Params</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Account_Book_Owner__c.field-meta.xml
<CustomField>
    <fullName>Account_Book_Owner__c</fullName>
    <formula>Account.Books_Of_Business__r.AE__r.FirstName &amp; &apos; &apos; &amp; Account.Books_Of_Business__r.AE__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Book Owner</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Hashtag__c.field-meta.xml
<CustomField>
    <fullName>Hashtag__c</fullName>
    <label>Contact Hashtag</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Original_Owner_for_Recycling_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Original_Owner_for_Recycling_Campaign__c</fullName>
    <formula>Account.Original_Owner_for_Recycling_Campaign__r.FirstName &amp;&quot; &quot;&amp;Account.Original_Owner_for_Recycling_Campaign__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Original Owner for Recycling Campaign</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Contact Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Attempting</fullName>
            </value>
            <value>
                <fullName>Demo Scheduled</fullName>
            </value>
            <value>
                <fullName>Demo No Show</fullName>
            </value>
            <value>
                <fullName>Demo Completed - Not Qualified</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Retouch - Did Not Connect</fullName>
            </value>
            <value>
                <fullName>Retouch - Confirmed No Opportunity</fullName>
                <label>Connected-Disqualified</label>
            </value>
            <value>
                <fullName>Send Small Fleet Link</fullName>
            </value>
            <value>
                <fullName>Small Fleet Link Sent</fullName>
            </value>
            <value>
                <fullName>Inactive - See Parent Account</fullName>
            </value>
            <value>
                <fullName>Small Fleet Link Failed - Invalid Email</fullName>
            </value>
            <value>
                <fullName>Small Fleet Link Pending - Manual Review</fullName>
            </value>
            <value>
                <fullName>Faulty Lead</fullName>
            </value>
            <value>
                <fullName>Do Not Contact - Open Conversation</fullName>
            </value>
            <value>
                <fullName>Contact Established</fullName>
                <isActive>false</isActive>
                <label>Contact Established</label>
            </value>
            <value>
                <fullName>Create Webstore Opportunity</fullName>
                <isActive>false</isActive>
                <label>Create Webstore Opportunity</label>
            </value>
            <value>
                <fullName>Delete Account</fullName>
                <isActive>false</isActive>
                <label>Delete Account</label>
            </value>
            <value>
                <fullName>Delete Contact Only</fullName>
                <isActive>false</isActive>
                <label>Delete Contact Only</label>
            </value>
            <value>
                <fullName>GDPR Delete</fullName>
                <isActive>false</isActive>
                <label>GDPR Delete</label>
            </value>
            <value>
                <fullName>Inactive - No Longer There</fullName>
                <isActive>false</isActive>
                <label>Inactive - No Longer There</label>
            </value>
            <value>
                <fullName>Multiple Campaign Interactions</fullName>
                <isActive>false</isActive>
                <label>Multiple Campaign Interactions</label>
            </value>
            <value>
                <fullName>No Authority</fullName>
                <isActive>false</isActive>
                <label>No Authority</label>
            </value>
            <value>
                <fullName>Opt out - Do not contact</fullName>
                <isActive>false</isActive>
                <label>Opt out - Do not contact</label>
            </value>
            <value>
                <fullName>Webstore Opportunity Created</fullName>
                <isActive>false</isActive>
                <label>Webstore Opportunity Created</label>
            </value>
            <value>
                <fullName>Webstore Opportunity Creation In Progress</fullName>
                <isActive>false</isActive>
                <label>Webstore Opportunity Creation In Progress</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Unload_Account__c.field-meta.xml
<CustomField>
    <fullName>Unload_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Unload Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Fleet.recordType-meta.xml
<RecordType>
    <fullName>Fleet</fullName>
    <active>true</active>
    <description>Fleet contact</description>
    <label>Fleet</label>
</RecordType>

force-app/main/default/objects/Lead/fields/Event_Lead__c.field-meta.xml
<CustomField>
    <fullName>Event_Lead__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Event Lead</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Hashtag__c.field-meta.xml
<CustomField>
    <fullName>Hashtag__c</fullName>
    <description>Tag the account with the concept you prefer. Useful for mass transfering, as the actual tool does not allow the description field to be used for that.</description>
    <label>Hashtag</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Hashtag__c.field-meta.xml
<CustomField>
    <fullName>Hashtag__c</fullName>
    <label>Opportunity Hashtag</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Trial_Status__c.field-meta.xml
<CustomField>
    <fullName>Trial_Status__c</fullName>
    <label>Trial Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Shipped</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Purchased</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Return In Process</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>Write-off</fullName>
            </value>
            <value>
                <fullName>Partial Purchase</fullName>
            </value>
            <value>
                <fullName>Partial Return</fullName>
            </value>
            <value>
                <fullName>Pending Return or Write-Off</fullName>
                <isActive>false</isActive>
                <label>Pending Return or Write-Off</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Trial.recordType-meta.xml
<RecordType>
    <fullName>Trial</fullName>
    <active>true</active>
    <businessProcess>Standard Opportunities</businessProcess>
    <label>Trial</label>
</RecordType>

force-app/main/default/classes/GS_Contact_ManuallyUnloadContactAsync.cls
/**
* Created By : Groundswell - Tanuj Tyagi
* @Date August 22, 2021
*
* @description : This class will be responsible for Manually Unloading Contact/Account on Contact
* SFA-14
*
**/
public with sharing class GS_Contact_ManuallyUnloadContactAsync extends BaseAsyncHandler{
    public SamsaraLoggerService thisSamsaraLoggerService = new SamsaraLoggerService();
    public override String getRequestType(){
        return 'ManuallyUnloadContact';
    } 
    
    List<Schema.SObjectType> MY_SOBJECTS = new List<Schema.SObjectType>{
        Contact.SObjectType,
            Account.SObjectType
            };
                
    Private UnitOfWork uow;
    public GS_ContactCacheService contactCache = new GS_ContactCacheService();       
    
    List<Id> recordsIds = new List<Id>();
    Map<Id, Account> accountUpdates = new Map<Id, Account>();
    Map<Id, Contact> contactToUpdateById = new Map<Id, Contact>();
    Map<String, Id> poolMap = null;
    Map<Id, Contact> contactsToUpdateOwner;
    Map<Id,Contact> contactsFlaggedToUnloadAccountMap = new Map<Id,Contact>();
    Map<Id, String> accountIdToPool = new Map<Id, String>();
    Id poolOwnerId;
    String recordTypeName;
    
    public override void execute(Async_Request__c ar)
    {
        recordsIds = ar.Params__c.split(PARAMETERS_SPLITTER);
        if(recordsIds.isEmpty()) return;
                
        contactsFlaggedToUnloadAccountMap = new Map<Id, Contact>(
            (new GS_ContactSelector(true)).getContactDetailsByIds(new Set<Id>(recordsIds)));
        
        DMLWrapper.intializeUnitOfWork(MY_SOBJECTS); 
        
        try{
            thisSamsaraLoggerService.logger.logTrace('Entering in GS_Contact_ManuallyUnloadContactAsync');
            accountUnload();
            publishDMLs();
        }catch(Exception ex){
            thisSamsaraLoggerService.logger.logError('Error in GS_Contact_ManuallyUnloadContactAsync::', new SamsaraLoggerObjectMVP(
                ex, recordsIds
        ));
            throw ex;
        }
        finally {
            thisSamsaraLoggerService.logger.logTrace('Exiting in GS_Contact_ManuallyUnloadContactAsync');
            thisSamsaraLoggerService.logger.dispatch();
        }
    }
    
    
    private void publishDMLs() {
        DMLWrapper.publishDML();
    }
    
    
    public void accountUnload(){
        contactCache.loadPoolUsers();
        poolMap = contactCache.poolMap;
        
        Map<Id, Account> accountByContactId = new Map<Id, Account>();
        Map<Id, List<Contact>> contactsByAccountId = new Map<Id, List<Contact>>();
        for (Contact thisContact : contactsFlaggedToUnloadAccountMap.values()) {
            if (contactsByAccountId.containsKey(thisContact.AccountId)) {
                contactsByAccountId.get(thisContact.AccountId).add(thisContact);
            } else {
                contactsByAccountId.put(thisContact.AccountId, new List<Contact>{thisContact});
            }
        }
        
        
        for (Account acct : new GS_AccountSelector(true).getAccountsByIds(new List<Id>(contactsByAccountId.keySet())))
        {
            for (Contact thisContact : contactsByAccountId.get(acct.Id)) {
                accountByContactId.put(thisContact.Id, acct);
            }
        }
        
        
        for(Contact contact: contactsFlaggedToUnloadAccountMap.values()){
            List<Opportunity> openRevenueOpportunities = new List<Opportunity>();
            List<Opportunity> openFreeTrailOpportunities = new List<Opportunity>();
            String hashtag='';
            
            Account account = accountByContactId.get(contact.Id);
            
            if(account.RecordType.Name <> 'Fleet'){
                poolOwnerId = poolMap.get(account.RecordType.Name);
                recordTypeName = account.RecordType.Name;
            }
            else{
                poolOwnerId = poolMap.get('Fleet');
                recordTypeName = 'Fleet';
            }
            // Only assign to pool if Account_Book_Owner__c is null GTMS-27769
            if(account.Account_Book_Owner__c == null){
            account.OwnerId = poolOwnerId;
             }
            
            if(!String.isBlank(hashtag)){
                hashtag=account.Hashtag__c;
            }
            for(Opportunity opportunity : account.Opportunities){
                if((opportunity.Type == 'Revenue Opportunity') && (opportunity.StageName !='Closed Lost')){
                    openRevenueOpportunities.add(opportunity);
                }
                else if((opportunity.Type == 'Free Trial Opportunity') && (opportunity.Trial_Status__c == 'Open')){
                    openFreeTrailOpportunities.add(opportunity);
                }
            }
            
            if(openRevenueOpportunities.size()>0 || openFreeTrailOpportunities.size()>0){
                CalloutException k = new CalloutException();
                k.setMessage('The account cannot be unloaded: it has either an open revenue opportunity or an open free trial.');
                throw k;
            }
            else if(hashtag.contains('Ex_Closed_Lost')){
                CalloutException k = new CalloutException();
                k.setMessage('The account cannot be unloaded as it is part of a special campaign.');
                throw k;
            }
            else if(account.Status__c=='New' && account.Event_Lead__c){
                CalloutException k = new CalloutException();
                k.setMessage('The account cannot be unloaded: it is an event lead and its account status is still new.');
                throw k;
            }
            else if(account.Status__c=='Attempting' && account.Event_Lead__c){
                if(account.Number_of_Calls_by_Current_Owner__c!=null){
                    if(account.Number_of_Calls_by_Current_Owner__c<8){
                        CalloutException k = new CalloutException();
                        k.setMessage('The account cannot be unloaded: it is an event lead, its account status is still attempting, and it has less than 8 calls by current owner.');
                        throw k;
                    }
                }
            }
            else if(account.Original_Owner_for_Recycling_Campaign__c != null){
                CalloutException k = new CalloutException();
                k.setMessage('The account cannot be unloaded as it is part of a special recycling campaign. Please check the Original Owner for Recycling Campaign field');
                throw k;
            }
            else{
                if (accountUpdates.containsKey(account.Id)) {
                    Account acct = accountUpdates.get(account.Id);
                    acct.OwnerId = account.OwnerId;
                    acct.Unload_Account__c = true;
                } else {
                    account.Unload_Account__c = true;
                    accountUpdates.put(account.Id, account);
                }
                accountIdToPool.put(contact.AccountId, recordTypeName);
            }
        }
        
        if(!accountUpdates.isEmpty()){
            thisSamsaraLoggerService.logger.logInfo('Unloading Account ::',accountUpdates.values());
            List<Account> accountToUpdateList = new List<Account>();
            accountToUpdateList.addAll(accountUpdates.values());
            DMLWrapper.doUpdate(accountToUpdateList);
                }
        if(!accountIdToPool.isEmpty())contactUnload(accountIdToPool);
        
    } 
    
    
    public void contactUnload(Map<Id, String> accountToPool) {
        contactsToUpdateOwner = new Map<Id, Contact>((new GS_ContactSelector(true)).getContactsByAccountIds(accountToPool.keySet()));
        
        for (Contact thisContact : contactsToUpdateOwner.values()) {
            String poolType = accountToPool.get(thisContact.Id) != null ? accountToPool.get(thisContact.Id) : 'Fleet';
            
            thisContact.OwnerId = poolMap.get(poolType);
            contactsToUpdateOwner.put(thisContact.Id, thisContact);
        }
        
        if(!contactsToUpdateOwner.isEmpty()){
            thisSamsaraLoggerService.logger.logInfo('Unloading Contact ::',contactsToUpdateOwner.values());
            List<Contact> contactToUpdateList = new List<Contact>();
            contactToUpdateList.addAll(contactsToUpdateOwner.values());
            DMLWrapper.doUpdate(contactToUpdateList);
        }
    }
    
    public void manuallyUnloadContact(Map<Id, Contact> oldContactMap, Map<Id, Contact> newContactMap, List<Contact> newContactList){
        Set<Id> contactRecordsIds = new Set<Id>();
        for (Contact contact : newContactList) { 
            if((contact.Unload_Account__c == True) && (oldContactMap.get( contact.Id ).Unload_Account__c != newContactMap.get( contact.Id ).Unload_Account__c)) {
                if(contact.Status__c.contains('Retouch') || contact.Status__c=='Delete Account'){
                    contactRecordsIds.add(contact.Id);
                }else{
                    CalloutException k = new CalloutException();
                    k.setMessage('You are trying to unload an account but the contact is not at Retouch or Delete Account statuses.');
                    throw k;
                }
            }
        }
        
        if(!contactRecordsIds.isEmpty()){
            thisSamsaraLoggerService.logger.logInfo('Unloading Contact ::',contactRecordsIds);
            DMLWrapper.doInsert(new GS_Contact_ManuallyUnloadContactAsync().prepareAsyncRequests(contactRecordsIds));
        }
            
    }
    
}