force-app/main/default/objects/Account/fields/Account_Lifetime_ACV__c.field-meta.xml
<CustomField>
    <fullName>Account_Lifetime_ACV__c</fullName>
    <description>Total ACV bookings over lifetime of account (DLRS)</description>
    <label>Account Lifetime ACV</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Billing_Contact__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Billing contact. Required if customer requests terms</description>
    <label>Billing Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Account.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_ARR__c.field-meta.xml
<CustomField>
    <fullName>Customer_ARR__c</fullName>
    <description>Active ACV shows daily changes to annual license revenue via opportunity license start/end date</description>
    <inlineHelpText>Active ACV shows daily changes to annual license revenue via opportunity license start/end date</inlineHelpText>
    <label>Active ACV [USD]</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/DUNS_Number__c.field-meta.xml
<CustomField>
    <fullName>DUNS_Number__c</fullName>
    <description>D&amp;B Number</description>
    <label>DUNS Number</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Justification_for_the_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Justification_for_the_Relationship__c</fullName>
    <label>Justification for the Relationship</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Latest_Active_Contract__c.field-meta.xml
<CustomField>
    <fullName>Latest_Active_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Latest Active Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Number_of_Powered_Assets__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Powered_Assets__c</fullName>
    <label>Number of Powered Assets (Field Input)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Number_of_Vehicles__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Vehicles__c</fullName>
    <label>Number of Vehicles (Field Input)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Organization_Size__c.field-meta.xml
<CustomField>
    <fullName>Organization_Size__c</fullName>
    <description>Number of employees or students</description>
    <inlineHelpText>Number of employees or students</inlineHelpText>
    <label>Organization Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 - 99</fullName>
            </value>
            <value>
                <fullName>100 - 499</fullName>
            </value>
            <value>
                <fullName>500 - 999</fullName>
            </value>
            <value>
                <fullName>1000 - 4999</fullName>
            </value>
            <value>
                <fullName>5000+</fullName>
            </value>
            <value>
                <fullName>0</fullName>
                <isActive>false</isActive>
                <label>0</label>
            </value>
            <value>
                <fullName>1-99</fullName>
                <isActive>false</isActive>
                <label>1-99</label>
            </value>
            <value>
                <fullName>1/1/1999 12:00:00 AM</fullName>
                <isActive>false</isActive>
                <label>1/1/1999 12:00:00 AM</label>
            </value>
            <value>
                <fullName>10</fullName>
                <isActive>false</isActive>
                <label>10</label>
            </value>
            <value>
                <fullName>100 - 999</fullName>
                <isActive>false</isActive>
                <label>100 - 999</label>
            </value>
            <value>
                <fullName>100-499</fullName>
                <isActive>false</isActive>
                <label>100-499</label>
            </value>
            <value>
                <fullName>1000+</fullName>
                <isActive>false</isActive>
                <label>1000+</label>
            </value>
            <value>
                <fullName>1000-4999</fullName>
                <isActive>false</isActive>
                <label>1000-4999</label>
            </value>
            <value>
                <fullName>10000+</fullName>
                <isActive>false</isActive>
                <label>10000+</label>
            </value>
            <value>
                <fullName>11</fullName>
                <isActive>false</isActive>
                <label>11</label>
            </value>
            <value>
                <fullName>13</fullName>
                <isActive>false</isActive>
                <label>13</label>
            </value>
            <value>
                <fullName>200</fullName>
                <isActive>false</isActive>
                <label>200</label>
            </value>
            <value>
                <fullName>201-500</fullName>
                <isActive>false</isActive>
                <label>201-500</label>
            </value>
            <value>
                <fullName>21</fullName>
                <isActive>false</isActive>
                <label>21</label>
            </value>
            <value>
                <fullName>22</fullName>
                <isActive>false</isActive>
                <label>22</label>
            </value>
            <value>
                <fullName>29</fullName>
                <isActive>false</isActive>
                <label>29</label>
            </value>
            <value>
                <fullName>34</fullName>
                <isActive>false</isActive>
                <label>34</label>
            </value>
            <value>
                <fullName>36161</fullName>
                <isActive>false</isActive>
                <label>36161</label>
            </value>
            <value>
                <fullName>42</fullName>
                <isActive>false</isActive>
                <label>42</label>
            </value>
            <value>
                <fullName>495 - 1000</fullName>
                <isActive>false</isActive>
                <label>495 - 1000</label>
            </value>
            <value>
                <fullName>496 - 1000</fullName>
                <isActive>false</isActive>
                <label>496 - 1000</label>
            </value>
            <value>
                <fullName>497 - 1000</fullName>
                <isActive>false</isActive>
                <label>497 - 1000</label>
            </value>
            <value>
                <fullName>498 - 1000</fullName>
                <isActive>false</isActive>
                <label>498 - 1000</label>
            </value>
            <value>
                <fullName>499 - 1000</fullName>
                <isActive>false</isActive>
                <label>499 - 1000</label>
            </value>
            <value>
                <fullName>500 - 1000</fullName>
                <isActive>false</isActive>
                <label>500 - 1000</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Quarantine_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Quarantine_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deactivated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Record_Type_Stamp_for_Dupes__c.field-meta.xml
<CustomField>
    <fullName>Record_Type_Stamp_for_Dupes__c</fullName>
    <label>Record Type Stamp for Dupes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SAM_Number_Undecorated__c.field-meta.xml
<CustomField>
    <fullName>SAM_Number_Undecorated__c</fullName>
    <label>SAM Number Undecorated</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Fleet.recordType-meta.xml
<RecordType>
    <fullName>Fleet</fullName>
    <active>true</active>
    <description>Fleet account</description>
    <label>Fleet</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Organization_Size__c.field-meta.xml
<CustomField>
    <fullName>Organization_Size__c</fullName>
    <formula>TEXT(Account.Organization_Size__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Please edit on the Account page.</inlineHelpText>
    <label>Organization Size</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Record_Type_Stamp_for_Dupes__c.field-meta.xml
<CustomField>
    <fullName>Record_Type_Stamp_for_Dupes__c</fullName>
    <description>Stamped by trigger and cloudingo.</description>
    <label>Record Type Stamp for Dupes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Fleet.recordType-meta.xml
<RecordType>
    <fullName>Fleet</fullName>
    <active>true</active>
    <description>Fleet contact</description>
    <label>Fleet</label>
</RecordType>

force-app/main/default/classes/Batch_AccountHierarchyOneTimeTest.cls
@isTest(SeeAllData=false)
public class Batch_AccountHierarchyOneTimeTest {
    Static Account testAccount;
    public static integer testCount=0;
    public static boolean isDUNSTest= false;

    @isTest static void testAccount_batchExeContractDNBmdt()
    {
        Test.startTest();
        List<Account> newAccount = new List<Account>();
        
        Account account = new Account (Name = 'Test Account RODRIGO Canada', Organization_Size__c = '5000+', Record_Type_Stamp_for_Dupes__c = 'Fleet', 
                                       Number_of_Powered_Assets__c = 200,
                                       BillingCountry = 'Canada', Industry = 'Other', Account_Lifetime_ACV__c=1001, Customer_ARR__c=1000,
                                       Quarantine_Enabled__c = false ,SAM_Number_Undecorated__c='abcabc',DUNS_Number__c = '1122',
                                       Justification_for_the_Relationship__c = '',Number_of_Vehicles__c=0
                                       );
         
        Account account2 = new Account (Name = 'Test Account RODRIGO Canada', Organization_Size__c = '5000+', Record_Type_Stamp_for_Dupes__c = 'Fleet', 
                                       Number_of_Powered_Assets__c = 200,
                                       BillingCountry = 'Canada', Industry = 'Other', Account_Lifetime_ACV__c=1001, Customer_ARR__c=1000,
                                       Quarantine_Enabled__c = false ,SAM_Number_Undecorated__c='abcabc',DUNS_Number__c = '1122',
                                       Justification_for_the_Relationship__c = '',Number_of_Vehicles__c = 0
                                       );
        
        newAccount.add(account);
        newAccount.add(account2);
        insert newAccount;
       
        List<Account> newAccountList = [select id, Latest_Active_Contract__c from Account limit 2];
               system.debug('Jaya test class newAccountList...'+newAccountList);
         
         Contract contract = new Contract(
                AccountId = newAccountList[0].Id,
                StartDate = Date.today(),
                EndDate = Date.today().adddays(1),
                ContractTerm = 12
        );
        insert contract;
                Contract contract1 = [select id from Contract];
       system.debug('Jaya test class contract1...'+contract1);

            newAccountList[0].Latest_Active_Contract__c = contract1.id;
            update newAccountList[0];
        testCount = 0;
        database.executeBatch(new Batch_AccountHierarchyOneTime(), 1);
        testCount = 1;
        database.executeBatch(new Batch_AccountHierarchyOneTime(), 1);
        testCount = 2;
        database.executeBatch(new Batch_AccountHierarchyOneTime(), 1);
        isDUNSTest = false;
        database.executeBatch(new Batch_AccountHierarchyOneTime(), 1);
        isDUNSTest = true;
        database.executeBatch(new Batch_AccountHierarchyOneTime(), 1);
 
        Test.stopTest();
    }
 @isTest static void testAccount_batchExeContact3()
    {
        Test.startTest();
        List<Account> newAccount = new List<Account>();
        
        Account account = new Account (Name = 'Test Account RODRIGO Canada', Organization_Size__c = '5000+', Record_Type_Stamp_for_Dupes__c = 'Fleet', 
                                       Number_of_Powered_Assets__c = 200,
                                       BillingCountry = 'Canada', Industry = 'Other', Account_Lifetime_ACV__c=1001, Customer_ARR__c=1000,
                                       Quarantine_Enabled__c = false,
                                       Justification_for_the_Relationship__c = ''
                                       );
         
        Account account2 = new Account (Name = 'Test Account RODRIGO Canada', Organization_Size__c = '5000+', Record_Type_Stamp_for_Dupes__c = 'Fleet', 
                                       Number_of_Powered_Assets__c = 200,
                                       BillingCountry = 'Canada', Industry = 'Other', Account_Lifetime_ACV__c=1001, Customer_ARR__c=1000,
                                       Quarantine_Enabled__c = false ,
                                       Justification_for_the_Relationship__c = ''
                                       );
        newAccount.add(account);
        newAccount.add(account2);
        insert newAccount;
        
        list<Contact> newContacts = new list<Contact>();
        list<Account> newAccountList = [select id, Latest_Active_Contract__c from Account limit 2];
               system.debug('Jaya test class newAccount1...'+newAccountList);
        
        list<Contract> contractList = new list<Contract>();
        for(Account acc: newAccountList){
            Contract contract = new Contract(
                    AccountId = acc.Id,
                    StartDate = Date.today(),
                    EndDate = Date.today().adddays(1),
                    ContractTerm = 12
            );
            contractList.add(contract);
            
        }
        insert contractList;
        
        Contract contract1 = [select id from Contract limit 1];
        system.debug('Jaya test class contract1...'+contract1);
        
        Contact con = new Contact (FirstName = 'TestClass', LastName = 'Tester', Email = 'ttester@a.com', AccountId=newAccountList[0].Id);
        newContacts.add(con);
        insert newContacts;
        
        Contact con1 = [select id from contact limit 1];
        newAccountList[0].Billing_Contact__c = con1.id;
        update newAccountList[0];
         testCount = 0;
        database.executeBatch(new Batch_AccountHierarchyOneTime(), 1);
        testCount = 1;
        database.executeBatch(new Batch_AccountHierarchyOneTime(), 1);
        testCount = 2;
        database.executeBatch(new Batch_AccountHierarchyOneTime(), 1);
        Test.stopTest();
    }
     @isTest static void testAccount_batchExeDUNSNum4()
    {
        Test.startTest();
        List<Account> newAccount = new List<Account>();
        
        Account account = new Account (Name = 'Test Account RODRIGO Canada', Organization_Size__c = '5000+', Record_Type_Stamp_for_Dupes__c = 'Fleet', 
                                       Number_of_Powered_Assets__c = 200,
                                       BillingCountry = 'Canada', Industry = 'Other', Account_Lifetime_ACV__c=1001, Customer_ARR__c=1000,
                                       Quarantine_Enabled__c = false,
                                       Justification_for_the_Relationship__c = ''
                                       );
         
        Account account2 = new Account (Name = 'Test Account RODRIGO Canada', Organization_Size__c = '5000+', Record_Type_Stamp_for_Dupes__c = 'Fleet', 
                                       Number_of_Powered_Assets__c = 200,
                                       BillingCountry = 'Canada', Industry = 'Other', Account_Lifetime_ACV__c=1001, Customer_ARR__c=1000,
                                       Quarantine_Enabled__c = false ,
                                       Justification_for_the_Relationship__c = ''
                                       );
        newAccount.add(account);
        newAccount.add(account2);
        insert newAccount;
        
        list<Contact> newContacts = new list<Contact>();
        list<Account> newAccountList = [select id, Latest_Active_Contract__c from Account limit 2];
               system.debug('Jaya test class newAccount1...'+newAccountList);
        
        list<Contract> contractList = new list<Contract>();
        for(Account acc: newAccountList){
            Contract contract = new Contract(
                    AccountId = acc.Id,
                    StartDate = Date.today(),
                    EndDate = Date.today().adddays(1),
                    ContractTerm = 12
            );
            contractList.add(contract);
            
        }
        insert contractList;
        
        Contract contract1 = [select id from Contract limit 1];
        system.debug('Jaya test class contract1...'+contract1);
        
        Contact con = new Contact (FirstName = 'TestClass', LastName = 'Tester', Email = 'ttester@a.com', AccountId=newAccountList[0].Id);
        newContacts.add(con);
        insert newContacts;
        
        Contact con1 = [select id from contact limit 1];
        newAccountList[0].Billing_Contact__c = con1.id;
        update newAccountList[0];
        testCount = 0;
        database.executeBatch(new Batch_AccountHierarchyOneTime(), 1);
        testCount = 1;
        database.executeBatch(new Batch_AccountHierarchyOneTime(), 1);
        testCount = 2;
        database.executeBatch(new Batch_AccountHierarchyOneTime(), 1);
        Test.stopTest();
    }
}