force-app/main/default/objects/Account/fields/ADR_Transfer__c.field-meta.xml
<CustomField>
    <fullName>ADR_Transfer__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Was the account created or the first opportunity initiated via an ADR lead transfer?</description>
    <label>ADR Transfer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Billing_Email__c.field-meta.xml
<CustomField>
    <fullName>Billing_Email__c</fullName>
    <label>Billing_Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Organization_Size__c.field-meta.xml
<CustomField>
    <fullName>Organization_Size__c</fullName>
    <description>Number of employees or students</description>
    <inlineHelpText>Number of employees or students</inlineHelpText>
    <label>Organization Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 - 99</fullName>
            </value>
            <value>
                <fullName>100 - 499</fullName>
            </value>
            <value>
                <fullName>500 - 999</fullName>
            </value>
            <value>
                <fullName>1000 - 4999</fullName>
            </value>
            <value>
                <fullName>5000+</fullName>
            </value>
            <value>
                <fullName>0</fullName>
                <isActive>false</isActive>
                <label>0</label>
            </value>
            <value>
                <fullName>1-99</fullName>
                <isActive>false</isActive>
                <label>1-99</label>
            </value>
            <value>
                <fullName>1/1/1999 12:00:00 AM</fullName>
                <isActive>false</isActive>
                <label>1/1/1999 12:00:00 AM</label>
            </value>
            <value>
                <fullName>10</fullName>
                <isActive>false</isActive>
                <label>10</label>
            </value>
            <value>
                <fullName>100 - 999</fullName>
                <isActive>false</isActive>
                <label>100 - 999</label>
            </value>
            <value>
                <fullName>100-499</fullName>
                <isActive>false</isActive>
                <label>100-499</label>
            </value>
            <value>
                <fullName>1000+</fullName>
                <isActive>false</isActive>
                <label>1000+</label>
            </value>
            <value>
                <fullName>1000-4999</fullName>
                <isActive>false</isActive>
                <label>1000-4999</label>
            </value>
            <value>
                <fullName>10000+</fullName>
                <isActive>false</isActive>
                <label>10000+</label>
            </value>
            <value>
                <fullName>11</fullName>
                <isActive>false</isActive>
                <label>11</label>
            </value>
            <value>
                <fullName>13</fullName>
                <isActive>false</isActive>
                <label>13</label>
            </value>
            <value>
                <fullName>200</fullName>
                <isActive>false</isActive>
                <label>200</label>
            </value>
            <value>
                <fullName>201-500</fullName>
                <isActive>false</isActive>
                <label>201-500</label>
            </value>
            <value>
                <fullName>21</fullName>
                <isActive>false</isActive>
                <label>21</label>
            </value>
            <value>
                <fullName>22</fullName>
                <isActive>false</isActive>
                <label>22</label>
            </value>
            <value>
                <fullName>29</fullName>
                <isActive>false</isActive>
                <label>29</label>
            </value>
            <value>
                <fullName>34</fullName>
                <isActive>false</isActive>
                <label>34</label>
            </value>
            <value>
                <fullName>36161</fullName>
                <isActive>false</isActive>
                <label>36161</label>
            </value>
            <value>
                <fullName>42</fullName>
                <isActive>false</isActive>
                <label>42</label>
            </value>
            <value>
                <fullName>495 - 1000</fullName>
                <isActive>false</isActive>
                <label>495 - 1000</label>
            </value>
            <value>
                <fullName>496 - 1000</fullName>
                <isActive>false</isActive>
                <label>496 - 1000</label>
            </value>
            <value>
                <fullName>497 - 1000</fullName>
                <isActive>false</isActive>
                <label>497 - 1000</label>
            </value>
            <value>
                <fullName>498 - 1000</fullName>
                <isActive>false</isActive>
                <label>498 - 1000</label>
            </value>
            <value>
                <fullName>499 - 1000</fullName>
                <isActive>false</isActive>
                <label>499 - 1000</label>
            </value>
            <value>
                <fullName>500 - 1000</fullName>
                <isActive>false</isActive>
                <label>500 - 1000</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/ADR_Transfer__c.field-meta.xml
<CustomField>
    <fullName>ADR_Transfer__c</fullName>
    <defaultValue>false</defaultValue>
    <description>is checked if the contact is an ADR transfer</description>
    <label>ADR Transfer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Organization_Size__c.field-meta.xml
<CustomField>
    <fullName>Organization_Size__c</fullName>
    <formula>TEXT(Account.Organization_Size__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Please edit on the Account page.</inlineHelpText>
    <label>Organization Size</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <defaultValue>&apos;Other&apos;</defaultValue>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>a16z EBC</fullName>
            </value>
            <value>
                <fullName>Adwords</fullName>
            </value>
            <value>
                <fullName>Bing</fullName>
            </value>
            <value>
                <fullName>BuyerZone</fullName>
            </value>
            <value>
                <fullName>Capterra</fullName>
            </value>
            <value>
                <fullName>Chatbot</fullName>
            </value>
            <value>
                <fullName>Customer Referral</fullName>
            </value>
            <value>
                <fullName>Deal Reg Form</fullName>
            </value>
            <value>
                <fullName>Deal Reg Form - Industrial</fullName>
            </value>
            <value>
                <fullName>Events</fullName>
            </value>
            <value>
                <fullName>Facebook Form</fullName>
            </value>
            <value>
                <fullName>Free Trial Request Form</fullName>
            </value>
            <value>
                <fullName>Inbound call / email</fullName>
            </value>
            <value>
                <fullName>LinkedIn Form</fullName>
            </value>
            <value>
                <fullName>List Import (no prior engagement)</fullName>
            </value>
            <value>
                <fullName>Marketing Email</fullName>
            </value>
            <value>
                <fullName>MVF</fullName>
            </value>
            <value>
                <fullName>ReadyQuote</fullName>
            </value>
            <value>
                <fullName>Outbound call / email / linkedin</fullName>
            </value>
            <value>
                <fullName>Partner referral</fullName>
            </value>
            <value>
                <fullName>Referral (Unpaid)</fullName>
            </value>
            <value>
                <fullName>Support Issue</fullName>
            </value>
            <value>
                <fullName>Webinar Registration Form</fullName>
            </value>
            <value>
                <fullName>Website form</fullName>
            </value>
            <value>
                <fullName>YouTube</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Partner Application Form</fullName>
            </value>
            <value>
                <fullName>Adwords (Industrial)</fullName>
            </value>
            <value>
                <fullName>Website Visitor</fullName>
            </value>
            <value>
                <fullName>Software Advice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ADR_Transfer__c.field-meta.xml
<CustomField>
    <fullName>ADR_Transfer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ADR Transfer</label>
    <referenceTo>ADR_Transfer_Log__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Send_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Send_Invoice__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked when a FT Invoice is sent to the customer (shown as quote object)</description>
    <inlineHelpText>Checked when a FT Invoice is sent to the customer (shown as quote object)</inlineHelpText>
    <label>Send Invoice</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Shipmate_Oppty_Owner__c.field-meta.xml
<CustomField>
    <fullName>Shipmate_Oppty_Owner__c</fullName>
    <formula>Owner.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Shipmate - Oppty Owner</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Shipping_Contact__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Shipping Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunity_Shipping_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Trial_Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Trial_Primary_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Primary contact for Trial - this is the person who will sign the Trial Agreement</description>
    <inlineHelpText>Person who will sign Trial Agreement</inlineHelpText>
    <label>Trial Primary Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Trial Primary Contact)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Source__c/Source__c.object-meta.xml
<CustomObject>
    <label>Source</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Source Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Source__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Source</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sources</relationshipLabel>
    <relationshipName>Sources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FreeTrialInvoiceTest.cls
//@isTest(SeeAllData=true)
@isTest
public class FreeTrialInvoiceTest{
    @testSetup
    private static void avalaraSetup() {
        
    }

	@isTest
	static void testFreeTrialAutomation() {

	    
		
         Account a = new Account (Name = 'Sla Co', Organization_Size__c = '5000+', BillingCountry = 'Canada', Industry = 'Other', ADR_Transfer__c = false);
         insert a;
                
         Contact c = new Contact(AccountId = a.Id, FirstName = 'Cntc', LastName = 'Test', OwnerId = '0051a0000015njF', Source__c = 'Facebook Form', Email='daniel.cervoni@samsara.com');  
         insert c;
        
         Opportunity o = new Opportunity(Name='Oppty 1', CloseDate = System.Today(), AccountId =a.Id, StageName='Proposal', Trial_Primary_Contact__c = c.Id, OwnerId = '0051a0000015njF');
         insert o;

         o.Send_Invoice__c = true;
         update o;

         System.assertEquals(true,true);
         SYstem.debug('inserted stuff NRNRNR');
         Quote q = new Quote();
         q.Name = 'FT Quote-' + o.name;
         q.OpportunityId = o.Id;
         q.PriceBook2Id = o.PriceBook2Id;
         q.ContactId = o.Trial_Primary_Contact__c;
         q.BillingName = o.Account.Name;
             //List<Account> a = [SELECT Billing_Email__c, BillingCountry FROM Account WHERE Id =: o.AccountId LIMIT 1];
             //q.Email = a[0].Billing_Email__c;
             //System.debug('off account');
             //System.debug(a[0].Billing_Email__c);
         q.Email = o.Account.Billing_Email__c;

            
         //    /*List<Contact> u = [select Id, Email from Contact where Id =: o.Shipping_Contact__c limit 1];
         //    String contactId = '0031a00000MWtFD';
         //    if (u.size() > 0){
         //        contactId = u[0].Id;
         //    }*/
         insert q;

         /*EmailTemplate et = new EmailTemplate(developerName = 'test', FolderId = UserInfo.getUserId(), TemplateType= 'Text', Name = 'test');
	     insert et;

	     OrgWideEmailAddress owa = new OrgWideEmailAddress(Address = 'trials@samsara.com');
	     //insert owa;*/

	    EmailTemplate et = [Select Id, Subject, HtmlValue, Body from EmailTemplate where Name = 'FT Invoice Email'];
		OrgWideEmailAddress owa = [select Id from OrgWideEmailAddress Where Address = 'trials@samsara.com'];

         Test.startTest();

         FreeTrialInvoicing.sendEmail(q.id, o.id,o.Trial_Primary_Contact__r.Id, o.Shipmate_Oppty_Owner__c, o.Trial_Primary_Contact__r.Email,owa.Id,et.Id);

         Test.stopTest();

         System.assertEquals(true,true);
     }


}