force-app/main/default/objects/Account/fields/AE_Notes__c.field-meta.xml
<CustomField>
    <fullName>AE_Notes__c</fullName>
    <label>AE Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/SE_Assignment__c.field-meta.xml
<CustomField>
    <fullName>SE_Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Populate SE based on Account Owner (Process Builder)</description>
    <label>SE Assignment</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts8</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Async_Request__c/Async_Request__c.object-meta.xml
<CustomObject>
    <description>Use to queue up an Asynchronous Request for processing</description>
    <label>Async Request</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Async Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Async Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Async_Request__c/fields/Options__c.field-meta.xml
<CustomField>
    <fullName>Options__c</fullName>
    <description>Additional Options that can be used when processing the request</description>
    <label>Options</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Async_Request__c/fields/Params__c.field-meta.xml
<CustomField>
    <fullName>Params__c</fullName>
    <label>Params</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <label>Notes</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Owner_Role_Copy__c.field-meta.xml
<CustomField>
    <fullName>Owner_Role_Copy__c</fullName>
    <description>Stores the role of the owner of the opportunity at the time it became a closed won.</description>
    <label>Owner Role Copy</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SE_Assignment__c.field-meta.xml
<CustomField>
    <fullName>SE_Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SE Assignment</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SE_Key_Account__c.field-meta.xml
<CustomField>
    <fullName>SE_Key_Account__c</fullName>
    <description>Checks if Key Account thresholds are met for ACV and deal stage</description>
    <formula>AND(
  OR(
        AND(Probability &gt;= 0.35,
            Probability &lt;= 1.0),
        ISPICKVAL(StageName, &quot;Closed Lost&quot;)
        ),
    OR(
(SE_Key_Account_Override__c = true),
        AND
(

OR(
  AND(
    CONTAINS(Owner_Role_Copy__c,&quot;SLED&quot;),
    ACV_Bookings_SOT__c&gt;=75000))),
  AND(
    CONTAINS(Owner_Role_Copy__c,&quot;AE2&quot;), 
    CONTAINS(Owner_Role_Copy__c,&quot;US&quot;),
    ACV_Bookings_SOT__c&gt;=50000),
  AND(
    CONTAINS(Owner_Role_Copy__c,&quot;AE3&quot;),
    CONTAINS(Owner_Role_Copy__c,&quot;US&quot;),
    ACV_Bookings_SOT__c&gt;=125000),

        AND(Account.BillingCountry=&quot;Canada&quot;, ACV_Bookings_SOT__c&gt;=50000*1.4),
        AND(Account.Global_Geography__c = &quot;Mexico&quot;, ACV_Bookings_SOT__c&gt;= (58411.21495*17.12)),
        AND(Account.Global_Geography__c=&quot;UK &amp; I&quot;,ACV_Bookings_SOT__c&gt;=(50000*0.86)),
        AND(Account.Global_Geography__c=&quot;France&quot;,ACV_Bookings_SOT__c&gt;=(30000* 0.98)),
        AND(Account.Global_Geography__c=&quot;DACH&quot;,ACV_Bookings_SOT__c&gt;=(30000 * 0.98)),
        AND(Account.Global_Geography__c=&quot;BENELUX&quot;,ACV_Bookings_SOT__c&gt;=(20000* 0.98))
))</formula>
    <inlineHelpText>Checks if Key Account thresholds are met for ACV and deal stage</inlineHelpText>
    <label>SE Key Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Segment_Sales_Role__c.field-meta.xml
<CustomField>
    <fullName>Segment_Sales_Role__c</fullName>
    <description>Based on owner role copy, used to classify opportunities by sales segment.</description>
    <formula>IF( 
    OR( 
        CONTAINS(Owner_Role_Copy__c,&quot;AE1&quot;), 
        CONTAINS(Owner_Role_Copy__c,&quot;SMB&quot;),
        CONTAINS(Owner_Role_Copy__c,&quot;SB&quot;), 
        AND(
        CONTAINS(Owner_Role_Copy__c,&quot;Fleet IS VP&quot;),
        CONTAINS(Finance_Segment_Stamp__c,&quot;SMB&quot;)),
        Small_Fleet_Opportunity__c 
        ),&quot;AE1&quot;,
IF(
    OR(
        CONTAINS(Owner_Role_Copy__c,&quot;IND&quot;), 
        CONTAINS(Owner_Role_Copy__c,&quot;Industrial&quot;),
        CONTAINS(Owner_Role_Copy__c, &quot;Equipment&quot;)
        ), &quot;Industrial&quot;,


IF(
    OR(
        CONTAINS(Owner_Role_Copy__c,&quot;CNWKR&quot;), 
        CONTAINS(Owner_Role_Copy__c,&quot;Connected&quot;),
        CONTAINS(Owner_Role_Copy__c, &quot;Sites&quot;)
        ),&quot;Connected Worker&quot;,


IF( 
    AND ( 
        OR(
            CONTAINS(Owner_Role_Copy__c,&quot;AE2&quot;), 
            CONTAINS(Owner_Role_Copy__c,&quot;MM&quot;),
            CONTAINS(Owner_Role_Copy__c,&quot;IS EMEA&quot;)
        ), 
            NOT(CONTAINS(Owner_Role_Copy__c,&quot;Industrial&quot;)),
            NOT(CONTAINS(Owner_Role_Copy__c,&quot;Connected Worker&quot;))
    ),&quot;AE2&quot;,

IF( 
    AND ( 
        OR(
            CONTAINS(Owner_Role_Copy__c,&quot;AE3&quot;), 
            CONTAINS(Owner_Role_Copy__c,&quot;MM&quot;)
            ), 
            NOT(CONTAINS(Owner_Role_Copy__c,&quot;Industrial&quot;)),
            NOT(CONTAINS(Owner_Role_Copy__c,&quot;Connected Worker&quot;))
            ),&quot;AE3&quot;,


IF(
    OR(
        CONTAINS(Owner_Role_Copy__c,&quot;Major&quot;),
        CONTAINS(Owner_Role_Copy__c,&quot;ENT&quot;),
        CONTAINS(Owner_Role_Copy__c,&quot;Enterprise&quot;),
        CONTAINS(Owner_Role_Copy__c,&quot;Field&quot;)
        ),&quot;Enterprise&quot;,

IF(
    OR(
        CONTAINS(Owner_Role_Copy__c,&quot;Management&quot;),
        CONTAINS(Owner_Role_Copy__c,&quot;EVP&quot;),
        CONTAINS(Owner_Role_Copy__c,&quot;Operations&quot;)
        ),&quot;Management&quot;,
IF(
    CONTAINS(Owner_Role_Copy__c, &quot;Renewal&quot;), &quot;Renewals&quot;,
&quot; &quot;))))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Segment (Sales Role)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TrialResolutionOppty__c.field-meta.xml
<CustomField>
    <fullName>TrialResolutionOppty__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reference to a Trial&apos;s Revenue or Return opportunity.</description>
    <label>Revenue Opportunity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Opportunity.Type</field>
            <operation>equals</operation>
            <value>Revenue Opportunity, Free Trial Return, Revenue Opportunity - Bill Only</value>
        </filterItems>
        <filterItems>
            <field>Opportunity.StageName</field>
            <operation>notEqual</operation>
            <value>Closed Won</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunities (Trial Resolution Oppty)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Engineering_Log__c/Sales_Engineering_Log__c.object-meta.xml
<CustomObject>
    <label>Sales Engineering Log</label>
    <nameField>
        <displayFormat>SE-{0000}</displayFormat>
        <label>SE Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Engineering Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Engineering_Log__c/fields/AE_Notes__c.field-meta.xml
<CustomField>
    <fullName>AE_Notes__c</fullName>
    <label>AE Notes</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Sales_Engineering_Log__c/fields/Key_Account__c.field-meta.xml
<CustomField>
    <fullName>Key_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Key Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales_Engineering_Log__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity.Type</field>
            <operation>equals</operation>
            <value>Revenue Opportunity</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Sales Engineering Logs</relationshipLabel>
    <relationshipName>Sales_Engineering_Logs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Engineering_Log__c/fields/SE_Assignment__c.field-meta.xml
<CustomField>
    <fullName>SE_Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Renamed the field Label for GTMS-19974.</description>
    <label>Assigned SE</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>contains</operation>
            <value>SE</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Sales_Engineering_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Engineering_Log__c/fields/SE_Follow_Up_Date__c.field-meta.xml
<CustomField>
    <fullName>SE_Follow_Up_Date__c</fullName>
    <label>SE Follow Up Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Sales_Engineering_Log__c/fields/Tech_Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Tech_Close_Date__c</fullName>
    <label>SE Close Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Sales_Engineering_Log__c/fields/Tech_Stage__c.field-meta.xml
<CustomField>
    <fullName>Tech_Stage__c</fullName>
    <label>Tech Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Key Account Identified</fullName>
            </value>
            <value>
                <fullName>Technical Discovery</fullName>
            </value>
            <value>
                <fullName>Trial Management</fullName>
            </value>
            <value>
                <fullName>Technical Proposal</fullName>
            </value>
            <value>
                <fullName>Tech Win</fullName>
            </value>
            <value>
                <fullName>Tech Loss</fullName>
            </value>
            <value>
                <fullName>Solution Design</fullName>
                <isActive>false</isActive>
                <label>Solution Design</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Engineering_Log__c/fields/Trial_gear_ship_date__c.field-meta.xml
<CustomField>
    <fullName>Trial_gear_ship_date__c</fullName>
    <label>Trial gear ship date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Sales_Engineering_Log__c/fields/Trial_Hardware_Install_date__c.field-meta.xml
<CustomField>
    <fullName>Trial_Hardware_Install_date__c</fullName>
    <label>Trial Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Sales_Engineering_Log__c/recordTypes/EMEA_SE_Log.recordType-meta.xml
<RecordType>
    <fullName>EMEA_SE_Log</fullName>
    <active>true</active>
    <description>EMEA SE Log Record Type with country-specific customizations and related automations so that the EMEA Sales Engineering (SE) team can maintain accurate, region-specific data quality and ensure timely updates to their activities.</description>
    <label>EMEA SE Log</label>
</RecordType>

force-app/main/default/classes/OpportunityToSELogsServiceAsync.cls
public with sharing class OpportunityToSELogsServiceAsync extends BaseAsyncHandler{
    gslib_IModuleLogger thisModuleLogger = gslib_LoggerService.getModuleLogger('GTMS');
    gslib_ILogger thisLogger = thisModuleLogger.getLogger(); 
    public override String getRequestType(){
        return 'Sales Engineering Logs Job';
    }

    List<Schema.SObjectType> MY_SOBJECTS = new List<Schema.SObjectType>{
        Sales_Engineering_Log__c.SObjectType
    };

    public static final Date FOLLOW_UP_DATE = System.today().addDays(7);
    public static final String TECH_STAGE_TEXT = Label.Sales_Engineering_Default_Tech_Stage;
    @TestVisible private static Boolean PERFORM_DMLS = true;

    @TestVisible List<Id> recordsIds;
    private Options option;
    
    @TestVisible Map<Id, Opportunity> queriedOppMap;
    private Set<Id> oppIdSetWithLogs;
    private OpportunityToSELogsService serviceRef;

    public override void execute(Async_Request__c ar)
    {
        recordsIds = ar.Params__c.split(PARAMETERS_SPLITTER);
        if(recordsIds.isEmpty()) return;
        option = (Options) JSON.deserialize(ar.Options__c, Options.class);

        DMLWrapper.intializeUnitOfWork(MY_SOBJECTS);
        
        serviceRef = new OpportunityToSELogsService();

        try{
            thisLogger.logTrace('Entering in OpportunityToSELogsServiceAsync');
            switch on option.Operation {
                when 'Insert' {
                    this.handleCreateLogs(recordsIds);
                }
            }
        }catch(Exception ex){
            System.debug('ON EXCEPTION: '+ex.getMessage()+' --- '+ex.getStackTraceString());
            thisLogger.logError(
                'Error in OpportunityToSELogsServiceAsync::',
                new SamsaraLoggerObjectMVP(
                    ex, recordsIds
                )
            );
            throw ex;
        }finally{
            thisLogger.dispatch();
        }
    }

    @TestVisible
    private void fetchOpportunities(List<Id> oppIds){
        if (queriedOppMap == null || queriedOppMap.isEmpty()){
            queriedOppMap = new Map<Id, Opportunity>([
                SELECT Id, SE_Key_Account__c,Owner_Role_Copy__c, StageName, Segment_Sales_Role__c, RecordTypeId, CloseDate, Account.SE_Assignment__c, TrialResolutionOppty__c, TrialResolutionOppty__r.CloseDate, TrialResolutionOppty__r.Notes__c, TrialResolutionOppty__r.Account.SE_Assignment__c
                  FROM Opportunity
                WHERE Id IN :oppIds  AND StageName NOT IN ('Closed Won', 'Closed Lost') AND IsClosed = FALSE
            ]);
        }
    }

    public void handleCreateLogs(List<Id> oppIds){
        fetchOpportunities(oppIds);

        // Get all existing Sales Logs
        fetchExistingLogsForOppId(queriedOppMap);
        
        // Start creating logs
        for (Id oppId : queriedOppMap.keySet()){
            Opportunity opp = queriedOppMap.get(oppId);

            System.debug(JSON.serializePretty(opp));

            if (serviceRef.isEnterprise(opp)){
                if (serviceRef.shouldRunTrial(opp)){
                    this.createLog(
                        opp.TrialResolutionOppty__c,
                        opp.TrialResolutionOppty__r.Account.SE_Assignment__c,
                        opp.TrialResolutionOppty__r.CloseDate,
                        null,
                        null,
                        opp.CloseDate,
                        opp.CloseDate,
                        opp.TrialResolutionOppty__r.Notes__c,
                        opp.Owner_Role_Copy__c
                    );
                } else if (serviceRef.shouldRunStandard(opp)){
                    this.createLog(
                        opp.Id,
                        opp.Account.SE_Assignment__c,
                        opp.CloseDate,
                        null,
                        null,
                        null,
                        null,
                        null,
                        opp.Owner_Role_Copy__c
                    );
                }
            }else if (serviceRef.isKeyAccount(opp) && serviceRef.shouldRunStandard(opp)){
                this.createLog(
                    opp.Id,
                    opp.Account.SE_Assignment__c,
                    opp.CloseDate,
                    FOLLOW_UP_DATE,
                    TECH_STAGE_TEXT,
                    null,
                    null,
                    null,
                    opp.Owner_Role_Copy__c
                );                
            }
        }

        if (PERFORM_DMLS) DMLWrapper.publishDML();
    }

    private Set<Id> getAllOppIdsFromMap(Map<Id, Opportunity> oppMap){
        Set<Id> idSet = new Set<Id>();
        for (Id oppId : oppMap.keySet()){
            Opportunity opp = oppMap.get(oppId);

            idSet.add(oppId);
            if (opp.TrialResolutionOppty__c != null) idSet.add(opp.TrialResolutionOppty__c);
        }

        return idSet;
    }

    @TestVisible
    private void fetchExistingLogsForOppId(Map<Id, Opportunity> oppMap){
        if (oppIdSetWithLogs == null || oppIdSetWithLogs.isEmpty()){
            Set<Id> querySet = this.getAllOppIdsFromMap(oppMap);

            oppIdSetWithLogs = new Set<Id>();
            for (Sales_Engineering_Log__c log : [
                SELECT Opportunity__c
                FROM Sales_Engineering_Log__c
                WHERE Opportunity__c IN :querySet
            ]){
                oppIdSetWithLogs.add(log.Opportunity__c);
            }
        }
    }

    private void createLog(Id opportunityId, Id SE_Assignment, Date techCloseDate, Date SEFollowUpDate, String techStage, Date TrialOpptyCloseDateforInstall, Date TrialOpptyCloseDateforGear, String AENotes, String ownerRoleCopy ){
        if (oppIdSetWithLogs.contains(opportunityId)) return;

           Sales_Engineering_Log__c seLogRec = new Sales_Engineering_Log__c(
                Opportunity__c = opportunityId,
                SE_Assignment__c = SE_Assignment,
                Tech_Close_Date__c = techCloseDate, 
                SE_Follow_Up_Date__c = SEFollowUpDate,
                Tech_Stage__c = techStage,
                Trial_Hardware_Install_date__c = TrialOpptyCloseDateforInstall,
                Trial_gear_ship_date__c = TrialOpptyCloseDateforGear,
                AE_Notes__c = AENotes         
             );
        if (ownerRoleCopy != null && !String.isBlank(ownerRoleCopy) && ownerRoleCopy.contains('EMEA')) {
            seLogRec.RecordTypeId = Schema.SObjectType.Sales_Engineering_Log__c.getRecordTypeInfosByDeveloperName().get('EMEA_SE_Log').getRecordTypeId();
            seLogRec.Key_Account__c = true;
        } 
        DMLWrapper.doInsert(seLogRec);        
    }
    
    public class Options {
        public String Operation {get; set;}
        
        public Options(String operation){
            this.Operation = operation;
        }
    }
}