force-app/main/default/objects/Account/fields/Approved_Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Approved_Payment_Type__c</fullName>
    <label>Approved Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Billing_Email__c.field-meta.xml
<CustomField>
    <fullName>Billing_Email__c</fullName>
    <label>Billing_Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fleet</fullName>
                <default>true</default>
                <label>Fleet</label>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
            <value>
                <fullName>Machine Vision</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Organization_Size__c.field-meta.xml
<CustomField>
    <fullName>Organization_Size__c</fullName>
    <description>Number of employees or students</description>
    <inlineHelpText>Number of employees or students</inlineHelpText>
    <label>Organization Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 - 99</fullName>
            </value>
            <value>
                <fullName>100 - 499</fullName>
            </value>
            <value>
                <fullName>500 - 999</fullName>
            </value>
            <value>
                <fullName>1000 - 4999</fullName>
            </value>
            <value>
                <fullName>5000+</fullName>
            </value>
            <value>
                <fullName>0</fullName>
                <isActive>false</isActive>
                <label>0</label>
            </value>
            <value>
                <fullName>1-99</fullName>
                <isActive>false</isActive>
                <label>1-99</label>
            </value>
            <value>
                <fullName>1/1/1999 12:00:00 AM</fullName>
                <isActive>false</isActive>
                <label>1/1/1999 12:00:00 AM</label>
            </value>
            <value>
                <fullName>10</fullName>
                <isActive>false</isActive>
                <label>10</label>
            </value>
            <value>
                <fullName>100 - 999</fullName>
                <isActive>false</isActive>
                <label>100 - 999</label>
            </value>
            <value>
                <fullName>100-499</fullName>
                <isActive>false</isActive>
                <label>100-499</label>
            </value>
            <value>
                <fullName>1000+</fullName>
                <isActive>false</isActive>
                <label>1000+</label>
            </value>
            <value>
                <fullName>1000-4999</fullName>
                <isActive>false</isActive>
                <label>1000-4999</label>
            </value>
            <value>
                <fullName>10000+</fullName>
                <isActive>false</isActive>
                <label>10000+</label>
            </value>
            <value>
                <fullName>11</fullName>
                <isActive>false</isActive>
                <label>11</label>
            </value>
            <value>
                <fullName>13</fullName>
                <isActive>false</isActive>
                <label>13</label>
            </value>
            <value>
                <fullName>200</fullName>
                <isActive>false</isActive>
                <label>200</label>
            </value>
            <value>
                <fullName>201-500</fullName>
                <isActive>false</isActive>
                <label>201-500</label>
            </value>
            <value>
                <fullName>21</fullName>
                <isActive>false</isActive>
                <label>21</label>
            </value>
            <value>
                <fullName>22</fullName>
                <isActive>false</isActive>
                <label>22</label>
            </value>
            <value>
                <fullName>29</fullName>
                <isActive>false</isActive>
                <label>29</label>
            </value>
            <value>
                <fullName>34</fullName>
                <isActive>false</isActive>
                <label>34</label>
            </value>
            <value>
                <fullName>36161</fullName>
                <isActive>false</isActive>
                <label>36161</label>
            </value>
            <value>
                <fullName>42</fullName>
                <isActive>false</isActive>
                <label>42</label>
            </value>
            <value>
                <fullName>495 - 1000</fullName>
                <isActive>false</isActive>
                <label>495 - 1000</label>
            </value>
            <value>
                <fullName>496 - 1000</fullName>
                <isActive>false</isActive>
                <label>496 - 1000</label>
            </value>
            <value>
                <fullName>497 - 1000</fullName>
                <isActive>false</isActive>
                <label>497 - 1000</label>
            </value>
            <value>
                <fullName>498 - 1000</fullName>
                <isActive>false</isActive>
                <label>498 - 1000</label>
            </value>
            <value>
                <fullName>499 - 1000</fullName>
                <isActive>false</isActive>
                <label>499 - 1000</label>
            </value>
            <value>
                <fullName>500 - 1000</fullName>
                <isActive>false</isActive>
                <label>500 - 1000</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Fleet.recordType-meta.xml
<RecordType>
    <fullName>Fleet</fullName>
    <active>true</active>
    <description>Fleet account</description>
    <label>Fleet</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <description>Account type for partners - resellers, referral partners, corporate partners</description>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Organization_Size__c.field-meta.xml
<CustomField>
    <fullName>Organization_Size__c</fullName>
    <formula>TEXT(Account.Organization_Size__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Please edit on the Account page.</inlineHelpText>
    <label>Organization Size</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <defaultValue>&apos;Other&apos;</defaultValue>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>a16z EBC</fullName>
            </value>
            <value>
                <fullName>Adwords</fullName>
            </value>
            <value>
                <fullName>Bing</fullName>
            </value>
            <value>
                <fullName>BuyerZone</fullName>
            </value>
            <value>
                <fullName>Capterra</fullName>
            </value>
            <value>
                <fullName>Chatbot</fullName>
            </value>
            <value>
                <fullName>Customer Referral</fullName>
            </value>
            <value>
                <fullName>Deal Reg Form</fullName>
            </value>
            <value>
                <fullName>Deal Reg Form - Industrial</fullName>
            </value>
            <value>
                <fullName>Events</fullName>
            </value>
            <value>
                <fullName>Facebook Form</fullName>
            </value>
            <value>
                <fullName>Free Trial Request Form</fullName>
            </value>
            <value>
                <fullName>Inbound call / email</fullName>
            </value>
            <value>
                <fullName>LinkedIn Form</fullName>
            </value>
            <value>
                <fullName>List Import (no prior engagement)</fullName>
            </value>
            <value>
                <fullName>Marketing Email</fullName>
            </value>
            <value>
                <fullName>MVF</fullName>
            </value>
            <value>
                <fullName>ReadyQuote</fullName>
            </value>
            <value>
                <fullName>Outbound call / email / linkedin</fullName>
            </value>
            <value>
                <fullName>Partner referral</fullName>
            </value>
            <value>
                <fullName>Referral (Unpaid)</fullName>
            </value>
            <value>
                <fullName>Support Issue</fullName>
            </value>
            <value>
                <fullName>Webinar Registration Form</fullName>
            </value>
            <value>
                <fullName>Website form</fullName>
            </value>
            <value>
                <fullName>YouTube</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Partner Application Form</fullName>
            </value>
            <value>
                <fullName>Adwords (Industrial)</fullName>
            </value>
            <value>
                <fullName>Website Visitor</fullName>
            </value>
            <value>
                <fullName>Software Advice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Fleet.recordType-meta.xml
<RecordType>
    <fullName>Fleet</fullName>
    <active>true</active>
    <description>Fleet contact</description>
    <label>Fleet</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <description>Partner contacts</description>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/Lead/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <defaultValue>&quot;Fleet&quot;</defaultValue>
    <description>This field on the Lead object determines what record type a lead converts to (i.e. End_Customer or Industrial_Account).</description>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fleet</fullName>
                <default>true</default>
                <label>Fleet</label>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Machine Vision</fullName>
            </value>
            <value>
                <fullName>Connected Worker</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Is_Deal_Registration__c.field-meta.xml
<CustomField>
    <fullName>Is_Deal_Registration__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Deal Registration</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Organization_Size__c.field-meta.xml
<CustomField>
    <fullName>Organization_Size__c</fullName>
    <description>Number of employees or students</description>
    <inlineHelpText>Number of employees or students</inlineHelpText>
    <label>Organization Size</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1 - 99</fullName>
                <default>true</default>
                <label>1 - 99</label>
            </value>
            <value>
                <fullName>100 - 499</fullName>
            </value>
            <value>
                <fullName>500 - 999</fullName>
            </value>
            <value>
                <fullName>1000 - 4999</fullName>
            </value>
            <value>
                <fullName>5000+</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>Used for the lead field mapping process. Copies the lead source value into the Account &amp; Contact.</description>
    <formula>TEXT(LeadSource)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Source</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/Channel_Registration.recordType-meta.xml
<RecordType>
    <fullName>Channel_Registration</fullName>
    <active>true</active>
    <businessProcess>New Default Lead Process</businessProcess>
    <description>Lead record for channel registrations from Impartner (partner portal)</description>
    <label>Channel Registration</label>
</RecordType>

force-app/main/default/objects/Lead/recordTypes/Partner_Application.recordType-meta.xml
<RecordType>
    <fullName>Partner_Application</fullName>
    <active>true</active>
    <businessProcess>Partner Application</businessProcess>
    <description>A Lead record to capture the partner application request from the Webform</description>
    <label>Partner Application</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Is_Deal_Registration__c.field-meta.xml
<CustomField>
    <fullName>Is_Deal_Registration__c</fullName>
    <defaultValue>false</defaultValue>
    <description>add for GTMS-25130</description>
    <label>Is Deal Registration</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Partner_Registration__c/Partner_Registration__c.object-meta.xml
<CustomObject>
    <description>created for GTMS-20584</description>
    <label>Partner Registration</label>
    <nameField>
        <displayFormat>PR-{000000}</displayFormat>
        <label>Partner Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Registrations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Registration__c/fields/Is_Deal_Registration__c.field-meta.xml
<CustomField>
    <fullName>Is_Deal_Registration__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Deal Registration</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Partner_Registration__c/fields/Organization_Size__c.field-meta.xml
<CustomField>
    <fullName>Organization_Size__c</fullName>
    <label>Organization Size</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1 - 99</fullName>
            </value>
            <value>
                <fullName>100 - 499</fullName>
            </value>
            <value>
                <fullName>500 - 999</fullName>
            </value>
            <value>
                <fullName>1000 - 4999</fullName>
            </value>
            <value>
                <fullName>5000+</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Registration__c/recordTypes/Partner_Application.recordType-meta.xml
<RecordType>
    <fullName>Partner_Application</fullName>
    <active>true</active>
    <label>Partner Application</label>
</RecordType>

force-app/main/default/objects/Source__c/Source__c.object-meta.xml
<CustomObject>
    <label>Source</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Source Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Source__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Source</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sources</relationshipLabel>
    <relationshipName>Sources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Payment_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Direct Monthly</fullName>
    </customValue>
    <customValue>
        <fullName>Direct Annual</fullName>
    </customValue>
    <customValue>
        <fullName>Upfront Payments</fullName>
    </customValue>
    <customValue>
        <fullName>Direct Quarterly</fullName>
    </customValue>
    <customValue>
        <fullName>Direct Semi-Annual</fullName>
    </customValue>
    <masterLabel>Payment Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CRLeadToPRConversionOneTimeBatch_Test.cls
@IsTest
public class CRLeadToPRConversionOneTimeBatch_Test {
    
    @TestSetup
    public static void setup(){
        
        //Create Partner Account
        String orgId = UserInfo.getOrganizationId();
        RecordType accountPartnerRT = [Select Id from RecordType Where SObjectType = 'Account' and Name = 'Partner' LIMIT 1]; 
        Account partnerAccount = new Account(Name='Partner Account', Organization_Size__c='1 - 99', BillingCountry='Belgium', BillingCountryCode = 'BE', RecordTypeId = accountPartnerRT.Id);
        insert partnerAccount;
        
        //Emable as Partner
        partnerAccount.IsPartner = true;
        update partnerAccount;
        
        //Create Partner Contact
        RecordType contactPartnerRT = [Select Id from RecordType Where SObjectType = 'Contact' and Name = 'Partner' LIMIT 1]; 
        Contact partnerContact = new Contact(FirstName = 'Partner', LastName = 'Contact', AccountId = partnerAccount.Id, Email = 'partner@test.com'+orgId);
        insert partnerContact;
        
        //Create Partner User
        Profile partnerProfile = [SELECT Id FROM Profile WHERE Name = 'Samsara Partner Community Login License User'];
        String dateString = String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
        Integer randomInt = Integer.valueOf(math.rint(math.random()*1000000));
        String uniqueName = orgId + dateString + randomInt;
        User partnerUser = new User(lastName = partnerContact.LastName,
                                    email = partnerContact.Email,
                                    Username = partnerContact.Email,
                                    ContactId = partnerContact.Id,
                                    EmailEncodingKey = 'ISO-8859-1',
                                    Alias = uniqueName.substring(10, 15),
                                    TimeZoneSidKey = 'America/Los_Angeles',
                                    LocaleSidKey = 'en_US',
                                    LanguageLocaleKey = 'en_US',
                                    ProfileId = partnerProfile.Id,
                                    EmployeeNumber='123');
        insert partnerUser;
    }
    
    public static Account createAccount(String accountName, string paymentType, string userId, string currencyVal){
        Account testAccount = new Account();
        testAccount.Name = accountName;
        testAccount.Industry = 'Biotechnology';
        testAccount.Organization_Size__c = '500 - 999';
        testAccount.BillingStreet = '123 main';
        testAccount.BillingCity = 'Missoula';
        testAccount.BillingState = 'California';
        testAccount.BillingCountry = 'United States';
        testAccount.BillingPostalCode = '59801';
        testAccount.Billing_Email__c = 'foo@bar.com';
        testAccount.Approved_Payment_Type__c = 'Direct Monthly';
        testAccount.ownerid = userId;
        testAccount.CurrencyIsoCode = currencyVal;
        testAccount.Approved_Payment_Type__c = paymentType;
        return testAccount;
    }
    
    
    
    public static Contact createContact(Id accountId) {
        Contact testContact = new Contact();
        testContact.FirstName = 'Test';
        testContact.LastName = 'Contact';
        testContact.AccountId = accountId;
        testContact.Source__c = 'Adwords';
        testContact.Email = 'test@test.com';
        return testContact;
    }
    
    @IsTest
    public static void batchTestMethod(){
        String orgId = UserInfo.getOrganizationId();
        String partnerUsername = 'partner@test.com'+orgId;
        
        //Before state - Assert that the running user(PSM) has no lead records visible to them
        List<Lead> myLeadsAtStart = (List<Lead>)Database.Query('Select Id from Lead');
        System.assert(myLeadsAtStart.size() == 0);
        
        Account partnerAccount = [SELECT Id FROM Account WHERE isPartner = true];
        Contact partnerContact = [SELECT Id FROM Contact WHERE AccountId=:partnerAccount.id];
        
        //Get partner user
        User partnerUser = [Select Id, Account.OwnerId from User where username =: partnerUsername];
        Account acc = createAccount('test Account','Direct Monthly',partnerUser.Id,'USD');
        insert acc;
        Contact con = createContact(acc.id);
        insert con;
        
        //Insert a Deal Reg Lead record to simulate the Partner community action
        string leadDealRegRT = sObjectType.Lead.getRecordTypeInfosByDeveloperName().get('Channel_Registration').getRecordTypeId();//[Select Id from RecordType Where SObjectType = 'Lead' and Name = 'Channel Registration' LIMIT 1];
        
        Lead dealRegLead2 = new Lead (LastName = 'Test Client2',Is_Deal_Registration__c = true, Email = 'dealreglead2@test.com'+orgId,
                                      RecordTypeId = leadDealRegRT, phone = '+1234567890', Company = 'Test company2', Business_unit__c = 'Fleet',
                                      LeadSource = 'Deal Reg Form', Country='United States', State='Texas',Partner_Account__c = partnerAccount.Id, Partner_Contact__c = partnerContact.Id,
                                      Status = 'New');
       	
        //List<Lead> leadList = new List<Lead>{dealRegLead1,dealRegLead2};
        insert dealRegLead2;
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new SubmitLeadToNotreDameTest.NotreDameHTTPServiceTestMocks());
        CRLeadToPRConversionOnTime_Batch bcVar = new CRLeadToPRConversionOnTime_Batch();
        bcVar.dateValue = Date.today().addDays(3);
        bcVar.emailIdList.add('Vijaychandra.amaraneni@Samsara.com');
        bcVar.inProgressLeads = true;
        bcVar.leadSourceVal = 'Deal Reg Form';
        bcVar.partnerTypeVal = 'Channel_Registration';
        //bcVar.failedLeads.put(leadList[1].Id,'Test Message');
        Database.executebatch(bcVar);
        Test.stopTest();
    }
    
    @IsTest
    static void convertedLeadTest(){
        String orgId = UserInfo.getOrganizationId();
        String partnerUsername = 'partner@test.com'+orgId;
        
        //Before state - Assert that the running user(PSM) has no lead records visible to them
        List<Lead> myLeadsAtStart = (List<Lead>)Database.Query('Select Id from Lead');
        System.assert(myLeadsAtStart.size() == 0);
        
        Account partnerAccount = [SELECT Id FROM Account WHERE isPartner = true];
        Contact partnerContact = [SELECT Id FROM Contact WHERE AccountId=:partnerAccount.id];
        
        //Get partner user
        User partnerUser = [Select Id, Account.OwnerId from User where username =: partnerUsername];
        Account acc = createAccount('test Account','Direct Monthly',partnerUser.Id,'USD');
        insert acc;
        Contact con = createContact(acc.id);
        insert con;
        
        //Insert a Deal Reg Lead record to simulate the Partner community action
        string leadDealRegRT = sObjectType.Lead.getRecordTypeInfosByDeveloperName().get('Channel_Registration').getRecordTypeId();//[Select Id from RecordType Where SObjectType = 'Lead' and Name = 'Channel Registration' LIMIT 1];
        Lead dealRegLead1 = new Lead (LastName = 'Test Client',Is_Deal_Registration__c = false, Email = 'dealreglead@test.com'+orgId,
                                      RecordTypeId = leadDealRegRT, phone = '+1234567890', Company = 'Test company', Business_unit__c = 'Fleet',
                                      LeadSource = 'Deal Reg Form', Country='United States', State='Texas',Partner_Account__c = partnerAccount.Id, Partner_Contact__c = partnerContact.Id,
                                      Status = 'New');
       	
        //List<Lead> leadList = new List<Lead>{dealRegLead1,dealRegLead2};
        insert dealRegLead1;
        
        Database.LeadConvert thisLC = new Database.LeadConvert();
        thisLC.setLeadId(dealRegLead1.Id);
        thisLC.setDoNotCreateOpportunity(true);
        thisLC.setConvertedStatus('Qualified');
        thisLC.setAccountId(acc.Id);
        thisLC.setContactId(con.Id);
        
        Database.convertLead(thisLC);
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new SubmitLeadToNotreDameTest.NotreDameHTTPServiceTestMocks());
        CRLeadToPRConversionOnTime_Batch bcVar = new CRLeadToPRConversionOnTime_Batch();
        bcVar.dateValue = Date.today().addDays(3);
        bcVar.emailIdList.add('Vijaychandra.amaraneni@Samsara.com');
        bcVar.convertedLeads = true;
        bcVar.leadSourceVal = 'Deal Reg Form';
        bcVar.partnerTypeVal = 'Channel_Registration';
        //bcVar.failedLeads.put(leadList[1].Id,'Test Message');
        Database.executebatch(bcVar);
        Test.stopTest();
        List<Partner_Registration__c> prList = new List<Partner_Registration__c>([SELECT Id,Name,Lead__c FROM Partner_Registration__c WHERE Lead__c =: dealRegLead1.Id]);
        //Assert.isTrue(prList.size()>0,'Partner Registration creation fails');
    }
    
    @IsTest
    static void deniedLeadTest(){
        String orgId = UserInfo.getOrganizationId();
        String partnerUsername = 'partner@test.com'+orgId;
        
        //Before state - Assert that the running user(PSM) has no lead records visible to them
        List<Lead> myLeadsAtStart = (List<Lead>)Database.Query('Select Id from Lead');
        System.assert(myLeadsAtStart.size() == 0);
        
        Account partnerAccount = [SELECT Id FROM Account WHERE isPartner = true];
        Contact partnerContact = [SELECT Id FROM Contact WHERE AccountId=:partnerAccount.id];
        
        //Get partner user
        User partnerUser = [Select Id, Account.OwnerId from User where username =: partnerUsername];
        Account acc = createAccount('test Account','Direct Monthly',partnerUser.Id,'USD');
        insert acc;
        Contact con = createContact(acc.id);
        insert con;
        
        //Insert a Deal Reg Lead record to simulate the Partner community action
        string leadDealRegRT = sObjectType.Lead.getRecordTypeInfosByDeveloperName().get('Channel_Registration').getRecordTypeId();//[Select Id from RecordType Where SObjectType = 'Lead' and Name = 'Channel Registration' LIMIT 1];
        Lead dealRegLead1 = new Lead (LastName = 'Test Client',Is_Deal_Registration__c = true, Email = 'dealreglead@test.com'+orgId,
                                      RecordTypeId = leadDealRegRT, phone = '+1234567890', Company = 'Test company', Business_unit__c = 'Fleet',
                                      LeadSource = 'Deal Reg Form', Country='United States', State='Texas',Partner_Account__c = partnerAccount.Id, Partner_Contact__c = partnerContact.Id,
                                      Status = 'New');
       	
        //List<Lead> leadList = new List<Lead>{dealRegLead1,dealRegLead2};
        insert dealRegLead1;
        
        Lead leadToUpdte = new Lead();
        leadToUpdte.Id = dealRegLead1.Id;
        leadToUpdte.Deal_Registration_Denied__c = true;
        
        update leadToUpdte;
        
        //system.debug([SELECT Id,Name,rvpe__DealRegistrationDenied__c,status,rvpe__DealRegistrationStatus__c FROM Lead WHERE Id =: dealRegLead1.Id]);
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new SubmitLeadToNotreDameTest.NotreDameHTTPServiceTestMocks());
        CRLeadToPRConversionOnTime_Batch bcVar = new CRLeadToPRConversionOnTime_Batch();
        bcVar.dateValue = Date.today().addDays(3);
        bcVar.emailIdList.add('Vijaychandra.amaraneni@Samsara.com');
        bcVar.deniedLeads = true;
        bcVar.leadSourceVal = 'Deal Reg Form';
        bcVar.partnerTypeVal = 'Channel_Registration';
        //bcVar.failedLeads.put(leadList[1].Id,'Test Message');
        Database.executebatch(bcVar);
        Test.stopTest();
    }
    
    @IsTest
    static void failedLeadsTest(){
        String orgId = UserInfo.getOrganizationId();
        String partnerUsername = 'partner@test.com'+orgId;
        
        //Before state - Assert that the running user(PSM) has no lead records visible to them
        List<Lead> myLeadsAtStart = (List<Lead>)Database.Query('Select Id from Lead');
        System.assert(myLeadsAtStart.size() == 0);
        
        Account partnerAccount = [SELECT Id FROM Account WHERE isPartner = true];
        Contact partnerContact = [SELECT Id FROM Contact WHERE AccountId=:partnerAccount.id];
        
        //Get partner user
        User partnerUser = [Select Id, Account.OwnerId from User where username =: partnerUsername];
        Account acc = createAccount('test Account','Direct Monthly',partnerUser.Id,'USD');
        insert acc;
        Contact con = createContact(acc.id);
        insert con;
        
        //Insert a Deal Reg Lead record to simulate the Partner community action
        string leadDealRegRT = sObjectType.Lead.getRecordTypeInfosByDeveloperName().get('Channel_Registration').getRecordTypeId();//[Select Id from RecordType Where SObjectType = 'Lead' and Name = 'Channel Registration' LIMIT 1];
        Lead dealRegLead1 = new Lead (LastName = 'Test Client',Is_Deal_Registration__c = true, Email = 'dealreglead@test.com'+orgId,
                                      RecordTypeId = leadDealRegRT, phone = '+1234567890', Company = 'Test company', Business_unit__c = 'Fleet',
                                      LeadSource = 'Deal Reg Form', Country='United States', State='Texas',Partner_Account__c = partnerAccount.Id, Partner_Contact__c = partnerContact.Id,
                                      Status = 'New');
       	
        //List<Lead> leadList = new List<Lead>{dealRegLead1,dealRegLead2};
        insert dealRegLead1;
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new SubmitLeadToNotreDameTest.NotreDameHTTPServiceTestMocks());
        CRLeadToPRConversionOnTime_Batch bcVar = new CRLeadToPRConversionOnTime_Batch();
        bcVar.dateValue = Date.today().addDays(3);
        bcVar.emailIdList.add('Vijaychandra.amaraneni@Samsara.com');
        bcVar.idList = new List<Id>{dealRegLead1.Id};
        bcVar.failedLeads.put(dealRegLead1.Id,'Test Message');
        bcVar.leadSourceVal = 'Deal Reg Form';
        bcVar.partnerTypeVal = 'Channel_Registration';
        Database.executebatch(bcVar);
        bcVar.mapPartnerPrFields(dealRegLead1,'AE Approved');
        Test.stopTest();
    }
    
    @IsTest
    static void directMethodCall(){
        String orgId = UserInfo.getOrganizationId();
        String partnerUsername = 'partner@test.com'+orgId;
        
        //Before state - Assert that the running user(PSM) has no lead records visible to them
        List<Lead> myLeadsAtStart = (List<Lead>)Database.Query('Select Id from Lead');
        System.assert(myLeadsAtStart.size() == 0);
        
        Account partnerAccount = [SELECT Id FROM Account WHERE isPartner = true];
        Contact partnerContact = [SELECT Id FROM Contact WHERE AccountId=:partnerAccount.id];
        
        //Get partner user
        User partnerUser = [Select Id, Account.OwnerId from User where username =: partnerUsername];
        Account acc = createAccount('test Account','Direct Monthly',partnerUser.Id,'USD');
        insert acc;
        Contact con = createContact(acc.id);
        insert con;
        
        //Insert a Deal Reg Lead record to simulate the Partner community action
        string leadDealRegRT = sObjectType.Lead.getRecordTypeInfosByDeveloperName().get('Channel_Registration').getRecordTypeId();//[Select Id from RecordType Where SObjectType = 'Lead' and Name = 'Channel Registration' LIMIT 1];
        Lead dealRegLead1 = new Lead (LastName = 'Test Client',Is_Deal_Registration__c = true, Email = 'dealreglead@test.com'+orgId,
                                      RecordTypeId = leadDealRegRT, phone = '+1234567890', Company = 'Test company', Business_unit__c = 'Fleet',
                                      LeadSource = 'Deal Reg Form', Country='United States', State='Texas',Partner_Account__c = partnerAccount.Id, Partner_Contact__c = partnerContact.Id,
                                      Status = 'New');
       	
        //List<Lead> leadList = new List<Lead>{dealRegLead1,dealRegLead2};
        insert dealRegLead1;
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new SubmitLeadToNotreDameTest.NotreDameHTTPServiceTestMocks());
        CRLeadToPRConversionOnTime_Batch bcVar = new CRLeadToPRConversionOnTime_Batch();
        bcVar.dateValue = Date.today().addDays(3);
        bcVar.emailIdList.add('Vijaychandra.amaraneni@Samsara.com');
        bcVar.idList = new List<Id>{dealRegLead1.Id};
        bcVar.leadSourceVal = 'Deal Reg Form';
        bcVar.partnerTypeVal = 'Channel_Registration';    
        bcVar.failedLeads.put(dealRegLead1.Id,'Test Message');
        
        Id jobId = Database.executebatch(bcVar);
        
        bcVar.mapPrFeilds(dealRegLead1,'AE Approved','Create New Opportunity');
        bcVar.sendEmailMethod(jobId, bcVar.failedLeads);
        Test.stopTest();
    }
    
    @IsTest
    public static void partnerApplicationTest(){
        String orgId = UserInfo.getOrganizationId();
        String partnerUsername = 'partner@test.com'+orgId;
        
        //Before state - Assert that the running user(PSM) has no lead records visible to them
        List<Lead> myLeadsAtStart = (List<Lead>)Database.Query('Select Id from Lead');
        System.assert(myLeadsAtStart.size() == 0);
        
        Account partnerAccount = [SELECT Id FROM Account WHERE isPartner = true];
        Contact partnerContact = [SELECT Id FROM Contact WHERE AccountId=:partnerAccount.id];
        
        //Get partner user
        User partnerUser = [Select Id, Account.OwnerId from User where username =: partnerUsername];
        Account acc = createAccount('test Account','Direct Monthly',partnerUser.Id,'USD');
        insert acc;
        Contact con = createContact(acc.id);
        insert con;
        
        //Insert a Deal Reg Lead record to simulate the Partner community action
        string leadDealRegRT = sObjectType.Lead.getRecordTypeInfosByDeveloperName().get('Channel_Registration').getRecordTypeId();//[Select Id from RecordType Where SObjectType = 'Lead' and Name = 'Channel Registration' LIMIT 1];
        string partnerRegRT = sObjectType.Lead.getRecordTypeInfosByDeveloperName().get('Partner_Application').getRecordTypeId();
        Lead dealRegLead1 = new Lead (LastName = 'Test Client',Is_Deal_Registration__c = false, Email = 'dealreglead@test.com'+orgId,
                                      RecordTypeId = partnerRegRT, phone = '+1234567890', Company = 'Test company', Business_unit__c = 'Fleet',
                                      LeadSource = 'Partner Application Form', Country='United States', State='Texas',Partner_Account__c = partnerAccount.Id, Partner_Contact__c = partnerContact.Id,
                                      Status = 'New');
        Lead dealRegLead2 = new Lead (LastName = 'Test Client2',Is_Deal_Registration__c = true, Email = 'dealreglead2@test.com'+orgId,
                                      RecordTypeId = partnerRegRT, phone = '+1234567890', Company = 'Test company2', Business_unit__c = 'Fleet',
                                      LeadSource = 'Partner Application Form', Country='United States', State='Texas',Partner_Account__c = partnerAccount.Id, Partner_Contact__c = partnerContact.Id,
                                      Status = 'New');
       	
        Lead dealRegLead3 = new Lead (LastName = 'Test Partner',Is_Deal_Registration__c = false, Email = 'dealreglead@test.com'+orgId,
                                      RecordTypeId = partnerRegRT, phone = '+1234567890', Company = 'Test company', Business_unit__c = 'Fleet',
                                      LeadSource = 'Partner Application Form', Country='United States', State='Texas',Partner_Account__c = partnerAccount.Id, Partner_Contact__c = partnerContact.Id,
                                      Status = 'New');
        Lead dealRegLead4 = new Lead (LastName = 'Test Partner2',Is_Deal_Registration__c = true, Email = 'dealreglead2@test.com'+orgId,
                                      RecordTypeId = partnerRegRT, phone = '+1234567890', Company = 'Test company2', Business_unit__c = 'Fleet',
                                      LeadSource = 'Partner Application Form', Country='United States', State='Texas',Partner_Account__c = partnerAccount.Id, Partner_Contact__c = partnerContact.Id,
                                      Status = 'New');
        
        List<Lead> leadList = new List<Lead>{dealRegLead1,dealRegLead2, dealRegLead3, dealRegLead4};
        insert leadList;
        
        Database.LeadConvert thisLC = new Database.LeadConvert();
        thisLC.setLeadId(leadList[0].Id);
        thisLC.setDoNotCreateOpportunity(true);
        thisLC.setConvertedStatus('Qualified');
        thisLC.setAccountId(acc.Id);
        thisLC.setContactId(con.Id);
        
        Database.convertLead(thisLC);
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new SubmitLeadToNotreDameTest.NotreDameHTTPServiceTestMocks());
        CRLeadToPRConversionOnTime_Batch bcVar = new CRLeadToPRConversionOnTime_Batch();
        bcVar.dateValue = Date.today().addDays(3);
        bcVar.emailIdList.add('Vijaychandra.amaraneni@Samsara.com');
        bcVar.failedLeads.put(leadList[1].Id,'Test Message');
        bcVar.isPartner = true;
        bcVar.partnerTypeVal = 'Partner_Application';
        bcVar.leadSourceVal = 'Partner Application Form';
        Database.executebatch(bcVar);
        bcVar.mapPrFeilds(leadList[1],'AE Approved','Create New Opportunity');
        Test.stopTest();
    }
}