force-app/main/default/objects/Account/fields/Approved_Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Approved_Payment_Type__c</fullName>
    <label>Approved Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Geographic_Region__c.field-meta.xml
<CustomField>
    <fullName>Geographic_Region__c</fullName>
    <label>Geographic Region</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/IF_Response_Date__c.field-meta.xml
<CustomField>
    <fullName>IF_Response_Date__c</fullName>
    <description>to store recently approved Internal Finance request approval response date</description>
    <label>IF Response Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/IF_Submitter_Email__c.field-meta.xml
<CustomField>
    <fullName>IF_Submitter_Email__c</fullName>
    <description>to store the recently approved Internal Finance Request submitter email</description>
    <label>IF Submitter Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Organization_Size__c.field-meta.xml
<CustomField>
    <fullName>Organization_Size__c</fullName>
    <description>Number of employees or students</description>
    <inlineHelpText>Number of employees or students</inlineHelpText>
    <label>Organization Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 - 99</fullName>
            </value>
            <value>
                <fullName>100 - 499</fullName>
            </value>
            <value>
                <fullName>500 - 999</fullName>
            </value>
            <value>
                <fullName>1000 - 4999</fullName>
            </value>
            <value>
                <fullName>5000+</fullName>
            </value>
            <value>
                <fullName>0</fullName>
                <isActive>false</isActive>
                <label>0</label>
            </value>
            <value>
                <fullName>1-99</fullName>
                <isActive>false</isActive>
                <label>1-99</label>
            </value>
            <value>
                <fullName>1/1/1999 12:00:00 AM</fullName>
                <isActive>false</isActive>
                <label>1/1/1999 12:00:00 AM</label>
            </value>
            <value>
                <fullName>10</fullName>
                <isActive>false</isActive>
                <label>10</label>
            </value>
            <value>
                <fullName>100 - 999</fullName>
                <isActive>false</isActive>
                <label>100 - 999</label>
            </value>
            <value>
                <fullName>100-499</fullName>
                <isActive>false</isActive>
                <label>100-499</label>
            </value>
            <value>
                <fullName>1000+</fullName>
                <isActive>false</isActive>
                <label>1000+</label>
            </value>
            <value>
                <fullName>1000-4999</fullName>
                <isActive>false</isActive>
                <label>1000-4999</label>
            </value>
            <value>
                <fullName>10000+</fullName>
                <isActive>false</isActive>
                <label>10000+</label>
            </value>
            <value>
                <fullName>11</fullName>
                <isActive>false</isActive>
                <label>11</label>
            </value>
            <value>
                <fullName>13</fullName>
                <isActive>false</isActive>
                <label>13</label>
            </value>
            <value>
                <fullName>200</fullName>
                <isActive>false</isActive>
                <label>200</label>
            </value>
            <value>
                <fullName>201-500</fullName>
                <isActive>false</isActive>
                <label>201-500</label>
            </value>
            <value>
                <fullName>21</fullName>
                <isActive>false</isActive>
                <label>21</label>
            </value>
            <value>
                <fullName>22</fullName>
                <isActive>false</isActive>
                <label>22</label>
            </value>
            <value>
                <fullName>29</fullName>
                <isActive>false</isActive>
                <label>29</label>
            </value>
            <value>
                <fullName>34</fullName>
                <isActive>false</isActive>
                <label>34</label>
            </value>
            <value>
                <fullName>36161</fullName>
                <isActive>false</isActive>
                <label>36161</label>
            </value>
            <value>
                <fullName>42</fullName>
                <isActive>false</isActive>
                <label>42</label>
            </value>
            <value>
                <fullName>495 - 1000</fullName>
                <isActive>false</isActive>
                <label>495 - 1000</label>
            </value>
            <value>
                <fullName>496 - 1000</fullName>
                <isActive>false</isActive>
                <label>496 - 1000</label>
            </value>
            <value>
                <fullName>497 - 1000</fullName>
                <isActive>false</isActive>
                <label>497 - 1000</label>
            </value>
            <value>
                <fullName>498 - 1000</fullName>
                <isActive>false</isActive>
                <label>498 - 1000</label>
            </value>
            <value>
                <fullName>499 - 1000</fullName>
                <isActive>false</isActive>
                <label>499 - 1000</label>
            </value>
            <value>
                <fullName>500 - 1000</fullName>
                <isActive>false</isActive>
                <label>500 - 1000</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Fleet.recordType-meta.xml
<RecordType>
    <fullName>Fleet</fullName>
    <active>true</active>
    <description>Fleet account</description>
    <label>Fleet</label>
</RecordType>

force-app/main/default/objects/Contract/fields/Deactivated__c.field-meta.xml
<CustomField>
    <fullName>Deactivated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Created as part of GTMS-6040</description>
    <label>Deactivated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/netsuite_conn__Reseller__c.field-meta.xml
<CustomField>
    <fullName>netsuite_conn__Reseller__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reseller</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contracts (Reseller)</relationshipLabel>
    <relationshipName>Contracts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Selected_Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Selected_Payment_Type__c</fullName>
    <label>Selected Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct Annual</fullName>
            </value>
            <value>
                <fullName>Direct Monthly</fullName>
            </value>
            <value>
                <fullName>Upfront Payments</fullName>
            </value>
            <value>
                <fullName>Direct Quarterly</fullName>
            </value>
            <value>
                <fullName>Direct Semi-Annual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/recordTypes/Standard_Contract.recordType-meta.xml
<RecordType>
    <fullName>Standard_Contract</fullName>
    <active>true</active>
    <label>Standard Contract</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/License_Term__c.field-meta.xml
<CustomField>
    <fullName>License_Term__c</fullName>
    <defaultValue>36</defaultValue>
    <description>The license term of the opportunity.</description>
    <label>License Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Max_Approved_Discount__c.field-meta.xml
<CustomField>
    <fullName>Max_Approved_Discount__c</fullName>
    <defaultValue>0.10</defaultValue>
    <label>Approved Discretionary Discount</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/netsuite_conn__Reseller__c.field-meta.xml
<CustomField>
    <fullName>netsuite_conn__Reseller__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reseller</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.netsuite_conn__Channel_Tier__c</field>
            <operation>equals</operation>
            <value>Reseller</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Reseller)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Owner_Role_Copy__c.field-meta.xml
<CustomField>
    <fullName>Owner_Role_Copy__c</fullName>
    <description>Stores the role of the owner of the opportunity at the time it became a closed won.</description>
    <label>Owner Role Copy</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Price_Book_Name__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_Name__c</fullName>
    <defaultValue>&quot;Samsara Standard&quot;</defaultValue>
    <description>Price Book Name, populated by workflow / field update</description>
    <label>Price Book Name</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Selected_Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Selected_Payment_Type__c</fullName>
    <inlineHelpText>This dropdown list is populated based on what your customer has been approved for in Internal Financing. If you do not see a finance option then your customer has not been approved for that option.</inlineHelpText>
    <label>Selected Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Direct Monthly</fullName>
            </value>
            <value>
                <fullName>Direct Annual</fullName>
            </value>
            <value>
                <fullName>Upfront Payments</fullName>
            </value>
            <value>
                <fullName>Direct Semi-Annual</fullName>
            </value>
            <value>
                <fullName>Direct Quarterly</fullName>
            </value>
            <value>
                <fullName>Net-30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/License_Term__c.field-meta.xml
<CustomField>
    <fullName>License_Term__c</fullName>
    <label>License Term</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Approved_Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Approved_Payment_Type__c</fullName>
    <description>If it&apos;s a first purchase</description>
    <formula>TEXT(SBQQ__Account__r.Approved_Payment_Type__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Approved Payment Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/License_Term__c.field-meta.xml
<CustomField>
    <fullName>License_Term__c</fullName>
    <label>License Term</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>36</fullName>
                <default>true</default>
                <label>36</label>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Selected_Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Selected_Payment_Type__c</fullName>
    <inlineHelpText>For Direct Annual or Direct Monthly payments, the total amount (TCV) of the quote must be $10,000 or greater. For Direct Monthly, the account must also be approved for Direct Monthly payments.  Existing customers must not be delinquent on payments.</inlineHelpText>
    <label>Selected Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct Annual</fullName>
            </value>
            <value>
                <fullName>Direct Monthly</fullName>
            </value>
            <value>
                <fullName>Upfront Payments</fullName>
            </value>
            <value>
                <fullName>Direct Quarterly</fullName>
            </value>
            <value>
                <fullName>Direct Semi-Annual</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
                <isActive>false</isActive>
                <label>Annual</label>
            </value>
            <value>
                <fullName>Monthly</fullName>
                <isActive>false</isActive>
                <label>Monthly</label>
            </value>
            <value>
                <fullName>Upfront</fullName>
                <isActive>false</isActive>
                <label>Upfront</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/SBQQ__Subscription__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__SubscriptionPricing__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__SubscriptionPricing__c</fullName>
    <description>Method of calculating the subscription price.</description>
    <inlineHelpText>Method of calculating the subscription price.</inlineHelpText>
    <label>Subscription Pricing</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fixed Price</fullName>
            </value>
            <value>
                <fullName>Percent Of Total</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Payment_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Direct Monthly</fullName>
    </customValue>
    <customValue>
        <fullName>Direct Annual</fullName>
    </customValue>
    <customValue>
        <fullName>Upfront Payments</fullName>
    </customValue>
    <customValue>
        <fullName>Direct Quarterly</fullName>
    </customValue>
    <customValue>
        <fullName>Direct Semi-Annual</fullName>
    </customValue>
    <masterLabel>Payment Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Flex_ControlCenterHelperTest.cls
@IsTest
public class Flex_ControlCenterHelperTest {
    @testSetup
    static void setupMethod(){
        TestData.setupControlCenterData();
        //bypassTriggers();
        // Standard Pricebook
        Id pricebookId = Test.getStandardPricebookId();
        
        // Create Product
        List<Product2> productList = new List<Product2>();
        Product2 vgLicense = new Product2(
            Name= 'LIC-VG-36MO', 
            ProductCode = 'LIC-VG-36MO', 
            Family = 'Test', 
            IsActive = true, 
            SBQQ__SubscriptionPricing__c = 'Fixed Price'
        );
        productList.add(vgLicense);  
        insert productList;

        // Create PriceBookEntries
        List<PricebookEntry> pricebookEntriesList = new List<PricebookEntry>();
        PricebookEntry vg33PB = new PricebookEntry(
            Pricebook2Id = pricebookId, 
            Product2Id = productList[0].Id, 
            UnitPrice = 10000, 
            IsActive = true
        );
        pricebookEntriesList.add(vg33PB);
        insert pricebookEntriesList;

        
        Account testAccount = new Account(Name='Acc1',Organization_Size__c = '1 - 99',Industry='Banking',BillingState='California',
                                          ShippingState='California',Approved_Payment_Type__c = 'Direct Monthly', BillingCountry = 'United States',
                                          IF_Response_Date__c=Date.today().addDays(-90),IF_Submitter_Email__c='testUser@Samsara.com',
                                          Geographic_Region__c='US'
                                         );
        insert testAccount;
        
        Account testAccount2 = new Account(Name='Acc2',Organization_Size__c = '1 - 99',
                                           Industry='Banking',BillingState='California',
                                           ShippingState='California',Approved_Payment_Type__c = 'Direct Monthly',
                                           BillingCountry = 'United States',
                                           IF_Response_Date__c=Date.today().addDays(-90),IF_Submitter_Email__c='testUser@Samsara.com',
                                           Geographic_Region__c='US'
                                         );
        insert testAccount2;

        // Create Opportunity
        List<Opportunity> newOppsList = new List<Opportunity>();
        Opportunity revenueOpportunity1 = new Opportunity(
            AccountId = testAccount.Id, 
            License_Term__c = 36, 
            Pricebook2Id = pricebookId, 
            Max_Approved_Discount__c = 0, 
            Name = 'Revenue Opportunity1', 
            Price_Book_Name__c = 'Standard Price Book', 
            CloseDate = System.today() + 90, 
            StageName = 'Incubate', 
            Owner_Role_Copy__c = 'Fleet IS AE2 NA US Team 8',
            Selected_Payment_Type__c = 'Direct Annual'
        ); 
        newOppsList.add(revenueOpportunity1);
        insert newOppsList;
        
        Opportunity renewalOpportunity = new Opportunity(
            AccountId = testAccount.Id, 
            License_Term__c = 36, 
            Pricebook2Id = pricebookId, 
            Max_Approved_Discount__c = 0, 
            Name = 'Renewal Opportunity1', 
            Price_Book_Name__c = 'Standard Price Book', 
            CloseDate = System.today() + 90, 
            Stagename = 'Proposal',
            Owner_Role_Copy__c = 'Fleet IS AE2 NA US Team 8',
            Selected_Payment_Type__c = 'Direct Annual'
        ); 
        
        insert renewalOpportunity;

        // Create a RecordType for Contract
        RecordType contractRecordType = [SELECT Id FROM RecordType WHERE DeveloperName = 'Standard_Contract' LIMIT 1];

        // Create Contracts
        List<Contract> contractList = new List<Contract>(); 
        /*Contract contract1 = new Contract(
            AccountId = testAccount.Id,
            StartDate = Date.today(),
            EndDate = Date.today().addDays(130),
            ContractTerm = 12,
            RecordTypeId = contractRecordType.Id,
            Deactivated__c = true,
            SBQQ__Opportunity__c = revenueOpportunity1.Id
            //SBQQ__Quote__c = quoteList[0].Id
        );
        contractList.add(contract1);
        
        Contract contract2 = new Contract(
            AccountId = testAccount2.Id,
            StartDate = Date.today(),
            EndDate = Date.today().addDays(130),
            ContractTerm = 12,
            RecordTypeId = contractRecordType.Id,
            Deactivated__c = true,
            SBQQ__Opportunity__c = revenueOpportunity1.Id
        );
        contractList.add(contract2); */

        Contract contract3 = new Contract(
            AccountId = testAccount.Id,
            StartDate = Date.today(),
            EndDate = Date.today().addDays(130),
            ContractTerm = 12,
            netsuite_conn__Reseller__c = testAccount2.Id,
            //Finance_Partner_Account__c = testAccount2.Id,
            Contract_C_R_In_Progress__c = TRUE,
            RecordTypeId = contractRecordType.Id,
            Deactivated__c = true,
            SBQQ__Opportunity__c = revenueOpportunity1.Id
        );
        contractList.add(contract3);
        
        /*Contract contract4 = new Contract(
            AccountId = testAccount.Id,
            StartDate = Date.today(),
            EndDate = Date.today().addDays(60),
            ContractTerm = 12,
            RecordTypeId = contractRecordType.Id,
            Deactivated__c = true,
            SBQQ__Opportunity__c = revenueOpportunity1.Id
        );
        contractList.add(contract4);*/
        
        Contract contract5 = new Contract(
            AccountId = testAccount.Id,
            StartDate = Date.today(),
            EndDate = Date.today().addDays(130),
            ContractTerm = 12,
            RecordTypeId = contractRecordType.Id,
            Deactivated__c = TRUE,
            SBQQ__Opportunity__c = revenueOpportunity1.Id,
            Contract_C_R_In_Progress__c = TRUE
        );
        contractList.add(contract5);
        
        
        insert contractList;

        // Create Subscriptions
        List<SBQQ__Subscription__c> subList = new List<SBQQ__Subscription__c>();
        
        List<Contract> contractList1 = new List<Contract>([SELECT Id, AccountId FROM Contract
                                                            WHERE Account.Name IN ('Acc1','Acc2')]);
        for(Contract con : contractList1) {
            SBQQ__Subscription__c sub1 = new SBQQ__Subscription__c(
                SBQQ__Quantity__c = 1,
                SBQQ__CustomerPrice__c = 100,
                SBQQ__Contract__c = con.id,
                SBQQ__Account__c = con.Accountid,
                SBQQ__Product__c = productList[0].Id
            );
            subList.add(sub1);
        }
        system.debug('subList size'+subList.size());
        insert subList;

        // Activate Contracts
        List<Contract> contractsToUpdate = [SELECT Id, Is_Active__c, Status, Deactivated__c
                                            FROM Contract WHERE Account.Name IN ('Acc1','Acc2')];
        for(Contract cont : contractsToUpdate) {
           cont.Status = 'Activated';
        }
        system.debug('contractsToUpdate size---'+contractsToUpdate.size());
        update contractsToUpdate;
        
    }
    
    
    @IsTest
    public static void testIneligibleContract(){
        Test.startTest();
            Account acc1 = [select id, BillingCountry, Segment__c from account where name = 'Acc1' limit 1];
            System.debug('Segment__c--'+acc1.Segment__c);
            System.debug('BillingCountry----'+acc1.BillingCountry);
            Flex_ControlCenterHelper.getEligibleContracts(acc1.id);  
        Test.stopTest();
    }
    
      @IsTest
    public static void testEligibleContract(){
        Test.startTest();
            Account acc2 = [select id, BillingCountry, Segment__c from account where name = 'Acc2' limit 1];
            System.debug('Segment__c--'+acc2.Segment__c);
            Flex_ControlCenterHelper.getEligibleContracts(acc2.id);  
        Test.stopTest();
    }
}