force-app/main/default/objects/Account/fields/Approved_Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Approved_Payment_Type__c</fullName>
    <label>Approved Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Organization_Size__c.field-meta.xml
<CustomField>
    <fullName>Organization_Size__c</fullName>
    <description>Number of employees or students</description>
    <inlineHelpText>Number of employees or students</inlineHelpText>
    <label>Organization Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 - 99</fullName>
            </value>
            <value>
                <fullName>100 - 499</fullName>
            </value>
            <value>
                <fullName>500 - 999</fullName>
            </value>
            <value>
                <fullName>1000 - 4999</fullName>
            </value>
            <value>
                <fullName>5000+</fullName>
            </value>
            <value>
                <fullName>0</fullName>
                <isActive>false</isActive>
                <label>0</label>
            </value>
            <value>
                <fullName>1-99</fullName>
                <isActive>false</isActive>
                <label>1-99</label>
            </value>
            <value>
                <fullName>1/1/1999 12:00:00 AM</fullName>
                <isActive>false</isActive>
                <label>1/1/1999 12:00:00 AM</label>
            </value>
            <value>
                <fullName>10</fullName>
                <isActive>false</isActive>
                <label>10</label>
            </value>
            <value>
                <fullName>100 - 999</fullName>
                <isActive>false</isActive>
                <label>100 - 999</label>
            </value>
            <value>
                <fullName>100-499</fullName>
                <isActive>false</isActive>
                <label>100-499</label>
            </value>
            <value>
                <fullName>1000+</fullName>
                <isActive>false</isActive>
                <label>1000+</label>
            </value>
            <value>
                <fullName>1000-4999</fullName>
                <isActive>false</isActive>
                <label>1000-4999</label>
            </value>
            <value>
                <fullName>10000+</fullName>
                <isActive>false</isActive>
                <label>10000+</label>
            </value>
            <value>
                <fullName>11</fullName>
                <isActive>false</isActive>
                <label>11</label>
            </value>
            <value>
                <fullName>13</fullName>
                <isActive>false</isActive>
                <label>13</label>
            </value>
            <value>
                <fullName>200</fullName>
                <isActive>false</isActive>
                <label>200</label>
            </value>
            <value>
                <fullName>201-500</fullName>
                <isActive>false</isActive>
                <label>201-500</label>
            </value>
            <value>
                <fullName>21</fullName>
                <isActive>false</isActive>
                <label>21</label>
            </value>
            <value>
                <fullName>22</fullName>
                <isActive>false</isActive>
                <label>22</label>
            </value>
            <value>
                <fullName>29</fullName>
                <isActive>false</isActive>
                <label>29</label>
            </value>
            <value>
                <fullName>34</fullName>
                <isActive>false</isActive>
                <label>34</label>
            </value>
            <value>
                <fullName>36161</fullName>
                <isActive>false</isActive>
                <label>36161</label>
            </value>
            <value>
                <fullName>42</fullName>
                <isActive>false</isActive>
                <label>42</label>
            </value>
            <value>
                <fullName>495 - 1000</fullName>
                <isActive>false</isActive>
                <label>495 - 1000</label>
            </value>
            <value>
                <fullName>496 - 1000</fullName>
                <isActive>false</isActive>
                <label>496 - 1000</label>
            </value>
            <value>
                <fullName>497 - 1000</fullName>
                <isActive>false</isActive>
                <label>497 - 1000</label>
            </value>
            <value>
                <fullName>498 - 1000</fullName>
                <isActive>false</isActive>
                <label>498 - 1000</label>
            </value>
            <value>
                <fullName>499 - 1000</fullName>
                <isActive>false</isActive>
                <label>499 - 1000</label>
            </value>
            <value>
                <fullName>500 - 1000</fullName>
                <isActive>false</isActive>
                <label>500 - 1000</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ACV_Commissionable_Dollars_Copy__c.field-meta.xml
<CustomField>
    <fullName>ACV_Commissionable_Dollars_Copy__c</fullName>
    <label>Commissionable Dollars ACV Copy</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Can_Create__c.field-meta.xml
<CustomField>
    <fullName>Can_Create__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is a field for internal use. It helps preventing the user to create the first opportunity for the Account from outside the contact</description>
    <label>Can Create</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Internal_Finance__c.field-meta.xml
<CustomField>
    <fullName>Internal_Finance__c</fullName>
    <description>DO NOT USE</description>
    <inlineHelpText>DO NOT USE</inlineHelpText>
    <label>*NO* Internal Finance Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Need More Information</fullName>
            </value>
            <value>
                <fullName>Pending - Require further information</fullName>
                <isActive>false</isActive>
                <label>Pending - Require further information</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Internal_Financing_Response_Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Internal_Financing_Response_Timestamp__c</fullName>
    <label>Internal Financing Response Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lead_Source_Encoded__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source_Encoded__c</fullName>
    <description>Date + source number: 1 Outbound, 2 Inbound, 3 Partner, 4 Events, 5 Other</description>
    <label>Lead Source Encoded</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/netsuite_conn__Order_Type__c.field-meta.xml
<CustomField>
    <fullName>netsuite_conn__Order_Type__c</fullName>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Contract - New</fullName>
            </value>
            <value>
                <fullName>Contract - Upsell</fullName>
            </value>
            <value>
                <fullName>Contract - Renewal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Owner_Role_Copy__c.field-meta.xml
<CustomField>
    <fullName>Owner_Role_Copy__c</fullName>
    <description>Stores the role of the owner of the opportunity at the time it became a closed won.</description>
    <label>Owner Role Copy</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Shipping_Country__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Country__c</fullName>
    <label>Shipping Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Aland Islands</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia, Plurinational State of</fullName>
            </value>
            <value>
                <fullName>Bonaire, Sint Eustatius and Saba</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Bouvet Island</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Shipping_Email_sent_bypassed__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Email_sent_bypassed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This box will prevent a shipping email from being sent to the customer. Auto checks after first shipping email sent. If manually checked, no email will go out.</description>
    <inlineHelpText>This box will prevent a shipping email from being sent to the customer. Auto checks after first shipping email sent. If manually checked, no email will go out.</inlineHelpText>
    <label>Shipping Email sent/bypassed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Shipping_Method__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Method__c</fullName>
    <label>Shipping Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Will Call</fullName>
            </value>
            <value>
                <fullName>UK Standard</fullName>
            </value>
            <value>
                <fullName>UK Express</fullName>
            </value>
            <value>
                <fullName>3 Day Select</fullName>
            </value>
            <value>
                <fullName>Ground</fullName>
                <default>true</default>
                <label>Ground</label>
            </value>
            <value>
                <fullName>Next Day Air</fullName>
            </value>
            <value>
                <fullName>Worldwide Expedited</fullName>
            </value>
            <value>
                <fullName>ECONOMY</fullName>
            </value>
            <value>
                <fullName>Fedex Freight Economy</fullName>
            </value>
            <value>
                <fullName>International Priority</fullName>
            </value>
            <value>
                <fullName>International Economy</fullName>
            </value>
            <value>
                <fullName>Ground - Mexico</fullName>
            </value>
            <value>
                <fullName>MX Standard</fullName>
            </value>
            <value>
                <fullName>MX Express</fullName>
            </value>
            <value>
                <fullName>MX LTL</fullName>
            </value>
            <value>
                <fullName>NEXT DAY AIR RS</fullName>
            </value>
            <value>
                <fullName>GROUND RS</fullName>
            </value>
            <value>
                <fullName>3 DAY SELECT RS</fullName>
            </value>
            <value>
                <fullName>UPS 3 Day Select</fullName>
                <isActive>false</isActive>
                <label>UPS 3 Day Select</label>
            </value>
            <value>
                <fullName>UPS Ground</fullName>
                <isActive>false</isActive>
                <label>UPS Ground</label>
            </value>
            <value>
                <fullName>UPS Next Day Air</fullName>
                <isActive>false</isActive>
                <label>UPS Next Day Air</label>
            </value>
            <value>
                <fullName>UPS Worldwide Expedited</fullName>
                <isActive>false</isActive>
                <label>UPS Worldwide Expedited</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Payment_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Direct Monthly</fullName>
    </customValue>
    <customValue>
        <fullName>Direct Annual</fullName>
    </customValue>
    <customValue>
        <fullName>Upfront Payments</fullName>
    </customValue>
    <customValue>
        <fullName>Direct Quarterly</fullName>
    </customValue>
    <customValue>
        <fullName>Direct Semi-Annual</fullName>
    </customValue>
    <masterLabel>Payment Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/flowControllerTest.cls
@isTest

private class flowControllerTest {
    
    @testSetup
    private static void testData(){
        system.debug('I was here');
          
        Account acc = new Account();
        acc.name='Acc1';
        acc.Organization_Size__c='1 - 99';
        acc.Industry='Agriculture';
        acc.BillingState='California';
        acc.ShippingState='California';
        acc.Approved_Payment_Type__c = 'Direct Monthly';
        insert acc;
        Account a=[Select id,name from account where name='Acc1'];
        
        Opportunity testOppty = new Opportunity();

        testOppty.Can_Create__c = true;
        testOppty.ForecastCategoryName = 'Forecast';
        testOppty.Shipping_Method__c = 'Will Call';
        
        testOppty.Shipping_Email_Sent_bypassed__c = false;
        testOppty.Shipping_Country__c = 'Canada';
        

        testOppty.Name = 'TestAccountTest';
        testOppty.AccountId = a.Id;
        testOppty.Amount = 1000000;
        testOppty.CloseDate = Date.today();
        testOppty.ACV_Commissionable_Dollars_Copy__c = 0;
        testOppty.Internal_Finance__c = 'Approved';
        testOppty.Internal_Financing_Response_Timestamp__c = Datetime.now();
        testOppty.LeadSource = 'Other';
        testOppty.Lead_Source_Encoded__c = 2019072519;
        testOppty.netsuite_conn__Order_Type__c = 'Contract - New';
        testOppty.Owner_Role_Copy__c = 'Management';
        testOppty.Selected_Payment_Type__c = 'Upfront Payments';
        testOppty.Shipping_Address_New_Concatenated__c = ',';
        testOppty.StageName = 'Closed Won';
        //testOppty.Unique_Flow_Identifier__c = '00663000009NaJIAA0';
       insert testOppty;
       system.debug('Oppertunity created');
        
    }
    
   //test with incorrect id
    private static testMethod void testCaseOne(){
        Test.startTest();
        system.debug('Within Test 1');
        PageReference pageRef = Page.AcceptanceFlow ; 
        Test.setCurrentPageReference(pageRef);
        // Put Id into the current page Parameters
        Opportunity testOppty = [SELECT Id, Unique_Flow_Identifier__c FROM Opportunity WHERE Name='TestAccountTest'];
        //system.debug('ID ='+ pageRef.getParameters().get('Id'));
        //pageRef.getParameters().put('Id', testOppty.id);
        testOppty.Unique_Flow_Identifier__c =testOppty.id;
        update testOppty;
        ApexPages.currentPage().getParameters().put('id','helloworld');
        system.debug('ID ='+ ApexPages.currentPage().getParameters().get('Id'));
        ApexPages.StandardController sc = new ApexPages.standardController(testOppty);
        //flowController testController3 = new flowController(sc);
        flowController testController3 = new flowController();
        testController3.flowController1();
        //object valURL = testController3.returnURL();
        Test.stopTest();
        
    }
    
    //test with correct id
    private static testMethod void TestCaseTwo()
    {
        Test.startTest();
        system.debug('Within Test 2');
        PageReference pageRef = Page.AcceptanceFlow ; 
        Test.setCurrentPageReference(pageRef);
        // Put Id into the current page Parameters
        Opportunity testOppty = [SELECT Id, Unique_Flow_Identifier__c FROM Opportunity WHERE Name='TestAccountTest'];
        //system.debug('ID ='+ pageRef.getParameters().get('Id'));
        //pageRef.getParameters().put('Id', testOppty.id);
        testOppty.Unique_Flow_Identifier__c =testOppty.id;
        update testOppty;
        ApexPages.currentPage().getParameters().put('id',testOppty.id);
        system.debug('ID ='+ ApexPages.currentPage().getParameters().get('Id'));
        //ApexPages.StandardController sc = new ApexPages.standardController(testOppty);
        //flowController testController3 = new flowController(sc);
        flowController testController3 = new flowController();
        //object valURL = testController3.returnURL();
        Test.stopTest();
    }
    
    private static testMethod void TestCaseThree()
    {
        Test.startTest();
        system.debug('Within Test 3');
        PageReference pageRef = Page.AcceptanceFlow ; 
        Test.setCurrentPageReference(pageRef);
        // Put Id into the current page Parameters
        Opportunity testOppty = [SELECT Id, Unique_Flow_Identifier__c FROM Opportunity WHERE Name='TestAccountTest'];
        system.debug('ID ='+ pageRef.getParameters().get('Id'));
        pageRef.getParameters().put('Id', testOppty.id);
        testOppty.Unique_Flow_Identifier__c =testOppty.id;
        update testOppty;
        ApexPages.currentPage().getParameters().put('id','');
        system.debug('ID ='+ ApexPages.currentPage().getParameters().get('Id'));
        //ApexPages.StandardController sc = new ApexPages.standardController(testOppty);
        //flowController testController3 = new flowController(sc);
        flowController testController3 = new flowController();
        //object valURL = testController3.returnURL();
        Test.stopTest();
    }

    private static testMethod void TestCaseFour()
    {
        Test.startTest();
        system.debug('Within Test 4');
        PageReference pageRef = Page.AcceptanceFlow ; 
        Test.setCurrentPageReference(pageRef);
        // Put Id into the current page Parameters
        Opportunity testOppty = [SELECT Id, Unique_Flow_Identifier__c FROM Opportunity WHERE Name='TestAccountTest'];
        system.debug('ID ='+ pageRef.getParameters().get('Id'));
        pageRef.getParameters().put('Id', testOppty.id);
        testOppty.Unique_Flow_Identifier__c =testOppty.id;
        update testOppty;
        ApexPages.currentPage().getParameters().put('id',null);
        system.debug('ID ='+ ApexPages.currentPage().getParameters().get('Id'));
        //ApexPages.StandardController sc = new ApexPages.standardController(testOppty);
        //flowController testController3 = new flowController(sc);
        flowController testController3 = new flowController();
        //object valURL = testController3.returnURL();
        Test.stopTest();
    }
  /*  //Split this method into two
 
     static testMethod void testAllCases() {


//Divide this into 2 methods
//MEthod One
       //test with incorrect id
       Test.startTest();
       PageReference pageRef = Page.AcceptanceFlow ; 

       pageRef.getParameters().put('Id', 'testincorrectId');

       Test.setCurrentPageReference(pageRef);

       flowController testController2 = new flowController();
        //Test.stopTest(); 

        

       //test with correct id
       // MEthod 2
        //Test.startTest();
       pageRef = Page.AcceptanceFlow; 
       Opportunity testOppty = [SELECT Id FROM Opportunity WHERE Name='TestAccountTest'];
       pageRef.getParameters().put('Id', testOppty.id);

       Test.setCurrentPageReference(pageRef);

       flowController testController3 = new flowController();
        Test.stopTest(); 

    }*/
}