force-app/main/default/objects/Account/fields/Approved_Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Approved_Payment_Type__c</fullName>
    <label>Approved Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Critically_Escalated_Hardware_Returns__c.field-meta.xml
<CustomField>
    <fullName>Critically_Escalated_Hardware_Returns__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used by hardware team to denote major customers reporting hardware issues, referenced in Consolidated Returns Process builder to set Shipmate-Preference on opportunity to ShipmatePreference-0498 and will return the hardware directly to Samsara HQ.</description>
    <label>Critically Escalated Hardware Returns</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Organization_Size__c.field-meta.xml
<CustomField>
    <fullName>Organization_Size__c</fullName>
    <description>Number of employees or students</description>
    <inlineHelpText>Number of employees or students</inlineHelpText>
    <label>Organization Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 - 99</fullName>
            </value>
            <value>
                <fullName>100 - 499</fullName>
            </value>
            <value>
                <fullName>500 - 999</fullName>
            </value>
            <value>
                <fullName>1000 - 4999</fullName>
            </value>
            <value>
                <fullName>5000+</fullName>
            </value>
            <value>
                <fullName>0</fullName>
                <isActive>false</isActive>
                <label>0</label>
            </value>
            <value>
                <fullName>1-99</fullName>
                <isActive>false</isActive>
                <label>1-99</label>
            </value>
            <value>
                <fullName>1/1/1999 12:00:00 AM</fullName>
                <isActive>false</isActive>
                <label>1/1/1999 12:00:00 AM</label>
            </value>
            <value>
                <fullName>10</fullName>
                <isActive>false</isActive>
                <label>10</label>
            </value>
            <value>
                <fullName>100 - 999</fullName>
                <isActive>false</isActive>
                <label>100 - 999</label>
            </value>
            <value>
                <fullName>100-499</fullName>
                <isActive>false</isActive>
                <label>100-499</label>
            </value>
            <value>
                <fullName>1000+</fullName>
                <isActive>false</isActive>
                <label>1000+</label>
            </value>
            <value>
                <fullName>1000-4999</fullName>
                <isActive>false</isActive>
                <label>1000-4999</label>
            </value>
            <value>
                <fullName>10000+</fullName>
                <isActive>false</isActive>
                <label>10000+</label>
            </value>
            <value>
                <fullName>11</fullName>
                <isActive>false</isActive>
                <label>11</label>
            </value>
            <value>
                <fullName>13</fullName>
                <isActive>false</isActive>
                <label>13</label>
            </value>
            <value>
                <fullName>200</fullName>
                <isActive>false</isActive>
                <label>200</label>
            </value>
            <value>
                <fullName>201-500</fullName>
                <isActive>false</isActive>
                <label>201-500</label>
            </value>
            <value>
                <fullName>21</fullName>
                <isActive>false</isActive>
                <label>21</label>
            </value>
            <value>
                <fullName>22</fullName>
                <isActive>false</isActive>
                <label>22</label>
            </value>
            <value>
                <fullName>29</fullName>
                <isActive>false</isActive>
                <label>29</label>
            </value>
            <value>
                <fullName>34</fullName>
                <isActive>false</isActive>
                <label>34</label>
            </value>
            <value>
                <fullName>36161</fullName>
                <isActive>false</isActive>
                <label>36161</label>
            </value>
            <value>
                <fullName>42</fullName>
                <isActive>false</isActive>
                <label>42</label>
            </value>
            <value>
                <fullName>495 - 1000</fullName>
                <isActive>false</isActive>
                <label>495 - 1000</label>
            </value>
            <value>
                <fullName>496 - 1000</fullName>
                <isActive>false</isActive>
                <label>496 - 1000</label>
            </value>
            <value>
                <fullName>497 - 1000</fullName>
                <isActive>false</isActive>
                <label>497 - 1000</label>
            </value>
            <value>
                <fullName>498 - 1000</fullName>
                <isActive>false</isActive>
                <label>498 - 1000</label>
            </value>
            <value>
                <fullName>499 - 1000</fullName>
                <isActive>false</isActive>
                <label>499 - 1000</label>
            </value>
            <value>
                <fullName>500 - 1000</fullName>
                <isActive>false</isActive>
                <label>500 - 1000</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Organization_Size__c.field-meta.xml
<CustomField>
    <fullName>Organization_Size__c</fullName>
    <formula>TEXT(Account.Organization_Size__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Please edit on the Account page.</inlineHelpText>
    <label>Organization Size</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Global_Automation_Settings__c/Global_Automation_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Global Automation Settings to toggle automation on &amp; off.</description>
    <label>Global Automation Settings</label>
</CustomObject>

force-app/main/default/objects/Global_Automation_Settings__c/fields/Allow_Handler_Selection__c.field-meta.xml
<CustomField>
    <fullName>Allow_Handler_Selection__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Allow Handler Selection</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Shipping_Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Address_Line_1__c</fullName>
    <label>Shipping Address Line 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Shipping_City__c.field-meta.xml
<CustomField>
    <fullName>Shipping_City__c</fullName>
    <label>Shipping City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Shipping_Contact__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Shipping Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunity_Shipping_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Shipping_Country__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Country__c</fullName>
    <label>Shipping Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Aland Islands</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia, Plurinational State of</fullName>
            </value>
            <value>
                <fullName>Bonaire, Sint Eustatius and Saba</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Bouvet Island</fullName>
            </value>
            <value>
                <fullName>Mexico</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>United States</fullName>
                <default>true</default>
                <label>United States</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Shipping_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Zip_Code__c</fullName>
    <label>Shipping Zip Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Trial.recordType-meta.xml
<RecordType>
    <fullName>Trial</fullName>
    <active>true</active>
    <businessProcess>Standard Opportunities</businessProcess>
    <label>Trial</label>
</RecordType>

force-app/main/default/objects/Shipping_Address__c/Shipping_Address__c.object-meta.xml
<CustomObject>
    <label>Shipping Address</label>
    <nameField>
        <label>Shipping Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipping Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipping_Address__c/fields/Shipping_Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Address_Line_1__c</fullName>
    <inlineHelpText>Shipping address should not include a PO Box.
This field appears on the shipping label: 
[First Name] [Last Name]
[Shipping Address Line 1]
[Shipping Address Line 2]
[Shipping City], [Shipping State] [Shipping Zip Code]</inlineHelpText>
    <label>Shipping Address Line 1</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipping_Address__c/fields/Shipping_City__c.field-meta.xml
<CustomField>
    <fullName>Shipping_City__c</fullName>
    <inlineHelpText>This field appears on the shipping label: 
[First Name] [Last Name]
[Shipping Address Line 1]
[Shipping Address Line 2]
[Shipping City], [Shipping State] [Shipping Zip Code]</inlineHelpText>
    <label>Shipping City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipping_Address__c/fields/Shipping_Contact__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Shipping Addresses</relationshipLabel>
    <relationshipName>Shipping_Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Address__c/fields/Shipping_Country__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Country__c</fullName>
    <label>Shipping Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Address_Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipping_Address__c/fields/Shipping_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Zip_Code__c</fullName>
    <inlineHelpText>This field appears on the shipping label: 
[First Name] [Last Name]
[Shipping Address Line 1]
[Shipping Address Line 2]
[Shipping City], [Shipping State] [Shipping Zip Code]</inlineHelpText>
    <label>Shipping Zip Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Address_Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia, Plurinational State of</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Bouvet Island</fullName>
    </customValue>
    <customValue>
        <fullName>Mexico</fullName>
    </customValue>
    <customValue>
        <fullName>United Kingdom</fullName>
    </customValue>
    <customValue>
        <fullName>United States</fullName>
        <default>true</default>
        <label>United States</label>
    </customValue>
    <masterLabel>Address: Country</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Payment_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Direct Monthly</fullName>
    </customValue>
    <customValue>
        <fullName>Direct Annual</fullName>
    </customValue>
    <customValue>
        <fullName>Upfront Payments</fullName>
    </customValue>
    <customValue>
        <fullName>Direct Quarterly</fullName>
    </customValue>
    <customValue>
        <fullName>Direct Semi-Annual</fullName>
    </customValue>
    <masterLabel>Payment Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OpportunityReturnProcessesTest.cls
@isTest
public class OpportunityReturnProcessesTest {
    
    @testSetup
    private static void testSetup(){
        insert new Global_Automation_Settings__c(Name = 'Automation_Settings',Allow_Handler_Selection__c = true);
        List<Opportunity> newOpportunities = new List<Opportunity>();
        List<Account> newAccounts = new List<Account>();
        List<Contact> newContacts = new List<Contact>();
        List<Shipping_Address__c> shippingAddressList = new List<Shipping_Address__c>();
        
        //Test Accounts
        Account accountOne = new Account(Name = 'Testers 1 Inc',
                                BillingCountry = 'United Kingdom',
                                Organization_Size__c = '100 - 499',
                                Critically_Escalated_Hardware_Returns__c=true,
                                Industry = 'Other');
        newAccounts.add(accountOne);
        
        Account accountTwo = new Account(Name = 'Testers 6 Inc',
                                BillingState='California',
                                BillingCountry = 'United States',
                                Organization_Size__c = '100 - 499',
                                Approved_Payment_Type__c = 'Direct Monthly',
                                Industry = 'Other');
        newAccounts.add(accountTwo);

        insert newAccounts;
        
        //Test COntacts
        Contact contactOne = (Contact) TestFactory.createSObject(new Contact(AccountId = accountOne.Id));
        newContacts.add(contactOne);
        
        Contact contactTwo = (Contact) TestFactory.createSObject(new Contact(AccountId = accountTwo.Id, Email = 'test@test.com'));
        newContacts.add(contactTwo);

        insert newContacts;
        
        //Test Shipping Address
        Shipping_Address__c sa1 = new Shipping_Address__c(Shipping_Zip_Code__c = '94105', Shipping_Contact__c=contactOne.Id, Shipping_Address_Line_1__c='1 Dolores, Dallas', Shipping_City__c='Dallas', Shipping_Country__c='United States', Shipping_State__c='Texas', Name='Test', Account__c = accountOne.Id);
        shippingAddressList.add(sa1);
        Shipping_Address__c sa2 = new Shipping_Address__c(Shipping_Zip_Code__c = '2030', Shipping_Contact__c=contactOne.Id, Shipping_Address_Line_1__c='Scheldelaan 417', Shipping_City__c='Antwerpen', Shipping_Country__c='Belgium', Name='Test Belgium', Account__c = accountOne.Id);
        shippingAddressList.add(sa2);
        Shipping_Address__c sa3 = new Shipping_Address__c(Shipping_Zip_Code__c = 'C.P. 45610', Shipping_Contact__c=contactOne.Id, Shipping_Address_Line_1__c='Adolf B Horn 1737-1', Shipping_City__c='San Pedro Tlaquepaque, Jal', Shipping_Country__c='Mexico', Name='Test Mexico', Account__c = accountOne.Id);
        shippingAddressList.add(sa3);
        
        insert shippingAddressList;
        
        //Test Opportunities
        Opportunity returningOppty = (Opportunity)
            TestFactory.createSObject(new Opportunity(AccountId = accountTwo.Id, 
                                                      Type = 'Trial',
                                                      Name = 'Returning Oppty 001',
                                                      StageName = 'Proposal',
                                                      Shipping_Contact__c = contactTwo.Id, 
                                                      Price_Book_Name__c = 'Standard',
                                                      Selected_Payment_Type__c = 'Direct Annual'));
        Insert returningOppty;
    }
    
    @isTest private static void testMethod001(){
        GS_TriggerHandlerRunnerConfig.oppNewTrigger = true;
        
        System.debug('test Method 001');
        Opportunity ReturningOppty = [Select id,Shipmate_Preference__c from Opportunity where name = 'Returning Oppty 001'];
        Account accountOne = [Select id from Account where name = 'Testers 1 Inc'];
        Contact contactOne = [Select id from Contact where AccountId =:accountOne.id ];
        Shipping_Address__c sa1 = [select id from Shipping_Address__c where name ='Test'];
        Shipping_Address__c sa2 = [select id from Shipping_Address__c where name ='Test Belgium'];
        Shipping_Address__c sa3 = [select id from Shipping_Address__c where name ='Test Mexico'];
        List<List<Opportunity>> opp = new List<List<Opportunity>>();
        List<Opportunity> oppList =  new List<Opportunity>();
        
        Test.startTest();
        Opportunity ReturnOppty = (Opportunity)
            TestFactory.createSObject(new Opportunity(AccountId = accountOne.Id, 
                                                      Type = 'Exchange',
                                                      Name = 'Return Opportunity 001',
                                                      StageName = 'Return initiated',
                                                      Returning_Opportunity__c = returningOppty.id,
                                                      amount = null,  
                                                      Rebate_Amount__c = null,
                                                      CloseDate = System.today() + 90,
                                                      RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Return Opportunity').getRecordTypeId(),
                                                      Shipping_Contact__c = contactOne.Id,
                                                     Shipping_Address_NEW__c = sa1.Id));
        Insert ReturnOppty;
        
        ReturnOppty.CloseDate = System.today() + 91;
        ReturnOppty.Shipping_Address_NEW__c = sa2.Id;
        ReturnOppty.Replacement_Opportunity__c = '/'+ReturningOppty.Id;
        Update ReturnOppty;
        ReturnOppty.Shipping_Address_NEW__c = sa3.Id;
        Update ReturnOppty;
        oppList.add(ReturnOppty);
        opp.add(oppList);
        //OpportunityReturnProcesses op = new OpportunityReturnProcesses(oppList,null);
        OpportunityReturnProcesses.createdRemorseRefund(opp);
        Test.stopTest();
        //System.assertEquals(null, ReturnOppty.Shipmate_Preference__c);
    }
}