force-app/main/default/objects/Account/fields/Auto_renewal_Opt_Out__c.field-meta.xml
<CustomField>
    <fullName>Auto_renewal_Opt_Out__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox to prevent customer from being auto-renewed as they have opted out via email</description>
    <label>Auto-renewal Opt Out</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_ARR__c.field-meta.xml
<CustomField>
    <fullName>Customer_ARR__c</fullName>
    <description>Active ACV shows daily changes to annual license revenue via opportunity license start/end date</description>
    <inlineHelpText>Active ACV shows daily changes to annual license revenue via opportunity license start/end date</inlineHelpText>
    <label>Active ACV [USD]</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Finance_Partner__c.field-meta.xml
<CustomField>
    <fullName>Finance_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Finance Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Finance Partner)</relationshipLabel>
    <relationshipName>Accounts5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Auto_Renewal__c.field-meta.xml
<CustomField>
    <fullName>Auto_Renewal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Auto Renewal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Selected_Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Selected_Payment_Type__c</fullName>
    <label>Selected Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct Annual</fullName>
            </value>
            <value>
                <fullName>Direct Monthly</fullName>
            </value>
            <value>
                <fullName>Upfront Payments</fullName>
            </value>
            <value>
                <fullName>Direct Quarterly</fullName>
            </value>
            <value>
                <fullName>Direct Semi-Annual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Blended_Discount__c.field-meta.xml
<CustomField>
    <fullName>Blended_Discount__c</fullName>
    <description>Calculates discount based on Primary Quote. Uses Blended Discount if available; otherwise, computes from list price, amount, and rebates.</description>
    <formula>IF(NOT(ISBLANK(SBQQ__PrimaryQuote__c)), Blended_Discount_CPQ__c,IF(List_Price__c &gt; 0,(List_Price__c-Amount+ABS(Sum_of_Rebates__c))/List_Price__c,0))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Blended Discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Finance_Partner__c.field-meta.xml
<CustomField>
    <fullName>Finance_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Finance Partner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Finance Partner</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Finance Partner)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/License_Term__c.field-meta.xml
<CustomField>
    <fullName>License_Term__c</fullName>
    <defaultValue>36</defaultValue>
    <description>The license term of the opportunity.</description>
    <label>License Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/License_Term_CPQ__c.field-meta.xml
<CustomField>
    <fullName>License_Term_CPQ__c</fullName>
    <description>Pulls the License Term from the Primary Quote. &lt;Check with Chad in a couple of months and evaluate if we still need this.&gt;</description>
    <label>License Term (CPQ)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/License_Term_Formula__c.field-meta.xml
<CustomField>
    <fullName>License_Term_Formula__c</fullName>
    <description>This field displays the license term on the layout without being editable by anyone. Last update GTMS-978</description>
    <formula>IF(
AND(
NOT(ISBLANK(SBQQ__PrimaryQuote__c)),
NOT(ISBLANK(License_Term_CPQ__c)),
License_Term_CPQ__c &gt; 0
),
License_Term_CPQ__c,
License_Term__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>License Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <description>Only applies to revenue opportunities because rebate opportunities are not marked upfront/direct annual/direct monthly.</description>
    <formula>IF((NOT
(ISBLANK(Reseller__c)
)
), &quot;Reseller&quot;,

IF(NOT
(ISBLANK(Finance_Partner__c)
)
, &quot;Finance Partner&quot;,

IF(
ISPICKVAL(Selected_Payment_Type__c, &quot;Direct Monthly&quot;),
&quot;Samsara Financed&quot;,
IF
(ISPICKVAL(Selected_Payment_Type__c, &quot;Direct Quarterly&quot;),
&quot;Samsara Financed&quot;,
IF
(ISPICKVAL(Selected_Payment_Type__c, &quot;Direct Semi-Annual&quot;),
&quot;Samsara Financed&quot;,
IF
(ISPICKVAL(Selected_Payment_Type__c, &quot;Direct Annual&quot;),
&quot;Samsara Financed&quot;,

IF
(OR
(ISPICKVAL(Selected_Payment_Type__c, &quot;Upfront Payments&quot;),
ISPICKVAL(Selected_Payment_Type__c, &quot;&quot;)),&quot;Upfront&quot;,

NULL)
)
)
)
)
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Only applies to revenue opportunities because rebate opportunities are not marked upfront/direct annual/direct monthly.</inlineHelpText>
    <label>Payment Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Renewable_ACV__c.field-meta.xml
<CustomField>
    <fullName>Renewable_ACV__c</fullName>
    <description>Annualized Total License Due</description>
    <formula>Total_License_Due__c / License_Term__c *12</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>License ACV</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Selected_Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Selected_Payment_Type__c</fullName>
    <inlineHelpText>This dropdown list is populated based on what your customer has been approved for in Internal Financing. If you do not see a finance option then your customer has not been approved for that option.</inlineHelpText>
    <label>Selected Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Direct Monthly</fullName>
            </value>
            <value>
                <fullName>Direct Annual</fullName>
            </value>
            <value>
                <fullName>Upfront Payments</fullName>
            </value>
            <value>
                <fullName>Direct Semi-Annual</fullName>
            </value>
            <value>
                <fullName>Direct Quarterly</fullName>
            </value>
            <value>
                <fullName>Net-30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <label>Sub - Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not For Resale (NFR)</fullName>
            </value>
            <value>
                <fullName>Paid Pilot</fullName>
            </value>
            <value>
                <fullName>Upfitter</fullName>
            </value>
            <value>
                <fullName>Auto-Renewal</fullName>
            </value>
            <value>
                <fullName>Split Opp - Q1</fullName>
            </value>
            <value>
                <fullName>Split Opp - Q2</fullName>
            </value>
            <value>
                <fullName>Split Opp - Q3</fullName>
            </value>
            <value>
                <fullName>Split Opp - Q4</fullName>
            </value>
            <value>
                <fullName>Split Opp</fullName>
            </value>
            <value>
                <fullName>Reprocessing Return</fullName>
            </value>
            <value>
                <fullName>Clickpath</fullName>
            </value>
            <value>
                <fullName>Consolidated Renewal</fullName>
            </value>
            <value>
                <fullName>Renewal Extension</fullName>
            </value>
            <value>
                <fullName>Virtual Return</fullName>
            </value>
            <value>
                <fullName>Sales Order X Processing</fullName>
            </value>
            <value>
                <fullName>Upgrade</fullName>
            </value>
            <value>
                <fullName>MX Data Migration</fullName>
            </value>
            <value>
                <fullName>ETF</fullName>
            </value>
            <value>
                <fullName>Remorse Refund - In Policy</fullName>
            </value>
            <value>
                <fullName>Remorse Refund - Approved Out of Policy</fullName>
            </value>
            <value>
                <fullName>Contract Cancellation</fullName>
            </value>
            <value>
                <fullName>Contract Replacement</fullName>
            </value>
            <value>
                <fullName>3PL to OEM transfer</fullName>
            </value>
            <value>
                <fullName>OEM to Customer delivery</fullName>
            </value>
            <value>
                <fullName>HOS No Vehicle</fullName>
                <isActive>false</isActive>
                <label>HOS No Vehicle</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/Finance_Partner__c.field-meta.xml
<CustomField>
    <fullName>Finance_Partner__c</fullName>
    <description>A drop down for reps to select the finance partner they are using</description>
    <label>Finance Partner</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dell Financial Services</fullName>
            </value>
            <value>
                <fullName>Crestmark Vendor Finance a Meta Bank company</fullName>
            </value>
            <value>
                <fullName>Samsara Capital Finance</fullName>
            </value>
            <value>
                <fullName>VAR Technology</fullName>
            </value>
            <value>
                <fullName>Hitachi</fullName>
            </value>
            <value>
                <fullName>Consultative Funding</fullName>
                <label>TFC</label>
            </value>
            <value>
                <fullName>Ascentium</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/License_Term__c.field-meta.xml
<CustomField>
    <fullName>License_Term__c</fullName>
    <formula>Opportunity.License_Term__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>License Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Blended_Discount__c.field-meta.xml
<CustomField>
    <fullName>Blended_Discount__c</fullName>
    <formula>IF(
 List_Amount_Rebate__c &gt; 0, 
 ((List_Amount_Rebate__c - (Net_Amount_Rebate__c - (Buyout_Amount__c +  Subsidy_Amount__c )))/ List_Amount_Rebate__c), 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Blended Discount</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Finance_Partner__c.field-meta.xml
<CustomField>
    <fullName>Finance_Partner__c</fullName>
    <label>Finance Partner</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dell Financial Services</fullName>
            </value>
            <value>
                <fullName>Pathward, National Association</fullName>
            </value>
            <value>
                <fullName>Samsara Capital Finance</fullName>
                <default>true</default>
                <label>Samsara Capital Finance</label>
            </value>
            <value>
                <fullName>Ascentium</fullName>
            </value>
            <value>
                <fullName>Howard Carter Lease Ltd.</fullName>
            </value>
            <value>
                <fullName>Hitachi</fullName>
            </value>
            <value>
                <fullName>LEAF Capital Funding LLC</fullName>
            </value>
            <value>
                <fullName>PNC Bank, National Association</fullName>
            </value>
            <value>
                <fullName>Crestmark Vendor Finance a Meta Bank Company</fullName>
                <isActive>false</isActive>
                <label>Crestmark Vendor Finance a Meta Bank Company</label>
            </value>
            <value>
                <fullName>Maxim Transportation Service</fullName>
                <isActive>false</isActive>
                <label>Maxim Transportation Service</label>
            </value>
            <value>
                <fullName>VAR Technology</fullName>
                <isActive>false</isActive>
                <label>VAR Technology</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/License_Term__c.field-meta.xml
<CustomField>
    <fullName>License_Term__c</fullName>
    <label>License Term</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>36</fullName>
                <default>true</default>
                <label>36</label>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContractAutomation.cls
/**
* Created By : 
* @Date September 10, 2021
*
* @description : This class will be responsible for handling the initiation of contract renewal automation
*
* Modification History:
* Date			Author				Story/Defect			Description
* 2022-08-23	Harsha				GTMS-8374  				Added null check for the renewal opportunity. 
* 2022-04-08	Rodrigo Carpio		GTMS-6084 				Original selected payment type, blended discount, and license term aren't populating
* 
**/
public class ContractAutomation implements Database.Batchable<sObject>{
    private final String query;
    private final Boolean chainFlag;

    public ContractAutomation(String query, Boolean chainFlag) {
        this.query = query;
        this.chainFlag = chainFlag;
    }
    
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext bc, List<Contract> scope){
        List<Account> accountUpdateList = new List<Account>();
        
        Set<Id> originalOptyId = new Set<Id>();
        Set<Id> renewalOptyId = new Set<Id>();
        //List<Opportunity> lstoptyToBeUpdated = new List<Opportunity>();
        List<SBQQ__Quote__c> lstQuoteToBeUpdated = new List<SBQQ__Quote__c>();
        Map<Id, Id> renewalOriginalIDMap = new Map<Id, Id>(); // identifier will be the renewal id, value is the original id
        for(Contract contract : scope){
            // check if the opporunit sub type != Auto-renewal, 
            // payment type = Blended Discount and License is not null or greater than 0
            // added for GTMS-6084
            if (contract.SBQQ__Opportunity__c != null && 
                contract.SBQQ__RenewalOpportunity__c != NULL &&
                contract.SBQQ__RenewalOpportunity__r.Sub_Type__c != 'Auto-Renewal' &&
                contract.SBQQ__Opportunity__r.Payment_Type__c  != null &&
                contract.SBQQ__Opportunity__r.License_Term__c != null &&
                contract.SBQQ__Opportunity__r.License_Term__c>0 &&
                contract.SBQQ__Opportunity__r.Blended_Discount__c  != null &&
                (contract.SBQQ__Opportunity__r.Blended_Discount__c != 0 || (Test.isRunningTest()))) // condition  added for GTMS-6084
            {
                // populated 3 field coming from original to the renewal, if fields are missing
                if (contract.SBQQ__Opportunity__c != null && contract.SBQQ__RenewalOpportunity__c != null) {
                    originalOptyId.add(contract.SBQQ__Opportunity__c);
                	renewalOptyId.add(contract.SBQQ__RenewalOpportunity__c);
                	renewalOriginalIDMap.put(contract.SBQQ__RenewalOpportunity__c, contract.SBQQ__Opportunity__c);
                    system.debug(originalOptyId + 'originalOptyId - renewalOptyId ' + renewalOptyId);
                }
            }
            else 
            {   
                // Check days between today & the Contract End Date
                //Renewal Quoted being marked true will auto generate a renewal quote associated with the Contract
                Integer daysBetween = 0;
                if (contract.EndDate != null) // added the check to avoid null exception
                	daysBetween = (System.Today().daysBetween(Date.valueOf(contract.EndDate)));                
                    contract.SBQQ__RenewalForecast__c = TRUE;
                    if(daysBetween > 0){
                        if(daysBetween <= 90 && contract.SBQQ__RenewalQuoted__c == FALSE){
                            contract.SBQQ__RenewalQuoted__c = TRUE;
                        }  
                    }
                
                
                Boolean escalationCriteriaMet = contract.SBQQ__RenewalOpportunity__r.Renewable_ACV__c < 10000 && 
                    contract.Account.Customer_ARR__c < 25000 && 
                    contract.SBQQ__RenewalOpportunity__r.Finance_Partner__c == null && 
                    (  contract.SBQQ__RenewalOpportunity__r.Payment_Type__c != 'Upfront' || 
                     contract.SBQQ__RenewalOpportunity__r.Payment_Type__c != 'Reseller')? true:false;
                
                //If Evergreen quote then mark as auto renewal
                if(escalationCriteriaMet){
                    contract.Auto_Renewal__c = true;
                    contract.SBQQ__RenewalTerm__c = 12;
                } else{
                    Account contractAccount = new Account(Id=contract.AccountId, Auto_Renewal_Opt_Out__c = true);
                    accountUpdateList.add(contractAccount);
                }   
            }
        }
        if(scope.size() > 0){
           Database.SaveResult[] srList = Database.update(scope, false);
        }
        
        // check if the originalOptyId not empty for GTMS-6084
        if (originalOptyId.size() > 0) {
            Map<Id, Opportunity> optyToBeUpdated = new Map<Id, Opportunity>();
            
            Map<Id, Opportunity> originalOpty = new Map<Id, Opportunity>([SELECT Id, Amount, Blended_Discount__c, Payment_Type__c, License_Term_Formula__c, License_Term_CPQ__c, License_Term__c, Selected_Payment_Type__c, Name, Blended_Discount_CPQ__c, Buyout_Opportunity__c, Subsidy_Opportunity__c,SBQQ__PrimaryQuote__c, SBQQ__PrimaryQuote__r.License_Term__c, SBQQ__PrimaryQuote__r.Selected_Payment_Type__c, SBQQ__PrimaryQuote__r.Original_Blended_Discount__c FROM Opportunity WHERE Id IN :originalOptyId]);
            Map<Id, Opportunity> renewalOpty = new Map<Id, Opportunity>([SELECT Id, Amount, Blended_Discount__c, Payment_Type__c, License_Term_Formula__c, License_Term_CPQ__c, License_Term__c, Selected_Payment_Type__c, Name, Blended_Discount_CPQ__c, Buyout_Opportunity__c, Subsidy_Opportunity__c, SBQQ__PrimaryQuote__c, SBQQ__PrimaryQuote__r.License_Term__c, SBQQ__PrimaryQuote__r.Selected_Payment_Type__c, SBQQ__PrimaryQuote__r.Original_Blended_Discount__c FROM Opportunity WHERE Id IN :renewalOptyId]);
            for (Opportunity opty : renewalOpty.Values()) {
                Id localOrigId = null;
                
                if ( (opty.SBQQ__PrimaryQuote__r.License_Term__c == null) || 
                    (opty.SBQQ__PrimaryQuote__r.Original_Blended_Discount__c  == null || opty.SBQQ__PrimaryQuote__r.Original_Blended_Discount__c  ==0) ||
                    (opty.SBQQ__PrimaryQuote__r.Selected_Payment_Type__c == null) )
                {
                    localOrigId = renewalOriginalIDMap.get(opty.Id);
                    Opportunity origOpty = originalOpty.get(localOrigId);
                    SBQQ__Quote__c renewalQuote = new SBQQ__Quote__c();
                    system.debug('SBQQ__PrimaryQuote__c ' + opty.SBQQ__PrimaryQuote__c);
                    if (opty.SBQQ__PrimaryQuote__c != null) {
                        renewalQuote.Id = opty.SBQQ__PrimaryQuote__c;
                        if (origOpty.License_Term__c != null && origOpty.License_Term__c !=0)
                        renewalQuote.Original_License_Term__c = origOpty.License_Term__c;
                        renewalQuote.Original_Selected_Payment_Type__c = origOpty.Selected_Payment_Type__c;
                        renewalQuote.Original_Blended_Discount__c = origOpty.Blended_Discount__c;                      
                        lstQuoteToBeUpdated.add(renewalQuote);   
                    }
                }                
            }
        }
        
        if (lstQuoteToBeUpdated.size()>0) { // added for GTMS-6084
            system.debug('RODRIGO lstQuoteToBeUpdated ' +lstQuoteToBeUpdated);
            Database.SaveResult[] srList = Database.update(lstQuoteToBeUpdated, false);
            system.debug('RODRIGO lstQuoteToBeUpdated ' +srList);
        }
    }
    
    public void finish(Database.BatchableContext bc){
        if(chainFlag){
            System.debug('CPU time before the job for the class <ContractAutoRenewalAutomation> is scheduled: ' +  Limits.getCpuTime());
            Database.executeBatch(new ContractAutoRenewalAutomation(System.Label.Contract_Auto_Renewal_Automation, true), 5);
            System.debug('CPU time after the job for the class <ContractAutoRenewalAutomation> is completed: ' +  Limits.getCpuTime());
        } 
    }
}