force-app/main/default/objects/Account/fields/BigCommerce_Id__c.field-meta.xml
<CustomField>
    <fullName>BigCommerce_Id__c</fullName>
    <externalId>true</externalId>
    <label>BigCommerce Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Billing_Email__c.field-meta.xml
<CustomField>
    <fullName>Billing_Email__c</fullName>
    <label>Billing_Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Billing_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Billing_First_Name__c</fullName>
    <description>First name of billing contact. There is no direct reference to Billing Contact in Contact table because of email duplication rules. The billing contact in the Contact table will be in one of two places: In a row that directly belongs to the Billing Contact or Under &apos;billing&apos; columns (Billing_FirstName__c, etc) for one of the contacts that shares the same email</description>
    <label>Billing First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Billing_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Billing_Last_Name__c</fullName>
    <description>Billing Last Name.</description>
    <label>Billing Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Current_Owner_Email__c.field-meta.xml
<CustomField>
    <fullName>Current_Owner_Email__c</fullName>
    <label>Current Owner Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Latest_Active_Contract__c.field-meta.xml
<CustomField>
    <fullName>Latest_Active_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Latest Active Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/SAM_Number_Decorated__c.field-meta.xml
<CustomField>
    <fullName>SAM_Number_Decorated__c</fullName>
    <formula>left(SAM_Number_Undecorated__c,1) &amp; &apos;-&apos; &amp; mid(SAM_Number_Undecorated__c,2,3) &amp; &apos;-&apos; &amp;  mid(SAM_Number_Undecorated__c,5,3)&amp; &apos;-&apos; &amp; mid(SAM_Number_Undecorated__c,8,3)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SAM Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SAM_Number_Undecorated__c.field-meta.xml
<CustomField>
    <fullName>SAM_Number_Undecorated__c</fullName>
    <label>SAM Number Undecorated</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <description>This field is being used by Netsuite and code for contracts. Before it is changed Business Systems needs to be notified, as it has a number of dependencies.</description>
    <formula>IF(

CONTAINS(Owner.UserRole.Name, &quot;Small Fleets&quot;),
&quot;Small Business&quot;,
IF(
CONTAINS(Owner.UserRole.Name, &quot;AE1&quot;),
&quot;AE1&quot;,
IF(
OR(
CONTAINS(Owner.UserRole.Name, &quot;Partner&quot;),
CONTAINS(Owner.UserRole.Name, &quot;AE2&quot;)
),
&quot;AE2&quot;,
IF(
CONTAINS(Owner.UserRole.Name, &quot;AE3&quot;),
&quot;AE3&quot;,
IF(
OR(
CONTAINS(Owner.UserRole.Name, &quot;ENT&quot;),
CONTAINS(Owner.UserRole.Name, &quot;Enterprise&quot;),
CONTAINS(Owner.UserRole.Name, &quot;Major&quot;),
CONTAINS(Owner.UserRole.Name, &quot;Field&quot;)
),
&quot;Enterprise&quot;,
&quot;Management&quot;
)
)
)
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Segment (by Current Owner)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Segment_Text_stamped__c.field-meta.xml
<CustomField>
    <fullName>Segment_Text_stamped__c</fullName>
    <description>This is a text field of Segment (by Current Owner)</description>
    <label>Segment Text stamped</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Which_written_language__c.field-meta.xml
<CustomField>
    <fullName>Which_written_language__c</fullName>
    <description>Used to associate the correct written language with an account.</description>
    <inlineHelpText>Used to associate the correct written language with an account. Very important b/c it allows us to ensure the correct IC is assigned &amp; can allow us to potentially send automated emails in their preferred language.</inlineHelpText>
    <label>Which written language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Language</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sync_Object_Field_WebStore__mdt/Sync_Object_Field_WebStore__mdt.object-meta.xml
<CustomObject>
    <description>This metadata is used to track changed fields and fire the platform event Account_Sync_Webstore_Event__e to sync Account fields to to webstore</description>
    <label>Sync Object Field WebStore</label>
    <pluralLabel>Sync Object Fields WebStore</pluralLabel>
</CustomObject>

force-app/main/default/objects/Sync_Object_Field_WebStore__mdt/fields/Null_Check_Needed__c.field-meta.xml
<CustomField>
    <fullName>Null_Check_Needed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to check for null of mandate fields needed for big commerce</description>
    <label>Null Check Needed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Toggle_Platform_Event__mdt/Toggle_Platform_Event__mdt.object-meta.xml
<CustomObject>
    <description>This metadata is used to toggle on and off the Account (Account_Sync_Webstore_Event__e) , Product (Product_Webstore_Event__e), and Customer 360 (Customer_360_Event__e) Platform Events.</description>
    <label>Toggle Platform Event</label>
    <pluralLabel>Toggle Platform Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Toggle_Platform_Event__mdt/fields/toggle__c.field-meta.xml
<CustomField>
    <fullName>toggle__c</fullName>
    <defaultValue>false</defaultValue>
    <label>toggle</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Language.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Dutch</fullName>
    </customValue>
    <customValue>
        <fullName>English</fullName>
    </customValue>
    <customValue>
        <fullName>French</fullName>
    </customValue>
    <customValue>
        <fullName>German</fullName>
    </customValue>
    <customValue>
        <fullName>Spanish</fullName>
    </customValue>
    <customValue>
        <fullName>Italian</fullName>
    </customValue>
    <description>Used for any language picklist</description>
    <masterLabel>Language</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TrackAccountFieldsToPublishPlatEvents.cls
public class TrackAccountFieldsToPublishPlatEvents {

    public static List<Account> trackAccountFields(Set<id> idSet,sObjectType objType){
        List<Account> accountstoUpdate = new List<Account>();
        
        String query = 'select id,Name,Current_Owner_Email__c, Which_Written_Language__c,BigCommerce_Id__c,Push_to_Webstore__c,CurrencyIsoCode,Segment__c ,Segment_Text_Stamped__c,SAM_Number_Undecorated__c,SAM_Number_Decorated__c,Billing_Email__c,Billing_First_Name__c ,Billing_Last_Name__c ,BillingCountry,BillingCountryCode, BillingState,BillingStateCode,Latest_Active_Contract__c from Account where ';
        query += (objType==Contract.sObjectType)?'Latest_Active_contract__c in:idSet':'Ownerid in:idSet';
        
        List<Account> accList = Database.query(query);
        
        if(!accList.isEmpty()){
            Toggle_Platform_Event__mdt accountEventToggle = Toggle_Platform_Event__mdt.getInstance('Account_Sync_Webstore_Event');
            Sync_Object_Field_WebStore__mdt [] accountNullCheckFields = [Select Id,Object_Api_Name__c,Field_Api_Name__c,Null_Check_Needed__c from Sync_Object_Field_WebStore__mdt Where Object_Api_Name__c = 'Account' and Null_Check_Needed__c = true];
            
            for(Account acc : accList){
                Boolean nullFlagCheck = verifyNullCheck(acc,accountNullCheckFields);
                if ((nullFlagCheck || acc.BigCommerce_Id__c != null) && acc.Push_to_Webstore__c == false && accountEventToggle.toggle__c){ 
                    accountstoUpdate.add(new Account(Id = acc.Id, Push_to_Webstore__c = true));
                }
            }
        }
        return accountstoUpdate;
    }
    
    public static Boolean verifyNullCheck(Account Acc,Sync_Object_Field_WebStore__mdt [] AccountNullCheckFields){
        for(Sync_Object_Field_WebStore__mdt EachMdtField: AccountNullCheckFields){
            if(Acc.get(EachMdtField.Field_Api_Name__c)==null){
                return false; 
            }
        }
        return true;
    }
}