force-app/main/default/objects/Account/fields/Billing_Contact__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Billing contact. Required if customer requests terms</description>
    <label>Billing Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Account.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Billing_Email__c.field-meta.xml
<CustomField>
    <fullName>Billing_Email__c</fullName>
    <label>Billing_Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Organization_Size__c.field-meta.xml
<CustomField>
    <fullName>Organization_Size__c</fullName>
    <description>Number of employees or students</description>
    <inlineHelpText>Number of employees or students</inlineHelpText>
    <label>Organization Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 - 99</fullName>
            </value>
            <value>
                <fullName>100 - 499</fullName>
            </value>
            <value>
                <fullName>500 - 999</fullName>
            </value>
            <value>
                <fullName>1000 - 4999</fullName>
            </value>
            <value>
                <fullName>5000+</fullName>
            </value>
            <value>
                <fullName>0</fullName>
                <isActive>false</isActive>
                <label>0</label>
            </value>
            <value>
                <fullName>1-99</fullName>
                <isActive>false</isActive>
                <label>1-99</label>
            </value>
            <value>
                <fullName>1/1/1999 12:00:00 AM</fullName>
                <isActive>false</isActive>
                <label>1/1/1999 12:00:00 AM</label>
            </value>
            <value>
                <fullName>10</fullName>
                <isActive>false</isActive>
                <label>10</label>
            </value>
            <value>
                <fullName>100 - 999</fullName>
                <isActive>false</isActive>
                <label>100 - 999</label>
            </value>
            <value>
                <fullName>100-499</fullName>
                <isActive>false</isActive>
                <label>100-499</label>
            </value>
            <value>
                <fullName>1000+</fullName>
                <isActive>false</isActive>
                <label>1000+</label>
            </value>
            <value>
                <fullName>1000-4999</fullName>
                <isActive>false</isActive>
                <label>1000-4999</label>
            </value>
            <value>
                <fullName>10000+</fullName>
                <isActive>false</isActive>
                <label>10000+</label>
            </value>
            <value>
                <fullName>11</fullName>
                <isActive>false</isActive>
                <label>11</label>
            </value>
            <value>
                <fullName>13</fullName>
                <isActive>false</isActive>
                <label>13</label>
            </value>
            <value>
                <fullName>200</fullName>
                <isActive>false</isActive>
                <label>200</label>
            </value>
            <value>
                <fullName>201-500</fullName>
                <isActive>false</isActive>
                <label>201-500</label>
            </value>
            <value>
                <fullName>21</fullName>
                <isActive>false</isActive>
                <label>21</label>
            </value>
            <value>
                <fullName>22</fullName>
                <isActive>false</isActive>
                <label>22</label>
            </value>
            <value>
                <fullName>29</fullName>
                <isActive>false</isActive>
                <label>29</label>
            </value>
            <value>
                <fullName>34</fullName>
                <isActive>false</isActive>
                <label>34</label>
            </value>
            <value>
                <fullName>36161</fullName>
                <isActive>false</isActive>
                <label>36161</label>
            </value>
            <value>
                <fullName>42</fullName>
                <isActive>false</isActive>
                <label>42</label>
            </value>
            <value>
                <fullName>495 - 1000</fullName>
                <isActive>false</isActive>
                <label>495 - 1000</label>
            </value>
            <value>
                <fullName>496 - 1000</fullName>
                <isActive>false</isActive>
                <label>496 - 1000</label>
            </value>
            <value>
                <fullName>497 - 1000</fullName>
                <isActive>false</isActive>
                <label>497 - 1000</label>
            </value>
            <value>
                <fullName>498 - 1000</fullName>
                <isActive>false</isActive>
                <label>498 - 1000</label>
            </value>
            <value>
                <fullName>499 - 1000</fullName>
                <isActive>false</isActive>
                <label>499 - 1000</label>
            </value>
            <value>
                <fullName>500 - 1000</fullName>
                <isActive>false</isActive>
                <label>500 - 1000</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Fleet.recordType-meta.xml
<RecordType>
    <fullName>Fleet</fullName>
    <active>true</active>
    <description>Fleet account</description>
    <label>Fleet</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Organization_Size__c.field-meta.xml
<CustomField>
    <fullName>Organization_Size__c</fullName>
    <formula>TEXT(Account.Organization_Size__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Please edit on the Account page.</inlineHelpText>
    <label>Organization Size</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Fleet.recordType-meta.xml
<RecordType>
    <fullName>Fleet</fullName>
    <active>true</active>
    <description>Fleet contact</description>
    <label>Fleet</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Shipping_Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Address_Line_1__c</fullName>
    <label>Shipping Address Line 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Shipping_City__c.field-meta.xml
<CustomField>
    <fullName>Shipping_City__c</fullName>
    <label>Shipping City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Shipping_Contact__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Shipping Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunity_Shipping_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Shipping_State__c.field-meta.xml
<CustomField>
    <fullName>Shipping_State__c</fullName>
    <label>Shipping State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Shipping_Country__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Australian Capital Territory</fullName>
            </value>
            <value>
                <fullName>New South Wales</fullName>
            </value>
            <value>
                <fullName>Northern Territory</fullName>
            </value>
            <value>
                <fullName>Queensland</fullName>
            </value>
            <value>
                <fullName>South Australia</fullName>
            </value>
            <value>
                <fullName>Tasmania</fullName>
            </value>
            <value>
                <fullName>Victoria</fullName>
            </value>
            <value>
                <fullName>Western Australia</fullName>
            </value>
            <value>
                <fullName>Acre</fullName>
            </value>
            <value>
                <fullName>Alagoas</fullName>
            </value>
            <value>
                <fullName>Amazonas</fullName>
            </value>
            <value>
                <fullName>Amapá</fullName>
            </value>
            <value>
                <fullName>Bahia</fullName>
            </value>
            <value>
                <fullName>Ceará</fullName>
            </value>
            <value>
                <fullName>Distrito Federal</fullName>
            </value>
            <value>
                <fullName>Espírito Santo</fullName>
            </value>
            <value>
                <fullName>Goiás</fullName>
            </value>
            <value>
                <fullName>Maranhão</fullName>
            </value>
            <value>
                <fullName>Minas Gerais</fullName>
            </value>
            <value>
                <fullName>Mato Grosso do Sul</fullName>
            </value>
            <value>
                <fullName>Mato Grosso</fullName>
            </value>
            <value>
                <fullName>Pará</fullName>
            </value>
            <value>
                <fullName>Paraíba</fullName>
            </value>
            <value>
                <fullName>Pernambuco</fullName>
            </value>
            <value>
                <fullName>Piauí</fullName>
            </value>
            <value>
                <fullName>Paraná</fullName>
            </value>
            <value>
                <fullName>Rio de Janeiro</fullName>
            </value>
            <value>
                <fullName>Rio Grande do Norte</fullName>
            </value>
            <value>
                <fullName>Rondônia</fullName>
            </value>
            <value>
                <fullName>Roraima</fullName>
            </value>
            <value>
                <fullName>Ontario</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipping_Address__c/Shipping_Address__c.object-meta.xml
<CustomObject>
    <label>Shipping Address</label>
    <nameField>
        <label>Shipping Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipping Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipping_Address__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Shipping Addresses</relationshipLabel>
    <relationshipName>Shipping_Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Address__c/fields/Shipping_Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Address_Line_1__c</fullName>
    <inlineHelpText>Shipping address should not include a PO Box.
This field appears on the shipping label: 
[First Name] [Last Name]
[Shipping Address Line 1]
[Shipping Address Line 2]
[Shipping City], [Shipping State] [Shipping Zip Code]</inlineHelpText>
    <label>Shipping Address Line 1</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipping_Address__c/fields/Shipping_City__c.field-meta.xml
<CustomField>
    <fullName>Shipping_City__c</fullName>
    <inlineHelpText>This field appears on the shipping label: 
[First Name] [Last Name]
[Shipping Address Line 1]
[Shipping Address Line 2]
[Shipping City], [Shipping State] [Shipping Zip Code]</inlineHelpText>
    <label>Shipping City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipping_Address__c/fields/Shipping_Contact__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Shipping Addresses</relationshipLabel>
    <relationshipName>Shipping_Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OppHelperForOrderAndFinanceTest.cls
@isTest
public class OppHelperForOrderAndFinanceTest {
   @testSetup
   static void setupTestData() {
       // Create Samsara - Finance Profile
       Profile financeProfile = [SELECT Id FROM Profile WHERE Name = 'Samsara - Finance' LIMIT 1];

       // Create a test user with financeProfile
       User financeUser = new User(
           FirstName = 'Test',
           LastName = 'User',
           Alias = 'tuser',
           Email = 'testuser@example.com',
           Username = 'testuser@example.com' + DateTime.now().getTime(),
           ProfileId = financeProfile.Id,
           TimeZoneSidKey = 'America/Los_Angeles',
           LocaleSidKey = 'en_US',
           EmailEncodingKey = 'UTF-8',
           LanguageLocaleKey = 'en_US',
           UserPermissionsOfflineUser = false,
           EmployeeNumber = '12345'
       );
       insert financeUser;
   }

   @isTest
   static void testUpdateOrderManagementProcessor() {
       User financeUser = [SELECT Id FROM User WHERE Email = 'testuser@example.com' LIMIT 1];
       System.runAs(financeUser) {
           
			Account acc = new Account(
                Name = 'MyTestAccount',
                Type = 'Fleet',
                Industry = 'Other',
                Organization_Size__c = '1 - 99',
                BillingStreet = '123 Main St, San Francisco CA, 94110',
                BillingState = 'California',
                BillingCountry = 'United States',
                BillingCity = 'San Francisco',
                BillingPostalCode = '94110',
                Billing_Email__c = 'test@test.test'
            );
           insert acc;
           
           Contact con = new Contact(AccountId = acc.Id, LastName = 'test', Email = 'test@test.test');
           insert con;
           
           acc.Billing_Contact__c = con.Id;
           update acc;
           
           Shipping_Address__c shipTo = new Shipping_Address__c(Account__c = acc.Id, Shipping_Contact__c = con.Id, Shipping_Address_Line_1__c = '444 Deharo St'
                                                            , Shipping_City__c = 'San', Shipping_State__c = 'Ontario', Shipping_Country__c ='Canada'
                                                            , Shipping_Zip_Code__c = '95054', Name = 'Ship To One');
           insert shipTo;
           Test.startTest();
           Opportunity oldOpp = new Opportunity(
               Shipping_Address_NEW__c = shipTo.Id,
               Name = 'Old Opportunity',
               Shipping_Country__c = 'Canada',
               StageName = 'Closing',
               CloseDate = Date.today(),
               AccountId = acc.Id
           );
           insert oldOpp;
		
           Opportunity newOpp1 = new Opportunity(
               Id = oldOpp.Id,
               Name = 'New Opportunity 1',
               StageName = 'Orders Processing',
               CloseDate = Date.today(),
               Order_Management_Processor__c = null,
			   AccountId = acc.Id
           );

           Opportunity oldOpp2 = new Opportunity(
               Shipping_Address_NEW__c = shipTo.Id,
               Name = 'Old Opportunity 2',
               Shipping_Country__c = 'Canada',
               StageName = 'Closing',
               CloseDate = Date.today(),
               AccountId = acc.Id
           );
           insert oldOpp2;

           Opportunity newOpp2 = new Opportunity(
               Id = oldOpp2.Id,
               Name = 'New Opportunity 2',
               StageName = 'Purchase',
               CloseDate = Date.today(),
               Order_Management_Processor__c = null,
			   AccountId = acc.Id
           );

           Opportunity oldOpp3 = new Opportunity(
               Shipping_Address_NEW__c = shipTo.Id,
               Name = 'Old Opportunity 3',
               Shipping_Country__c = 'Canada',
               StageName = 'Orders Processing',
               CloseDate = Date.today(),
               Order_Management_Processor__c = 'Previous User',
               AccountId = acc.Id
           );
           insert oldOpp3;

           Opportunity newOpp3 = new Opportunity(
               Id = oldOpp3.Id,
               Name = 'New Opportunity 3',
               StageName = 'Purchase',
               CloseDate = Date.today(),
               Order_Management_Processor__c = 'Previous User',
			   AccountId = acc.Id
           );

           // Prepare input data for the method
           List<Opportunity> newOppList = new List<Opportunity>{ newOpp1, newOpp2, newOpp3 };
           Map<Id, Opportunity> oldOppMap = new Map<Id, Opportunity>{ 
               oldOpp.Id => oldOpp, 
               oldOpp2.Id => oldOpp2, 
               oldOpp3.Id => oldOpp3 
           };

           // Call the method
           OppHelperForOrderAndFinance helper = new OppHelperForOrderAndFinance();
           helper.updateOrderManagementProcessor(newOppList, oldOppMap);
           
           Test.stopTest();
       }
   }
}