force-app/main/default/objects/Account/fields/Billing_Contact__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Billing contact. Required if customer requests terms</description>
    <label>Billing Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Account.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Partner_Discount__c.field-meta.xml
<CustomField>
    <fullName>Partner_Discount__c</fullName>
    <description>GTMS-6421</description>
    <label>Partner Discount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <description>Account type for partners - resellers, referral partners, corporate partners</description>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/Channel_Relationship__c/Channel_Relationship__c.object-meta.xml
<CustomObject>
    <description>Used to related channel partners with opportunities (and vice versa).</description>
    <label>Channel Relationship</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Channel Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Channel Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel_Relationship__c/fields/Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner__c</fullName>
    <label>Partner Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Partner</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Channel Relationships</relationshipLabel>
    <relationshipName>Channel_Relationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Channel_Relationship__c/fields/Channel_Partner_Representative__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner_Representative__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Partner Representative</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Channel_Partner__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Channel Relationships</relationshipLabel>
    <relationshipName>Channel_Relationship_Representative</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Channel_Relationship__c/fields/Customer_Account__c.field-meta.xml
<CustomField>
    <fullName>Customer_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>added for GTMS-16044</description>
    <label>Customer Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Channel Relationships (Customer Account Name)</relationshipLabel>
    <relationshipName>Channel_Relationships3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Channel_Relationship__c/fields/Customer_Contact__c.field-meta.xml
<CustomField>
    <fullName>Customer_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>added for GTMS-16044</description>
    <label>Customer Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Channel Relationships (Customer Contact)</relationshipLabel>
    <relationshipName>Channel_Relationships1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Channel_Relationship__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Channel Relationships</relationshipLabel>
    <relationshipName>Channel_Relationships</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Channel_Relationship__c/fields/Partner_Contact__c.field-meta.xml
<CustomField>
    <fullName>Partner_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>added for GTMS-16044</description>
    <label>Partner Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Channel Relationships (Partner Contact)</relationshipLabel>
    <relationshipName>Channel_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Channel_Relationship__c/fields/Partner_Deal_14_Day_Auto_Tag__c.field-meta.xml
<CustomField>
    <fullName>Partner_Deal_14_Day_Auto_Tag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Partner Deal 14 Day Auto-Tag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Channel_Relationship__c/fields/Partner_Discount__c.field-meta.xml
<CustomField>
    <fullName>Partner_Discount__c</fullName>
    <description>GTMS-6421: Partner Discount information that is populated on the related partner account</description>
    <label>Partner Discount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Channel_Relationship__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <description>GTMS-16042</description>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CM33</fullName>
            </value>
            <value>
                <fullName>CM34</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Channel_Relationship__c/fields/Samsara_Product_SKU__c.field-meta.xml
<CustomField>
    <fullName>Samsara_Product_SKU__c</fullName>
    <description>added for GTMS-16044</description>
    <label>Samsara Product SKU</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CM33</fullName>
            </value>
            <value>
                <fullName>CM34</fullName>
            </value>
            <value>
                <fullName>CM31</fullName>
                <isActive>false</isActive>
                <label>CM31</label>
            </value>
            <value>
                <fullName>CM32</fullName>
                <isActive>false</isActive>
                <label>CM32</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Channel_Relationship__c/fields/Source_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Source_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Source Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Channel Relationships (Source Opportunity)</relationshipLabel>
    <relationshipName>Channel_Relationships2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Channel_Relationship__c/fields/Subsidy_Amount__c.field-meta.xml
<CustomField>
    <fullName>Subsidy_Amount__c</fullName>
    <description>added for GTMS-16044</description>
    <label>Subsidy Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Insurance_Partner__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Insurance partner associated with an opportunity.</description>
    <label>Insurance Partner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Insurance Partner</value>
        </filterItems>
        <filterItems>
            <field>Account.Record_Type__c</field>
            <operation>equals</operation>
            <value>Partner</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Insurance Partner End-Customer Opportunities</relationshipLabel>
    <relationshipName>Insurance_Partner_Customer_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Subsidy_Amount__c.field-meta.xml
<CustomField>
    <fullName>Subsidy_Amount__c</fullName>
    <description>Subsidy amount from rebate opportunity., updated for GTMS-27234</description>
    <formula>IF(
    SBQQ__PrimaryQuote__r.New_DC_architecture__c,
    SBQQ__PrimaryQuote__r.Subsidy_Amount__c * -1,
    Subsidy_Opportunity__r.Rebate_Amount__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Subsidy amount from rebate opportunity.</inlineHelpText>
    <label>Sum of Subsidy</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Subsidy_Amount_New__c.field-meta.xml
<CustomField>
    <fullName>Subsidy_Amount_New__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Subsidy Amount New</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Channel_Partner_Discount__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner_Discount__c</fullName>
    <description>GTMS-6421: This field will hold the partner discount that is set on the partner account record.</description>
    <label>Channel Partner Discount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Subsidy_Amount__c.field-meta.xml
<CustomField>
    <fullName>Subsidy_Amount__c</fullName>
    <label>Sum of Subsidy</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ChannelRelationshipHelper.cls
/**
* Created By : 
* @Date 
*
* @description : This class will be responsible for handling all Channel Relationship  Operations
* SFA-11
* Dec-01-2023 : Rodrigo - (GTMS-16044) country/state code related logic
* May-07-2025 : Azra - (GTMS- 27725) Replaced Partner_Contact__c with Channel_Partner_Representative__c
**/
public class ChannelRelationshipHelper {
    
    // GTMS-16044 to set field values if manually set
    public static void setDefualtFieldValues(List<Channel_Relationship__c> newChannelRelationshipList) { 
        Set<Id>opptyIdList = new Set<Id>();
        Set<Id>accountIdList = new Set<Id>();
        
        // get all opportunity ids
        FOR(Channel_Relationship__c crObj : newChannelRelationshipList) {
            if (crObj.Channel_Partner__c!=null)
                accountIdList.add(crObj.Channel_Partner__c);
            opptyIdList.add(crObj.Opportunity__c);
        }
        Map<Id, Opportunity>  opptyMap = new Map<Id, Opportunity>([SELECT Id, Insurance_Partner__c, AccountId,
                                                                    Subsidy_Amount_New__c 
                                                                   FROM Opportunity 
                                                                   WHERE Id IN: opptyIdList]);
        // get all account id
        FOR(Opportunity opptyObj : opptyMap.values()) {
            accountIdList.add(opptyObj.AccountId);
            if(opptyObj.Insurance_Partner__c!=null)
                accountIdList.add(opptyObj.Insurance_Partner__c);
        }
        
        Map<Id, Account> accountMap = new Map<Id, Account>([SELECT Id, Billing_Contact__c, BillingCity, BillingCountryCode,
                                                            BillingStateCode, BillingPostalCode, BillingStreet
                                                             FROM Account 
                                                            WHERE Id IN: accountIdList]);
        FOR(Channel_Relationship__c crObj : newChannelRelationshipList) {
            Opportunity opptyRec =  opptyMap.get(crObj.Opportunity__c);
            Account acctRec = new Account();
            Account acctRec2 = new Account();
            if (crObj.Channel_Partner__c != null)
                acctRec2 = accountMap.get(crObj.Channel_Partner__c);
            if(opptyRec != null) {
                if (crObj.Channel_Partner__c == null)
                	acctRec2 = accountMap.get(opptyRec.Insurance_Partner__c);
                acctRec = accountMap.get(opptyRec.AccountId);
            }
            
            if(crObj.Samsara_Product_SKU__c == null) {
                crObj.Samsara_Product_SKU__c = crObj.Product_Type__c;
            }
            if(crObj.Channel_Partner_Representative__c  == null && acctRec != null) {
                if(acctRec != null)
                	crObj.Channel_Partner_Representative__c  = acctRec.Billing_Contact__c;
            }
            if(crObj.Customer_Account__c == null && opptyRec != null) {
                crObj.Customer_Account__c = opptyRec.AccountId;
            }
            if(crObj.Customer_Contact__c == null && acctRec2 != null) {
                if(acctRec != null)
                	crObj.Customer_Contact__c = acctRec2.Billing_Contact__c;
            }
            if(crObj.Subsidy_Amount__c == null && opptyRec != null) {
                crObj.Subsidy_Amount__c = opptyRec.Subsidy_Amount_New__c;
            }
            if(crObj.Customer_Address__City__s==null && acctRec != null) {
                crObj.Customer_Address__City__s = acctRec.BillingCity;
            }
            
            if(crObj.Customer_Address__CountryCode__s==null && acctRec != null) {
                crObj.Customer_Address__CountryCode__s = acctRec.BillingCountryCode;
            }
            
            if(crObj.Customer_Address__PostalCode__s==null && acctRec != null) {
                crObj.Customer_Address__PostalCode__s = acctRec.BillingPostalCode;
            }
            if(crObj.Customer_Address__StateCode__s==null && acctRec != null && crObj.Customer_Address__CountryCode__s==acctRec.BillingCountryCode) {
                crObj.Customer_Address__StateCode__s = acctRec.BillingStateCode;
            }
            if(crObj.Customer_Address__Street__s==null && acctRec != null) {
                crObj.Customer_Address__Street__s = acctRec.BillingStreet;
            }
            
            if(crObj.Partner_Address__City__s==null && acctRec2 != null) {
                crObj.Partner_Address__City__s = acctRec2.BillingCity;
            }
            
            if(crObj.Partner_Address__CountryCode__s==null && acctRec2 != null) {
                crObj.Partner_Address__CountryCode__s = acctRec2.BillingCountryCode;
            }
            
            if(crObj.Partner_Address__PostalCode__s==null && acctRec2 != null) {
                crObj.Partner_Address__PostalCode__s = acctRec2.BillingPostalCode;
            }
            if(crObj.Partner_Address__StateCode__s==null && acctRec2 != null && crObj.Partner_Address__CountryCode__s==acctRec2.BillingCountryCode) {
                crObj.Partner_Address__StateCode__s = acctRec2.BillingStateCode;
            }
            if(crObj.Partner_Address__Street__s==null && acctRec2 != null) {
                crObj.Partner_Address__Street__s = acctRec2.BillingStreet;
            }
        }
    }
    
    public static void updateCPQQuoteWithPartnerDetails(List<Channel_Relationship__c> newChannelRelationshipList){
        Map<Id, Channel_Relationship__c> oppIdToChannelRelationship = new Map<Id, Channel_Relationship__c>();

        for(Channel_Relationship__c channelRel: newChannelRelationshipList){
            if(channelRel.Opportunity__c != null){
                oppIdToChannelRelationship.put(channelRel.Opportunity__c, channelRel);
            }
        }

        Map<Id, SBQQ__Quote__c> cpqDraftQuotes = new Map<Id, SBQQ__Quote__c>([  SELECT  Id,
                                                                                        SBQQ__Partner__c, 
                                                                                        SBQQ__Opportunity2__c,
                                                                              			Channel_Partner_Discount__c 
                                                                                FROM SBQQ__Quote__c
                                                                                WHERE SBQQ__Opportunity2__c IN : oppIdToChannelRelationship.keySet()
                                                                                AND SBQQ__Status__c = :  'Draft']);
        
        for(SBQQ__Quote__c cpqDraftQuote: cpqDraftQuotes.values()){
            Id partnerAccount = oppIdToChannelRelationship.get(cpqDraftQuote.SBQQ__Opportunity2__c).Channel_Partner__c;
            cpqDraftQuote.SBQQ__Partner__c = partnerAccount;
            cpqDraftQuote.Channel_Partner_Discount__c = oppIdToChannelRelationship.get(cpqDraftQuote.SBQQ__Opportunity2__c).Partner_Discount__c;
        }                  
        
        if(cpqDraftQuotes.size() > 0){
            update cpqDraftQuotes.values();
        }
    } 
    
    // GTMS-16044 get country/state code starts here
    public class countryStateCodeReq {
        @InvocableVariable public string countryName;
        @InvocableVariable public string stateName;
        @InvocableVariable public string countryCode;
        @InvocableVariable public string stateCode;
    }
    
    public class countryStateCodeResp {
        @InvocableVariable public string countryCode;
        @InvocableVariable public string stateCode;
        @InvocableVariable public string countryName;
        @InvocableVariable public string stateName;
    }
    
    @InvocableMethod(label='Get Country/State Code')
    public static List<countryStateCodeResp> getCountryStateCode(List<countryStateCodeReq> requestData){ 
        List<countryStateCodeResp> responseDataList = new List<countryStateCodeResp>();
        countryStateCodeResp responseData = new countryStateCodeResp();
        //if (requestData[0].countryName != null) {
            string countryName = requestData[0].countryName;
            string stateName = requestData[0].stateName;
            string countryCode = requestData[0].countryCode;
            string stateCode = requestData[0].stateCode;
            Schema.DescribeFieldResult fieldResultCountry = User.Countrycode.getDescribe();
            List<Schema.PicklistEntry> pleCountry = fieldResultCountry.getPicklistValues();
            //System.debug('Picklist::'+pleCountry);
            for( Schema.PicklistEntry f : pleCountry){
                if(countryName!= null && countryName == f.getLabel())
                    responseData.countryCode = f.getValue();
                if(countryCode!= null && countryCode == f.getValue())
                    responseData.countryName = f.getLabel();
                //System.debug(f.getLabel() +'::'+ f.getValue());
            }
            
            Schema.DescribeFieldResult fieldResultState = User.Statecode.getDescribe();
            List<Schema.PicklistEntry> pleState = fieldResultState.getPicklistValues();
            //System.debug('Picklist::'+pleState);
            for( Schema.PicklistEntry f : pleState){
                if(stateName!= null && stateName == f.getLabel())
                    responseData.stateCode = f.getValue();
                if(stateCode!= null && stateCode == f.getValue())
                    responseData.stateName = f.getLabel();
                //System.debug(f.getLabel() +'::'+ f.getValue());
            }
        
            
        //}
        system.debug('responseData ' + responseData);
        responseDataList.add(responseData);
       	return responseDataList;
    }
    // GTMS-16044 get country/state code ends here
    
    // GTMS-26105 14 Day Auto-Tag for Partner Deals code starts here
    public static void updNewChannelRelationship14DaysAutoTag(List<Channel_Relationship__c> newChannelRelationshipList) {
        If(newChannelRelationshipList[0].Customer_Account__c != null && newChannelRelationshipList[0].Channel_Partner__c != null) {
            Channel_Relationship__c OldCR = new Channel_Relationship__c();
            
            String query = 'SELECT ';
            for(Schema.FieldSetMember f : SObjectType.Channel_Relationship__c.fieldSets.Auto_Tag_Partner_Deals_14_Days.getFields()) {
                query += f.getFieldPath() + ', ';
            }
            query += 'Id, Opportunity__c, Opportunity__r.LastModifiedDate FROM Channel_Relationship__c WHERE Channel_Partner__c = \'' + newChannelRelationshipList[0].Channel_Partner__c
                + '\' AND Opportunity__r.StageName = \'Closed Lost\' AND Opportunity__r.CloseDate = LAST_N_DAYS:14 AND Opportunity__r.IsClosed = true'
                + ' AND Opportunity__r.AccountId = \'' + newChannelRelationshipList[0].Customer_Account__c 
                + '\' Order by Opportunity__r.LastModifiedDate desc LIMIT 1';
            
            if(Database.query(query).size() > 0){
                OldCR = Database.query(query);
                Channel_Relationship__c NewCR = new Channel_Relationship__c();           
                List<Schema.FieldSetMember> schemaset= Schema.SObjectType.Channel_Relationship__c.fieldSets.Auto_Tag_Partner_Deals_14_Days.getFields();
                NewCR.put('Id', newChannelRelationshipList[0].Id);
                NewCR.put('Source_Opportunity__c', OldCR.Opportunity__c);
                NewCR.put('Partner_Deal_14_Day_Auto_Tag__c', true);
                for(integer a=0; a<schemaset.size(); a++){
                    NewCR.put(schemaset[a].getFieldPath(), OldCR.get(schemaset[a].getFieldPath()));
                }
                
                Update NewCR;
            }
        }  
    }
    // GTMS-26105 14 Day Auto-Tag for Partner Deals code ends here
}