force-app/main/default/objects/Account/fields/Billing_Email__c.field-meta.xml
<CustomField>
    <fullName>Billing_Email__c</fullName>
    <label>Billing_Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Organization_Size__c.field-meta.xml
<CustomField>
    <fullName>Organization_Size__c</fullName>
    <description>Number of employees or students</description>
    <inlineHelpText>Number of employees or students</inlineHelpText>
    <label>Organization Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 - 99</fullName>
            </value>
            <value>
                <fullName>100 - 499</fullName>
            </value>
            <value>
                <fullName>500 - 999</fullName>
            </value>
            <value>
                <fullName>1000 - 4999</fullName>
            </value>
            <value>
                <fullName>5000+</fullName>
            </value>
            <value>
                <fullName>0</fullName>
                <isActive>false</isActive>
                <label>0</label>
            </value>
            <value>
                <fullName>1-99</fullName>
                <isActive>false</isActive>
                <label>1-99</label>
            </value>
            <value>
                <fullName>1/1/1999 12:00:00 AM</fullName>
                <isActive>false</isActive>
                <label>1/1/1999 12:00:00 AM</label>
            </value>
            <value>
                <fullName>10</fullName>
                <isActive>false</isActive>
                <label>10</label>
            </value>
            <value>
                <fullName>100 - 999</fullName>
                <isActive>false</isActive>
                <label>100 - 999</label>
            </value>
            <value>
                <fullName>100-499</fullName>
                <isActive>false</isActive>
                <label>100-499</label>
            </value>
            <value>
                <fullName>1000+</fullName>
                <isActive>false</isActive>
                <label>1000+</label>
            </value>
            <value>
                <fullName>1000-4999</fullName>
                <isActive>false</isActive>
                <label>1000-4999</label>
            </value>
            <value>
                <fullName>10000+</fullName>
                <isActive>false</isActive>
                <label>10000+</label>
            </value>
            <value>
                <fullName>11</fullName>
                <isActive>false</isActive>
                <label>11</label>
            </value>
            <value>
                <fullName>13</fullName>
                <isActive>false</isActive>
                <label>13</label>
            </value>
            <value>
                <fullName>200</fullName>
                <isActive>false</isActive>
                <label>200</label>
            </value>
            <value>
                <fullName>201-500</fullName>
                <isActive>false</isActive>
                <label>201-500</label>
            </value>
            <value>
                <fullName>21</fullName>
                <isActive>false</isActive>
                <label>21</label>
            </value>
            <value>
                <fullName>22</fullName>
                <isActive>false</isActive>
                <label>22</label>
            </value>
            <value>
                <fullName>29</fullName>
                <isActive>false</isActive>
                <label>29</label>
            </value>
            <value>
                <fullName>34</fullName>
                <isActive>false</isActive>
                <label>34</label>
            </value>
            <value>
                <fullName>36161</fullName>
                <isActive>false</isActive>
                <label>36161</label>
            </value>
            <value>
                <fullName>42</fullName>
                <isActive>false</isActive>
                <label>42</label>
            </value>
            <value>
                <fullName>495 - 1000</fullName>
                <isActive>false</isActive>
                <label>495 - 1000</label>
            </value>
            <value>
                <fullName>496 - 1000</fullName>
                <isActive>false</isActive>
                <label>496 - 1000</label>
            </value>
            <value>
                <fullName>497 - 1000</fullName>
                <isActive>false</isActive>
                <label>497 - 1000</label>
            </value>
            <value>
                <fullName>498 - 1000</fullName>
                <isActive>false</isActive>
                <label>498 - 1000</label>
            </value>
            <value>
                <fullName>499 - 1000</fullName>
                <isActive>false</isActive>
                <label>499 - 1000</label>
            </value>
            <value>
                <fullName>500 - 1000</fullName>
                <isActive>false</isActive>
                <label>500 - 1000</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Global_Automation_Settings__c/Global_Automation_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Global Automation Settings to toggle automation on &amp; off.</description>
    <label>Global Automation Settings</label>
</CustomObject>

force-app/main/default/objects/Global_Automation_Settings__c/fields/Skip_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Skip_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Skip Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Global_Automation_Settings__c/fields/Skip_Validation_Rule__c.field-meta.xml
<CustomField>
    <fullName>Skip_Validation_Rule__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Skip Validation Rule</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Price_Book_Name__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_Name__c</fullName>
    <defaultValue>&quot;Samsara Standard&quot;</defaultValue>
    <description>Price Book Name, populated by workflow / field update</description>
    <label>Price Book Name</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Selected_Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Selected_Payment_Type__c</fullName>
    <inlineHelpText>This dropdown list is populated based on what your customer has been approved for in Internal Financing. If you do not see a finance option then your customer has not been approved for that option.</inlineHelpText>
    <label>Selected Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Direct Monthly</fullName>
            </value>
            <value>
                <fullName>Direct Annual</fullName>
            </value>
            <value>
                <fullName>Upfront Payments</fullName>
            </value>
            <value>
                <fullName>Direct Semi-Annual</fullName>
            </value>
            <value>
                <fullName>Direct Quarterly</fullName>
            </value>
            <value>
                <fullName>Net-30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Send_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Send_Invoice__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked when a FT Invoice is sent to the customer (shown as quote object)</description>
    <inlineHelpText>Checked when a FT Invoice is sent to the customer (shown as quote object)</inlineHelpText>
    <label>Send Invoice</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TrialResolutionOppty__c.field-meta.xml
<CustomField>
    <fullName>TrialResolutionOppty__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reference to a Trial&apos;s Revenue or Return opportunity.</description>
    <label>Revenue Opportunity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Opportunity.Type</field>
            <operation>equals</operation>
            <value>Revenue Opportunity, Free Trial Return, Revenue Opportunity - Bill Only</value>
        </filterItems>
        <filterItems>
            <field>Opportunity.StageName</field>
            <operation>notEqual</operation>
            <value>Closed Won</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunities (Trial Resolution Oppty)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Trial.recordType-meta.xml
<RecordType>
    <fullName>Trial</fullName>
    <active>true</active>
    <businessProcess>Standard Opportunities</businessProcess>
    <label>Trial</label>
</RecordType>

force-app/main/default/classes/EmailFreeTrialOpportunityHandlerTest.cls
@isTest
public class EmailFreeTrialOpportunityHandlerTest {
    
    @testSetup
    static void setupTestData() {

        insert new Global_Automation_Settings__c(Skip_Trigger__c = true, Skip_Validation_Rule__c = true);

        // Create test Account
        Account testAccount = new Account(Name = 'Testers 1 Inc',
            BillingStreet = '26 Napier Street',
            BillingCity = 'London',
            BillingPostalCode  = '1030',
            BillingCountry = 'United Kingdom',
            Billing_Email__c  = 'qdasdas@gmail.com',
            Organization_Size__c = '100 - 499',
            Industry = 'Other');
        insert testAccount;

        // Create test Opportunity
        Opportunity testOpportunity = (Opportunity)TestFactory.createSObject(new Opportunity(AccountId = testAccount.Id,
            Type = 'Revenue Opportunity',
            Name = 'Opp Testers 1 Inc',
            StageName = 'Decision',
            Selected_Payment_Type__c = 'Direct Annual',
            Price_Book_Name__c = 'Standard',
            Send_Invoice__c = false));
        insert testOpportunity;

        // Create related Opportunity with StageName 'Closed Won' and Type 'Free Trial Opportunity'
        Opportunity relatedOpportunity = new Opportunity(
            Name = 'Related Opportunity',
            StageName = 'Closed Won',
            Type = 'Free Trial Opportunity',
            CloseDate = Date.today().addDays(30),
            AccountId = testAccount.Id,
            TrialResolutionOppty__c = testOpportunity.Id
        );
        insert relatedOpportunity;
    }

    @isTest
    static void testSendFreeTrialEmail() {
        // Retrieve the test Opportunity
        Opportunity testOpportunity = [SELECT Id FROM Opportunity WHERE Name = 'Opp Testers 1 Inc' LIMIT 1];

        // Call the method
        Test.startTest();
        EmailFreeTrialOpportunityHandler.sendFreeTrialEmail(new List<Id> { testOpportunity.Id });
        Test.stopTest();

        // Verify that the email was sent
        List<EmailMessage> sentEmails = [SELECT Id, Subject, HtmlBody FROM EmailMessage WHERE Subject LIKE '[Reminder] Return Needed for %'];
        System.assertEquals(1, sentEmails.size(), 'One email should have been sent.');
        System.assert(sentEmails[0].HtmlBody.contains('Testers 1 Inc'), 'Email body should contain the account name.');
        System.assert(sentEmails[0].HtmlBody.contains('Related Opportunity'), 'Email body should contain the related opportunity link.');
    }
}