force-app/main/default/objects/Account/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fleet</fullName>
                <default>true</default>
                <label>Fleet</label>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
            <value>
                <fullName>Machine Vision</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Experimental_Group__c.field-meta.xml
<CustomField>
    <fullName>Experimental_Group__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Experimental Group</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Experimental_Group_Routing__c.field-meta.xml
<CustomField>
    <fullName>Experimental_Group_Routing__c</fullName>
    <label>Experimental Group Routing</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Hashtag__c.field-meta.xml
<CustomField>
    <fullName>Hashtag__c</fullName>
    <description>Tag the account with the concept you prefer. Useful for mass transfering, as the actual tool does not allow the description field to be used for that.</description>
    <label>Account Hashtag</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Initiate_Round_Robin__c.field-meta.xml
<CustomField>
    <fullName>Initiate_Round_Robin__c</fullName>
    <defaultValue>false</defaultValue>
    <description>GTMS-11254</description>
    <label>Initiate Round Robin</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Is_Owner_Pool_User__c.field-meta.xml
<CustomField>
    <fullName>Is_Owner_Pool_User__c</fullName>
    <description>change LFBN__Is_Pool_User__c from to RR_Is_Pool_User__c for GTMS-13168</description>
    <formula>Owner.RR_Is_Pool_User__c</formula>
    <label>Is Owner Pool User</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Most_Recent_Source__c.field-meta.xml
<CustomField>
    <fullName>Most_Recent_Source__c</fullName>
    <description>Populated by the most recent lead that converts/merges into this account (or a contact under this account).</description>
    <label>Most Recent Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Owner_Role__c.field-meta.xml
<CustomField>
    <fullName>Owner_Role__c</fullName>
    <formula>Owner.UserRole.Name</formula>
    <label>Owner Role</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Program_Type__c.field-meta.xml
<CustomField>
    <fullName>Program_Type__c</fullName>
    <description>renamed for GTMS-13482</description>
    <label>Sales Program Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Subsidy</fullName>
            </value>
            <value>
                <fullName>Premium Discount</fullName>
            </value>
            <value>
                <fullName>Unpaid Referral</fullName>
            </value>
            <value>
                <fullName>Paid Referral</fullName>
            </value>
            <value>
                <fullName>Resale</fullName>
            </value>
            <value>
                <fullName>Whitelabel</fullName>
            </value>
            <value>
                <fullName>Teaming</fullName>
            </value>
            <value>
                <fullName>Safety Program</fullName>
            </value>
            <value>
                <fullName>Technology</fullName>
            </value>
            <value>
                <fullName>Teaming Partner</fullName>
                <isActive>false</isActive>
                <label>Teaming Partner</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Fleet.recordType-meta.xml
<RecordType>
    <fullName>Fleet</fullName>
    <active>true</active>
    <description>Fleet account</description>
    <label>Fleet</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Industrial.recordType-meta.xml
<RecordType>
    <fullName>Industrial</fullName>
    <active>true</active>
    <description>Industrial account</description>
    <label>Industrial</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <description>Account type for partners - resellers, referral partners, corporate partners</description>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/Business_Unit_User__mdt/Business_Unit_User__mdt.object-meta.xml
<CustomObject>
    <label>Business Unit User</label>
    <pluralLabel>Business Unit Users</pluralLabel>
</CustomObject>

force-app/main/default/objects/Lead/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <defaultValue>&quot;Fleet&quot;</defaultValue>
    <description>This field on the Lead object determines what record type a lead converts to (i.e. End_Customer or Industrial_Account).</description>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fleet</fullName>
                <default>true</default>
                <label>Fleet</label>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Machine Vision</fullName>
            </value>
            <value>
                <fullName>Connected Worker</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/CAE_Routing__c.field-meta.xml
<CustomField>
    <fullName>CAE_Routing__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Field utilized for channel ae routing deals with channel payment method of Deal Registration Margin</inlineHelpText>
    <label>CAE Routing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Campaign_to_Add__c.field-meta.xml
<CustomField>
    <fullName>Campaign_to_Add__c</fullName>
    <description>Maps to the converted contact, then adds campaign member to contact based on the value of this field.</description>
    <label>Campaign to Add</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Channel_Payment_Method_V2__c.field-meta.xml
<CustomField>
    <fullName>Channel_Payment_Method_V2__c</fullName>
    <formula>IF(
	OR(
	
		AND(
ISPICKVAL(Partner_Account_lr__r.Partner_Program_Tier__c, &quot;Dynamic Fleet (Sales)&quot;),
			OR(
				CONTAINS( Fleet_Segment__c ,&quot;Commercial&quot;),
				AND(
					CONTAINS( Fleet_Segment__c , &quot;Enterprise&quot;),
Partner_Account_lr__r.Qualifies_for_Resale_in_Fleet_Enterprise__c = false
				)
			)
		),
		
		OR(
ISPICKVAL(Partner_Account_lr__r.Partner_Program_Tier__c, &quot;Agile Fleet (Sales)&quot;),
ISPICKVAL(Partner_Account_lr__r.Partner_Program_Tier__c, &quot;Industrial Referral (Sales)&quot;),
ISPICKVAL(Partner_Account_lr__r.Partner_Program_Tier__c, &quot;Fleet Insurance Referral&quot;)
		)
	),

&quot;Rebate (% MSRP)&quot;,
	IF(
		OR(
			AND(
ISPICKVAL(Partner_Account_lr__r.Partner_Program_Tier__c, &quot;Dynamic Fleet (Sales)&quot;),
				CONTAINS( Fleet_Segment__c ,&quot;Mid-Market&quot;)
			),
			AND(
ISPICKVAL(Partner_Account_lr__r.Partner_Program_Tier__c, &quot;Dynamic Fleet (Sales)&quot;),
				CONTAINS( Fleet_Segment__c ,&quot;Enterprise&quot;),
Partner_Account_lr__r.Qualifies_for_Resale_in_Fleet_Enterprise__c = true
			),
ISPICKVAL(Partner_Account_lr__r.Partner_Program_Tier__c, &quot;Industrial Reseller (Sales)&quot;),
			ISPICKVAL(Product_Interest_Type__c, &apos;Onsite Security Cameras&apos;)
		),
	&quot;Deal Registration Margin&quot;,
		IF(
			OR(
				AND( 
ISPICKVAL(Partner_Account_lr__r.Partner_Program_Tier__c, &quot;Fleet Insight (Insurance)&quot;),
				NOT(ISPICKVAL(Product_Interest_Type__c, &apos;Onsite Security Cameras&apos;))
				),
				AND(
ISPICKVAL(Partner_Account_lr__r.Partner_Program_Tier__c, &quot;Fleet Control (Insurance)&quot;),
				NOT(ISPICKVAL(Product_Interest_Type__c, &apos;Onsite Security Cameras&apos;))
				)
			),
		&quot;End Customer Discount&quot;,
		&quot;None&quot;
		)
	)
)</formula>
    <label>Channel Payment Method</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Channel_Source__c.field-meta.xml
<CustomField>
    <fullName>Channel_Source__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Channel Source</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Description_for_Conversion__c.field-meta.xml
<CustomField>
    <fullName>Description_for_Conversion__c</fullName>
    <description>Description field that is updated via process builder when native Description is modified or Lead is new because native Description field won&apos;t transfer with conversion because why would it.</description>
    <label>Description for Conversion</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Experimental_Group_Routing__c.field-meta.xml
<CustomField>
    <fullName>Experimental_Group_Routing__c</fullName>
    <inlineHelpText>This field is needed to by pass existing limitations on our Salesforce org for TOFU</inlineHelpText>
    <label>Experimental Group Routing</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Hashtag__c.field-meta.xml
<CustomField>
    <fullName>Hashtag__c</fullName>
    <description>Tag the account with the concept you prefer. Useful for mass transfering, as the actual tool does not allow the description field to be used for that.</description>
    <label>Hashtag</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Most_Recent_Source__c.field-meta.xml
<CustomField>
    <fullName>Most_Recent_Source__c</fullName>
    <label>Most Recent Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Owner_Role__c.field-meta.xml
<CustomField>
    <fullName>Owner_Role__c</fullName>
    <formula>Owner:User.UserRole.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Owner Role</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Product_Interest_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Interest_Type__c</fullName>
    <label>Product Interest Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fleet/Industrial Deal</fullName>
            </value>
            <value>
                <fullName>Onsite Security Cameras</fullName>
            </value>
            <value>
                <fullName>Both</fullName>
            </value>
            <value>
                <fullName>Connected Sites</fullName>
                <isActive>false</isActive>
                <label>Connected Sites</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Program_Type__c.field-meta.xml
<CustomField>
    <fullName>Program_Type__c</fullName>
    <label>Sales Program Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Subsidy</fullName>
            </value>
            <value>
                <fullName>Premium Discount</fullName>
            </value>
            <value>
                <fullName>Unpaid Referral</fullName>
            </value>
            <value>
                <fullName>Paid Referral</fullName>
            </value>
            <value>
                <fullName>Resale</fullName>
            </value>
            <value>
                <fullName>Whitelabel</fullName>
            </value>
            <value>
                <fullName>Teaming</fullName>
            </value>
            <value>
                <fullName>Safety Program</fullName>
                <isActive>false</isActive>
                <label>Safety Program</label>
            </value>
            <value>
                <fullName>Teaming Partner</fullName>
                <isActive>false</isActive>
                <label>Teaming Partner</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/RR_Duplicate_Account__c.field-meta.xml
<CustomField>
    <fullName>RR_Duplicate_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Matched Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads (RR Duplicate Account)</relationshipLabel>
    <relationshipName>Leads2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fleet</fullName>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
            <value>
                <fullName>Connected Worker</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Experimental_Group__c.field-meta.xml
<CustomField>
    <fullName>Experimental_Group__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used by Growth to indicate that this record is part of an experimental group.</description>
    <label>Experimental Group</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/LeadHelper.cls
public class LeadHelper {
    static Map<Id, Account> accountUpdates = new Map<Id, Account>();
    static Map<Id, Account> staticAccountsMap = new Map<Id, Account>();
    static Boolean loadedStaticAccounts = false;

    public static Id channelrt = Schema.SObjectType.Lead.getRecordTypeInfosByName().get('Channel Registration').getRecordTypeId();
    public static Id industrialAcctrt = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Industrial').getRecordTypeId();

    public static void loadStaticAccountsMap(Set<Id> accountIds) {
        if(!loadedStaticAccounts && accountIds.size() > 0) {
            staticAccountsMap = new Map<Id, Account>([  SELECT  Id,
                                                                Industry,
                                                                Owner.Name, 
                                                                Most_Recent_Source__c,
                                                                Owner_Role__c, 
                                                                Initiate_Round_Robin__c,
                                                                Is_Owner_Pool_User__c, 
                                                                Hashtag__c 
                                                        FROM Account 
                                                        WHERE Id IN :accountIds]);
            loadedStaticAccounts = true;
        }
    }

    public static void beforeInsertOnly(List<Lead> newLeadList) {
        Set<Id> leadOwnerIdSet = new Set<Id>();
        for(Lead l : newLeadList) {
            leadOwnerIdSet.add(l.OwnerId);
        }
        // Query owner roles
        Map<Id, User> ownerMap = new Map<Id, User>([SELECT Id, UserRole.Name, UserRole.PortalType FROM User WHERE Id IN: leadOwnerIdSet]);
        Map<String, Id> poolMap = new Map<String, Id>();
        for(Business_Unit_User__mdt userMapping : [SELECT Id, MasterLabel, User_Id__c FROM Business_Unit_User__mdt]) {
            poolMap.put(userMapping.MasterLabel, userMapping.User_Id__c);
        }

        //Deprecated Consolidated Lead Processes Builder Node: (Business Unit) - rsaavedra 
        for(Lead l : newLeadList) {
            if(ownerMap.get(l.OwnerId).UserRole.Name == 'Management' || (Test.isRunningTest() && ownerMap.get(l.OwnerId).UserRole.PortalType != 'Partner')) {
                if(poolMap.containsKey(l.Business_Unit__c)){
                    l.OwnerId = poolMap.get(l.Business_Unit__c);
                }
            }

            if(l.RecordTypeId == channelrt){
                l.Channel_Source__c = true;
            }

            if(l.Experimental_Group__c){
                l.Experimental_Group_Routing__c = 'True';
            }
            else{
                l.Experimental_Group_Routing__c = 'False';
            }
			//GTMS-3838 replacing BU value as Fleet from Connected Worker
            if(l.Product_Interest_Type__c == 'Onsite Security Cameras'){
                l.Business_Unit__c = 'Fleet';
                l.Campaign_to_Add__c = System.Label.SITES_Campaign_Id;
            }
        }
    }
    //Deprecated Consolidated Lead Processes Builder Node: (Description Changes or IsNew) - rsaavedra
    public static void beforeInsertandUpdate(Map<Id, Lead> oldLeadMap, List<Lead> newLeadList){

        Id ChannelReg_RecordTypeId = Schema.SObjectType.Lead.getRecordTypeInfosByName().get('Channel Registration').getRecordTypeId();

 
        for(Lead ll :newLeadList){

            if(ll.Business_Unit__c == NULL){
                ll.Business_Unit__c = 'Fleet';
            }

            if(ll.Channel_Payment_Method_V2__c == 'Deal Registration Margin'){
                ll.CAE_Routing__c = true;
            }
            
            if(ll.Description != NULL){
                ll.Description_for_Conversion__c = ll.Description;
            }
            
            List<String> programTypeList = new List<String>();
            if(ll.Program_Type__c != NULL && ll.RecordTypeId == ChannelReg_RecordTypeId){
                programTypeList.addAll(ll.Program_Type__c.split(';'));
                if(programTypeList.size() > 1){
                    ll.addError('You can select only one program type on a deal registration');
                }
            }
        }
    }


    //method is assuming that we remain on the Account based model and updates the Most Recent source on both update & insert
    public static void leadToAccount(Map<Id, Lead> oldLeadMap, List<Lead> newLeadList, Boolean isUpdate){

        Set<Id> acctIds = new Set<Id>(); 
        Map<Id, Account> accts = new Map<Id, Account>();

        for(Lead l: newLeadList){
            if(l.RR_Duplicate_Account__c != NULL){
                acctIds.add(l.RR_Duplicate_Account__c);
            }
        }

        loadStaticAccountsMap(acctIds);

        for(Lead lead: newLeadList){
            if(lead.RR_Duplicate_Account__c != null && (isUpdate && lead.Channel_Source__c || !isUpdate && !lead.Channel_Source__c)){
                if(staticAccountsMap.containsKey(lead.RR_Duplicate_Account__c)){
                    Account account = accountUpdates.get(lead.RR_Duplicate_Account__c);

                    if(accountUpdates.containsKey(lead.RR_Duplicate_Account__c)){
                        account.Most_Recent_Source__c = lead.LeadSource;
                        account.Experimental_Group_Routing__c = lead.Experimental_Group_Routing__c;
                        accountUpdates.put(account.Id, account);
                    } 
                    else{
                        accountUpdates.put(lead.RR_Duplicate_Account__c, new Account(Id = lead.RR_Duplicate_Account__c,
                                                                                        Most_Recent_Source__c = lead.LeadSource,
                                                                                        Experimental_Group_Routing__c = lead.Experimental_Group_Routing__c));
                    }
                }
            }
        }
        // Update called in the trigger handler.
    }

    //Deprecated Consolidated Lead Processes Builder Node: (Matched Account Hashtag) - rsaavedra 
    public static void acctHashtag(Map<Id, Lead> oldLeadMap, List<Lead> newLeadList){
        Set<Id> acctIds = new Set<Id>(); 

        for(Lead l: newLeadList){
            if(l.RR_Duplicate_Account__c != NULL){
                acctIds.add(l.RR_Duplicate_Account__c);
            }
        }

        loadStaticAccountsMap(acctIds);    
        if(acctIds.size() > 0 ){
            for(Lead ll :newLeadList){

                Lead oldLead = new Lead();

                //evaluate if the duplicate has changed
                if (oldLeadMap != NULL){
                    oldLead = oldLeadMap.get(ll.Id);
                }

                //protect from null pointer error if matched account field hasn't been populated
                if(ll.RR_Duplicate_Account__c != NULL){
                    if(ll.RR_Duplicate_Account__c != oldLead.RR_Duplicate_Account__c){
                        if(staticAccountsMap.containsKey(ll.RR_Duplicate_Account__c)){
                            Account a = staticAccountsMap.get(ll.RR_Duplicate_Account__c);
                            if(ll.Hashtag__c != NULL){
                            //protect from NULL hashtag on the matched Account
                                if(a.Hashtag__c != NULL){
                                    if(!a.Hashtag__c.contains(ll.Hashtag__c)){
                                        //protect from duplicate ids in list
                                        if(accountUpdates.containsKey(ll.RR_Duplicate_Account__c)){
                                            accountUpdates.get(ll.RR_Duplicate_Account__c).Hashtag__c = ll.Hashtag__c+' '+a.Hashtag__c;
                                        } 
                                        else{
                                            accountUpdates.put(a.Id, new Account(Id = a.Id, Hashtag__c = ll.Hashtag__c+' '+a.Hashtag__c));
                                        }
                                    }
                                }
                                else{
                                    //protect from duplicate ids in list
                                    if(accountUpdates.containsKey(ll.RR_Duplicate_Account__c)){
                                        accountUpdates.get(ll.RR_Duplicate_Account__c).Hashtag__c = ll.Hashtag__c;
                                    } 
                                    else{
                                        accountUpdates.put(a.Id, new Account(Id = a.Id, Hashtag__c = ll.Hashtag__c));
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }

        // Update called in the trigger handler.
    }

    public static void updateAccounts() {
        if (accountUpdates.size() > 0) {
            //update accountUpdates.values();
            DMLWrapper.doUpdate(accountUpdates.values());
        }
    }
}