force-app/main/default/objects/Account/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fleet</fullName>
                <default>true</default>
                <label>Fleet</label>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
            <value>
                <fullName>Machine Vision</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Organization_Size__c.field-meta.xml
<CustomField>
    <fullName>Organization_Size__c</fullName>
    <description>Number of employees or students</description>
    <inlineHelpText>Number of employees or students</inlineHelpText>
    <label>Organization Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 - 99</fullName>
            </value>
            <value>
                <fullName>100 - 499</fullName>
            </value>
            <value>
                <fullName>500 - 999</fullName>
            </value>
            <value>
                <fullName>1000 - 4999</fullName>
            </value>
            <value>
                <fullName>5000+</fullName>
            </value>
            <value>
                <fullName>0</fullName>
                <isActive>false</isActive>
                <label>0</label>
            </value>
            <value>
                <fullName>1-99</fullName>
                <isActive>false</isActive>
                <label>1-99</label>
            </value>
            <value>
                <fullName>1/1/1999 12:00:00 AM</fullName>
                <isActive>false</isActive>
                <label>1/1/1999 12:00:00 AM</label>
            </value>
            <value>
                <fullName>10</fullName>
                <isActive>false</isActive>
                <label>10</label>
            </value>
            <value>
                <fullName>100 - 999</fullName>
                <isActive>false</isActive>
                <label>100 - 999</label>
            </value>
            <value>
                <fullName>100-499</fullName>
                <isActive>false</isActive>
                <label>100-499</label>
            </value>
            <value>
                <fullName>1000+</fullName>
                <isActive>false</isActive>
                <label>1000+</label>
            </value>
            <value>
                <fullName>1000-4999</fullName>
                <isActive>false</isActive>
                <label>1000-4999</label>
            </value>
            <value>
                <fullName>10000+</fullName>
                <isActive>false</isActive>
                <label>10000+</label>
            </value>
            <value>
                <fullName>11</fullName>
                <isActive>false</isActive>
                <label>11</label>
            </value>
            <value>
                <fullName>13</fullName>
                <isActive>false</isActive>
                <label>13</label>
            </value>
            <value>
                <fullName>200</fullName>
                <isActive>false</isActive>
                <label>200</label>
            </value>
            <value>
                <fullName>201-500</fullName>
                <isActive>false</isActive>
                <label>201-500</label>
            </value>
            <value>
                <fullName>21</fullName>
                <isActive>false</isActive>
                <label>21</label>
            </value>
            <value>
                <fullName>22</fullName>
                <isActive>false</isActive>
                <label>22</label>
            </value>
            <value>
                <fullName>29</fullName>
                <isActive>false</isActive>
                <label>29</label>
            </value>
            <value>
                <fullName>34</fullName>
                <isActive>false</isActive>
                <label>34</label>
            </value>
            <value>
                <fullName>36161</fullName>
                <isActive>false</isActive>
                <label>36161</label>
            </value>
            <value>
                <fullName>42</fullName>
                <isActive>false</isActive>
                <label>42</label>
            </value>
            <value>
                <fullName>495 - 1000</fullName>
                <isActive>false</isActive>
                <label>495 - 1000</label>
            </value>
            <value>
                <fullName>496 - 1000</fullName>
                <isActive>false</isActive>
                <label>496 - 1000</label>
            </value>
            <value>
                <fullName>497 - 1000</fullName>
                <isActive>false</isActive>
                <label>497 - 1000</label>
            </value>
            <value>
                <fullName>498 - 1000</fullName>
                <isActive>false</isActive>
                <label>498 - 1000</label>
            </value>
            <value>
                <fullName>499 - 1000</fullName>
                <isActive>false</isActive>
                <label>499 - 1000</label>
            </value>
            <value>
                <fullName>500 - 1000</fullName>
                <isActive>false</isActive>
                <label>500 - 1000</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Fleet.recordType-meta.xml
<RecordType>
    <fullName>Fleet</fullName>
    <active>true</active>
    <description>Fleet account</description>
    <label>Fleet</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <description>Account type for partners - resellers, referral partners, corporate partners</description>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Organization_Size__c.field-meta.xml
<CustomField>
    <fullName>Organization_Size__c</fullName>
    <formula>TEXT(Account.Organization_Size__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Please edit on the Account page.</inlineHelpText>
    <label>Organization Size</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Fleet.recordType-meta.xml
<RecordType>
    <fullName>Fleet</fullName>
    <active>true</active>
    <description>Fleet contact</description>
    <label>Fleet</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <description>Partner contacts</description>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/Lead/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <defaultValue>&quot;Fleet&quot;</defaultValue>
    <description>This field on the Lead object determines what record type a lead converts to (i.e. End_Customer or Industrial_Account).</description>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fleet</fullName>
                <default>true</default>
                <label>Fleet</label>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Machine Vision</fullName>
            </value>
            <value>
                <fullName>Connected Worker</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Organization_Size__c.field-meta.xml
<CustomField>
    <fullName>Organization_Size__c</fullName>
    <description>Number of employees or students</description>
    <inlineHelpText>Number of employees or students</inlineHelpText>
    <label>Organization Size</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1 - 99</fullName>
                <default>true</default>
                <label>1 - 99</label>
            </value>
            <value>
                <fullName>100 - 499</fullName>
            </value>
            <value>
                <fullName>500 - 999</fullName>
            </value>
            <value>
                <fullName>1000 - 4999</fullName>
            </value>
            <value>
                <fullName>5000+</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SubmitDealRegistrationEvent__e/SubmitDealRegistrationEvent__e.object-meta.xml
<CustomObject>
    <label>SubmitDealRegistrationEvent</label>
    <pluralLabel>SubmitDealRegistrationEvents</pluralLabel>
</CustomObject>

force-app/main/default/objects/SubmitDealRegistrationEvent__e/fields/Lead_Record_Id_t__c.field-meta.xml
<CustomField>
    <fullName>Lead_Record_Id_t__c</fullName>
    <label>Lead Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fleet</fullName>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
            <value>
                <fullName>Connected Worker</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SubmitDealRegistrationTest.cls
@isTest
private class SubmitDealRegistrationTest {
    @TestSetup
    static void makeData(){
        //TO DO - move to a test data factory class
        //Create Partner Account
        String orgId = UserInfo.getOrganizationId();
        RecordType accountPartnerRT = [Select Id from RecordType Where SObjectType = 'Account' and Name = 'Partner' LIMIT 1]; 
        Account partnerAccount = new Account(Name='Partner Account', Organization_Size__c='1 - 99', BillingCountry='Belgium', BillingCountryCode = 'BE', RecordTypeId = accountPartnerRT.Id);
        insert partnerAccount;
        
        //Emable as Partner
        partnerAccount.IsPartner = true;
        update partnerAccount;

        //Create Partner Contact
        RecordType contactPartnerRT = [Select Id from RecordType Where SObjectType = 'Contact' and Name = 'Partner' LIMIT 1]; 
        Contact partnerContact = new Contact(FirstName = 'Partner', LastName = 'Contact', AccountId = partnerAccount.Id, Email = 'partner@test.com'+orgId);
        insert partnerContact;

        //Create Partner User
        Profile partnerProfile = [SELECT Id FROM Profile WHERE Name = 'Samsara Partner Community Login License User'];
        String dateString = String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
        Integer randomInt = Integer.valueOf(math.rint(math.random()*1000000));
        String uniqueName = orgId + dateString + randomInt;
        User partnerUser = new User(lastName = partnerContact.LastName,
                        email = partnerContact.Email,
                        Username = partnerContact.Email,
                        ContactId = partnerContact.Id,
                        EmailEncodingKey = 'ISO-8859-1',
                        Alias = uniqueName.substring(10, 15),
                        TimeZoneSidKey = 'America/Los_Angeles',
                        LocaleSidKey = 'en_US',
                        LanguageLocaleKey = 'en_US',
                        ProfileId = partnerProfile.Id,
                        EmployeeNumber='123');
        insert partnerUser;
    }

    @isTest 
    static void testDealSubmission() {
        String orgId = UserInfo.getOrganizationId();
        String partnerUsername = 'partner@test.com'+orgId;
        
        //Before state - Assert that the running user(PSM) has no lead records visible to them
        List<Lead> myLeadsAtStart = (List<Lead>)Database.Query('Select Id from Lead');
        System.assert(myLeadsAtStart.size() == 0);
        
        //Get partner user
        User partnerUser = [Select Id, Account.OwnerId from User where username =: partnerUsername];
        System.runAs(partnerUser) {
            
            //Insert a Deal Reg Lead record to simulate the Partner community action
            RecordType leadDealRegRT = [Select Id from RecordType Where SObjectType = 'Lead' and Name = 'Channel Registration' LIMIT 1]; 
            Lead dealRegLead = new Lead (LastName = 'Test Client', Email = 'dealreglead@test.com'+orgId, RecordTypeId = leadDealRegRT.id, phone = '+1234567890', Company = 'Test company', Business_unit__c = 'Fleet', LeadSource = 'Deal Reg Form', Country='United States', State='Texas', Status = 'New');
            insert dealRegLead;

            Test.startTest();
            Test.setMock(HttpCalloutMock.class, new SubmitLeadToNotreDameTest.NotreDameHTTPServiceTestMocks());
            //The partner user should be the owner of the Lead record after creation.
            Lead queriedLead = [Select Id, OwnerId from Lead where Id =: dealRegLead.Id];
            System.assert(queriedLead.OwnerId == partnerUser.Id);
			
            //The partner user submits the Deal Reg Lead for approval.
            SubmitDealRegistrationEvent__e event = new SubmitDealRegistrationEvent__e();
            event.Lead_Record_Id_t__c = dealRegLead.Id;
            EventBus.publish(event);
     
            Test.stopTest();
            
            //The partner user should no longer have access to the lead record. Owner changed to PSM user
            List<Lead> partnerLeadsAtEnd = (List<Lead>)Database.Query('Select Id from Lead where Id =\''+dealRegLead.Id+'\'');
        	//System.assert(partnerLeadsAtEnd.size() == 0);
        }
        
        //After state - Assert that the running user(PSM) has the Deal Reg lead records visible to them
        List<Lead> myLeadsAtEnd = (List<Lead>)Database.Query('Select Id from Lead');
        //System.assert(myLeadsAtEnd.size() == 1);
    }

    @IsTest
    static void shouldCallSubmitDealRegistrationToNotreDame(){
        String orgId = UserInfo.getOrganizationId();
        String partnerUsername = 'partner@test.com'+orgId;

        //Before state - Assert that the running user(PSM) has no lead records visible to them
        List<Lead> myLeadsAtStart = (List<Lead>)Database.Query('Select Id from Lead');
        System.assert(myLeadsAtStart.size() == 0);

        //Get partner user
        User partnerUser = [Select Id, Account.OwnerId from User where username =: partnerUsername];
        Lead dealRegLead = new Lead();
        System.runAs(partnerUser) {

            //Insert a Deal Reg Lead record to simulate the Partner community action
            RecordType leadDealRegRT = [Select Id from RecordType Where SObjectType = 'Lead' and Name = 'Channel Registration' LIMIT 1];
            dealRegLead = new Lead (LastName = 'Test Client', Email = 'dealreglead@test.com'+orgId, RecordTypeId = leadDealRegRT.id, phone = '+1234567890', Company = 'Test company', Business_unit__c = 'Fleet', LeadSource = 'Deal Reg Form', Country='United States', State='Texas', Status = 'New');
            insert dealRegLead;
        }

        Test.startTest();
        //The partner user should be the owner of the Lead record after creation.
        Lead queriedLead = [Select Id, OwnerId from Lead where Id =: dealRegLead.Id];
        SubmitDealRegToNotreDame.Payload payload = new SubmitDealRegToNotreDame.Payload();
        payload.leadId = queriedLead.Id;
        SubmitDealRegToNotreDame.submitLeadForConversion(new List<SubmitDealRegToNotreDame.Payload>{
                payload
        });
    }
    
    
}