force-app/main/default/objects/Account/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fleet</fullName>
                <default>true</default>
                <label>Fleet</label>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
            <value>
                <fullName>Machine Vision</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/DUNS_Number__c.field-meta.xml
<CustomField>
    <fullName>DUNS_Number__c</fullName>
    <description>D&amp;B Number</description>
    <label>DUNS Number</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Organization_Size__c.field-meta.xml
<CustomField>
    <fullName>Organization_Size__c</fullName>
    <description>Number of employees or students</description>
    <inlineHelpText>Number of employees or students</inlineHelpText>
    <label>Organization Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 - 99</fullName>
            </value>
            <value>
                <fullName>100 - 499</fullName>
            </value>
            <value>
                <fullName>500 - 999</fullName>
            </value>
            <value>
                <fullName>1000 - 4999</fullName>
            </value>
            <value>
                <fullName>5000+</fullName>
            </value>
            <value>
                <fullName>0</fullName>
                <isActive>false</isActive>
                <label>0</label>
            </value>
            <value>
                <fullName>1-99</fullName>
                <isActive>false</isActive>
                <label>1-99</label>
            </value>
            <value>
                <fullName>1/1/1999 12:00:00 AM</fullName>
                <isActive>false</isActive>
                <label>1/1/1999 12:00:00 AM</label>
            </value>
            <value>
                <fullName>10</fullName>
                <isActive>false</isActive>
                <label>10</label>
            </value>
            <value>
                <fullName>100 - 999</fullName>
                <isActive>false</isActive>
                <label>100 - 999</label>
            </value>
            <value>
                <fullName>100-499</fullName>
                <isActive>false</isActive>
                <label>100-499</label>
            </value>
            <value>
                <fullName>1000+</fullName>
                <isActive>false</isActive>
                <label>1000+</label>
            </value>
            <value>
                <fullName>1000-4999</fullName>
                <isActive>false</isActive>
                <label>1000-4999</label>
            </value>
            <value>
                <fullName>10000+</fullName>
                <isActive>false</isActive>
                <label>10000+</label>
            </value>
            <value>
                <fullName>11</fullName>
                <isActive>false</isActive>
                <label>11</label>
            </value>
            <value>
                <fullName>13</fullName>
                <isActive>false</isActive>
                <label>13</label>
            </value>
            <value>
                <fullName>200</fullName>
                <isActive>false</isActive>
                <label>200</label>
            </value>
            <value>
                <fullName>201-500</fullName>
                <isActive>false</isActive>
                <label>201-500</label>
            </value>
            <value>
                <fullName>21</fullName>
                <isActive>false</isActive>
                <label>21</label>
            </value>
            <value>
                <fullName>22</fullName>
                <isActive>false</isActive>
                <label>22</label>
            </value>
            <value>
                <fullName>29</fullName>
                <isActive>false</isActive>
                <label>29</label>
            </value>
            <value>
                <fullName>34</fullName>
                <isActive>false</isActive>
                <label>34</label>
            </value>
            <value>
                <fullName>36161</fullName>
                <isActive>false</isActive>
                <label>36161</label>
            </value>
            <value>
                <fullName>42</fullName>
                <isActive>false</isActive>
                <label>42</label>
            </value>
            <value>
                <fullName>495 - 1000</fullName>
                <isActive>false</isActive>
                <label>495 - 1000</label>
            </value>
            <value>
                <fullName>496 - 1000</fullName>
                <isActive>false</isActive>
                <label>496 - 1000</label>
            </value>
            <value>
                <fullName>497 - 1000</fullName>
                <isActive>false</isActive>
                <label>497 - 1000</label>
            </value>
            <value>
                <fullName>498 - 1000</fullName>
                <isActive>false</isActive>
                <label>498 - 1000</label>
            </value>
            <value>
                <fullName>499 - 1000</fullName>
                <isActive>false</isActive>
                <label>499 - 1000</label>
            </value>
            <value>
                <fullName>500 - 1000</fullName>
                <isActive>false</isActive>
                <label>500 - 1000</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;New&quot;</defaultValue>
    <description>This is a roll up from the status of the contacts of the account. 
Eg. If there is any disqualified contact -&gt; Disqualified and so on.</description>
    <label>Account Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Fleet.recordType-meta.xml
<RecordType>
    <fullName>Fleet</fullName>
    <active>true</active>
    <description>Fleet account</description>
    <label>Fleet</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Organization_Size__c.field-meta.xml
<CustomField>
    <fullName>Organization_Size__c</fullName>
    <formula>TEXT(Account.Organization_Size__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Please edit on the Account page.</inlineHelpText>
    <label>Organization Size</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Contact Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Attempting</fullName>
            </value>
            <value>
                <fullName>Demo Scheduled</fullName>
            </value>
            <value>
                <fullName>Demo No Show</fullName>
            </value>
            <value>
                <fullName>Demo Completed - Not Qualified</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Retouch - Did Not Connect</fullName>
            </value>
            <value>
                <fullName>Retouch - Confirmed No Opportunity</fullName>
                <label>Connected-Disqualified</label>
            </value>
            <value>
                <fullName>Send Small Fleet Link</fullName>
            </value>
            <value>
                <fullName>Small Fleet Link Sent</fullName>
            </value>
            <value>
                <fullName>Inactive - See Parent Account</fullName>
            </value>
            <value>
                <fullName>Small Fleet Link Failed - Invalid Email</fullName>
            </value>
            <value>
                <fullName>Small Fleet Link Pending - Manual Review</fullName>
            </value>
            <value>
                <fullName>Faulty Lead</fullName>
            </value>
            <value>
                <fullName>Do Not Contact - Open Conversation</fullName>
            </value>
            <value>
                <fullName>Contact Established</fullName>
                <isActive>false</isActive>
                <label>Contact Established</label>
            </value>
            <value>
                <fullName>Create Webstore Opportunity</fullName>
                <isActive>false</isActive>
                <label>Create Webstore Opportunity</label>
            </value>
            <value>
                <fullName>Delete Account</fullName>
                <isActive>false</isActive>
                <label>Delete Account</label>
            </value>
            <value>
                <fullName>Delete Contact Only</fullName>
                <isActive>false</isActive>
                <label>Delete Contact Only</label>
            </value>
            <value>
                <fullName>GDPR Delete</fullName>
                <isActive>false</isActive>
                <label>GDPR Delete</label>
            </value>
            <value>
                <fullName>Inactive - No Longer There</fullName>
                <isActive>false</isActive>
                <label>Inactive - No Longer There</label>
            </value>
            <value>
                <fullName>Multiple Campaign Interactions</fullName>
                <isActive>false</isActive>
                <label>Multiple Campaign Interactions</label>
            </value>
            <value>
                <fullName>No Authority</fullName>
                <isActive>false</isActive>
                <label>No Authority</label>
            </value>
            <value>
                <fullName>Opt out - Do not contact</fullName>
                <isActive>false</isActive>
                <label>Opt out - Do not contact</label>
            </value>
            <value>
                <fullName>Webstore Opportunity Created</fullName>
                <isActive>false</isActive>
                <label>Webstore Opportunity Created</label>
            </value>
            <value>
                <fullName>Webstore Opportunity Creation In Progress</fullName>
                <isActive>false</isActive>
                <label>Webstore Opportunity Creation In Progress</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Fleet.recordType-meta.xml
<RecordType>
    <fullName>Fleet</fullName>
    <active>true</active>
    <description>Fleet contact</description>
    <label>Fleet</label>
</RecordType>

force-app/main/default/objects/Finance_Partner_Quote__c/Finance_Partner_Quote__c.object-meta.xml
<CustomObject>
    <label>Finance Partner Quote</label>
    <nameField>
        <displayFormat>FPQ-{00000}</displayFormat>
        <label>FPQ Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Finance Partner Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Finance_Partner_Quote__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Finance Partner Quotes</relationshipLabel>
    <relationshipName>Finance_Partner_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Finance_Partner_Quote__c/fields/DUNS_Number__c.field-meta.xml
<CustomField>
    <fullName>DUNS_Number__c</fullName>
    <description>GTMS-9965 3PF Automation</description>
    <label>DUNS Number</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Finance_Partner_Settings__c/Finance_Partner_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Finance Partner Settings</label>
</CustomObject>

force-app/main/default/objects/Finance_Partner_Settings__c/fields/Names__c.field-meta.xml
<CustomField>
    <fullName>Names__c</fullName>
    <label>Names</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Internal_Finance_Approval_Request__c/Internal_Finance_Approval_Request__c.object-meta.xml
<CustomObject>
    <label>Internal Finance Request</label>
    <nameField>
        <displayFormat>IF-{00000}</displayFormat>
        <label>Internal Financing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Internal Finance Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Internal_Finance_Approval_Request__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Internal Finance Requests</relationshipLabel>
    <relationshipName>Internal_Finance_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Finance_Partner_Notes__c.field-meta.xml
<CustomField>
    <fullName>Finance_Partner_Notes__c</fullName>
    <label>Finance Partner Notes</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/License_Term__c.field-meta.xml
<CustomField>
    <fullName>License_Term__c</fullName>
    <defaultValue>36</defaultValue>
    <description>The license term of the opportunity.</description>
    <label>License Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Related_Contact__c.field-meta.xml
<CustomField>
    <fullName>Related_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Related Contact)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Subsidize_Financing__c.field-meta.xml
<CustomField>
    <fullName>Subsidize_Financing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Subsidize Financing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fleet</fullName>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
            <value>
                <fullName>Connected Worker</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FinancePartnerQuoteControllerTest.cls
@isTest
private class FinancePartnerQuoteControllerTest{
  
  @TestSetup
  static void testDataSetup(){
     User Owner = [Select Id FROM User WHERE Name LIKE 'Ron Saavedra'];

    Finance_Partner_Settings__c partner_settings = new Finance_Partner_Settings__c();
    partner_settings.Emails__c = 'ron.saavedra@samsara.com';
    partner_settings.Names__c = 'ron.saavedra@samsara.com';
    insert partner_settings;

    Account a = new Account();
    a.Name = 'TestFirst Account';
    a.Business_Unit__c = 'Fleet';
    a.BillingStreet = '123 Testing St';
    a.BillingCity = 'San Francisco';
    a.BillingCountryCode = 'US';
    a.BillingStateCode = 'CA';
    a.BillingPostalCode = '94109';
    a.DUNS_Number__c = '12345';
    a.Website = 'www.samsara.com';
    a.Organization_Size__c = '1 - 99';
    a.OwnerId = Owner.Id;
    insert a;

    Contact c = new Contact();
    c.FirstName = 'TestFirst';
    c.AccountId = a.Id;
    c.LastName = 'Contact';
    c.Email = 'saavedra.test@email.com';
    c.Status__c = 'New';
    c.MailingCountryCode = 'US';
    c.MailingStateCode = 'CA';
    c.OwnerId = Owner.Id;
    insert c;
      
    Internal_Finance_Approval_Request__c internalFinance=new Internal_Finance_Approval_Request__c();
    internalFinance.Account__c=a.id;
    insert internalFinance;

    Opportunity o = new Opportunity();
    o.StageName = 'Qualified';
    o.Name = 'Test Opp 1';
    o.AccountId = a.Id;
    o.Related_Contact__c = c.Id;
    o.License_Term__c = 36;
    o.Amount = 15000;
    o.Finance_Partner_Notes__c = 'Test';
    o.Subsidize_Financing__c = True;
    o.CloseDate =  system.today()+5;
    o.Can_Create__c = true;
    o.License_End_Date_Notes__c = 'TESTING 456';
    insert o;
      
    list<Finance_Partner_Quote__c>FinanceQuotelist=new list<Finance_Partner_Quote__c>();
    Finance_Partner_Quote__c FinanceQuote=new Finance_Partner_Quote__c();
    FinanceQuote.Financing_Decision__c='Pending';
    FinanceQuote.Preferred_Offer__c=false;
    FinanceQuote.Opportunity__c=o.id;
    FinanceQuote.Account__c=a.id;
    FinanceQuotelist.add(FinanceQuote);
    
    Finance_Partner_Quote__c FinanceQuoteNew=new Finance_Partner_Quote__c();
    FinanceQuoteNew.Financing_Decision__c='Pending';
    FinanceQuoteNew.Preferred_Offer__c=true;
    FinanceQuoteNew.Opportunity__c=o.id;
    FinanceQuoteNew.Account__c=a.id;
     FinanceQuotelist.add(FinanceQuoteNew);
    insert FinanceQuotelist;
  }
   
    @isTest
    static void getQuoteDetailTest(){
     Finance_Partner_Quote__c FinanceQuote=[select id,Financing_Decision__c from Finance_Partner_Quote__c where Preferred_Offer__c=false];
    Test.startTest();
        try{
             FinancePartnerQuoteController.getQuoteDetail (FinanceQuote.id);
       FinancePartnerQuoteController.approvalSubmit (FinanceQuote.id);
        FinancePartnerQuoteController.sendPOUploadEmail (FinanceQuote.id);
        }catch(exception ex){
            System.assert(ex !=null,true);  
        }
     
    Test.stopTest();

    
  }
  }