force-app/main/default/objects/Account/fields/CSM_First_30d_Stage__c.field-meta.xml
<CustomField>
    <fullName>CSM_First_30d_Stage__c</fullName>
    <label>CSM First 30d Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Intro</fullName>
            </value>
            <value>
                <fullName>Pending Delivery</fullName>
            </value>
            <value>
                <fullName>Attempting Training</fullName>
            </value>
            <value>
                <fullName>Scheduled Training</fullName>
            </value>
            <value>
                <fullName>Health Check</fullName>
            </value>
            <value>
                <fullName>Scheduled Additional Training</fullName>
            </value>
            <value>
                <fullName>Additional followup needed</fullName>
            </value>
            <value>
                <fullName>Initial onboarding completed</fullName>
            </value>
            <value>
                <fullName>Cannot_connect</fullName>
                <label>Cannot connect</label>
            </value>
            <value>
                <fullName>----Mid Market Fields----</fullName>
            </value>
            <value>
                <fullName>MM Internal Planning</fullName>
            </value>
            <value>
                <fullName>MM Attempting Kickoff</fullName>
            </value>
            <value>
                <fullName>MM Scheduled Kickoff</fullName>
            </value>
            <value>
                <fullName>Attempting_1st_session</fullName>
                <label>Attempting 1st session</label>
            </value>
            <value>
                <fullName>Scheduled_1st_session</fullName>
                <label>Scheduled 1st session</label>
            </value>
            <value>
                <fullName>Attempting_2nd_session</fullName>
                <label>Attempting 2nd session</label>
            </value>
            <value>
                <fullName>Scheduled_2nd_session</fullName>
                <label>Scheduled 2nd session</label>
            </value>
            <value>
                <fullName>Attempting 3rd session</fullName>
            </value>
            <value>
                <fullName>Scheduled 3rd session</fullName>
            </value>
            <value>
                <fullName>MM Attempting Additional Training</fullName>
            </value>
            <value>
                <fullName>MM Scheduled Additional Training</fullName>
            </value>
            <value>
                <fullName>MM Trainings Complete - Continuing Regular Check-Ins</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>Completed_1st_session</fullName>
                <isActive>false</isActive>
                <label>Completed 1st session</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Async_Request__c/Async_Request__c.object-meta.xml
<CustomObject>
    <description>Use to queue up an Asynchronous Request for processing</description>
    <label>Async Request</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Async Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Async Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Async_Request__c/fields/Options__c.field-meta.xml
<CustomField>
    <fullName>Options__c</fullName>
    <description>Additional Options that can be used when processing the request</description>
    <label>Options</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Async_Request__c/fields/Params__c.field-meta.xml
<CustomField>
    <fullName>Params__c</fullName>
    <label>Params</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/BaseAsyncHandlerTest.cls
/**
 * Created by vikasmishra on 2021-09-09.
 */

@IsTest
private class BaseAsyncHandlerTest {

    private static final String NEW_DESCRIPTION = 'New Description';

    @isTest static void should_update_all_accounts(){
        // Arrange
        List<Account> newAccounts = new List<Account>();

        newAccounts.add((Account) TestFactory.createSObject(new Account(Name='Blah1', Website='test.test', CSM_First_30d_Stage__c = 'Pending Intro')));
        newAccounts.add((Account) TestFactory.createSObject(new Account(Name='Blah2', Website='um.um', CSM_First_30d_Stage__c = 'Pending Delivery')));
        newAccounts.add((Account) TestFactory.createSObject(new Account(Name='Blah2', Website='um.um', CSM_First_30d_Stage__c = 'Attempting Training')));
        newAccounts.add((Account) TestFactory.createSObject(new Account(Name='Blah2', Website='um.um', CSM_First_30d_Stage__c = 'Scheduled Training')));
        newAccounts.add((Account) TestFactory.createSObject(new Account(Name='Blah2', Website='um.um', CSM_First_30d_Stage__c = 'Health Check')));
        newAccounts.add((Account) TestFactory.createSObject(new Account(Name='Blah2', Website='um.um', CSM_First_30d_Stage__c = 'Scheduled Additional Training')));


        insert newAccounts;

        // Act
        System.assert(new GS_AccountSelector(true).checkFatalError().getAccountsByIds(new List<Id>()).isEmpty());
        System.assert(new GS_AccountSelector(true).checkFatalError().getAccountsWithOppAndShipAddrByIds(new List<Id>()).isEmpty());
      
         new BaseAsyncHandlerTest.SampleOptionsJobAsync().moreRequestToProcess();
        new BaseAsyncHandlerTest.SampleOptionsJobAsync().prepareAsyncRequests(new Set<Id>(), 10);
        Test.startTest();

        Set<Id> accIds = new Map<Id, Account>(newAccounts).keySet();
        insert new BaseAsyncHandlerTest.SampleOptionsJobAsync().prepareAsyncRequests(
                JSON.serialize(new BaseAsyncHandlerTest.Options(NEW_DESCRIPTION)),
                accIds);

        Test.stopTest();

        (new BaseAsyncHandlerTest.SampleOptionsJobAsync()).prepareAsyncRequests(new Set<Id>{TestFactory.getFakeId(Opportunity.getSObjectType())});
        (new BaseAsyncHandlerTest.SampleOptionsJobAsync()).getRequestType();
        (new BaseAsyncHandlerTest.SampleOptionsJobAsync()).isHandlerReadOnly();
    }

    public without sharing class SampleOptionsJobAsync extends BaseAsyncHandler {

        public override String getRequestType(){
            return 'Sample Options Job';
        }

        public  Boolean moreRequestToProcess(){
           return this.moreRequestsToProcess(null);
        }
        public override void execute(Async_Request__c ar)
        {
            List<Id> accountIds = ar.Params__c.split(PARAMETERS_SPLITTER);
            if(accountIds.size() == 0) return;

            Options opt = (Options) JSON.deserialize(ar.Options__c, Options.class);

            // Do something with Accounts

            List<Account> accountsToUpdate = [
                    SELECT Id, Description
                    FROM Account
                    WHERE Id IN :accountIds
            ];

            for(Account acc : accountsToUpdate){
                acc.Description = opt.Description;
            }

            update accountsToUpdate;
        }


    }

    public class Options {
        public String Description {get; set;}

        public Options(String description){
            this.Description = description;
        }
    }
}