force-app/main/default/objects/Account/fields/Customer_ARR__c.field-meta.xml
<CustomField>
    <fullName>Customer_ARR__c</fullName>
    <description>Active ACV shows daily changes to annual license revenue via opportunity license start/end date</description>
    <inlineHelpText>Active ACV shows daily changes to annual license revenue via opportunity license start/end date</inlineHelpText>
    <label>Active ACV [USD]</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <description>This field is being used by Netsuite and code for contracts. Before it is changed Business Systems needs to be notified, as it has a number of dependencies.</description>
    <formula>IF(

CONTAINS(Owner.UserRole.Name, &quot;Small Fleets&quot;),
&quot;Small Business&quot;,
IF(
CONTAINS(Owner.UserRole.Name, &quot;AE1&quot;),
&quot;AE1&quot;,
IF(
OR(
CONTAINS(Owner.UserRole.Name, &quot;Partner&quot;),
CONTAINS(Owner.UserRole.Name, &quot;AE2&quot;)
),
&quot;AE2&quot;,
IF(
CONTAINS(Owner.UserRole.Name, &quot;AE3&quot;),
&quot;AE3&quot;,
IF(
OR(
CONTAINS(Owner.UserRole.Name, &quot;ENT&quot;),
CONTAINS(Owner.UserRole.Name, &quot;Enterprise&quot;),
CONTAINS(Owner.UserRole.Name, &quot;Major&quot;),
CONTAINS(Owner.UserRole.Name, &quot;Field&quot;)
),
&quot;Enterprise&quot;,
&quot;Management&quot;
)
)
)
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Segment (by Current Owner)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Finance_Partner_Account__c.field-meta.xml
<CustomField>
    <fullName>Finance_Partner_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>added for GTMS-16222</description>
    <label>Finance Partner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Is_Finance_Partner_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contracts (Finance Partner)</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_360__c/Customer_360__c.object-meta.xml
<CustomObject>
    <label>Customer 360</label>
    <nameField>
        <label>Customer 360 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer 360</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_360__c/fields/Latest_Active_Contract_Historical__c.field-meta.xml
<CustomField>
    <fullName>Latest_Active_Contract_Historical__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Latest Active Contract Historical</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Customer 360</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/of_LIC_Products__c.field-meta.xml
<CustomField>
    <fullName>of_LIC_Products__c</fullName>
    <label># of LIC Products</label>
    <summarizedField>OpportunityLineItem.Quantity</summarizedField>
    <summaryFilterItems>
        <field>OpportunityLineItem.Product_Code_Copy__c</field>
        <operation>contains</operation>
        <value>LIC-</value>
    </summaryFilterItems>
    <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Returning_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Returning_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Returning Opportunity</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Opportunity.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Opportunity.StageName</field>
            <operation>equals</operation>
            <value>Closed Won</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Return Opportunities</relationshipLabel>
    <relationshipName>Related_Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <description>Used by Finance for Netsuite and financial reporting.</description>
    <formula>if( CONTAINS(Pricebook2.Name,&quot;Samsara Express&quot;),&quot;SMB&quot;,

if( AND(OR(CONTAINS(Owner_Role_Copy__c,&quot;MM&quot;),CONTAINS(Owner_Role_Copy__c,&quot;Mid Market&quot;)),Industrial_Oppty__c =FALSE),&quot;Mid Market&quot;,

if( AND(OR(CONTAINS(Owner_Role_Copy__c,&quot;MM&quot;),CONTAINS(Owner_Role_Copy__c,&quot;Mid Market&quot;)),Industrial_Oppty__c =TRUE),&quot;Industrial&quot;,

if( AND(OR(CONTAINS(Owner_Role_Copy__c,&quot;Major Accounts&quot;),CONTAINS(Owner_Role_Copy__c,&quot;Major&quot;),CONTAINS(Owner_Role_Copy__c,&quot;Field&quot;),CONTAINS(Owner_Role_Copy__c,&quot;Enterprise&quot;)),Industrial_Oppty__c =FALSE),&quot;Enterprise&quot;,

if( AND(OR(CONTAINS(Owner_Role_Copy__c,&quot;Major Accounts&quot;),CONTAINS(Owner_Role_Copy__c,&quot;Major&quot;),CONTAINS(Owner_Role_Copy__c,&quot;Field&quot;),CONTAINS(Owner_Role_Copy__c,&quot;Enterprise&quot;)),Industrial_Oppty__c =TRUE),&quot;Industrial&quot;,

if(AND(CONTAINS(Owner_Role_Copy__c,&quot;SMB&quot;),CONTAINS(Pricebook2.Name,&quot;Samsara Standard&quot;)),&quot;Mid Market&quot;,

if(CONTAINS(Owner_Role_Copy__c,&quot;Industrial&quot;),&quot;Industrial&quot;,

if(OR(CONTAINS(Owner_Role_Copy__c,&quot;Management&quot;),CONTAINS(Owner_Role_Copy__c, &quot;Operations&quot;)), Account.Segment_Text_stamped__c , Account.Segment_Text_stamped__c))))))))</formula>
    <inlineHelpText>Deprecated--use Finance Segment instead.</inlineHelpText>
    <label>[DON&apos;T USE] Segment (Price Book)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Prior_OLI_Id__c.field-meta.xml
<CustomField>
    <fullName>Prior_OLI_Id__c</fullName>
    <description>Captures the Opportunity Line Item Id that created this subscription record. This field will be passed over to QLI for Amendments for Remorse Refund Logic to figure out the specific line for refunding.</description>
    <label>Prior OLI Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/SBQQ__Subscription__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Subscription__c/fields/Prior_OLI_Id__c.field-meta.xml
<CustomField>
    <fullName>Prior_OLI_Id__c</fullName>
    <description>Captures the Opportunity Line Item Id that created this subscription record. This field will be passed over to QLI for Amendments for Remorse Refund Logic to figure out the specific line for refunding.</description>
    <label>Prior OLI Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/Prior_OppId_Legacy__c.field-meta.xml
<CustomField>
    <fullName>Prior_OppId_Legacy__c</fullName>
    <description>Captures the Opportunity Id this Subscription record is generated from</description>
    <inlineHelpText>Captures the Opportunity Id this Subscription record is generated from</inlineHelpText>
    <label>Prior OppId (Legacy)</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__Account__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account that owns this subscription. This relationship is used for volume discount calculations.</description>
    <inlineHelpText>Account that owns this subscription. This relationship is used for volume discount calculations.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__AdditionalDiscountAmount__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__AdditionalDiscountAmount__c</fullName>
    <description>Additional Discount for this Subscription, if expressed as an amount</description>
    <inlineHelpText>Additional Discount for this Subscription, if expressed as an amount</inlineHelpText>
    <label>Additional Disc. (Amt)</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__Contract__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contract that governs this subscription.</description>
    <inlineHelpText>Contract that governs this subscription.</inlineHelpText>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__Discount__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Discount__c</fullName>
    <description>Additional Discount for this Subscription, if expressed as a percentage</description>
    <inlineHelpText>Additional Discount for this Subscription, if expressed as a percentage</inlineHelpText>
    <label>Additional Disc. (%)</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__Product__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product used to sell this subscription.</description>
    <inlineHelpText>Product used to sell this subscription.</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__Quantity__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quantity__c</fullName>
    <description>Quantity of this subscription product purchased by the customer.</description>
    <inlineHelpText>Quantity of this subscription product purchased by the customer.</inlineHelpText>
    <label>Quantity</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__QuoteLine__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__QuoteLine__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Quote line that generated this subscription.</description>
    <inlineHelpText>Quote line that generated this subscription.</inlineHelpText>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__RenewalQuantity__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__RenewalQuantity__c</fullName>
    <description>Quantity of this subscription product that will be renewed.</description>
    <inlineHelpText>Quantity of this subscription product that will be renewed.</inlineHelpText>
    <label>Renewal Quantity</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__RevisedSubscription__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__RevisedSubscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Lookup the Revised Subscription for this field.</inlineHelpText>
    <label>Revised Subscription</label>
    <referenceTo>SBQQ__Subscription__c</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Revisions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__RootId__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__RootId__c</fullName>
    <description>The ID of the subscription or asset at the root of the bundle that contains this subscription</description>
    <externalId>true</externalId>
    <inlineHelpText>The ID of the subscription or asset at the root of the bundle that contains this subscription</inlineHelpText>
    <label>Root Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__SubscriptionStartDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__SubscriptionStartDate__c</fullName>
    <description>Matches the quote line start date by default. If blank, it will match the contract start date.</description>
    <inlineHelpText>Matches the quote line start date by default. If blank, it will match the contract start date.</inlineHelpText>
    <label>Subscription Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__TerminatedDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__TerminatedDate__c</fullName>
    <description>Date on which this subscription terminated.</description>
    <inlineHelpText>Date the subscription terminated. Automatically populated when covered asset is upgraded.</inlineHelpText>
    <label>Terminated Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/Batch_ReturnOpptyDataFix.cls
/*
* GTMS - GTMS-11667 Siddharth Kumar Mishra -  03/17/2023  - Add scheduled batch job to fix returns data                
*/
public class Batch_ReturnOpptyDataFix implements Database.Batchable<sObject>,Database.Stateful,Schedulable
{
    public SamsaraLoggerService thisSamsaraLoggerService = new SamsaraLoggerService();
    public string errorString = '';
    
    //START METHOD
    public Database.QueryLocator start(Database.BatchableContext BC)
    { 
        String query = 'SELECT Id,AccountId,Account.Name,Account.Customer_ARR__c , Account.Segment__c ,Type,StageName,CloseDate,CreatedDate, CreatedBy.Name, ContractID,SBQQ__AmendedContract__c, Contract.EndDate, Returning_Opportunity__c,Returning_Opportunity__r.Name,Returning_Opportunity__r.AccountId, Returning_Opportunity__r.ContractId, Returning_Opportunity__r.SBQQ__AmendedContract__c FROM opportunity WHERE type =\'Remorse Refund\' AND CloseDate >= LAST_N_DAYS:7 AND Returning_Opportunity__c !=null AND SBQQ__AmendedContract__c =null AND stagename = \'Refunded - Closed\' AND ContractID=null  AND of_LIC_Products__c!=0 ';
        
        
        return Database.getQueryLocator(query);
    }
    
    //EXECUTE METHOD
    public void execute(Database.BatchableContext BC, List<Opportunity> opportunityList)
    {
        findContracts(opportunityList);
        
        
    }
    
    //FINISH METHOD
    public void finish(Database.BatchableContext BC)
    { 
        if(!String.isBlank(errorString) && !string.isEmpty(errorString))
        {
            emailErrors(errorString);
        }
        
    }
    
    public void findContracts(List<Opportunity> opportunityList)
    {
        Set<Id> oppIds = new Set<Id>();
        for(Opportunity o:opportunityList)
        {
            oppIds.add(o.Id);          
        }
        Map<Id,Opportunity> mapOpps=new Map<Id,Opportunity>([Select Id,AccountId,Account.Name,Account.Customer_ARR__c , Account.Segment__c ,Type,StageName,CloseDate,CreatedDate, CreatedBy.Name, ContractID,SBQQ__AmendedContract__c, Contract.EndDate, Returning_Opportunity__c,Returning_Opportunity__r.Name,Returning_Opportunity__r.AccountId, Returning_Opportunity__r.ContractId, Returning_Opportunity__r.SBQQ__AmendedContract__c, (Select Id From SBQQ__Contracts__r) ,(Select Id,Product2Id,Quantity From OpportunityLineItems Where ProductCode like '%LIC%') From Opportunity where Id IN:oppIds order by Id]);
        Map<Id,Id> OriginalReturnOppID=new Map<Id,Id>();
        Map<Id,Id> ReturnOriginalOppID=new Map<Id,Id>();
        Map<Id,Id> returnOppID=new Map<Id,Id>();
        Map<Id,Id> originalOppWithContractMap = new Map<Id,Id>();
        for(Opportunity o:mapOpps.values()){
            OriginalReturnOppID.put(o.Id,o.Returning_Opportunity__c);
            ReturnOriginalOppID.put(o.Returning_Opportunity__c,o.Id);
        }
        
        Map<Id,Opportunity> mapReturnOpps=new Map<Id,Opportunity> ([Select Id, CreatedDate, CreatedBy.Name, ContractID, Contract.EndDate,SBQQ__AmendedContract__c,(Select Id,EndDate From SBQQ__Contracts__r) From Opportunity where id=:OriginalReturnOppID.values() ]);
        Map<Id,Id> ReturnOppWithContractID=new Map<Id,Id>();
        Map<Id,Id> ContractReturnOppWithID=new Map<Id,Id>();
        Map<Id,Id> oppWithoutContract=new Map<Id,Id>();
        for(Opportunity o:mapReturnOpps.values()){
            if(o.ContractID!=null){
                ReturnOppWithContractID.put(o.Id,o.ContractID);
                ContractReturnOppWithID.put(o.ContractId,o.Id);
            }
            else if(o.SBQQ__AmendedContract__c!=null){
                ReturnOppWithContractID.put(o.Id,o.SBQQ__AmendedContract__c);
                ContractReturnOppWithID.put(o.SBQQ__AmendedContract__c,o.Id);
            }
            else if(o.SBQQ__Contracts__r.size()>0){
                ReturnOppWithContractID.put(o.Id,o.SBQQ__Contracts__r[0].Id);
                ContractReturnOppWithID.put(o.SBQQ__Contracts__r[0].Id,o.Id);
                if(o.SBQQ__Contracts__r.size()>1){
                    System.debug('Opp withmore than one contract---->'+o.Id);
                }
            }
            else{
                oppWithoutContract.put(ReturnOriginalOppID.get(o.Id),o.Id);
            }
        }
        if(!ReturnOppWithContractID.isEmpty())
        {
            for(Id i:ReturnOppWithContractID.keySet())
            {
                createSubscriptions(ReturnOriginalOppID.get(i),ReturnOppWithContractID.get(i));
            }	            
        }
        
    }
    
    public void createSubscriptions(Id oppId, Id contractId)
    {
        String result='';
        if(String.isNotBlank(contractId) && String.isNotBlank(oppId)){
            try{
                Opportunity o;
                List<Opportunity>  listO=[Select Id,SBQQ__AmendedContract__c,(Select Id,Product2Id,Quantity,OpportunityId,Opportunity.CloseDate From OpportunityLineItems where Product2.ProductCode like 'LIC-%' and Quantity<0 ) From Opportunity Where Id=:oppId];
                if(listO.size()==0){
                    result='Opportunity not found';
                }
                else{
                    o=listO[0];
                }
                if(o!=null && o.SBQQ__AmendedContract__c!=null){
                    result='Opportunity is already updated';
                }
                else if(o!=null){
                    List<String> reqFields = getFields('SBQQ__Subscription__c');
                    Contract c=Database.query('Select Id,(Select '+String.join(reqFields,',')+' From SBQQ__Subscriptions__r) From Contract Where Id=:contractId ');
                    Map<Id,SBQQ__Subscription__c> mapSub=new Map<Id,SBQQ__Subscription__c>();
                    Map<Id,Decimal> mapSubQuantity=new Map<Id,Decimal>();
                    Map<Id,Decimal> mapOLIQuantity=new Map<Id,Decimal>();
                    for(SBQQ__Subscription__c s:c.SBQQ__Subscriptions__r){
                        if(!mapSubQuantity.containsKey(s.SBQQ__Product__c)){
                            mapSubQuantity.put(s.SBQQ__Product__c,0);
                        }
                        mapSub.put(s.SBQQ__Product__c,s);
                        mapSubQuantity.put(s.SBQQ__Product__c,mapSubQuantity.get(s.SBQQ__Product__c)+s.SBQQ__Quantity__c);
                    }
                    for(OpportunityLineItem oli:o.OpportunityLineItems){
                        if(!mapOLIQuantity.containsKey(oli.Product2Id)){
                            mapOLIQuantity.put(oli.Product2Id,0);
                        }
                        mapOLIQuantity.put(oli.Product2Id,mapOLIQuantity.get(oli.Product2Id)+oli.Quantity);                
                    }
                    List<SBQQ__Subscription__c> listS=new List<SBQQ__Subscription__c>();
                    Set<String> processIDs=new Set<String>();
                    for(OpportunityLineItem oli:o.OpportunityLineItems){
                        if(processIDs.contains(oli.Product2Id))
                        {
                            continue;
                        }
                        processIDs.add(oli.Product2Id);
                        SBQQ__Subscription__c oliS=mapSub.get(oli.Product2Id);
                        Decimal subQuantity=mapSubQuantity.get(oli.Product2Id);
                        Decimal oliQuantity=mapOLIQuantity.get(oli.Product2Id);
                        if(oliS!=null && (subQuantity+oliQuantity)>=0){
                            SBQQ__Subscription__c clonedS=oliS.clone();
                            // clonedS.SBQQ__Discount__c=null;
                            // clonedS.SBQQ__AdditionalDiscountAmount__c=null;
                            clonedS.Prior_OLI_Id__c=oli.Id;
                            clonedS.Prior_OppId_Legacy__c=oli.OpportunityId;
                            clonedS.SBQQ__Product__c=oli.Product2Id;
                            clonedS.SBQQ__Quantity__c=oliQuantity;
                            clonedS.SBQQ__QuoteLine__c=null;
                            clonedS.SBQQ__SubscriptionStartDate__c=oli.Opportunity.CloseDate;
                            clonedS.SBQQ__RootId__c=null;
                            clonedS.OwnerId='0054p000002sSsE'; //Dataload Bot
                            //clonedS.SBQQ__RenewalQuantity__c=oli.Quantity;
                            clonedS.SBQQ__RevisedSubscription__c=oliS.Id;
                            
                            if((subQuantity+oliQuantity)<=0){
                                clonedS.SBQQ__TerminatedDate__c=oli.Opportunity.CloseDate;
                                for(SBQQ__Subscription__c s:c.SBQQ__Subscriptions__r){
                                    if(s.SBQQ__Product__c==oli.Product2Id){
                                        s.SBQQ__TerminatedDate__c=oli.Opportunity.CloseDate;
                                        listS.add(s);
                                    }
                                }                        
                                
                            }
                            listS.add(clonedS);
                        }
                    }
                    
                    if(listS.size()>0){
                        upsert listS;
                        o.SBQQ__AmendedContract__c=contractId;
                        update o;
                        result='Successfully updated';
                    }
                    else{
                        result='Sum of sub after applying is less than zero';
                    }
                    
                }
                
            }
            catch(Exception ex){
                result=ex.getMessage();
            }
        }
        System.debug('@@@==='+oppId+'='+result+'===@@@');
        
    }
    
    public static List<string> getFields(String selectedObject)
    {
        List<String> reqFields = new List<String>();
        Map <String,Schema.SObjectType> gd = Schema.getGlobalDescribe();
        Schema.SObjectType sobjType = gd.get(selectedObject);
        Schema.DescribeSObjectResult r = sobjType.getDescribe();
        Map<String, Schema.SObjectField> MapofField = r.fields.getMap();
        
        for(String fieldName : MapofField.keySet()) {
            Schema.SObjectField field = MapofField.get(fieldName);
            Schema.DescribeFieldResult F = field.getDescribe();
            //System.debug('field---->'+field);
            //  System.debug('F---->'+F.getType()); //type of field
            reqFields.add(fieldName);
        }
        System.debug(reqFields);
        return reqFields;
    }
    
    public void emailErrors(string errorString)
    {
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setToAddresses(getEmailAddresses());
        mail.setSubject('CPQ Error Notification');
        mail.setPlainTextBody(errorString);
        if(!test.isRunningTest())
        {
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });            
        }
        
    }
    public List<String> getEmailAddresses()
    {
        List<Id> idList = new List<Id>();
        List<String> mailToAddresses = System.Label.Batch_ReturnOpptyDataFix_Error_Emails.Split(',');
        
        return mailToAddresses;
    }
    
    //Schedulable execute
    public void execute(SchedulableContext SC)
    {
        Database.executebatch((new Batch_ReturnOpptyDataFix()),1);
    }
}