force-app/main/default/objects/Account/fields/Customer_ARR__c.field-meta.xml
<CustomField>
    <fullName>Customer_ARR__c</fullName>
    <description>Active ACV shows daily changes to annual license revenue via opportunity license start/end date</description>
    <inlineHelpText>Active ACV shows daily changes to annual license revenue via opportunity license start/end date</inlineHelpText>
    <label>Active ACV [USD]</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Most_Recent_Source__c.field-meta.xml
<CustomField>
    <fullName>Most_Recent_Source__c</fullName>
    <description>Populated by the most recent lead that converts/merges into this account (or a contact under this account).</description>
    <label>Most Recent Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Organization_Size__c.field-meta.xml
<CustomField>
    <fullName>Organization_Size__c</fullName>
    <description>Number of employees or students</description>
    <inlineHelpText>Number of employees or students</inlineHelpText>
    <label>Organization Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 - 99</fullName>
            </value>
            <value>
                <fullName>100 - 499</fullName>
            </value>
            <value>
                <fullName>500 - 999</fullName>
            </value>
            <value>
                <fullName>1000 - 4999</fullName>
            </value>
            <value>
                <fullName>5000+</fullName>
            </value>
            <value>
                <fullName>0</fullName>
                <isActive>false</isActive>
                <label>0</label>
            </value>
            <value>
                <fullName>1-99</fullName>
                <isActive>false</isActive>
                <label>1-99</label>
            </value>
            <value>
                <fullName>1/1/1999 12:00:00 AM</fullName>
                <isActive>false</isActive>
                <label>1/1/1999 12:00:00 AM</label>
            </value>
            <value>
                <fullName>10</fullName>
                <isActive>false</isActive>
                <label>10</label>
            </value>
            <value>
                <fullName>100 - 999</fullName>
                <isActive>false</isActive>
                <label>100 - 999</label>
            </value>
            <value>
                <fullName>100-499</fullName>
                <isActive>false</isActive>
                <label>100-499</label>
            </value>
            <value>
                <fullName>1000+</fullName>
                <isActive>false</isActive>
                <label>1000+</label>
            </value>
            <value>
                <fullName>1000-4999</fullName>
                <isActive>false</isActive>
                <label>1000-4999</label>
            </value>
            <value>
                <fullName>10000+</fullName>
                <isActive>false</isActive>
                <label>10000+</label>
            </value>
            <value>
                <fullName>11</fullName>
                <isActive>false</isActive>
                <label>11</label>
            </value>
            <value>
                <fullName>13</fullName>
                <isActive>false</isActive>
                <label>13</label>
            </value>
            <value>
                <fullName>200</fullName>
                <isActive>false</isActive>
                <label>200</label>
            </value>
            <value>
                <fullName>201-500</fullName>
                <isActive>false</isActive>
                <label>201-500</label>
            </value>
            <value>
                <fullName>21</fullName>
                <isActive>false</isActive>
                <label>21</label>
            </value>
            <value>
                <fullName>22</fullName>
                <isActive>false</isActive>
                <label>22</label>
            </value>
            <value>
                <fullName>29</fullName>
                <isActive>false</isActive>
                <label>29</label>
            </value>
            <value>
                <fullName>34</fullName>
                <isActive>false</isActive>
                <label>34</label>
            </value>
            <value>
                <fullName>36161</fullName>
                <isActive>false</isActive>
                <label>36161</label>
            </value>
            <value>
                <fullName>42</fullName>
                <isActive>false</isActive>
                <label>42</label>
            </value>
            <value>
                <fullName>495 - 1000</fullName>
                <isActive>false</isActive>
                <label>495 - 1000</label>
            </value>
            <value>
                <fullName>496 - 1000</fullName>
                <isActive>false</isActive>
                <label>496 - 1000</label>
            </value>
            <value>
                <fullName>497 - 1000</fullName>
                <isActive>false</isActive>
                <label>497 - 1000</label>
            </value>
            <value>
                <fullName>498 - 1000</fullName>
                <isActive>false</isActive>
                <label>498 - 1000</label>
            </value>
            <value>
                <fullName>499 - 1000</fullName>
                <isActive>false</isActive>
                <label>499 - 1000</label>
            </value>
            <value>
                <fullName>500 - 1000</fullName>
                <isActive>false</isActive>
                <label>500 - 1000</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Quarantine_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Quarantine_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deactivated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Fleet.recordType-meta.xml
<RecordType>
    <fullName>Fleet</fullName>
    <active>true</active>
    <description>Fleet account</description>
    <label>Fleet</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Most_Recent_Source__c.field-meta.xml
<CustomField>
    <fullName>Most_Recent_Source__c</fullName>
    <label>Most Recent Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/New_Inbound_Lead__c.field-meta.xml
<CustomField>
    <fullName>New_Inbound_Lead__c</fullName>
    <defaultValue>false</defaultValue>
    <label>New Inbound Lead</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Organization_Size__c.field-meta.xml
<CustomField>
    <fullName>Organization_Size__c</fullName>
    <formula>TEXT(Account.Organization_Size__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Please edit on the Account page.</inlineHelpText>
    <label>Organization Size</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Fleet.recordType-meta.xml
<RecordType>
    <fullName>Fleet</fullName>
    <active>true</active>
    <description>Fleet contact</description>
    <label>Fleet</label>
</RecordType>

force-app/main/default/classes/BatchAssignADRfromContactTest.cls
@isTest
public with sharing class BatchAssignADRfromContactTest {
    @testSetup 
    public static void dataSetup() {
        UserRole ur = [Select id,name from Userrole where Name ='Enterprise - UK - AE'];
        User usr = new User(
         ProfileId = [SELECT Id FROM Profile WHERE Name = 'Samsara Sales - NA US AE3'].Id,
         LastName = 'last',
         Email = 'puser000@amamama.com',
         Username = 'puser000@amamama.com' + System.currentTimeMillis(),
         CompanyName = 'TEST',
         Title = 'title',
         Alias = 'alias',
         TimeZoneSidKey = 'America/Los_Angeles',
         EmailEncodingKey = 'UTF-8',
         LanguageLocaleKey = 'en_US',
         LocaleSidKey = 'en_US',
         UserRoleId = ur.Id,
         EmployeeNumber = '12345876'
        );
        insert usr;
        system.runAs(usr) {
            Account accountOne = new Account(Name = 'Testers 1 Inc',
                                BillingCountry = 'United kingdom',
                                Organization_Size__c = '100 - 499',
                                Industry = 'Other',
                                Customer_ARR__c = 5,
                                Quarantine_Enabled__c = false);
            Account accountTwo = new Account(Name = 'Testers 2 Inc',
                                    BillingCountry = 'United kingdom',
                                    Organization_Size__c = '100 - 499',
                                    Industry = 'Other',
                                    Customer_ARR__c = 5,
                                    Quarantine_Enabled__c = false,
                                    ownerId = usr.Id);
            insert accountOne;
            insert accountTwo;
            Contact contactOne = (Contact)TestFactory.createSObject(new Contact(AccountId = accountOne.Id));
            contactOne.New_Inbound_Lead__c = True;
            contactOne.Most_Recent_Source__c = 'Sites webinar registration form';
            insert contactOne;
            Contact contactTwo = (Contact)TestFactory.createSObject(new Contact(AccountId = accountTwo.Id));
            contactTwo.New_Inbound_Lead__c = True;
            contactTwo.Most_Recent_Source__c = 'Sites webinar registration form';
            insert contactTwo;
            User u = [SELECT Id FROM User WHERE UserRole.Name ='Fleet ADR NA US Team 1 - Manager' LIMIT 1];
            AccountTeamMember atm  = new AccountTeamMember(TeamMemberRole = 'Sites Account Development Representative', AccountId = accountTwo.id, userId = u.id);
            insert atm;
            AccountTeamMember atmTwo  = new AccountTeamMember(TeamMemberRole = 'Sites Account Development Representative', AccountId = accountOne.id, userId = u.id);
            insert atmTwo;
        }
        
    }


    @isTest static void runNonEntr(){
        Test.startTest();
        Database.executeBatch(new BatchAssignADRfromContact());
        Map<Id, Id> UserContactMap = new Map<Id, Id>();
        Map<Id, Id> accIdContactId = new Map<Id, Id>();
        Map<Id, Id> AccountToADRMap = new Map<Id, Id>();
        Map<Id, Integer> mapUserCount = new Map<Id, Integer>();
        List <Account> lstacc = [Select Id,(Select Id, UserId, AccountId from AccountTeamMembers),(Select Id,AccountId from Contacts) from Account];
        For(Account ac: LstAcc){
            for(AccountTeamMember atm : ac.AccountTeamMembers) {
                AccountToADRMap.put(atm.AccountId, atm.UserId);
                mapUserCount.put(atm.UserId, 0);
            }
            for(Contact c : ac.Contacts) {
                accIdContactId.put(c.AccountId, c.Id);
            }
        }
        for(Id accId: AccountToADRMap.keySet()){
            UserContactMap.put(accIdContactId.get(accId),AccountToADRMap.get(accId));
        }
        BatchAssignADRfromContactHelper.InsertADRs(lstacc[0].contacts,mapUserCount,UserContactMap);
        Test.stopTest();
    }
}