force-app/main/default/objects/Account/fields/Domain_Name__c.field-meta.xml
<CustomField>
    <fullName>Domain_Name__c</fullName>
    <description>Saves the domain, considering first the name after the email and then the website.</description>
    <label>Domain Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Organization_Size__c.field-meta.xml
<CustomField>
    <fullName>Organization_Size__c</fullName>
    <description>Number of employees or students</description>
    <inlineHelpText>Number of employees or students</inlineHelpText>
    <label>Organization Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 - 99</fullName>
            </value>
            <value>
                <fullName>100 - 499</fullName>
            </value>
            <value>
                <fullName>500 - 999</fullName>
            </value>
            <value>
                <fullName>1000 - 4999</fullName>
            </value>
            <value>
                <fullName>5000+</fullName>
            </value>
            <value>
                <fullName>0</fullName>
                <isActive>false</isActive>
                <label>0</label>
            </value>
            <value>
                <fullName>1-99</fullName>
                <isActive>false</isActive>
                <label>1-99</label>
            </value>
            <value>
                <fullName>1/1/1999 12:00:00 AM</fullName>
                <isActive>false</isActive>
                <label>1/1/1999 12:00:00 AM</label>
            </value>
            <value>
                <fullName>10</fullName>
                <isActive>false</isActive>
                <label>10</label>
            </value>
            <value>
                <fullName>100 - 999</fullName>
                <isActive>false</isActive>
                <label>100 - 999</label>
            </value>
            <value>
                <fullName>100-499</fullName>
                <isActive>false</isActive>
                <label>100-499</label>
            </value>
            <value>
                <fullName>1000+</fullName>
                <isActive>false</isActive>
                <label>1000+</label>
            </value>
            <value>
                <fullName>1000-4999</fullName>
                <isActive>false</isActive>
                <label>1000-4999</label>
            </value>
            <value>
                <fullName>10000+</fullName>
                <isActive>false</isActive>
                <label>10000+</label>
            </value>
            <value>
                <fullName>11</fullName>
                <isActive>false</isActive>
                <label>11</label>
            </value>
            <value>
                <fullName>13</fullName>
                <isActive>false</isActive>
                <label>13</label>
            </value>
            <value>
                <fullName>200</fullName>
                <isActive>false</isActive>
                <label>200</label>
            </value>
            <value>
                <fullName>201-500</fullName>
                <isActive>false</isActive>
                <label>201-500</label>
            </value>
            <value>
                <fullName>21</fullName>
                <isActive>false</isActive>
                <label>21</label>
            </value>
            <value>
                <fullName>22</fullName>
                <isActive>false</isActive>
                <label>22</label>
            </value>
            <value>
                <fullName>29</fullName>
                <isActive>false</isActive>
                <label>29</label>
            </value>
            <value>
                <fullName>34</fullName>
                <isActive>false</isActive>
                <label>34</label>
            </value>
            <value>
                <fullName>36161</fullName>
                <isActive>false</isActive>
                <label>36161</label>
            </value>
            <value>
                <fullName>42</fullName>
                <isActive>false</isActive>
                <label>42</label>
            </value>
            <value>
                <fullName>495 - 1000</fullName>
                <isActive>false</isActive>
                <label>495 - 1000</label>
            </value>
            <value>
                <fullName>496 - 1000</fullName>
                <isActive>false</isActive>
                <label>496 - 1000</label>
            </value>
            <value>
                <fullName>497 - 1000</fullName>
                <isActive>false</isActive>
                <label>497 - 1000</label>
            </value>
            <value>
                <fullName>498 - 1000</fullName>
                <isActive>false</isActive>
                <label>498 - 1000</label>
            </value>
            <value>
                <fullName>499 - 1000</fullName>
                <isActive>false</isActive>
                <label>499 - 1000</label>
            </value>
            <value>
                <fullName>500 - 1000</fullName>
                <isActive>false</isActive>
                <label>500 - 1000</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DedupeAccountsTest.cls
@isTest
private class DedupeAccountsTest {
   // Setup test data
   @testSetup
    private static void testDataSetup(){
        //create three test accounts
        List<Account> newAccounts = new List<Account>();
        for (Integer i = 0; i < 2; i++){
            newAccounts.add(new Account (Name = 'Super Crazy Test Account',Website='www.crazytestaccount313.com',Domain_Name__c='crazytestaccount313.com', Organization_Size__c = '5000+', BillingCountry = 'United States',BillingState = 'Alabama', Industry = 'Other'));
        }
        newAccounts.add(new Account (Name = 'Not a Crazy Test Account',Organization_Size__c = '5000+', BillingCountry = 'United States',BillingState = 'Alabama', Industry = 'Other'));
        insert newAccounts;
        
    }
   // Methods for testing
   @isTest static void whenDuplicateRecordsExist() {
      // get the first super crazy test account
      Account testAccount = [SELECT Id,RecordTypeId FROM Account WHERE Website='www.crazytestaccount313.com' LIMIT 1];
      Account secondTestAccount = [SELECT Id,RecordTypeId FROM Account WHERE Website='www.crazytestaccount313.com' AND Id!=:testAccount.Id LIMIT 1];
      
      Test.startTest();
      DuplicateRule dR = [select id from DuplicateRule where DeveloperName = 'Lead_to_Account_Matching_v4' LIMIT 1];
      DuplicateRecordSet dupRS = new DuplicateRecordSet(DuplicateRuleId = dR.id);
      insert dupRS;

      DuplicateRecordItem dup = new DuplicateRecordItem(DuplicateRecordSetId = dupRS.id, RecordId=testAccount.id);
      insert dup;
      List<Account> accounts = new List<Account>();
      accounts.add(testAccount);
      List<List<Account>> results = DedupeAccounts.getDuplicateAccountsForProcessing(accounts);
      Boolean test_result = results[0].contains(secondTestAccount);
      System.assert(true,test_result);
      Test.stopTest();
   }
    
   @isTest static void whenDuplicateRecordsDoNotExist() {
      Test.startTest();
      // get the first super crazy test account
      Account testAccount = [SELECT Id,RecordTypeId FROM Account WHERE Name='Not a Crazy Test Account' LIMIT 1];
      List<Account> accounts = new List<Account>();
      accounts.add(testAccount);
      List<List<Account>> results = DedupeAccounts.getDuplicateAccountsForProcessing(accounts);
      Integer test_result = results[0].size();
      System.assertEquals(0, test_result);
      Test.stopTest();
   }
}