force-app/main/default/objects/Account/fields/Domain_Name__c.field-meta.xml
<CustomField>
    <fullName>Domain_Name__c</fullName>
    <description>Saves the domain, considering first the name after the email and then the website.</description>
    <label>Domain Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DUNS_Number__c.field-meta.xml
<CustomField>
    <fullName>DUNS_Number__c</fullName>
    <description>D&amp;B Number</description>
    <label>DUNS Number</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Organization_Size__c.field-meta.xml
<CustomField>
    <fullName>Organization_Size__c</fullName>
    <description>Number of employees or students</description>
    <inlineHelpText>Number of employees or students</inlineHelpText>
    <label>Organization Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 - 99</fullName>
            </value>
            <value>
                <fullName>100 - 499</fullName>
            </value>
            <value>
                <fullName>500 - 999</fullName>
            </value>
            <value>
                <fullName>1000 - 4999</fullName>
            </value>
            <value>
                <fullName>5000+</fullName>
            </value>
            <value>
                <fullName>0</fullName>
                <isActive>false</isActive>
                <label>0</label>
            </value>
            <value>
                <fullName>1-99</fullName>
                <isActive>false</isActive>
                <label>1-99</label>
            </value>
            <value>
                <fullName>1/1/1999 12:00:00 AM</fullName>
                <isActive>false</isActive>
                <label>1/1/1999 12:00:00 AM</label>
            </value>
            <value>
                <fullName>10</fullName>
                <isActive>false</isActive>
                <label>10</label>
            </value>
            <value>
                <fullName>100 - 999</fullName>
                <isActive>false</isActive>
                <label>100 - 999</label>
            </value>
            <value>
                <fullName>100-499</fullName>
                <isActive>false</isActive>
                <label>100-499</label>
            </value>
            <value>
                <fullName>1000+</fullName>
                <isActive>false</isActive>
                <label>1000+</label>
            </value>
            <value>
                <fullName>1000-4999</fullName>
                <isActive>false</isActive>
                <label>1000-4999</label>
            </value>
            <value>
                <fullName>10000+</fullName>
                <isActive>false</isActive>
                <label>10000+</label>
            </value>
            <value>
                <fullName>11</fullName>
                <isActive>false</isActive>
                <label>11</label>
            </value>
            <value>
                <fullName>13</fullName>
                <isActive>false</isActive>
                <label>13</label>
            </value>
            <value>
                <fullName>200</fullName>
                <isActive>false</isActive>
                <label>200</label>
            </value>
            <value>
                <fullName>201-500</fullName>
                <isActive>false</isActive>
                <label>201-500</label>
            </value>
            <value>
                <fullName>21</fullName>
                <isActive>false</isActive>
                <label>21</label>
            </value>
            <value>
                <fullName>22</fullName>
                <isActive>false</isActive>
                <label>22</label>
            </value>
            <value>
                <fullName>29</fullName>
                <isActive>false</isActive>
                <label>29</label>
            </value>
            <value>
                <fullName>34</fullName>
                <isActive>false</isActive>
                <label>34</label>
            </value>
            <value>
                <fullName>36161</fullName>
                <isActive>false</isActive>
                <label>36161</label>
            </value>
            <value>
                <fullName>42</fullName>
                <isActive>false</isActive>
                <label>42</label>
            </value>
            <value>
                <fullName>495 - 1000</fullName>
                <isActive>false</isActive>
                <label>495 - 1000</label>
            </value>
            <value>
                <fullName>496 - 1000</fullName>
                <isActive>false</isActive>
                <label>496 - 1000</label>
            </value>
            <value>
                <fullName>497 - 1000</fullName>
                <isActive>false</isActive>
                <label>497 - 1000</label>
            </value>
            <value>
                <fullName>498 - 1000</fullName>
                <isActive>false</isActive>
                <label>498 - 1000</label>
            </value>
            <value>
                <fullName>499 - 1000</fullName>
                <isActive>false</isActive>
                <label>499 - 1000</label>
            </value>
            <value>
                <fullName>500 - 1000</fullName>
                <isActive>false</isActive>
                <label>500 - 1000</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FlowAccountFinderTest.cls
@isTest
private class FlowAccountFinderTest {
   // Setup test data
   @testSetup
    private static void testDataSetup(){
        //create two test accounts
        List<Account> newAccounts = new List<Account>();
        newAccounts.add(new Account (Name = 'Super Crazy Test Account',Website='www.crazytestaccount1.com',Domain_Name__c='crazytestaccount1.com',Alternative_Domains__c='["crazytestaccount1.com","crazytestaccount.com"]', Organization_Size__c = '5000+', Phone='123-456-7890',BillingCountry = 'United States',DUNS_Number__c='048244101',BillingStreet = '123 crazy kids lane #1',BillingState = 'Alabama',BillingPostalCode = '12345', Industry = 'Passenger Transit'));
        newAccounts.add(new Account (Name = 'Super Crazy Test Account 31234',Alternative_Domains__c='["crazytestaccount1.com","crazytestaccount.com"]', Organization_Size__c = '5000+',BillingCountry = 'United Kingdom',DUNS_Number__c='048244101', Industry = 'Passenger Transit'));
        insert newAccounts;
    }
   // Methods for testing
   @isTest static void doASearch() {
      // get the first super crazy test account
      Account testAccount = [SELECT Name,Website,Domain_Name__c,Alternative_Domains__c,Phone,BillingCity,BillingCountry,BillingState,BillingStreet,BillingPostalCode,DUNS_Number__c,RecordTypeId,Id FROM Account WHERE Website='www.crazytestaccount1.com' LIMIT 1];
      Account secondAccount = [SELECT Id,Website,Domain_Name__c,BillingStreet,BillingState,BillingCity,Phone FROM Account WHERE Name='Super Crazy Test Account 31234' LIMIT 1];
      Test.startTest();

      List<Account> accounts = new List<Account>();
      accounts.add(testAccount);
      List<List<Account>> accounts_list = new List<List<Account>>();
      accounts_list.add(accounts);
      List<List<SObject>> results = FlowAccountFinder.searchForAccounts(accounts_list);
      Boolean test_result = false;
      for(Integer i = 0;i<results[0].size();i++){
          System.debug(results[0][i]);
          if(secondAccount.Id == results[0][i].Id){
              test_result=true;
              //cast result as an account instead of sObject
              Account a = (Account)results[0][i];
              System.assert(true,(String.isBlank(secondAccount.Website) && a.Website==''));
              System.assert(true,(String.isBlank(secondAccount.Domain_Name__c) && a.Domain_Name__c==''));
              System.assert(true,(String.isBlank(secondAccount.BillingStreet) && a.BillingStreet==''));
              System.assert(true,(String.isBlank(secondAccount.BillingState) && a.BillingState==''));
              System.assert(true,(String.isBlank(secondAccount.BillingCity) && a.BillingCity==''));
              System.assert(true,(String.isBlank(secondAccount.Phone) && a.Phone==''));
          }
      }
      System.assert(true,test_result);
      Test.stopTest();
   }
}