force-app/main/default/objects/Account/fields/DUNS_Number__c.field-meta.xml
<CustomField>
    <fullName>DUNS_Number__c</fullName>
    <description>D&amp;B Number</description>
    <label>DUNS Number</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Balance_Due__c.field-meta.xml
<CustomField>
    <fullName>Balance_Due__c</fullName>
    <description>Amount, sales tax, shipping &amp; handling less amount received</description>
    <formula>Amount
+ SBQQ__PrimaryQuote__r.Total_Quote_Line_Item_Subsidy_amount__c
+IF(ISPICKVAL(SBQQ__PrimaryQuote__r.Is_Installation_Reimbursable__c, &apos;No&apos;),SBQQ__PrimaryQuote__r.Total_Estimated_Installation_Costs__c,0)
+ IF(CPQ_Opportunity__c, Sales_Tax_Amount__c, Sales_Tax__c)
+ Shipping_and_Handling__c
+ X3rd_Party_Products_Services__c
- Amount_Received__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Amount, sales tax, shipping &amp; handling less amount received</inlineHelpText>
    <label>Balance Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Finance_Partner_Notes__c.field-meta.xml
<CustomField>
    <fullName>Finance_Partner_Notes__c</fullName>
    <label>Finance Partner Notes</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/License_Term__c.field-meta.xml
<CustomField>
    <fullName>License_Term__c</fullName>
    <defaultValue>36</defaultValue>
    <description>The license term of the opportunity.</description>
    <label>License Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/S_H_Tax__c.field-meta.xml
<CustomField>
    <fullName>S_H_Tax__c</fullName>
    <description>Testing</description>
    <inlineHelpText>This is only available for Quotes originated for Mexico</inlineHelpText>
    <label>Shipping &amp; Handling Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sales_Tax__c.field-meta.xml
<CustomField>
    <fullName>Sales_Tax__c</fullName>
    <formula>IF(
    ISPICKVAL(Type, &apos;Revenue Opportunity&apos;),
    IF(
        NOT(ISBLANK(Shipping_Address_NEW__c)),
        IF(
            Sales_Tax_Historical__c != 0, 
            Sales_Tax_Historical__c,
            IF(
                NOT(ISBLANK(SBQQ__PrimaryQuote__c)), 
                Sales_Tax_Amount__c, 
                Total_Sales_Tax__c+S_H_Tax__c
            )
        ),
        99999
    ),
    IF(
        ISPICKVAL(Type, &apos;Rebate&apos;),
        IF(
            Sales_Tax_Historical__c != 0, 
            Sales_Tax_Historical__c, 
            Total_Sales_Tax__c
        ), 
        0
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Shipping_and_Handling_Amount__c.field-meta.xml
<CustomField>
    <fullName>Shipping_and_Handling_Amount__c</fullName>
    <inlineHelpText>Shipping and Handling (From the Primary Quote)</inlineHelpText>
    <label>Shipping and Handling Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Subsidize_Financing__c.field-meta.xml
<CustomField>
    <fullName>Subsidize_Financing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Subsidize Financing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/EmailFinancePartners.cls
global class EmailFinancePartners{
    @InvocableMethod(label='Email Finance Partners' description='Emails finance partners with relevant information for partners to execute assessment')
    webservice static void sendEmail(List<Id> newOppList){

        Opportunity opps = [Select Id, Amount, License_Term__c, Subsidize_Financing__c, Finance_Partner_Notes__c, AccountId, CloseDate, Balance_Due__c,Sales_Tax__c, S_H_Tax__c,Shipping_and_Handling_Amount__c FROM Opportunity Where Id IN :newOppList];

        Account account = [Select Id, Name, BillingStreet, BillingCity, BillingStateCode, BillingCountryCode, BillingPostalCode, DUNS_Number__c, Website FROM Account Where Id = :opps.AccountId];
                
        String accountaddress = account.BillingStreet+' '+account.BillingCity+', '+account.BillingStateCode+' '+account.BillingPostalCode+' '+account.BillingCountryCode;
        //String accountName_URL = account.Name.replace(' ','+');
        String  opportunity_URL= System.URL.getSalesforceBaseUrl().toExternalForm()+'/'+opps.Id;
        String accountAddress_URL = accountaddress.replace(' ','+');

        String subsidize_string = 'No';
        if(opps.Subsidize_Financing__c) subsidize_string = 'Yes';
        OrgWideEmailAddress owa = [Select Id from OrgWideEmailAddress Where Address = 'deal-desk@samsara.com'];
            Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
            message.setOrgWideEmailAddressId(owa.Id);
            message.setToAddresses(new String[]{'deal-desk@samsara.com'});
            message.setCcAddresses(new String[]{'deal-desk@samsara.com'});
            message.optOutPolicy = 'FILTER';
            message.subject = 'Samsara: Customer Financing Form - '+account.Name;
            String intro = 'Hello, ';
            String email = intro+'\r\n\r\nBilling Name: '+account.Name+'\r\n\r\nBilling Address: '+accountaddress+'\r\n\r\nClose Date: '+opps.CloseDate+'\r\n\r\nOpportunity SFDC Link: '+opportunity_URL+'\r\n\r\nOpportunity Amount: $'+opps.Amount+'\r\n\r\nTerm: '+opps.License_Term__c+' Months\r\n\r\nSales Tax: '+opps.Sales_Tax__c+'\r\n\r\nShipping & Handling: ' + opps.Shipping_and_Handling_Amount__c+'\r\n\r\nTotal Contract Value: ' + opps.Balance_Due__c;
            if(opps.Finance_Partner_Notes__c != ''){
                email = email + '\r\n\r\nNotes: '+opps.Finance_Partner_Notes__c;
            }
            message.plainTextBody = email;

            Messaging.SingleEmailMessage[] messages =   new List<Messaging.SingleEmailMessage> {message};
            Messaging.SendEmailResult[] results = Messaging.sendEmail(messages);
            if (results[0].success) {
                System.debug('The email was sent successfully.');
            } else {
                System.debug('The email failed to send: ' + results[0].errors[0].message);
            }
       // }
        
    }

}