force-app/main/default/objects/Account/fields/DUNS_Number__c.field-meta.xml
<CustomField>
    <fullName>DUNS_Number__c</fullName>
    <description>D&amp;B Number</description>
    <label>DUNS Number</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Finance_Partner__c.field-meta.xml
<CustomField>
    <fullName>Finance_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Finance Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Finance Partner)</relationshipLabel>
    <relationshipName>Accounts5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Credit_Report__c/Credit_Report__c.object-meta.xml
<CustomObject>
    <label>Credit Report</label>
    <nameField>
        <label>Credit Report Provider</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credit Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Credit_Report__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Credit Reports</relationshipLabel>
    <relationshipName>Credit_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Credit_Report__c/fields/DUNS_Number__c.field-meta.xml
<CustomField>
    <fullName>DUNS_Number__c</fullName>
    <label>DUNS Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Finance_Partner_Quote__c/Finance_Partner_Quote__c.object-meta.xml
<CustomObject>
    <label>Finance Partner Quote</label>
    <nameField>
        <displayFormat>FPQ-{00000}</displayFormat>
        <label>FPQ Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Finance Partner Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Finance_Partner_Quote__c/fields/Balance_Due__c.field-meta.xml
<CustomField>
    <fullName>Balance_Due__c</fullName>
    <description>GTMS-16419: Updated field label, Help Text, Length and Decimal places</description>
    <inlineHelpText>Opportunity TCV. Changes require 3PF re-review; please resubmit for approval after updating.</inlineHelpText>
    <label>Requested Amount (TCV)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Finance_Partner_Quote__c/fields/DUNS_Number__c.field-meta.xml
<CustomField>
    <fullName>DUNS_Number__c</fullName>
    <description>GTMS-9965 3PF Automation</description>
    <label>DUNS Number</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Finance_Partner_Quote__c/fields/Finance_Partner__c.field-meta.xml
<CustomField>
    <fullName>Finance_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Finance Partner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Is_Finance_Partner_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Finance Partner Quotes (Finance Partner)</relationshipLabel>
    <relationshipName>Finance_Partner_Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Finance_Partner_Quote__c/fields/Financing_Decision__c.field-meta.xml
<CustomField>
    <fullName>Financing_Decision__c</fullName>
    <label>Financing Decision</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Need More Info</fullName>
            </value>
            <value>
                <fullName>Pending - Under Partner Review</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Resubmit For Review</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Finance_Partner_Quote__c/fields/Financing_Decision_Date__c.field-meta.xml
<CustomField>
    <fullName>Financing_Decision_Date__c</fullName>
    <label>Financing Decision Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Finance_Partner_Quote__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Finance Partner Quotes</relationshipLabel>
    <relationshipName>Finance_Partner_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Finance_Partner_Quote__c/fields/Partner_Contact__c.field-meta.xml
<CustomField>
    <fullName>Partner_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>GTMS-16456: Added filter criteria for this field - 12/12/23</description>
    <label>Partner Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Finance_Partner__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Finance Partner Quotes</relationshipLabel>
    <relationshipName>Finance_Partner_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Balance_Due__c.field-meta.xml
<CustomField>
    <fullName>Balance_Due__c</fullName>
    <description>Amount, sales tax, shipping &amp; handling less amount received</description>
    <formula>Amount
+ SBQQ__PrimaryQuote__r.Total_Quote_Line_Item_Subsidy_amount__c
+IF(ISPICKVAL(SBQQ__PrimaryQuote__r.Is_Installation_Reimbursable__c, &apos;No&apos;),SBQQ__PrimaryQuote__r.Total_Estimated_Installation_Costs__c,0)
+ IF(CPQ_Opportunity__c, Sales_Tax_Amount__c, Sales_Tax__c)
+ Shipping_and_Handling__c
+ X3rd_Party_Products_Services__c
- Amount_Received__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Amount, sales tax, shipping &amp; handling less amount received</inlineHelpText>
    <label>Balance Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Concatenated_Shipping_Address__c.field-meta.xml
<CustomField>
    <fullName>Concatenated_Shipping_Address__c</fullName>
    <formula>Shipping_Address_NEW__r.Shipping_FirstName__c &amp;&quot; &quot;&amp;Shipping_Address_NEW__r.Shipping_LastName__c&amp;BR()&amp;
Shipping_Address_NEW__r.Shipping_Address_Line_1__c&amp;BR()&amp;
Shipping_Address_NEW__r.Shipping_Address_Line_2__c&amp;BR()&amp;
Shipping_Address_NEW__r.Shipping_City__c &amp;&quot;, &quot;&amp;
TEXT( Shipping_Address_NEW__r.Shipping_State__c )&amp;&quot; &quot;&amp;
Shipping_Address_NEW__r.Shipping_Zip_Code__c&amp;BR()&amp;
TEXT(Shipping_Address_NEW__r.Shipping_Country__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Concatenated Shipping Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Finance_Partner__c.field-meta.xml
<CustomField>
    <fullName>Finance_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Finance Partner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Finance Partner</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Finance Partner)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Finance_Partner_Contact__c.field-meta.xml
<CustomField>
    <fullName>Finance_Partner_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Buyout Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Finance Partner Contact)</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Latest_Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Latest_Close_Date__c</fullName>
    <description>Latest close date without changing the license term</description>
    <formula>CloseDate

+

Floor(




(
(
	( License_End_Date__c - CloseDate 
	)
/30.4
)

-


(ROUND((
	( License_End_Date__c - CloseDate 
	)
/30.4
),0)
					-0.5
)

)

* 30.4

)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Latest close date without changing the license term</inlineHelpText>
    <label>Latest Close Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/License_Term__c.field-meta.xml
<CustomField>
    <fullName>License_Term__c</fullName>
    <defaultValue>36</defaultValue>
    <description>The license term of the opportunity.</description>
    <label>License Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/FinancePartnerQuoteController.cls
public without sharing class FinancePartnerQuoteController {
    public class wrapper{
        @AuraEnabled public String LegalName;
        @AuraEnabled public Decimal Tcv;
        @AuraEnabled public Decimal Term;
        @AuraEnabled public Date ExpCloseDate;
        @AuraEnabled public String Address;
        @AuraEnabled public String Duns;
        @AuraEnabled public String opportunityOwner;
    }  
    @AuraEnabled 
    public static wrapper getQuoteDetail(String QuoteID){
        Finance_Partner_Quote__c FPQ;
        account acc;
        FPQ=[Select Id,Opportunity__c,Opportunity__r.AccountId,Opportunity__r.Latest_Close_Date__c,Opportunity__r.owner.Name,Opportunity__r.License_Term__c,Opportunity__r.Balance_Due__c,Opportunity__r.Concatenated_Shipping_Address__c from Finance_Partner_Quote__c where Id=:QuoteID];
       acc=[Select Id,Name,(Select Id,DUNS_Number__c from Credit_Reports__R order by createddate desc limit 1) from account where Id=:FPQ.Opportunity__r.AccountId];
        wrapper wrp = new wrapper();
        system.debug('opppppp-'+FPQ.Opportunity__r.Balance_Due__c);
        wrp.LegalName=acc.Name;
        wrp.Tcv=FPQ.Opportunity__r.Balance_Due__c;
        wrp.ExpCloseDate=FPQ.Opportunity__r.Latest_Close_Date__c;
        wrp.Address=FPQ.Opportunity__r.Concatenated_Shipping_Address__c;
        wrp.Term=FPQ.Opportunity__r.License_Term__c;
        wrp.opportunityOwner = FPQ.Opportunity__r.Owner.Name;
        if(acc != null && acc.Credit_Reports__R != null && acc.Credit_Reports__R.size() > 0)
            wrp.Duns = acc.Credit_Reports__R[0].DUNS_Number__c;
        return wrp;


    }
    @AuraEnabled 
    public static String approvalSubmit(String QuoteID){
        try{
            if(QuoteID != null){
                Finance_Partner_Quote__c obj = new Finance_Partner_Quote__c(Id=QuoteID,Financing_Decision_Date__c=system.now(),Financing_Decision__c = 'Approved');
                update obj;
                List<Finance_Partner_Quote__c> listFPQ = [Select id,Opportunity__c,Finance_Partner__c,Partner_Contact__c from Finance_Partner_Quote__c where Id=:QuoteID];
                Opportunity opp = new Opportunity(Id=listFPQ[0].Opportunity__c,Finance_Partner__c=listFPQ[0].Finance_Partner__c,Finance_Partner_Contact__C =listFPQ[0].Partner_Contact__c);
                //Update opp;
                return 'SUCCESS';
            }
        }catch(Exception ex){
            return ex.getmessage();
        }
        return 'SUCCESS';
    }
    @AuraEnabled 
    public static String sendPOUploadEmail(String QuoteID){
    
        if(QuoteID != null){
            List<Finance_Partner_Quote__c> listFPQ = [Select id,Opportunity__c,Opportunity__r.Owner.email,Opportunity__r.Owner.managerid,Opportunity__r.Owner.manager.email,Finance_Partner__c,Partner_Contact__c from Finance_Partner_Quote__c where Id=:QuoteID];
            if(listFPQ != null && listFPQ.size() > 0){
            String toemail = listFPQ[0].Opportunity__r.Owner.email;
            String ccemail;
            if(listFPQ[0].Opportunity__r.Owner.managerId != null)
               ccemail = listFPQ[0].Opportunity__r.Owner.manager.email;
                sendEmail.sendEmailMethod('FPQ PO Upload Notification',toemail ,ccemail ,listFPQ[0].Opportunity__c);
            }    
        
        }
        return '';
    
    }
}