force-app/main/default/objects/Account/fields/Experimental_Group__c.field-meta.xml
<CustomField>
    <fullName>Experimental_Group__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Experimental Group</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Organization_Size__c.field-meta.xml
<CustomField>
    <fullName>Organization_Size__c</fullName>
    <description>Number of employees or students</description>
    <inlineHelpText>Number of employees or students</inlineHelpText>
    <label>Organization Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 - 99</fullName>
            </value>
            <value>
                <fullName>100 - 499</fullName>
            </value>
            <value>
                <fullName>500 - 999</fullName>
            </value>
            <value>
                <fullName>1000 - 4999</fullName>
            </value>
            <value>
                <fullName>5000+</fullName>
            </value>
            <value>
                <fullName>0</fullName>
                <isActive>false</isActive>
                <label>0</label>
            </value>
            <value>
                <fullName>1-99</fullName>
                <isActive>false</isActive>
                <label>1-99</label>
            </value>
            <value>
                <fullName>1/1/1999 12:00:00 AM</fullName>
                <isActive>false</isActive>
                <label>1/1/1999 12:00:00 AM</label>
            </value>
            <value>
                <fullName>10</fullName>
                <isActive>false</isActive>
                <label>10</label>
            </value>
            <value>
                <fullName>100 - 999</fullName>
                <isActive>false</isActive>
                <label>100 - 999</label>
            </value>
            <value>
                <fullName>100-499</fullName>
                <isActive>false</isActive>
                <label>100-499</label>
            </value>
            <value>
                <fullName>1000+</fullName>
                <isActive>false</isActive>
                <label>1000+</label>
            </value>
            <value>
                <fullName>1000-4999</fullName>
                <isActive>false</isActive>
                <label>1000-4999</label>
            </value>
            <value>
                <fullName>10000+</fullName>
                <isActive>false</isActive>
                <label>10000+</label>
            </value>
            <value>
                <fullName>11</fullName>
                <isActive>false</isActive>
                <label>11</label>
            </value>
            <value>
                <fullName>13</fullName>
                <isActive>false</isActive>
                <label>13</label>
            </value>
            <value>
                <fullName>200</fullName>
                <isActive>false</isActive>
                <label>200</label>
            </value>
            <value>
                <fullName>201-500</fullName>
                <isActive>false</isActive>
                <label>201-500</label>
            </value>
            <value>
                <fullName>21</fullName>
                <isActive>false</isActive>
                <label>21</label>
            </value>
            <value>
                <fullName>22</fullName>
                <isActive>false</isActive>
                <label>22</label>
            </value>
            <value>
                <fullName>29</fullName>
                <isActive>false</isActive>
                <label>29</label>
            </value>
            <value>
                <fullName>34</fullName>
                <isActive>false</isActive>
                <label>34</label>
            </value>
            <value>
                <fullName>36161</fullName>
                <isActive>false</isActive>
                <label>36161</label>
            </value>
            <value>
                <fullName>42</fullName>
                <isActive>false</isActive>
                <label>42</label>
            </value>
            <value>
                <fullName>495 - 1000</fullName>
                <isActive>false</isActive>
                <label>495 - 1000</label>
            </value>
            <value>
                <fullName>496 - 1000</fullName>
                <isActive>false</isActive>
                <label>496 - 1000</label>
            </value>
            <value>
                <fullName>497 - 1000</fullName>
                <isActive>false</isActive>
                <label>497 - 1000</label>
            </value>
            <value>
                <fullName>498 - 1000</fullName>
                <isActive>false</isActive>
                <label>498 - 1000</label>
            </value>
            <value>
                <fullName>499 - 1000</fullName>
                <isActive>false</isActive>
                <label>499 - 1000</label>
            </value>
            <value>
                <fullName>500 - 1000</fullName>
                <isActive>false</isActive>
                <label>500 - 1000</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <description>Account type for partners - resellers, referral partners, corporate partners</description>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/CampaignMember/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Campaign Members</relationshipLabel>
    <relationshipName>Campaign_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Campaign_Interaction_Date__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Interaction_Date__c</fullName>
    <inlineHelpText>When campaign member responded = true, the value of this field is automatically updated with new date/time to reflect response date. This value is used in calculating attribution</inlineHelpText>
    <label>Campaign Interaction Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/experimentId__c.field-meta.xml
<CustomField>
    <fullName>experimentId__c</fullName>
    <inlineHelpText>This field is used for Optimizely mapping for experiments run by the Growth team</inlineHelpText>
    <label>experimentId</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Google_GCLIDv2__c.field-meta.xml
<CustomField>
    <fullName>Google_GCLIDv2__c</fullName>
    <label>Google GCLID</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Third_Party_Vendor_Lead_ID__c.field-meta.xml
<CustomField>
    <fullName>Third_Party_Vendor_Lead_ID__c</fullName>
    <label>Third Party Vendor Lead ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/utm_campaign__c.field-meta.xml
<CustomField>
    <fullName>utm_campaign__c</fullName>
    <description>Field gets populated from the utm parameters of the link the customer clicked to land on a samsara page. These values are stored as cookies for 60 days in case the customer doesn&apos;t convert right away.</description>
    <label>utm_campaign</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/utm_content__c.field-meta.xml
<CustomField>
    <fullName>utm_content__c</fullName>
    <description>Field gets populated from the utm parameters of the link the customer clicked to land on a samsara page. These values are stored as cookies for 60 days in case the customer doesn&apos;t convert right away.</description>
    <label>utm_content</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/utm_ext_ad_id__c.field-meta.xml
<CustomField>
    <fullName>utm_ext_ad_id__c</fullName>
    <description>Id of the external ad (e.g Facebook ad id, AdWords ad id, etc).</description>
    <label>utm_ext_ad_id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/utm_ext_adset_id__c.field-meta.xml
<CustomField>
    <fullName>utm_ext_adset_id__c</fullName>
    <label>utm_ext_adset_id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/utm_ext_campaign_id__c.field-meta.xml
<CustomField>
    <fullName>utm_ext_campaign_id__c</fullName>
    <description>Unique id from the ad campaign used to join object against the ad platform.</description>
    <label>utm_ext_campaign_id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/utm_medium__c.field-meta.xml
<CustomField>
    <fullName>utm_medium__c</fullName>
    <description>Field gets populated from the utm parameters of the link the customer clicked to land on a samsara page. These values are stored as cookies for 60 days in case the customer doesn&apos;t convert right away.</description>
    <label>utm_medium</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/utm_source__c.field-meta.xml
<CustomField>
    <fullName>utm_source__c</fullName>
    <description>Field gets populated from the utm parameters of the link the customer clicked to land on a samsara page. These values are stored as cookies for 60 days in case the customer doesn&apos;t convert right away.</description>
    <label>utm_source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/utm_term__c.field-meta.xml
<CustomField>
    <fullName>utm_term__c</fullName>
    <description>Field gets populated from the utm parameters of the link the customer clicked to land on a samsara page. These values are stored as cookies for 60 days in case the customer doesn&apos;t convert right away.</description>
    <label>utm_term</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Campaign_to_Add__c.field-meta.xml
<CustomField>
    <fullName>Campaign_to_Add__c</fullName>
    <description>Populated via Lead conversion, a process builder picks up this field and inserts a campaignmember, which is used by the legacy round robin process.</description>
    <label>Campaign to Add</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Google_GCLIDv2__c.field-meta.xml
<CustomField>
    <fullName>Google_GCLIDv2__c</fullName>
    <label>Google GCLID</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Organization_Size__c.field-meta.xml
<CustomField>
    <fullName>Organization_Size__c</fullName>
    <formula>TEXT(Account.Organization_Size__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Please edit on the Account page.</inlineHelpText>
    <label>Organization Size</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Third_Party_Vendor_Lead_ID__c.field-meta.xml
<CustomField>
    <fullName>Third_Party_Vendor_Lead_ID__c</fullName>
    <label>Third Party Vendor Lead ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/utm_campaign__c.field-meta.xml
<CustomField>
    <fullName>utm_campaign__c</fullName>
    <description>utm parameter for campaign name</description>
    <label>utm_campaign</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/utm_campaign_append__c.field-meta.xml
<CustomField>
    <fullName>utm_campaign_append__c</fullName>
    <label>utm campaign append</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/utm_content__c.field-meta.xml
<CustomField>
    <fullName>utm_content__c</fullName>
    <description>utm_content info for a campaign</description>
    <label>utm_content</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/utm_content_append__c.field-meta.xml
<CustomField>
    <fullName>utm_content_append__c</fullName>
    <label>utm content append</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/utm_ext_ad_id__c.field-meta.xml
<CustomField>
    <fullName>utm_ext_ad_id__c</fullName>
    <description>Id of the external ad (e.g Facebook ad id, AdWords ad id, etc).</description>
    <label>utm_ext_ad_id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/utm_ext_adset_id__c.field-meta.xml
<CustomField>
    <fullName>utm_ext_adset_id__c</fullName>
    <label>utm_ext_adset_id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/utm_medium__c.field-meta.xml
<CustomField>
    <fullName>utm_medium__c</fullName>
    <description>utm_medium for a campaign</description>
    <label>utm_medium</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/utm_medium_append__c.field-meta.xml
<CustomField>
    <fullName>utm_medium_append__c</fullName>
    <label>utm medium append</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/utm_source__c.field-meta.xml
<CustomField>
    <fullName>utm_source__c</fullName>
    <description>utm_source for marketing campaigns</description>
    <label>utm_source</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/utm_source_append__c.field-meta.xml
<CustomField>
    <fullName>utm_source_append__c</fullName>
    <description>Used to append the utm source field on contacts.</description>
    <label>utm source append</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/utm_term__c.field-meta.xml
<CustomField>
    <fullName>utm_term__c</fullName>
    <description>utm_term for marketing campaigns</description>
    <label>utm_term</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/utm_term_append__c.field-meta.xml
<CustomField>
    <fullName>utm_term_append__c</fullName>
    <label>utm term append</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <description>Partner contacts</description>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/Slack_Enabled_Campaign_Type__mdt/Slack_Enabled_Campaign_Type__mdt.object-meta.xml
<CustomObject>
    <label>Slack Enabled Campaign Type</label>
    <pluralLabel>Slack Enabled Campaign Types</pluralLabel>
</CustomObject>

force-app/main/default/objects/Slack_Enabled_Campaign_Type__mdt/fields/Campaign_Member_Update_Types__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Member_Update_Types__c</fullName>
    <label>Campaign Member Update Types</label>
    <length>1200</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/CampaigntoAdd_Test.cls
@isTest  (SeeAllData=false)
public class CampaigntoAdd_Test {
    /*@testSetup
    private static void testDataSetup() {
        Slack_Enabled_Campaign_Type__mdt mdt = new Slack_Enabled_Campaign_Type__mdt(Campaign_Member_Update_Types__c='Website - Form,Partner');
    }*/
     @isTest
    private static void test1() {
        String manualSource = 'true';
        DateTime now;
         Map<Id, Boolean> yoyoContactMap;
         Map<Id, Id> contactToCampaignId = new Map<Id, Id>();
             
   List<Account> newAccount = new List<Account>();
        Account acc = new Account (Name = 'Test Account', Organization_Size__c = '5000+', BillingCountry = 'Canada', Industry = 'Other');
        newAccount.add(acc);   
        insert newAccount;

   List<Contact> newContacts = new List<Contact>();
   Campaign c = new Campaign();
   c.Name = 'TestCampaign TestCampaign TestCampai';
   c.Type = 'Website - Form';
   insert c;
   Campaign c1 = new Campaign();
   c1.Name = 'TestCampaign TestCampaign TestCampai';
   c1.Type = 'Website Field Event';
   insert c1;
        Map<Id, Contact> contactMap = new Map<Id, Contact>();
       //Contact contact = [select id,Campaign_to_Add__c,FirstName,LastName,Email from Contact limit 1 ];
        Contact con = new Contact (FirstName = 'User', LastName = 'Tester', Email = 'test@test.com', AccountId=acc.Id , Campaign_to_Add__c=c.Id);
        newContacts.add(con);  
        Contact con1 = new Contact (FirstName = 'User1', LastName = 'Tester1', Email = 'test1@test.com', AccountId=acc.Id , Campaign_to_Add__c='1234567890');
        newContacts.add(con1);
        insert newContacts;
        contactMap.put(con.id,con);
    	//contactMap.put(con1.id,con1);
    List<CampaignMember> cmList = new list<CampaignMember>();
     CampaignMember cmem = new CampaignMember();
    cmem.Account__c = con.AccountId;
    cmem.ContactId = con.id;
    cmem.CampaignId = c.Id;
        cmem.utm_campaign__c =  con.utm_campaign_append__c;
                cmem.utm_content__c = con.utm_content_append__c;
                cmem.utm_ext_ad_id__c = con.utm_ext_ad_id__c;
                cmem.utm_ext_adset_id__c = con.utm_ext_adset_id__c;
                cmem.utm_ext_campaign_id__c = con.utm_ext_campaign_id__c;
                cmem.utm_medium__c = con.utm_medium_append__c;
                cmem.utm_source__c = con.utm_source_append__c;
                cmem.utm_term__c = con.utm_term_append__c;
                cmem.Campaign_Interaction_Date__c = System.now();
                cmem.Third_Party_Vendor_Lead_ID__c=con.Third_Party_Vendor_Lead_ID__c;
                cmem.Google_GCLIDv2__c = con.Google_GCLIDv2__c;
                cmem.experimentId__c = con.experimentId__c;
                cmem.Experimental_Group__c = con.Experimental_Group__c;
                cmem.Lead_Funnel_Trigger_Start__c = con.Lead_Funnel_Trigger_Start__c;
                cmem.Lead_Funnel_RDS_DB_Insert__c = con.Lead_Funnel_RDS_DB_Insert__c;
                cmem.Microsoft_MSCLKID__c = con.Microsoft_MSCLIKID__c;
                cmem.Personalization_Experiment_Id__c = con.Personalization_Experiment_Id__c;

                cmList.add(cmem);
        
        CampaignMember cmem1 = new CampaignMember();
    cmem1.Account__c = con.AccountId;
    cmem1.ContactId = con.id;
    cmem1.CampaignId = c1.Id;
        cmem1.utm_campaign__c =  con.utm_campaign_append__c;
                cmem1.utm_content__c = con.utm_content_append__c;
                cmem1.utm_ext_ad_id__c = con.utm_ext_ad_id__c;
                cmem1.utm_ext_adset_id__c = con.utm_ext_adset_id__c;
                cmem1.utm_ext_campaign_id__c = con.utm_ext_campaign_id__c;
                cmem1.utm_medium__c = con.utm_medium_append__c;
                cmem1.utm_source__c = con.utm_source_append__c;
                cmem1.utm_term__c = con.utm_term_append__c;
                cmem1.Campaign_Interaction_Date__c = System.now();
                cmem1.Third_Party_Vendor_Lead_ID__c=con.Third_Party_Vendor_Lead_ID__c;
                cmem1.Google_GCLIDv2__c = con.Google_GCLIDv2__c;
                cmem1.experimentId__c = con.experimentId__c;
                cmem1.Experimental_Group__c = con.Experimental_Group__c;
                cmem1.Lead_Funnel_Trigger_Start__c = con.Lead_Funnel_Trigger_Start__c;
                cmem1.Lead_Funnel_RDS_DB_Insert__c = con.Lead_Funnel_RDS_DB_Insert__c;
                cmem1.Microsoft_MSCLKID__c = con.Microsoft_MSCLIKID__c;
                cmem1.Personalization_Experiment_Id__c = con.Personalization_Experiment_Id__c;

                cmList.add(cmem1);
        
        insert cmList;
        contactToCampaignId.put(cmem.id,con.Id);
        contactToCampaignId.put(cmem1.id,con.Id);
        Map<Id, String> conIdCampName = new Map<Id, String>();
        conIdCampName.put(con.Id, c.Name);
        Map<Id, Campaign> campaignNamesToBeAddedMap = new Map<Id, Campaign>();
        campaignNamesToBeAddedMap.put(con.Id,c);
        
        con.Campaign_to_Add__c = c1.Id;
        Map<Id, Contact> oldContactById = new Map<Id,Contact>();
        oldContactById.put(con.Id,con);
        //system.debug('values' +contactMap +manualSource +now +yoyoContactMap +contactToCampaignId);
         Test.startTest(); 
        CampaigntoAdd.CampaigntoAdd(contactMap, manualSource, now, yoyoContactMap, contactToCampaignId);
        CampaigntoAdd.createRepeatCampaign(campaignNamesToBeAddedMap,conIdCampName);
        CampaigntoAdd.CampaignMemberCheckFuture(oldContactById , contactMap, manualSource, yoyoContactMap, now);
        CampaigntoAdd.CampaigntoAdd(contactMap, manualSource, now, yoyoContactMap, null);
        
         Test.stopTest();
     
    }
    
	@isTest
    private static void test2() {
        String manualSource = 'true';
        DateTime now;
         Map<Id, Boolean> yoyoContactMap;
         Map<Id, Id> contactToCampaignId = new Map<Id, Id>();
             
   List<Account> newAccount = new List<Account>();
        Account acc = new Account (Name = 'Test Account', Organization_Size__c = '5000+', BillingCountry = 'Canada', Industry = 'Other');
        newAccount.add(acc);   
        insert newAccount;

   List<Contact> newContacts = new List<Contact>();
   Campaign c = new Campaign();
   c.Name = 'TestCampaign TestCampaign TestCampai';
   c.Type = 'Website Field Event';
   insert c;
   Campaign c1 = new Campaign();
   c1.Name = 'TestCampaign TestCampaign TestCampai';
   c1.Type = 'Field Event';
   insert c1;
        Map<Id, Contact> contactMap = new Map<Id, Contact>();
       //Contact contact = [select id,Campaign_to_Add__c,FirstName,LastName,Email from Contact limit 1 ];
        Contact con = new Contact (FirstName = 'User', LastName = 'Tester', Email = 'test@test.com', AccountId=acc.Id , Campaign_to_Add__c=c.Id);
        newContacts.add(con);  
        Contact con1 = new Contact (FirstName = 'User1', LastName = 'Tester1', Email = 'test1@test.com', AccountId=acc.Id , Campaign_to_Add__c='1234567890');
        newContacts.add(con1);
        insert newContacts;
        contactMap.put(con.id,con);
    	//contactMap.put(con1.id,con1);
    List<CampaignMember> cmList = new list<CampaignMember>();
     CampaignMember cmem = new CampaignMember();
    cmem.Account__c = con.AccountId;
    cmem.ContactId = con.id;
    cmem.CampaignId = c.Id;
        cmem.utm_campaign__c =  con.utm_campaign_append__c;
                cmem.utm_content__c = con.utm_content_append__c;
                cmem.utm_ext_ad_id__c = con.utm_ext_ad_id__c;
                cmem.utm_ext_adset_id__c = con.utm_ext_adset_id__c;
                cmem.utm_ext_campaign_id__c = con.utm_ext_campaign_id__c;
                cmem.utm_medium__c = con.utm_medium_append__c;
                cmem.utm_source__c = con.utm_source_append__c;
                cmem.utm_term__c = con.utm_term_append__c;
                cmem.Campaign_Interaction_Date__c = System.now();
                cmem.Third_Party_Vendor_Lead_ID__c=con.Third_Party_Vendor_Lead_ID__c;
                cmem.Google_GCLIDv2__c = con.Google_GCLIDv2__c;
                cmem.experimentId__c = con.experimentId__c;
                cmem.Experimental_Group__c = con.Experimental_Group__c;
                cmem.Lead_Funnel_Trigger_Start__c = con.Lead_Funnel_Trigger_Start__c;
                cmem.Lead_Funnel_RDS_DB_Insert__c = con.Lead_Funnel_RDS_DB_Insert__c;
                cmem.Microsoft_MSCLKID__c = con.Microsoft_MSCLIKID__c;
                cmem.Personalization_Experiment_Id__c = con.Personalization_Experiment_Id__c;

                cmList.add(cmem);
        insert cmList;
        contactToCampaignId.put(cmem.id,con.Id);
        Map<Id, String> conIdCampName = new Map<Id, String>();
        conIdCampName.put(con.Id, c.Name);
        Map<Id, Campaign> campaignNamesToBeAddedMap = new Map<Id, Campaign>();
        campaignNamesToBeAddedMap.put(con.Id,c);
        
        con.Campaign_to_Add__c = c1.Id;
        Map<Id, Contact> oldContactById = new Map<Id,Contact>();
        oldContactById.put(con.Id,con);
        //system.debug('values' +contactMap +manualSource +now +yoyoContactMap +contactToCampaignId);
         Test.startTest(); 
        CampaigntoAdd.CampaigntoAdd(contactMap, manualSource, now, yoyoContactMap, contactToCampaignId);
        CampaigntoAdd.createRepeatCampaign(campaignNamesToBeAddedMap,conIdCampName);
        CampaigntoAdd.CampaignMemberCheckFuture(oldContactById , contactMap, manualSource, yoyoContactMap, now);
        CampaigntoAdd.CampaigntoAdd(contactMap, manualSource, now, yoyoContactMap, null);
        
         Test.stopTest();
     
    }
    
    @isTest
    private static void test3() {
        String manualSource = 'true';
        DateTime now;
         Map<Id, Boolean> yoyoContactMap;
         Map<Id, Id> contactToCampaignId = new Map<Id, Id>();
             
   List<Account> newAccount = new List<Account>();
        Account acc = new Account (Name = 'Test Account', Organization_Size__c = '5000+', BillingCountry = 'Canada', Industry = 'Other');
        newAccount.add(acc);   
        insert newAccount;

   List<Contact> newContacts = new List<Contact>();
   Campaign c = new Campaign();
   c.Name = 'TestCampaign TestCampaign TestCampai';
   c.Type = 'Field Event';
   insert c;
   Campaign c1 = new Campaign();
   c1.Name = 'TestCampaign TestCampaign TestCampai';
   c1.Type = 'Website - Form';
   insert c1;
        Map<Id, Contact> contactMap = new Map<Id, Contact>();
       //Contact contact = [select id,Campaign_to_Add__c,FirstName,LastName,Email from Contact limit 1 ];
        Contact con = new Contact (FirstName = 'User', LastName = 'Tester', Email = 'test@test.com', AccountId=acc.Id , Campaign_to_Add__c=c.Id);
        newContacts.add(con);  
        Contact con1 = new Contact (FirstName = 'User1', LastName = 'Tester1', Email = 'test1@test.com', AccountId=acc.Id , Campaign_to_Add__c='1234567890');
        newContacts.add(con1);
        insert newContacts;
        contactMap.put(con.id,con);
    	//contactMap.put(con1.id,con1);
    List<CampaignMember> cmList = new list<CampaignMember>();
     CampaignMember cmem = new CampaignMember();
    cmem.Account__c = con.AccountId;
    cmem.ContactId = con.id;
    cmem.CampaignId = c.Id;
        cmem.utm_campaign__c =  con.utm_campaign_append__c;
                cmem.utm_content__c = con.utm_content_append__c;
                cmem.utm_ext_ad_id__c = con.utm_ext_ad_id__c;
                cmem.utm_ext_adset_id__c = con.utm_ext_adset_id__c;
                cmem.utm_ext_campaign_id__c = con.utm_ext_campaign_id__c;
                cmem.utm_medium__c = con.utm_medium_append__c;
                cmem.utm_source__c = con.utm_source_append__c;
                cmem.utm_term__c = con.utm_term_append__c;
                cmem.Campaign_Interaction_Date__c = System.now();
                cmem.Third_Party_Vendor_Lead_ID__c=con.Third_Party_Vendor_Lead_ID__c;
                cmem.Google_GCLIDv2__c = con.Google_GCLIDv2__c;
                cmem.experimentId__c = con.experimentId__c;
                cmem.Experimental_Group__c = con.Experimental_Group__c;
                cmem.Lead_Funnel_Trigger_Start__c = con.Lead_Funnel_Trigger_Start__c;
                cmem.Lead_Funnel_RDS_DB_Insert__c = con.Lead_Funnel_RDS_DB_Insert__c;
                cmem.Microsoft_MSCLKID__c = con.Microsoft_MSCLIKID__c;
                cmem.Personalization_Experiment_Id__c = con.Personalization_Experiment_Id__c;

                cmList.add(cmem);
        insert cmList;
        contactToCampaignId.put(cmem.id,con.Id);
        Map<Id, String> conIdCampName = new Map<Id, String>();
        conIdCampName.put(con.Id, c.Name);
        Map<Id, Campaign> campaignNamesToBeAddedMap = new Map<Id, Campaign>();
        campaignNamesToBeAddedMap.put(con.Id,c);
        
        con.Campaign_to_Add__c = c1.Id;
        Map<Id, Contact> oldContactById = new Map<Id,Contact>();
        oldContactById.put(con.Id,con);
        //system.debug('values' +contactMap +manualSource +now +yoyoContactMap +contactToCampaignId);
         Test.startTest(); 
        CampaigntoAdd.CampaigntoAdd(contactMap, manualSource, now, yoyoContactMap, contactToCampaignId);
        CampaigntoAdd.createRepeatCampaign(campaignNamesToBeAddedMap,conIdCampName);
        CampaigntoAdd.CampaignMemberCheckFuture(oldContactById , contactMap, manualSource, yoyoContactMap, now);
        CampaigntoAdd.CampaigntoAdd(contactMap, manualSource, now, yoyoContactMap, null);
        
         Test.stopTest();
     
    }
}