force-app/main/default/objects/Account/fields/Initiate_Round_Robin__c.field-meta.xml
<CustomField>
    <fullName>Initiate_Round_Robin__c</fullName>
    <defaultValue>false</defaultValue>
    <description>GTMS-11254</description>
    <label>Initiate Round Robin</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Most_Recent_Source__c.field-meta.xml
<CustomField>
    <fullName>Most_Recent_Source__c</fullName>
    <description>Populated by the most recent lead that converts/merges into this account (or a contact under this account).</description>
    <label>Most Recent Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Open_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Open_Opportunity__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked via DLRS if there is at least one currently open opportunity on the account.</description>
    <label>Open Opportunity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Organization_Size__c.field-meta.xml
<CustomField>
    <fullName>Organization_Size__c</fullName>
    <description>Number of employees or students</description>
    <inlineHelpText>Number of employees or students</inlineHelpText>
    <label>Organization Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 - 99</fullName>
            </value>
            <value>
                <fullName>100 - 499</fullName>
            </value>
            <value>
                <fullName>500 - 999</fullName>
            </value>
            <value>
                <fullName>1000 - 4999</fullName>
            </value>
            <value>
                <fullName>5000+</fullName>
            </value>
            <value>
                <fullName>0</fullName>
                <isActive>false</isActive>
                <label>0</label>
            </value>
            <value>
                <fullName>1-99</fullName>
                <isActive>false</isActive>
                <label>1-99</label>
            </value>
            <value>
                <fullName>1/1/1999 12:00:00 AM</fullName>
                <isActive>false</isActive>
                <label>1/1/1999 12:00:00 AM</label>
            </value>
            <value>
                <fullName>10</fullName>
                <isActive>false</isActive>
                <label>10</label>
            </value>
            <value>
                <fullName>100 - 999</fullName>
                <isActive>false</isActive>
                <label>100 - 999</label>
            </value>
            <value>
                <fullName>100-499</fullName>
                <isActive>false</isActive>
                <label>100-499</label>
            </value>
            <value>
                <fullName>1000+</fullName>
                <isActive>false</isActive>
                <label>1000+</label>
            </value>
            <value>
                <fullName>1000-4999</fullName>
                <isActive>false</isActive>
                <label>1000-4999</label>
            </value>
            <value>
                <fullName>10000+</fullName>
                <isActive>false</isActive>
                <label>10000+</label>
            </value>
            <value>
                <fullName>11</fullName>
                <isActive>false</isActive>
                <label>11</label>
            </value>
            <value>
                <fullName>13</fullName>
                <isActive>false</isActive>
                <label>13</label>
            </value>
            <value>
                <fullName>200</fullName>
                <isActive>false</isActive>
                <label>200</label>
            </value>
            <value>
                <fullName>201-500</fullName>
                <isActive>false</isActive>
                <label>201-500</label>
            </value>
            <value>
                <fullName>21</fullName>
                <isActive>false</isActive>
                <label>21</label>
            </value>
            <value>
                <fullName>22</fullName>
                <isActive>false</isActive>
                <label>22</label>
            </value>
            <value>
                <fullName>29</fullName>
                <isActive>false</isActive>
                <label>29</label>
            </value>
            <value>
                <fullName>34</fullName>
                <isActive>false</isActive>
                <label>34</label>
            </value>
            <value>
                <fullName>36161</fullName>
                <isActive>false</isActive>
                <label>36161</label>
            </value>
            <value>
                <fullName>42</fullName>
                <isActive>false</isActive>
                <label>42</label>
            </value>
            <value>
                <fullName>495 - 1000</fullName>
                <isActive>false</isActive>
                <label>495 - 1000</label>
            </value>
            <value>
                <fullName>496 - 1000</fullName>
                <isActive>false</isActive>
                <label>496 - 1000</label>
            </value>
            <value>
                <fullName>497 - 1000</fullName>
                <isActive>false</isActive>
                <label>497 - 1000</label>
            </value>
            <value>
                <fullName>498 - 1000</fullName>
                <isActive>false</isActive>
                <label>498 - 1000</label>
            </value>
            <value>
                <fullName>499 - 1000</fullName>
                <isActive>false</isActive>
                <label>499 - 1000</label>
            </value>
            <value>
                <fullName>500 - 1000</fullName>
                <isActive>false</isActive>
                <label>500 - 1000</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/RR_Assign_Region_Owner__c.field-meta.xml
<CustomField>
    <fullName>RR_Assign_Region_Owner__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Assign Region Owner</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Fleet.recordType-meta.xml
<RecordType>
    <fullName>Fleet</fullName>
    <active>true</active>
    <description>Fleet account</description>
    <label>Fleet</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Industrial.recordType-meta.xml
<RecordType>
    <fullName>Industrial</fullName>
    <active>true</active>
    <description>Industrial account</description>
    <label>Industrial</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Manufacturer.recordType-meta.xml
<RecordType>
    <fullName>Manufacturer</fullName>
    <active>true</active>
    <description>Samsara Supply Chain</description>
    <label>Manufacturer</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Channel_Source__c.field-meta.xml
<CustomField>
    <fullName>Channel_Source__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Field used to demarcate if inbound lead comes from our Channel partners. Automatically cleared once the lead is converted to Contact</inlineHelpText>
    <label>Channel Source</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Most_Recent_Source__c.field-meta.xml
<CustomField>
    <fullName>Most_Recent_Source__c</fullName>
    <label>Most Recent Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/New_Inbound_Lead__c.field-meta.xml
<CustomField>
    <fullName>New_Inbound_Lead__c</fullName>
    <defaultValue>false</defaultValue>
    <label>New Inbound Lead</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Organization_Size__c.field-meta.xml
<CustomField>
    <fullName>Organization_Size__c</fullName>
    <formula>TEXT(Account.Organization_Size__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Please edit on the Account page.</inlineHelpText>
    <label>Organization Size</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Fleet.recordType-meta.xml
<RecordType>
    <fullName>Fleet</fullName>
    <active>true</active>
    <description>Fleet contact</description>
    <label>Fleet</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Industrial.recordType-meta.xml
<RecordType>
    <fullName>Industrial</fullName>
    <active>true</active>
    <description>Industrial Contact. Allows us to create intentional dupes for fleet and industrial contacts.</description>
    <label>Industrial</label>
</RecordType>

force-app/main/default/objects/User/fields/RR_Is_Pool_User__c.field-meta.xml
<CustomField>
    <fullName>RR_Is_Pool_User__c</fullName>
    <defaultValue>false</defaultValue>
    <description>added for GTMS-13168</description>
    <label>Is Pool User</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/GS_ContactInboundOrChannelServiceTest.cls
@isTest
public class GS_ContactInboundOrChannelServiceTest {
    @isTest
    static void testNewInboundOrChannel() {
         Profile testProfile = [SELECT Id FROM Profile WHERE Name = 'Samsara Inbound ADRs']; // Adjust profile name as needed
       // UserRole testRole = [SELECT Id FROM UserRole WHERE Name = 'Some Role']; // Adjust role name as needed
        User u = new User(lastName = 'blah',
                          email = 'uniqueName' + '@test' +'.org',
                          Username = 'u' + '@test' + '.org',
                          EmailEncodingKey = 'ISO-8859-1',
                          Alias = 'qwer',
                          TimeZoneSidKey = 'America/Los_Angeles',
                          LocaleSidKey = 'en_US',
                          LanguageLocaleKey = 'en_US',
                          ProfileId = testProfile.Id,
                          EmployeeNumber='123',
                         RR_Is_Pool_User__c=true);
        insert u;
        
        // Create test data for Contact and Account
        Account testAccount = new Account(Name = 'Test Account', Organization_Size__c = '1000 - 4999', BillingCountry = 'United States', BillingState='California', Industry = 'Other',Open_Opportunity__c=false,Initiate_Round_Robin__c=false,
                                         RecordTypeId  = Schema.SObjectType.account.getRecordTypeInfosByName().get('Industrial').getRecordTypeId());
        insert testAccount;
        
        Contact testContact1 = new Contact(
            FirstName = 'John',
            LastName = 'Doe',
            AccountId = testAccount.Id,
            New_Inbound_Lead__c = true,
            Most_Recent_Source__c = 'test'
        );
        Contact testContact2 = new Contact(
            FirstName = 'Jane',
            LastName = 'Smith',
            AccountId = testAccount.Id,
            Channel_Source__c = true,
            Most_Recent_Source__c = 'test'
        );
        List<Contact> newContactList = new List<Contact>{testContact1, testContact2};
        insert newContactList;

        // Create an instance of the GS_ContactCacheService class (you may need to mock this)
        GS_ContactCacheService contactCache = new GS_ContactCacheService();

        // Create an instance of the GS_ContactInboundOrChannelService class
        GS_ContactInboundOrChannelService service = new GS_ContactInboundOrChannelService();

        // Call the newInboundOrChannel method
        Test.startTest();
        service.newInboundOrChannel(newContactList, new Map<Id, Contact>(), contactCache);
        Test.stopTest();

        // Perform assertions to verify the expected behavior
        // You can assert the values in the Account records and any other expected outcomes
        // Example: Account updated fields should match your expected values
        Account updatedAccount = [SELECT Id, Most_Recent_Source__c FROM Account WHERE Id = :testAccount.Id];
        //System.assertEquals('Expected Source', updatedAccount.Most_Recent_Source__c);

        // You can add more assertions based on your specific requirements
    }
    @isTest
    static void testMethod002() {
         Profile testProfile = [SELECT Id FROM Profile WHERE Name = 'Samsara Inbound ADRs']; // Adjust profile name as needed
         UserRole testRole = [SELECT Id FROM UserRole WHERE Name = 'Fleet ADR IB NA US Team 8']; // Adjust role name as needed
        User u = new User(lastName = 'blah',
                          email = 'uniqueName' + '@test' +'.org',
                          Username = 'u' + '@test' + '.org',
                          EmailEncodingKey = 'ISO-8859-1',
                          Alias = 'qwer',
                          TimeZoneSidKey = 'America/Los_Angeles',
                          LocaleSidKey = 'en_US',
                          LanguageLocaleKey = 'en_US',
                          ProfileId = testProfile.Id,
                          UserRoleId = testRole.Id,
                          EmployeeNumber='123',
                         RR_Is_Pool_User__c=true);
        insert u;
        
        // Create test data for Contact and Account
        List<Contact> newContactList = new List<Contact>();
        Account testAccount = new Account();
        system.runAs(u)
        {
            testAccount = new Account(Name = 'Test Account', Organization_Size__c = '1000 - 4999', BillingCountry = 'United States', BillingState='California', Industry = 'Other',Open_Opportunity__c=false,Initiate_Round_Robin__c=false,
                                              RecordTypeId  = Schema.SObjectType.account.getRecordTypeInfosByName().get('Industrial').getRecordTypeId(),RR_Assign_Region_Owner__c=false);
            insert testAccount;
            
            Contact testContact1 = new Contact(
                FirstName = 'John',
                LastName = 'Doe',
                AccountId = testAccount.Id,
                New_Inbound_Lead__c = true,
                Most_Recent_Source__c = 'test'
            );
            Contact testContact2 = new Contact(
                FirstName = 'Jane',
                LastName = 'Smith',
                AccountId = testAccount.Id,
                Most_Recent_Source__c = 'test'
            );
            newContactList = new List<Contact>{testContact1, testContact2};
                insert newContactList;
        }
        

        // Create an instance of the GS_ContactCacheService class (you may need to mock this)
        GS_ContactCacheService contactCache = new GS_ContactCacheService();

        // Create an instance of the GS_ContactInboundOrChannelService class
        GS_ContactInboundOrChannelService service = new GS_ContactInboundOrChannelService();

        // Call the newInboundOrChannel method
        Test.startTest();
        service.newInboundOrChannel(newContactList, new Map<Id, Contact>(), contactCache);
        Test.stopTest();

        // Perform assertions to verify the expected behavior
        // You can assert the values in the Account records and any other expected outcomes
        // Example: Account updated fields should match your expected values
        Account updatedAccount = [SELECT Id, Most_Recent_Source__c FROM Account WHERE Id = :testAccount.Id];
        //System.assertEquals('Expected Source', updatedAccount.Most_Recent_Source__c);

        // You can add more assertions based on your specific requirements
    }
    @isTest
    static void testMethod003() {
         Profile testProfile = [SELECT Id FROM Profile WHERE Name = 'Samsara Inbound ADRs']; // Adjust profile name as needed
         UserRole testRole = [SELECT Id FROM UserRole WHERE Name = 'Fleet ADR IB NA US Team 8']; // Adjust role name as needed
        User u = new User(lastName = 'blah',
                          email = 'uniqueName' + '@test' +'.org',
                          Username = 'u' + '@test' + '.org',
                          EmailEncodingKey = 'ISO-8859-1',
                          Alias = 'qwer',
                          TimeZoneSidKey = 'America/Los_Angeles',
                          LocaleSidKey = 'en_US',
                          LanguageLocaleKey = 'en_US',
                          ProfileId = testProfile.Id,
                          UserRoleId = testRole.Id,
                          EmployeeNumber='123',
                         RR_Is_Pool_User__c=true);
        insert u;
        
        // Create test data for Contact and Account
        List<Contact> newContactList = new List<Contact>();
        Account testAccount = new Account();
        system.runAs(u)
        {
            testAccount = new Account(Name = 'Test Account', Organization_Size__c = '1000 - 4999', BillingCountry = 'United States', BillingState='California', Industry = 'Other',Open_Opportunity__c=false,Initiate_Round_Robin__c=false,
                                              RecordTypeId  = Schema.SObjectType.account.getRecordTypeInfosByName().get('Industrial').getRecordTypeId(),RR_Assign_Region_Owner__c=false);
            insert testAccount;
            
            Contact testContact1 = new Contact(
                FirstName = 'John',
                LastName = 'Doe',
                AccountId = testAccount.Id,
                New_Inbound_Lead__c = true,
                Most_Recent_Source__c = 'test'
            );
            Contact testContact2 = new Contact(
                FirstName = 'Jane',
                LastName = 'Smith',
                AccountId = testAccount.Id,
            Channel_Source__c = true,
                Most_Recent_Source__c = 'test'
            );
            newContactList = new List<Contact>{testContact1, testContact2};
                insert newContactList;
        }
        

        // Create an instance of the GS_ContactCacheService class (you may need to mock this)
        GS_ContactCacheService contactCache = new GS_ContactCacheService();

        // Create an instance of the GS_ContactInboundOrChannelService class
        GS_ContactInboundOrChannelService service = new GS_ContactInboundOrChannelService();

        // Call the newInboundOrChannel method
        Test.startTest();
        service.newInboundOrChannel(newContactList, new Map<Id, Contact>(), contactCache);
        Test.stopTest();

        // Perform assertions to verify the expected behavior
        // You can assert the values in the Account records and any other expected outcomes
        // Example: Account updated fields should match your expected values
        Account updatedAccount = [SELECT Id, Most_Recent_Source__c FROM Account WHERE Id = :testAccount.Id];
        //System.assertEquals('Expected Source', updatedAccount.Most_Recent_Source__c);

        // You can add more assertions based on your specific requirements
    }
    @isTest
    static void testMethod004() {
         Profile testProfile = [SELECT Id FROM Profile WHERE Name = 'Samsara Inbound ADRs']; // Adjust profile name as needed
         UserRole testRole = [SELECT Id FROM UserRole WHERE Name = 'Fleet ADR IB NA US Team 8']; // Adjust role name as needed
        User u = new User(lastName = 'blah',
                          email = 'uniqueName' + '@test' +'.org',
                          Username = 'u' + '@test' + '.org',
                          EmailEncodingKey = 'ISO-8859-1',
                          Alias = 'qwer',
                          TimeZoneSidKey = 'America/Los_Angeles',
                          LocaleSidKey = 'en_US',
                          LanguageLocaleKey = 'en_US',
                          ProfileId = testProfile.Id,
                          UserRoleId = testRole.Id,
                          EmployeeNumber='123',
                         RR_Is_Pool_User__c=true);
        insert u;
        
        // Create test data for Contact and Account
        List<Contact> newContactList = new List<Contact>();
        Account testAccount = new Account();
        system.runAs(u)
        {
            testAccount = new Account(Name = 'Test Account', Organization_Size__c = '1 - 99', BillingCountry = 'United States', BillingState='California', Industry = 'Other',Open_Opportunity__c=false,Initiate_Round_Robin__c=false,
                                              RecordTypeId  = Schema.SObjectType.account.getRecordTypeInfosByName().get('Industrial').getRecordTypeId(),RR_Assign_Region_Owner__c=false);
            insert testAccount;
            
            Contact testContact1 = new Contact(
                FirstName = 'John',
                LastName = 'Doe',
                AccountId = testAccount.Id,
                New_Inbound_Lead__c = true,
                Most_Recent_Source__c = 'test'
            );
            Contact testContact2 = new Contact(
                FirstName = 'Jane',
                LastName = 'Smith',
                AccountId = testAccount.Id,
            Channel_Source__c = true,
                Most_Recent_Source__c = 'test'
            );
            newContactList = new List<Contact>{testContact1, testContact2};
                insert newContactList;
        }
        

        // Create an instance of the GS_ContactCacheService class (you may need to mock this)
        GS_ContactCacheService contactCache = new GS_ContactCacheService();

        // Create an instance of the GS_ContactInboundOrChannelService class
        GS_ContactInboundOrChannelService service = new GS_ContactInboundOrChannelService();

        // Call the newInboundOrChannel method
        Test.startTest();
        service.newInboundOrChannel(newContactList, new Map<Id, Contact>(), contactCache);
        Test.stopTest();

        // Perform assertions to verify the expected behavior
        // You can assert the values in the Account records and any other expected outcomes
        // Example: Account updated fields should match your expected values
        Account updatedAccount = [SELECT Id, Most_Recent_Source__c FROM Account WHERE Id = :testAccount.Id];
        //System.assertEquals('Expected Source', updatedAccount.Most_Recent_Source__c);

        // You can add more assertions based on your specific requirements
    }
    
    @isTest
    static void testMethod005() {
         Profile testProfile = [SELECT Id FROM Profile WHERE Name = 'Samsara Inbound ADRs']; // Adjust profile name as needed
         UserRole testRole = [SELECT Id FROM UserRole WHERE Name = 'Fleet ADR IB NA US Team 8']; // Adjust role name as needed
        User u = new User(lastName = 'blah',
                          email = 'uniqueName' + '@test' +'.org',
                          Username = 'u' + '@test' + '.org',
                          EmailEncodingKey = 'ISO-8859-1',
                          Alias = 'qwer',
                          TimeZoneSidKey = 'America/Los_Angeles',
                          LocaleSidKey = 'en_US',
                          LanguageLocaleKey = 'en_US',
                          ProfileId = testProfile.Id,
                          UserRoleId = testRole.Id,
                          EmployeeNumber='123',
                         RR_Is_Pool_User__c=true);
        insert u;
        
        // Create test data for Contact and Account
        List<Contact> newContactList = new List<Contact>();
        Account testAccount = new Account();
        system.runAs(u)
        {
            testAccount = new Account(Name = 'Test Account', Organization_Size__c = '1 - 99', BillingCountry = 'United States', BillingState='California', Industry = 'Other',Open_Opportunity__c=false,Initiate_Round_Robin__c=false,
                                              RecordTypeId  = Schema.SObjectType.account.getRecordTypeInfosByName().get('Manufacturer').getRecordTypeId(),RR_Assign_Region_Owner__c=false);
            insert testAccount;
            
            Contact testContact1 = new Contact(
                FirstName = 'John',
                LastName = 'Doe',
                AccountId = testAccount.Id,
                New_Inbound_Lead__c = true,
                Most_Recent_Source__c = 'test'
            );
            Contact testContact2 = new Contact(
                FirstName = 'Jane',
                LastName = 'Smith',
                AccountId = testAccount.Id,
            Channel_Source__c = true,
                Most_Recent_Source__c = 'test'
            );
            newContactList = new List<Contact>{testContact1, testContact2};
                insert newContactList;
        }
        

        // Create an instance of the GS_ContactCacheService class (you may need to mock this)
        GS_ContactCacheService contactCache = new GS_ContactCacheService();

        // Create an instance of the GS_ContactInboundOrChannelService class
        GS_ContactInboundOrChannelService service = new GS_ContactInboundOrChannelService();

        // Call the newInboundOrChannel method
        Test.startTest();
        service.newInboundOrChannel(newContactList, new Map<Id, Contact>(), contactCache);
        Test.stopTest();

        // Perform assertions to verify the expected behavior
        // You can assert the values in the Account records and any other expected outcomes
        // Example: Account updated fields should match your expected values
        Account updatedAccount = [SELECT Id, Most_Recent_Source__c FROM Account WHERE Id = :testAccount.Id];
        //System.assertEquals('Expected Source', updatedAccount.Most_Recent_Source__c);

        // You can add more assertions based on your specific requirements
    }

    // Add more test methods to cover other scenarios and edge cases
}