force-app/main/default/objects/Account/fields/Initiate_Round_Robin__c.field-meta.xml
<CustomField>
    <fullName>Initiate_Round_Robin__c</fullName>
    <defaultValue>false</defaultValue>
    <description>GTMS-11254</description>
    <label>Initiate Round Robin</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Latest_Partner_Account_Interaction__c.field-meta.xml
<CustomField>
    <fullName>Latest_Partner_Account_Interaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>GTMS-6421: This field will be used as an account level identifier of the most recent partner account interaction.</description>
    <label>Latest Partner Account Interaction</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Latest Partner Account Interaction)</relationshipLabel>
    <relationshipName>Accounts3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Latest_Partner_Program_Interaction__c.field-meta.xml
<CustomField>
    <fullName>Latest_Partner_Program_Interaction__c</fullName>
    <description>GTMS-6421</description>
    <label>Latest Partner Program Interaction</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Organization_Size__c.field-meta.xml
<CustomField>
    <fullName>Organization_Size__c</fullName>
    <description>Number of employees or students</description>
    <inlineHelpText>Number of employees or students</inlineHelpText>
    <label>Organization Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 - 99</fullName>
            </value>
            <value>
                <fullName>100 - 499</fullName>
            </value>
            <value>
                <fullName>500 - 999</fullName>
            </value>
            <value>
                <fullName>1000 - 4999</fullName>
            </value>
            <value>
                <fullName>5000+</fullName>
            </value>
            <value>
                <fullName>0</fullName>
                <isActive>false</isActive>
                <label>0</label>
            </value>
            <value>
                <fullName>1-99</fullName>
                <isActive>false</isActive>
                <label>1-99</label>
            </value>
            <value>
                <fullName>1/1/1999 12:00:00 AM</fullName>
                <isActive>false</isActive>
                <label>1/1/1999 12:00:00 AM</label>
            </value>
            <value>
                <fullName>10</fullName>
                <isActive>false</isActive>
                <label>10</label>
            </value>
            <value>
                <fullName>100 - 999</fullName>
                <isActive>false</isActive>
                <label>100 - 999</label>
            </value>
            <value>
                <fullName>100-499</fullName>
                <isActive>false</isActive>
                <label>100-499</label>
            </value>
            <value>
                <fullName>1000+</fullName>
                <isActive>false</isActive>
                <label>1000+</label>
            </value>
            <value>
                <fullName>1000-4999</fullName>
                <isActive>false</isActive>
                <label>1000-4999</label>
            </value>
            <value>
                <fullName>10000+</fullName>
                <isActive>false</isActive>
                <label>10000+</label>
            </value>
            <value>
                <fullName>11</fullName>
                <isActive>false</isActive>
                <label>11</label>
            </value>
            <value>
                <fullName>13</fullName>
                <isActive>false</isActive>
                <label>13</label>
            </value>
            <value>
                <fullName>200</fullName>
                <isActive>false</isActive>
                <label>200</label>
            </value>
            <value>
                <fullName>201-500</fullName>
                <isActive>false</isActive>
                <label>201-500</label>
            </value>
            <value>
                <fullName>21</fullName>
                <isActive>false</isActive>
                <label>21</label>
            </value>
            <value>
                <fullName>22</fullName>
                <isActive>false</isActive>
                <label>22</label>
            </value>
            <value>
                <fullName>29</fullName>
                <isActive>false</isActive>
                <label>29</label>
            </value>
            <value>
                <fullName>34</fullName>
                <isActive>false</isActive>
                <label>34</label>
            </value>
            <value>
                <fullName>36161</fullName>
                <isActive>false</isActive>
                <label>36161</label>
            </value>
            <value>
                <fullName>42</fullName>
                <isActive>false</isActive>
                <label>42</label>
            </value>
            <value>
                <fullName>495 - 1000</fullName>
                <isActive>false</isActive>
                <label>495 - 1000</label>
            </value>
            <value>
                <fullName>496 - 1000</fullName>
                <isActive>false</isActive>
                <label>496 - 1000</label>
            </value>
            <value>
                <fullName>497 - 1000</fullName>
                <isActive>false</isActive>
                <label>497 - 1000</label>
            </value>
            <value>
                <fullName>498 - 1000</fullName>
                <isActive>false</isActive>
                <label>498 - 1000</label>
            </value>
            <value>
                <fullName>499 - 1000</fullName>
                <isActive>false</isActive>
                <label>499 - 1000</label>
            </value>
            <value>
                <fullName>500 - 1000</fullName>
                <isActive>false</isActive>
                <label>500 - 1000</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CreateOpportunityEvent__e/CreateOpportunityEvent__e.object-meta.xml
<CustomObject>
    <label>Create Opportunity Event</label>
    <pluralLabel>CreateOpportunityEvent</pluralLabel>
</CustomObject>

force-app/main/default/objects/CreateOpportunityEvent__e/fields/Converted_Lead_Id_t__c.field-meta.xml
<CustomField>
    <fullName>Converted_Lead_Id_t__c</fullName>
    <label>Converted Lead Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Organization_Size__c.field-meta.xml
<CustomField>
    <fullName>Organization_Size__c</fullName>
    <description>Number of employees or students</description>
    <inlineHelpText>Number of employees or students</inlineHelpText>
    <label>Organization Size</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1 - 99</fullName>
                <default>true</default>
                <label>1 - 99</label>
            </value>
            <value>
                <fullName>100 - 499</fullName>
            </value>
            <value>
                <fullName>500 - 999</fullName>
            </value>
            <value>
                <fullName>1000 - 4999</fullName>
            </value>
            <value>
                <fullName>5000+</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CreateOpportunityEventTest.cls
@isTest
private class CreateOpportunityEventTest {
  @isTest
    static void platformEventTest_unit() {
        String keyPrefix = Lead.SObjectType.getDescribe().getKeyPrefix();
        Id leadId = Id.valueOf(keyPrefix + String.valueOf(101).leftPad(12, '0'));
        //GTMS-8185
        Lead LeadRecord= new Lead(LastName='Test',Company='Test Com',state='alabama',LeadSource='Bing');
        insert LeadRecord;
        
        Database.LeadConvert lc = new Database.LeadConvert();
        lc.setLeadId(LeadRecord.id);
        lc.setOwnerId(System.UserInfo.getUserId());
        lc.setDoNotCreateOpportunity(true);
        
        LeadStatus convertStatus = [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted=true LIMIT 1];
        lc.setConvertedStatus(convertStatus.MasterLabel);
        
        Database.LeadConvertResult lcr = Database.convertLead(lc);
        
        Account acc = new Account (Name = 'Acme Co', Organization_Size__c = '5000+', BillingCountry = 'Canada', Industry = 'Other');
        insert acc;
        Account a = new Account (Name = 'Acme Co', Organization_Size__c = '5000+', BillingCountry = 'Canada', Industry = 'Other',
                                 //LFBN__Assign_Account__c=true,
                                 Initiate_Round_Robin__c = true,
                                 Latest_Partner_Account_Interaction__c=acc.id,Latest_Partner_Program_Interaction__c='subsidy');
        insert a;
        
        id convertedAccId = lc.getAccountId();
        System.debug('convertedAccId'+convertedAccId);
        List<Account> AccountidList= new  List<Account>();
        AccountidList.add(a);
        CreateOpportunityEventHelper.updateAccounts(AccountidList);
        System.assert(lcr.isSuccess());
        
        
        //GTMS-8185
        try{
            Test.startTest();
            CreateOpportunityEvent__e  event = new CreateOpportunityEvent__e ();
            event.Converted_Lead_Id_t__c  =LeadRecord.id;
            EventBus.publish(event);            
            Test.stopTest();
        }
        catch(Exception ex) {
            //expect it to fail since I am using a mocked lead Id. This is just for unit test coverage
        }
    }
}