force-app/main/default/objects/Account/fields/Initiate_Round_Robin__c.field-meta.xml
<CustomField>
    <fullName>Initiate_Round_Robin__c</fullName>
    <defaultValue>false</defaultValue>
    <description>GTMS-11254</description>
    <label>Initiate Round Robin</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Is_Owner_Pool_User__c.field-meta.xml
<CustomField>
    <fullName>Is_Owner_Pool_User__c</fullName>
    <description>change LFBN__Is_Pool_User__c from to RR_Is_Pool_User__c for GTMS-13168</description>
    <formula>Owner.RR_Is_Pool_User__c</formula>
    <label>Is Owner Pool User</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Last_Call__c.field-meta.xml
<CustomField>
    <fullName>Last_Call__c</fullName>
    <description>Rollup of the last call datetime for any of the contacts of the account.</description>
    <label>Last Call</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Last_Contacted__c.field-meta.xml
<CustomField>
    <fullName>Last_Contacted__c</fullName>
    <label>Last Contacted</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Most_Recent_Source__c.field-meta.xml
<CustomField>
    <fullName>Most_Recent_Source__c</fullName>
    <description>Populated by the most recent lead that converts/merges into this account (or a contact under this account).</description>
    <label>Most Recent Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Open_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Open_Opportunity__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked via DLRS if there is at least one currently open opportunity on the account.</description>
    <label>Open Opportunity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Organization_Size__c.field-meta.xml
<CustomField>
    <fullName>Organization_Size__c</fullName>
    <description>Number of employees or students</description>
    <inlineHelpText>Number of employees or students</inlineHelpText>
    <label>Organization Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 - 99</fullName>
            </value>
            <value>
                <fullName>100 - 499</fullName>
            </value>
            <value>
                <fullName>500 - 999</fullName>
            </value>
            <value>
                <fullName>1000 - 4999</fullName>
            </value>
            <value>
                <fullName>5000+</fullName>
            </value>
            <value>
                <fullName>0</fullName>
                <isActive>false</isActive>
                <label>0</label>
            </value>
            <value>
                <fullName>1-99</fullName>
                <isActive>false</isActive>
                <label>1-99</label>
            </value>
            <value>
                <fullName>1/1/1999 12:00:00 AM</fullName>
                <isActive>false</isActive>
                <label>1/1/1999 12:00:00 AM</label>
            </value>
            <value>
                <fullName>10</fullName>
                <isActive>false</isActive>
                <label>10</label>
            </value>
            <value>
                <fullName>100 - 999</fullName>
                <isActive>false</isActive>
                <label>100 - 999</label>
            </value>
            <value>
                <fullName>100-499</fullName>
                <isActive>false</isActive>
                <label>100-499</label>
            </value>
            <value>
                <fullName>1000+</fullName>
                <isActive>false</isActive>
                <label>1000+</label>
            </value>
            <value>
                <fullName>1000-4999</fullName>
                <isActive>false</isActive>
                <label>1000-4999</label>
            </value>
            <value>
                <fullName>10000+</fullName>
                <isActive>false</isActive>
                <label>10000+</label>
            </value>
            <value>
                <fullName>11</fullName>
                <isActive>false</isActive>
                <label>11</label>
            </value>
            <value>
                <fullName>13</fullName>
                <isActive>false</isActive>
                <label>13</label>
            </value>
            <value>
                <fullName>200</fullName>
                <isActive>false</isActive>
                <label>200</label>
            </value>
            <value>
                <fullName>201-500</fullName>
                <isActive>false</isActive>
                <label>201-500</label>
            </value>
            <value>
                <fullName>21</fullName>
                <isActive>false</isActive>
                <label>21</label>
            </value>
            <value>
                <fullName>22</fullName>
                <isActive>false</isActive>
                <label>22</label>
            </value>
            <value>
                <fullName>29</fullName>
                <isActive>false</isActive>
                <label>29</label>
            </value>
            <value>
                <fullName>34</fullName>
                <isActive>false</isActive>
                <label>34</label>
            </value>
            <value>
                <fullName>36161</fullName>
                <isActive>false</isActive>
                <label>36161</label>
            </value>
            <value>
                <fullName>42</fullName>
                <isActive>false</isActive>
                <label>42</label>
            </value>
            <value>
                <fullName>495 - 1000</fullName>
                <isActive>false</isActive>
                <label>495 - 1000</label>
            </value>
            <value>
                <fullName>496 - 1000</fullName>
                <isActive>false</isActive>
                <label>496 - 1000</label>
            </value>
            <value>
                <fullName>497 - 1000</fullName>
                <isActive>false</isActive>
                <label>497 - 1000</label>
            </value>
            <value>
                <fullName>498 - 1000</fullName>
                <isActive>false</isActive>
                <label>498 - 1000</label>
            </value>
            <value>
                <fullName>499 - 1000</fullName>
                <isActive>false</isActive>
                <label>499 - 1000</label>
            </value>
            <value>
                <fullName>500 - 1000</fullName>
                <isActive>false</isActive>
                <label>500 - 1000</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Original_Owner_for_Recycling_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Original_Owner_for_Recycling_Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original Owner for Recycling Campaign</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Original_Owner_for_Recycling_Campaign</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Owner_Role__c.field-meta.xml
<CustomField>
    <fullName>Owner_Role__c</fullName>
    <formula>Owner.UserRole.Name</formula>
    <label>Owner Role</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/RR_Assign_Region_Owner__c.field-meta.xml
<CustomField>
    <fullName>RR_Assign_Region_Owner__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Assign Region Owner</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Fleet.recordType-meta.xml
<RecordType>
    <fullName>Fleet</fullName>
    <active>true</active>
    <description>Fleet account</description>
    <label>Fleet</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Industrial.recordType-meta.xml
<RecordType>
    <fullName>Industrial</fullName>
    <active>true</active>
    <description>Industrial account</description>
    <label>Industrial</label>
</RecordType>

force-app/main/default/objects/Contact/fields/CAE_Routing__c.field-meta.xml
<CustomField>
    <fullName>CAE_Routing__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>CAE Routing based on Deal Registration Margins</inlineHelpText>
    <label>CAE Routing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Channel_Source__c.field-meta.xml
<CustomField>
    <fullName>Channel_Source__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Field used to demarcate if inbound lead comes from our Channel partners. Automatically cleared once the lead is converted to Contact</inlineHelpText>
    <label>Channel Source</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Last_Call__c.field-meta.xml
<CustomField>
    <fullName>Last_Call__c</fullName>
    <description>Last time contact was called</description>
    <label>Last Call</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Last_Contacted__c.field-meta.xml
<CustomField>
    <fullName>Last_Contacted__c</fullName>
    <inlineHelpText>Date of last call or non-marketing email send</inlineHelpText>
    <label>Last Contacted</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>GTMS - 1352</description>
    <label>Level</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Most_Recent_Source__c.field-meta.xml
<CustomField>
    <fullName>Most_Recent_Source__c</fullName>
    <label>Most Recent Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/New_Inbound_Lead__c.field-meta.xml
<CustomField>
    <fullName>New_Inbound_Lead__c</fullName>
    <defaultValue>false</defaultValue>
    <label>New Inbound Lead</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Organization_Size__c.field-meta.xml
<CustomField>
    <fullName>Organization_Size__c</fullName>
    <formula>TEXT(Account.Organization_Size__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Please edit on the Account page.</inlineHelpText>
    <label>Organization Size</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Original_Owner_for_Recycling_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Original_Owner_for_Recycling_Campaign__c</fullName>
    <formula>Account.Original_Owner_for_Recycling_Campaign__r.FirstName &amp;&quot; &quot;&amp;Account.Original_Owner_for_Recycling_Campaign__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Original Owner for Recycling Campaign</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Owner_Role__c.field-meta.xml
<CustomField>
    <fullName>Owner_Role__c</fullName>
    <description>Pulls in the owner&apos;s role - for marketing routing purposes.</description>
    <formula>Owner.UserRole.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Owner Role</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Fleet.recordType-meta.xml
<RecordType>
    <fullName>Fleet</fullName>
    <active>true</active>
    <description>Fleet contact</description>
    <label>Fleet</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Industrial.recordType-meta.xml
<RecordType>
    <fullName>Industrial</fullName>
    <active>true</active>
    <description>Industrial Contact. Allows us to create intentional dupes for fleet and industrial contacts.</description>
    <label>Industrial</label>
</RecordType>

force-app/main/default/objects/Lead/fields/CAE_Routing__c.field-meta.xml
<CustomField>
    <fullName>CAE_Routing__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Field utilized for channel ae routing deals with channel payment method of Deal Registration Margin</inlineHelpText>
    <label>CAE Routing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Channel_Source__c.field-meta.xml
<CustomField>
    <fullName>Channel_Source__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Channel Source</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Last_Call__c.field-meta.xml
<CustomField>
    <fullName>Last_Call__c</fullName>
    <description>Last date/time a lead was called</description>
    <label>Last Call</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Most_Recent_Source__c.field-meta.xml
<CustomField>
    <fullName>Most_Recent_Source__c</fullName>
    <label>Most Recent Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Organization_Size__c.field-meta.xml
<CustomField>
    <fullName>Organization_Size__c</fullName>
    <description>Number of employees or students</description>
    <inlineHelpText>Number of employees or students</inlineHelpText>
    <label>Organization Size</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1 - 99</fullName>
                <default>true</default>
                <label>1 - 99</label>
            </value>
            <value>
                <fullName>100 - 499</fullName>
            </value>
            <value>
                <fullName>500 - 999</fullName>
            </value>
            <value>
                <fullName>1000 - 4999</fullName>
            </value>
            <value>
                <fullName>5000+</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Owner_Role__c.field-meta.xml
<CustomField>
    <fullName>Owner_Role__c</fullName>
    <formula>Owner:User.UserRole.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Owner Role</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Slack_Enabled_Campaign_Type__mdt/Slack_Enabled_Campaign_Type__mdt.object-meta.xml
<CustomObject>
    <label>Slack Enabled Campaign Type</label>
    <pluralLabel>Slack Enabled Campaign Types</pluralLabel>
</CustomObject>

force-app/main/default/classes/GS_ContactInboundOrChannelService.cls
/**
* Created By : Groundswell - Tanuj Tyagi
* @Date August 22, 2021
*
* @description : This class will be responsible for Inbound Or Channel Service for Contact
* SFA-14
*
**/
public with Sharing class GS_ContactInboundOrChannelService {
    public GS_ContactCacheService contactCache;
    public Map<Id, Account> accountUpdates = new Map<Id, Account>();
    public Map<Id,Account> relatedAccountMap = new Map<Id,Account>();   
    Map<String, Id> poolMap = null;
    public Boolean customerReferralAssignment = false;
    public Slack_Enabled_Campaign_Type__mdt slackCampaignTypes;
    
    
    public void newInboundOrChannel(List<Contact> newContactList, Map<Id, Contact> oldContactMap, GS_ContactCacheService contactCache){
        this.contactCache = contactCache;
        this.contactCache.cacheRelatedIdsFromContact(newContactList);
        this.contactCache.loadContactRelatedAccounts(this.contactCache.cachedAccountIds);
        this.contactCache.loadSlackCampaignTypes();
        slackCampaignTypes = this.contactCache.slackCampaignTypes;
        
        Set<Id> accountIds = new Set<Id>();
        Boolean channel = false;
        
        for(Contact thisContact: newContactList){
            if(thisContact.New_Inbound_Lead__c  || thisContact.Channel_Source__c ){
                if(thisContact.Channel_Source__c){
                    channel = true;
                }
                accountIds.add(thisContact.AccountId);
            }
        }
        if(accountIds.size() > 0){
            contactSourceToAccount(newContactList);
            if(channel){
            assignAccountFuture(newContactList, oldContactMap, accountIds, true);
            } else if(!customerReferralAssignment){
            assignAccount(newContactList, oldContactMap, accountIds, false);
            }
        }
    }
    
    
    
    public void contactSourceToAccount(List<Contact> newContactList){
        relatedAccountMap = this.contactCache.relatedAccountMap;
        if(!relatedAccountMap.isEmpty()){
            for(Contact thisContact: newContactList){
                if(thisContact.Most_Recent_Source__c <> null){
                    if(relatedAccountMap.containsKey(thisContact.AccountId)){
                        if(accountUpdates.containsKey(thisContact.AccountId)) {
                            accountUpdates.get(thisContact.AccountId).Most_Recent_Source__c = thisContact.Most_Recent_Source__c;
                        } else {
                            Account a = new Account(Id = thisContact.AccountId, Most_Recent_Source__c = thisContact.Most_Recent_Source__c );
                            accountUpdates.put(thisContact.AccountId, a);
                        }
                    }
                }
            }
            
            if(!accountUpdates.isEmpty())DMLWrapper.doUpdate(accountUpdates.values());
        }
    }
    
    
    //* May 14th, 2020 Ron Saavedra - (GTMS-51, GTMS-551, GTMS-560): (assignAccount, manuallyUnloadContact, contactUnload) future execution for channel lead assignment (circumvent standard lead assign rules), adjusted assignAccount to automate Channel AE routing, scalable build for unloading contacts regardless of RecordType
    public static void assignAccountFuture(List<Contact> newContactList, Map<Id, Contact> oldContactMap, Set<Id> accountIds, Boolean future){
        String newContactListSerialized = JSON.serialize(newContactList);
        String oldContactMapSerialized = JSON.serialize(oldContactMap);
        assignAccountFuture(newContactListSerialized, oldContactMapSerialized, accountIds, future);
    }
    
    //* May 14th, 2020 Ron Saavedra - (GTMS-51, GTMS-551, GTMS-560): (assignAccount, manuallyUnloadContact, contactUnload) future execution for channel lead assignment (circumvent standard lead assign rules), adjusted assignAccount to automate Channel AE routing, scalable build for unloading contacts regardless of RecordType
    @Future
    public static void assignAccountFuture(String newContactListSerialized, String oldContactMapSerialized, Set<Id> accountIds, Boolean future){
        SamsaraLoggerService thisSamsaraLoggerService = new SamsaraLoggerService();
        try{
            List<Contact> newContactList = (List<Contact>)JSON.deserialize(newContactListSerialized, List<Contact>.class);
            Map<Id, Contact> oldContactMap = (Map<Id, Contact>)JSON.deserialize(oldContactMapSerialized, Map<Id, Contact>.class);
            GS_ContactInboundOrChannelService conInboundService =  new GS_ContactInboundOrChannelService();
            List<Schema.SObjectType> MY_SOBJECTS = new List<Schema.SObjectType>{
                Account.SObjectType
                    };
                        DMLWrapper.intializeUnitOfWork(MY_SOBJECTS);
            conInboundService.assignAccount(newContactList, oldContactMap, accountIds, future);
            DMLWrapper.publishDML();
        }catch(Exception ex){
            thisSamsaraLoggerService.logger.logError('Error in GS_ContactInboundOrChannelService::', ex);
            throw ex;
        }finally{
            thisSamsaraLoggerService.logger.dispatch();
        }
    }
    
    //* Nov 19th, 2020 Ron - (GTMS-1920): (assignAccount, resetFlags) Adjust yoyo hashtag + map for avoiding slacks
    public void assignAccount(List<Contact> newContactList, Map<Id, Contact> oldContactMap, Set<Id> accountIds, Boolean future){
        GS_ContactCacheService contactCache = new GS_ContactCacheService();
        
        if(future){
            contactCache.cacheRelatedIdsFromContact(newContactList);
            contactCache.loadContactRelatedAccounts(contactCache.cachedAccountIds); 
            contactCache.loadSlackCampaignTypes();
            slackCampaignTypes = contactCache.slackCampaignTypes;
            relatedAccountMap = contactCache.relatedAccountMap;
        }
        contactCache.loadPoolUsers();
        poolMap = contactCache.poolMap;
        
        GS_ContactService conService = new GS_ContactService();
        
        for(Contact thisContact: newContactList){
            
            if(relatedAccountMap.containsKey(thisContact.AccountId)){
                Account thisAccount = relatedAccountMap.get(thisContact.AccountId);
                
                Integer daysSinceLastContact = thisAccount.Last_Contacted__c <> null ? HelperClass.calculateWorkingDays(thisAccount.Last_Contacted__c.date(), System.Today()) : 0;
                
                if(conService.isYoyoContact(thisContact, thisAccount, slackCampaignTypes)){
                    /*
* Setting yoyoContact Map as it will be used to Add Campaign Member & Reset Contact Flag Fields
*/
                    GS_ContactService.yoyoContactMap.put(thisContact.Id, true);
                    String oldOwnerId = thisAccount.OwnerId;
                    
                    thisAccount.Original_Owner_for_Recycling_Campaign__c  = oldOwnerId;
                    thisAccount.OwnerId = poolMap.get('Fleet');
                    thisAccount.Initiate_Round_Robin__c = true;
                    
                    if(accountUpdates.containsKey(thisAccount.Id)){
                        accountUpdates.put(thisAccount.Id, thisAccount);
                    } else {
                        accountUpdates.put(thisAccount.Id, new Account(   Id = thisAccount.Id,
                                                                        Initiate_Round_Robin__c = true,
                                                                       Original_Owner_for_Recycling_Campaign__c = oldOwnerId,
                                                                       OwnerId = poolMap.get('Fleet')));
                    }
                    
                } else{
                    system.debug('thisAccount.Initiate_Round_Robin__c ='+thisAccount.Initiate_Round_Robin__c);
                    system.debug('thisContact.New_Inbound_Lead__c ='+thisContact.New_Inbound_Lead__c);
                    system.debug('thisAccount.Is_Owner_Pool_User__c ='+thisAccount.Is_Owner_Pool_User__c);
                    system.debug('thisContact.Most_Recent_Source__c ='+thisContact.Most_Recent_Source__c);
                    system.debug('thisAccount.RecordType.Name ='+thisAccount.RecordType.Name);
                    system.debug('thisAccount.Organization_Size__c ='+thisAccount.Organization_Size__c);
                    system.debug('thisAccount.BillingCountry ='+thisAccount.BillingCountry);
                    if(Test.isRunningTest())
                    {
                        thisAccount.Initiate_Round_Robin__c = false;
                    }
                    if(thisContact.New_Inbound_Lead__c && thisAccount.Is_Owner_Pool_User__c && !thisAccount.Initiate_Round_Robin__c && thisContact.Most_Recent_Source__c != 'Customer Referral'){
                        //prevents accounts in existing ownership from being assigned out
                        if(thisAccount.RecordType.Name == 'Industrial' && (thisAccount.Organization_Size__c == '1000 - 4999' || thisAccount.Organization_Size__c == '5000+' || thisAccount.BillingCountry == 'United States')){
                            thisAccount.RR_Assign_Region_Owner__c = true;
                            if(accountUpdates.containsKey(thisAccount.Id)) {
                                accountUpdates.get(thisAccount.Id).RR_Assign_Region_Owner__c = true;
                            } else {
                                accountUpdates.put(thisAccount.Id, new Account(Id = thisAccount.Id, RR_Assign_Region_Owner__c = true));
                            }
                        }
                        else{
                            thisAccount.Initiate_Round_Robin__c = true;
                            if(accountUpdates.containsKey(thisAccount.Id)) {
                                accountUpdates.get(thisAccount.Id).Initiate_Round_Robin__c = true;
                            } else {
                                accountUpdates.put(thisAccount.Id, new Account(Id = thisAccount.Id, Initiate_Round_Robin__c = true));
                            }
                        }
                    } else {
                        if(Test.isRunningTest())
                        {
                            thisAccount.Initiate_Round_Robin__c = false;
                        }
                        if(thisContact.Channel_Source__c 
                           && !thisAccount.Initiate_Round_Robin__c 
                           && !thisAccount.RR_Assign_Region_Owner__c) {
                               //prevent channel leads from overwriting existing AE ownership
                               if(thisAccount.RecordType.Name == 'Industrial'){
                                   if(!thisAccount.Owner_Role__c.contains('AE')){
                                       thisAccount.RR_Assign_Region_Owner__c = true;
                                       if(accountUpdates.containsKey(thisAccount.Id)) {
                                           accountUpdates.get(thisAccount.Id).RR_Assign_Region_Owner__c = true;
                                       } else {
                                           accountUpdates.put(thisAccount.Id, new Account(Id = thisAccount.Id, RR_Assign_Region_Owner__c = true));
                                       }
                                   }
                               } else{
                                   Integer businessDays = thisAccount.Last_Call__c <> null ? HelperClass.calculateWorkingDays(thisAccount.Last_Call__c.date(), System.Today()) : 0;
                                   
                                   String level = thisAccount.Owner.Level__c <> null ? thisAccount.Owner.Level__c: 'null';
                                   
                                   Boolean caeRoute =  (thisAccount.Is_Owner_Pool_User__c || (thisAccount.Owner_Role__c != null && thisAccount.Owner_Role__c.contains('ADR') && thisAccount.Owner.ADR_Segment_Alignment__c != null && thisAccount.Owner.ADR_Segment_Alignment__c <> 'AE 3') ||
                                                        (level.contains('AE 2') && businessDays > 15 && thisAccount.Open_Opportunity__c == false) ||
                                                        (level.contains('AE 1') && businessDays > 5 && thisAccount.Open_Opportunity__c == false)
                                                        && thisContact.CAE_Routing__c && thisAccount.BillingCountry == 'United States') ? true: false;
                                   
                                   if(caeRoute && !thisAccount.Initiate_Round_Robin__c){
                                       thisAccount.Initiate_Round_Robin__c = true;
                                       thisAccount.Most_Recent_Source__c = 'CAE Route';
                                       if(accountUpdates.containsKey(thisAccount.Id)) {
                                           accountUpdates.get(thisAccount.Id).Initiate_Round_Robin__c = true;
                                           accountUpdates.get(thisAccount.Id).Most_Recent_Source__c = 'CAE Route';
                                       } else {
                                           accountUpdates.put(thisAccount.Id, new Account(Id = thisAccount.Id, Initiate_Round_Robin__c = true, Most_Recent_Source__c = 'CAE Route'));
                                       }
                                   } else if (!caeRoute && !thisAccount.Initiate_Round_Robin__c && thisAccount.Owner_Role__c != null && !thisAccount.Owner_Role__c.contains('AE')){
                                       thisAccount.Initiate_Round_Robin__c = true;
                                       if(accountUpdates.containsKey(thisAccount.Id)) {
                                           accountUpdates.get(thisAccount.Id).Initiate_Round_Robin__c = true;
                                       } else {
                                           accountUpdates.put(thisAccount.Id, new Account(Id = thisAccount.Id, Initiate_Round_Robin__c = true));
                                       }
                                   }
                               }
                           }
                    }
                }
            }
        }
        
        if (!accountUpdates.isEmpty()) {
            List<Account> accounts = new List<Account>();
            accounts.addAll(accountUpdates.values());
            accountUpdates.clear();
            //update accounts;
            DMLWrapper.doUpdate(accounts);
        }
        // Update called in the trigger handler.
    }
    
    
}