force-app/main/default/objects/Account/fields/Last_Meaningful_Engagement_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Meaningful_Engagement_Date__c</fullName>
    <label>Last Meaningful Engagement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Organization_Size__c.field-meta.xml
<CustomField>
    <fullName>Organization_Size__c</fullName>
    <description>Number of employees or students</description>
    <inlineHelpText>Number of employees or students</inlineHelpText>
    <label>Organization Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 - 99</fullName>
            </value>
            <value>
                <fullName>100 - 499</fullName>
            </value>
            <value>
                <fullName>500 - 999</fullName>
            </value>
            <value>
                <fullName>1000 - 4999</fullName>
            </value>
            <value>
                <fullName>5000+</fullName>
            </value>
            <value>
                <fullName>0</fullName>
                <isActive>false</isActive>
                <label>0</label>
            </value>
            <value>
                <fullName>1-99</fullName>
                <isActive>false</isActive>
                <label>1-99</label>
            </value>
            <value>
                <fullName>1/1/1999 12:00:00 AM</fullName>
                <isActive>false</isActive>
                <label>1/1/1999 12:00:00 AM</label>
            </value>
            <value>
                <fullName>10</fullName>
                <isActive>false</isActive>
                <label>10</label>
            </value>
            <value>
                <fullName>100 - 999</fullName>
                <isActive>false</isActive>
                <label>100 - 999</label>
            </value>
            <value>
                <fullName>100-499</fullName>
                <isActive>false</isActive>
                <label>100-499</label>
            </value>
            <value>
                <fullName>1000+</fullName>
                <isActive>false</isActive>
                <label>1000+</label>
            </value>
            <value>
                <fullName>1000-4999</fullName>
                <isActive>false</isActive>
                <label>1000-4999</label>
            </value>
            <value>
                <fullName>10000+</fullName>
                <isActive>false</isActive>
                <label>10000+</label>
            </value>
            <value>
                <fullName>11</fullName>
                <isActive>false</isActive>
                <label>11</label>
            </value>
            <value>
                <fullName>13</fullName>
                <isActive>false</isActive>
                <label>13</label>
            </value>
            <value>
                <fullName>200</fullName>
                <isActive>false</isActive>
                <label>200</label>
            </value>
            <value>
                <fullName>201-500</fullName>
                <isActive>false</isActive>
                <label>201-500</label>
            </value>
            <value>
                <fullName>21</fullName>
                <isActive>false</isActive>
                <label>21</label>
            </value>
            <value>
                <fullName>22</fullName>
                <isActive>false</isActive>
                <label>22</label>
            </value>
            <value>
                <fullName>29</fullName>
                <isActive>false</isActive>
                <label>29</label>
            </value>
            <value>
                <fullName>34</fullName>
                <isActive>false</isActive>
                <label>34</label>
            </value>
            <value>
                <fullName>36161</fullName>
                <isActive>false</isActive>
                <label>36161</label>
            </value>
            <value>
                <fullName>42</fullName>
                <isActive>false</isActive>
                <label>42</label>
            </value>
            <value>
                <fullName>495 - 1000</fullName>
                <isActive>false</isActive>
                <label>495 - 1000</label>
            </value>
            <value>
                <fullName>496 - 1000</fullName>
                <isActive>false</isActive>
                <label>496 - 1000</label>
            </value>
            <value>
                <fullName>497 - 1000</fullName>
                <isActive>false</isActive>
                <label>497 - 1000</label>
            </value>
            <value>
                <fullName>498 - 1000</fullName>
                <isActive>false</isActive>
                <label>498 - 1000</label>
            </value>
            <value>
                <fullName>499 - 1000</fullName>
                <isActive>false</isActive>
                <label>499 - 1000</label>
            </value>
            <value>
                <fullName>500 - 1000</fullName>
                <isActive>false</isActive>
                <label>500 - 1000</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <inlineHelpText>Field used for Territory Routing (Business Units Active: Industrial)</inlineHelpText>
    <label>Territory</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Timezone__c.field-meta.xml
<CustomField>
    <fullName>Timezone__c</fullName>
    <description>Calculates timezone based on the billing state of the account</description>
    <formula>CASE( BillingState,&apos;Alabama&apos;,&apos;CST&apos;, 
&apos;Alaska&apos;,&apos;AKST&apos;, 
&apos;Arizona&apos;,&apos;MST&apos;, 
&apos;Arkansas&apos;,&apos;CST&apos;, 
&apos;California&apos;,&apos;PST&apos;, 
&apos;Colorado&apos;,&apos;MST&apos;, 
&apos;Connecticut&apos;,&apos;EST&apos;, 
&apos;Delaware&apos;,&apos;EST&apos;, 
&apos;District of Columbia&apos;,&apos;EST&apos;,
&apos;Florida&apos;,&apos;EST&apos;, 
&apos;Georgia&apos;,&apos;EST&apos;, 
&apos;Hawaii&apos;,&apos;HST&apos;, 
&apos;Idaho&apos;,&apos;MST&apos;, 
&apos;Illinois&apos;,&apos;CST&apos;, 
&apos;Indiana&apos;,&apos;EST&apos;, 
&apos;Iowa&apos;,&apos;CST&apos;, 
&apos;Kansas&apos;,&apos;CST&apos;, 
&apos;Kentucky&apos;,&apos;CST&apos;, 
&apos;Louisiana&apos;,&apos;CST&apos;, 
&apos;Maine&apos;,&apos;EST&apos;, 
&apos;Maryland&apos;,&apos;EST&apos;, 
&apos;Massachusetts&apos;,&apos;EST&apos;, 
&apos;Michigan&apos;,&apos;EST&apos;, 
&apos;Minnesota&apos;,&apos;CST&apos;, 
&apos;Mississippi&apos;,&apos;CST&apos;, 
&apos;Missouri&apos;,&apos;CST&apos;, 
&apos;Montana&apos;,&apos;MST&apos;, 
&apos;Nebraska&apos;,&apos;CST&apos;, 
&apos;Nevada&apos;,&apos;PST&apos;, 
&apos;New Hampshire&apos;,&apos;EST&apos;, 
&apos;New Jersey&apos;,&apos;EST&apos;, 
&apos;New Mexico&apos;,&apos;MST&apos;, 
&apos;New York&apos;,&apos;EST&apos;, 
&apos;North Carolina&apos;,&apos;EST&apos;, 
&apos;North Dakota&apos;,&apos;CST&apos;, 
&apos;Ohio&apos;,&apos;EST&apos;, 
&apos;Oklahoma&apos;,&apos;CST&apos;, 
&apos;Oregon&apos;,&apos;PST&apos;, 
&apos;Pennsylvania&apos;,&apos;EST&apos;, 
&apos;Rhode Island&apos;,&apos;EST&apos;, 
&apos;South Carolina&apos;,&apos;EST&apos;, 
&apos;South Dakota&apos;,&apos;CST&apos;, 
&apos;Tennessee&apos;,&apos;CST&apos;, 
&apos;Texas&apos;,&apos;CST&apos;, 
&apos;Utah&apos;,&apos;MST&apos;, 
&apos;Vermont&apos;,&apos;EST&apos;, 
&apos;Virginia&apos;,&apos;EST&apos;, 
&apos;Washington&apos;,&apos;PST&apos;, 
&apos;West Virginia&apos;,&apos;EST&apos;, 
&apos;Wisconsin&apos;,&apos;CST&apos;, 
&apos;Wyoming&apos;,&apos;MST&apos;, 
&apos;Alberta&apos;,&apos;MST&apos;, 
&apos;British Columbia&apos;,&apos;MST&apos;, 
&apos;Manitoba&apos;,&apos;CST&apos;, 
&apos;New Brunswick&apos;,&apos;AST&apos;, 
&apos;Newfoundland and Labrador&apos;,&apos;AST&apos;, 
&apos;Northwest Territories&apos;,&apos;MST&apos;, 
&apos;Nova Scotia&apos;,&apos;AST&apos;, 
&apos;Nunavut&apos;,&apos;EST&apos;, 
&apos;Ontario&apos;,&apos;EST&apos;, 
&apos;Prince Edward Island&apos;,&apos;AST&apos;, 
&apos;Quebec&apos;,&apos;EST&apos;, 
&apos;Saskatchewan&apos;,&apos;CST&apos;, 
&apos;Yukon Territories&apos;,&apos;PST&apos;, 
&apos;Other&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Calculates timezone based on the billing state of the account</inlineHelpText>
    <label>Timezone</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Fleet.recordType-meta.xml
<RecordType>
    <fullName>Fleet</fullName>
    <active>true</active>
    <description>Fleet account</description>
    <label>Fleet</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Last_meaningful_engagement_date__c.field-meta.xml
<CustomField>
    <fullName>Last_meaningful_engagement_date__c</fullName>
    <formula>If(LastModifiedDate &gt;  SBQQ__PrimaryQuote__r.LastModifiedDate, LastModifiedDate, SBQQ__PrimaryQuote__r.LastModifiedDate)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Last meaningful engagement date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Shipping_Country__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Country__c</fullName>
    <label>Shipping Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Aland Islands</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia, Plurinational State of</fullName>
            </value>
            <value>
                <fullName>Bonaire, Sint Eustatius and Saba</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Bouvet Island</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Trial.recordType-meta.xml
<RecordType>
    <fullName>Trial</fullName>
    <active>true</active>
    <businessProcess>Standard Opportunities</businessProcess>
    <label>Trial</label>
</RecordType>

force-app/main/default/objects/User/fields/Leave_Return_Date__c.field-meta.xml
<CustomField>
    <fullName>Leave_Return_Date__c</fullName>
    <label>Leave Return Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/User/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <inlineHelpText>Use instead of Geography as of Q1.FY2021</inlineHelpText>
    <label>Sales Territory</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/User/fields/TimeZone__c.field-meta.xml
<CustomField>
    <fullName>TimeZone__c</fullName>
    <label>TimeZone</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Batch_LEAPCloseOpportunitiesTest.cls
/*
* @Author : Siddharth Kumar Mishra
* @Description:- Test class for Batch_LEAPCloseOpportunities ( GTMS - 7001  -  4/19/2022  -  Move opportunities to "Closed Lost" if all conditions are met )
*/
@IsTest
public class Batch_LEAPCloseOpportunitiesTest
{
    @TestSetup 
    public static void setup()
    {
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
       // Insert account as current user
        System.runAs (thisUser) {
        
        //Test User
        User testUser = new User();
        testUser.lastName = 'Test User 001';
        testUser.Alias = 'test';
        testUser.Email = 'tuser@test.com';
        testUser.Username = 'tuser@test001tests.com';
        testUser.CommunityNickname = 'User16529768062775798018';
        testUser.UserRoleId = [select Id,name from UserRole where name like '%Fleet IS AE2 NA US%' limit 1].id;
        testUser.ProfileId = [select Id,name from Profile where name like '%Samsara Sales Management - New System%' limit 1].id;
        testUser.EmployeeNumber = '9000234';
		testUser.Territory__c = 'North America';
		testuser.TimeZone__c = 'America/Los_Angeles';
		testuser.TimeZoneSidKey = 'America/Los_Angeles';
		testuser.LocaleSidKey = 'en_US';
		testuser.LanguageLocaleKey = 'en_US';
		testuser.EmailEncodingKey = '	ISO-8859-1';
        testuser.Leave_Return_Date__c = null;
        Insert testUser;

        //Executing as testUser as Owner needs to be an User with role containing 'Fleet IS AE1 NA US' or 'Fleet IS AE2 NA US'
        Account testAcc = new Account();
        testAcc.name = 'Test Account 001';
        testAcc.Last_Meaningful_Engagement_Date__c = null;
        testAcc.Organization_Size__c = '1 - 99';
        testAcc.BillingCountry = 'India';
        
        
        Insert testAcc;
        
        //Test opportunity
        Opportunity testOpp = new Opportunity();
        testOpp.Name = 'Test Opportunity 001';
        testOpp.AccountId = testAcc.Id;
        testOpp.RecordTypeId = [Select Id,name from RecordType where SobjectType = 'Opportunity' AND name = 'Standard Opportunity'].Id;
        testOpp.Type = 'Revenue Opportunity';
        testOpp.StageName = 'Trial';
        testOpp.CloseDate = Date.today().addDays(-10);
        testOpp.Shipping_Country__c = 'India';
        testOpp.Shipping_State__c = 'Maharashtra';
        testOpp.OwnerId = testUser.id;
        //testOpp.amount = 10000;         
        //testOpp.Amount_Number__c = 10000;

        Insert testOpp;

        Opportunity testOpp2 = new Opportunity();
        testOpp2.Name = 'Test Opportunity 002';
        testOpp2.AccountId = testAcc.Id;
        testOpp2.RecordTypeId = [Select Id,name from RecordType where SobjectType = 'Opportunity' AND name = 'Standard Opportunity'].Id;
        testOpp2.Type = 'Revenue Opportunity';
        testOpp2.StageName = 'Trial';
        testOpp2.CloseDate = Date.today().addDays(-10);
        testOpp2.Shipping_Country__c = 'India';
        testOpp2.Shipping_State__c = 'Maharashtra';
        testOpp2.OwnerId = testUser.id;
        Insert testOpp2;
        
        testAcc.Account_Assignment_Date__c = System.now().addDays(-100);
        update testAcc;        

        Opportunity testOpp3 = new Opportunity();
        testOpp3.Name = 'Test free trial Opportunity 001';
        testOpp3.AccountId = testAcc.Id;
        testOpp3.RecordTypeId = [Select Id,name from RecordType where SobjectType = 'Opportunity' AND name = 'Trial'].Id;
        testOpp3.Type = 'Free Trial Opportunity';
        testOpp3.StageName = 'Closed Won';
        testOpp3.CloseDate = Date.today();
        testOpp3.Shipping_Country__c = 'India';
        testOpp3.Shipping_State__c = 'Maharashtra';
        testOpp3.TrialResolutionOppty__c = testOpp2.id;
        testOpp3.Trial_Status__c ='Open';
        testOpp3.OwnerId = testUser.id;
        Insert testOpp3;
        System.debug('testOpp2.TrialResolutionOppty__c ---->'+testOpp3.TrialResolutionOppty__c);  
        }      
    }
    
    @IsTest
    static void testMethod01()
    {
        //Opportunity oldOpp = [select id,name,StageName,Owner.UserRole.name from Opportunity where name = 'Test Opportunity 001' limit 1];
        //Account acc = [Select id,name from Account where name = 'Test Account 001' Limit 1];
        test.startTest();
        //database.executebatch((new Batch_LEAPCloseOpportunities()),20);
        Batch_LEAPCloseOpportunities sch = new Batch_LEAPCloseOpportunities();
        sch.execute(null);
        test.stopTest();
        
        Opportunity newOpp1 = [select id,name,StageName from Opportunity where name = 'Test Opportunity 001' limit 1];
        Opportunity newOpp2 = [select id,name,StageName from Opportunity where name = 'Test Opportunity 002' limit 1];
        
        system.assertEquals('Closed Lost', newOpp1.StageName);
        system.assertEquals('Closed Lost', newOpp2.StageName);
    }    
}