force-app/main/default/objects/Account/fields/Latest_Active_Contract__c.field-meta.xml
<CustomField>
    <fullName>Latest_Active_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Latest Active Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <description>This field is being used by Netsuite and code for contracts. Before it is changed Business Systems needs to be notified, as it has a number of dependencies.</description>
    <formula>IF(

CONTAINS(Owner.UserRole.Name, &quot;Small Fleets&quot;),
&quot;Small Business&quot;,
IF(
CONTAINS(Owner.UserRole.Name, &quot;AE1&quot;),
&quot;AE1&quot;,
IF(
OR(
CONTAINS(Owner.UserRole.Name, &quot;Partner&quot;),
CONTAINS(Owner.UserRole.Name, &quot;AE2&quot;)
),
&quot;AE2&quot;,
IF(
CONTAINS(Owner.UserRole.Name, &quot;AE3&quot;),
&quot;AE3&quot;,
IF(
OR(
CONTAINS(Owner.UserRole.Name, &quot;ENT&quot;),
CONTAINS(Owner.UserRole.Name, &quot;Enterprise&quot;),
CONTAINS(Owner.UserRole.Name, &quot;Major&quot;),
CONTAINS(Owner.UserRole.Name, &quot;Field&quot;)
),
&quot;Enterprise&quot;,
&quot;Management&quot;
)
)
)
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Segment (by Current Owner)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/netsuite_conn__Bill_To_Tier__c.field-meta.xml
<CustomField>
    <fullName>netsuite_conn__Bill_To_Tier__c</fullName>
    <label>Bill To Tier</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>End User</fullName>
            </value>
            <value>
                <fullName>Reseller</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Original_Approved_Discount__c.field-meta.xml
<CustomField>
    <fullName>Original_Approved_Discount__c</fullName>
    <formula>MIN(
	IF(
		NOT(ISBLANK(SBQQ__Opportunity__r.Approved_Discount__c)),
		SBQQ__Opportunity__r.Approved_Discount__c, 
		IF(
			SBQQ__Opportunity__r.Blended_Discount__c=0,NULL,
			(SBQQ__Opportunity__r.Blended_Discount__c+0.001)
		)
	),0.401
)

/*MIN(
		IF(
				NOT(
						ISBLANK(Original_Contracted_Opportunity__r.Approved_Discount__c)
					),
				Original_Contracted_Opportunity__r.Approved_Discount__c, 
			IF(Original_Contracted_Opportunity__r.Blended_Discount__c=0,NULL,

				(Original_Contracted_Opportunity__r.Blended_Discount__c+0.001
				)
			)
		),0.401
	)
*/</formula>
    <label>Original Approved Discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Adjust_License_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Adjust_License_Start_Date__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Enable Sys Admin and Sales Ops to make License Start Date != Close Date (can make sense for early renewals and co-terming issues)</description>
    <inlineHelpText>Confirm there are no items that require shipping on this opportunity</inlineHelpText>
    <label>Adjust License Start Date</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Approved_Discount__c.field-meta.xml
<CustomField>
    <fullName>Approved_Discount__c</fullName>
    <label>Approved Discount</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Balance_Due__c.field-meta.xml
<CustomField>
    <fullName>Balance_Due__c</fullName>
    <description>Amount, sales tax, shipping &amp; handling less amount received</description>
    <formula>Amount
+ SBQQ__PrimaryQuote__r.Total_Quote_Line_Item_Subsidy_amount__c
+IF(ISPICKVAL(SBQQ__PrimaryQuote__r.Is_Installation_Reimbursable__c, &apos;No&apos;),SBQQ__PrimaryQuote__r.Total_Estimated_Installation_Costs__c,0)
+ IF(CPQ_Opportunity__c, Sales_Tax_Amount__c, Sales_Tax__c)
+ Shipping_and_Handling__c
+ X3rd_Party_Products_Services__c
- Amount_Received__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Amount, sales tax, shipping &amp; handling less amount received</inlineHelpText>
    <label>Balance Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Configuration_Segment__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Segment__c</fullName>
    <label>Configuration Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Express</fullName>
            </value>
            <value>
                <fullName>Non Express</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Express_Agreement_Accepted_Date__c.field-meta.xml
<CustomField>
    <fullName>Express_Agreement_Accepted_Date__c</fullName>
    <label>Check out agreement accepted date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Finance_Notes__c.field-meta.xml
<CustomField>
    <fullName>Finance_Notes__c</fullName>
    <label>Finance Notes</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/License_End_Date__c.field-meta.xml
<CustomField>
    <fullName>License_End_Date__c</fullName>
    <description>Date License Ends for Opportunity</description>
    <label>License End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/License_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>License_Start_Date__c</fullName>
    <description>Determines the License Term. Automatically set to match the Close Date when Opportunity moves to Closed Won.</description>
    <inlineHelpText>Determines the License Term. Automatically set to match the Close Date when Opportunity moves to Closed Won.</inlineHelpText>
    <label>License Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/License_Term__c.field-meta.xml
<CustomField>
    <fullName>License_Term__c</fullName>
    <defaultValue>36</defaultValue>
    <description>The license term of the opportunity.</description>
    <label>License Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/License_Term_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>License_Term_Approval_Status__c</fullName>
    <label>License Term Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approval required</fullName>
                <isActive>false</isActive>
                <label>Approval required</label>
            </value>
            <value>
                <fullName>N/A</fullName>
                <isActive>false</isActive>
                <label>N/A</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/netsuite_conn__Bill_To_Tier__c.field-meta.xml
<CustomField>
    <fullName>netsuite_conn__Bill_To_Tier__c</fullName>
    <label>Bill To Tier</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>End User</fullName>
                <default>true</default>
                <label>End User</label>
            </value>
            <value>
                <fullName>Reseller</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/netsuite_conn__From_Contract__c.field-meta.xml
<CustomField>
    <fullName>netsuite_conn__From_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>From Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Opportunities (From Contract)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Original_Approved_Discount__c.field-meta.xml
<CustomField>
    <fullName>Original_Approved_Discount__c</fullName>
    <description>The original opportunity approved blended discount</description>
    <label>Original Approved Discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Overwrite_Validation_Rule__c.field-meta.xml
<CustomField>
    <fullName>Overwrite_Validation_Rule__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Allows validation rules to be temporarily overwritten. This should always be defaulted to FALSE. It can be checked when running a process that needs to give reps ability to bypass a validation rule but should ALWAYS be unchecked again as part of that process.</description>
    <label>Overwrite Validation Rule</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Price_Book_Name__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_Name__c</fullName>
    <defaultValue>&quot;Samsara Standard&quot;</defaultValue>
    <description>Price Book Name, populated by workflow / field update</description>
    <label>Price Book Name</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Promo_Reason__c.field-meta.xml
<CustomField>
    <fullName>Promo_Reason__c</fullName>
    <description>Reason for the promo</description>
    <label>Promo Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Exchange</fullName>
            </value>
            <value>
                <fullName>Warranty Exchange</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Sales Incentive</fullName>
            </value>
            <value>
                <fullName>Charitable Donation</fullName>
            </value>
            <value>
                <fullName>Free Trial: Exchange</fullName>
            </value>
            <value>
                <fullName>Free Trial: Warranty Exchange</fullName>
            </value>
            <value>
                <fullName>Beta Program</fullName>
            </value>
            <value>
                <fullName>Employee - Engineering/Testing</fullName>
            </value>
            <value>
                <fullName>Employee - Personal Use/New Hire</fullName>
            </value>
            <value>
                <fullName>Employee - On site</fullName>
            </value>
            <value>
                <fullName>NPI</fullName>
            </value>
            <value>
                <fullName>Approval HW Upgrade</fullName>
            </value>
            <value>
                <fullName>Return to Sender: Exchange</fullName>
            </value>
            <value>
                <fullName>Unplanned Return: Exchange</fullName>
            </value>
            <value>
                <fullName>Demo/Prototype</fullName>
                <isActive>false</isActive>
                <label>Demo/Prototype</label>
            </value>
            <value>
                <fullName>Employee</fullName>
                <isActive>false</isActive>
                <label>Employee</label>
            </value>
            <value>
                <fullName>WIP</fullName>
                <isActive>false</isActive>
                <label>WIP</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <description>Used by Finance for Netsuite and financial reporting.</description>
    <formula>if( CONTAINS(Pricebook2.Name,&quot;Samsara Express&quot;),&quot;SMB&quot;,

if( AND(OR(CONTAINS(Owner_Role_Copy__c,&quot;MM&quot;),CONTAINS(Owner_Role_Copy__c,&quot;Mid Market&quot;)),Industrial_Oppty__c =FALSE),&quot;Mid Market&quot;,

if( AND(OR(CONTAINS(Owner_Role_Copy__c,&quot;MM&quot;),CONTAINS(Owner_Role_Copy__c,&quot;Mid Market&quot;)),Industrial_Oppty__c =TRUE),&quot;Industrial&quot;,

if( AND(OR(CONTAINS(Owner_Role_Copy__c,&quot;Major Accounts&quot;),CONTAINS(Owner_Role_Copy__c,&quot;Major&quot;),CONTAINS(Owner_Role_Copy__c,&quot;Field&quot;),CONTAINS(Owner_Role_Copy__c,&quot;Enterprise&quot;)),Industrial_Oppty__c =FALSE),&quot;Enterprise&quot;,

if( AND(OR(CONTAINS(Owner_Role_Copy__c,&quot;Major Accounts&quot;),CONTAINS(Owner_Role_Copy__c,&quot;Major&quot;),CONTAINS(Owner_Role_Copy__c,&quot;Field&quot;),CONTAINS(Owner_Role_Copy__c,&quot;Enterprise&quot;)),Industrial_Oppty__c =TRUE),&quot;Industrial&quot;,

if(AND(CONTAINS(Owner_Role_Copy__c,&quot;SMB&quot;),CONTAINS(Pricebook2.Name,&quot;Samsara Standard&quot;)),&quot;Mid Market&quot;,

if(CONTAINS(Owner_Role_Copy__c,&quot;Industrial&quot;),&quot;Industrial&quot;,

if(OR(CONTAINS(Owner_Role_Copy__c,&quot;Management&quot;),CONTAINS(Owner_Role_Copy__c, &quot;Operations&quot;)), Account.Segment_Text_stamped__c , Account.Segment_Text_stamped__c))))))))</formula>
    <inlineHelpText>Deprecated--use Finance Segment instead.</inlineHelpText>
    <label>[DON&apos;T USE] Segment (Price Book)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Send_Virtual_Bell__c.field-meta.xml
<CustomField>
    <fullName>Send_Virtual_Bell__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This is to enable Order Ops to turn off Virtual Bell for transactions for any specific reason</description>
    <inlineHelpText>Unchecking this will not fire Virtual Bell for this transaction</inlineHelpText>
    <label>Send Virtual Bell</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Stripe_Subscription_Id__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Subscription_Id__c</fullName>
    <description>Stripe Subscription Id associated with an opportunity on acct</description>
    <label>Stripe Subscription Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Trial.recordType-meta.xml
<RecordType>
    <fullName>Trial</fullName>
    <active>true</active>
    <businessProcess>Standard Opportunities</businessProcess>
    <label>Trial</label>
</RecordType>

force-app/main/default/classes/GS_OpportunityPBConversionService.cls
public with sharing class GS_OpportunityPBConversionService {
    
  @TestVisible private Map<Id, Opportunity> oldOppMap;
  @TestVisible private List<Opportunity> newOppList;
  @TestVisible private GS_OpportunityCacheService cache;

    public GS_OpportunityPBConversionService(Map<Id, Opportunity> oldOppMap, List<Opportunity> newOppList, GS_OpportunityCacheService cache){
        this.oldOppMap  = oldOppMap;
        this.newOppList = newOppList;
        this.cache      = cache;
    }

    public void readyToShipOrClosedWon(){
        Map<Id,Opportunity> virtualBellOpptyMap = new Map<Id, Opportunity>();

        // Check if trigger.newMap is eligible to push to NS
        for(Opportunity opp : this.newOppList){
            //TODO - include backup to allow for Send Virtual Bell checkbox to trigger the logic a secondary time if necessary
            if(opp.StageName == 'Orders Processing' || opp.StageName == 'Closed Won') {
                if(opp.Send_Virtual_Bell__c){
                    virtualBellOpptyMap.put(opp.Id, opp);
                }
            }
        }
        if(virtualBellOpptyMap.size() > 0){
            (new GS_OpportunityEventPublisherService()).createR2ShipCWPlatformEvent(virtualBellOpptyMap);
        }
    }

    public void processContractUpdates(){
        // Commented below Query as the Account Map is not being used anywhere
        //Map<Id, Account> accountMap = linkContracts(newOpptyMap, oldOpptyMap);
        updateContractBasedFields();
    }

    public void updateContractBasedFields(){

        Set<Id> contractIds = new Set<Id>();
        for(Opportunity opp : this.newOppList) {
            contractIds.add(opp.ContractId);
            if (this.oldOppMap.get(opp.Id).netsuite_conn__From_Contract__c != opp.netsuite_conn__From_Contract__c && opp.netsuite_conn__From_Contract__c != null) {
               contractIds.add(opp.netsuite_conn__From_Contract__c);
            }
            if (this.oldOppMap.get(opp.Id).netsuite_conn__From_Contract__c != opp.netsuite_conn__From_Contract__c && opp.netsuite_conn__From_Contract__c == null) {
                opp.Original_Approved_Discount__c = Null;
            }
        }
        if (!contractIds.isEmpty()) {
        Map<Id, Contract> contractsMap = new Map<Id, Contract>((new GS_ContractSelector()).getContractsWithOppDataById(new List<Id>(contractIds)));

            for (Opportunity oppty : this.newOppList) {
                if (contractsMap.containsKey(oppty.netsuite_conn__From_Contract__c)) {
                    Contract fromContract = contractsMap.get(oppty.netsuite_conn__From_Contract__c);
                    oppty.Original_Approved_Discount__c = fromContract.Original_Approved_Discount__c;
                }
                Opportunity oldOpp = this.oldOppMap.get(oppty.Id);
                oppty.Contract = contractsMap.get(oppty.ContractId);

                if (oppty.ContractId != null) {
                    /*
                    PlaceHolder for Future Changes if needed
                    *
                    */
                } else {
                    // will not have contract
                    if((oppty.netsuite_conn__Bill_To_Tier__c == null && HelperClass.isChanged(oppty, oldOpp, Schema.Opportunity.netsuite_conn__Bill_To_Tier__c)) 
                        || (oppty.License_Term_Approval_Status__c == 'Approved' && HelperClass.isChanged(oppty, oldOpp, Schema.Opportunity.License_Term_Approval_Status__c))){

                        /* Replaces Node 'Contract Unlinked' */
                        oppty.Approved_Discount__c = 10;
                    }

                    
                    if (HelperClass.isChanged(oppty, oldOpp, Schema.Opportunity.StageName) && oppty.Type == 'Revenue Opportunity' && (oppty.StageName == 'Ready to Ship' || oppty.StageName == 'Closed Won')) {
                        
                        if(!oppty.Adjust_License_Start_Date__c && (oppty.License_Start_Date__c == null || oppty.License_End_Date__c == null || oppty.License_Start_Date__c != oppty.CloseDate)) {
                            oppty.CloseDate = Date.today();
                            oppty.License_Start_Date__c = oppty.CloseDate;
                            oppty.License_End_Date__c = Date.newInstance((Integer)(oppty.CloseDate.year() + Math.floor(oppty.CloseDate.month() + oppty.License_Term__c - 1)/12), 
                                                                        Math.mod((Integer)(oppty.CloseDate.month() + oppty.License_Term__c - 1), 12) + 1, 
                                                                        oppty.CloseDate.day() - 1);
                        }
                        
                        if(oppty.Adjust_License_Start_Date__c && oppty.License_Start_Date__c != null && oppty.License_End_Date__c == null) {
                            oppty.License_End_Date__c = Date.newInstance((Integer)(oppty.License_Start_Date__c.year() + Math.floor(oppty.License_Start_Date__c.month() + oppty.License_Term__c - 1)/12), 
                                                                        Math.mod((Integer)(oppty.License_Start_Date__c.month() + oppty.License_Term__c - 1), 12) + 1, 
                                                                        oppty.License_Start_Date__c.day() - 1);
                        }
                    }
                    
                    // Anil Bogadi Auto-Populate License End Date for Promos - GTMS-3963
                    
                    if( HelperClass.isChanged(oppty, oldOpp, Schema.Opportunity.StageName) && oppty.StageName == 'Closed Won' && oppty.Promo_Reason__c == 'Beta Program' && oppty.Type == 'Promo Opportunity') {
                            oppty.License_End_Date__c = Date.newInstance((Integer)(oppty.CloseDate.year() + Math.floor(oppty.CloseDate.month() + oppty.License_Term__c - 1)/12), 
                                                                        Math.mod((Integer)(oppty.CloseDate.month() + oppty.License_Term__c - 1), 12) + 1, 
                                                                        oppty.CloseDate.day());
                        }
                }

                // moved from opportunity helper - beforeUpdateOnly
                if(oppty.Type == 'Revenue Opportunity' 
                    && oppty.License_Term__c != oldOpp.License_Term__c 
                    && oppty.License_Term__c < oldOpp.License_Term__c) {

                    oppty.Approved_Discount__c = null;
                }
            }
        }
    }

    public void closingOppWithStripeTrialOrExpessFinanceApproval() {
        for (Opportunity oppty : this.newOppList) {
            if(oppty.StageName == 'Closing' && ((oppty.Type == 'Free Trial Opportunity' || oppty.Type == 'Promo Opportunity' || oppty.Stripe_Subscription_Id__c != null) 
                || (oppty.Type == 'Revenue Opportunity' && oppty.Finance_Notes__c != null 
                && ((oppty.Express_Agreement_Accepted_Date__c <> null && oppty.Price_Book_Name__c != null && oppty.Configuration_Segment__c == 'Express') || (oppty.Amount >0 && oppty.Balance_Due__c < 10))))){
                /* Replaces Node 'Closing Opp with Stripe/Trial OR Express/Finance Approval' */
                oppty.Overwrite_Validation_Rule__c = true;
                oppty.Probability = 98;
                oppty.StageName = 'Orders Processing';
            }
        }
    }

    /*
     * // Commented below Query as the Account Map is not being used anywhere
     * public static Map<Id, Account> linkContracts( Map<Id, Opportunity> newOpptyMap, Map<Id, Opportunity> oldOpptyMap ){

        Map<Id, Account> accountMap = new Map<Id, Account>([
            SELECT Id, Latest_Active_Contract__c, 
                   Latest_Active_Contract__r.EndDate, Segment__c 
            FROM Account
            WHERE Id IN (SELECT AccountId FROM Opportunity WHERE Id IN :newOpptyMap.keySet())
        ]);
        return accountMap;
	
    }*/
}