force-app/main/default/objects/Account/fields/Latest_Partner_Account_Interaction__c.field-meta.xml
<CustomField>
    <fullName>Latest_Partner_Account_Interaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>GTMS-6421: This field will be used as an account level identifier of the most recent partner account interaction.</description>
    <label>Latest Partner Account Interaction</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Latest Partner Account Interaction)</relationshipLabel>
    <relationshipName>Accounts3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Latest_Partner_Program_Interaction__c.field-meta.xml
<CustomField>
    <fullName>Latest_Partner_Program_Interaction__c</fullName>
    <description>GTMS-6421</description>
    <label>Latest Partner Program Interaction</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Organization_Size__c.field-meta.xml
<CustomField>
    <fullName>Organization_Size__c</fullName>
    <description>Number of employees or students</description>
    <inlineHelpText>Number of employees or students</inlineHelpText>
    <label>Organization Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 - 99</fullName>
            </value>
            <value>
                <fullName>100 - 499</fullName>
            </value>
            <value>
                <fullName>500 - 999</fullName>
            </value>
            <value>
                <fullName>1000 - 4999</fullName>
            </value>
            <value>
                <fullName>5000+</fullName>
            </value>
            <value>
                <fullName>0</fullName>
                <isActive>false</isActive>
                <label>0</label>
            </value>
            <value>
                <fullName>1-99</fullName>
                <isActive>false</isActive>
                <label>1-99</label>
            </value>
            <value>
                <fullName>1/1/1999 12:00:00 AM</fullName>
                <isActive>false</isActive>
                <label>1/1/1999 12:00:00 AM</label>
            </value>
            <value>
                <fullName>10</fullName>
                <isActive>false</isActive>
                <label>10</label>
            </value>
            <value>
                <fullName>100 - 999</fullName>
                <isActive>false</isActive>
                <label>100 - 999</label>
            </value>
            <value>
                <fullName>100-499</fullName>
                <isActive>false</isActive>
                <label>100-499</label>
            </value>
            <value>
                <fullName>1000+</fullName>
                <isActive>false</isActive>
                <label>1000+</label>
            </value>
            <value>
                <fullName>1000-4999</fullName>
                <isActive>false</isActive>
                <label>1000-4999</label>
            </value>
            <value>
                <fullName>10000+</fullName>
                <isActive>false</isActive>
                <label>10000+</label>
            </value>
            <value>
                <fullName>11</fullName>
                <isActive>false</isActive>
                <label>11</label>
            </value>
            <value>
                <fullName>13</fullName>
                <isActive>false</isActive>
                <label>13</label>
            </value>
            <value>
                <fullName>200</fullName>
                <isActive>false</isActive>
                <label>200</label>
            </value>
            <value>
                <fullName>201-500</fullName>
                <isActive>false</isActive>
                <label>201-500</label>
            </value>
            <value>
                <fullName>21</fullName>
                <isActive>false</isActive>
                <label>21</label>
            </value>
            <value>
                <fullName>22</fullName>
                <isActive>false</isActive>
                <label>22</label>
            </value>
            <value>
                <fullName>29</fullName>
                <isActive>false</isActive>
                <label>29</label>
            </value>
            <value>
                <fullName>34</fullName>
                <isActive>false</isActive>
                <label>34</label>
            </value>
            <value>
                <fullName>36161</fullName>
                <isActive>false</isActive>
                <label>36161</label>
            </value>
            <value>
                <fullName>42</fullName>
                <isActive>false</isActive>
                <label>42</label>
            </value>
            <value>
                <fullName>495 - 1000</fullName>
                <isActive>false</isActive>
                <label>495 - 1000</label>
            </value>
            <value>
                <fullName>496 - 1000</fullName>
                <isActive>false</isActive>
                <label>496 - 1000</label>
            </value>
            <value>
                <fullName>497 - 1000</fullName>
                <isActive>false</isActive>
                <label>497 - 1000</label>
            </value>
            <value>
                <fullName>498 - 1000</fullName>
                <isActive>false</isActive>
                <label>498 - 1000</label>
            </value>
            <value>
                <fullName>499 - 1000</fullName>
                <isActive>false</isActive>
                <label>499 - 1000</label>
            </value>
            <value>
                <fullName>500 - 1000</fullName>
                <isActive>false</isActive>
                <label>500 - 1000</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <description>Account type for partners - resellers, referral partners, corporate partners</description>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/Clari_Opp__c/Clari_Opp__c.object-meta.xml
<CustomObject>
    <label>Clari Opp</label>
    <nameField>
        <displayFormat>CO-{0000}</displayFormat>
        <label>Clari Opp Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clari Opps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Clari_Opp__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Clari Opps</relationshipLabel>
    <relationshipName>Clari_Opps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Original_Contracted_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Original_Contracted_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original Contracted Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Original_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Original_Reseller_ID__c.field-meta.xml
<CustomField>
    <fullName>Original_Reseller_ID__c</fullName>
    <formula>Original_Contracted_Opportunity__r.Reseller_Partner__r.X18_Digit_Account_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Original Reseller ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Clari_Opp__c.field-meta.xml
<CustomField>
    <fullName>Clari_Opp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clari Opp</label>
    <referenceTo>Clari_Opp__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Reseller_Partner__c.field-meta.xml
<CustomField>
    <fullName>Reseller_Partner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The reseller partner associated with this opportunity.</description>
    <inlineHelpText>Reseller partner registered with this opportunity.</inlineHelpText>
    <label>Reseller Partner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Record_Type__c</field>
            <operation>equals</operation>
            <value>Partner</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Reseller End-Customer Opportunities</relationshipLabel>
    <relationshipName>Reseller_End_Customer_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/clariOppTests.cls
@IsTest
private class clariOppTests {
    @IsTest
    private static void createTestData(){
        //create test account
        Account acc              = new Account();
        acc.Name                 = 'Clari Test Acc';
        acc.Organization_Size__c = '1 - 99';
        acc.Industry             = 'Construction';
        acc.BillingCountry       = 'United States';
        acc.BillingState         = 'California';
        insert acc;
        
        
        //create test opportunity
        Opportunity opp = new Opportunity();
        opp.Name        = 'Clari Test Opp';
        opp.AccountId   = acc.Id;
        opp.CloseDate   = date.today();
        opp.StageName   = 'Incubate';
        insert opp;
        
        //query for created Clari Opp and inserted Opp
        Clari_Opp__c clariOpp = [SELECT Id,
                                		Opportunity__c
                                		FROM Clari_Opp__c WHERE Opportunity__c = :opp.Id];
        
        Opportunity updatedOpp = [SELECT Id, 
                                  		 Clari_Opp__c
                                 		 FROM Opportunity WHERE Id = :opp.Id];
        
        
        
        System.assertEquals(updatedOpp.Id, clariOpp.Opportunity__c);
        
    }
    
    @isTest private static void testPArtnerPopulator(){

        List <Account> accsToInsert = new List <Account>();
        Test.startTest();
        Account acc = new Account();
        acc.Name = 'End Customer Test';
        acc.Organization_Size__c = '1 - 99';
        acc.Industry = 'Agriculture';
        acc.BillingState = 'California';
        acc.BillingCountry = 'United States';
        accsToInsert.add(acc);

        Account accReseller = new Account();
        accReseller.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Partner').getRecordTypeId();
                                                      
        accReseller.Name = 'Reseller Test';
        accReseller.Organization_Size__c = '1 - 99';
        accReseller.BillingState = 'California';
        accReseller.BillingCountry = 'United States';
        accsToInsert.add(accReseller);

        insert accsToInsert;
        
        //Update Account with partner info
        acc.Latest_Partner_Account_Interaction__c = accReseller.id;
        acc.Latest_Partner_Program_Interaction__c = 'Resale';
        update acc;

        Opportunity opp = new Opportunity();
        opp.Name = 'Original Oppty';
        opp.AccountId = acc.Id;
        opp.CloseDate = Date.today();
        opp.StageName = 'Closed Won';
        opp.Reseller_Partner__c = accReseller.Id;
        insert opp;

        Contract con = new Contract();
        con.AccountId = acc.Id;
        con.Original_Contracted_Opportunity__c = opp.Id;
        con.StartDate = Date.today();
        con.EndDate = Date.today() + 365;
     
        insert con;
       Contract newContract = [SELECT id, Name, Original_Reseller_ID__c, StartDate, EndDate, Original_Contracted_Opportunity__c, SBQQ__Opportunity__r.AccountId, ContractNumber FROM CONTRACT LIMIT 1];

        
        
        Opportunity amendOpp = new Opportunity();
        amendOpp.Name = 'Amendment Oppty';
        amendOpp.AccountId = acc.Id;
        amendOpp.CloseDate = Date.today() + 90;
        amendOpp.ContractId = newContract.Id;
        //Zak
        amendOpp.SBQQ__AmendedContract__c = newContract.Id;
        
        amendOpp.StageName = 'Incubate';
        amendOpp.Reseller_Partner__c = accReseller.ID;
        OpportunityTriggerHandler.resetAll();
        insert amendOpp;
        
        Opportunity renOpps = [SELECT id, Name, Reseller_Partner__c, ContractId from Opportunity WHERE id = :amendOpp.Id LIMIT 1];
        
        System.assertEquals(amendOpp.Reseller_Partner__c, accReseller.id);
        Test.stopTest();
    }

}