force-app/main/default/objects/Account/fields/Latest_Active_Contract__c.field-meta.xml
<CustomField>
    <fullName>Latest_Active_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Latest Active Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;New&quot;</defaultValue>
    <description>This is a roll up from the status of the contacts of the account. 
Eg. If there is any disqualified contact -&gt; Disqualified and so on.</description>
    <label>Account Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Contact Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Attempting</fullName>
            </value>
            <value>
                <fullName>Demo Scheduled</fullName>
            </value>
            <value>
                <fullName>Demo No Show</fullName>
            </value>
            <value>
                <fullName>Demo Completed - Not Qualified</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Retouch - Did Not Connect</fullName>
            </value>
            <value>
                <fullName>Retouch - Confirmed No Opportunity</fullName>
                <label>Connected-Disqualified</label>
            </value>
            <value>
                <fullName>Send Small Fleet Link</fullName>
            </value>
            <value>
                <fullName>Small Fleet Link Sent</fullName>
            </value>
            <value>
                <fullName>Inactive - See Parent Account</fullName>
            </value>
            <value>
                <fullName>Small Fleet Link Failed - Invalid Email</fullName>
            </value>
            <value>
                <fullName>Small Fleet Link Pending - Manual Review</fullName>
            </value>
            <value>
                <fullName>Faulty Lead</fullName>
            </value>
            <value>
                <fullName>Do Not Contact - Open Conversation</fullName>
            </value>
            <value>
                <fullName>Contact Established</fullName>
                <isActive>false</isActive>
                <label>Contact Established</label>
            </value>
            <value>
                <fullName>Create Webstore Opportunity</fullName>
                <isActive>false</isActive>
                <label>Create Webstore Opportunity</label>
            </value>
            <value>
                <fullName>Delete Account</fullName>
                <isActive>false</isActive>
                <label>Delete Account</label>
            </value>
            <value>
                <fullName>Delete Contact Only</fullName>
                <isActive>false</isActive>
                <label>Delete Contact Only</label>
            </value>
            <value>
                <fullName>GDPR Delete</fullName>
                <isActive>false</isActive>
                <label>GDPR Delete</label>
            </value>
            <value>
                <fullName>Inactive - No Longer There</fullName>
                <isActive>false</isActive>
                <label>Inactive - No Longer There</label>
            </value>
            <value>
                <fullName>Multiple Campaign Interactions</fullName>
                <isActive>false</isActive>
                <label>Multiple Campaign Interactions</label>
            </value>
            <value>
                <fullName>No Authority</fullName>
                <isActive>false</isActive>
                <label>No Authority</label>
            </value>
            <value>
                <fullName>Opt out - Do not contact</fullName>
                <isActive>false</isActive>
                <label>Opt out - Do not contact</label>
            </value>
            <value>
                <fullName>Webstore Opportunity Created</fullName>
                <isActive>false</isActive>
                <label>Webstore Opportunity Created</label>
            </value>
            <value>
                <fullName>Webstore Opportunity Creation In Progress</fullName>
                <isActive>false</isActive>
                <label>Webstore Opportunity Creation In Progress</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SBQQ__PrimaryQuote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__PrimaryQuote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Points to primary quote on this opportunity.</description>
    <inlineHelpText>Salesforce CPQ uses this to point to the primary quote on this opportunity.</inlineHelpText>
    <label>Primary Quote</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>SBQQ__Quote__c.SBQQ__Opportunity2__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>PrimaryOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Shipping_Address__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Address__c</fullName>
    <description>Opportunity shipping address (use in place of  quote ship-to)</description>
    <formula>Opportunity.Shipping_Address_NEW__r.Shipping_Address_Line_1__c  &amp;&quot;,&quot;&amp; BR()&amp;
 Opportunity.Shipping_Address_NEW__r.Shipping_City__c &amp;&quot;,&quot;&amp;BR()&amp;
TEXT( Opportunity.Shipping_Address_NEW__r.Shipping_State__c )&amp;IF(ISBLANK(TEXT(Opportunity.Shipping_Address_NEW__r.Shipping_State__c)),&quot;&quot;,&quot;, &quot;)&amp; Opportunity.Shipping_Address_NEW__r.Shipping_Zip_Code__c&amp;&quot;, &quot;&amp;BR()&amp;TEXT(Opportunity.Shipping_Address_NEW__r.Shipping_Country__c)</formula>
    <inlineHelpText>Opportunity shipping address</inlineHelpText>
    <label>Shipping Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Request_Tracker__c/Request_Tracker__c.object-meta.xml
<CustomObject>
    <label>Request Tracker</label>
    <nameField>
        <displayFormat>RT-{0000}</displayFormat>
        <label>Request Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request Tracker</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Request_Tracker__c/fields/OrderId__c.field-meta.xml
<CustomField>
    <fullName>OrderId__c</fullName>
    <externalId>true</externalId>
    <label>OrderId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Request_Tracker__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <isActive>false</isActive>
                <label>Open</label>
            </value>
            <value>
                <fullName>Success</fullName>
                <isActive>false</isActive>
                <label>Success</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request_Tracker__c/fields/Step_Status__c.field-meta.xml
<CustomField>
    <fullName>Step_Status__c</fullName>
    <label>Step Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Request_Tracker__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>WEBSTORE_ADD_ON_PURCHASE</fullName>
            </value>
            <value>
                <fullName>WEBSTORE_FIRST_PURCHASE</fullName>
            </value>
            <value>
                <fullName>WEBSTORE_COMMERCIAL_CHECKOUT_LINK</fullName>
            </value>
            <value>
                <fullName>WEBSTORE_DIGITAL_RENEWAL</fullName>
            </value>
            <value>
                <fullName>WEBSTORE_MIDMARKET_PLUS_CHECKOUT_LINK</fullName>
            </value>
            <value>
                <fullName>WEBSTORE_FREE_TRIAL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account X</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Address__c/Shipping_Address__c.object-meta.xml
<CustomObject>
    <label>Shipping Address</label>
    <nameField>
        <label>Shipping Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipping Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipping_Address__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Shipping Addresses</relationshipLabel>
    <relationshipName>Shipping_Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MidMarketPlusCheckoutHandlerTest.cls
@isTest
private class MidMarketPlusCheckoutHandlerTest {
    @TestSetup
    static void setupTestData() {
        // Create test account
        Account testAccount = MercuryPhase2DataFactory.createAccount('Test Account', true);
        
        // Create test contact
        Contact testContact = MercuryPhase2DataFactory.createContact(testAccount.Id, true);
        
        // Create test shipping address
        Shipping_Address__c testShippingAddress = MercuryPhase2DataFactory.createShippingAddress(testAccount.Id, testContact.Id, true);

        // Create Opportunity
        Opportunity testOpp = new Opportunity(
            Name = 'Test Opportunity',
            AccountId = testAccount.Id,
            StageName = 'Prospecting',
            CloseDate = Date.today().addDays(30)
        );
        Test.startTest();
        TriggerHandler.bypass('OpportunityTriggerHandler');
        TriggerHandler.bypass('Product2TriggerHandler');
        TriggerHandler.bypass('SBQQ__QuoteTriggerHandler');
        TriggerHandler.bypass('SBQQ__QuoteLineTriggerHandler');
        SBQQ.TriggerControl.disable();
        
        insert testOpp;
        
        // Create test contract
        Contract testContract = MercuryPhase2DataFactory.createContract(testAccount.Id, true);

        Id pricebookId = Test.getStandardPricebookId();

        // Create Product
        Product2 testProduct = MercuryPhase2DataFactory.createProduct(true);
           
        //Create PriceBookEntries
        List<PricebookEntry> pricebookEntries = new List<PricebookEntry>();
        PricebookEntry vg33PB = new PricebookEntry(Pricebook2Id = pricebookId, Product2Id = testProduct.Id, UnitPrice = 10000, IsActive = true);
        pricebookEntries.add(vg33PB);

        insert pricebookEntries;
        
        // Create Quote
        SBQQ__Quote__c testQuote = MercuryPhase2DataFactory.createQuote(testAccount.Id, testOpp.Id, true);
        // Create Subscription with the quote line
        SBQQ__QuoteLine__c testQuoteLine = MercuryPhase2DataFactory.createQuoteLines(testAccount.Id, testQuote.Id, String.valueOf(testShippingAddress.Id), String.valueOf(testProduct.Id), String.valueOf(vg33PB.Id), 10000, 2, true);
        MercuryPhase2DataFactory.createSubscription(testAccount.Id, testContract.Id, testQuoteLine.Id, true);

        //activate the contract
        testContract.Status = 'Activated';
        testContract.SBQQ__Opportunity__c = testOpp.Id;
        testContract.ActivatedDate = Date.today();
        update testContract;

        testAccount.Latest_Active_Contract__c = testContract.Id;
        TriggerHandler.bypass('AccountTriggerHandler');
        update testAccount;
    }
    
    @isTest
    static void testProcessTransaction_Success() {
        // Get the test tracker
        Account testAccount = [SELECT Id FROM Account WHERE Name = 'Test Account' LIMIT 1];
        Contract testContract = [SELECT Id FROM Contract WHERE AccountId = :testAccount.Id LIMIT 1];
        Shipping_Address__c testShippingAddress = [SELECT Id FROM Shipping_Address__c WHERE Account__c = :testAccount.Id LIMIT 1];
        SBQQ__Quote__c testQuote = [SELECT Id FROM SBQQ__Quote__c WHERE SBQQ__Account__c = :testAccount.Id LIMIT 1];
        Opportunity testOpp = [SELECT Id FROM Opportunity WHERE AccountId = :testAccount.Id LIMIT 1];
        
        // Create test request tracker
        OrderPayload payload = MercuryPhase2DataFactory.createMidMarketPlusPayload(testAccount.Id, testOpp.Id, 'pm_1QxExtIbzZlMbYFSSzBD9pvE', 'seti_1QxEvzIbzZlMbYFSg8bGvUG3', 'ch_3QwsPIIbzZlMbYFS2iSvIg1I');
        
        Request_Tracker__c tracker = new Request_Tracker__c(
            OrderId__c = 'TEST-123',
            Transaction_Type__c = 'WEBSTORE_MIDMARKET_PLUS_CHECKOUT_LINK',
            Account_Id__c = testAccount.Id,
            Request__c = JSON.serialize(payload),
            Status__c = 'Received',
            Step_Status__c = 'Step-1'
        );

        insert tracker;

        try {
            Test.startTest();
            OrderTransactionHandler transactionHandler = OrderTransactionHandlerFactory.getHandler(tracker.Transaction_Type__c);
            transactionHandler.processOrder(tracker);
            Test.stopTest();
        } catch (Exception e) {
            System.debug('Error: ' + e.getMessage());
        }
    }
    
    @isTest
    static void testProcessTransaction_InvalidPayload() {
        // Get the test tracker
        Account testAccount = [SELECT Id FROM Account WHERE Name = 'Test Account' LIMIT 1];
        
        Request_Tracker__c tracker = new Request_Tracker__c(
            OrderId__c = 'TEST-123',
            Transaction_Type__c = 'WEBSTORE_MIDMARKET_PLUS_CHECKOUT_LINK',
            Account_Id__c = testAccount.Id,
            Request__c = 'invalid json',
            Status__c = 'Received',
            Step_Status__c = 'Step-1'
        );

        insert tracker;
        try {
            Test.startTest();
            OrderTransactionHandler transactionHandler = OrderTransactionHandlerFactory.getHandler(tracker.Transaction_Type__c);
            transactionHandler.processOrder(tracker);
            Test.stopTest();
        } catch (Exception e) {
            System.assert(e.getMessage() != null, 'Exception should be related to JSON parsing');
        }
       
    }

    @isTest
    static void testProcessAccount_Success() {
        // Get the test tracker
        Account testAccount = [SELECT Id FROM Account WHERE Name = 'Test Account' LIMIT 1];
        Opportunity testOpp = [SELECT Id FROM Opportunity WHERE AccountId = :testAccount.Id LIMIT 1];
        
        // Create test request tracker
        OrderPayload payload = MercuryPhase2DataFactory.createMidMarketPlusPayload(testAccount.Id, testOpp.Id, 'pm_1QxExtIbzZlMbYFSSzBD9pvE', 'seti_1QxEvzIbzZlMbYFSg8bGvUG3', 'ch_3QwsPIIbzZlMbYFS2iSvIg1I');
        
        Request_Tracker__c tracker = new Request_Tracker__c(
            OrderId__c = 'TEST-123',
            Transaction_Type__c = 'WEBSTORE_MIDMARKET_PLUS_CHECKOUT_LINK',
            Account_Id__c = testAccount.Id,
            Request__c = JSON.serialize(payload),
            Status__c = 'Received',
            Step_Status__c = 'Step-1'
        );

        insert tracker;

        try {
            Test.startTest();
            UpdateAccount updateAccount = new UpdateAccount(tracker,'Step-2',payload,0);
            OrderUtil.enqueueJobIfPossible(updateAccount);
            Test.stopTest();
        } catch (Exception e) {
            System.debug('Error: ' + e.getMessage());
        }
    }

    @isTest
    static void testProcessOpportunity_Success() {
        // Get the test tracker
        Account testAccount = [SELECT Id FROM Account WHERE Name = 'Test Account' LIMIT 1];
        Opportunity testOpp = [SELECT Id FROM Opportunity WHERE AccountId = :testAccount.Id LIMIT 1];
        
        // Create test request tracker
        OrderPayload payload = MercuryPhase2DataFactory.createMidMarketPlusPayload(testAccount.Id, testOpp.Id, 'pm_1QxExtIbzZlMbYFSSzBD9pvE', 'seti_1QxEvzIbzZlMbYFSg8bGvUG3', 'ch_3QwsPIIbzZlMbYFS2iSvIg1I');
        
        Request_Tracker__c tracker = new Request_Tracker__c(
            OrderId__c = 'TEST-123',
            Transaction_Type__c = 'WEBSTORE_MIDMARKET_PLUS_CHECKOUT_LINK',
            Account_Id__c = testAccount.Id,
            Request__c = JSON.serialize(payload),
            Status__c = 'Received',
            Step_Status__c = 'Step-1'
        );

        insert tracker;

        try {
            Test.startTest();
            MidMarketCheckoutOpportunityUpdate updateOpportunity = new MidMarketCheckoutOpportunityUpdate(tracker,'Step-3',payload,0);
            OrderUtil.enqueueJobIfPossible(updateOpportunity);
            Test.stopTest();
        } catch (Exception e) {
            System.debug('Error: ' + e.getMessage());
        }
    }
    
    @isTest
    static void testProcessOpportunity_NewInstanceRetry() {
        // Get the test tracker
        Account testAccount = [SELECT Id FROM Account WHERE Name = 'Test Account' LIMIT 1];
        Opportunity testOpp = [SELECT Id FROM Opportunity WHERE AccountId = :testAccount.Id LIMIT 1];
        
        // Create test request tracker
        OrderPayload payload = MercuryPhase2DataFactory.createMidMarketPlusPayload(testAccount.Id, testOpp.Id, 'pm_1QxExtIbzZlMbYFSSzBD9pvE', 'seti_1QxEvzIbzZlMbYFSg8bGvUG3', 'ch_3QwsPIIbzZlMbYFS2iSvIg1I');
        
        Request_Tracker__c tracker = new Request_Tracker__c(
            OrderId__c = 'TEST-123',
            Transaction_Type__c = 'WEBSTORE_MIDMARKET_PLUS_CHECKOUT_LINK',
            Account_Id__c = testAccount.Id,
            Request__c = JSON.serialize(payload),
            Status__c = 'Received',
            Step_Status__c = 'Step-1'
        );

        insert tracker;

        try {
            Test.startTest();
            MidMarketCheckoutOpportunityUpdate updateOpportunity = new MidMarketCheckoutOpportunityUpdate(tracker,'Step-3',payload,0);
            updateOpportunity.createLog('Finished processing: Opportunity:');
            updateOpportunity.newInstanceWithRetry(2);
            Test.stopTest();
        } catch (Exception e) {
            System.debug('Error: ' + e.getMessage());
        }
    }


    @isTest
    static void testProcessQuote_Success() {
        // Get the test tracker
        Account testAccount = [SELECT Id FROM Account WHERE Name = 'Test Account' LIMIT 1];
        Opportunity testOpp = [SELECT Id FROM Opportunity WHERE AccountId = :testAccount.Id LIMIT 1];
        SBQQ__Quote__c testQuote = [SELECT Id FROM SBQQ__Quote__c WHERE SBQQ__Account__c = :testAccount.Id LIMIT 1];
        
        testOpp.SBQQ__PrimaryQuote__c = testQuote.Id;
        TriggerHandler.bypass('OpportunityTriggerHandler');
        update testOpp;
        TriggerHandler.clearBypass('OpportunityTriggerHandler');
        // Create test request tracker
        OrderPayload payload = MercuryPhase2DataFactory.createMidMarketPlusPayload(testAccount.Id, testOpp.Id, 'pm_1QxExtIbzZlMbYFSSzBD9pvE', 'seti_1QxEvzIbzZlMbYFSg8bGvUG3', 'ch_3QwsPIIbzZlMbYFS2iSvIg1I');
        
        Request_Tracker__c tracker = new Request_Tracker__c(
            OrderId__c = 'TEST-123',
            Transaction_Type__c = 'WEBSTORE_MIDMARKET_PLUS_CHECKOUT_LINK',
            Account_Id__c = testAccount.Id,
            Request__c = JSON.serialize(payload),
            Status__c = 'Received',
            Step_Status__c = 'Step-1'
        );

        insert tracker;

        try {
            Test.startTest();
            MidMarketCheckoutQuoteUpdate updateQuote = new MidMarketCheckoutQuoteUpdate(tracker,'Step-4',payload,0);
            
            OrderUtil.enqueueJobIfPossible(updateQuote);
            updateQuote.updateQuoteViaRest(null,null);
        } catch (Exception e) {
            System.debug('Error: ' + e.getMessage());
        }
    }

    @isTest
    static void testProcessQuote_NewInstanceRetry() {
        // Get the test tracker
        Account testAccount = [SELECT Id FROM Account WHERE Name = 'Test Account' LIMIT 1];
        Opportunity testOpp = [SELECT Id FROM Opportunity WHERE AccountId = :testAccount.Id LIMIT 1];
        
        // Create test request tracker
        OrderPayload payload = MercuryPhase2DataFactory.createMidMarketPlusPayload(testAccount.Id, testOpp.Id, 'pm_1QxExtIbzZlMbYFSSzBD9pvE', 'seti_1QxEvzIbzZlMbYFSg8bGvUG3', 'ch_3QwsPIIbzZlMbYFS2iSvIg1I');
        
        Request_Tracker__c tracker = new Request_Tracker__c(
            OrderId__c = 'TEST-123',
            Transaction_Type__c = 'WEBSTORE_MIDMARKET_PLUS_CHECKOUT_LINK',
            Account_Id__c = testAccount.Id,
            Request__c = JSON.serialize(payload),
            Status__c = 'Received',
            Step_Status__c = 'Step-1'
        );

        insert tracker;

        try {
            Test.startTest();
            MidMarketCheckoutQuoteUpdate updateQuote = new MidMarketCheckoutQuoteUpdate(tracker,'Step-4',payload,0);
            updateQuote.createLog('Finished processing: Quote:');
            updateQuote.newInstanceWithRetry(2);
            Test.stopTest();
        } catch (Exception e) {
            System.debug('Error: ' + e.getMessage());
        }
    }

    @isTest
    static void testProcessWorkatoService_Success() {
        // Get the test tracker
        Account testAccount = [SELECT Id FROM Account WHERE Name = 'Test Account' LIMIT 1];
        Opportunity testOpp = [SELECT Id FROM Opportunity WHERE AccountId = :testAccount.Id LIMIT 1];
        
        // Create test request tracker
        OrderPayload payload = MercuryPhase2DataFactory.createMidMarketPlusPayload(testAccount.Id, testOpp.Id, 'pm_1QxExtIbzZlMbYFSSzBD9pvE', 'seti_1QxEvzIbzZlMbYFSg8bGvUG3', 'ch_3QwsPIIbzZlMbYFS2iSvIg1I');
        
        Request_Tracker__c tracker = new Request_Tracker__c(
            OrderId__c = 'TEST-123',
            Transaction_Type__c = 'WEBSTORE_MIDMARKET_PLUS_CHECKOUT_LINK',
            Account_Id__c = testAccount.Id,
            Request__c = JSON.serialize(payload),
            Status__c = 'Received',
            Step_Status__c = 'Step-1'
        );

        insert tracker;

        try {
            Test.startTest();
            // Set mock for HTTP callout
            Test.setMock(HttpCalloutMock.class, new MidMarketPlusMock(201));

            OrderResultToWorkatoService workatoService = new OrderResultToWorkatoService(tracker,'Step-4',payload,0);
            OrderUtil.enqueueJobIfPossible(workatoService);
            Test.stopTest();
        } catch (Exception e) {
            System.debug('Error: ' + e.getMessage());
        }
    }

    // Mock class for HTTP callout
    private class MidMarketPlusMock implements HttpCalloutMock {
        private Integer statusCode;
        
        public MidMarketPlusMock(Integer statusCode) {
            this.statusCode = statusCode;
        }
        
        public HTTPResponse respond(HTTPRequest req) {
            HTTPResponse res = new HTTPResponse();
            res.setStatusCode(statusCode);
            res.setBody('{"success": true}');
            return res;
        }
    }
}