force-app/main/default/objects/Account/fields/Latest_Active_Contract__c.field-meta.xml
<CustomField>
    <fullName>Latest_Active_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Latest Active Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;New&quot;</defaultValue>
    <description>This is a roll up from the status of the contacts of the account. 
Eg. If there is any disqualified contact -&gt; Disqualified and so on.</description>
    <label>Account Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Contact Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Attempting</fullName>
            </value>
            <value>
                <fullName>Demo Scheduled</fullName>
            </value>
            <value>
                <fullName>Demo No Show</fullName>
            </value>
            <value>
                <fullName>Demo Completed - Not Qualified</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Retouch - Did Not Connect</fullName>
            </value>
            <value>
                <fullName>Retouch - Confirmed No Opportunity</fullName>
                <label>Connected-Disqualified</label>
            </value>
            <value>
                <fullName>Send Small Fleet Link</fullName>
            </value>
            <value>
                <fullName>Small Fleet Link Sent</fullName>
            </value>
            <value>
                <fullName>Inactive - See Parent Account</fullName>
            </value>
            <value>
                <fullName>Small Fleet Link Failed - Invalid Email</fullName>
            </value>
            <value>
                <fullName>Small Fleet Link Pending - Manual Review</fullName>
            </value>
            <value>
                <fullName>Faulty Lead</fullName>
            </value>
            <value>
                <fullName>Do Not Contact - Open Conversation</fullName>
            </value>
            <value>
                <fullName>Contact Established</fullName>
                <isActive>false</isActive>
                <label>Contact Established</label>
            </value>
            <value>
                <fullName>Create Webstore Opportunity</fullName>
                <isActive>false</isActive>
                <label>Create Webstore Opportunity</label>
            </value>
            <value>
                <fullName>Delete Account</fullName>
                <isActive>false</isActive>
                <label>Delete Account</label>
            </value>
            <value>
                <fullName>Delete Contact Only</fullName>
                <isActive>false</isActive>
                <label>Delete Contact Only</label>
            </value>
            <value>
                <fullName>GDPR Delete</fullName>
                <isActive>false</isActive>
                <label>GDPR Delete</label>
            </value>
            <value>
                <fullName>Inactive - No Longer There</fullName>
                <isActive>false</isActive>
                <label>Inactive - No Longer There</label>
            </value>
            <value>
                <fullName>Multiple Campaign Interactions</fullName>
                <isActive>false</isActive>
                <label>Multiple Campaign Interactions</label>
            </value>
            <value>
                <fullName>No Authority</fullName>
                <isActive>false</isActive>
                <label>No Authority</label>
            </value>
            <value>
                <fullName>Opt out - Do not contact</fullName>
                <isActive>false</isActive>
                <label>Opt out - Do not contact</label>
            </value>
            <value>
                <fullName>Webstore Opportunity Created</fullName>
                <isActive>false</isActive>
                <label>Webstore Opportunity Created</label>
            </value>
            <value>
                <fullName>Webstore Opportunity Creation In Progress</fullName>
                <isActive>false</isActive>
                <label>Webstore Opportunity Creation In Progress</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SBQQ__PrimaryQuote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__PrimaryQuote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Points to primary quote on this opportunity.</description>
    <inlineHelpText>Salesforce CPQ uses this to point to the primary quote on this opportunity.</inlineHelpText>
    <label>Primary Quote</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>SBQQ__Quote__c.SBQQ__Opportunity2__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>PrimaryOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Trial_Status__c.field-meta.xml
<CustomField>
    <fullName>Trial_Status__c</fullName>
    <label>Trial Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Shipped</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Purchased</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Return In Process</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>Write-off</fullName>
            </value>
            <value>
                <fullName>Partial Purchase</fullName>
            </value>
            <value>
                <fullName>Partial Return</fullName>
            </value>
            <value>
                <fullName>Pending Return or Write-Off</fullName>
                <isActive>false</isActive>
                <label>Pending Return or Write-Off</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TrialResolutionOppty__c.field-meta.xml
<CustomField>
    <fullName>TrialResolutionOppty__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reference to a Trial&apos;s Revenue or Return opportunity.</description>
    <label>Revenue Opportunity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Opportunity.Type</field>
            <operation>equals</operation>
            <value>Revenue Opportunity, Free Trial Return, Revenue Opportunity - Bill Only</value>
        </filterItems>
        <filterItems>
            <field>Opportunity.StageName</field>
            <operation>notEqual</operation>
            <value>Closed Won</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunities (Trial Resolution Oppty)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Trial.recordType-meta.xml
<RecordType>
    <fullName>Trial</fullName>
    <active>true</active>
    <businessProcess>Standard Opportunities</businessProcess>
    <label>Trial</label>
</RecordType>

force-app/main/default/objects/Order/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>In Fulfillment</fullName>
            </value>
            <value>
                <fullName>Fulfilled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Return Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/Shipping_Address__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Address__c</fullName>
    <description>Opportunity shipping address (use in place of  quote ship-to)</description>
    <formula>Opportunity.Shipping_Address_NEW__r.Shipping_Address_Line_1__c  &amp;&quot;,&quot;&amp; BR()&amp;
 Opportunity.Shipping_Address_NEW__r.Shipping_City__c &amp;&quot;,&quot;&amp;BR()&amp;
TEXT( Opportunity.Shipping_Address_NEW__r.Shipping_State__c )&amp;IF(ISBLANK(TEXT(Opportunity.Shipping_Address_NEW__r.Shipping_State__c)),&quot;&quot;,&quot;, &quot;)&amp; Opportunity.Shipping_Address_NEW__r.Shipping_Zip_Code__c&amp;&quot;, &quot;&amp;BR()&amp;TEXT(Opportunity.Shipping_Address_NEW__r.Shipping_Country__c)</formula>
    <inlineHelpText>Opportunity shipping address</inlineHelpText>
    <label>Shipping Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Request_Tracker__c/Request_Tracker__c.object-meta.xml
<CustomObject>
    <label>Request Tracker</label>
    <nameField>
        <displayFormat>RT-{0000}</displayFormat>
        <label>Request Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request Tracker</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Request_Tracker__c/fields/Opportunity_Id__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Id__c</fullName>
    <label>Opportunity Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Request_Tracker__c/fields/OrderId__c.field-meta.xml
<CustomField>
    <fullName>OrderId__c</fullName>
    <externalId>true</externalId>
    <label>OrderId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Request_Tracker__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <isActive>false</isActive>
                <label>Open</label>
            </value>
            <value>
                <fullName>Success</fullName>
                <isActive>false</isActive>
                <label>Success</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request_Tracker__c/fields/Step_Status__c.field-meta.xml
<CustomField>
    <fullName>Step_Status__c</fullName>
    <label>Step Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Request_Tracker__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>WEBSTORE_ADD_ON_PURCHASE</fullName>
            </value>
            <value>
                <fullName>WEBSTORE_FIRST_PURCHASE</fullName>
            </value>
            <value>
                <fullName>WEBSTORE_COMMERCIAL_CHECKOUT_LINK</fullName>
            </value>
            <value>
                <fullName>WEBSTORE_DIGITAL_RENEWAL</fullName>
            </value>
            <value>
                <fullName>WEBSTORE_MIDMARKET_PLUS_CHECKOUT_LINK</fullName>
            </value>
            <value>
                <fullName>WEBSTORE_FREE_TRIAL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account X</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Address__c/Shipping_Address__c.object-meta.xml
<CustomObject>
    <label>Shipping Address</label>
    <nameField>
        <label>Shipping Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipping Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipping_Address__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Shipping Addresses</relationshipLabel>
    <relationshipName>Shipping_Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/InsertFreeTrialQuoteJobTest.cls
@isTest
private class InsertFreeTrialQuoteJobTest {

    @TestSetup
    static void setupTestData() {
        // Bypass triggers for test setup
        TriggerHandler.bypass('OpportunityTriggerHandler');
        TriggerHandler.bypass('Product2TriggerHandler');
        TriggerHandler.bypass('SBQQ__QuoteTriggerHandler');
        TriggerHandler.bypass('SBQQ__QuoteLineTriggerHandler');
        TriggerHandler.bypass('GS_AccountTriggerHandler');
        TriggerHandler.bypass('ShippingAddressTriggerHandler');
        SBQQ.TriggerControl.disable();
        
        // Create test account
        Account testAccount = MercuryPhase2DataFactory.createAccount('Test Account', true);
        
        // Create test contact
        Contact testContact = MercuryPhase2DataFactory.createContact(testAccount.Id, true);
        
        // Create test shipping address
        Shipping_Address__c testShippingAddress = MercuryPhase2DataFactory.createShippingAddress(testAccount.Id, testContact.Id, true);

        // Create Revenue Opportunity (Parent)
        Opportunity revenueOpp = new Opportunity(
            Name = 'Revenue Opportunity - Test',
            AccountId = testAccount.Id,
            StageName = 'Qualified',
            CloseDate = Date.today().addDays(30),
            Type = 'New Business',
            Amount = 10000
        );
        
        Test.startTest();
        insert revenueOpp;
        
        // Create test contract
        Contract testContract = MercuryPhase2DataFactory.createContract(testAccount.Id, true);

        Id pricebookId = Test.getStandardPricebookId();

        // Create Product
        Product2 testProduct = MercuryPhase2DataFactory.createProduct(true);
           
        // Create PriceBookEntries
        List<PricebookEntry> pricebookEntries = new List<PricebookEntry>();
        PricebookEntry vg33PB = new PricebookEntry(Pricebook2Id = pricebookId, Product2Id = testProduct.Id, UnitPrice = 10000, IsActive = true);
        pricebookEntries.add(vg33PB);

        insert pricebookEntries;
        
        // Create Quote for Revenue Opportunity
        SBQQ__Quote__c revenueQuote = MercuryPhase2DataFactory.createQuote(testAccount.Id, revenueOpp.Id, false);
        revenueQuote.SBQQ__Primary__c = true;
        revenueQuote.SBQQ__Status__c = 'Draft';
        insert revenueQuote;

        // Create Quote Line for Revenue Opportunity
        SBQQ__QuoteLine__c revenueQuoteLine = MercuryPhase2DataFactory.createQuoteLines(
            testAccount.Id, 
            revenueQuote.Id, 
            String.valueOf(testShippingAddress.Id), 
            String.valueOf(testProduct.Id), 
            String.valueOf(vg33PB.Id), 
            10000, 
            2, 
            true
        );
        
        // Activate the contract
        testContract.Status = 'Activated';
        testContract.SBQQ__Opportunity__c = revenueOpp.Id;
        testContract.ActivatedDate = Date.today();
        update testContract;

        testAccount.Latest_Active_Contract__c = testContract.Id;
        update testAccount;
        
        revenueOpp.SBQQ__PrimaryQuote__c = revenueQuote.Id;
        update revenueOpp;
        
        // Clear bypasses
        TriggerHandler.clearBypass('OpportunityTriggerHandler');
        TriggerHandler.clearBypass('Product2TriggerHandler');
        TriggerHandler.clearBypass('SBQQ__QuoteTriggerHandler');
        TriggerHandler.clearBypass('SBQQ__QuoteLineTriggerHandler');
        TriggerHandler.clearBypass('GS_AccountTriggerHandler');
        TriggerHandler.clearBypass('ShippingAddressTriggerHandler');
        SBQQ.TriggerControl.enable();
        Test.stopTest();
    }
    
    @isTest
    static void testInsertFreeTrialQuoteJob() {
        // Get test data
        Account testAccount = [SELECT Id FROM Account WHERE Name = 'Test Account' LIMIT 1];
        Opportunity revenueOpp = [SELECT Id FROM Opportunity WHERE Name = 'Revenue Opportunity - Test' LIMIT 1];
        
        // Create free trial opportunity
        Opportunity freeTrialOpp = new Opportunity(
            Name = 'Test Free Trial Opportunity',
            AccountId = testAccount.Id,
            RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Trial').getRecordTypeId(),
            StageName = 'Prospecting',
            CloseDate = Date.today().addDays(3),
            Type = 'Free Trial Opportunity',
            TrialResolutionOppty__c = revenueOpp.Id,
            Trial_Status__c = 'Open'
        );
        insert freeTrialOpp;
        
        // Create test payload
        Product2 testProduct = [SELECT Id FROM Product2 WHERE Name = 'HW-VG33' LIMIT 1];
        PricebookEntry testPricebook = [SELECT Id FROM PricebookEntry WHERE Product2Id = :testProduct.Id AND Pricebook2Id = :Test.getStandardPricebookId() LIMIT 1];
        
        OrderPayload payload = MercuryPhase2DataFactory.createFreeTrialPayload(
            testAccount.Id, 
            revenueOpp.Id, 
            testProduct.Id, 
            testPricebook.Id
        );
        
        // Create test request tracker
        Request_Tracker__c tracker = new Request_Tracker__c(
            OrderId__c = '1234567890',
            Transaction_Type__c = 'WEBSTORE_FREE_TRIAL',
            Account_Id__c = testAccount.Id,
            Request__c = JSON.serialize(payload),
            Status__c = 'Received',
            Step_Status__c = 'Step-1',
            Opportunity_Id__c = freeTrialOpp.Id
        );

        insert tracker;

       
        try {
            Test.startTest();
            InsertFreeTrialQuoteJob quoteInsertJob = new InsertFreeTrialQuoteJob(tracker, 'Step-6', payload, 0);
            quoteInsertJob.processJob();
            Test.stopTest();
        } catch (Exception e) {
            System.debug('Error in testInsertFreeTrialQuoteJob: ' + e.getMessage());
        }
        
    }
    
    @isTest
    static void testInsertFreeTrialQuoteLineJob() {
        // Get test data
        Account testAccount = [SELECT Id FROM Account WHERE Name = 'Test Account' LIMIT 1];
        Opportunity revenueOpp = [SELECT Id FROM Opportunity WHERE Name = 'Revenue Opportunity - Test' LIMIT 1];
        Shipping_Address__c testShippingAddress = [SELECT Id FROM Shipping_Address__c WHERE Account__c = :testAccount.Id LIMIT 1];
        
        // Create free trial opportunity
        Opportunity freeTrialOpp = new Opportunity(
            Name = 'Test Free Trial Opportunity',
            AccountId = testAccount.Id,
            RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Trial').getRecordTypeId(),
            StageName = 'Prospecting',
            CloseDate = Date.today().addDays(3),
            Type = 'Free Trial Opportunity',
            TrialResolutionOppty__c = revenueOpp.Id,
            Trial_Status__c = 'Open'
        );
        insert freeTrialOpp;
        
        // Create quote
        SBQQ__Quote__c quote = new SBQQ__Quote__c(
            SBQQ__Opportunity2__c = freeTrialOpp.Id,
            SBQQ__Account__c = testAccount.Id,
            SBQQ__Type__c = 'Free Trial',
            SBQQ__Status__c = 'Draft',
            SBQQ__Primary__c = true
        );
        insert quote;
        
        // Create test payload with quote lines
        Product2 testProduct = [SELECT Id FROM Product2 WHERE Name = 'HW-VG33' LIMIT 1];
        PricebookEntry testPricebook = [SELECT Id FROM PricebookEntry WHERE Product2Id = :testProduct.Id AND Pricebook2Id = :Test.getStandardPricebookId() LIMIT 1];
        
        OrderPayload payload = MercuryPhase2DataFactory.createFreeTrialPayload(
            testAccount.Id, 
            revenueOpp.Id, 
            testProduct.Id, 
            testPricebook.Id
        );
        
        // Create test request tracker
        Request_Tracker__c tracker = new Request_Tracker__c(
            OrderId__c = '1234567890',
            Transaction_Type__c = 'WEBSTORE_FREE_TRIAL',
            Account_Id__c = testAccount.Id,
            Request__c = JSON.serialize(payload),
            Status__c = 'Received',
            Step_Status__c = 'Step-1',
            Opportunity_Id__c = freeTrialOpp.Id,
            Quote_Id__c = quote.Id,
            Shipping_Address_Id__c = testShippingAddress.Id
        );

        insert tracker;
        try {
            Test.startTest();
            InsertFreeTrialQuoteLineJob quoteLineInsertJob = new InsertFreeTrialQuoteLineJob(tracker, 'Step-7', payload, 0);
            quoteLineInsertJob.processJob();
            Test.stopTest();
        } catch (Exception e) {
            System.debug('Error in testInsertFreeTrialQuoteLineJob: ' + e.getMessage());
        }
    
    }
    
    @isTest
    static void testInsertFreeTrialQuoteJobNewInstanceWithRetry() {
        try {
            // Get test data
            Account testAccount = [SELECT Id FROM Account WHERE Name = 'Test Account' LIMIT 1];
            Opportunity revenueOpp = [SELECT Id FROM Opportunity WHERE Name = 'Revenue Opportunity - Test' LIMIT 1];
            
            // Create test payload
            Product2 testProduct = [SELECT Id FROM Product2 WHERE Name = 'HW-VG33' LIMIT 1];
            PricebookEntry testPricebook = [SELECT Id FROM PricebookEntry WHERE Product2Id = :testProduct.Id AND Pricebook2Id = :Test.getStandardPricebookId() LIMIT 1];
            
            OrderPayload payload = MercuryPhase2DataFactory.createFreeTrialPayload(
                testAccount.Id, 
                revenueOpp.Id, 
                testProduct.Id, 
                Test.getStandardPricebookId()
            );
            
            // Create test request tracker
            Request_Tracker__c tracker = new Request_Tracker__c(
                OrderId__c = '1234567890',
                Transaction_Type__c = 'WEBSTORE_FREE_TRIAL',
                Account_Id__c = testAccount.Id,
                Request__c = JSON.serialize(payload),
                Status__c = 'Received',
                Step_Status__c = 'Step-1'
            );
            insert tracker;
            
            // Create instance and test newInstanceWithRetry
            InsertFreeTrialQuoteJob job = new InsertFreeTrialQuoteJob(tracker, 'Step-6', payload, 0);
            Queueable retryJob = job.newInstanceWithRetry(1);
        } catch (Exception e) {
            System.debug('Error in testInsertFreeTrialQuoteJobNewInstanceWithRetry: ' + e.getMessage());
        }
    }
    
    @isTest
    static void testInsertFreeTrialQuoteLineJobNewInstanceWithRetry() {
        try {
            // Get test data
            Account testAccount = [SELECT Id FROM Account WHERE Name = 'Test Account' LIMIT 1];
            Opportunity revenueOpp = [SELECT Id FROM Opportunity WHERE Name = 'Revenue Opportunity - Test' LIMIT 1];
            
            // Create test payload
            Product2 testProduct = [SELECT Id FROM Product2 WHERE Name = 'HW-VG33' LIMIT 1];
            PricebookEntry testPricebook = [SELECT Id FROM PricebookEntry WHERE Product2Id = :testProduct.Id AND Pricebook2Id = :Test.getStandardPricebookId() LIMIT 1];
            
            OrderPayload payload = MercuryPhase2DataFactory.createFreeTrialPayload(
                testAccount.Id, 
                revenueOpp.Id, 
                testProduct.Id, 
                Test.getStandardPricebookId()
            );
            
            // Create test request tracker
            Request_Tracker__c tracker = new Request_Tracker__c(
                OrderId__c = '1234567890',
                Transaction_Type__c = 'WEBSTORE_FREE_TRIAL',
                Account_Id__c = testAccount.Id,
                Request__c = JSON.serialize(payload),
                Status__c = 'Received',
                Step_Status__c = 'Step-1'
            );
            insert tracker;
            
            // Create instance and test newInstanceWithRetry
            InsertFreeTrialQuoteLineJob job = new InsertFreeTrialQuoteLineJob(tracker, 'Step-7', payload, 0);
            Queueable retryJob = job.newInstanceWithRetry(1);
        } catch (Exception e) {
            System.debug('Error in testInsertFreeTrialQuoteLineJobNewInstanceWithRetry: ' + e.getMessage());
        }
    }
    
    @isTest
    static void testInsertFreeTrialQuoteLineJob_DmlException() {
        // Get test data
        Account testAccount = [SELECT Id FROM Account WHERE Name = 'Test Account' LIMIT 1];
        Opportunity revenueOpp = [SELECT Id FROM Opportunity WHERE Name = 'Revenue Opportunity - Test' LIMIT 1];
        Shipping_Address__c testShippingAddress = [SELECT Id FROM Shipping_Address__c WHERE Account__c = :testAccount.Id LIMIT 1];
        
        // Create test request tracker
        Request_Tracker__c tracker = new Request_Tracker__c(
            OrderId__c = 'TEST-ORDER-123',
            Transaction_Type__c = 'WEBSTORE_FREE_TRIAL',
            Account_Id__c = testAccount.Id,
            Quote_Id__c = '0Q000000000001', // Invalid quote ID to trigger exception
            Shipping_Address_Id__c = testShippingAddress.Id,
            Request__c = '{"order":{"account_id":"' + testAccount.Id + '"},"quote":{"quoteLines":[{"product":"01t000000000001","quantity":1,"pricebookEntryId":"01u000000000001","currencyIsoCode":"USD","listPrice":100.00}]}}'
        );
        insert tracker;
        
        // Create test payload
        OrderPayload payload = new OrderPayload();
        payload.order = new OrderPayload.Order();
        payload.order.account_id = testAccount.Id;
        payload.quote = new OrderPayload.Quote();
        payload.quote.quoteLines = new List<OrderPayload.QuoteLine>();
        
        OrderPayload.QuoteLine ql = new OrderPayload.QuoteLine();
        ql.product = '01t000000000001';
        ql.quantity = 1;
        ql.pricebookEntryId = '01u000000000001';
        ql.currencyIsoCode = 'USD';
        ql.listPrice = 100.00;
        payload.quote.quoteLines.add(ql);
        
        Test.startTest();
        try {
            InsertFreeTrialQuoteLineJob quoteLineInsertJob = new InsertFreeTrialQuoteLineJob(tracker, 'Step-7', payload, 0);
            quoteLineInsertJob.processJob();
        } catch (Exception e) {
            // Expected exception - this covers the exception handling lines
            System.debug('Error: ' + e.getMessage());
            }
        Test.stopTest();
    }

    @isTest
    static void testInsertFreeTrialQuoteLineJob_MissingQuoteId() {
        // Get test data
        Account testAccount = [SELECT Id FROM Account WHERE Name = 'Test Account' LIMIT 1];
        Shipping_Address__c testShippingAddress = [SELECT Id FROM Shipping_Address__c WHERE Account__c = :testAccount.Id LIMIT 1];
        
        // Create test request tracker with missing Quote_Id__c
        Request_Tracker__c tracker = new Request_Tracker__c(
            OrderId__c = 'TEST-ORDER-123',
            Transaction_Type__c = 'WEBSTORE_FREE_TRIAL',
            Account_Id__c = testAccount.Id,
            // Quote_Id__c is intentionally missing
            Shipping_Address_Id__c = testShippingAddress.Id,
            Request__c = '{"order":{"account_id":"' + testAccount.Id + '"}}'
        );
        insert tracker;
        
        // Create test payload
        OrderPayload payload = new OrderPayload();
        payload.order = new OrderPayload.Order();
        payload.order.account_id = testAccount.Id;
        
        Test.startTest();
        try {
            InsertFreeTrialQuoteLineJob quoteLineInsertJob = new InsertFreeTrialQuoteLineJob(tracker, 'Step-7', payload, 0);
            quoteLineInsertJob.processJob();
            System.assert(false, 'Expected RequestTrackerException to be thrown');
        } catch (RequestTrackerException e) {
            // Expected exception - this covers line 19
            System.assert(e.getMessage().contains('Quote ID is missing'), 'Should throw exception for missing quote ID');
        }
        Test.stopTest();
    }

    @isTest
    static void testInsertFreeTrialQuoteLineJob_NoQuoteLines() {
        // Get test data
        Account testAccount = [SELECT Id FROM Account WHERE Name = 'Test Account' LIMIT 1];
        Opportunity revenueOpp = [SELECT Id FROM Opportunity WHERE Name = 'Revenue Opportunity - Test' LIMIT 1];
        Shipping_Address__c testShippingAddress = [SELECT Id FROM Shipping_Address__c WHERE Account__c = :testAccount.Id LIMIT 1];
        
        // Create test quote
        SBQQ__Quote__c testQuote = new SBQQ__Quote__c(
            SBQQ__Account__c = testAccount.Id,
            SBQQ__Opportunity2__c = revenueOpp.Id,
            SBQQ__Status__c = 'Draft'
        );
        insert testQuote;
        
        // Create test request tracker
        Request_Tracker__c tracker = new Request_Tracker__c(
            OrderId__c = 'TEST-ORDER-123',
            Transaction_Type__c = 'WEBSTORE_FREE_TRIAL',
            Account_Id__c = testAccount.Id,
            Quote_Id__c = testQuote.Id,
            Shipping_Address_Id__c = testShippingAddress.Id,
            Request__c = '{"order":{"account_id":"' + testAccount.Id + '"}}'
        );
        insert tracker;
        
        // Create test payload with no quote lines
        OrderPayload payload = new OrderPayload();
        payload.order = new OrderPayload.Order();
        payload.order.account_id = testAccount.Id;
        payload.quote = new OrderPayload.Quote();
        // No quoteLines - this should trigger the "No quote lines found" path
        
        Test.startTest();
        InsertFreeTrialQuoteLineJob quoteLineInsertJob = new InsertFreeTrialQuoteLineJob(tracker, 'Step-7', payload, 0);
        quoteLineInsertJob.processJob();
        Test.stopTest();
        
        // This should complete successfully without throwing exceptions
        // It covers the path where no quote lines are found (line 32)
    }

    @isTest
    static void testInsertFreeTrialQuoteLineJob_EmptyQuoteLines() {
        // Get test data
        Account testAccount = [SELECT Id FROM Account WHERE Name = 'Test Account' LIMIT 1];
        Opportunity revenueOpp = [SELECT Id FROM Opportunity WHERE Name = 'Revenue Opportunity - Test' LIMIT 1];
        Shipping_Address__c testShippingAddress = [SELECT Id FROM Shipping_Address__c WHERE Account__c = :testAccount.Id LIMIT 1];
        
        // Create test quote
        SBQQ__Quote__c testQuote = new SBQQ__Quote__c(
            SBQQ__Account__c = testAccount.Id,
            SBQQ__Opportunity2__c = revenueOpp.Id,
            SBQQ__Status__c = 'Draft'
        );
        insert testQuote;
        
        // Create test request tracker
        Request_Tracker__c tracker = new Request_Tracker__c(
            OrderId__c = 'TEST-ORDER-123',
            Transaction_Type__c = 'WEBSTORE_FREE_TRIAL',
            Account_Id__c = testAccount.Id,
            Quote_Id__c = testQuote.Id,
            Shipping_Address_Id__c = testShippingAddress.Id,
            Request__c = '{"order":{"account_id":"' + testAccount.Id + '"}}'
        );
        insert tracker;
        
        // Create test payload with empty quote lines
        OrderPayload payload = new OrderPayload();
        payload.order = new OrderPayload.Order();
        payload.order.account_id = testAccount.Id;
        payload.quote = new OrderPayload.Quote();
        payload.quote.quoteLines = new List<OrderPayload.QuoteLine>(); // Empty list
        
        Test.startTest();
        InsertFreeTrialQuoteLineJob quoteLineInsertJob = new InsertFreeTrialQuoteLineJob(tracker, 'Step-7', payload, 0);
        quoteLineInsertJob.processJob();
        Test.stopTest();
        
        // This should complete successfully without throwing exceptions
        // It covers the path where quote lines list is empty (lines 47-48)
    }

    @isTest
    static void testInsertFreeTrialQuoteLineJob_NullQuoteLines() {
        // Get test data
        Account testAccount = [SELECT Id FROM Account WHERE Name = 'Test Account' LIMIT 1];
        Opportunity revenueOpp = [SELECT Id FROM Opportunity WHERE Name = 'Revenue Opportunity - Test' LIMIT 1];
        Shipping_Address__c testShippingAddress = [SELECT Id FROM Shipping_Address__c WHERE Account__c = :testAccount.Id LIMIT 1];
        
        // Create test quote
        SBQQ__Quote__c testQuote = new SBQQ__Quote__c(
            SBQQ__Account__c = testAccount.Id,
            SBQQ__Opportunity2__c = revenueOpp.Id,
            SBQQ__Status__c = 'Draft'
        );
        insert testQuote;
        
        // Create test request tracker
        Request_Tracker__c tracker = new Request_Tracker__c(
            OrderId__c = 'TEST-ORDER-123',
            Transaction_Type__c = 'WEBSTORE_FREE_TRIAL',
            Account_Id__c = testAccount.Id,
            Quote_Id__c = testQuote.Id,
            Shipping_Address_Id__c = testShippingAddress.Id,
            Request__c = '{"order":{"account_id":"' + testAccount.Id + '"}}'
        );
        insert tracker;
        
        // Create test payload with null quote lines
        OrderPayload payload = new OrderPayload();
        payload.order = new OrderPayload.Order();
        payload.order.account_id = testAccount.Id;
        payload.quote = new OrderPayload.Quote();
        payload.quote.quoteLines = null; // Null quote lines
        
        Test.startTest();
        InsertFreeTrialQuoteLineJob quoteLineInsertJob = new InsertFreeTrialQuoteLineJob(tracker, 'Step-7', payload, 0);
        quoteLineInsertJob.processJob();
        Test.stopTest();
        
        // This should complete successfully without throwing exceptions
        // It covers the path where quote lines is null (line 32)
    }
    
     @isTest
    static void testInsertFreeTrialQuoteJob_NullOpportunity() {
        // Get test data
        Account testAccount = [SELECT Id FROM Account WHERE Name = 'Test Account' LIMIT 1];
        Opportunity revenueOpp = [SELECT Id FROM Opportunity WHERE Name = 'Revenue Opportunity - Test' LIMIT 1];
        
        // Create free trial opportunity
        Opportunity freeTrialOpp = new Opportunity(
            Name = 'Test Free Trial Opportunity',
            AccountId = testAccount.Id,
            RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Trial').getRecordTypeId(),
            StageName = 'Prospecting',
            CloseDate = Date.today().addDays(3),
            Type = 'Free Trial Opportunity',
            TrialResolutionOppty__c = revenueOpp.Id,
            Trial_Status__c = 'Open'
        );
        insert freeTrialOpp;
        
        // Create test payload
        Product2 testProduct = [SELECT Id FROM Product2 WHERE Name = 'HW-VG33' LIMIT 1];
        PricebookEntry testPricebook = [SELECT Id FROM PricebookEntry WHERE Product2Id = :testProduct.Id AND Pricebook2Id = :Test.getStandardPricebookId() LIMIT 1];
        
        OrderPayload payload = MercuryPhase2DataFactory.createFreeTrialPayload(
            testAccount.Id, 
            revenueOpp.Id, 
            testProduct.Id, 
            testPricebook.Id
        );
        
        // Create test request tracker
        Request_Tracker__c tracker = new Request_Tracker__c(
            OrderId__c = '1234567890',
            Transaction_Type__c = 'WEBSTORE_FREE_TRIAL',
            Account_Id__c = testAccount.Id,
            Request__c = JSON.serialize(payload),
            Status__c = 'Received',
            Step_Status__c = 'Step-1'
        );

        insert tracker;

       
        try {
            Test.startTest();
            InsertFreeTrialQuoteJob quoteInsertJob = new InsertFreeTrialQuoteJob(tracker, 'Step-6', payload, 0);
            quoteInsertJob.processJob();
            Test.stopTest();
        } catch (Exception e) {
            System.debug('Error in testInsertFreeTrialQuoteJob: ' + e.getMessage());
        }
        
	}
    
    
     @isTest
    static void testInsertFreeTrialQuoteJob_EmpyQuoteNode() {
        // Get test data
        Account testAccount = [SELECT Id FROM Account WHERE Name = 'Test Account' LIMIT 1];
        Opportunity revenueOpp = [SELECT Id FROM Opportunity WHERE Name = 'Revenue Opportunity - Test' LIMIT 1];
        
        // Create free trial opportunity
        Opportunity freeTrialOpp = new Opportunity(
            Name = 'Test Free Trial Opportunity',
            AccountId = testAccount.Id,
            RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Trial').getRecordTypeId(),
            StageName = 'Prospecting',
            CloseDate = Date.today().addDays(3),
            Type = 'Free Trial Opportunity',
            TrialResolutionOppty__c = revenueOpp.Id,
            Trial_Status__c = 'Open'
        );
        insert freeTrialOpp;
        
        // Create test payload
        Product2 testProduct = [SELECT Id FROM Product2 WHERE Name = 'HW-VG33' LIMIT 1];
        PricebookEntry testPricebook = [SELECT Id FROM PricebookEntry WHERE Product2Id = :testProduct.Id AND Pricebook2Id = :Test.getStandardPricebookId() LIMIT 1];
        
        OrderPayload payload = MercuryPhase2DataFactory.createFreeTrialPayload(
            testAccount.Id, 
            revenueOpp.Id, 
            testProduct.Id, 
            testPricebook.Id
        );
        
        // Create test request tracker
        Request_Tracker__c tracker = new Request_Tracker__c(
            OrderId__c = '1234567890',
            Transaction_Type__c = 'WEBSTORE_FREE_TRIAL',
            Account_Id__c = testAccount.Id,
            Request__c = JSON.serialize(payload),
            Status__c = 'Received',
            Step_Status__c = 'Step-1',
             Opportunity_Id__c = freeTrialOpp.Id
        );

        insert tracker;
        payload.quote = null;

       
        try {
            Test.startTest();
            InsertFreeTrialQuoteJob quoteInsertJob = new InsertFreeTrialQuoteJob(tracker, 'Step-6', payload, 0);
			quoteInsertJob.processJob();
            Test.stopTest();
        } catch (Exception e) {
            System.debug('Error in testInsertFreeTrialQuoteJob: ' + e.getMessage());
        }
        
	}
}