force-app/main/default/objects/Account/fields/Most_Recent_Source__c.field-meta.xml
<CustomField>
    <fullName>Most_Recent_Source__c</fullName>
    <description>Populated by the most recent lead that converts/merges into this account (or a contact under this account).</description>
    <label>Most Recent Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <description>This field is being used by Netsuite and code for contracts. Before it is changed Business Systems needs to be notified, as it has a number of dependencies.</description>
    <formula>IF(

CONTAINS(Owner.UserRole.Name, &quot;Small Fleets&quot;),
&quot;Small Business&quot;,
IF(
CONTAINS(Owner.UserRole.Name, &quot;AE1&quot;),
&quot;AE1&quot;,
IF(
OR(
CONTAINS(Owner.UserRole.Name, &quot;Partner&quot;),
CONTAINS(Owner.UserRole.Name, &quot;AE2&quot;)
),
&quot;AE2&quot;,
IF(
CONTAINS(Owner.UserRole.Name, &quot;AE3&quot;),
&quot;AE3&quot;,
IF(
OR(
CONTAINS(Owner.UserRole.Name, &quot;ENT&quot;),
CONTAINS(Owner.UserRole.Name, &quot;Enterprise&quot;),
CONTAINS(Owner.UserRole.Name, &quot;Major&quot;),
CONTAINS(Owner.UserRole.Name, &quot;Field&quot;)
),
&quot;Enterprise&quot;,
&quot;Management&quot;
)
)
)
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Segment (by Current Owner)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ADR_Roundrobin_Assignments__mdt/ADR_Roundrobin_Assignments__mdt.object-meta.xml
<CustomObject>
    <label>ADR Roundrobin Assignment</label>
    <pluralLabel>ADR Roundrobin Assignments</pluralLabel>
</CustomObject>

force-app/main/default/objects/ADR_Roundrobin_Assignments__mdt/fields/Is_ENTR__c.field-meta.xml
<CustomField>
    <fullName>Is_ENTR__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is ENTR?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ADR_Roundrobin_Assignments__mdt/fields/User_ID__c.field-meta.xml
<CustomField>
    <fullName>User_ID__c</fullName>
    <label>User ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Most_Recent_Source__c.field-meta.xml
<CustomField>
    <fullName>Most_Recent_Source__c</fullName>
    <label>Most Recent Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/New_Inbound_Lead__c.field-meta.xml
<CustomField>
    <fullName>New_Inbound_Lead__c</fullName>
    <defaultValue>false</defaultValue>
    <label>New Inbound Lead</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <formula>Account.Segment__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Segment</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Inside Sales</fullName>
            </value>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>ADR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BatchAssignADRfromContact.cls
/*
* Test Class   :   BatchAssignADRfromContactTest
* Description  :   This batch apex assign ADR from contact 
* Related Jira :   GTMS-3637
* *************************************************************************************************************
*/

global class BatchAssignADRfromContact implements Database.Batchable<sObject>, Database.Stateful, Schedulable {
    Map<String, ADR_Roundrobin_Assignments__mdt> ADR_UserMap = ADR_Roundrobin_Assignments__mdt.getAll();
    Map<Id, Id> UserContactMap = new Map<Id, Id>();
    global Database.Querylocator start(Database.BatchableContext BC) {
        // Get contacts with Most_Recent_Source__c = 'Sites webinar registration form' and New_Inbound_Lead__c = TRUE
        return Database.getQueryLocator(System.label.Contact_for_ADR_assignment);
    }    

    global void execute(Database.BatchableContext BC, List<Contact> scope) {
        Set<ID> AccountIDs = new Set<ID>();
        List<Contact> contactswithADR  = new List<Contact>();
        List<Contact> EnterpriseContacts = new List<Contact>();
        List<Contact> NonEnterpriseContacts = new List<Contact>();
        Map<Id, AccountTeamMember> AccountToADRMap = new Map<Id, AccountTeamMember>();
        List<Id> ADRList = new List<Id>();
        Set<Id> AccIDs = new Set<id>();
        //Map<Id, Integer> userRecordCount = new Map<Id, Integer>();
        Map<Id, Integer> EntrUserCountMap = new Map<Id, Integer> ();
        Map<Id, Integer> NonEntrUserCountMap = new Map<Id, Integer> ();
        for(ADR_Roundrobin_Assignments__mdt ADR :  ADR_UserMap.values()){
            if(ADR.Is_Active__c) ADRList.add(ADR.User_Id__c);
        }
        
        List<Id> activeUsers = new List<Id>();
        List<User> usersList = new List<User>();
        usersList = [select Id, isActive from User where Id in:ADRList and isActive=TRUE];
        for(User u:usersList){
            activeUsers.add(u.Id);
        }
        //List<AggregateResult> aggResult = [SELECT count(Id) cnt, UserId FROM AccountTeamMember WHERE TeamMemberRole = 'Sites Account Development Representative' AND UserId IN :ADRList GROUP BY UserId];
        
        /*for(AggregateResult ar : aggResult) {
            userRecordCount.put((Id)ar.get('UserId'), Integer.valueOf(ar.get('cnt')));
        }*/
        // Build a map with users in custom metadata with their respective counts
        for(ADR_Roundrobin_Assignments__mdt eachADR : ADR_UserMap.values()) {
            if(eachADR.Is_Active__c && activeUsers.contains(eachADR.User_Id__c)){
                //Integer recCount = userRecordCount.get(eachADR.User_Id__c) == null ? 0 : userRecordCount.get(eachADR.User_Id__c);
                if(eachADR.Is_ENTR__c) EntrUserCountMap.put(eachADR.User_Id__c, 0);
                else NonEntrUserCountMap.put(eachADR.User_Id__c, 0);
            }
            
        }

        for(Contact contact : scope){
            AccountIDs.add(contact.AccountID);
        }
        // Get existing account team members for the accounts in scope
        for(AccountTeamMember atm : [SELECT AccountID,UserId FROM AccountTeamMember where TeamMemberRole = 'Sites Account Development Representative' and AccountID in : AccountIDs]){
            AccountToADRMap.put(atm.AccountID, atm);
        }

        for(Contact contact : scope){
            // if contact/account has account team member, then only send email (Add to global collection for email later)
            if(contact.AccountID != null && !AccIDs.contains(contact.AccountID)){
                system.debug('contact.Account.Segment__c---'+contact.Account.Segment__c);
                AccIDs.add(contact.AccountID);
                if(AccountToADRMap.get(contact.AccountID) != null){
                    contactswithADR.add(new Contact(Id = contact.Id, New_Inbound_Lead__c = False));
                    if((AccountToADRMap.get(contact.AccountID)).UserId != null) UserContactMap.put(contact.Id, (AccountToADRMap.get(contact.AccountID)).UserId);
                }else if(contact.Account.Segment__c != null && contact.Account.Segment__c == 'Enterprise'){
                    EnterpriseContacts.add(contact);
                }else if(contact.Account.Segment__c != null && contact.Account.Segment__c != 'Enterprise'){
                    NonEnterpriseContacts.add(Contact);
                }
            }else{
                contactswithADR.add(new Contact(Id = contact.Id, New_Inbound_Lead__c = False));
            }
           
        }
      
        if(!contactswithADR.isEmpty()) BatchAssignADRfromContactHelper.updateContacts(contactswithADR);
        if(!EnterpriseContacts.isEmpty()) BatchAssignADRfromContactHelper.InsertADRs(EnterpriseContacts, EntrUserCountMap, UserContactMap);
        if(!NonEnterpriseContacts.isEmpty()) BatchAssignADRfromContactHelper.InsertADRs(NonEnterpriseContacts, NonEntrUserCountMap, UserContactMap);  
    }

        
    global void finish(Database.BatchableContext BC) {
        if(!UserContactMap.isEmpty()) BatchAssignADRfromContactHelper.sendEmail(UserContactMap);
    }   

    global void execute(SchedulableContext sc){
        BatchAssignADRfromContact b = new BatchAssignADRfromContact();
        database.executebatch(b,200);
    }
}