force-app/main/default/objects/Account/fields/MX_Non_Compliant_Tax_Payer__c.field-meta.xml
<CustomField>
    <fullName>MX_Non_Compliant_Tax_Payer__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True if the account&apos;s Tax Id is present in the &quot;MX Non Compliant tax payer&quot; object</description>
    <label>MX Non Compliant Tax Payer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Organization_Size__c.field-meta.xml
<CustomField>
    <fullName>Organization_Size__c</fullName>
    <description>Number of employees or students</description>
    <inlineHelpText>Number of employees or students</inlineHelpText>
    <label>Organization Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 - 99</fullName>
            </value>
            <value>
                <fullName>100 - 499</fullName>
            </value>
            <value>
                <fullName>500 - 999</fullName>
            </value>
            <value>
                <fullName>1000 - 4999</fullName>
            </value>
            <value>
                <fullName>5000+</fullName>
            </value>
            <value>
                <fullName>0</fullName>
                <isActive>false</isActive>
                <label>0</label>
            </value>
            <value>
                <fullName>1-99</fullName>
                <isActive>false</isActive>
                <label>1-99</label>
            </value>
            <value>
                <fullName>1/1/1999 12:00:00 AM</fullName>
                <isActive>false</isActive>
                <label>1/1/1999 12:00:00 AM</label>
            </value>
            <value>
                <fullName>10</fullName>
                <isActive>false</isActive>
                <label>10</label>
            </value>
            <value>
                <fullName>100 - 999</fullName>
                <isActive>false</isActive>
                <label>100 - 999</label>
            </value>
            <value>
                <fullName>100-499</fullName>
                <isActive>false</isActive>
                <label>100-499</label>
            </value>
            <value>
                <fullName>1000+</fullName>
                <isActive>false</isActive>
                <label>1000+</label>
            </value>
            <value>
                <fullName>1000-4999</fullName>
                <isActive>false</isActive>
                <label>1000-4999</label>
            </value>
            <value>
                <fullName>10000+</fullName>
                <isActive>false</isActive>
                <label>10000+</label>
            </value>
            <value>
                <fullName>11</fullName>
                <isActive>false</isActive>
                <label>11</label>
            </value>
            <value>
                <fullName>13</fullName>
                <isActive>false</isActive>
                <label>13</label>
            </value>
            <value>
                <fullName>200</fullName>
                <isActive>false</isActive>
                <label>200</label>
            </value>
            <value>
                <fullName>201-500</fullName>
                <isActive>false</isActive>
                <label>201-500</label>
            </value>
            <value>
                <fullName>21</fullName>
                <isActive>false</isActive>
                <label>21</label>
            </value>
            <value>
                <fullName>22</fullName>
                <isActive>false</isActive>
                <label>22</label>
            </value>
            <value>
                <fullName>29</fullName>
                <isActive>false</isActive>
                <label>29</label>
            </value>
            <value>
                <fullName>34</fullName>
                <isActive>false</isActive>
                <label>34</label>
            </value>
            <value>
                <fullName>36161</fullName>
                <isActive>false</isActive>
                <label>36161</label>
            </value>
            <value>
                <fullName>42</fullName>
                <isActive>false</isActive>
                <label>42</label>
            </value>
            <value>
                <fullName>495 - 1000</fullName>
                <isActive>false</isActive>
                <label>495 - 1000</label>
            </value>
            <value>
                <fullName>496 - 1000</fullName>
                <isActive>false</isActive>
                <label>496 - 1000</label>
            </value>
            <value>
                <fullName>497 - 1000</fullName>
                <isActive>false</isActive>
                <label>497 - 1000</label>
            </value>
            <value>
                <fullName>498 - 1000</fullName>
                <isActive>false</isActive>
                <label>498 - 1000</label>
            </value>
            <value>
                <fullName>499 - 1000</fullName>
                <isActive>false</isActive>
                <label>499 - 1000</label>
            </value>
            <value>
                <fullName>500 - 1000</fullName>
                <isActive>false</isActive>
                <label>500 - 1000</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;New&quot;</defaultValue>
    <description>This is a roll up from the status of the contacts of the account. 
Eg. If there is any disqualified contact -&gt; Disqualified and so on.</description>
    <label>Account Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/VATId__c.field-meta.xml
<CustomField>
    <fullName>VATId__c</fullName>
    <description>Value Added Tax Number. Should only be filled for United Kingdom Accounts</description>
    <label>Tax ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MX_Non_Compliant_Taxpayers__c/MX_Non_Compliant_Taxpayers__c.object-meta.xml
<CustomObject>
    <label>MX Non-Compliant Taxpayers</label>
    <nameField>
        <displayFormat>MX-{000000}</displayFormat>
        <label>MX Non-Compliant Taxpayers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MX Non-Compliant Taxpayers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MX_Non_Compliant_Taxpayers__c/fields/RFC__c.field-meta.xml
<CustomField>
    <fullName>RFC__c</fullName>
    <label>RFC</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MX_Non_Compliant_Taxpayers__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MX_Non_Compliant_Taxpayers__c/fields/Taxpayer_Name__c.field-meta.xml
<CustomField>
    <fullName>Taxpayer_Name__c</fullName>
    <label>Taxpayer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MarkMXNonCompliantAccountTest.cls
/*
* @Author : Siddharth Kumar Mishra
* @Description:- Test class for MarkMXNonCompliantAccount,Batch_UnMarkMXNonCompliantAccounts,Batch_MarkMXNonCompliantAccount ( GTMS - 6447  -  4/23/2022  -  MX Non Compliant Tax Payers )
*/
@IsTest
public class MarkMXNonCompliantAccountTest
{
    @TestSetup 
    public static void setup()
    {
        //Test Accounts
        Account testAccount = new Account
        (
            name = 'Test Account 1',
            VATId__c = '1001001',
            Organization_Size__c = '1 - 99',
            BillingCountry = 'India'
        );
        Insert testAccount;
        Account testAccount2 = new Account
        (
            name = 'Test Account 2',
            VATId__c = '1001001',
            Organization_Size__c = '1 - 99',
            BillingCountry = 'India',
            MX_Non_Compliant_Tax_Payer__c = true
        );
        Insert testAccount2;
        
        MX_Non_Compliant_Taxpayers__c testRec = new MX_Non_Compliant_Taxpayers__c
        (
            RFC__c = '1001001',
            Status__c = '',
            Taxpayer_Name__c = 'test non compliant tax payer'
        );
        Insert testRec;
    }
    @IsTest
    static void testMethod01()
    {
        Account testAccOld1 = [SELECT Id,Name,MX_Non_Compliant_Tax_Payer__c FROM Account WHERE MX_Non_Compliant_Tax_Payer__c = TRUE];
        Account testAccOld2 = [SELECT Id,Name,MX_Non_Compliant_Tax_Payer__c FROM Account WHERE MX_Non_Compliant_Tax_Payer__c = FALSE];
        Test.startTest();
        MarkMXNonCompliantAccount.markAccount();
        Test.stopTest();
        List<Account> testAccNew = [SELECT Id,Name,MX_Non_Compliant_Tax_Payer__c FROM Account limit 2];
        System.assertEquals(TRUE, testAccOld1.MX_Non_Compliant_Tax_Payer__c);
        System.assertEquals(FALSE, testAccOld2.MX_Non_Compliant_Tax_Payer__c);
        System.assertEquals(TRUE, testAccNew[0].MX_Non_Compliant_Tax_Payer__c);
        System.assertEquals(TRUE, testAccNew[1].MX_Non_Compliant_Tax_Payer__c);
    }
    
}