force-app/main/default/objects/Account/fields/Organization_Size__c.field-meta.xml
<CustomField>
    <fullName>Organization_Size__c</fullName>
    <description>Number of employees or students</description>
    <inlineHelpText>Number of employees or students</inlineHelpText>
    <label>Organization Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 - 99</fullName>
            </value>
            <value>
                <fullName>100 - 499</fullName>
            </value>
            <value>
                <fullName>500 - 999</fullName>
            </value>
            <value>
                <fullName>1000 - 4999</fullName>
            </value>
            <value>
                <fullName>5000+</fullName>
            </value>
            <value>
                <fullName>0</fullName>
                <isActive>false</isActive>
                <label>0</label>
            </value>
            <value>
                <fullName>1-99</fullName>
                <isActive>false</isActive>
                <label>1-99</label>
            </value>
            <value>
                <fullName>1/1/1999 12:00:00 AM</fullName>
                <isActive>false</isActive>
                <label>1/1/1999 12:00:00 AM</label>
            </value>
            <value>
                <fullName>10</fullName>
                <isActive>false</isActive>
                <label>10</label>
            </value>
            <value>
                <fullName>100 - 999</fullName>
                <isActive>false</isActive>
                <label>100 - 999</label>
            </value>
            <value>
                <fullName>100-499</fullName>
                <isActive>false</isActive>
                <label>100-499</label>
            </value>
            <value>
                <fullName>1000+</fullName>
                <isActive>false</isActive>
                <label>1000+</label>
            </value>
            <value>
                <fullName>1000-4999</fullName>
                <isActive>false</isActive>
                <label>1000-4999</label>
            </value>
            <value>
                <fullName>10000+</fullName>
                <isActive>false</isActive>
                <label>10000+</label>
            </value>
            <value>
                <fullName>11</fullName>
                <isActive>false</isActive>
                <label>11</label>
            </value>
            <value>
                <fullName>13</fullName>
                <isActive>false</isActive>
                <label>13</label>
            </value>
            <value>
                <fullName>200</fullName>
                <isActive>false</isActive>
                <label>200</label>
            </value>
            <value>
                <fullName>201-500</fullName>
                <isActive>false</isActive>
                <label>201-500</label>
            </value>
            <value>
                <fullName>21</fullName>
                <isActive>false</isActive>
                <label>21</label>
            </value>
            <value>
                <fullName>22</fullName>
                <isActive>false</isActive>
                <label>22</label>
            </value>
            <value>
                <fullName>29</fullName>
                <isActive>false</isActive>
                <label>29</label>
            </value>
            <value>
                <fullName>34</fullName>
                <isActive>false</isActive>
                <label>34</label>
            </value>
            <value>
                <fullName>36161</fullName>
                <isActive>false</isActive>
                <label>36161</label>
            </value>
            <value>
                <fullName>42</fullName>
                <isActive>false</isActive>
                <label>42</label>
            </value>
            <value>
                <fullName>495 - 1000</fullName>
                <isActive>false</isActive>
                <label>495 - 1000</label>
            </value>
            <value>
                <fullName>496 - 1000</fullName>
                <isActive>false</isActive>
                <label>496 - 1000</label>
            </value>
            <value>
                <fullName>497 - 1000</fullName>
                <isActive>false</isActive>
                <label>497 - 1000</label>
            </value>
            <value>
                <fullName>498 - 1000</fullName>
                <isActive>false</isActive>
                <label>498 - 1000</label>
            </value>
            <value>
                <fullName>499 - 1000</fullName>
                <isActive>false</isActive>
                <label>499 - 1000</label>
            </value>
            <value>
                <fullName>500 - 1000</fullName>
                <isActive>false</isActive>
                <label>500 - 1000</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <description>Account type for partners - resellers, referral partners, corporate partners</description>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/Async_Request__c/Async_Request__c.object-meta.xml
<CustomObject>
    <description>Use to queue up an Asynchronous Request for processing</description>
    <label>Async Request</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Async Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Async Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Async_Request__c/fields/Options__c.field-meta.xml
<CustomField>
    <fullName>Options__c</fullName>
    <description>Additional Options that can be used when processing the request</description>
    <label>Options</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Async_Request__c/fields/Params__c.field-meta.xml
<CustomField>
    <fullName>Params__c</fullName>
    <label>Params</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Buyout_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Buyout_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Linking the rebate opportunity for buyouts to the revenue opportunity.</description>
    <inlineHelpText>Lookup field to link buyout opportunity</inlineHelpText>
    <label>Buyout Opportunity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Opportunity.Returning_Opportunity__r.AccountId</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Buyout Opportunity</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Configuration_Segment__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Segment__c</fullName>
    <label>Configuration Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Express</fullName>
            </value>
            <value>
                <fullName>Non Express</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Partner_Referral_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Partner_Referral_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Linking the partner referral rebate field to the revenue opportunity</description>
    <inlineHelpText>Lookup field to link partner referral opportunity</inlineHelpText>
    <label>Partner Referral Opportunity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Opportunity.Returning_Opportunity__r.AccountId</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunities (Partner Referral Opportunity)</relationshipLabel>
    <relationshipName>Opportunities3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Push_Return_to_Netsuite__c.field-meta.xml
<CustomField>
    <fullName>Push_Return_to_Netsuite__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Push Return to Netsuite</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Rebate_Type__c.field-meta.xml
<CustomField>
    <fullName>Rebate_Type__c</fullName>
    <label>Rebate Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Subsidy</fullName>
            </value>
            <value>
                <fullName>Buyout</fullName>
            </value>
            <value>
                <fullName>Partner Referral</fullName>
            </value>
            <value>
                <fullName>Delinquent</fullName>
            </value>
            <value>
                <fullName>Co-Term Credit</fullName>
                <label>Renewal Credit</label>
            </value>
            <value>
                <fullName>License Term Credit</fullName>
            </value>
            <value>
                <fullName>Non-Commissionable SKU</fullName>
            </value>
            <value>
                <fullName>Installation Costs</fullName>
            </value>
            <value>
                <fullName>Free Months</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Retry_TO_to_NS__c.field-meta.xml
<CustomField>
    <fullName>Retry_TO_to_NS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Push Transfer Order to Netsuite</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Shipping_Country__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Country__c</fullName>
    <label>Shipping Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Aland Islands</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia, Plurinational State of</fullName>
            </value>
            <value>
                <fullName>Bonaire, Sint Eustatius and Saba</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Bouvet Island</fullName>
            </value>
            <value>
                <fullName>United States</fullName>
                <default>true</default>
                <label>United States</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Subsidy_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Subsidy_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Linking the subsidy opportunity for subsidy to the revenue opportunity.</description>
    <inlineHelpText>Lookup field to link subsidy opportunity</inlineHelpText>
    <label>Subsidy Opportunity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Opportunity.Returning_Opportunity__r.AccountId</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Subsidy Opportunity</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Trial.recordType-meta.xml
<RecordType>
    <fullName>Trial</fullName>
    <active>true</active>
    <businessProcess>Standard Opportunities</businessProcess>
    <label>Trial</label>
</RecordType>

force-app/main/default/classes/GS_OpportunityNetSuiteServiceTest.cls
@isTest
public with sharing class GS_OpportunityNetSuiteServiceTest {
    
    @isTest
    public static void pushToNetSuite_Sync(){
        DMLWrapper.intializeUnitOfWork(new List<SObjectType>{
            Opportunity.SOBjectType,
            Async_Request__c.SOBjectType
        });

        Id fakeId1 = TestFactory.getFakeId(Opportunity.SObjectType);
        Id fakeId2 = TestFactory.getFakeId(Opportunity.SObjectType);
        List<Opportunity> newOppList = new List<Opportunity>{
            new Opportunity(
                Id = fakeId1,
                Type = 'Free Trial Opportunity',
                StageName = 'Ready to Ship'
            ),
            new Opportunity(
                Id = fakeId2,
                Type = 'Revenue Opportunity',
                StageName = 'Ready to Ship'
            )
        };

        Map<Id, Opportunity> oldOppMap = new Map<Id, Opportunity>{
            fakeId1 => new Opportunity(
                Id = fakeId1,
                Type = 'Free Trial Opportunity',
                StageName = 'Proposal'
            ),
            fakeId2 => new Opportunity(
                Id = fakeId2,
                Type = 'Revenue Opportunity',
                StageName = 'Proposal'
            )
        };

        Test.startTest();
        (new GS_OpportunityNetSuiteService()).pushInfoToNetsuite(oldOppMap, newOppList);
        Test.stopTest();

        System.assertEquals(true, newOppList[0].Retry_TO_to_NS__c);
        System.assertEquals(true, newOppList[1].netsuite_conn__Push_To_Netsuite__c);
    }

    @isTest
    public static void pushToNetSuite_AsyncRecords(){
        DMLWrapper.intializeUnitOfWork(new List<SObjectType>{
            Opportunity.SOBjectType,
            Async_Request__c.SOBjectType
        });
        
        Id fakeId1 = TestFactory.getFakeId(Opportunity.SObjectType);
        Id fakeId2 = TestFactory.getFakeId(Opportunity.SObjectType);
        List<Opportunity> newOppList = new List<Opportunity>{
            new Opportunity(
                Id = fakeId1,
                Type = 'Free Trial Opportunity',
                StageName = 'Closed Won'
            ),
            new Opportunity(
                Id = fakeId2,
                Type = 'Revenue Opportunity',
                StageName = 'Closed Won'
            )
        };

        Map<Id, Opportunity> oldOppMap = new Map<Id, Opportunity>{
            fakeId1 => new Opportunity(
                Id = fakeId1,
                Type = 'Free Trial Opportunity',
                StageName = 'Ready to Ship'
            ),
            fakeId2 => new Opportunity(
                Id = fakeId2,
                Type = 'Revenue Opportunity',
                StageName = 'Ready to Ship'
            )
        };

        Test.startTest();
        (new GS_OpportunityNetSuiteService()).pushInfoToNetsuite(oldOppMap, newOppList);
        DMLWrapper.publishDML();
        Test.stopTest();

        System.assertEquals(1, [SELECT COUNT() FROM Async_Request__c]);
    }

    @isTest
    public static void pushToNetSuite_Async_RelatedRecordsUpdate(){
        Account acc = new Account(
            Name = 'Test Account 1 - Transportation',
            Industry = 'Transportation & Warehousing',
            Organization_Size__c = '100 - 499',
            BillingCountry = 'United States',
            BillingState = 'California'
        );
        insert acc;

        List<Opportunity> oppList_related = new List<Opportunity>{
            new Opportunity(
                Type = 'Rebate',
                RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Return Opportunity').getRecordTypeId(),
                Name = 'New opp for testing 0',
                AccountId = acc.Id,
                Configuration_Segment__c = 'Non Express',
                StageName = 'Closed Date',
                CloseDate = System.today(),
                Probability = 100,
                Rebate_Type__c = 'Buyout',
                Shipping_Country__c = 'United States'
            ),
            new Opportunity(
                Type = 'Rebate',
                RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Return Opportunity').getRecordTypeId(),
                Name = 'New opp for testing 1',
                AccountId = acc.Id,
                Configuration_Segment__c = 'Non Express',
                StageName = 'Closed Date',
                CloseDate = System.today(),
                Probability = 100,
                Rebate_Type__c = 'Subsidy',
                Shipping_Country__c = 'United States'
            ),
            new Opportunity(
                Type = 'Rebate',
                RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Return Opportunity').getRecordTypeId(),
                Name = 'New opp for testing 2',
                AccountId = acc.Id,
                Configuration_Segment__c = 'Non Express',
                StageName = 'Closed Date',
                CloseDate = System.today(),
                Probability = 100,
                Rebate_Type__c = 'Partner Referral',
                Shipping_Country__c = 'United States'
            )
        };
        insert oppList_related;

        List<Opportunity> oppList_main = new List<Opportunity>{
            new Opportunity(
                Type = 'Free Trial Opportunity',
                RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Trial').getRecordTypeId(),
                Name = 'New opp for testing 0',
                Buyout_Opportunity__c = oppList_related[0].Id,
                AccountId = acc.Id,
                Configuration_Segment__c = 'Non Express',
                StageName = 'Proposal',
                CloseDate = System.today(),
                Probability = 100,
                Shipping_Country__c = 'United States'
            ),
            new Opportunity(
                Type = 'Free Trial Opportunity',
                RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Trial').getRecordTypeId(),
                Name = 'New opp for testing 1',
                Subsidy_Opportunity__c = oppList_related[1].Id,
                AccountId = acc.Id,
                Configuration_Segment__c = 'Non Express',
                StageName = 'Proposal',
                CloseDate = System.today(),
                Probability = 100,
                Shipping_Country__c = 'United States'
            ),
            new Opportunity(
                Type = 'Free Trial Opportunity',
                RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Trial').getRecordTypeId(),
                Name = 'New opp for testing 2',
                Partner_Referral_Opportunity__c = oppList_related[2].Id,
                AccountId = acc.Id,
                Configuration_Segment__c = 'Non Express',
                StageName = 'Proposal',
                CloseDate = System.today(),
                Probability = 100,
                Shipping_Country__c = 'United States'
            )
        };
        insert oppList_main;

        Test.startTest();
        (new GS_OpportunityNetSuiteServiceAsync()).execute(new Async_Request__c(
            Params__c = oppList_main[0].Id+';'+oppList_main[1].Id+';'+oppList_main[2].Id+';',
            Options__c = JSON.serialize(new GS_OpportunityNetSuiteServiceAsync.Options('RELATED_RECORDS_UPDATE'))
        ));
        Test.stopTest();

        System.assertEquals(true, [SELECT Push_Return_to_Netsuite__c FROM Opportunity WHERE ID = :oppList_related[0].Id][0].Push_Return_to_Netsuite__c);
        System.assertEquals(true, [SELECT Push_Return_to_Netsuite__c FROM Opportunity WHERE ID = :oppList_related[1].Id][0].Push_Return_to_Netsuite__c);
        System.assertEquals(true, [SELECT Push_Return_to_Netsuite__c FROM Opportunity WHERE ID = :oppList_related[2].Id][0].Push_Return_to_Netsuite__c);
    }
}