force-app/main/default/objects/Account/fields/Organization_Size__c.field-meta.xml
<CustomField>
    <fullName>Organization_Size__c</fullName>
    <description>Number of employees or students</description>
    <inlineHelpText>Number of employees or students</inlineHelpText>
    <label>Organization Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 - 99</fullName>
            </value>
            <value>
                <fullName>100 - 499</fullName>
            </value>
            <value>
                <fullName>500 - 999</fullName>
            </value>
            <value>
                <fullName>1000 - 4999</fullName>
            </value>
            <value>
                <fullName>5000+</fullName>
            </value>
            <value>
                <fullName>0</fullName>
                <isActive>false</isActive>
                <label>0</label>
            </value>
            <value>
                <fullName>1-99</fullName>
                <isActive>false</isActive>
                <label>1-99</label>
            </value>
            <value>
                <fullName>1/1/1999 12:00:00 AM</fullName>
                <isActive>false</isActive>
                <label>1/1/1999 12:00:00 AM</label>
            </value>
            <value>
                <fullName>10</fullName>
                <isActive>false</isActive>
                <label>10</label>
            </value>
            <value>
                <fullName>100 - 999</fullName>
                <isActive>false</isActive>
                <label>100 - 999</label>
            </value>
            <value>
                <fullName>100-499</fullName>
                <isActive>false</isActive>
                <label>100-499</label>
            </value>
            <value>
                <fullName>1000+</fullName>
                <isActive>false</isActive>
                <label>1000+</label>
            </value>
            <value>
                <fullName>1000-4999</fullName>
                <isActive>false</isActive>
                <label>1000-4999</label>
            </value>
            <value>
                <fullName>10000+</fullName>
                <isActive>false</isActive>
                <label>10000+</label>
            </value>
            <value>
                <fullName>11</fullName>
                <isActive>false</isActive>
                <label>11</label>
            </value>
            <value>
                <fullName>13</fullName>
                <isActive>false</isActive>
                <label>13</label>
            </value>
            <value>
                <fullName>200</fullName>
                <isActive>false</isActive>
                <label>200</label>
            </value>
            <value>
                <fullName>201-500</fullName>
                <isActive>false</isActive>
                <label>201-500</label>
            </value>
            <value>
                <fullName>21</fullName>
                <isActive>false</isActive>
                <label>21</label>
            </value>
            <value>
                <fullName>22</fullName>
                <isActive>false</isActive>
                <label>22</label>
            </value>
            <value>
                <fullName>29</fullName>
                <isActive>false</isActive>
                <label>29</label>
            </value>
            <value>
                <fullName>34</fullName>
                <isActive>false</isActive>
                <label>34</label>
            </value>
            <value>
                <fullName>36161</fullName>
                <isActive>false</isActive>
                <label>36161</label>
            </value>
            <value>
                <fullName>42</fullName>
                <isActive>false</isActive>
                <label>42</label>
            </value>
            <value>
                <fullName>495 - 1000</fullName>
                <isActive>false</isActive>
                <label>495 - 1000</label>
            </value>
            <value>
                <fullName>496 - 1000</fullName>
                <isActive>false</isActive>
                <label>496 - 1000</label>
            </value>
            <value>
                <fullName>497 - 1000</fullName>
                <isActive>false</isActive>
                <label>497 - 1000</label>
            </value>
            <value>
                <fullName>498 - 1000</fullName>
                <isActive>false</isActive>
                <label>498 - 1000</label>
            </value>
            <value>
                <fullName>499 - 1000</fullName>
                <isActive>false</isActive>
                <label>499 - 1000</label>
            </value>
            <value>
                <fullName>500 - 1000</fullName>
                <isActive>false</isActive>
                <label>500 - 1000</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Organization_Size__c.field-meta.xml
<CustomField>
    <fullName>Organization_Size__c</fullName>
    <formula>TEXT(Account.Organization_Size__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Please edit on the Account page.</inlineHelpText>
    <label>Organization Size</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quota__c/Quota__c.object-meta.xml
<CustomObject>
    <description>Used for role&apos;s/rep&apos;s historical performance analysis.</description>
    <label>Quota</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Quota Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quota__c/fields/Fiscal_Period__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_Period__c</fullName>
    <description>Fiscal period associated with the quota.</description>
    <label>Fiscal Period</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quota__c/fields/Fiscal_Period_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_Period_End_Date__c</fullName>
    <description>Used to determine ramp period and status</description>
    <inlineHelpText>Used to determine ramp period and status</inlineHelpText>
    <label>Fiscal Period End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quota__c/fields/Fiscal_Period_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_Period_Start_Date__c</fullName>
    <description>Used to determine ramp period and status</description>
    <inlineHelpText>Used to determine ramp period and status</inlineHelpText>
    <label>Fiscal Period Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quota__c/fields/Quota__c.field-meta.xml
<CustomField>
    <fullName>Quota__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Amount associated with the quota instance.</description>
    <label>Quota</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quota__c/fields/Quota_Period__c.field-meta.xml
<CustomField>
    <fullName>Quota_Period__c</fullName>
    <description>Used to differentiate between monthly vs. quarterly quotas</description>
    <inlineHelpText>Used to differentiate between monthly vs. quarterly quotas</inlineHelpText>
    <label>Quota Period</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quota__c/fields/Quota_Period_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Quota_Period_End_Date__c</fullName>
    <description>For trigger to run. Rep cannot have a quota record with overlapping quota period start/end dates</description>
    <inlineHelpText>For trigger to run. Rep cannot have a quota record with overlapping quota period start/end dates</inlineHelpText>
    <label>Quota Period End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quota__c/fields/Quota_Period_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Quota_Period_Start_Date__c</fullName>
    <description>For trigger to run. Rep cannot have a quota record with overlapping quota period start/end dates</description>
    <inlineHelpText>For trigger to run. Rep cannot have a quota record with overlapping quota period start/end dates</inlineHelpText>
    <label>Quota Period Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quota__c/fields/Role_at_Start_of_Fiscal_Period__c.field-meta.xml
<CustomField>
    <fullName>Role_at_Start_of_Fiscal_Period__c</fullName>
    <description>Role of the rep at the start of Fiscal Period</description>
    <label>Role at Start of Fiscal Period</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quota__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User associated with the Quota instance.</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quotas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestFactory.cls
@isTest
public class TestFactory {

    public static SObject createSObject(SObject sObj) {
        // Check what type of object we are creating and add any defaults that are needed.
        String objectName = String.valueOf(sObj.getSObjectType());
        // Construct the default values class. Salesforce doesn't allow '__' in class names
        String defaultClassName = 'TestFactory.' + objectName.replaceAll('__(c|C)$|__', '') + 'Defaults';
        // If there is a class that exists for the default values, then use them
        if (Type.forName(defaultClassName) != null) {
            sObj = createSObject(sObj, defaultClassName);
        }
        return sObj;
    }

    public static SObject createSObject(SObject sObj, Boolean doInsert) {
        SObject retObject = createSObject(sObj);
        if (doInsert) {
            insert retObject;
        }
        return retObject;
    }

    public static SObject createSObject(SObject sObj, String defaultClassName) {
        // Create an instance of the defaults class so we can get the Map of field defaults
        Type t = Type.forName(defaultClassName);
        if (t == null) {
            Throw new TestFactoryException('Invalid defaults class.');
        }
        FieldDefaults defaults = (FieldDefaults) t.newInstance();
        addFieldDefaults(sObj, defaults.getFieldDefaults());
        return sObj;
    }

    public static SObject createSObject(SObject sObj, String defaultClassName, Boolean doInsert) {
        SObject retObject = createSObject(sObj, defaultClassName);
        if (doInsert) {
            insert retObject;
        }
        return retObject;
    }

    public static SObject[] createSObjectList(Sobject sObj, Integer numberOfObjects) {
        return createSObjectList(sObj, numberOfObjects, (String) null);
    }

    public static SObject[] createSObjectList(SObject sObj, Integer numberOfObjects, Boolean doInsert) {
        SObject[] retList = createSObjectList(sObj, numberOfObjects, (String) null);
        if (doInsert) {
            insert retList;
        }
        return retList;
    }

    public static SObject[] createSObjectList(SObject sObj, Integer numberOfObjects, String defaultClassName, Boolean doInsert) {
        SObject[] retList = createSObjectList(sObj, numberOfObjects, defaultClassName);
        if (doInsert) {
            insert retList;
        }
        return retList;
    }

    public static SObject[] createSObjectList(Sobject sObj, Integer numberOfObjects, String defaultClassName) {
        SObject[] sObjs = new SObject[]{
        };
        SObject newObj;

        // Get one copy of the object
        if (defaultClassName == null) {
            newObj = createSObject(sObj);
        } else {
            newObj = createSObject(sObj, defaultClassName);
        }

        // Get the name field for the object
        String nameField = nameFieldMap.get(String.valueOf(sObj.getSObjectType()));
        if (nameField == null) {
            nameField = 'Name';
        }

        // Clone the object the number of times requested. Increment the name field so each record is unique
        for (Integer i = 0; i < numberOfObjects; i++) {
            SObject clonedSObj = newObj.clone(false, true);
            clonedSObj.put(nameField, (String) clonedSObj.get(nameField) + ' ' + i);
            sObjs.add(clonedSObj);
        }
        return sObjs;
    }

    private static void addFieldDefaults(SObject sObj, Map<Schema.SObjectField, Object> defaults) {
        // Loop through the map of fields and if they weren't specifically assigned, fill them.
        Map<String, Object> populatedFields = sObj.getPopulatedFieldsAsMap();
        for (Schema.SObjectField field : defaults.keySet()) {
            if (!populatedFields.containsKey(String.valueOf(field))) {
                sObj.put(field, defaults.get(field));
            }
        }
    }

    // When we create a list of SObjects, we need to
    private static Map<String, String> nameFieldMap = new Map<String, String>{
            'Contact' => 'LastName',
            'Case' => 'Subject'
    };

    public class TestFactoryException extends Exception {
    }

    // Use the FieldDefaults interface to set up values you want to default in for all objects.
    public interface FieldDefaults {
        Map<Schema.SObjectField, Object> getFieldDefaults();
    }

    // To specify defaults for objects, use the naming convention [ObjectName]Defaults.
    // For custom objects, omit the __c from the Object Name

    public class AccountDefaults implements FieldDefaults {
        public Map<Schema.SObjectField, Object> getFieldDefaults() {
            return new Map<Schema.SObjectField, Object>{
                    Account.Name => 'Test Account',
                    Account.Organization_Size__c => '100 - 499',
                    Account.BillingCountry => 'United States',
                    Account.BillingState => 'California'
            };
        }
    }

    public class ContactDefaults implements FieldDefaults {
        public Map<Schema.SObjectField, Object> getFieldDefaults() {
            return new Map<Schema.SObjectField, Object>{
                    Contact.FirstName => 'First',
                    Contact.LastName => 'Last',
                    Contact.Email => 'test@test.com'
            };
        }
    }

    public class OpportunityDefaults implements FieldDefaults {
        public Map<Schema.SObjectField, Object> getFieldDefaults() {
            return new Map<Schema.SObjectField, Object>{
                    Opportunity.Name => 'Test Opportunity - ' + generateRandomString(5),
                    Opportunity.StageName => 'Incubate',
                    Opportunity.Amount => 10000.00,
                    Opportunity.CloseDate => System.today()
            };
        }
    }

    public class CaseDefaults implements FieldDefaults {
        public Map<Schema.SObjectField, Object> getFieldDefaults() {
            return new Map<Schema.SObjectField, Object>{
                    Case.Subject => 'Test Case'
            };
        }
    }

    public class Pricebook2Defaults implements FieldDefaults {
        public Map<Schema.SObjectField, Object> getFieldDefaults() {
            return new Map<Schema.SObjectField, Object>{
                    Pricebook2.Name => 'Samsara Standard',
                    Pricebook2.IsActive => TRUE
            };
        }
    }

    public class Product2Defaults implements FieldDefaults {
        public Map<Schema.SObjectField, Object> getFieldDefaults() {
            return new Map<Schema.SObjectField, Object>{
                    Product2.Name => 'Test Product',
                    Product2.ProductCode => String.join(new List<String>{
                            TestFactory.generateRandomString(4),
                            TestFactory.generateRandomString(4),
                            TestFactory.generateRandomString(4)
                    }, '-')
            };
        }
    }

    public class PricebookEntryDefaults implements FieldDefaults {
        public Map<Schema.SObjectField, Object> getFieldDefaults() {
            return new Map<Schema.SObjectField, Object>{
                    PricebookEntry.UnitPrice => 100.00,
                    PricebookEntry.IsActive => true,
                    PricebookEntry.Pricebook2Id => Test.getStandardPricebookId()
            };
        }
    }

    public class OpportunityLineItemDefaults implements FieldDefaults {
        public Map<Schema.SObjectField, Object> getFieldDefaults() {
            return new Map<Schema.SObjectField, Object>{
                    OpportunityLineItem.UnitPrice => 100.00,
                    OpportunityLineItem.Quantity => 1
            };
        }
    }

    public class QuotaDefaults implements FieldDefaults {
        public Map<Schema.SObjectField, Object> getFieldDefaults() {
            return new Map<Schema.SObjectField, Object>{
                    Quota__c.Role_at_Start_of_Fiscal_Period__c => 'My Role',
                    Quota__c.User__c => UserInfo.getUserId(),
                    Quota__c.CurrencyIsoCode => 'USD',
                    Quota__c.Quota__c => 8000,
                    Quota__c.Quota_Period_End_Date__c => Date.Today() + 4,
                    Quota__c.Quota_Period_Start_Date__c => Date.Today() - 4,
                    Quota__c.Fiscal_Period_End_Date__c => Date.Today() + 4,
                    Quota__c.Fiscal_Period_Start_Date__c => Date.Today() - 4,
                    Quota__c.Quota_Period__c => 'Test',
                    Quota__c.Fiscal_Period__c => 'Test'
            };
        }
    }

    /**
    * @author Groundswell - Vikasm - vikas@gscloudsolutions.com
    * @date 2020-08-26
    * Not yet deployed for Production
    */
    public static Account initializeAccount(String prefix) {
        Map<Schema.SObjectField, Object> accountDefaultFieldmap = new Map<Schema.SObjectField, Object>();
        AccountDefaults accountdefault = new AccountDefaults();
        accountDefaultFieldmap = accountdefault.getFieldDefaults();
        Account thisAccount = new Account();
        thisAccount.Name = prefix + ' ' + String.valueOf(accountDefaultFieldmap.get(Account.Name));
        thisAccount.Organization_Size__c = (String) accountDefaultFieldmap.get(Account.Organization_Size__c);
        thisAccount.BillingCountry = (String) accountDefaultFieldmap.get(Account.BillingCountry);
        thisAccount.BillingState = (String) accountDefaultFieldmap.get(Account.BillingState);
        return thisAccount;
    }

    /**
    * @author Groundswell - Vikasm - vikas@gscloudsolutions.com
    * @date 2020-08-26
    * Not yet deployed for Production
    */
    public static Opportunity initializeOpportunity(String Prefix) {
        Map<Schema.SObjectField, Object> opportunityDefaultFieldmap = new Map<Schema.SObjectField, Object>();
        OpportunityDefaults OpportunityDefaults = new OpportunityDefaults();
        opportunityDefaultFieldmap = OpportunityDefaults.getFieldDefaults();
        Opportunity thisOpportunity = new Opportunity();
        thisOpportunity.Name = prefix + ' ' + String.valueOf(opportunityDefaultFieldmap.get(Opportunity.Name));
        thisOpportunity.StageName = String.valueOf(opportunityDefaultFieldmap.get(Opportunity.StageName));
        thisOpportunity.Amount = (Decimal) opportunityDefaultFieldmap.get(Opportunity.Amount);
        thisOpportunity.CloseDate = (Date) opportunityDefaultFieldmap.get(Opportunity.CloseDate);
        return thisOpportunity;
    }

    /**
    * @author Groundswell - Vikasm - vikas@gscloudsolutions.com
    * @date 2020-08-26
    * Not yet deployed for Production
    */
    public static Contact initializeContact(String prefix) {
        Map<Schema.SObjectField, Object> contactDefaultFieldmap = new Map<Schema.SObjectField, Object>();
        ContactDefaults contactDefaults = new ContactDefaults();
        contactDefaultFieldmap = contactDefaults.getFieldDefaults();
        Contact thisContact = new Contact();
        thisContact.FirstName = prefix + ' ' + String.valueOf(contactDefaultFieldmap.get(Contact.FirstName));
        thisContact.LastName = (String) contactDefaultFieldmap.get(Contact.LastName);
        thisContact.Email = (String) contactDefaultFieldmap.get(Contact.Email);
        return thisContact;
    }

    private static String generateRandomString(Integer len) {
        final String chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789abcdefghijklmnopqrstuvwxyz';
        String randStr = '';
        while (randStr.length() < len) {
            Long randomLong = Crypto.getRandomLong();
            // Convert to positive Integer safely
            Integer idx = Math.mod(Math.abs(randomLong.intValue()), chars.length());
            randStr += chars.substring(idx, idx + 1);
        }
        return randStr;
    }

    private static Integer fakeIdCount = 1;
    public static Id getFakeId(Schema.SObjectType sot) {
        String result = String.valueOf(fakeIdCount++);
        String generatedId = sot.getDescribe().getKeyPrefix() +
                '0'.repeat(12 - result.length()) + result;
        return Id.valueOf(generatedId);
    }
}