force-app/main/default/objects/Account/fields/Organization_Size__c.field-meta.xml
<CustomField>
    <fullName>Organization_Size__c</fullName>
    <description>Number of employees or students</description>
    <inlineHelpText>Number of employees or students</inlineHelpText>
    <label>Organization Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 - 99</fullName>
            </value>
            <value>
                <fullName>100 - 499</fullName>
            </value>
            <value>
                <fullName>500 - 999</fullName>
            </value>
            <value>
                <fullName>1000 - 4999</fullName>
            </value>
            <value>
                <fullName>5000+</fullName>
            </value>
            <value>
                <fullName>0</fullName>
                <isActive>false</isActive>
                <label>0</label>
            </value>
            <value>
                <fullName>1-99</fullName>
                <isActive>false</isActive>
                <label>1-99</label>
            </value>
            <value>
                <fullName>1/1/1999 12:00:00 AM</fullName>
                <isActive>false</isActive>
                <label>1/1/1999 12:00:00 AM</label>
            </value>
            <value>
                <fullName>10</fullName>
                <isActive>false</isActive>
                <label>10</label>
            </value>
            <value>
                <fullName>100 - 999</fullName>
                <isActive>false</isActive>
                <label>100 - 999</label>
            </value>
            <value>
                <fullName>100-499</fullName>
                <isActive>false</isActive>
                <label>100-499</label>
            </value>
            <value>
                <fullName>1000+</fullName>
                <isActive>false</isActive>
                <label>1000+</label>
            </value>
            <value>
                <fullName>1000-4999</fullName>
                <isActive>false</isActive>
                <label>1000-4999</label>
            </value>
            <value>
                <fullName>10000+</fullName>
                <isActive>false</isActive>
                <label>10000+</label>
            </value>
            <value>
                <fullName>11</fullName>
                <isActive>false</isActive>
                <label>11</label>
            </value>
            <value>
                <fullName>13</fullName>
                <isActive>false</isActive>
                <label>13</label>
            </value>
            <value>
                <fullName>200</fullName>
                <isActive>false</isActive>
                <label>200</label>
            </value>
            <value>
                <fullName>201-500</fullName>
                <isActive>false</isActive>
                <label>201-500</label>
            </value>
            <value>
                <fullName>21</fullName>
                <isActive>false</isActive>
                <label>21</label>
            </value>
            <value>
                <fullName>22</fullName>
                <isActive>false</isActive>
                <label>22</label>
            </value>
            <value>
                <fullName>29</fullName>
                <isActive>false</isActive>
                <label>29</label>
            </value>
            <value>
                <fullName>34</fullName>
                <isActive>false</isActive>
                <label>34</label>
            </value>
            <value>
                <fullName>36161</fullName>
                <isActive>false</isActive>
                <label>36161</label>
            </value>
            <value>
                <fullName>42</fullName>
                <isActive>false</isActive>
                <label>42</label>
            </value>
            <value>
                <fullName>495 - 1000</fullName>
                <isActive>false</isActive>
                <label>495 - 1000</label>
            </value>
            <value>
                <fullName>496 - 1000</fullName>
                <isActive>false</isActive>
                <label>496 - 1000</label>
            </value>
            <value>
                <fullName>497 - 1000</fullName>
                <isActive>false</isActive>
                <label>497 - 1000</label>
            </value>
            <value>
                <fullName>498 - 1000</fullName>
                <isActive>false</isActive>
                <label>498 - 1000</label>
            </value>
            <value>
                <fullName>499 - 1000</fullName>
                <isActive>false</isActive>
                <label>499 - 1000</label>
            </value>
            <value>
                <fullName>500 - 1000</fullName>
                <isActive>false</isActive>
                <label>500 - 1000</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ACV_Amount_Multi_Currency__c.field-meta.xml
<CustomField>
    <fullName>ACV_Amount_Multi_Currency__c</fullName>
    <description>This field is created for big deal Alert emails to send USD amount if the currency is not USD - GTMS-16147</description>
    <label>ACV Amount Multi Currency</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/flex_openAmendmentOpportunityTest.cls
@isTest
public class flex_openAmendmentOpportunityTest {
    @isTest
    public static void testGetAmendmentOpportunities() {
        
       Account acc = new Account();
acc.Name = 'End Customer Test';
acc.Organization_Size__c = '1 - 99';
acc.Industry = 'Agriculture';
acc.BillingState = 'California';
acc.BillingCountry = 'United States';
 insert acc;
        
        Contract cont1 = new Contract(
            AccountId = acc.Id,
            StartDate = System.today(),
            EndDate   = System.today().addDays(30),
            ContractTerm = 1
            );
        
        Contract cont2 = new Contract(
            AccountId = acc.Id,
            StartDate = System.today(),
            EndDate   = System.today().addDays(30),
            ContractTerm = 1
            );
        
        Opportunity opportunity1 = new Opportunity(
            Name = 'Opportunity 1',
            StageName = 'Qualified',
            CloseDate = Date.today().addDays(30),
            Amount = 5000,
            ContractId = cont1.Id,
            SBQQ__AmendedContract__c = cont1.Id,
            ACV_Amount_Multi_Currency__c = '4000'
        );
        
        Opportunity opportunity2 = new Opportunity(
            Name = 'Opportunity 2',
            StageName = 'Qualified',
            CloseDate = Date.today().addDays(45),
            Amount = 7000,
            ContractId = cont2.Id,
            SBQQ__AmendedContract__c = cont2.Id,
            ACV_Amount_Multi_Currency__c = '6000'
        );

			 insert new List<Opportunity>{opportunity1, opportunity2};
        
        // Step 2: Create a test method that calls the method to be tested
        Test.startTest();
        
        // Pass the Contract Ids to the method
        List<Id> contractIds = new List<Id>{cont1.Id, cont2.Id};
        List<Opportunity> opportunities = flex_OpenAmendmentOpportunityController.getAmendmentOpportunities(contractIds);
        
        Test.stopTest();        
    }

}