force-app/main/default/objects/Account/fields/Organization_Size__c.field-meta.xml
<CustomField>
    <fullName>Organization_Size__c</fullName>
    <description>Number of employees or students</description>
    <inlineHelpText>Number of employees or students</inlineHelpText>
    <label>Organization Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 - 99</fullName>
            </value>
            <value>
                <fullName>100 - 499</fullName>
            </value>
            <value>
                <fullName>500 - 999</fullName>
            </value>
            <value>
                <fullName>1000 - 4999</fullName>
            </value>
            <value>
                <fullName>5000+</fullName>
            </value>
            <value>
                <fullName>0</fullName>
                <isActive>false</isActive>
                <label>0</label>
            </value>
            <value>
                <fullName>1-99</fullName>
                <isActive>false</isActive>
                <label>1-99</label>
            </value>
            <value>
                <fullName>1/1/1999 12:00:00 AM</fullName>
                <isActive>false</isActive>
                <label>1/1/1999 12:00:00 AM</label>
            </value>
            <value>
                <fullName>10</fullName>
                <isActive>false</isActive>
                <label>10</label>
            </value>
            <value>
                <fullName>100 - 999</fullName>
                <isActive>false</isActive>
                <label>100 - 999</label>
            </value>
            <value>
                <fullName>100-499</fullName>
                <isActive>false</isActive>
                <label>100-499</label>
            </value>
            <value>
                <fullName>1000+</fullName>
                <isActive>false</isActive>
                <label>1000+</label>
            </value>
            <value>
                <fullName>1000-4999</fullName>
                <isActive>false</isActive>
                <label>1000-4999</label>
            </value>
            <value>
                <fullName>10000+</fullName>
                <isActive>false</isActive>
                <label>10000+</label>
            </value>
            <value>
                <fullName>11</fullName>
                <isActive>false</isActive>
                <label>11</label>
            </value>
            <value>
                <fullName>13</fullName>
                <isActive>false</isActive>
                <label>13</label>
            </value>
            <value>
                <fullName>200</fullName>
                <isActive>false</isActive>
                <label>200</label>
            </value>
            <value>
                <fullName>201-500</fullName>
                <isActive>false</isActive>
                <label>201-500</label>
            </value>
            <value>
                <fullName>21</fullName>
                <isActive>false</isActive>
                <label>21</label>
            </value>
            <value>
                <fullName>22</fullName>
                <isActive>false</isActive>
                <label>22</label>
            </value>
            <value>
                <fullName>29</fullName>
                <isActive>false</isActive>
                <label>29</label>
            </value>
            <value>
                <fullName>34</fullName>
                <isActive>false</isActive>
                <label>34</label>
            </value>
            <value>
                <fullName>36161</fullName>
                <isActive>false</isActive>
                <label>36161</label>
            </value>
            <value>
                <fullName>42</fullName>
                <isActive>false</isActive>
                <label>42</label>
            </value>
            <value>
                <fullName>495 - 1000</fullName>
                <isActive>false</isActive>
                <label>495 - 1000</label>
            </value>
            <value>
                <fullName>496 - 1000</fullName>
                <isActive>false</isActive>
                <label>496 - 1000</label>
            </value>
            <value>
                <fullName>497 - 1000</fullName>
                <isActive>false</isActive>
                <label>497 - 1000</label>
            </value>
            <value>
                <fullName>498 - 1000</fullName>
                <isActive>false</isActive>
                <label>498 - 1000</label>
            </value>
            <value>
                <fullName>499 - 1000</fullName>
                <isActive>false</isActive>
                <label>499 - 1000</label>
            </value>
            <value>
                <fullName>500 - 1000</fullName>
                <isActive>false</isActive>
                <label>500 - 1000</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Organization_Size__c.field-meta.xml
<CustomField>
    <fullName>Organization_Size__c</fullName>
    <formula>TEXT(Account.Organization_Size__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Please edit on the Account page.</inlineHelpText>
    <label>Organization Size</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Selected_Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Selected_Payment_Type__c</fullName>
    <label>Selected Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct Annual</fullName>
            </value>
            <value>
                <fullName>Direct Monthly</fullName>
            </value>
            <value>
                <fullName>Upfront Payments</fullName>
            </value>
            <value>
                <fullName>Direct Quarterly</fullName>
            </value>
            <value>
                <fullName>Direct Semi-Annual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Price_Book_Name__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_Name__c</fullName>
    <defaultValue>&quot;Samsara Standard&quot;</defaultValue>
    <description>Price Book Name, populated by workflow / field update</description>
    <label>Price Book Name</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Returning_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Returning_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Returning Opportunity</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Opportunity.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Opportunity.StageName</field>
            <operation>equals</operation>
            <value>Closed Won</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Return Opportunities</relationshipLabel>
    <relationshipName>Related_Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Selected_Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Selected_Payment_Type__c</fullName>
    <inlineHelpText>This dropdown list is populated based on what your customer has been approved for in Internal Financing. If you do not see a finance option then your customer has not been approved for that option.</inlineHelpText>
    <label>Selected Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Direct Monthly</fullName>
            </value>
            <value>
                <fullName>Direct Annual</fullName>
            </value>
            <value>
                <fullName>Upfront Payments</fullName>
            </value>
            <value>
                <fullName>Direct Semi-Annual</fullName>
            </value>
            <value>
                <fullName>Direct Quarterly</fullName>
            </value>
            <value>
                <fullName>Net-30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Shipping_Contact__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Shipping Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunity_Shipping_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Trial.recordType-meta.xml
<RecordType>
    <fullName>Trial</fullName>
    <active>true</active>
    <businessProcess>Standard Opportunities</businessProcess>
    <label>Trial</label>
</RecordType>

force-app/main/default/classes/Batch_ReturnOpptyDataFix_Test.cls
@isTest
public class Batch_ReturnOpptyDataFix_Test 
{
    @testSetup
    private static void testSetup()
    {
    }
    @isTest private static void testMethod001()
    {
        
        Account acc = new Account(Name = 'TestAccount',
                                  BillingState='California',
                                  BillingCountry = 'United States',
                                  Organization_Size__c = '100 - 499');
        insert acc;
        Contact con = (Contact) TestFactory.createSObject(new Contact(AccountId = acc.Id));
        insert con;
        Opportunity oppty = (Opportunity)
            TestFactory.createSObject(new Opportunity(AccountId = acc.Id, 
                                                      Type = 'Remorse Refund',
                                                      Name = 'Returning Oppty 001',
                                                      StageName = 'Refunded - Closed',
                                                      Shipping_Contact__c = con.Id, 
                                                      Price_Book_Name__c = 'Standard',
                                                      Selected_Payment_Type__c = 'Direct Annual',
                                                      CloseDate = Date.today().adddays(-1)));
        Insert oppty;
        
        Product2 prod = new Product2(Name= 'LIC-Test', ProductCode = 'LIC-Test', Family = 'Test');
        insert prod;
        
        Id pricebookId = Test.getStandardPricebookId();
        PricebookEntry pb = new PricebookEntry(Pricebook2Id = pricebookId, Product2Id = prod.Id, UnitPrice = 100, IsActive = true);
        insert pb;
        
        OpportunityLineItem ol = new OpportunityLineItem (OpportunityId=oppty.Id, Quantity=-1, PricebookEntryId=pb.Id, UnitPrice=pb.UnitPrice);
        Insert ol;
        
                  
        Contract contract = new Contract(
            AccountId = acc.Id,
            StartDate = Date.today(),
            EndDate = Date.today().adddays(100),
            ContractTerm = 12);
        insert contract;       
        
        Opportunity retOppty = (Opportunity)
            TestFactory.createSObject(new Opportunity(AccountId = acc.Id, 
                                                      Type = 'Trial',
                                                      Name = 'Returning Oppty 001',
                                                      StageName = 'Proposal',
                                                      Shipping_Contact__c = con.Id, 
                                                      Price_Book_Name__c = 'Standard',
                                                      Selected_Payment_Type__c = 'Direct Annual',
                                                      ContractId = contract.Id ));
        Insert retOppty;
        
        oppty.Returning_Opportunity__c = retOppty.Id;
        Update oppty;
        
        test.startTest();
        Batch_ReturnOpptyDataFix bc  = new Batch_ReturnOpptyDataFix();
        bc.execute(null);
        test.stopTest();
        
        
    }
    @isTest private static void testMethod002()
    {
        
        Account acc = new Account(Name = 'TestAccount',
                                  BillingState='California',
                                  BillingCountry = 'United States',
                                  Organization_Size__c = '100 - 499');
        insert acc;
        Contact con = (Contact) TestFactory.createSObject(new Contact(AccountId = acc.Id));
        insert con;
        Opportunity oppty = (Opportunity)
            TestFactory.createSObject(new Opportunity(AccountId = acc.Id, 
                                                      Type = 'Remorse Refund',
                                                      Name = 'Returning Oppty 001',
                                                      StageName = 'Refunded - Closed',
                                                      Shipping_Contact__c = con.Id, 
                                                      Price_Book_Name__c = 'Standard',
                                                      Selected_Payment_Type__c = 'Direct Annual',
                                                      CloseDate = Date.today().adddays(-1)));
        Insert oppty;
        
        Product2 prod = new Product2(Name= 'LIC-Test', ProductCode = 'LIC-Test', Family = 'Test');
        insert prod;
        
        Id pricebookId = Test.getStandardPricebookId();
        PricebookEntry pb = new PricebookEntry(Pricebook2Id = pricebookId, Product2Id = prod.Id, UnitPrice = 100, IsActive = true);
        insert pb;
        
        OpportunityLineItem ol = new OpportunityLineItem (OpportunityId=oppty.Id, Quantity=1, PricebookEntryId=pb.Id, UnitPrice=pb.UnitPrice);
        Insert ol;
        
        
        Contract contract = new Contract(
            AccountId = acc.Id,
            StartDate = Date.today(),
            EndDate = Date.today().adddays(100),
            ContractTerm = 12);
        insert contract;
        Opportunity retOppty = (Opportunity)
            TestFactory.createSObject(new Opportunity(AccountId = acc.Id, 
                                                      Type = 'Trial',
                                                      Name = 'Returning Oppty 001',
                                                      StageName = 'Proposal',
                                                      Shipping_Contact__c = con.Id, 
                                                      Price_Book_Name__c = 'Standard',
                                                      Selected_Payment_Type__c = 'Direct Annual',
                                                      SBQQ__AmendedContract__c = contract.Id ));
        Insert retOppty;
        
        oppty.Returning_Opportunity__c = retOppty.Id;
        Update oppty;
        
        test.startTest();
        Batch_ReturnOpptyDataFix bc  = new Batch_ReturnOpptyDataFix();
        bc.execute(null);
        test.stopTest();
        
        
    }
    @isTest private static void testMethod003()
    {
        
        Account acc = new Account(Name = 'TestAccount',
                                  BillingState='California',
                                  BillingCountry = 'United States',
                                  Organization_Size__c = '100 - 499');
        insert acc;
        Contact con = (Contact) TestFactory.createSObject(new Contact(AccountId = acc.Id));
        insert con;
        Opportunity oppty = (Opportunity)
            TestFactory.createSObject(new Opportunity(AccountId = acc.Id, 
                                                      Type = 'Remorse Refund',
                                                      Name = 'Returning Oppty 001',
                                                      StageName = 'Refunded - Closed',
                                                      Shipping_Contact__c = con.Id, 
                                                      Price_Book_Name__c = 'Standard',
                                                      Selected_Payment_Type__c = 'Direct Annual',
                                                      CloseDate = Date.today().adddays(-1)));
        Insert oppty;
        
        Product2 prod = new Product2(Name= 'LIC-Test', ProductCode = 'LIC-Test', Family = 'Test');
        insert prod;
        
        Id pricebookId = Test.getStandardPricebookId();
        PricebookEntry pb = new PricebookEntry(Pricebook2Id = pricebookId, Product2Id = prod.Id, UnitPrice = 100, IsActive = true);
        insert pb;
        
        OpportunityLineItem ol = new OpportunityLineItem (OpportunityId=oppty.Id, Quantity=1, PricebookEntryId=pb.Id, UnitPrice=pb.UnitPrice);
        Insert ol;
        
        Opportunity retOppty = (Opportunity)
            TestFactory.createSObject(new Opportunity(AccountId = acc.Id, 
                                                      Type = 'Trial',
                                                      Name = 'Returning Oppty 001',
                                                      StageName = 'Proposal',
                                                      Shipping_Contact__c = con.Id, 
                                                      Price_Book_Name__c = 'Standard',
                                                      Selected_Payment_Type__c = 'Direct Annual'));
        Insert retOppty;
        
        Contract contract1 = new Contract(
            AccountId = acc.Id,
            StartDate = Date.today(),
            EndDate = Date.today().adddays(100),
            ContractTerm = 12,
            SBQQ__Opportunity__c = retOppty.Id);
        insert contract1;
        
        Contract contract2 = new Contract(
            AccountId = acc.Id,
            StartDate = Date.today(),
            EndDate = Date.today().adddays(100),
            ContractTerm = 12,
            SBQQ__Opportunity__c = retOppty.Id);
        insert contract2;
        
        oppty.Returning_Opportunity__c = retOppty.Id;
        Update oppty;
        
        test.startTest();
        Batch_ReturnOpptyDataFix bc  = new Batch_ReturnOpptyDataFix();
        bc.execute(null);
        test.stopTest();
        
        
    }
    @isTest private static void testMethod004()
    {
        
        Account acc = new Account(Name = 'TestAccount',
                                  BillingState='California',
                                  BillingCountry = 'United States',
                                  Organization_Size__c = '100 - 499');
        insert acc;
        Contact con = (Contact) TestFactory.createSObject(new Contact(AccountId = acc.Id));
        insert con;
        Opportunity oppty = (Opportunity)
            TestFactory.createSObject(new Opportunity(AccountId = acc.Id, 
                                                      Type = 'Remorse Refund',
                                                      Name = 'Returning Oppty 001',
                                                      StageName = 'Refunded - Closed',
                                                      Shipping_Contact__c = con.Id, 
                                                      Price_Book_Name__c = 'Standard',
                                                      Selected_Payment_Type__c = 'Direct Annual',
                                                      CloseDate = Date.today().adddays(-1)));
        Insert oppty;
        
        Product2 prod = new Product2(Name= 'LIC-Test', ProductCode = 'LIC-Test', Family = 'Test');
        insert prod;
        
        Id pricebookId = Test.getStandardPricebookId();
        PricebookEntry pb = new PricebookEntry(Pricebook2Id = pricebookId, Product2Id = prod.Id, UnitPrice = 100, IsActive = true);
        insert pb;
        
        OpportunityLineItem ol = new OpportunityLineItem (OpportunityId=oppty.Id, Quantity=1, PricebookEntryId=pb.Id, UnitPrice=pb.UnitPrice);
        Insert ol;
        
        
        
        Opportunity retOppty = (Opportunity)
            TestFactory.createSObject(new Opportunity(AccountId = acc.Id, 
                                                      Type = 'Trial',
                                                      Name = 'Returning Oppty 001',
                                                      StageName = 'Proposal',
                                                      Shipping_Contact__c = con.Id, 
                                                      Price_Book_Name__c = 'Standard',
                                                      Selected_Payment_Type__c = 'Direct Annual'));
        Insert retOppty;
        
        oppty.Returning_Opportunity__c = retOppty.Id;
        Update oppty;
        
        test.startTest();
        Batch_ReturnOpptyDataFix bc  = new Batch_ReturnOpptyDataFix();
        bc.execute(null);
        test.stopTest();
        
        
    }
    @isTest private static void testMethod005()
    {
        test.startTest();
        Batch_ReturnOpptyDataFix bc  =new Batch_ReturnOpptyDataFix();
        bc.emailErrors('Test');
        test.stopTest();
    }
}