force-app/main/default/objects/Account/fields/Organization_Size__c.field-meta.xml
<CustomField>
    <fullName>Organization_Size__c</fullName>
    <description>Number of employees or students</description>
    <inlineHelpText>Number of employees or students</inlineHelpText>
    <label>Organization Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 - 99</fullName>
            </value>
            <value>
                <fullName>100 - 499</fullName>
            </value>
            <value>
                <fullName>500 - 999</fullName>
            </value>
            <value>
                <fullName>1000 - 4999</fullName>
            </value>
            <value>
                <fullName>5000+</fullName>
            </value>
            <value>
                <fullName>0</fullName>
                <isActive>false</isActive>
                <label>0</label>
            </value>
            <value>
                <fullName>1-99</fullName>
                <isActive>false</isActive>
                <label>1-99</label>
            </value>
            <value>
                <fullName>1/1/1999 12:00:00 AM</fullName>
                <isActive>false</isActive>
                <label>1/1/1999 12:00:00 AM</label>
            </value>
            <value>
                <fullName>10</fullName>
                <isActive>false</isActive>
                <label>10</label>
            </value>
            <value>
                <fullName>100 - 999</fullName>
                <isActive>false</isActive>
                <label>100 - 999</label>
            </value>
            <value>
                <fullName>100-499</fullName>
                <isActive>false</isActive>
                <label>100-499</label>
            </value>
            <value>
                <fullName>1000+</fullName>
                <isActive>false</isActive>
                <label>1000+</label>
            </value>
            <value>
                <fullName>1000-4999</fullName>
                <isActive>false</isActive>
                <label>1000-4999</label>
            </value>
            <value>
                <fullName>10000+</fullName>
                <isActive>false</isActive>
                <label>10000+</label>
            </value>
            <value>
                <fullName>11</fullName>
                <isActive>false</isActive>
                <label>11</label>
            </value>
            <value>
                <fullName>13</fullName>
                <isActive>false</isActive>
                <label>13</label>
            </value>
            <value>
                <fullName>200</fullName>
                <isActive>false</isActive>
                <label>200</label>
            </value>
            <value>
                <fullName>201-500</fullName>
                <isActive>false</isActive>
                <label>201-500</label>
            </value>
            <value>
                <fullName>21</fullName>
                <isActive>false</isActive>
                <label>21</label>
            </value>
            <value>
                <fullName>22</fullName>
                <isActive>false</isActive>
                <label>22</label>
            </value>
            <value>
                <fullName>29</fullName>
                <isActive>false</isActive>
                <label>29</label>
            </value>
            <value>
                <fullName>34</fullName>
                <isActive>false</isActive>
                <label>34</label>
            </value>
            <value>
                <fullName>36161</fullName>
                <isActive>false</isActive>
                <label>36161</label>
            </value>
            <value>
                <fullName>42</fullName>
                <isActive>false</isActive>
                <label>42</label>
            </value>
            <value>
                <fullName>495 - 1000</fullName>
                <isActive>false</isActive>
                <label>495 - 1000</label>
            </value>
            <value>
                <fullName>496 - 1000</fullName>
                <isActive>false</isActive>
                <label>496 - 1000</label>
            </value>
            <value>
                <fullName>497 - 1000</fullName>
                <isActive>false</isActive>
                <label>497 - 1000</label>
            </value>
            <value>
                <fullName>498 - 1000</fullName>
                <isActive>false</isActive>
                <label>498 - 1000</label>
            </value>
            <value>
                <fullName>499 - 1000</fullName>
                <isActive>false</isActive>
                <label>499 - 1000</label>
            </value>
            <value>
                <fullName>500 - 1000</fullName>
                <isActive>false</isActive>
                <label>500 - 1000</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Owner_Role_Copy__c.field-meta.xml
<CustomField>
    <fullName>Owner_Role_Copy__c</fullName>
    <description>Stores the role of the owner of the opportunity at the time it became a closed won.</description>
    <label>Owner Role Copy</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Created_From_NS__c.field-meta.xml
<CustomField>
    <fullName>Created_From_NS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Created From NS</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quota__c/Quota__c.object-meta.xml
<CustomObject>
    <description>Used for role&apos;s/rep&apos;s historical performance analysis.</description>
    <label>Quota</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Quota Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quota__c/fields/Fiscal_Period__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_Period__c</fullName>
    <description>Fiscal period associated with the quota.</description>
    <label>Fiscal Period</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quota__c/fields/Fiscal_Period_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_Period_End_Date__c</fullName>
    <description>Used to determine ramp period and status</description>
    <inlineHelpText>Used to determine ramp period and status</inlineHelpText>
    <label>Fiscal Period End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quota__c/fields/Fiscal_Period_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_Period_Start_Date__c</fullName>
    <description>Used to determine ramp period and status</description>
    <inlineHelpText>Used to determine ramp period and status</inlineHelpText>
    <label>Fiscal Period Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quota__c/fields/Q1_Quota__c.field-meta.xml
<CustomField>
    <fullName>Q1_Quota__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Q1 Quota</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quota__c/fields/Q2_Quota__c.field-meta.xml
<CustomField>
    <fullName>Q2_Quota__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Q2 Quota</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quota__c/fields/Q3_Quota__c.field-meta.xml
<CustomField>
    <fullName>Q3_Quota__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Q3 Quota</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quota__c/fields/Q4_Quota__c.field-meta.xml
<CustomField>
    <fullName>Q4_Quota__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Q4 Quota</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quota__c/fields/Quota__c.field-meta.xml
<CustomField>
    <fullName>Quota__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Amount associated with the quota instance.</description>
    <label>Quota</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quota__c/fields/Quota_Period__c.field-meta.xml
<CustomField>
    <fullName>Quota_Period__c</fullName>
    <description>Used to differentiate between monthly vs. quarterly quotas</description>
    <inlineHelpText>Used to differentiate between monthly vs. quarterly quotas</inlineHelpText>
    <label>Quota Period</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quota__c/fields/Quota_Period_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Quota_Period_End_Date__c</fullName>
    <description>For trigger to run. Rep cannot have a quota record with overlapping quota period start/end dates</description>
    <inlineHelpText>For trigger to run. Rep cannot have a quota record with overlapping quota period start/end dates</inlineHelpText>
    <label>Quota Period End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quota__c/fields/Quota_Period_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Quota_Period_Start_Date__c</fullName>
    <description>For trigger to run. Rep cannot have a quota record with overlapping quota period start/end dates</description>
    <inlineHelpText>For trigger to run. Rep cannot have a quota record with overlapping quota period start/end dates</inlineHelpText>
    <label>Quota Period Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quota__c/fields/Role_at_Start_of_Fiscal_Period__c.field-meta.xml
<CustomField>
    <fullName>Role_at_Start_of_Fiscal_Period__c</fullName>
    <description>Role of the rep at the start of Fiscal Period</description>
    <label>Role at Start of Fiscal Period</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quota__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User associated with the Quota instance.</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quotas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quota_Opportunity__c/Quota_Opportunity__c.object-meta.xml
<CustomObject>
    <label>Quota Opportunity</label>
    <nameField>
        <displayFormat>QO-{00000}</displayFormat>
        <label>Quote Opportunity Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quota Opportunities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quota_Opportunity__c/fields/Related_Quota__c.field-meta.xml
<CustomField>
    <fullName>Related_Quota__c</fullName>
    <label>Related Quota</label>
    <referenceTo>Quota__c</referenceTo>
    <relationshipLabel>Quota Opportunities (Related Quota)</relationshipLabel>
    <relationshipName>Quota_Opportunities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User/fields/Quota__c.field-meta.xml
<CustomField>
    <fullName>Quota__c</fullName>
    <description>Current Quarter Quota</description>
    <inlineHelpText>Current Quarter Quota set by Sales Management</inlineHelpText>
    <label>Quota</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/TestBatchAssociateQuotaToOpportunity.cls
@isTest
public with sharing class TestBatchAssociateQuotaToOpportunity {
    @TestSetup
    static void setup() {
//        Account acc = (Account) TestFactory.createSObject(
//                new Account(Name = 'Testing Class Account',
//                        Organization_Size__c = '1 - 99',
//                        Industry = 'Food & Beverage',
//                        CurrencyIsoCode = 'USD'),
//                true
//        );
//        final Integer oppAmount = Math.round(Math.random() * 10000);
//        insert new List<Opportunity>{
//                (Opportunity) TestFactory.createSObject(
//                        new Opportunity(AccountId = acc.Id,
//                                StageName = 'Closed Won',
//                                Amount = oppAmount,
//                                Type = 'Revenue Opportunity',
//                                Owner_Role_Copy__c = 'My Role',
//                                CurrencyIsoCode = 'USD')
//                ),
//                (Opportunity) TestFactory.createSObject(
//                        new Opportunity(AccountId = acc.Id,
//                                StageName = 'Refunded - Closed',
//                                Amount = oppAmount,
//                                Type = 'Free Trail Opportunity',
//                                Owner_Role_Copy__c = 'My Role',
//                                CurrencyIsoCode = 'USD')
//                )
//        };
        Account account = new Account(Name = 'Testing Class Account', Organization_Size__c = '1 - 99', Industry = 'Food & Beverage', CurrencyIsoCode = 'USD', Website = 'TestClassByHarsha.com', BillingCountry = 'United States', BillingState = 'California');
        insert account;
        List<Opportunity> newOppotunities = new List<Opportunity>();
        Opportunity opportunityClosed;
        Opportunity opportunityRefunded;
        for (Integer j = 0; j < 1; j++) {
            Integer randAmount = Math.round(Math.random() * 10000);
            Date closeDate = Date.Today();
            opportunityClosed = new Opportunity(Name = 'Test Opportunity ' + j, AccountId = account.Id, CloseDate = closeDate,
                    StageName = 'Closed Won', Amount = randAmount, Type = 'Revenue Opportunity',
                    Owner_Role_Copy__c = 'Management', CurrencyIsoCode = 'USD');

            newOppotunities.add(opportunityClosed);
        }

        for (Integer k = 0; k < 1; k++) {
            Integer randAmount = Math.round(Math.random() * 10000);
            Date closeDate = Date.Today() + 1;
            opportunityRefunded = new Opportunity(Name = 'Test Opportunity ' + k, AccountId = account.Id, CloseDate = closeDate,
                    StageName = 'Refunded - Closed', Amount = randAmount, Type = 'Free Trail Opportunity',
                    Owner_Role_Copy__c = 'Management', CurrencyIsoCode = 'USD');
            newOppotunities.add(opportunityRefunded);
        }

        insert newOppotunities;

        TestData.ProductsAndPriceBooks productsAndPricebooks = TestData.createProductsAndPricebookEntries();
        Map<String, PricebookEntry> pricebookEntries = productsAndPricebooks.pricebookEntries;

        Map<String, OpportunityLineItem> items = new Map<String, OpportunityLineItem>();
        OpportunityLineItem ol = new OpportunityLineItem (Quantity = 5, OpportunityId = opportunityClosed.Id, PriceBookEntryId = pricebookEntries.get('vg33').Id, UnitPrice = pricebookEntries.get('vg33').UnitPrice, Discount = 2);
        items.put('revVg33', ol);

        ol = new OpportunityLineItem (Quantity = 5, OpportunityId = opportunityClosed.Id, PriceBookEntryId = pricebookEntries.get('em11').Id, UnitPrice = pricebookEntries.get('em11').UnitPrice, Discount = 2);
        items.put('revEm11', ol);

        ol = new OpportunityLineItem (Quantity = 5, OpportunityId = opportunityRefunded.Id, PriceBookEntryId = pricebookEntries.get('vgLicense').Id, UnitPrice = pricebookEntries.get('vgLicense').UnitPrice, Discount = 2, Created_From_NS__c = true);
        items.put('revVgLicense', ol);

        ol = new OpportunityLineItem (Quantity = 5, OpportunityId = opportunityRefunded.Id, PriceBookEntryId = pricebookEntries.get('emLicense').Id, UnitPrice = pricebookEntries.get('emLicense').UnitPrice, Discount = 2);
        items.put('revEmLicense', ol);

        insert items.values();
    }

    
    @isTest
    static void testbatchassociatequotaopportunityGBP() {
        System.debug(LoggingLevel.INFO, '##### ScheduledAssociateQuotaOpportunityTest -> testAssociateQuotaOpportunityUSDGBP -> in test');

        TestDataFactoryForAccountsAndOpps.createQuota('GBP');
        List<Opportunity> newOppotunities = new List<Opportunity>();
        Test.startTest();
        Account account = new Account(Name = 'Testing Class Account', Organization_Size__c = '1 - 99', Industry = 'Food & Beverage', CurrencyIsoCode = 'USD', Website = 'TestClassByHarsha.com', BillingCountry = 'United States', BillingState = 'California');
        insert account;
        
        Opportunity opportunityClosed = new Opportunity(Name = 'Test Opportunity 1', AccountId = account.Id, CloseDate = Date.Today(),
                    StageName = 'Closed Won', Amount = 456, Type = 'Revenue Opportunity',
                    Owner_Role_Copy__c = 'Management', CurrencyIsoCode = 'USD');
            newOppotunities.add(opportunityClosed);
        insert newOppotunities;

        User user = [Select id from User where Id = :UserInfo.getUserId()];
        Quota__c quota = new Quota__c(User__c = user.id, Role_at_Start_of_Fiscal_Period__c = 'Management', CurrencyIsoCode = 'USD', Quota__c = 8000,Q1_Quota__c = 2000,Q2_Quota__c = 2000,Q3_Quota__c = 2000,Q4_Quota__c = 2000, Quota_Period_End_Date__c = Date.Today() + 10, Quota_Period_Start_Date__c = Date.Today() - 4, Fiscal_Period_End_Date__c = Date.Today() + 4, Fiscal_Period_Start_Date__c = Date.Today() - 4, Quota_Period__c = 'Test', Fiscal_Period__c = 'Test');
        insert quota;
       
        BatchAssociateQuotaToOpportunity b = new BatchAssociateQuotaToOpportunity();
        b.execute(null);       
        //String CRON_EXP = '0 0 0 3 9 ? 2022';
        //String jobId = System.schedule('BatchAssociateQuotaToOpportunity', CRON_EXP, new BatchAssociateQuotaToOpportunity());
        Test.stopTest();
    }

    @isTest
    static void testmapdata() {
        

        List<Opportunity> newOppotunities = new List<Opportunity>();
        Account account = new Account(Name = 'Testing Class Account', Organization_Size__c = '1 - 99', Industry = 'Food & Beverage', CurrencyIsoCode = 'USD', Website = 'TestClassByHarsha.com', BillingCountry = 'United States', BillingState = 'California');
        insert account;
        Test.starttest();
        Opportunity opportunityClosed = new Opportunity(Name = 'Test Opportunity 1', AccountId = account.Id, CloseDate = Date.Today(),
                    StageName = 'Closed Won', Amount = 456, Type = 'Revenue Opportunity',
                    Owner_Role_Copy__c = 'My Role', CurrencyIsoCode = 'USD');
            newOppotunities.add(opportunityClosed);
        insert newOppotunities;

        User user = [Select id from User where Id = :UserInfo.getUserId()];
        Quota__c quota = new Quota__c(User__c = user.id, Role_at_Start_of_Fiscal_Period__c = 'My Role', CurrencyIsoCode = 'USD', Quota__c = 8000, Q1_Quota__c = 2000,Q2_Quota__c = 2000,Q3_Quota__c = 2000,Q4_Quota__c = 2000, Quota_Period_End_Date__c = Date.Today() + 4, Quota_Period_Start_Date__c = Date.Today() - 4, Fiscal_Period_End_Date__c = Date.Today() + 4, Fiscal_Period_Start_Date__c = Date.Today() - 4, Quota_Period__c = 'Test', Fiscal_Period__c = 'Test');
        insert quota;

        List<Quota_Opportunity__c> newQuotaOpportunities = new List<Quota_Opportunity__c>();
        Quota_Opportunity__c qo = new Quota_Opportunity__c(Related_Quota__c = quota.id);
        newQuotaOpportunities.add(qo);
        insert newQuotaOpportunities;



        BatchAssociateQuotaToOpportunity b = new BatchAssociateQuotaToOpportunity();  
        b.mapData(newQuotaOpportunities[0], newOppotunities[0], quota);
        Test.stopTest();
    }

}