force-app/main/default/objects/Account/fields/Organization_Size__c.field-meta.xml
<CustomField>
    <fullName>Organization_Size__c</fullName>
    <description>Number of employees or students</description>
    <inlineHelpText>Number of employees or students</inlineHelpText>
    <label>Organization Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 - 99</fullName>
            </value>
            <value>
                <fullName>100 - 499</fullName>
            </value>
            <value>
                <fullName>500 - 999</fullName>
            </value>
            <value>
                <fullName>1000 - 4999</fullName>
            </value>
            <value>
                <fullName>5000+</fullName>
            </value>
            <value>
                <fullName>0</fullName>
                <isActive>false</isActive>
                <label>0</label>
            </value>
            <value>
                <fullName>1-99</fullName>
                <isActive>false</isActive>
                <label>1-99</label>
            </value>
            <value>
                <fullName>1/1/1999 12:00:00 AM</fullName>
                <isActive>false</isActive>
                <label>1/1/1999 12:00:00 AM</label>
            </value>
            <value>
                <fullName>10</fullName>
                <isActive>false</isActive>
                <label>10</label>
            </value>
            <value>
                <fullName>100 - 999</fullName>
                <isActive>false</isActive>
                <label>100 - 999</label>
            </value>
            <value>
                <fullName>100-499</fullName>
                <isActive>false</isActive>
                <label>100-499</label>
            </value>
            <value>
                <fullName>1000+</fullName>
                <isActive>false</isActive>
                <label>1000+</label>
            </value>
            <value>
                <fullName>1000-4999</fullName>
                <isActive>false</isActive>
                <label>1000-4999</label>
            </value>
            <value>
                <fullName>10000+</fullName>
                <isActive>false</isActive>
                <label>10000+</label>
            </value>
            <value>
                <fullName>11</fullName>
                <isActive>false</isActive>
                <label>11</label>
            </value>
            <value>
                <fullName>13</fullName>
                <isActive>false</isActive>
                <label>13</label>
            </value>
            <value>
                <fullName>200</fullName>
                <isActive>false</isActive>
                <label>200</label>
            </value>
            <value>
                <fullName>201-500</fullName>
                <isActive>false</isActive>
                <label>201-500</label>
            </value>
            <value>
                <fullName>21</fullName>
                <isActive>false</isActive>
                <label>21</label>
            </value>
            <value>
                <fullName>22</fullName>
                <isActive>false</isActive>
                <label>22</label>
            </value>
            <value>
                <fullName>29</fullName>
                <isActive>false</isActive>
                <label>29</label>
            </value>
            <value>
                <fullName>34</fullName>
                <isActive>false</isActive>
                <label>34</label>
            </value>
            <value>
                <fullName>36161</fullName>
                <isActive>false</isActive>
                <label>36161</label>
            </value>
            <value>
                <fullName>42</fullName>
                <isActive>false</isActive>
                <label>42</label>
            </value>
            <value>
                <fullName>495 - 1000</fullName>
                <isActive>false</isActive>
                <label>495 - 1000</label>
            </value>
            <value>
                <fullName>496 - 1000</fullName>
                <isActive>false</isActive>
                <label>496 - 1000</label>
            </value>
            <value>
                <fullName>497 - 1000</fullName>
                <isActive>false</isActive>
                <label>497 - 1000</label>
            </value>
            <value>
                <fullName>498 - 1000</fullName>
                <isActive>false</isActive>
                <label>498 - 1000</label>
            </value>
            <value>
                <fullName>499 - 1000</fullName>
                <isActive>false</isActive>
                <label>499 - 1000</label>
            </value>
            <value>
                <fullName>500 - 1000</fullName>
                <isActive>false</isActive>
                <label>500 - 1000</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Organization_Size__c.field-meta.xml
<CustomField>
    <fullName>Organization_Size__c</fullName>
    <formula>TEXT(Account.Organization_Size__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Please edit on the Account page.</inlineHelpText>
    <label>Organization Size</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Planned_Trial_Installation_Date__c.field-meta.xml
<CustomField>
    <fullName>Planned_Trial_Installation_Date__c</fullName>
    <description>This is the date in which the customer plans to install the trial.</description>
    <label>Planned Trial Installation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Shipping_Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Address_Line_1__c</fullName>
    <label>Shipping Address Line 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Shipping_City__c.field-meta.xml
<CustomField>
    <fullName>Shipping_City__c</fullName>
    <label>Shipping City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Shipping_Contact__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Shipping Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunity_Shipping_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Trial_Agreement_Accepted__c.field-meta.xml
<CustomField>
    <fullName>Trial_Agreement_Accepted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to check if Trial Agreement has been accepted by the Customer</description>
    <label>Trial Agreement Accepted?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Trial_Goal_1__c.field-meta.xml
<CustomField>
    <fullName>Trial_Goal_1__c</fullName>
    <label>Trial Goal 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Trial_Period__c.field-meta.xml
<CustomField>
    <fullName>Trial_Period__c</fullName>
    <defaultValue>IF( CONTAINS( $UserRole.Name , &quot;Industrial&quot;), 15, 
IF(  
OR(
CONTAINS( $UserRole.Name , &quot;ENT&quot;),
CONTAINS( $UserRole.Name , &quot;Major&quot;)), 
90,
IF(CONTAINS( $UserRole.Name, &quot;AE3&quot;), 60,
30)))</defaultValue>
    <description>Length of trial in days, as per Free Trial Agreement</description>
    <inlineHelpText>Default period of 30 days for Inside sales + partner managers, 60 days for Major Accounts, 15 days for Industrial</inlineHelpText>
    <label>Trial Period (in days)</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Trial_Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Trial_Primary_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Primary contact for Trial - this is the person who will sign the Trial Agreement</description>
    <inlineHelpText>Person who will sign Trial Agreement</inlineHelpText>
    <label>Trial Primary Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Trial Primary Contact)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Trial_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Trial_Start_Date__c</fullName>
    <description>Date on which Trial is expected to start, as per Free Trial Agreement</description>
    <inlineHelpText>As discussed with customer</inlineHelpText>
    <label>Trial Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Trial_Status__c.field-meta.xml
<CustomField>
    <fullName>Trial_Status__c</fullName>
    <label>Trial Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Shipped</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Purchased</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Return In Process</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>Write-off</fullName>
            </value>
            <value>
                <fullName>Partial Purchase</fullName>
            </value>
            <value>
                <fullName>Partial Return</fullName>
            </value>
            <value>
                <fullName>Pending Return or Write-Off</fullName>
                <isActive>false</isActive>
                <label>Pending Return or Write-Off</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TrialResolutionOppty__c.field-meta.xml
<CustomField>
    <fullName>TrialResolutionOppty__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reference to a Trial&apos;s Revenue or Return opportunity.</description>
    <label>Revenue Opportunity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Opportunity.Type</field>
            <operation>equals</operation>
            <value>Revenue Opportunity, Free Trial Return, Revenue Opportunity - Bill Only</value>
        </filterItems>
        <filterItems>
            <field>Opportunity.StageName</field>
            <operation>notEqual</operation>
            <value>Closed Won</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunities (Trial Resolution Oppty)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Trial.recordType-meta.xml
<RecordType>
    <fullName>Trial</fullName>
    <active>true</active>
    <businessProcess>Standard Opportunities</businessProcess>
    <label>Trial</label>
</RecordType>

force-app/main/default/objects/OpportunityLineItem/fields/Product_Code_Copy__c.field-meta.xml
<CustomField>
    <fullName>Product_Code_Copy__c</fullName>
    <description>Copy of Product Code to enable rollup summaries etc.</description>
    <label>Product Code Copy</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Shipped_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Shipped_Quantity__c</fullName>
    <description>Number shipped</description>
    <label>Shipped Quantity</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Trial_Status__c.field-meta.xml
<CustomField>
    <fullName>Trial_Status__c</fullName>
    <label>Trial Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Purchased</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/QuantityControllerExtensionTest.cls
@IsTest
private class QuantityControllerExtensionTest {

    @TestSetup static void setupRecords() {


        System.debug('In testShipQty');


        TestData.ProductsAndPriceBooks productsAndPriceBook = TestData.createProductsAndPricebookEntries();
        Map<String, PricebookEntry> pricebookEntries = productsAndPriceBook.pricebookEntries;

        // Create account
        Account a = new Account (Name = 'Acme Co', Organization_Size__c = '5000+', BillingCountry = 'Canada', Industry = 'Other');
        insert a;

        Contact c = new Contact (FirstName = 'Juan', LastName = 'Perez', Email = 'juan@a.com', AccountId = a.Id);
        insert c;

        RecordType trialType = [SELECT Id FROM RecordType WHERE SObjectType = 'Opportunity' AND Name = 'Trial' LIMIT 1];

        // Create Revenue Oppty
        Map<String, Opportunity> oppsInsert = new Map<String, Opportunity>();
        Opportunity rev = new Opportunity(AccountId = a.Id, Name = 'Rev', CloseDate = System.today() + 90, StageName = 'Incubate');
        insert rev;

        // create trial associated with revenue opportunity - first one is not shipped
        Opportunity o = new Opportunity(AccountId = a.Id, Name = 'Free Trial', CloseDate = System.today() + 90, RecordTypeId = trialType.Id,
                Probability = 0, StageName = 'Incubate', Trial_Status__c = 'Open', type = 'Free Trial Opportunity', TrialResolutionOppty__c = rev.Id, Planned_Trial_Installation_Date__c = System.today() + 5, Trial_Goal_1__c = 'Test', Trial_Period__c = 30, Trial_Start_Date__c = System.today(), Trial_Primary_Contact__c = c.Id);
        oppsInsert.put('trialNotShipped', o);
        // create trial associated with revenue oppty - this one will be shipped
        o = new Opportunity(AccountId = a.Id, Name = 'Free Trial', CloseDate = System.today() + 90, RecordTypeId = trialType.Id,
                Probability = 0, StageName = 'Incubate', type = 'Free Trial Opportunity', Trial_Status__c = 'Open', TrialResolutionOppty__c = rev.Id);
        //setShipping(o);
        oppsInsert.put('trialShipped', o);
        insert oppsInsert.values();

        Test.startTest();

        // Add Revenue Oppty products
        Map<String, OpportunityLineItem> items = new Map<String, OpportunityLineItem>();
        OpportunityLineItem ol = new OpportunityLineItem (Quantity = 5, OpportunityId = rev.Id, PriceBookEntryId = pricebookEntries.get('vg33').Id, UnitPrice = pricebookEntries.get('vg33').UnitPrice);
        items.put('revVg33', ol);

        ol = new OpportunityLineItem (Quantity = 5, OpportunityId = rev.Id, PriceBookEntryId = pricebookEntries.get('em11').Id, UnitPrice = pricebookEntries.get('em11').UnitPrice);
        items.put('revEm11', ol);

        ol = new OpportunityLineItem (Quantity = 5, OpportunityId = rev.Id, PriceBookEntryId = pricebookEntries.get('vgLicense').Id, UnitPrice = pricebookEntries.get('vgLicense').UnitPrice);
        items.put('revVgLicense', ol);

        ol = new OpportunityLineItem (Quantity = 5, OpportunityId = rev.Id, PriceBookEntryId = pricebookEntries.get('emLicense').Id, UnitPrice = pricebookEntries.get('emLicense').UnitPrice);
        items.put('revEmLicense', ol);

        // add products to not shipped trial
        ol = new OpportunityLineItem (Quantity = 2, OpportunityId = oppsInsert.get('trialNotShipped').Id, PriceBookEntryId = pricebookEntries.get('em11').Id, UnitPrice = pricebookEntries.get('em11').UnitPrice);
        items.put('trialNotShippedEm11', ol);

        ol = new OpportunityLineItem (Quantity = 2, OpportunityId = oppsInsert.get('trialNotShipped').Id, PriceBookEntryId = pricebookEntries.get('emLicense').Id, UnitPrice = pricebookEntries.get('emLicense').UnitPrice);
        items.put('trialNotShippedEmLicense', ol);

        // add products to shipped trial
        ol = new OpportunityLineItem (Quantity = 1, OpportunityId = oppsInsert.get('trialShipped').Id, PriceBookEntryId = pricebookEntries.get('vg33').Id, UnitPrice = pricebookEntries.get('vg33').UnitPrice);
        items.put('trailShippedVg33', ol);

        ol = new OpportunityLineItem (Quantity = 1, OpportunityId = oppsInsert.get('trialShipped').Id, PriceBookEntryId = pricebookEntries.get('vgLicense').Id, UnitPrice = pricebookEntries.get('vgLicense').UnitPrice);
        items.put('trialShippedVgLicense', ol);

        ol = new OpportunityLineItem (Quantity = 1, OpportunityId = oppsInsert.get('trialShipped').Id, PriceBookEntryId = pricebookEntries.get('emLicense').Id, UnitPrice = pricebookEntries.get('emLicense').UnitPrice);
        items.put('trialShippedVgLicense', ol);

        insert items.values();
        //System.debug(LoggingLevel.INFO, 'here are the line items inserted: ' + items);

        // ship trial
        Opportunity oppToUpdate = new Opportunity();
        oppToUpdate = oppsInsert.get('trialShipped');
        oppToUpdate.Trial_Agreement_Accepted__c = true;
        oppToUpdate.Probability = 100;
        oppToUpdate.StageName = 'Closed Won';
        update oppToUpdate;
        oppsInsert.put('trialShipped', oppToUpdate);

        Test.stopTest();

        //System.assertEquals('Open', [SELECT Trial_Status__c FROM Opportunity WHERE Id = :oppsInsert.get('trialShipped').Id LIMIT 1].Trial_Status__c);

        // create trial associated with revenue oppty - this one will be shipped too
        //Opportunity trialShipped2 = new Opportunity(AccountId = a.Id, Name = 'Free Trial', CloseDate = System.today() + 90, RecordTypeId = trialType.Id, 
        //Probability = 0, StageName = 'Incubate', type = 'Free Trial Opportunity', TrialResolutionOppty__c = rev.Id, Planned_Trial_Installation_Date__c = System.today()+5, Trial_Goal_1__c  = 'Test', Trial_Period__c=30, Trial_Start_Date__c=System.today(), Trial_Primary_Contact__c=c.Id);
        //setShipping2(trialShipped2);
        //insert trialShipped2;

        //OpportunityLineItem trailShipped2Vg33 = new OpportunityLineItem (Quantity=1, OpportunityId=trialShipped2.Id, PriceBookEntryId=pricebookEntries.get('vg33').Id, UnitPrice = pricebookEntries.get('vg33').UnitPrice);
        //insert trailShipped2Vg33;

        // ship trial
        //trialShipped2.Trial_Agreement_Accepted__c = true;
        //trialShipped2.Probability = 100;
        //trialShipped2.StageName = 'Closed Won';
        //System.debug(LoggingLevel.INFO, '108');
        //update trialShipped2;
    }

    @isTest static void testRevControllerLoad() {
        Opportunity rev = [SELECT Id, AccountId, Name, CloseDate, StageName FROM Opportunity WHERE Name = 'Rev' LIMIT 1];
        Test.startTest();
        QuantityControllerExtension qtyController = new QuantityControllerExtension(new ApexPages.StandardController(rev));
        Test.stopTest();
    }

    @isTest static void testTrialControllerLoad() {
        Opportunity trial = [SELECT Id, AccountId, Name, CloseDate, StageName FROM Opportunity WHERE Name = 'Free Trial' LIMIT 1];
        Test.startTest();
        QuantityControllerExtension qtyController = new QuantityControllerExtension(new ApexPages.StandardController(trial));
        Test.stopTest();
    }

    @IsTest static void testShipQty() {
        // Start testing quantities page
        Opportunity rev = [SELECT Id, AccountId, Name, CloseDate, StageName FROM Opportunity WHERE Name = 'Rev' LIMIT 1];
        Test.startTest();
        QuantityControllerExtension qtyController = new QuantityControllerExtension(new ApexPages.StandardController(rev));

        Map<String, Decimal> trialQuantities = qtyController.getTrialQuantities();

        PageReference submitted = qtyController.submit();

        System.assertEquals(submitted.getUrl(), '/' + rev.id);

        /*
        List<OpportunityLineItem> revLineItems = [Select Id, OpportunityId, Shipped_Quantity__c, Product_Code_Copy__c from OpportunityLineItem where OpportunityId = :rev.Id];
        for (OpportunityLineItem revLi : revLineItems){
            if (revLi.Product_Code_Copy__c == 'HW-VG33'){
                System.assertEquals(revLi.Shipped_Quantity__c, 3);
            }
            else if (revLi.Product_Code_Copy__c == 'LIC-VG-36MO'){
                System.assertEquals(revLi.Shipped_Quantity__c, 4);
            }
            else if (revLi.Product_Code_Copy__c == 'HW-EM11'){
                System.assertEquals(revLi.Shipped_Quantity__c, 5);
            }
            else if (revLi.Product_Code_Copy__c == 'LIC-EM-36MO'){
                System.assertEquals(revLi.Shipped_Quantity__c, 5);
            }
        }
        */

        PageReference back = qtyController.backToOppty();

        System.assertEquals(submitted.getUrl(), '/' + rev.id);


        System.debug('In testShipQty End');
        Test.stopTest();
    }
    @isTest static void testTrialQuantities() {
        Opportunity rev = [SELECT Id, AccountId, Name, CloseDate, StageName FROM Opportunity WHERE Name = 'Rev' LIMIT 1];
        Test.startTest();
        QuantityControllerExtension qtyController = new QuantityControllerExtension(new ApexPages.StandardController(rev));
        Map<String, Decimal> testMap = qtyController.getPurchasedTrialQuantities();
        Map<String, Decimal> trialQuantities = qtyController.getTrialQuantities();
        for (String s : trialQuantities.keySet()) {
            trialQuantities.put(s, 1.0);
        }
        qtyController.shipQuantities = trialQuantities;
        PageReference pr = qtyController.refresh();
        Test.stopTest();
    }

    @isTest static void testTetShipLocations() {
        Opportunity rev = [SELECT Id, AccountId, Name, CloseDate, StageName FROM Opportunity WHERE Name = 'Rev' LIMIT 1];
        Test.startTest();
        QuantityControllerExtension qtyController = new QuantityControllerExtension(new ApexPages.StandardController(rev));
        Map<String, String> shipLocations = qtyController.getShipLocations();
        Test.stopTest();
    }

    @isTest static void testInputQuantities() {
        Opportunity rev = [SELECT Id, AccountId, Name, CloseDate, StageName FROM Opportunity WHERE Name = 'Rev' LIMIT 1];
        Test.startTest();
        QuantityControllerExtension qtyController = new QuantityControllerExtension(new ApexPages.StandardController(rev));
        Map<String, Decimal> inputQuantities = qtyController.getInputQuantities();
        for (String s : inputQuantities.keySet()) {
            inputQuantities.put(s, 1.0);
        }
        qtyController.inputQuantityMap = inputQuantities;
        PageReference pr = qtyController.submit_rep();
        Test.stopTest();
    }

    @isTest static void testRefresh() {
        Opportunity rev = [SELECT Id, AccountId, Name, CloseDate, StageName FROM Opportunity WHERE Name = 'Rev' LIMIT 1];
        Test.startTest();
        QuantityControllerExtension qtyController = new QuantityControllerExtension(new ApexPages.StandardController(rev));
        PageReference pr = qtyController.refresh();
        Test.stopTest();
    }

    @isTest static void testValidate() {
        Opportunity rev = [SELECT Id, AccountId, Name, CloseDate, StageName FROM Opportunity WHERE Name = 'Rev' LIMIT 1];
        Test.startTest();
        QuantityControllerExtension qtyController = new QuantityControllerExtension(new ApexPages.StandardController(rev));
        Boolean boo = qtyController.validate_form();
        Test.stopTest();
    }

    static private void setShipping(Opportunity o) {
        Contact c = new Contact (email = 'test@test.com', LastName = 'x');
        insert c;
        o.Shipping_Contact__c = c.Id;

        o.Shipping_Address_Line_1__c = 'x';
        o.Shipping_City__c = 'x';
        o.Shipping_State__c = 'x';
        o.Shipping_Zip_Code__c = 'x';
        o.Shipping_Country__c = 'Canada';
    }

    static private void setShipping2(Opportunity o) {
        Contact c = new Contact (email = 'yyy@test.com', LastName = 'yyy');
        insert c;
        o.Shipping_Contact__c = c.Id;

        o.Shipping_Address_Line_1__c = 'x';
        o.Shipping_City__c = 'x';
        o.Shipping_State__c = 'x';
        o.Shipping_Zip_Code__c = 'x';
        o.Shipping_Country__c = 'Canada';
    }
}