force-app/main/default/objects/Account/fields/Organization_Size__c.field-meta.xml
<CustomField>
    <fullName>Organization_Size__c</fullName>
    <description>Number of employees or students</description>
    <inlineHelpText>Number of employees or students</inlineHelpText>
    <label>Organization Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 - 99</fullName>
            </value>
            <value>
                <fullName>100 - 499</fullName>
            </value>
            <value>
                <fullName>500 - 999</fullName>
            </value>
            <value>
                <fullName>1000 - 4999</fullName>
            </value>
            <value>
                <fullName>5000+</fullName>
            </value>
            <value>
                <fullName>0</fullName>
                <isActive>false</isActive>
                <label>0</label>
            </value>
            <value>
                <fullName>1-99</fullName>
                <isActive>false</isActive>
                <label>1-99</label>
            </value>
            <value>
                <fullName>1/1/1999 12:00:00 AM</fullName>
                <isActive>false</isActive>
                <label>1/1/1999 12:00:00 AM</label>
            </value>
            <value>
                <fullName>10</fullName>
                <isActive>false</isActive>
                <label>10</label>
            </value>
            <value>
                <fullName>100 - 999</fullName>
                <isActive>false</isActive>
                <label>100 - 999</label>
            </value>
            <value>
                <fullName>100-499</fullName>
                <isActive>false</isActive>
                <label>100-499</label>
            </value>
            <value>
                <fullName>1000+</fullName>
                <isActive>false</isActive>
                <label>1000+</label>
            </value>
            <value>
                <fullName>1000-4999</fullName>
                <isActive>false</isActive>
                <label>1000-4999</label>
            </value>
            <value>
                <fullName>10000+</fullName>
                <isActive>false</isActive>
                <label>10000+</label>
            </value>
            <value>
                <fullName>11</fullName>
                <isActive>false</isActive>
                <label>11</label>
            </value>
            <value>
                <fullName>13</fullName>
                <isActive>false</isActive>
                <label>13</label>
            </value>
            <value>
                <fullName>200</fullName>
                <isActive>false</isActive>
                <label>200</label>
            </value>
            <value>
                <fullName>201-500</fullName>
                <isActive>false</isActive>
                <label>201-500</label>
            </value>
            <value>
                <fullName>21</fullName>
                <isActive>false</isActive>
                <label>21</label>
            </value>
            <value>
                <fullName>22</fullName>
                <isActive>false</isActive>
                <label>22</label>
            </value>
            <value>
                <fullName>29</fullName>
                <isActive>false</isActive>
                <label>29</label>
            </value>
            <value>
                <fullName>34</fullName>
                <isActive>false</isActive>
                <label>34</label>
            </value>
            <value>
                <fullName>36161</fullName>
                <isActive>false</isActive>
                <label>36161</label>
            </value>
            <value>
                <fullName>42</fullName>
                <isActive>false</isActive>
                <label>42</label>
            </value>
            <value>
                <fullName>495 - 1000</fullName>
                <isActive>false</isActive>
                <label>495 - 1000</label>
            </value>
            <value>
                <fullName>496 - 1000</fullName>
                <isActive>false</isActive>
                <label>496 - 1000</label>
            </value>
            <value>
                <fullName>497 - 1000</fullName>
                <isActive>false</isActive>
                <label>497 - 1000</label>
            </value>
            <value>
                <fullName>498 - 1000</fullName>
                <isActive>false</isActive>
                <label>498 - 1000</label>
            </value>
            <value>
                <fullName>499 - 1000</fullName>
                <isActive>false</isActive>
                <label>499 - 1000</label>
            </value>
            <value>
                <fullName>500 - 1000</fullName>
                <isActive>false</isActive>
                <label>500 - 1000</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Fleet.recordType-meta.xml
<RecordType>
    <fullName>Fleet</fullName>
    <active>true</active>
    <description>Fleet account</description>
    <label>Fleet</label>
</RecordType>

force-app/main/default/objects/Customer_360__c/Customer_360__c.object-meta.xml
<CustomObject>
    <label>Customer 360</label>
    <nameField>
        <label>Customer 360 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer 360</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_360__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer 360</relationshipLabel>
    <relationshipName>Customer_360</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BatchDeleteDuplicateCustomer360MainTest.cls
@isTest
public class BatchDeleteDuplicateCustomer360MainTest {
    static Account createAccount() {
        Account account = new Account();
        account.Name = 'MyTestAccount';
        account.Type = 'Fleet';
        account.Industry = 'Other';
        account.organization_size__c = '1 - 99';
        account.billingstreet = '123 Main St, San Francisco CA, 94110';
        account.billingstate = 'California';
        account.billingcountry = 'United States';
        account.billingcity = 'San Francisco';
        account.billingPostalCode = '94110';
        account.shippingstreet = '123 Main St, San Francisco CA, 94110';
        account.shippingstate = 'California';
        account.shippingcountry = 'United States';
        account.shippingcity = 'San Francisco';
        account.shippingPostalCode = '94110';
        insert account;
        return account;
    }
    static List<Customer_360__c> createListCustomer360() 
    {
        List<Customer_360__c> cus=new List<Customer_360__c>();
        Customer_360__c cus1=new Customer_360__c();
        Account acc=createAccount();
        cus1.Account__c=acc.id;
        Customer_360__c cus2=new Customer_360__c();
        cus2.Account__c=acc.id;
        cus.add(cus2);
        cus.add(cus1);
        insert cus;
        return cus;
        
    }
    
    @isTest
    static void BatchDeleteDuplicateCustomer360MainTestMethod()
    {
        List<Customer_360__c> dataForBatch=createListCustomer360();
        System.Test.startTest();
        Database.executeBatch(new BatchDeleteDuplicateCustomer360Main(),1);
        System.Test.stopTest();
        
    }
    
}