force-app/main/default/objects/Account/fields/Sales_Ops_Notes__c.field-meta.xml
<CustomField>
    <fullName>Sales_Ops_Notes__c</fullName>
    <description>Internal Sales Ops notes for any notes, approvals, etc.</description>
    <inlineHelpText>Internal Sales Ops notes for any notes, approvals, etc.</inlineHelpText>
    <label>Sales Ops Notes</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Fleet.recordType-meta.xml
<RecordType>
    <fullName>Fleet</fullName>
    <active>true</active>
    <description>Fleet account</description>
    <label>Fleet</label>
</RecordType>

force-app/main/default/objects/Contract/fields/Sales_Ops_Notes__c.field-meta.xml
<CustomField>
    <fullName>Sales_Ops_Notes__c</fullName>
    <label>Sales Ops Notes</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/License_Term__c.field-meta.xml
<CustomField>
    <fullName>License_Term__c</fullName>
    <defaultValue>36</defaultValue>
    <description>The license term of the opportunity.</description>
    <label>License Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Max_Approved_Discount__c.field-meta.xml
<CustomField>
    <fullName>Max_Approved_Discount__c</fullName>
    <defaultValue>0.10</defaultValue>
    <label>Approved Discretionary Discount</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Owner_Role_Copy__c.field-meta.xml
<CustomField>
    <fullName>Owner_Role_Copy__c</fullName>
    <description>Stores the role of the owner of the opportunity at the time it became a closed won.</description>
    <label>Owner Role Copy</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Price_Book_Name__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_Name__c</fullName>
    <defaultValue>&quot;Samsara Standard&quot;</defaultValue>
    <description>Price Book Name, populated by workflow / field update</description>
    <label>Price Book Name</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sales_Ops_Notes__c.field-meta.xml
<CustomField>
    <fullName>Sales_Ops_Notes__c</fullName>
    <description>Internal Sales Ops notes for any notes, approvals, etc.</description>
    <inlineHelpText>Internal Sales Ops notes for any notes, approvals, etc.</inlineHelpText>
    <label>Sales Ops Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Product2/fields/License_Term__c.field-meta.xml
<CustomField>
    <fullName>License_Term__c</fullName>
    <label>License Term</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/License_Term__c.field-meta.xml
<CustomField>
    <fullName>License_Term__c</fullName>
    <formula>Opportunity.License_Term__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>License Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/License_Term__c.field-meta.xml
<CustomField>
    <fullName>License_Term__c</fullName>
    <label>License Term</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>36</fullName>
                <default>true</default>
                <label>36</label>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Quote_Name__c.field-meta.xml
<CustomField>
    <fullName>Quote_Name__c</fullName>
    <description>Text field for Sales to use to label quotes</description>
    <label>Quote Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Sales_Ops_Notes__c.field-meta.xml
<CustomField>
    <fullName>Sales_Ops_Notes__c</fullName>
    <label>Sales Ops Notes</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__SubscriptionTerm__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__SubscriptionTerm__c</fullName>
    <description>Subscription term used to prorate eligible products by day or month.  This has been set by your administrator.</description>
    <inlineHelpText>Subscription term used to prorate eligible products by day or month.  This has been set by your administrator.</inlineHelpText>
    <label>Subscription Term</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/accountLookupTest__c.field-meta.xml
<CustomField>
    <fullName>accountLookupTest__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Y</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quote Lines (Account)</relationshipLabel>
    <relationshipName>Quote_Lines1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Renewal_LineItem_Type__c.field-meta.xml
<CustomField>
    <fullName>Renewal_LineItem_Type__c</fullName>
    <description>Pulling and persisting the renewal QL value of LineItem Type for twinning to its contracted Subscription.
Created as part of GTMS-6087 &amp; GTMS-6088</description>
    <formula>/* IF(ISBLANK(TEXT(LineItem_Type_Override__c)), LineItem_type__c, TEXT(LineItem_Type_Override__c)). */


IF(
  ISBLANK(TEXT(LineItem_Type_Override__c)), 
    IF(ISPICKVAL(SBQQ__Quote__r.SBQQ__Type__c, &apos;Amendment&apos;), 
      IF(CONTAINS(SBQQ__ProductCode__c, &apos;LIC&apos;), 
          IF(SBQQ__UpgradedSubscription__c != null, SBQQ__UpgradedSubscription__r.Original_LineItem_Type__c
        ,&apos;Upsell&apos;)
    ,null)

  ,IF(CONTAINS(SBQQ__ProductCode__c, &apos;LIC&apos;), 
      IF(SBQQ__RenewedSubscription__c != null &amp;&amp; Previous_Quantity__c &gt; SBQQ__Quantity__c, &apos;Downsell&apos;
        ,IF(SBQQ__RenewedSubscription__c != null &amp;&amp; Previous_Quantity__c &lt; SBQQ__Quantity__c, &apos;Upsell&apos;
          ,IF(SBQQ__RenewedSubscription__c != null &amp;&amp; Previous_Quantity__c = SBQQ__Quantity__c, &apos;Renewed line&apos;
              ,IF(SBQQ__RenewedSubscription__c == null &amp;&amp; SBQQ__UpgradedSubscription__c == null, &apos;Upsell&apos;
                  ,null
                  ))))
  ,null)
)
,TEXT(LineItem_Type_Override__c)
)</formula>
    <label>Renewal LineItem Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__NetPrice__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__NetPrice__c</fullName>
    <description>Net unit price for the product quoted by this line item.</description>
    <inlineHelpText>Net unit price for the product quoted by this line item.</inlineHelpText>
    <label>Net Unit Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/SBQQ__Subscription__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Subscription__c/fields/NS_Unit_Rate__c.field-meta.xml
<CustomField>
    <fullName>NS_Unit_Rate__c</fullName>
    <description>NS Unit Rate from Opportunity Products</description>
    <label>NS Unit Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/Prior_OppId_Legacy__c.field-meta.xml
<CustomField>
    <fullName>Prior_OppId_Legacy__c</fullName>
    <description>Captures the Opportunity Id this Subscription record is generated from</description>
    <inlineHelpText>Captures the Opportunity Id this Subscription record is generated from</inlineHelpText>
    <label>Prior OppId (Legacy)</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/Renewal_LineItem_Type__c.field-meta.xml
<CustomField>
    <fullName>Renewal_LineItem_Type__c</fullName>
    <description>Twinned from Renewal QL.
Created as part of GTMS-6087 &amp; GTMS-6088</description>
    <label>Renewal LineItem Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__Contract__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contract that governs this subscription.</description>
    <inlineHelpText>Contract that governs this subscription.</inlineHelpText>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__Discount__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Discount__c</fullName>
    <description>Additional Discount for this Subscription, if expressed as a percentage</description>
    <inlineHelpText>Additional Discount for this Subscription, if expressed as a percentage</inlineHelpText>
    <label>Additional Disc. (%)</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__ListPrice__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__ListPrice__c</fullName>
    <description>List price for this subscription product.</description>
    <inlineHelpText>List price for this subscription product.</inlineHelpText>
    <label>List Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__NetPrice__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__NetPrice__c</fullName>
    <description>Net price for this subscription.</description>
    <inlineHelpText>Net price for this subscription.</inlineHelpText>
    <label>Net Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__Product__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product used to sell this subscription.</description>
    <inlineHelpText>Product used to sell this subscription.</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__Quantity__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quantity__c</fullName>
    <description>Quantity of this subscription product purchased by the customer.</description>
    <inlineHelpText>Quantity of this subscription product purchased by the customer.</inlineHelpText>
    <label>Quantity</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__QuoteLine__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__QuoteLine__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Quote line that generated this subscription.</description>
    <inlineHelpText>Quote line that generated this subscription.</inlineHelpText>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__RenewalQuantity__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__RenewalQuantity__c</fullName>
    <description>Quantity of this subscription product that will be renewed.</description>
    <inlineHelpText>Quantity of this subscription product that will be renewed.</inlineHelpText>
    <label>Renewal Quantity</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__SubscriptionEndDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__SubscriptionEndDate__c</fullName>
    <description>Matches the quote line end date by default. If blank, it will match the contract end date.</description>
    <inlineHelpText>Matches the quote line end date by default. If blank, it will match the contract end date.</inlineHelpText>
    <label>Subscription End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/SBQQ__SubscriptionStartDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__SubscriptionStartDate__c</fullName>
    <description>Matches the quote line start date by default. If blank, it will match the contract start date.</description>
    <inlineHelpText>Matches the quote line start date by default. If blank, it will match the contract start date.</inlineHelpText>
    <label>Subscription Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/LegacySubscriptionsFixBatchTest.cls
/**
 * Jan-10-2023 Rajesh GTMS-10518
 */
@isTest
public with sharing class LegacySubscriptionsFixBatchTest {
    @testSetup
    private static void testDataSetup() {
        //Standard Pricebook
        Id pricebookId = Test.getStandardPricebookId();
        
        //Create Products
        List<Product2> products = new List<Product2>();
        Product2 vg33 = new Product2(Name= 'HW-VG33', ProductCode = 'HW-VG33', Family = 'Test');
        products.add(vg33);
        Product2 vgLicense = new Product2(Name= 'LIC-VG-36MO', ProductCode = 'LIC-VG-36MO', Family = 'Test');
        products.add(vgLicense);  
        Product2 insuranceSUBSIDY = new Product2(Name= 'INS-SUBSIDY', ProductCode = 'INS-SUBSIDY', Family = 'Test');
        products.add(insuranceSUBSIDY);  
        insert products;
        
        //Create PriceBookEntries
        List<PricebookEntry> pricebookEntries = new List<PricebookEntry>();
        PricebookEntry vg33PB = new PricebookEntry(Pricebook2Id = pricebookId, Product2Id = vg33.Id, UnitPrice = 10000, IsActive = true);
        pricebookEntries.add(vg33PB);
        PricebookEntry vgLicensePB = new PricebookEntry(Pricebook2Id = pricebookId, Product2Id = vgLicense.Id, UnitPrice = 10000, IsActive = true);
        pricebookEntries.add(vgLicensePB);
        PricebookEntry insuranceSUBSIDYPB = new PricebookEntry(Pricebook2Id = pricebookId, Product2Id = insuranceSUBSIDY.Id, UnitPrice = 10000, IsActive = true);
        pricebookEntries.add(insuranceSUBSIDYPB);
        insert pricebookEntries;        
        Account account = new Account ();
        account = TestFactory.initializeAccount('Test Account');
        insert account;
        List<Contract> contracts = new List<Contract>();
        Contract contract = new Contract(
                AccountId = account.Id,
                StartDate = Date.today(),
                EndDate = Date.today().adddays(30),
                ContractTerm = 12
        );
        Contract contract2 = new Contract(
                AccountId = account.Id,
                StartDate = Date.today(),
                EndDate = Date.today().adddays(30),
                ContractTerm = 37,
                Sales_Ops_Notes__c = 'Test'
        );
        Contract contract3 = new Contract(
                AccountId = account.Id,
                StartDate = Date.today(),
                EndDate = Date.today().adddays(30),
                ContractTerm = 72,
                Sales_Ops_Notes__c = 'Test'
        );
        Contract contract4 = new Contract(
                AccountId = account.Id,
                StartDate = Date.today(),
                EndDate = Date.today().adddays(30),
                ContractTerm = 24,
                Sales_Ops_Notes__c = 'Test'
        );
        Contract contract5 = new Contract(
                AccountId = account.Id,
                StartDate = Date.today(),
                EndDate = Date.today().adddays(30),
                ContractTerm = 75,
                Sales_Ops_Notes__c = 'Test'
        );
        contracts.add(contract);
        contracts.add(contract2);
        contracts.add(contract3);
        contracts.add(contract4);
        contracts.add(contract5);
        insert contracts;
        
        Opportunity revenueOpportunity = new Opportunity( AccountId = account.Id, License_Term__c =36, Pricebook2Id = pricebookId, 
                                                         Max_Approved_Discount__c=0, Name = 'Revenue Opportunity', Price_Book_Name__c = 'Standard Price Book', 
                                                         CloseDate = System.today() + 90, StageName = 'Incubate', Owner_Role_Copy__c='Fleet IS AE2 NA US Team 8');
        insert revenueOpportunity;        
    }
    @IsTest
    private static void testBeforeInsert(){
        Account testAccount = [SELECT id, Name, BillingCountry FROM Account WHERE Name like '%Test Account%'];
        Opportunity testOpportunity = [SELECT id, Name From Opportunity WHERE Name='Revenue Opportunity'];
        List<Contract> ctt = [SELECT Id, StartDate,EndDate FROM Contract];
        
        Product2 vgProduct = [SELECT id FROM Product2 WHERE Name = 'LIC-VG-36MO'];
        PricebookEntry pricebookEntry = [SELECT id, Product2Id, UnitPrice FROM PricebookEntry WHERE Product2Id =: vgProduct.Id]; 
        
        SBQQ__Quote__c quote = new SBQQ__Quote__c(Quote_Name__c = 'Test Version', SBQQ__Opportunity2__c =testOpportunity.Id, 
                                                  SBQQ__Primary__c = false, SBQQ__Type__c='Quote',
                                                  SBQQ__SubscriptionTerm__c=12);
        SBQQ__Quote__c quote2 = new SBQQ__Quote__c(Quote_Name__c = 'Test Version', SBQQ__Opportunity2__c =testOpportunity.Id, 
                                                  SBQQ__Primary__c = false, SBQQ__Type__c='Quote',
                                                  SBQQ__SubscriptionTerm__c=37);
        List<SBQQ__Quote__c> quotes = new List<SBQQ__Quote__c>();
        quotes.add(quote);
        quotes.add(quote2);
        insert quotes;
        
        List<SBQQ__QuoteLine__c> newlineItems = new List<SBQQ__QuoteLine__c>();
        SBQQ__QuoteLine__c quoteLineOne =  new SBQQ__QuoteLine__c(SBQQ__Quote__c = quote.Id, SBQQ__PricebookEntryId__c = pricebookEntry.Id, SBQQ__Quantity__c  = 5, 
                                                                  SBQQ__Discount__c = 0, SBQQ__Product__c = vgProduct.Id, accountLookupTest__c = testAccount.Id,
                                                                  SBQQ__ListPrice__c=100);
        newlineItems.add(quoteLineOne); 
        
        SBQQ__QuoteLine__c quoteLineTwo =  new SBQQ__QuoteLine__c(SBQQ__Quote__c = quote2.Id, SBQQ__PricebookEntryId__c = pricebookEntry.Id, SBQQ__Quantity__c  = 5, 
                                                                  SBQQ__Discount__c = 0, SBQQ__Product__c = vgProduct.Id, accountLookupTest__c = testAccount.Id,
                                                                  SBQQ__ListPrice__c=100);
        newlineItems.add(quoteLineTwo);
        
        insert newlineItems;
        List<SBQQ__Subscription__c> subscriptionList = new List<SBQQ__Subscription__c>();
        SBQQ__Subscription__c subscription1 = new SBQQ__Subscription__c(
            SBQQ__QuoteLine__c=quoteLineOne.Id,
            SBQQ__NetPrice__c = 10,
            SBQQ__RenewalQuantity__c = -5,
            SBQQ__Quantity__c = -5,
            SBQQ__Product__c = vgProduct.Id,
            SBQQ__Contract__c = ctt[0].Id,
            SBQQ__SubscriptionStartDate__c = ctt[0].StartDate,
            SBQQ__SubscriptionEndDate__c=ctt[0].EndDate,
            Renewal_LineItem_Type__c = 'Downsell',
            NS_Unit_Rate__c = 100
        );
        subscriptionList.add(subscription1);
        SBQQ__Subscription__c subscription2 = new SBQQ__Subscription__c(
            SBQQ__QuoteLine__c=quoteLineTwo.Id,
            SBQQ__NetPrice__c = 10,
            SBQQ__RenewalQuantity__c = 10,
            SBQQ__Quantity__c = 10,
            SBQQ__BundledQuantity__c=10,
            SBQQ__Product__c = vgProduct.Id,
            SBQQ__Contract__c = ctt[0].Id,
            SBQQ__SubscriptionStartDate__c = ctt[0].StartDate,
            SBQQ__SubscriptionEndDate__c=ctt[0].EndDate,
            Renewal_LineItem_Type__c = 'Downsell',
            NS_Unit_Rate__c = 100
        );
        subscriptionList.add(subscription2);
        SBQQ__Subscription__c subscription3 = new SBQQ__Subscription__c(
            SBQQ__QuoteLine__c=quoteLineOne.Id,
            SBQQ__NetPrice__c = 10,
            SBQQ__RenewalQuantity__c = -5,
            SBQQ__Quantity__c = -5,
            SBQQ__Product__c = vgProduct.Id,
            SBQQ__Contract__c = ctt[1].Id,
            SBQQ__SubscriptionStartDate__c = ctt[1].StartDate,
            SBQQ__SubscriptionEndDate__c=ctt[1].EndDate,
            Renewal_LineItem_Type__c = 'Downsell',
            NS_Unit_Rate__c = 100
        );
        subscriptionList.add(subscription3);
        SBQQ__Subscription__c subscription4 = new SBQQ__Subscription__c(
            //SBQQ__QuoteLine__c=quoteLineOne.Id,
            SBQQ__NetPrice__c = 10,
            SBQQ__RenewalQuantity__c = -5,
            SBQQ__Quantity__c = -5,
            SBQQ__Product__c = vgProduct.Id,
            SBQQ__Contract__c = ctt[2].Id,
            SBQQ__SubscriptionStartDate__c = ctt[2].StartDate,
            SBQQ__SubscriptionEndDate__c=ctt[2].EndDate,
            Renewal_LineItem_Type__c = 'Downsell',
            NS_Unit_Rate__c = 100,
            SBQQ__ListPrice__c = 100,
            Prior_OppId_Legacy__c = testOpportunity.id
        );
        subscriptionList.add(subscription4);
        SBQQ__Subscription__c subscription5 = new SBQQ__Subscription__c(
            SBQQ__QuoteLine__c=quoteLineOne.Id,
            SBQQ__NetPrice__c = 10,
            SBQQ__RenewalQuantity__c = -5,
            SBQQ__Quantity__c = -5,
            SBQQ__Product__c = vgProduct.Id,
            SBQQ__Contract__c = ctt[3].Id,
            SBQQ__SubscriptionStartDate__c = ctt[3].StartDate,
            SBQQ__SubscriptionEndDate__c=ctt[3].EndDate,
            Renewal_LineItem_Type__c = 'Downsell',
            NS_Unit_Rate__c = 100
        );
        subscriptionList.add(subscription5);
        SBQQ__Subscription__c subscription6 = new SBQQ__Subscription__c(
            SBQQ__QuoteLine__c=quoteLineOne.Id,
            SBQQ__NetPrice__c = 10,
            SBQQ__RenewalQuantity__c = -5,
            SBQQ__Quantity__c = -5,
            SBQQ__Product__c = vgProduct.Id,
            SBQQ__Contract__c = ctt[4].Id,
            SBQQ__SubscriptionStartDate__c = ctt[4].StartDate,
            SBQQ__SubscriptionEndDate__c=ctt[4].EndDate,
            Renewal_LineItem_Type__c = 'Downsell',
            NS_Unit_Rate__c = 100
        );
        subscriptionList.add(subscription6);
        insert subscriptionList;       
               
        String chron = '0 1 * * * ?';
        Test.startTest();
            database.executebatch(new LegacySubscriptionsFixBatch(),5);
        Test.stopTest();
    }  
}