force-app/main/default/objects/Account/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <description>This field is being used by Netsuite and code for contracts. Before it is changed Business Systems needs to be notified, as it has a number of dependencies.</description>
    <formula>IF(

CONTAINS(Owner.UserRole.Name, &quot;Small Fleets&quot;),
&quot;Small Business&quot;,
IF(
CONTAINS(Owner.UserRole.Name, &quot;AE1&quot;),
&quot;AE1&quot;,
IF(
OR(
CONTAINS(Owner.UserRole.Name, &quot;Partner&quot;),
CONTAINS(Owner.UserRole.Name, &quot;AE2&quot;)
),
&quot;AE2&quot;,
IF(
CONTAINS(Owner.UserRole.Name, &quot;AE3&quot;),
&quot;AE3&quot;,
IF(
OR(
CONTAINS(Owner.UserRole.Name, &quot;ENT&quot;),
CONTAINS(Owner.UserRole.Name, &quot;Enterprise&quot;),
CONTAINS(Owner.UserRole.Name, &quot;Major&quot;),
CONTAINS(Owner.UserRole.Name, &quot;Field&quot;)
),
&quot;Enterprise&quot;,
&quot;Management&quot;
)
)
)
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Segment (by Current Owner)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Async_Request__c/Async_Request__c.object-meta.xml
<CustomObject>
    <description>Use to queue up an Asynchronous Request for processing</description>
    <label>Async Request</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Async Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Async Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Async_Request__c/fields/Options__c.field-meta.xml
<CustomField>
    <fullName>Options__c</fullName>
    <description>Additional Options that can be used when processing the request</description>
    <label>Options</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Async_Request__c/fields/Params__c.field-meta.xml
<CustomField>
    <fullName>Params__c</fullName>
    <label>Params</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Configuration_Segment__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Segment__c</fullName>
    <label>Configuration Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Express</fullName>
            </value>
            <value>
                <fullName>Non Express</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/FP_and_Upsell_ACV__c.field-meta.xml
<CustomField>
    <fullName>FP_and_Upsell_ACV__c</fullName>
    <label>First Purchase and Upsell ACV</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Is_Webstore_Upsell_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Is_Webstore_Upsell_Opportunity__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Webstore Upsell Opportunity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/License_Term__c.field-meta.xml
<CustomField>
    <fullName>License_Term__c</fullName>
    <defaultValue>36</defaultValue>
    <description>The license term of the opportunity.</description>
    <label>License Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Owner_Segment__c.field-meta.xml
<CustomField>
    <fullName>Owner_Segment__c</fullName>
    <formula>IF(

CONTAINS(Owner_Role_Copy__c,&quot;Small Fleets&quot;),
&quot;Small Business&quot;,
IF(
OR(
CONTAINS(Owner_Role_Copy__c,&quot;AE1&quot;),
CONTAINS(Owner_Role_Copy__c,&quot;SMB&quot;)
),
&quot;AE1&quot;,
IF(
OR(
CONTAINS(Owner_Role_Copy__c,&quot;AE2&quot;),
CONTAINS(Owner_Role_Copy__c,&quot;MM&quot;)
),
&quot;AE2&quot;,
IF(
CONTAINS(Owner_Role_Copy__c,&quot;AE3&quot;),
&quot;AE3&quot;,
IF(
OR(
CONTAINS(Owner_Role_Copy__c,&quot;Major&quot;),
CONTAINS(Owner_Role_Copy__c,&quot;Enterprise&quot;),
CONTAINS(Owner_Role_Copy__c,&quot;ENT&quot;),
CONTAINS(Owner_Role_Copy__c,&quot;Field&quot;)
),
&quot;Enterprise&quot;,
&quot;Other&quot;
)
)
)
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Owner Segment</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Renewal_ACV__c.field-meta.xml
<CustomField>
    <fullName>Renewal_ACV__c</fullName>
    <label>Renewal ACV</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <description>Used by Finance for Netsuite and financial reporting.</description>
    <formula>if( CONTAINS(Pricebook2.Name,&quot;Samsara Express&quot;),&quot;SMB&quot;,

if( AND(OR(CONTAINS(Owner_Role_Copy__c,&quot;MM&quot;),CONTAINS(Owner_Role_Copy__c,&quot;Mid Market&quot;)),Industrial_Oppty__c =FALSE),&quot;Mid Market&quot;,

if( AND(OR(CONTAINS(Owner_Role_Copy__c,&quot;MM&quot;),CONTAINS(Owner_Role_Copy__c,&quot;Mid Market&quot;)),Industrial_Oppty__c =TRUE),&quot;Industrial&quot;,

if( AND(OR(CONTAINS(Owner_Role_Copy__c,&quot;Major Accounts&quot;),CONTAINS(Owner_Role_Copy__c,&quot;Major&quot;),CONTAINS(Owner_Role_Copy__c,&quot;Field&quot;),CONTAINS(Owner_Role_Copy__c,&quot;Enterprise&quot;)),Industrial_Oppty__c =FALSE),&quot;Enterprise&quot;,

if( AND(OR(CONTAINS(Owner_Role_Copy__c,&quot;Major Accounts&quot;),CONTAINS(Owner_Role_Copy__c,&quot;Major&quot;),CONTAINS(Owner_Role_Copy__c,&quot;Field&quot;),CONTAINS(Owner_Role_Copy__c,&quot;Enterprise&quot;)),Industrial_Oppty__c =TRUE),&quot;Industrial&quot;,

if(AND(CONTAINS(Owner_Role_Copy__c,&quot;SMB&quot;),CONTAINS(Pricebook2.Name,&quot;Samsara Standard&quot;)),&quot;Mid Market&quot;,

if(CONTAINS(Owner_Role_Copy__c,&quot;Industrial&quot;),&quot;Industrial&quot;,

if(OR(CONTAINS(Owner_Role_Copy__c,&quot;Management&quot;),CONTAINS(Owner_Role_Copy__c, &quot;Operations&quot;)), Account.Segment_Text_stamped__c , Account.Segment_Text_stamped__c))))))))</formula>
    <inlineHelpText>Deprecated--use Finance Segment instead.</inlineHelpText>
    <label>[DON&apos;T USE] Segment (Price Book)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Upsell_ACV__c.field-meta.xml
<CustomField>
    <fullName>Upsell_ACV__c</fullName>
    <description>copy of Upsell ACV from Quote</description>
    <label>New ACV</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/License_Term__c.field-meta.xml
<CustomField>
    <fullName>License_Term__c</fullName>
    <formula>Opportunity.License_Term__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>License Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote_To_Opportunity_Mapping__mdt/Quote_To_Opportunity_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>Quote To Opportunity Mapping</label>
    <pluralLabel>Quote To Opportunity Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Quote_To_Opportunity_Mapping__mdt/fields/Bypass__c.field-meta.xml
<CustomField>
    <fullName>Bypass__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote_To_Opportunity_Mapping__mdt/fields/Null_Check__c.field-meta.xml
<CustomField>
    <fullName>Null_Check__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Determine if the field needs to perform a null check</inlineHelpText>
    <label>Null Check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote_To_Opportunity_Mapping__mdt/fields/Opportunity_Field__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Field__c</fullName>
    <label>Opportunity Field</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_To_Opportunity_Mapping__mdt/fields/Owner_Segment__c.field-meta.xml
<CustomField>
    <fullName>Owner_Segment__c</fullName>
    <label>Owner Segment</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quote_To_Opportunity_Mapping__mdt/fields/Quote_Field__c.field-meta.xml
<CustomField>
    <fullName>Quote_Field__c</fullName>
    <label>Quote Field</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_To_Opportunity_Mapping__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>Field used to determine if field should be updated on Opp based on Sales Motion</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Non Express</fullName>
            </value>
            <value>
                <fullName>Express</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Configuration_Segment__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Segment__c</fullName>
    <label>Configuration Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Express</fullName>
            </value>
            <value>
                <fullName>Non Express</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Custom_License_Term__c.field-meta.xml
<CustomField>
    <fullName>Custom_License_Term__c</fullName>
    <description>field used by managers and sales ops to set custom term lengths outside of the standard 36, 48, 60 terms</description>
    <label>Custom License Term</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/First_Calculated__c.field-meta.xml
<CustomField>
    <fullName>First_Calculated__c</fullName>
    <label>First Calculated</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/License_Term__c.field-meta.xml
<CustomField>
    <fullName>License_Term__c</fullName>
    <label>License Term</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>36</fullName>
                <default>true</default>
                <label>36</label>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Owner_Segment__c.field-meta.xml
<CustomField>
    <fullName>Owner_Segment__c</fullName>
    <formula>IF( 
 OR( 
  CONTAINS(SBQQ__Opportunity2__r.Owner_Role_Copy__c ,&quot;SMB&quot;), 
  CONTAINS(SBQQ__Opportunity2__r.Price_Book_Name__c  , &quot;Express&quot; ), 
  SBQQ__Opportunity2__r.Small_Fleet_Opportunity__c  
 ), 
 &quot;SMB&quot;, 
 IF( 
  OR( 
   CONTAINS(SBQQ__Opportunity2__r.Owner_Role_Copy__c,&quot;Industrial&quot;), 
    SBQQ__Opportunity2__r.Industrial_Oppty__c  = TRUE 
  ), 
  &quot;Industrial&quot;,
IF(
CONTAINS(SBQQ__Opportunity2__r.Owner_Role_Copy__c,&quot;Connected Worker&quot;),
&quot;Connected Worker&quot;, 
  IF( 
   OR( 
    CONTAINS(SBQQ__Opportunity2__r.Owner_Role_Copy__c,&quot;Experimental&quot;), 
    CONTAINS(SBQQ__Opportunity2__r.Owner_Role_Copy__c,&quot;MM&quot;), 
    CONTAINS(SBQQ__Opportunity2__r.Owner_Role_Copy__c,&quot;Mid Market&quot;) 
   ), 
   &quot;Mid Market&quot;, 
   IF( 
    OR( 
     CONTAINS(SBQQ__Opportunity2__r.Owner_Role_Copy__c,&quot;Major&quot;), 
     CONTAINS(SBQQ__Opportunity2__r.Owner_Role_Copy__c,&quot;Enterprise&quot;), 
     CONTAINS(SBQQ__Opportunity2__r.Owner_Role_Copy__c,&quot;Field&quot;) 
    ), 
   &quot;Enterprise&quot;, 
  &quot;Other&quot; 
  ) 
 ) 
 ) 
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Owner Segment</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Recalculate_Quote__c.field-meta.xml
<CustomField>
    <fullName>Recalculate_Quote__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Recalculate Quote</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Renewal_ACV__c.field-meta.xml
<CustomField>
    <fullName>Renewal_ACV__c</fullName>
    <description>Populated by QCP. Created as part of GTMS-6087</description>
    <label>Renewal ACV[Deprecated]</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Renewal_Amount__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Amount__c</fullName>
    <label>Renewal Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Upsell_ACV__c.field-meta.xml
<CustomField>
    <fullName>Upsell_ACV__c</fullName>
    <description>Set by price rule. 
Created as part of GTMS-6085</description>
    <label>Upsell ACV[Deprecated]</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Upsell_Amount__c.field-meta.xml
<CustomField>
    <fullName>Upsell_Amount__c</fullName>
    <label>Upsell Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/GS_SBQQQuoteServiceAsync.cls
/**
* Created By : Groundswell - Suman Kundu
* @Date September 10, 2021
*
* @description : This class will be responsible for handling Async Actions on SBQQ Quote
* SFA-11
*
**/

public without sharing class GS_SBQQQuoteServiceAsync extends BaseAsyncHandler{
    gslib_IModuleLogger thisModuleLogger = gslib_LoggerService.getModuleLogger('GTMS');
    gslib_ILogger thisLogger = thisModuleLogger.getLogger(); 
    public override String getRequestType(){
        return 'SBQQ Quote Service Async Job';
    } 
    
    List<Schema.SObjectType> MY_SOBJECTS = new List<Schema.SObjectType>{
        SBQQ__Quote__c.SObjectType
    };
                
    UnitOfWork uow = new UnitOfWork(MY_SOBJECTS);
    @TestVisible List<Id> recordsIds = new List<Id>();
    private Options option;
    public static String asyncContext;
    
    public override void execute(Async_Request__c ar)
    {
        recordsIds = ar.Params__c.split(PARAMETERS_SPLITTER);
        if(recordsIds.isEmpty()) return;
        option = (Options) JSON.deserialize(ar.Options__c, Options.class);
        
        // Do something with Quote Records
        try{
            thisLogger.logTrace('Entering in GS_SBQQQuoteServiceAsync');
            System.debug('****option.Operation> '+option.Operation);
            switch on option.Operation {
                when 'Insert' {
                }
                when 'Update' {
                }
                when 'Upsert' {
                }
                when 'Delete' {
                }
                /* when 'recalculateQuote' {
                    recalculateQuote();
                } */
                when 'CopyQuoteFieldsToOppty' {
                    asyncContext = 'CopyQuoteFieldsToOppty';
                    copyValuesToOpporttunity();
                }
                /*when 'updatedQuoteLines' {
                    updatedQuoteLines();
                }*/
            }
        }catch(Exception ex){
            thisLogger.logError(
                'Error in GS_SBQQQuoteServiceAsync::',
                new SamsaraLoggerObjectMVP(
                    ex, recordsIds
                )
            );
            throw ex;
        }finally{
            thisLogger.dispatch();
        }
    }

    /* public void recalculateQuote() {
        List<SBQQ__Quote__c> qts = new List <SBQQ__Quote__c>();
        for (Id quoteId : recordsIds) {
            SBQQ__Quote__c cpq = new SBQQ__Quote__c(Id = quoteId, Recalculate_Quote__c = true, First_Calculated__c = Date.today());
            qts.add(cpq);
        }
        if (!qts.isempty()) {
            thisLogger.logDebug('Recalculating Quote Records :: ', recordsIds);
            uow.registerDirty(qts);
            uow.commitWork();
        }

        List<CS_Record__c> csRecords = new List<CS_Record__c>();
        csRecords = new GS_CS_RecordSelector(true).checkFatalError().getCSRecordsByIds(recordsIds);
        if(!csRecords.isEmpty()) {
            thisLogger.logDebug('Deleting CS Record  ::', csRecords);
            //delete csRecords;
            uow.registerDeleted(csRecords);
            uow.commitWork();
        }
    } */

    // Below method copies values from Quote to Oppotunity
    public void copyValuesToOpporttunity() {
        thisLogger.logTrace('Entering into copyValuesToOpportunity');
        DMLWrapper.intializeUnitOfWork(new List<Schema.SObjectType>{
            Opportunity.SObjectType
        });
        Set<Id> quoteIds = new Set<Id>();
        quoteIds.addAll(recordsIds);
        List<SBQQ__Quote__c> quoteList = new GS_SBQQQuoteSelector(true).checkFatalError().getAllCustomFieldsQuotesById(quoteIds).values();
        Set<Id> opptyIds = new Set<Id>();
        for (SBQQ__Quote__c quote : quoteList) {
            opptyIds.add(quote.SBQQ__Opportunity2__c);
        }
        List<Quote_To_Opportunity_Mapping__mdt> quoteToOpptyFieldMapping = new GS_QuoteToOpportunityMappingSelector(true).checkFatalError().getFieldMapping();
        Map<Id, Opportunity> opptyMap = new GS_OpportunitySelector(true).checkFatalError().getQuoteToOppotyFieldMappingData(opptyIds, quoteToOpptyFieldMapping);
        if (opptyMap == null || opptyMap.size() == 0) {
            return;
        }
        Map<String, Quote_To_Opportunity_Mapping__mdt> fieldMappings = new Map<String, Quote_To_Opportunity_Mapping__mdt>();
        for (Quote_To_Opportunity_Mapping__mdt mapping : quoteToOpptyFieldMapping) {
            fieldMappings.put(mapping.Quote_Field__c, mapping);
        }
        Map<String, Schema.SobjectField> opptyFieldSchema = Opportunity.SObjectType.getDescribe().fields.getMap();
        List<SobjectField> dirtyFields = new List<SObjectField>();
        for (SBQQ__Quote__c updatedQuote : quoteList) {
            Boolean changeFlag = false;
            if (updatedQuote.SBQQ__Primary__c == true) {
                Opportunity relatedOpportunity = opptyMap.get(updatedQuote.SBQQ__Opportunity2__c);
                dirtyFields.clear();
                //* 11/5/2020 Ron - (GTMS - 2064) Waterfall approach to ternary operators to make checks based on declarative updates to custom metadata
                for(String quoteField : fieldMappings.keySet()) {
                    Quote_To_Opportunity_Mapping__mdt mappingMetadata = fieldMappings.get(quoteField);
                    String oppField = mappingMetadata.Opportunity_Field__c;
                    Boolean noBypass = mappingMetadata.Bypass__c? false: true;
                    Boolean isChanged = relatedOpportunity.get(oppField) != updatedQuote.get(quoteField)? true: false;
                    Boolean nullCheck = mappingMetadata.Null_Check__c == true && isChanged? updatedQuote.get(quoteField) != null: isChanged;
                    Boolean typeCheck = mappingMetadata.Type__c != null && isChanged? mappingMetadata.Type__c == updatedQuote.Configuration_Segment__c||relatedOpportunity.Is_Webstore_Upsell_Opportunity__c : nullCheck;
                	Boolean ownerCheck = mappingMetadata.Owner_Segment__c != null && isChanged? mappingMetadata.Owner_Segment__c.contains(relatedOpportunity.Account.Segment__c) : nullCheck;
                    
                    if(isChanged && nullCheck && typeCheck && noBypass && ownerCheck){
                        relatedOpportunity.put(oppField, updatedQuote.get(quoteField));
                        changeFlag = true;
                        Schema.SobjectField theDirtyField = opptyFieldSchema.get(oppField);
                        dirtyFields.add(theDirtyField);
                    }
                }
                
                if (updatedQuote.Upsell_Amount__c != NULL && (updatedQuote.License_Term__c != NULL || updatedQuote.Custom_License_Term__c != NULL)) {
                    Decimal term = updatedQuote.License_Term__c != NULL? Decimal.valueOf(updatedQuote.License_Term__c) : updatedQuote.Custom_License_Term__c;
                    relatedOpportunity.FP_and_Upsell_ACV__c = updatedQuote.Upsell_Amount__c / (term /12) ;
                    changeFlag = true;
                    dirtyFields.add(Opportunity.FP_and_Upsell_ACV__c);
                }
                
                if (updatedQuote.SBQQ__RenewalTerm__c != NULL && updatedQuote.Renewal_Amount__c != NULL && String.isNotBlank(updatedQuote.License_Term__c)) {
                    relatedOpportunity.Renewal_ACV__c = (updatedQuote.Renewal_Amount__c  + updatedQuote.Downsell_Amount__c) / (Decimal.valueOf(updatedQuote.License_Term__c) /12);
                    //relatedOpportunity.FP_and_Upsell_ACV__c = updatedQuote.Upsell_Amount__c / (Decimal.valueOf(updatedQuote.License_Term__c) /12) ;
                    changeFlag = true;
                    //dirtyFields.add(Opportunity.Upsell_ACV__c);
                    dirtyFields.add(Opportunity.Renewal_ACV__c);
                } 
                
                if ((updatedQuote.License_Term__c != null) &&
                        (relatedOpportunity.License_Term_CPQ__c != Decimal.valueOf(updatedQuote.License_Term__c))) {
                    relatedOpportunity.License_Term_CPQ__c = Decimal.valueOf(updatedQuote.License_Term__c);
                    changeFlag = true;
                    dirtyFields.add(Opportunity.License_Term_CPQ__c);
                }
                if (updatedQuote.License_Term__c != null) {
                    Decimal licenseTerm = Decimal.valueOf(updatedQuote.License_Term__c);
                    if (relatedOpportunity.License_Term__c != licenseTerm) {
                        relatedOpportunity.License_Term__c = licenseTerm;
                        changeFlag = true;
                        dirtyFields.add(Opportunity.License_Term__c);
                    } 
                }
                /*To sync License Term Fields on Opportunity from CPQ Quote's Custom License Term - GTMS-3734 - @Gaurav Sharma Start*/
                if (updatedQuote.Custom_License_Term__c != null) {
                    if(relatedOpportunity.License_Term_CPQ__c != updatedQuote.Custom_License_Term__c){
                        relatedOpportunity.License_Term_CPQ__c = updatedQuote.Custom_License_Term__c;
                        changeFlag = true;
                        dirtyFields.add(Opportunity.License_Term_CPQ__c);
                    }
                    if(relatedOpportunity.License_Term__c != updatedQuote.Custom_License_Term__c){
                        relatedOpportunity.License_Term__c = updatedQuote.Custom_License_Term__c;
                        changeFlag = true;
                        dirtyFields.add(Opportunity.License_Term__c);
                    }
                }
                thisLogger.logTrace('Values:'+option.quoteEligibleActions+' :: '+updatedQuote.Id);
                if (option.quoteEligibleActions != null && option.quoteEligibleActions.containsKey(updatedQuote.Id)) {
                    List<String> actions = option.quoteEligibleActions.get(updatedQuote.Id).split(',');
                    for (String action : actions) {
                        if (action == 'DA') {
                            String discountApprovedStatus = updatedQuote.Discount_Approval_Required__c;
                            if (discountApprovedStatus.contains('No Approval Needed')) {
                                relatedOpportunity.Discount_Approval_Status_from_Quote__c = false;
                            } else {
                                relatedOpportunity.Discount_Approval_Status_from_Quote__c = true;
                            }
                            changeFlag = true;
                            dirtyFields.add(Opportunity.Discount_Approval_Status_from_Quote__c);
                        } else if (action == 'PA') {
                            String productApprovedStatus = updatedQuote.Product_Approval__c;
                            if (productApprovedStatus.contains('No Approval Needed')) {
                                relatedOpportunity.Product_Approval_Status_from_Quote__c = false;
                            } else {
                                relatedOpportunity.Product_Approval_Status_from_Quote__c = true;
                            }
                            changeFlag = true;
                            dirtyFields.add(Opportunity.Product_Approval_Status_from_Quote__c);
                        } else if (action == 'AD') {
                            relatedOpportunity.Approved_Discount__c = updatedQuote.Approved_Discount__c;
                            changeFlag = true;
                            dirtyFields.add(Opportunity.Approved_Discount__c);
                        } 
                    }
                }

                if(changeFlag == true) {
                    System.debug('++++relatedOpportunity> '+relatedOpportunity);
                    System.debug('++++dirtyFields> '+dirtyFields);
                    DMLWrapper.doUpdate(relatedOpportunity, dirtyFields);
                }
            }
        }
        DMLWrapper.publishDML(); 
    }
    /*
    // Below method updates quote lines from Quote DML statement
    public void updatedQuoteLines() {
        thisLogger.logTrace('Entering into updatedQuoteLines');
        DMLWrapper.intializeUnitOfWork(new List<Schema.SObjectType>{
            SBQQ__QuoteLine__c.SObjectType
        });
        Set<Id> quoteIds = new Set<Id>();
        quoteIds.addAll(recordsIds);
        Map<Id, SBQQ__QuoteLine__c> relatedQuoteLines;
        if (quoteIds.size() > 0) {
            relatedQuoteLines = new GS_SBQQQuoteLineSelector(true).checkFatalError().getQuoteLinessByQuoteId(quoteIds);
        }

        List<SObjectField> dirtyFields = new List<SObjectField>();
        // Code to stamp the changed Ship TO on line items.
        List<SBQQ__QuoteLine__c> updatedQuoteLines = new List<SBQQ__QuoteLine__c>();
        if (relatedQuoteLines != null) {
            for (SBQQ__QuoteLine__c quoteLine : relatedQuoteLines.values()) {
                Boolean changeFlag = false;
                if (quoteLine.Ship_To__c != quoteLine.SBQQ__Quote__r.Shipping_Address_NEW__c) {
                    quoteLine.Ship_To__c = quoteLine.SBQQ__Quote__r.Shipping_Address_NEW__c;
                    changeFlag = true;
                    dirtyFields.add(SBQQ__QuoteLine__c.Ship_To__c);
                }
                if(quoteLine.Ship_From_Location__c  != quoteLine.SBQQ__Quote__r.Ship_From_Location__c ){
                    quoteLine.Ship_From_Location__c = quoteLine.SBQQ__Quote__r.Ship_From_Location__c ;
                    changeFlag = true;
                    dirtyFields.add(SBQQ__QuoteLine__c.Ship_From_Location__c);
                }
                if(changeFlag == true) {
                    //updatedQuoteLines.add(quoteLine);
                    DMLWrapper.doUpdate(quoteLine, dirtyFields);
                }
            } 
        }
        if (!Test.isRunningTest()) {
            DMLWrapper.publishDML();
        }
    }*/

    public class Options {
        public String Operation {get; set;}
        public Map<String, String> quoteEligibleActions; // Eligible actions comma separated
        
        public Options(String operation){
            this.Operation = operation;
        }

        public Options(String operation, Map<String, String> quoteEligibleActions){
            this.Operation = operation;
            this.quoteEligibleActions = quoteEligibleActions;
        }
    }
}