force-app/main/default/objects/Channel_Relationship__c/Channel_Relationship__c.object-meta.xml
<CustomObject>
    <description>Used to related channel partners with opportunities (and vice versa).</description>
    <label>Channel Relationship</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Channel Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Channel Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel_Relationship__c/fields/Channel_Partner_User_lr__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner_User_lr__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Partner User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Channel_Relationships1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Channel_Relationship__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Channel Relationships</relationshipLabel>
    <relationshipName>Channel_Relationships</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/ChannelRltionShipPtnrSharingServiceTest.cls
/**
 * Created by vikasmishra on 2021-07-06.
 */

@IsTest
private class ChannelRltionShipPtnrSharingServiceTest {
    @IsTest
    static void shouldRunSharingForOpportunity() {
        OpportunityTeamMemberServiceMock thisOTMS = new OpportunityTeamMemberServiceMock();
        OpportunityTeamSelectorMock thisOpportunityTeamSelectorMock = new OpportunityTeamSelectorMock();
        ChannelRelationShipPartnerSharingService.thisOTMService = thisOTMS;
        ChannelRelationShipPartnerSharingService.thisOTMSelector = thisOpportunityTeamSelectorMock;
        ChannelRelationShipPartnerSharingService thisService = new  ChannelRelationShipPartnerSharingService();
        thisService.runPartnerSharingForOpportunity(
                new Map<Id, Channel_Relationship__c>{
                        generateId(Channel_Relationship__c.SObjectType, 101) =>
                                new Channel_Relationship__c(
                                        Id = generateId(Channel_Relationship__c.SObjectType, 101),
                                        Opportunity__c = generateId(Opportunity.SObjectType, 101),
                                        Channel_Partner_User_lr__c = generateId(User.SObjectType, 101)
                                )

                },
                new Map<Id, Channel_Relationship__c>()
        );
        System.assert(thisOTMS.methodCalled, 'Should call sharing ');
    }

    @IsTest
    static void shouldRunSharingForOpportunityDelete() {
        OpportunityTeamMemberServiceMock thisOTMS = new OpportunityTeamMemberServiceMock();
        OpportunityTeamSelectorMock thisOpportunityTeamSelectorMock = new OpportunityTeamSelectorMock();
        ChannelRelationShipPartnerSharingService.thisOTMService = thisOTMS;
        ChannelRelationShipPartnerSharingService.thisOTMSelector = thisOpportunityTeamSelectorMock;
        ChannelRelationShipPartnerSharingService thisService = new  ChannelRelationShipPartnerSharingService();
        thisService.runPartnerSharingForOpportunity(
                new Map<Id, Channel_Relationship__c>(),
                new Map<Id, Channel_Relationship__c>{
                        generateId(Channel_Relationship__c.SObjectType, 101) =>
                                new Channel_Relationship__c(
                                        Id = generateId(Channel_Relationship__c.SObjectType, 101),
                                        Opportunity__c = generateId(Opportunity.SObjectType, 101),
                                        Channel_Partner_User_lr__c = generateId(User.SObjectType, 101)
                                )

                }
        );
        System.assert(thisOTMS.methodCalled, 'Should call sharing ');
        System.assert(thisOpportunityTeamSelectorMock.methodCalled, 'Should call Selector ');
    }

    public class OpportunityTeamMemberServiceMock  implements OpportunityTeamMemberService.IService{
        public Boolean methodCalled = false;
        public void runSharingForChannelRelation(OpportunityTeamMemberService.ShareByChannelRelation shareData){
            methodCalled = true;
        }
    }

    public class OpportunityTeamSelectorMock implements OpportunityTeamMemberService.ISelector{
        public Boolean methodCalled = false;
        public List<OpportunityTeamMember> getOpportunityTeamMembersByOppIdAndUserIds(Set<Id> opportunityIds, Set<Id> userIds) {
            methodCalled = true;
            return new List<OpportunityTeamMember>{
                    new OpportunityTeamMember(
                            Id = generateId(OpportunityTeamMember.SObjectType, 101),
                            OpportunityId = generateId(Opportunity.SObjectType, 101),
                            UserId = generateId(User.SObjectType, 101),
                            TeamMemberRole = OpportunityTeamMemberService.CHANNEL_PARTNER_ROLE_CONSTANT
                    )
            };
        }
    }

    public static Id generateId(SObjectType sobjectType, Integer sequenceNum) {
        String keyPrefix = sobjectType.getDescribe().getKeyPrefix();
        return Id.valueOf(keyPrefix + String.valueOf(sequenceNum).leftPad(12, '0'));
    }
}