force-app/main/default/objects/Finance_Partner_Quote__c/Finance_Partner_Quote__c.object-meta.xml
<CustomObject>
    <label>Finance Partner Quote</label>
    <nameField>
        <displayFormat>FPQ-{00000}</displayFormat>
        <label>FPQ Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Finance Partner Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Finance_Partner_Quote__c/fields/Documents_Uploaded__c.field-meta.xml
<CustomField>
    <fullName>Documents_Uploaded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Documents Uploaded By Customer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Finance_Partner_Quote__c/fields/Financing_Decision__c.field-meta.xml
<CustomField>
    <fullName>Financing_Decision__c</fullName>
    <label>Financing Decision</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Need More Info</fullName>
            </value>
            <value>
                <fullName>Pending - Under Partner Review</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Resubmit For Review</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FPQFileUpload.cls
public without sharing class FPQFileUpload {
    @AuraEnabled
    public static Boolean checkAlreadyUploaded(Id parentId){
        Finance_Partner_Quote__c fpq = new Finance_Partner_Quote__c();
        fpq = [Select Id,Documents_Uploaded__c from Finance_Partner_Quote__c where Id =: parentId limit 1];
        if(fpq.Documents_Uploaded__c == true){
            return true;
        }
        else{
            return false;
        }
    }
    
   @AuraEnabled
    public static Id saveFile(Id parentId, String fileName, String base64Data, String contentType, String fileId) {
        // check if fileId id ''(Always blank in first chunk), then call the saveTheFile method,
        //  which is save the check data and return the attachemnt Id after insert,
        //  next time (in else) we are call the appentTOFile() method
        //   for update the attachment with remains chunks
        if (fileId == '') {
            fileId = saveTheFile(parentId, fileName, base64Data, contentType);
        } else {
            appendToFile(fileId, base64Data);
        }
         Finance_Partner_Quote__c fpq = new Finance_Partner_Quote__c();
        fpq = [Select Id,Documents_Uploaded__c from Finance_Partner_Quote__c where Id =: parentId limit 1];
        fpq.Documents_Uploaded__c = true;
        fpq.Financing_Decision__c = 'Pending - Under Partner Review';
        update fpq;
        return Id.valueOf(fileId);
    }
    
    public static Id saveTheFile(Id parentId, String fileName, String base64Data, String contentType) {
        base64Data = EncodingUtil.urlDecode(base64Data, 'UTF-8');
        
        Attachment oAttachment = new Attachment();
        oAttachment.parentId = parentId;
        
        oAttachment.Body = EncodingUtil.base64Decode(base64Data);
        oAttachment.Name = fileName;
        oAttachment.ContentType = contentType;
        
        insert oAttachment;        
        return oAttachment.Id;
    }
    
    @testVisible
    private static void appendToFile(Id fileId, String base64Data) {
        base64Data = EncodingUtil.urlDecode(base64Data, 'UTF-8');        
        Attachment a = [
            SELECT Id, Body
            FROM Attachment
            WHERE Id = : fileId
        ];
        
        String existingBody = EncodingUtil.base64Encode(a.Body);        
        a.Body = EncodingUtil.base64Decode(existingBody + base64Data);        
        update a;
    }
}