force-app/main/default/objects/New_Product_Addition__c/New_Product_Addition__c.object-meta.xml
<CustomObject>
    <label>New Product Addition</label>
    <nameField>
        <displayFormat>NPA-{0000}</displayFormat>
        <label>New Product Addition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>New Product Additions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/New_Product_Addition__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/New_Product_Addition__c/fields/Dimensions_cm3__c.field-meta.xml
<CustomField>
    <fullName>Dimensions_cm3__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Dimensions (cm3)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/New_Product_Addition__c/fields/Geo_Availability__c.field-meta.xml
<CustomField>
    <fullName>Geo_Availability__c</fullName>
    <label>Geo Availability</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>USA</fullName>
            </value>
            <value>
                <fullName>Mexico</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/New_Product_Addition__c/fields/Lauched_EA_Date__c.field-meta.xml
<CustomField>
    <fullName>Lauched_EA_Date__c</fullName>
    <label>Lauched EA Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/New_Product_Addition__c/fields/Launched_GA_Date__c.field-meta.xml
<CustomField>
    <fullName>Launched_GA_Date__c</fullName>
    <label>Launched GA Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/New_Product_Addition__c/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <label>Product SKU</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/New_Product_Addition__c/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <label>Product Family</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Safety</fullName>
            </value>
            <value>
                <fullName>Asset</fullName>
            </value>
            <value>
                <fullName>Telematics</fullName>
            </value>
            <value>
                <fullName>Connected Sites</fullName>
            </value>
            <value>
                <fullName>Connected Worker</fullName>
                <isActive>false</isActive>
                <label>Connected Worker</label>
            </value>
            <value>
                <fullName>Core Fleet</fullName>
                <isActive>false</isActive>
                <label>Core Fleet</label>
            </value>
            <value>
                <fullName>Family</fullName>
                <isActive>false</isActive>
                <label>Family</label>
            </value>
            <value>
                <fullName>Industrial 4.0</fullName>
                <isActive>false</isActive>
                <label>Industrial 4.0</label>
            </value>
            <value>
                <fullName>Machine Vision</fullName>
                <isActive>false</isActive>
                <label>Machine Vision</label>
            </value>
            <value>
                <fullName>Samsara Brand</fullName>
                <isActive>false</isActive>
                <label>Samsara Brand</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/New_Product_Addition__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <label>Product Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/New_Product_Addition__c/fields/Segment_Availability__c.field-meta.xml
<CustomField>
    <fullName>Segment_Availability__c</fullName>
    <label>Segment Availability</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fleet</fullName>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
            <value>
                <fullName>Connected Worker</fullName>
            </value>
            <value>
                <fullName>Sales Ops Profile</fullName>
            </value>
            <value>
                <fullName>All</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/New_Product_Addition__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Product Initiated</fullName>
                <default>true</default>
                <label>Product Initiated</label>
            </value>
            <value>
                <fullName>Back Office Processing</fullName>
            </value>
            <value>
                <fullName>Ready to Approve</fullName>
            </value>
            <value>
                <fullName>Pending Product Ops Review</fullName>
            </value>
            <value>
                <fullName>Pending Finance Approval</fullName>
                <label>Pending Biz Systems - Finance Approval</label>
            </value>
            <value>
                <fullName>Pending NPI Approval</fullName>
            </value>
            <value>
                <fullName>Pending Supply Chain Approval</fullName>
            </value>
            <value>
                <fullName>Pending Product Approval</fullName>
            </value>
            <value>
                <fullName>Product Creation</fullName>
            </value>
            <value>
                <fullName>Ready to Launch</fullName>
            </value>
            <value>
                <fullName>Launched EA</fullName>
            </value>
            <value>
                <fullName>Launched GA</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Pending Sales Ops Approval</fullName>
            </value>
            <value>
                <fullName>Finance Processing</fullName>
                <isActive>false</isActive>
                <label>Finance Processing</label>
            </value>
            <value>
                <fullName>NPI Processing</fullName>
                <isActive>false</isActive>
                <label>NPI Processing</label>
            </value>
            <value>
                <fullName>Supply Chain Processing</fullName>
                <isActive>false</isActive>
                <label>Supply Chain Processing</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/New_Product_Addition__c/fields/Sub_Family__c.field-meta.xml
<CustomField>
    <fullName>Sub_Family__c</fullName>
    <label>Sub-Family</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Samsara Brand</fullName>
            </value>
            <value>
                <fullName>Connected Equipment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/New_Product_Addition__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>SKU Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hardware</fullName>
            </value>
            <value>
                <fullName>Accessory</fullName>
            </value>
            <value>
                <fullName>Cable</fullName>
            </value>
            <value>
                <fullName>License</fullName>
            </value>
            <value>
                <fullName>Service Fee</fullName>
            </value>
            <value>
                <fullName>Kit/Package</fullName>
                <isActive>false</isActive>
                <label>Kit/Package</label>
            </value>
            <value>
                <fullName>Serialized Hardware</fullName>
                <isActive>false</isActive>
                <label>Serialized Hardware</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/New_Product_Addition__c/fields/Weight_oz__c.field-meta.xml
<CustomField>
    <fullName>Weight_oz__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Weight (oz)</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/New_Product_Addition__c.field-meta.xml
<CustomField>
    <fullName>New_Product_Addition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Product Addition</label>
    <referenceTo>New_Product_Addition__c</referenceTo>
    <relationshipLabel>Price Book Entries</relationshipLabel>
    <relationshipName>Price_Book_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Dimensions_cm3__c.field-meta.xml
<CustomField>
    <fullName>Dimensions_cm3__c</fullName>
    <description>Dimensions of product cm3</description>
    <label>Dimensions cm3</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Geo_Availablity__c.field-meta.xml
<CustomField>
    <fullName>Geo_Availablity__c</fullName>
    <label>Geo Availablity</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USA</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>All</fullName>
                <default>true</default>
                <label>All</label>
            </value>
            <value>
                <fullName>Mexico</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/New_Product_Addition__c.field-meta.xml
<CustomField>
    <fullName>New_Product_Addition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Product Addition</label>
    <referenceTo>New_Product_Addition__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accessory</fullName>
            </value>
            <value>
                <fullName>Serialized Hardware</fullName>
            </value>
            <value>
                <fullName>License Subscription</fullName>
            </value>
            <value>
                <fullName>Service Fee</fullName>
            </value>
            <value>
                <fullName>Bundle</fullName>
            </value>
            <value>
                <fullName>Cable</fullName>
            </value>
            <value>
                <fullName>Promotional Product</fullName>
            </value>
            <value>
                <fullName>Hardware</fullName>
            </value>
            <value>
                <fullName>License</fullName>
            </value>
            <value>
                <fullName>Professional Services</fullName>
            </value>
            <value>
                <fullName>Samsara Beyond</fullName>
            </value>
            <value>
                <fullName>Deal Component</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Segment_Availability__c.field-meta.xml
<CustomField>
    <fullName>Segment_Availability__c</fullName>
    <label>Segment Availability</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fleet</fullName>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
            <value>
                <fullName>Connected Worker</fullName>
            </value>
            <value>
                <fullName>All</fullName>
                <default>true</default>
                <label>All</label>
            </value>
            <value>
                <fullName>Sales Ops Profile</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Sub_Family__c.field-meta.xml
<CustomField>
    <fullName>Sub_Family__c</fullName>
    <description>Used to categorize products within a Product Family</description>
    <label>Sub-Family</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Samsara Brand</fullName>
            </value>
            <value>
                <fullName>Connected Equipment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Weight_oz__c.field-meta.xml
<CustomField>
    <fullName>Weight_oz__c</fullName>
    <description>Product weight in oz</description>
    <label>Weight (oz)</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/NewProductAdditionHelper.cls
/*
 * 04/06/20 Tommy - (GTMS-736): Added Product Short Name and Readable Name to fields to copy to Product2 record upon creation
 * 02/25/21 Gaurav Sharma - (GTMS-2854): Added New_Product_Addition__c record to Product related list
 * 04/30/21 Lavanya - (GTMS-1396): Added code to insert Price Book Entry records for the newly created products
  * 08/35/21 Anil - (GTMS-4028): Remove manual steps for PM on SKU Creation approval workflow
 */
public class NewProductAdditionHelper {
  
    private static Map<Id, New_Product_Addition__c> oldNPAS;
    private static Map<Id, New_Product_Addition__c> newNPAS;
    
    
    public static void ProductCreator(
        Map<Id, New_Product_Addition__c> oldTriggerNPAS,
        Map<Id, New_Product_Addition__c> newTriggerNPAS){
            oldNPAS = oldTriggerNPAS;
            newNPAS = newTriggerNPAS;
            system.debug('ProductCreator initiated');
            createNewProducts();

    }

    
    public static void createNewProducts(){
        List<Product2> prodsToInsert = new List<Product2>();
        List<New_Product_Addition__c> prodsAddedToInsert = new List<New_Product_Addition__c>();
        Map<String,New_Product_Addition__c> newProdsAdded=new Map<String,New_Product_Addition__c>();
        List<PricebookEntry> priceBookEntryList = new List<PricebookEntry>();
        
        for (New_Product_Addition__c npa : newNPAS.values()){
            New_Product_Addition__c oldNPA = oldNPAS.get(npa.Id);
            if (oldNPA.Status__c != npa.Status__c && npa.Status__c == 'Launched EA') {
                npa.Lauched_EA_Date__c = system.now();
            }
            if (oldNPA.Status__c != npa.Status__c && npa.Status__c == 'Launched GA') {
                npa.Launched_GA_Date__c = system.now();
            }
            system.debug('Old ID is: ' + oldNPA.Id);
            if (oldNPA.Id != NULL){
                boolean alreadyCreated = oldNPA.Status__c == 'Product Creation';
                system.debug('About to create product');
                if (!alreadyCreated && npa.Status__c.equals('Product Creation')){
                    Product2 newProd                = new Product2();
                    newProd.Name                    = npa.Product_Name__c;
                    newProd.ProductCode             = npa.Product_Code__c;
                    newProd.Description             = npa.Description__c;
                    newProd.Family                  = npa.Product_Family__c;
                    newProd.Sub_Family__c           = npa.Sub_Family__c;                    
                    newProd.Product_Type__c         = npa.Type__c;
                    newProd.Weight_oz__c            = npa.Weight_oz__c;
                    newProd.Dimensions_cm3__c       = npa.Dimensions_cm3__c;
                    newProd.Geo_Availablity__c      = npa.Geo_Availability__c;
                    newProd.Segment_Availability__c = npa.Segment_Availability__c;
                    newProd.Sales_Segment__c        = npa.Sales_Segment__c;
                    
                    //newProd.Readable_Name__c        = npa.Readable_Name__c;
                    //newProd.Product_Short_Name__c   = npa.Product_Short_Name__c;
                    newProd.New_Product_Addition__c = npa.Id;
                    
                    //create a map here between npa and product getting inserted
                    newProdsAdded.put(newProd.Name,npa);                    
                    system.debug('Prod created');
                    
                    prodsToInsert.add(newProd);
                }
            }
            
            if(prodsToInsert.size() > 0){
                insert prodsToInsert;
            }
            List<String> pbookNames = Label.Price_Books_for_NPA.Split(',');
            //Query the price books
            List<Pricebook2> priceBookList = [Select Id,Name from Pricebook2 where name in :pbookNames];
            
            if(prodsToInsert.size() > 0){
                for(Product2 prod:prodsToInsert){
                    New_Product_Addition__c npa2 = newProdsAdded.get(prod.Name);
                    
                    npa2.Product2__c = prod.Id;
                    prodsAddedToInsert.add(npa2);
                    
                    for(Pricebook2 pb: priceBookList){
                        if(npa2.Standard_Price_CAD__c != null){
                            priceBookEntryList.add(createPBE(prod,pb,'CAD',npa2.Standard_Price_CAD__c));
                        }
                        if(npa2.Standard_Price_CHF__c != null){
                            priceBookEntryList.add(createPBE(prod,pb,'CHF',npa2.Standard_Price_CHF__c));
                        }
                        if(npa2.Standard_Price_EUR__c != null){
                            priceBookEntryList.add(createPBE(prod,pb,'EUR',npa2.Standard_Price_EUR__c));
                        }
                        if(npa2.Standard_Price_GBP__c != null){
                            priceBookEntryList.add(createPBE(prod,pb,'GBP',npa2.Standard_Price_GBP__c));
                        }
                        if(npa2.Standard_Price_MXN__c != null){
                            priceBookEntryList.add(createPBE(prod,pb,'MXN',npa2.Standard_Price_MXN__c));
                        }
                        if(npa2.Standard_Price_USD__c != null){
                            priceBookEntryList.add(createPBE(prod,pb,'USD',npa2.Standard_Price_USD__c));
                        } 
                    }
                }
            }
            
            if(!priceBookEntryList.isEmpty()){
                insert priceBookEntryList;
            }
            //perform the iteration on prodsToInsert
            //npa.Product__c = newProd.Id;
            
            
            
             system.debug('There were '+ prodsToInsert.size() + ' products created.');
        }
    }
    
    public static PricebookEntry createPBE(Product2 prod, PriceBook2 pb,String currencyCode,Decimal unitPrice){
        PricebookEntry pbe = new PricebookEntry();
        pbe.Product2Id = prod.Id;
        pbe.Pricebook2Id = pb.Id;
        pbe.UnitPrice = unitPrice;
        pbe.CurrencyIsoCode = currencyCode;
        pbe.IsActive = true;
        return pbe;
    }

// Below Medod to update stage - Anil Bogadi
     public static void updateStage(Map<Id, New_Product_Addition__c> oldTriggerNPAS,
        Map<Id, New_Product_Addition__c> newTriggerNPAS){
           List<New_Product_Addition__c> newNPASList = new List<New_Product_Addition__c>(); 
            for (New_Product_Addition__c npa : newTriggerNPAS.values()){
                if(((npa.Weight_oz__c != null && npa.Dimensions_cm3__c != null && npa.BOM_Cost__c != null && npa.Lead_Time__c != null  && 
                     npa.Revenue_Recognition_Type__c != null && npa.Type__c == 'Hardware') ||
                    (npa.Revenue_Recognition_Type__c != null && npa.Type__c == 'Accessory') ||
                    (npa.Revenue_Recognition_Type__c != null && npa.Type__c == 'Cable') ||
                    (npa.Revenue_Recognition_Type__c != null && npa.Type__c == 'License') ||
                    (npa.Revenue_Recognition_Type__c != null && npa.Type__c == 'Service Fee')) &&
                     npa.Status__c == 'Back Office Processing' )  {
                  New_Product_Addition__c newProductAddition = new New_Product_Addition__c();
                    newProductAddition.Id = npa.Id;    
                    newProductAddition.Status__c = 'Ready to Approve';
                    newNPASList.add(newProductAddition);    
                }    
            }
            if(newNPASList.size() > 0){
              update newNPASList; 
               
              OrgWideEmailAddress owa = [Select Id from OrgWideEmailAddress Where Address = 'no-reply@samsara.com'];
              New_Product_Addition__c  ToAddressesEmail = [Select Id,Product_Owner_Manager__r.email from New_Product_Addition__c Where id =: newNPASList[0].Id];
              Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
              message.setOrgWideEmailAddressId(owa.Id);
              message.setToAddresses(new String[]{ToAddressesEmail.Product_Owner_Manager__r.email});// Product_Owner_Manager__c.Email
              //message.setToAddresses(new String[]{'anilkumar.bogadi@gmail.com'});
              message.subject = '[Action Requested] - Submit NPA for Approval';
              String intro = 'Hello, A new product has been moved to the Ready to Approve stage. Please go into the New Product Addition record and click the “Submit for Approval” button to initiate the approval workflow.';
              String email = intro+'\n https://samsara--uat.lightning.force.com/'+ToAddressesEmail.Id;
              message.plainTextBody = email;
              Messaging.SingleEmailMessage[] messages =   new List<Messaging.SingleEmailMessage> {message};
              Messaging.SendEmailResult[] results = Messaging.sendEmail(messages);
              if (results[0].success) {
             System.debug('The email was sent successfully.');
             } else {
           System.debug('The email failed to send: ' + results[0].errors[0].message);
}  
            }
            
    }
}