force-app/main/default/objects/Async_Request__c/Async_Request__c.object-meta.xml
<CustomObject>
    <description>Use to queue up an Asynchronous Request for processing</description>
    <label>Async Request</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Async Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Async Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Async_Request__c/fields/Options__c.field-meta.xml
<CustomField>
    <fullName>Options__c</fullName>
    <description>Additional Options that can be used when processing the request</description>
    <label>Options</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Async_Request__c/fields/Params__c.field-meta.xml
<CustomField>
    <fullName>Params__c</fullName>
    <label>Params</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Resend_Return_Email__c.field-meta.xml
<CustomField>
    <fullName>Resend_Return_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Triggers the return email to resend.</description>
    <label>Resend Return Email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Return_Label_Attachment__c.field-meta.xml
<CustomField>
    <fullName>Return_Label_Attachment__c</fullName>
    <description>Attachment ID of Return Label</description>
    <label>Return Label Attachment</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Shipping_Address_NEW__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Address_NEW__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Shipping Addresses should not include a PO Box.</inlineHelpText>
    <label>Shipping Address</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Shipping_Address__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Shipping_Address__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Shipping_Country__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Country__c</fullName>
    <label>Shipping Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Aland Islands</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia, Plurinational State of</fullName>
            </value>
            <value>
                <fullName>Bonaire, Sint Eustatius and Saba</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Bouvet Island</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Tracking_Number__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Number__c</fullName>
    <label>Tracking Number</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Trial.recordType-meta.xml
<RecordType>
    <fullName>Trial</fullName>
    <active>true</active>
    <businessProcess>Standard Opportunities</businessProcess>
    <label>Trial</label>
</RecordType>

force-app/main/default/classes/GS_OpportunitySendEmailAsync.cls
public with sharing class GS_OpportunitySendEmailAsync extends BaseAsyncHandler{
    public SamsaraLoggerService thisSamsaraLoggerService = new SamsaraLoggerService();

    public override String getRequestType(){
        return 'OpportunitySendEmailAsync Async Job';
    }

    List<Id> recordsIds;
    List<Opportunity> opptyList;
    public GS_OpportunityCacheService oppCache = new GS_OpportunityCacheService();
    public override void execute(Async_Request__c ar){

        recordsIds = ar.Params__c.split(PARAMETERS_SPLITTER);
        if(recordsIds.isEmpty()) return;
        Options opt = (Options) JSON.deserialize(ar.Options__c, Options.class);
        try{
            thisSamsaraLoggerService.logger.logTrace('Entering in GS_OpportunitySendEmailAsync');   
            switch on opt.Operation {
                when 'SEND_RETURN_EMAIL_OPERATIONS' {	
                    this.loadOpportunities(recordsIds);
                    this.sendReturnEmails();
                }
            }
        }catch(Exception ex){
            thisSamsaraLoggerService.logger.logError('Error in GS_OpportunitySendEmailAsync::', new SamsaraLoggerObjectMVP(
                ex, recordsIds
        ));
            throw ex;
        }
        finally {
            thisSamsaraLoggerService.logger.logTrace('Exiting in GS_OpportunitySendEmailAsync');
            thisSamsaraLoggerService.logger.dispatch();
        }
    }

    private void loadOpportunities(List<Id> idList){
        if (opptyList == null){
            this.opptyList = (new GS_OpportunitySelector(false)).loadOpportunityWithItems(new Set<Id>(idList));
        }
    }
    
    private void sendReturnEmails(){
        Map<Id, Opportunity> returnOpptysToEmail = new Map<Id, Opportunity>();

        for (Opportunity newOpp : this.opptyList) {
            returnOpptysToEmail.put(newOpp.Id, newOpp);
        }

        if (!returnOpptysToEmail.isEmpty()) {
            ReturnLabelEmailer.sendReturnEmails(returnOpptysToEmail);
        }
    } 


    public void sendReturnLabelEmail(Map<Id, Opportunity> oldOppMap, List<Opportunity> newOpportunityList) {
        // Could be modified to a process builder
        Set<Id> opptyIdsSet = new Set<Id>();
        for (Opportunity newOppty : newOpportunityList) {
            if (newOppty.type == 'Free Trial Return' || newOppty.type == 'Exchange' || newOppty.type == 'Remorse Refund'|| newOppty.type == 'Warranty Exchange') {
                if (newOppty.Return_Label_Attachment__c != null && ((!System.Label.Commercial_Invoice_Inernational_Shipment.contains(newOppty.Shipping_Country__c) && (newOppty.StageName != oldOppMap.get(newOppty.Id).StageName && newOppty.StageName == 'Return Label Sent')) 
                    || (System.Label.Commercial_Invoice_Inernational_Shipment.contains(newOppty.Shipping_Country__c) && newOppty.Return_Label_Attachment__c != oldOppMap.get(newOppty.Id).Return_Label_Attachment__c 
                        && newOppty.Return_Label_Attachment__c.contains(',') && newOppty.StageName == 'Return Label Sent')
                    || (newOppty.Resend_Return_Email__c != oldOppMap.get(newOppty.Id).Resend_Return_Email__c && newOppty.Resend_Return_Email__c))) {
                    if (newOppty.Tracking_Number__c != NULL && newOppty.Shipping_Address_NEW__c != NULL) {
                        opptyIdsSet.add(newOppty.Id);                        
                    }
                }
            }
        }
        if (!opptyIdsSet.isEmpty()) {
            DMLWrapper.doInsert(new GS_OpportunitySendEmailAsync().prepareAsyncRequests(
                JSON.serialize(new GS_OpportunitySendEmailAsync.Options('SEND_RETURN_EMAIL_OPERATIONS')),
                opptyIdsSet
            )); 
        }
    }

    public class Options {
        public String Operation {get; set;}

        public Options(String operation){
            this.Operation = operation;
        }
        
    }
}