force-app/main/default/objects/Async_Request__c/Async_Request__c.object-meta.xml
<CustomObject>
    <description>Use to queue up an Asynchronous Request for processing</description>
    <label>Async Request</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Async Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Async Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Async_Request__c/fields/Params__c.field-meta.xml
<CustomField>
    <fullName>Params__c</fullName>
    <label>Params</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Express_Annual_Discount__c.field-meta.xml
<CustomField>
    <fullName>Express_Annual_Discount__c</fullName>
    <defaultValue>0.0</defaultValue>
    <label>Annual Discount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Express_Selected_Discount__c.field-meta.xml
<CustomField>
    <fullName>Express_Selected_Discount__c</fullName>
    <defaultValue>0.0</defaultValue>
    <description>Discount manually selected by reps on express deals (non-automatic, such as the one that gets stamped for annual payments).</description>
    <label>Express Selected Discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Express_Upfront_Discount__c.field-meta.xml
<CustomField>
    <fullName>Express_Upfront_Discount__c</fullName>
    <defaultValue>0.0</defaultValue>
    <label>Upfront Discount</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Hold_Reason__c.field-meta.xml
<CustomField>
    <fullName>Hold_Reason__c</fullName>
    <description>GTMS -38 Update the Sales Error drop down button</description>
    <label>Hold Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Incorrect Quantities</fullName>
            </value>
            <value>
                <fullName>Missing / Wrong Shipping Address</fullName>
            </value>
            <value>
                <fullName>No PM approval</fullName>
            </value>
            <value>
                <fullName>Out of stock</fullName>
            </value>
            <value>
                <fullName>Confirming FT</fullName>
            </value>
            <value>
                <fullName>Inventory Hold</fullName>
            </value>
            <value>
                <fullName>Clarification Hold</fullName>
            </value>
            <value>
                <fullName>Requested Later Ship Date</fullName>
            </value>
            <value>
                <fullName>Special Shipping Request Hold</fullName>
            </value>
            <value>
                <fullName>Partial Shipment</fullName>
            </value>
            <value>
                <fullName>RFO Notes</fullName>
            </value>
            <value>
                <fullName>Return Kickback: Promo - RTS</fullName>
            </value>
            <value>
                <fullName>Free Trial - RTS</fullName>
            </value>
            <value>
                <fullName>Revenue - RTS</fullName>
            </value>
            <value>
                <fullName>Partial Remorse Refund</fullName>
            </value>
            <value>
                <fullName>Unplanned Return</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/License_Term__c.field-meta.xml
<CustomField>
    <fullName>License_Term__c</fullName>
    <defaultValue>36</defaultValue>
    <description>The license term of the opportunity.</description>
    <label>License Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/of_Accessories__c.field-meta.xml
<CustomField>
    <fullName>of_Accessories__c</fullName>
    <description>Sum of Accessories</description>
    <label># of Accessories</label>
    <summarizedField>OpportunityLineItem.Quantity</summarizedField>
    <summaryFilterItems>
        <field>OpportunityLineItem.Product_Code_Copy__c</field>
        <operation>startsWith</operation>
        <value>&quot;ACC-&quot;, &quot;CBL&quot;, &quot;ELOG&quot;, &quot;SHRT&quot;, &quot;WELCOME&quot;,  &quot;EXPRESS-WELCOME&quot;, &quot;FREE-TRIAL&quot;</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>OpportunityLineItem.Product_Code_Copy__c</field>
        <operation>notEqual</operation>
        <value>ACC-DRIVERID</value>
    </summaryFilterItems>
    <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/of_HW_Products__c.field-meta.xml
<CustomField>
    <fullName>of_HW_Products__c</fullName>
    <label># of HW Products</label>
    <summarizedField>OpportunityLineItem.Quantity</summarizedField>
    <summaryFilterItems>
        <field>OpportunityLineItem.Product_Code_Copy__c</field>
        <operation>contains</operation>
        <value>&quot;HW-&quot;,&quot;ACC-DRIVERID&quot;</value>
    </summaryFilterItems>
    <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Order_Ops_Notes__c.field-meta.xml
<CustomField>
    <fullName>Order_Ops_Notes__c</fullName>
    <description>Area for Order Ops to add notes for shipping delays, cut off times, etc.</description>
    <label>Order Ops Notes</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Selected_Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Selected_Payment_Type__c</fullName>
    <inlineHelpText>This dropdown list is populated based on what your customer has been approved for in Internal Financing. If you do not see a finance option then your customer has not been approved for that option.</inlineHelpText>
    <label>Selected Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Direct Monthly</fullName>
            </value>
            <value>
                <fullName>Direct Annual</fullName>
            </value>
            <value>
                <fullName>Upfront Payments</fullName>
            </value>
            <value>
                <fullName>Direct Semi-Annual</fullName>
            </value>
            <value>
                <fullName>Direct Quarterly</fullName>
            </value>
            <value>
                <fullName>Net-30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Ship_From_Location__c.field-meta.xml
<CustomField>
    <fullName>Ship_From_Location__c</fullName>
    <label>Ship From Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Samsara HQ</fullName>
            </value>
            <value>
                <fullName>DCL</fullName>
            </value>
            <value>
                <fullName>Samsara UK</fullName>
            </value>
            <value>
                <fullName>Free Trial</fullName>
            </value>
            <value>
                <fullName>VCK</fullName>
            </value>
            <value>
                <fullName>DCL-KY</fullName>
            </value>
            <value>
                <fullName>MX Free Trial</fullName>
            </value>
            <value>
                <fullName>MX-Intransit</fullName>
            </value>
            <value>
                <fullName>Estafeta</fullName>
            </value>
            <value>
                <fullName>DCL-LA</fullName>
                <default>true</default>
                <label>DCL-LA</label>
            </value>
            <value>
                <fullName>Free Trial EU</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
            </value>
            <value>
                <fullName>ON-Logistics</fullName>
            </value>
            <value>
                <fullName>OEM-Fontaine</fullName>
            </value>
            <value>
                <fullName>OEM-Freightliner-CTS</fullName>
            </value>
            <value>
                <fullName>DHL</fullName>
            </value>
            <value>
                <fullName>Work Order</fullName>
                <isActive>false</isActive>
                <label>Work Order</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Shipping_Address_NEW__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Address_NEW__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Shipping Addresses should not include a PO Box.</inlineHelpText>
    <label>Shipping Address</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Shipping_Address__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Shipping_Address__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Shipping_Method__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Method__c</fullName>
    <label>Shipping Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Will Call</fullName>
            </value>
            <value>
                <fullName>UK Standard</fullName>
            </value>
            <value>
                <fullName>UK Express</fullName>
            </value>
            <value>
                <fullName>3 Day Select</fullName>
            </value>
            <value>
                <fullName>Ground</fullName>
                <default>true</default>
                <label>Ground</label>
            </value>
            <value>
                <fullName>Next Day Air</fullName>
            </value>
            <value>
                <fullName>Worldwide Expedited</fullName>
            </value>
            <value>
                <fullName>ECONOMY</fullName>
            </value>
            <value>
                <fullName>Fedex Freight Economy</fullName>
            </value>
            <value>
                <fullName>International Priority</fullName>
            </value>
            <value>
                <fullName>International Economy</fullName>
            </value>
            <value>
                <fullName>Ground - Mexico</fullName>
            </value>
            <value>
                <fullName>MX Standard</fullName>
            </value>
            <value>
                <fullName>MX Express</fullName>
            </value>
            <value>
                <fullName>MX LTL</fullName>
            </value>
            <value>
                <fullName>NEXT DAY AIR RS</fullName>
            </value>
            <value>
                <fullName>GROUND RS</fullName>
            </value>
            <value>
                <fullName>3 DAY SELECT RS</fullName>
            </value>
            <value>
                <fullName>UPS 3 Day Select</fullName>
                <isActive>false</isActive>
                <label>UPS 3 Day Select</label>
            </value>
            <value>
                <fullName>UPS Ground</fullName>
                <isActive>false</isActive>
                <label>UPS Ground</label>
            </value>
            <value>
                <fullName>UPS Next Day Air</fullName>
                <isActive>false</isActive>
                <label>UPS Next Day Air</label>
            </value>
            <value>
                <fullName>UPS Worldwide Expedited</fullName>
                <isActive>false</isActive>
                <label>UPS Worldwide Expedited</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Total_License_Due__c.field-meta.xml
<CustomField>
    <fullName>Total_License_Due__c</fullName>
    <label>Total License Due</label>
    <summarizedField>OpportunityLineItem.TotalPrice</summarizedField>
    <summaryFilterItems>
        <field>OpportunityLineItem.Product_Code_Copy__c</field>
        <operation>contains</operation>
        <value>LIC, PROF</value>
    </summaryFilterItems>
    <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Unique_Shipping_Addresses__c.field-meta.xml
<CustomField>
    <fullName>Unique_Shipping_Addresses__c</fullName>
    <description>Rolled up with DLRS to count the # of unique shipping addresses associated with Opp Line Items.</description>
    <label>Unique Shipping Addresses</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Trial.recordType-meta.xml
<RecordType>
    <fullName>Trial</fullName>
    <active>true</active>
    <businessProcess>Standard Opportunities</businessProcess>
    <label>Trial</label>
</RecordType>

force-app/main/default/objects/OpportunityLineItem/fields/Express_Annual_Discount__c.field-meta.xml
<CustomField>
    <fullName>Express_Annual_Discount__c</fullName>
    <label>Express Annual Discount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Express_Selected_Discount__c.field-meta.xml
<CustomField>
    <fullName>Express_Selected_Discount__c</fullName>
    <description>Holds the discount given in the Add Products page(Commercial), can retire this once we get rid of the Add products page.</description>
    <label>Express Selected Discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Express_Upfront_Discount__c.field-meta.xml
<CustomField>
    <fullName>Express_Upfront_Discount__c</fullName>
    <defaultValue>0.15</defaultValue>
    <label>Express Upfront Discount</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Selected_Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>Selected_Sales_Price__c</fullName>
    <description>Price that the user manually selected for the product line (otherwise it is just the suggested price).</description>
    <label>Monthly Price per Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Ship_From_Location__c.field-meta.xml
<CustomField>
    <fullName>Ship_From_Location__c</fullName>
    <description>Where is the product line for the oppty being shipped from.</description>
    <label>Ship From Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GS_OpportunityToLineItemUpdateAsync.cls
public with sharing class GS_OpportunityToLineItemUpdateAsync extends BaseAsyncHandler{
    public SamsaraLoggerService thisSamsaraLoggerService = new SamsaraLoggerService();
    public override String getRequestType(){
        return 'OpportunityToLineItemUpdate Async Job';
    }
    
    List<Schema.SObjectType> MY_SOBJECTS = new List<Schema.SObjectType>{
        OpportunityLineItem.SObjectType
    };

    List<Id> recordsIds;
    List<Opportunity> opptyList;
    public GS_OpportunityCacheService oppCache = new GS_OpportunityCacheService();
    public override void execute(Async_Request__c ar){

        recordsIds = ar.Params__c.split(PARAMETERS_SPLITTER);
        if(recordsIds.isEmpty()) return;
    
        DMLWrapper.intializeUnitOfWork(MY_SOBJECTS);
        
        try{
        thisSamsaraLoggerService.logger.logTrace('Entering in GS_OpportunityToLineItemUpdateAsync');
        this.loadOpportunities(recordsIds);

        this.setAnnualDiscountLineItemeUpdateOperations();

        this.publishDMLs();
        }catch(Exception ex){
            thisSamsaraLoggerService.logger.logError('Error in GS_OpportunityToLineItemUpdateAsync::', new SamsaraLoggerObjectMVP(
                ex, recordsIds
        ));
            throw ex;
        }
        finally {
            thisSamsaraLoggerService.logger.logTrace('Exiting in GS_OpportunityToLineItemUpdateAsync');
            thisSamsaraLoggerService.logger.dispatch();
        }
    }

    private void loadOpportunities(List<Id> idList){
        if (opptyList == null){
            this.opptyList = (new GS_OpportunitySelector(false)).loadOpportunityWithItems(new Set<Id>(idList));
            oppCache.cacheRelatedIdsFromOpps(this.opptyList);
            oppCache.loadOpportunityWithOpptyLineItems(oppCache.cachedOpportunityIds);
        }
    }

    public void setAnnualDiscountLineItemeUpdateOperations(){
        
        List<OpportunityLineItem> opptyLToUpdate = new List<OpportunityLineItem>();

        for (Opportunity newOpp : this.opptyList) {
            Decimal expressSelectedDiscount = newOpp.Express_Selected_Discount__c != null ? newOpp.Express_Selected_Discount__c : 0;
            for (OpportunityLineItem oli : oppCache.loadedOpportunityWithOpptyLineItemsMap.get(newOpp.Id).OpportunityLineItems) {
                        
                OpportunityLineItem triggerHandlerOli;
                
                    triggerHandlerOli = new OpportunityLineItem(Id = oli.Id, Express_Selected_Discount__c = oli.Express_Selected_Discount__c, Discount = oli.Discount, Express_Annual_Discount__c = oli.Express_Annual_Discount__c, Selected_Sales_Price__c = oli.Selected_Sales_Price__c, UnitPrice = oli.UnitPrice);

                if (oli.ProductCode.contains('LIC')) {
                    if (newOpp.Selected_Payment_Type__c == 'Direct Annual') {
                        triggerHandlerOli.Express_Annual_Discount__c = (((newOpp.Total_License_Due__c - (newOpp.Total_License_Due__c * (1 - (newOpp.Express_Annual_Discount__c / 100)))) / (newOpp.Total_License_Due__c / (1 - (expressSelectedDiscount / 100)))) * 100);

                        if (newOpp.Express_Selected_Discount__c != null) {
                            triggerHandlerOli.Discount = newOpp.Express_Selected_Discount__c + triggerHandlerOli.Express_Annual_Discount__c;
                        } else if (triggerHandlerOli.Discount != null) {
                            triggerHandlerOli.Discount = triggerHandlerOli.Discount + triggerHandlerOli.Express_Annual_Discount__c;
                        } else {
                            triggerHandlerOli.Discount = triggerHandlerOli.Express_Annual_Discount__c;
                        }

                        if (newOpp.License_Term__c != null) {
                            triggerHandlerOli.Selected_Sales_Price__c = triggerHandlerOli.UnitPrice * (100 - triggerHandlerOli.Discount) / (newOpp.License_Term__c * 100);
                        } else {
                            triggerHandlerOli.Selected_Sales_Price__c = triggerHandlerOli.UnitPrice * (100 - triggerHandlerOli.Discount) / (36 * 100);
                        }
                    } else if (newOpp.Selected_Payment_Type__c == 'Upfront Payments') {
                        triggerHandlerOli.Express_Upfront_Discount__c = (((newOpp.Total_License_Due__c - (newOpp.Total_License_Due__c * (1 - (newOpp.Express_Upfront_Discount__c / 100)))) / (newOpp.Total_License_Due__c / (1 - (expressSelectedDiscount / 100)))) * 100);

                        if (newOpp.Express_Selected_Discount__c != null) {
                            triggerHandlerOli.Discount = newOpp.Express_Selected_Discount__c + triggerHandlerOli.Express_Upfront_Discount__c;
                        } else if (triggerHandlerOli.Discount != null) {
                            triggerHandlerOli.Discount = triggerHandlerOli.Discount + triggerHandlerOli.Express_Upfront_Discount__c;
                        } else {
                            triggerHandlerOli.Discount = triggerHandlerOli.Express_Upfront_Discount__c;
                        }

                        if (newOpp.License_Term__c != null) {
                            triggerHandlerOli.Selected_Sales_Price__c = triggerHandlerOli.UnitPrice * (100 - triggerHandlerOli.Discount) / (newOpp.License_Term__c * 100);
                        } else {
                            triggerHandlerOli.Selected_Sales_Price__c = triggerHandlerOli.UnitPrice * (100 - triggerHandlerOli.Discount) / (36 * 100);
                        }
                    } else {
                        triggerHandlerOli.Express_Annual_Discount__c = 0;

                        if (newOpp.Express_Selected_Discount__c != null) {
                            triggerHandlerOli.Discount = newOpp.Express_Selected_Discount__c + triggerHandlerOli.Express_Annual_Discount__c;
                        } else if (triggerHandlerOli.Discount != null) {
                            triggerHandlerOli.Discount = triggerHandlerOli.Discount + triggerHandlerOli.Express_Annual_Discount__c;
                        } else {
                            triggerHandlerOli.Discount = triggerHandlerOli.Express_Annual_Discount__c;
                        }

                        if (newOpp.License_Term__c != null) {
                            triggerHandlerOli.Selected_Sales_Price__c = triggerHandlerOli.UnitPrice * (100 - triggerHandlerOli.Discount) / (newOpp.License_Term__c * 100);
                        } else {
                            triggerHandlerOli.Selected_Sales_Price__c = triggerHandlerOli.UnitPrice * (100 - triggerHandlerOli.Discount) / (36 * 100);
                        }
                    }
                    opptyLToUpdate.add(triggerHandlerOli);
                }
            }
        }

        /**
        * @author Groundswell - Henry Zhao - henry@gscloudsolutions.com
        * @date 2020-10-06
        * @deprecated per request of Ron. This logic is no longer needed with the launch of CPQ
        */
        if (opptyLToUpdate.size() > 0) {
            //update opptyLToUpdate;
            DMLWrapper.doUpdate(opptyLToUpdate);
        }
    
    }


    private void publishDMLs() {
        DMLWrapper.publishDML();
    }

    //* Dec 17th, 2020 Ron (GTMS-2033) expressSetAnnualDiscountLineItem (pull back in for Webstore Deals + legacy AE1 deals)
    // After the Annual Discount logic is deprecated, this method can be given a generic name -@Harsha
    public void expressSetAnnualDiscountLineItem(Map<Id, Opportunity> oldOppMap, List<Opportunity> newOpportunityList, GS_OpportunityCacheService oppCache) {
        Map<String, String> prodCodesToDispatchMap = new Map<String, String>();
        List<String> lstDCLProdCodes = new List<String>();
        Set<Id> opptyIdsSet = new Set<Id>();
        oppCache.loadOpportunityWithOpptyLineItems(oppCache.cachedOpportunityIds);

        for (Opportunity newOpp : newOpportunityList) { 
            Opportunity oldOpp = oldOppMap.get(newOpp.Id);
            String prodCodesToDispatch = '';
            Decimal productCount = newOpp.of_HW_Products__c + newOpp.of_Accessories__c;
        
                if (oldOpp.StageName != 'Orders Processing' 
                    && newOpp.StageName == 'Orders Processing' 
                    &&(newOpp.Type == 'Free Trial Opportunity' 
                       || newOpp.Type == 'Promo Opportunity')
                    && (newOpp.Ship_From_Location__c == 'DCL' 
                        || newOpp.Ship_From_Location__c == 'DCL-KY')
                    && oldOpp.Probability < 98 
                    && newOpp.CurrencyIsoCode == 'USD' 
                    && newOpp.Hold_Reason__c == null 
                    && newOpp.Order_Ops_Notes__c == null 
                    && newOpp.Shipping_Address_NEW__c != null 
                    && newOpp.Unique_Shipping_Addresses__c == 1 
                    && productCount <= 50 
                    && (newOpp.Shipping_Method__c == '3 Day Select' 
                        || newOpp.Shipping_Method__c == 'Ground' 
                        || newOpp.Shipping_Method__c == 'Next Day Air') 
                    && new GS_OpportunityService().checkDCLQualified(newOpp, oldOpp)) {
                    lstDCLProdCodes = System.Label.DCL_Product_SKU_List.split(',');
                    Boolean productFlag = true;
                    for (OpportunityLineItem oli : oppCache.loadedOpportunityWithOpptyLineItemsMap.get(newOpp.Id).OpportunityLineItems) {
                        system.debug('lstDCLProdCodes :'+lstDCLProdCodes);
                        system.debug('oli.ProductCode :'+oli.ProductCode);
                        if (lstDCLProdCodes.contains(oli.ProductCode) 
                            && oli.Quantity <= 10 
                            && oli.Quantity >= 1 
                            && oli.Ship_To_Country__c == 'United States') {
                            prodCodesToDispatch = prodCodesToDispatch + ',' + oli.ProductCode;
                        } else {
                            productFlag = false;
                        }
                    }
                        system.debug('prodCodesToDispatch :'+prodCodesToDispatch);
                        system.debug('productFlag :'+productFlag);  
                    if (prodCodesToDispatch != '' 
                        && productFlag == true) {
                        prodCodesToDispatchMap.put(newOpp.Id, prodCodesToDispatch);
                    }
                }

					system.debug('newOpp.Configuration_Segment__c :'+newOpp.Configuration_Segment__c);
                    system.debug('newOpp.Probability :'+newOpp.Probability);
                   system.debug('newOpp.Total_License_Due__c :'+newOpp.Total_License_Due__c);
            
                if (((newOpp.Selected_Payment_Type__c != null 
                            && oldOpp.Selected_Payment_Type__c != newOpp.Selected_Payment_Type__c)
                            || newOpp.Name.contains('Webstore'))
                        && newOpp.Configuration_Segment__c != null 
                        && newOpp.Configuration_Segment__c == 'Express' 
                        && newOpp.Probability < 95 
                        && newOpp.Total_License_Due__c > 0 
                        && newOpp.SBQQ__PrimaryQuote__c == null) {
                            opptyIdsSet.add(newOpp.Id);
                    }   

                if(!opptyIdsSet.isEmpty()){
                    DMLWrapper.doInsert(new GS_OpportunityToLineItemUpdateAsync().prepareAsyncRequests(
                        opptyIdsSet
                    ));
                }        

            if (!prodCodesToDispatchMap.isEmpty()) {
                System.debug('About to call ValidateProductQuantityFeature');
                ValidateProductQuantityFuture.fetchProductQuantity(prodCodesToDispatchMap);
            }
        }
    }

    public void updateLicenseTermToMatchParentOpportunity(Opportunity oppty){
        /* Replaces Node 'License Term Changes' */
        for(OpportunityLineItem oli : oppty.OpportunityLineItems){
            oli.License_Term_Copy__c = oppty.License_Term__c;
            DMLWrapper.doUpdate(oli, new List<SObjectField>{OpportunityLineItem.License_Term_Copy__c});
            //System.debug('OpportunityProcessBuilderConversion - Running Node: License Term Changes');
        }
    }
 
    public void updateShipToToMatchAddressFromOpportunity(Opportunity oppty){
        System.debug(LoggingLevel.INFO, 'Shipping Address Change');
        /* Replaces Node 'Product Added or Opp's Shipping Address Changes' */
        for(OpportunityLineItem oli : oppty.OpportunityLineItems){
            oli.Ship_To__c = oppty.Shipping_Address_NEW__c;
            DMLWrapper.doUpdate(oli, new List<SObjectField>{OpportunityLineItem.Ship_To__c});
            //System.debug('OpportunityProcessBuilderConversion - Running Node: Product Added or Opp\'s Shipping Address Changes');
        }
    }

}