force-app/main/default/objects/Async_Request__c/Async_Request__c.object-meta.xml
<CustomObject>
    <description>Use to queue up an Asynchronous Request for processing</description>
    <label>Async Request</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Async Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Async Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Async_Request__c/fields/Options__c.field-meta.xml
<CustomField>
    <fullName>Options__c</fullName>
    <description>Additional Options that can be used when processing the request</description>
    <label>Options</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Async_Request__c/fields/Params__c.field-meta.xml
<CustomField>
    <fullName>Params__c</fullName>
    <label>Params</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/License_Term__c.field-meta.xml
<CustomField>
    <fullName>License_Term__c</fullName>
    <defaultValue>36</defaultValue>
    <description>The license term of the opportunity.</description>
    <label>License Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Owner_Role_Copy__c.field-meta.xml
<CustomField>
    <fullName>Owner_Role_Copy__c</fullName>
    <description>Stores the role of the owner of the opportunity at the time it became a closed won.</description>
    <label>Owner Role Copy</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TrialResolutionOppty__c.field-meta.xml
<CustomField>
    <fullName>TrialResolutionOppty__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reference to a Trial&apos;s Revenue or Return opportunity.</description>
    <label>Revenue Opportunity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Opportunity.Type</field>
            <operation>equals</operation>
            <value>Revenue Opportunity, Free Trial Return, Revenue Opportunity - Bill Only</value>
        </filterItems>
        <filterItems>
            <field>Opportunity.StageName</field>
            <operation>notEqual</operation>
            <value>Closed Won</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunities (Trial Resolution Oppty)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Standard_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Standard_Opportunity</fullName>
    <active>true</active>
    <businessProcess>Revenue Opportunities</businessProcess>
    <label>Standard Opportunity</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Trial.recordType-meta.xml
<RecordType>
    <fullName>Trial</fullName>
    <active>true</active>
    <businessProcess>Standard Opportunities</businessProcess>
    <label>Trial</label>
</RecordType>

force-app/main/default/objects/User/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <inlineHelpText>Use instead of Geography as of Q1.FY2021</inlineHelpText>
    <label>Sales Territory</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/OpportunityToSELogsServiceTest.cls
@IsTest
public without sharing class OpportunityToSELogsServiceTest {
    
@TestSetup    
 
    public static void setupTestUsers() {
        // Query UserRole and Profile in separate SOQL calls
        Id userRoleId = [SELECT Id FROM UserRole WHERE Name LIKE '%Fleet IS AE2 NA US%' LIMIT 1].Id;
        Id profileId = [SELECT Id FROM Profile WHERE Name LIKE '%System Administrator%' LIMIT 1].Id;

        // Create test users
        User testUsers = new User(
                LastName = 'McGrath',
                Alias = 'test1',
                Email = 'tuser@test1.com',
                Username = 'tuser' + DateTime.now().millisecond() + '@test.com', // Unique username
                CommunityNickname = 'User16529768062775798018',
                UserRoleId = userRoleId,
                ProfileId = profileId, 
                Territory__c = 'North America', // Ensure this field exists
                TimeZoneSidKey = 'America/Los_Angeles',
                LocaleSidKey = 'en_US',
                LanguageLocaleKey = 'en_US',
                EmailEncodingKey = 'ISO-8859-1',
            EmployeeNumber = 'NA'
        );
     insert testUsers;
    }
    
       
    public static Opportunity opp;

    public static void buildBasicOpp(){
            User testUser = [SELECT Id FROM User WHERE Email = 'tuser@test1.com' LIMIT 1];
        System.runAs(testUser) {
        opp = new Opportunity(
            Id = TestFactory.getFakeId(Opportunity.getSObjectType()),
            CurrencyIsoCode = 'USD',
            Probability = 50,
            Owner_Role_Copy__c = 'Enterprise',
            Amount = 1000000,
            License_Term__c = 11
        );
        
        opp.TrialResolutionOppty__c = TestFactory.getFakeId(Opportunity.getSObjectType());
        opp.TrialResolutionOppty__r = new Opportunity(
            Id = opp.TrialResolutionOppty__c,
            CloseDate = System.today().addDays(30)
        );
        }
    }
    public static void buildEnterpriseTrialOpp(){
            User testUser = [SELECT Id FROM User WHERE Email = 'tuser@test1.com' LIMIT 1];
        System.runAs(testUser) {
        buildBasicOpp();
        opp.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Trial').getRecordTypeId();
        opp.StageName = 'Closed Won';

        Formula.recalculateFormulas(new List<Opportunity>{opp});
        }
    }

    public static void buildEnterpriseStandardOpp(){
            User testUser = [SELECT Id FROM User WHERE Email = 'tuser@test1.com' LIMIT 1];
        System.runAs(testUser) {
        buildBasicOpp();
        opp.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Standard_Opportunity').getRecordTypeId();
        opp.StageName = 'Trial';

        Formula.recalculateFormulas(new List<Opportunity>{opp});
        }
    }

    public static void buildNonEnterpriseStandardOpp(){
         User testUser = [SELECT Id FROM User WHERE Email = 'tuser@test1.com' LIMIT 1];
        System.runAs(testUser) {
        buildBasicOpp();
        opp.Owner_Role_Copy__c = 'SLED';
        opp.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Standard_Opportunity').getRecordTypeId();
        opp.StageName = 'Trial';
        
        Formula.recalculateFormulas(new List<Opportunity>{opp});
        }
    }

    @IsTest
    public static void testSyncService(){
         User testUser = [SELECT Id FROM User WHERE Email = 'tuser@test1.com' LIMIT 1];
        System.runAs(testUser) {
        DMLWrapper.intializeUnitOfWork(new List<Schema.SObjectType>{
            Async_Request__c.SObjectType
        });

        buildEnterpriseTrialOpp();
        Opportunity enterpriseTrialOpp = opp;
        buildNonEnterpriseStandardOpp();
        Opportunity nonEnterpriseOpp = opp;

        new OpportunityToSELogsService().runAfter(new Map<Id, Opportunity>{
            enterpriseTrialOpp.Id => enterpriseTrialOpp,
            nonEnterpriseOpp.Id => nonEnterpriseOpp
        });
        //Test.stopTest();
    }
    }

    @IsTest
    public static void testAsyncService_SELogsCreation(){
         User testUser = [SELECT Id FROM User WHERE Email = 'tuser@test1.com' LIMIT 1];
        System.runAs(testUser) {
        buildEnterpriseTrialOpp();
        Opportunity enterpriseTrialOpp = opp;
        buildEnterpriseStandardOpp();
        Opportunity enterpriseStandardOpp = opp;
        buildNonEnterpriseStandardOpp();
        Opportunity trialOpp = opp; 

        OpportunityToSELogsServiceAsync.PERFORM_DMLS = false;
        OpportunityToSELogsServiceAsync service = new OpportunityToSELogsServiceAsync();
        service.queriedOppMap = new Map<Id, Opportunity>{
            enterpriseTrialOpp.Id => enterpriseTrialOpp,
            enterpriseStandardOpp.Id => enterpriseStandardOpp,
            trialOpp.Id => trialOpp
        };

        service.execute(new Async_Request__c(
            Params__c = enterpriseTrialOpp.Id+';'+enterpriseStandardOpp.Id+';'+trialOpp.Id+';',
            Options__c = JSON.serialize(new OpportunityToSELogsServiceAsync.Options('Insert'))
        ));
    }
    }
}