force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Samsara Log</label>
    <nameField>
        <displayFormat>LOG-{0000}</displayFormat>
        <label>Samsara Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Samsara Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/ExceptionMessage__c.field-meta.xml
<CustomField>
    <fullName>ExceptionMessage__c</fullName>
    <label>Exception Message</label>
    <length>131071</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/LogLevel__c.field-meta.xml
<CustomField>
    <fullName>LogLevel__c</fullName>
    <label>Log Level</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Samsara Logs</relationshipLabel>
    <relationshipName>Samsara_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Samsara Logs</relationshipLabel>
    <relationshipName>Samsara_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/StackTrace__c.field-meta.xml
<CustomField>
    <fullName>StackTrace__c</fullName>
    <label>Stack Trace</label>
    <length>131071</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Renewal_Data_Error_Category__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Data_Error_Category__c</fullName>
    <description>Renewal_Data_Error_Category__c picklist field will identify any errors in the oppty quote data and this field is used by jobRecalculateQuote Batch class if it is true</description>
    <label>Renewal Data Error Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACVDidNotMatch</fullName>
                <label>ACV Did Not Match</label>
            </value>
            <value>
                <fullName>AmountDidNotMatch</fullName>
                <label>Amount Did Not Match</label>
            </value>
            <value>
                <fullName>LicenseTermDidNotMatch</fullName>
                <label>License Term Did Not Match</label>
            </value>
            <value>
                <fullName>ShippingAddressDidNotMatch</fullName>
                <label>Shipping Address Did Not Match</label>
            </value>
            <value>
                <fullName>PaymentTypeDidNotMatch</fullName>
                <label>Payment Type Did Not Match</label>
            </value>
            <value>
                <fullName>TaxIssue</fullName>
                <label>Tax Issue</label>
            </value>
            <value>
                <fullName>CalculationIssue</fullName>
                <label>Calculation Issue</label>
            </value>
            <value>
                <fullName>CleanData</fullName>
                <label>Clean Data</label>
            </value>
            <value>
                <fullName>NegativeBlendedDiscount</fullName>
                <label>Negative Blended Discount</label>
            </value>
            <value>
                <fullName>UpliftIsNull</fullName>
                <label>Uplift is Null</label>
            </value>
            <value>
                <fullName>UpliftNotMatch</fullName>
                <label>Quote Uplift Did Not Match with Contract Uplift</label>
            </value>
            <value>
                <fullName>DigitalRenewalJobFailed</fullName>
                <label>Digital Renewal Job Failed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AsyncJobReCalculateQuote.cls
public class AsyncJobReCalculateQuote implements Queueable {
    public Integer batchStep;
    public Set<Id> qteIds;
    public List<Log__c> logListAfter = new List<Log__c>();
    
	public AsyncJobReCalculateQuote(set<string> quoteIds ){
        Set<Id> qteeIds =new Set<Id>();
        for(string qt: quoteIds){
            qteeIds.add(qt);
        }
        this.qteIds = qteeIds;
    }
    public void execute(QueueableContext context) {
            
        	if(qteIds.size()>0){
            	GS_SBQQQuoteService.sourceQuoteData = new GS_SBQQQuoteSelector(true).checkFatalError().getQuotesAndQuoteLinesById(qteIds);
				for(SBQQ__Quote__c qte: GS_SBQQQuoteService.sourceQuoteData.values()){
                	if(GS_SBQQQuoteService.getRenewalDataErrorCategoryType(qte)){
                    
                    Log__c logRecord = new Log__c();
                    logRecord.Quote__c = qte.Id;
                    logRecord.Opportunity__c = qte.SBQQ__Opportunity2__c;
                    logRecord.ClassName__c = 'JobReCalculateQuote';
                    logRecord.Type__c = 'Renewal Validation Job';
                    logRecord.Message__c = 'Erros After Job';
                    logRecord.ExceptionMessage__c = qte.Renewal_Data_Error_Category__c;
                    logRecord.StackTrace__c = null;
                    logRecord.Exception_Type__c = null;
                    logRecord.LogLevel__c = 'Info';
                    this.logListAfter.add(logRecord);
                	}
            	}
        	}
        
                if(logListAfter.size() > 0){ 
                    try{
                    	Database.insert(logListAfter, false);
                	}catch(Exception e){
                    	System.debug('e.getMessage()====='+e.getMessage());
                    } 
                }
                
            
        
    }
	
}