force-app/main/default/objects/LeanData__Round_Robin_Schedule_Setting__c/LeanData__Round_Robin_Schedule_Setting__c.object-meta.xml
<CustomObject>
    <label>Schedule Setting</label>
    <nameField>
        <label>Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LeanData__Round_Robin_Schedule_Setting__c/fields/LeanData__Vacation_User__c.field-meta.xml
<CustomField>
    <fullName>LeanData__Vacation_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vacation User</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>User</relationshipLabel>
    <relationshipName>User</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quota__c/Quota__c.object-meta.xml
<CustomObject>
    <description>Used for role&apos;s/rep&apos;s historical performance analysis.</description>
    <label>Quota</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Quota Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quota__c/fields/Adj_Role_Start_Date_v2__c.field-meta.xml
<CustomField>
    <fullName>Adj_Role_Start_Date_v2__c</fullName>
    <label>Adj. Role Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quota__c/fields/ADR_Segment_Alignment__c.field-meta.xml
<CustomField>
    <fullName>ADR_Segment_Alignment__c</fullName>
    <description>The segment OB ADRs are supporting, as this is not in the role hierarchy. This is field is being getting data from User Object.</description>
    <label>ADR Segment Alignment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AE2</fullName>
            </value>
            <value>
                <fullName>AE3</fullName>
            </value>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
            </value>
            <value>
                <fullName>Partnerships</fullName>
            </value>
            <value>
                <fullName>DVS</fullName>
            </value>
            <value>
                <fullName>AE2 SLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quota__c/fields/Fiscal_Period__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_Period__c</fullName>
    <description>Fiscal period associated with the quota.</description>
    <label>Fiscal Period</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quota__c/fields/Fiscal_Period_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_Period_Start_Date__c</fullName>
    <description>Used to determine ramp period and status</description>
    <inlineHelpText>Used to determine ramp period and status</inlineHelpText>
    <label>Fiscal Period Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quota__c/fields/Geography__c.field-meta.xml
<CustomField>
    <fullName>Geography__c</fullName>
    <label>Geography</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quota__c/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <label>Industry</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quota__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quotas1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quota__c/fields/Office_Location__c.field-meta.xml
<CustomField>
    <fullName>Office_Location__c</fullName>
    <label>Office Location</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quota__c/fields/Q4_Quota__c.field-meta.xml
<CustomField>
    <fullName>Q4_Quota__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Q4 Quota</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quota__c/fields/Quota__c.field-meta.xml
<CustomField>
    <fullName>Quota__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Amount associated with the quota instance.</description>
    <label>Quota</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quota__c/fields/Quota_Period__c.field-meta.xml
<CustomField>
    <fullName>Quota_Period__c</fullName>
    <description>Used to differentiate between monthly vs. quarterly quotas</description>
    <inlineHelpText>Used to differentiate between monthly vs. quarterly quotas</inlineHelpText>
    <label>Quota Period</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quota__c/fields/Role_at_Start_of_Fiscal_Period__c.field-meta.xml
<CustomField>
    <fullName>Role_at_Start_of_Fiscal_Period__c</fullName>
    <description>Role of the rep at the start of Fiscal Period</description>
    <label>Role at Start of Fiscal Period</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quota__c/fields/Role_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Role_Start_Date__c</fullName>
    <description>Role start date for rep&apos;s role tied to the quota record</description>
    <inlineHelpText>Role start date for rep&apos;s role tied to the quota record</inlineHelpText>
    <label>Role Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quota__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <label>Territory</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quota__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User associated with the Quota instance.</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quotas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/ADR_Segment_Alignment__c.field-meta.xml
<CustomField>
    <fullName>ADR_Segment_Alignment__c</fullName>
    <description>The segment OB ADRs are supporting, as this is not in the role hierarchy.</description>
    <label>ADR Segment Alignment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AE2</fullName>
            </value>
            <value>
                <fullName>AE2 SLED</fullName>
            </value>
            <value>
                <fullName>AE3</fullName>
            </value>
            <value>
                <fullName>Core</fullName>
            </value>
            <value>
                <fullName>DVS</fullName>
            </value>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Inbound GS</fullName>
            </value>
            <value>
                <fullName>Mid - Market</fullName>
            </value>
            <value>
                <fullName>Mid - Market GS</fullName>
            </value>
            <value>
                <fullName>Mid - Market Pubsec</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
            </value>
            <value>
                <fullName>Partnerships</fullName>
            </value>
            <value>
                <fullName>Select</fullName>
            </value>
            <value>
                <fullName>Select Pubsec</fullName>
            </value>
            <value>
                <fullName>Strategic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fleet</fullName>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
            <value>
                <fullName>Connected Worker</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Geography__c.field-meta.xml
<CustomField>
    <fullName>Geography__c</fullName>
    <description>DO NOT DELETE.  REQUIRED FOR HISTORICAL REPORTING.  Contact Adam Barten with questions

 Pre Q1 FY21 AE Geography.</description>
    <label>Geography[Legacy]</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Central</fullName>
            </value>
            <value>
                <fullName>Northeast</fullName>
            </value>
            <value>
                <fullName>West</fullName>
            </value>
            <value>
                <fullName>South &amp; Midwest</fullName>
            </value>
            <value>
                <fullName>Mexico</fullName>
            </value>
            <value>
                <fullName>Canada West</fullName>
            </value>
            <value>
                <fullName>Canada East</fullName>
            </value>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>DACH</fullName>
            </value>
            <value>
                <fullName>UK &amp; I</fullName>
            </value>
            <value>
                <fullName>Iberia</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>BENELUX</fullName>
            </value>
            <value>
                <fullName>Industrial MV</fullName>
            </value>
            <value>
                <fullName>Industrial 4.0</fullName>
            </value>
            <value>
                <fullName>Field</fullName>
            </value>
            <value>
                <fullName>Italy</fullName>
            </value>
            <value>
                <fullName>East</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <label>Industry</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/User/fields/Office_Location__c.field-meta.xml
<CustomField>
    <fullName>Office_Location__c</fullName>
    <label>Office Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Atlanta</fullName>
            </value>
            <value>
                <fullName>Atlanta - ATL1</fullName>
            </value>
            <value>
                <fullName>London</fullName>
            </value>
            <value>
                <fullName>London - UK1</fullName>
            </value>
            <value>
                <fullName>London - UK2</fullName>
            </value>
            <value>
                <fullName>Remote</fullName>
            </value>
            <value>
                <fullName>Remote - AK</fullName>
            </value>
            <value>
                <fullName>Remote - AL</fullName>
            </value>
            <value>
                <fullName>Remote - AR</fullName>
            </value>
            <value>
                <fullName>Remote - AZ</fullName>
            </value>
            <value>
                <fullName>Remote - CA</fullName>
            </value>
            <value>
                <fullName>Remote - Calgary</fullName>
            </value>
            <value>
                <fullName>Remote - Canada</fullName>
            </value>
            <value>
                <fullName>Remote - CO</fullName>
            </value>
            <value>
                <fullName>Remote - Colombia</fullName>
            </value>
            <value>
                <fullName>Remote - CT</fullName>
            </value>
            <value>
                <fullName>Remote - DC</fullName>
            </value>
            <value>
                <fullName>Remote - FL</fullName>
            </value>
            <value>
                <fullName>Remote - France</fullName>
            </value>
            <value>
                <fullName>Remote - France (35H)</fullName>
            </value>
            <value>
                <fullName>Remote - GA</fullName>
            </value>
            <value>
                <fullName>Remote - Germany</fullName>
            </value>
            <value>
                <fullName>Remote - HI</fullName>
            </value>
            <value>
                <fullName>Remote - IA</fullName>
            </value>
            <value>
                <fullName>Remote - ID</fullName>
            </value>
            <value>
                <fullName>Remote - IL</fullName>
            </value>
            <value>
                <fullName>Remote - IN</fullName>
            </value>
            <value>
                <fullName>Remote - India</fullName>
            </value>
            <value>
                <fullName>Remote - KS</fullName>
            </value>
            <value>
                <fullName>Remote - KY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Quota__c.field-meta.xml
<CustomField>
    <fullName>Quota__c</fullName>
    <description>Current Quarter Quota</description>
    <inlineHelpText>Current Quarter Quota set by Sales Management</inlineHelpText>
    <label>Quota</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/User/fields/Role_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Role_Start_Date__c</fullName>
    <description>Date when user was hired or promoted into current role</description>
    <inlineHelpText>Date when user was hired or promoted into current role</inlineHelpText>
    <label>Role Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/User/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <inlineHelpText>Use instead of Geography as of Q1.FY2021</inlineHelpText>
    <label>Sales Territory</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/QuotaDefaultsTest.cls
/**
 * Created by henryzhao on 2020-12-18.
 */

@IsTest
private class QuotaDefaultsTest {
    @IsTest
    static void testNullDefaultsFromUser() {
        /*Arrange*/
        Id managerId = TestFactory.getFakeId(User.getSObjectType());
        UserRole mockRole = new UserRole(Name = 'FakeRole');
        User usr = (User) TestFactory.createSObject(new User(
                Id = TestFactory.getFakeId(User.getSObjectType()),
                Office_Location__c = 'FakeLocation',
                ManagerId = managerId,
                Territory__c = 'FakeTerritory',
                Business_Unit__c = 'FakeBusiness',
                Role_Start_Date__c = Date.today(),
                UserRole = mockRole,
                ADR_Segment_Alignment__c = 'FakeSegment'
        ));
        Quota__c testQuota = new Quota__c(
                Id = TestFactory.getFakeId(Quota__c.getSObjectType()),
                User__c = usr.Id,
                User__r = usr
        );
        QuotaDefaults defaults = new QuotaDefaults(new List<Quota__c>{
                testQuota
        });
        defaults.quotaToUserMap.put(testQuota.Id, usr);
        /*Act*/
        defaults.onApplyDefaults(testQuota,null);

        /*Assert*/
        System.assertEquals(usr.Id, testQuota.OwnerId);
        System.assertEquals(usr.Office_Location__c, testQuota.Office_Location__c);
        System.assertEquals(usr.ManagerId, testQuota.Manager__c);
        System.assertEquals(usr.Territory__c, testQuota.Geography__c);
        System.assertEquals(usr.Business_Unit__c, testQuota.Industry__c);
        System.assertEquals(usr.Territory__c, testQuota.Territory__c);
        System.assertEquals(usr.Role_Start_Date__c, testQuota.Role_Start_Date__c);
        System.assertEquals(usr.UserRole.Name, testQuota.Role_at_Start_of_Fiscal_Period__c);
        System.assertEquals(usr.ADR_Segment_Alignment__c, testQuota.ADR_Segment_Alignment__c);
    }

    @IsTest
    static void testNonNullDefaultsFromUser() {
        /*Arrange*/
        Id managerId = TestFactory.getFakeId(User.getSObjectType());
        UserRole mockRole = new UserRole(Name = 'FakeRole');
        User usr = (User) TestFactory.createSObject(new User(
                Id = TestFactory.getFakeId(User.getSObjectType()),
                Office_Location__c = 'FakeLocation',
                ManagerId = managerId,
                Territory__c = 'FakeTerritory',
                Business_Unit__c = 'FakeBusiness',
                Role_Start_Date__c = Date.today(),
                UserRole = mockRole,
                ADR_Segment_Alignment__c = 'FakeSegment'
        ));
        Id realManagerId = TestFactory.getFakeId(User.getSObjectType());
        Quota__c testQuota = new Quota__c(
                Id = TestFactory.getFakeId(Quota__c.getSObjectType()),
                User__c = usr.Id,
                User__r = usr,
                OwnerId = TestFactory.getFakeId(User.getSObjectType()),
                Office_Location__c = 'RealLocation',
                Manager__c = realManagerId,
                Geography__c = 'RealGeography',
                Industry__c = 'RealIndustry',
                Territory__c = 'RealTerritory',
                Role_Start_Date__c = Date.today().addDays(-1),
                Role_at_Start_of_Fiscal_Period__c = 'RealRole',
                ADR_Segment_Alignment__c = 'RealSegment'
        );
        QuotaDefaults defaults = new QuotaDefaults(new List<Quota__c>{
                testQuota
        });
        defaults.quotaToUserMap.put(testQuota.Id, usr);
        /*Act*/
        defaults.onApplyDefaults(testQuota,null);

        /*Assert*/
        System.assertEquals(usr.Id, testQuota.OwnerId);
        System.assertEquals(usr.ADR_Segment_Alignment__c, testQuota.ADR_Segment_Alignment__c);
        System.assertEquals('RealLocation', testQuota.Office_Location__c);
        System.assertEquals(realManagerId, testQuota.Manager__c);
        System.assertEquals('RealGeography', testQuota.Geography__c);
        System.assertEquals('RealIndustry', testQuota.Industry__c);
        System.assertEquals('RealTerritory', testQuota.Territory__c);
        System.assertEquals(Date.today().addDays(-1), testQuota.Role_Start_Date__c);
        System.assertEquals('FakeRole', testQuota.Role_at_Start_of_Fiscal_Period__c);
    }

    @IsTest
    static void testSetAdjRoleStartDateRoundDown() {
        /*Arrange*/
        final Date startDate = Date.newInstance(2020, 1, 1);
        Quota__c testQuota = new Quota__c(
                Id = TestFactory.getFakeId(Quota__c.getSObjectType()),
                Role_at_Start_of_Fiscal_Period__c = 'AE',
                Adj_Role_Start_Date_v2__c = null,
                Role_Start_Date__c = startDate
        );
        QuotaDefaults defaults = new QuotaDefaults(new List<Quota__c>{
                testQuota
        });
        /*Act*/
        defaults.onApplyDefaults(testQuota,null);

        /*Assert*/
        System.assertEquals(1, testQuota.Adj_Role_Start_Date_v2__c.day());
        System.assertEquals(startDate.month(), testQuota.Adj_Role_Start_Date_v2__c.month());
    }

    @IsTest
    static void testSetAdjRoleStartDateRoundUp() {
        /*Arrange*/
        final Date startDate = Date.newInstance(2020, 1, 16);
        Quota__c testQuota = new Quota__c(
                Id = TestFactory.getFakeId(Quota__c.getSObjectType()),
                Role_at_Start_of_Fiscal_Period__c = 'ADR',
                Adj_Role_Start_Date_v2__c = null,
                Role_Start_Date__c = startDate,
            	Fiscal_Period_Start_Date__c = date.today(),
        		Quota_Period__c='Q4',
                Quota__c = 1000,
                Q4_Quota__c = 1000);

        QuotaDefaults defaults = new QuotaDefaults(new List<Quota__c>{
                testQuota
        });
        /*Act*/
        defaults.onApplyDefaults(testQuota,null);

        /*Assert*/
        System.assertEquals(1, testQuota.Adj_Role_Start_Date_v2__c.day());
        System.assertEquals(startDate.month() + 1, testQuota.Adj_Role_Start_Date_v2__c.month());
    }
    
    @isTest
    static void insertQuotatest() {
        String UserQuery;    
        User testUser;

        UserQuery = 'SELECT Id, Name, Role_Start_Date__c, UserRole.Name FROM User WHERE UserRole.Name LIKE \'%Manager%\' AND IsActive = true LIMIT 1';
        

        testUser = database.query(UserQuery);

        Quota__c newQuota = new Quota__c(   User__c = testUser.Id, 
                                            Role_Start_Date__c = testUser.Role_Start_Date__c,
                                            Role_at_Start_of_Fiscal_Period__c = testUser.UserRole.Name,
                                            Fiscal_Period_Start_Date__c = System.now().date(), 
                                            Fiscal_Period_End_Date__c = System.now().date()+30, 
                                            Fiscal_Period__c='Q4-3000',
                                        	Quota_Period__c='Q3',
                                         	Quota__c = 1000,
                                        	Q3_Quota__c = 1000);
        
        Test.startTest();
        insert newQuota;
        Test.stopTest();
    }
    
    @isTest
     static void testAfterUpdate() {
        // Create test data
        String UserQuery;    
        User testUser;

        UserQuery = 'SELECT Id, Name, Role_Start_Date__c, UserRole.Name FROM User WHERE UserRole.Name LIKE \'%Manager%\' AND IsActive = true LIMIT 1';
        

        testUser = database.query(UserQuery);

        Quota__c newQuota = new Quota__c(   User__c = testUser.Id, 
                                            Role_Start_Date__c = testUser.Role_Start_Date__c,
                                            Role_at_Start_of_Fiscal_Period__c = testUser.UserRole.Name,
                                            Fiscal_Period_Start_Date__c = System.now().date(), 
                                            Fiscal_Period_End_Date__c = System.now().date()+30, 
                                            Fiscal_Period__c='Q3-3000',
                                        	Quota_Period__c='Q2',
                                         	Quota__c = 1000,
                                        	Q2_Quota__c = 1000);
        
         //insert method
        insert newQuota;
        
        // Call afterUpdate method
        Test.startTest();
        List<Quota__c> quotaList = new List<Quota__c>();
        newQuota.Quota__c = 200;
        quotaList.add(newQuota);
        update quotaList;
        Test.stopTest();
        
        
    }
    @isTest
    static void Quotadefaultstest() {
        String UserQuery;    
        User testUser;

        UserQuery = 'SELECT Id, Name, Role_Start_Date__c, UserRole.Name FROM User WHERE UserRole.Name LIKE \'%Manager%\' AND IsActive = true LIMIT 1';
        

        testUser = database.query(UserQuery);

        Quota__c newQuota = new Quota__c(   User__c = testUser.Id, 
                                            Role_Start_Date__c = testUser.Role_Start_Date__c,
                                            Role_at_Start_of_Fiscal_Period__c = testUser.UserRole.Name,
                                            Fiscal_Period_Start_Date__c = System.now().date(), 
                                            Fiscal_Period_End_Date__c = System.now().date()+30, 
                                            Fiscal_Period__c='Q2-3000',
                                        	Quota_Period__c='FY',
                                         	Quota__c = 0,
                                         	Q1_Quota__c = 0,
                                         	Q2_Quota__c = 0,
                                         	Q3_Quota__c = 0,
                                        	Q4_Quota__c = 0);
        
        Test.startTest();
        insert newQuota;
        Test.stopTest();
    }
@isTest
    static void Quotadefaultstest1() {
        String UserQuery;    
        User testUser;

        UserQuery = 'SELECT Id, Name, Role_Start_Date__c, UserRole.Name FROM User WHERE UserRole.Name LIKE \'%Manager%\' AND IsActive = true LIMIT 1';
        

        testUser = database.query(UserQuery);

        Quota__c newQuota = new Quota__c(   User__c = testUser.Id, 
                                            Role_Start_Date__c = testUser.Role_Start_Date__c,
                                            Role_at_Start_of_Fiscal_Period__c = testUser.UserRole.Name,
                                            Fiscal_Period_Start_Date__c = System.now().date(), 
                                            Fiscal_Period_End_Date__c = System.now().date()+30, 
                                            Fiscal_Period__c='Q2-3000',
                                        	Quota_Period__c='Q4',
                                         	Quota__c = 400,
                                         	Q1_Quota__c = 0,
                                         	Q2_Quota__c = 0,
                                         	Q3_Quota__c = 0,
                                        	Q4_Quota__c = 400);
        
        Test.startTest();
        insert newQuota;
        Test.stopTest();
    }
    @isTest
    static void Quotadefaultstest2() {
        String UserQuery;    
        User testUser;

        UserQuery = 'SELECT Id, Name, Role_Start_Date__c, UserRole.Name FROM User WHERE UserRole.Name LIKE \'%Manager%\' AND IsActive = true LIMIT 1';
        

        testUser = database.query(UserQuery);

        Quota__c newQuota = new Quota__c(   User__c = testUser.Id, 
                                            Role_Start_Date__c = testUser.Role_Start_Date__c,
                                            Role_at_Start_of_Fiscal_Period__c = testUser.UserRole.Name,
                                            Fiscal_Period_Start_Date__c = System.now().date(), 
                                            Fiscal_Period_End_Date__c = System.now().date()+30, 
                                            Fiscal_Period__c='Q1-3000',
                                        	Quota_Period__c='Q1',
                                         	Quota__c = 400,
                                         	Q1_Quota__c = 400,
                                         	Q2_Quota__c = 0,
                                         	Q3_Quota__c = 0,
                                        	Q4_Quota__c = 0);
        
        Test.startTest();
        insert newQuota;
        Test.stopTest();
    }

    @isTest
    static void setChangedTrialQuotaOnUserTest() {
        String UserQuery;    
        User testUser;

        UserQuery = 'SELECT Id, Name, Role_Start_Date__c, UserRole.Name FROM User WHERE UserRole.Name LIKE \'%Manager%\' AND IsActive = true LIMIT 1';
        

        testUser = database.query(UserQuery);

        Quota__c newQuota = new Quota__c(   User__c = testUser.Id, 
                                            Role_Start_Date__c = testUser.Role_Start_Date__c,
                                            Role_at_Start_of_Fiscal_Period__c = testUser.UserRole.Name,
                                            Fiscal_Period_Start_Date__c = System.now().date(), 
                                            Fiscal_Period_End_Date__c = System.now().date()+30, 
                                            Fiscal_Period__c='Q1-3000',
                                        	Quota_Period__c='Q1',
                                         	ADR_Quota__c = 400,
                                         	Q1_Quota__c = 400,
                                         	Q2_Quota__c = 0,
                                         	Q3_Quota__c = 0,
                                        	Q4_Quota__c = 0,
                                        	Trial_Quota__c =100);
        
        Test.startTest();
        
        insert newQuota;
        newQuota.ADR_Quota__c = 500;
        newQuota.Fiscal_Period_End_Date__c =System.now().date()+10;
        update newQuota;
        
        Test.stopTest();
    }

	@isTest
    static void setQuotaOnUserTest() {
        String UserQuery;    
        User testUser;

        UserQuery = 'SELECT Id, Name, Role_Start_Date__c, UserRole.Name FROM User WHERE UserRole.Name LIKE \'%Manager%\' AND IsActive = true LIMIT 1';
        

        testUser = database.query(UserQuery);

        Quota__c newQuota = new Quota__c(   User__c = testUser.Id, 
                                            Role_Start_Date__c = testUser.Role_Start_Date__c,
                                            Role_at_Start_of_Fiscal_Period__c = testUser.UserRole.Name,
                                            Fiscal_Period_Start_Date__c = System.now().date(), 
                                            Fiscal_Period_End_Date__c = System.now().date()-30, 
                                            Fiscal_Period__c='Q1-3000',
                                        	Quota_Period__c='Q1',
                                         	ADR_Quota__c = 400,
                                         	Q1_Quota__c = 400,
                                         	Q2_Quota__c = 0,
                                         	Q3_Quota__c = 0,
                                        	Q4_Quota__c = 0,
                                        	Trial_Quota__c =100);
        
        Test.startTest();
        
        insert newQuota;
        
        Test.stopTest();
    }
    
}