force-app/main/default/objects/Action_User_Preference__c/Action_User_Preference__c.object-meta.xml
<CustomObject>
    <label>Action User Preference</label>
    <nameField>
        <displayFormat>GUPREF-{00000000}</displayFormat>
        <label>Action User Preference Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action User Preferences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Action_User_Preference__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Action</label>
    <referenceTo>Actions__c</referenceTo>
    <relationshipLabel>Action User Preferences</relationshipLabel>
    <relationshipName>Action_User_Preferences</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Action_User_Preference__c/fields/Dismissed_Date__c.field-meta.xml
<CustomField>
    <fullName>Dismissed_Date__c</fullName>
    <label>Dismissed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Action_User_Preference__c/fields/Unique_Id__c.field-meta.xml
<CustomField>
    <fullName>Unique_Id__c</fullName>
    <externalId>true</externalId>
    <label>Unique Id</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Action_User_Preference__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Action_User_Preferences</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Actions__c/Actions__c.object-meta.xml
<CustomObject>
    <description>Object that captures actions to be taken when the usr hits a specific URL/type of page.</description>
    <label>Actions</label>
    <nameField>
        <label>Guideme Actions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Actions__c/fields/Action_Text__c.field-meta.xml
<CustomField>
    <fullName>Action_Text__c</fullName>
    <label>Action Text</label>
    <length>100000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Actions__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Actions__c/fields/Page_Type__c.field-meta.xml
<CustomField>
    <fullName>Page_Type__c</fullName>
    <label>Page Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Record Home</fullName>
            </value>
            <value>
                <fullName>Record Detail</fullName>
            </value>
            <value>
                <fullName>Record Update</fullName>
            </value>
            <value>
                <fullName>Record Create</fullName>
            </value>
            <value>
                <fullName>Reports Home</fullName>
            </value>
            <value>
                <fullName>Dashboards Home</fullName>
            </value>
            <value>
                <fullName>Task home</fullName>
            </value>
            <value>
                <fullName>Task Detail From List</fullName>
            </value>
            <value>
                <fullName>Chatter</fullName>
            </value>
            <value>
                <fullName>Chatter Group Detail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Actions__c/fields/Popover_Text__c.field-meta.xml
<CustomField>
    <fullName>Popover_Text__c</fullName>
    <label>Popover Text</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Actions__c/fields/Recurrence__c.field-meta.xml
<CustomField>
    <fullName>Recurrence__c</fullName>
    <label>Recurrence</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Days after certain date</fullName>
            </value>
            <value>
                <fullName>Only once</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Actions__c/fields/Recurrence_Date__c.field-meta.xml
<CustomField>
    <fullName>Recurrence_Date__c</fullName>
    <label>Recurrence Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Actions__c/fields/Recurrence_Days__c.field-meta.xml
<CustomField>
    <fullName>Recurrence_Days__c</fullName>
    <label>Recurrence Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Actions__c/fields/Subtab_Name__c.field-meta.xml
<CustomField>
    <fullName>Subtab_Name__c</fullName>
    <label>Subtab Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Actions__c/recordTypes/Image_Carousel.recordType-meta.xml
<RecordType>
    <fullName>Image_Carousel</fullName>
    <active>true</active>
    <label>Image Carousel</label>
</RecordType>

force-app/main/default/objects/Actions__c/recordTypes/Popover.recordType-meta.xml
<RecordType>
    <fullName>Popover</fullName>
    <active>true</active>
    <label>Popover</label>
</RecordType>

force-app/main/default/objects/Actions__c/recordTypes/Rich_Text.recordType-meta.xml
<RecordType>
    <fullName>Rich_Text</fullName>
    <active>true</active>
    <label>Rich Text</label>
</RecordType>

force-app/main/default/classes/LightningBuddyActionControllerTest.cls
@IsTest
public class LightningBuddyActionControllerTest {
    @testSetup static void setup() {
        
        Schema.DescribeSObjectResult sObjDesc = Actions__c.sObjectType.getDescribe();
        Map<String, Schema.RecordTypeInfo> recTypes = sObjDesc.getRecordTypeInfosByDeveloperName();
        System.debug('>>>>>> recordTypes : '+recTypes);
        List<Actions__c> toInsert = new List<Actions__c>();
        Actions__c action;
        action = new Actions__c(RecordTypeId=recTypes.get('Image_Carousel').getRecordTypeId(),
                                                Name='Test Image Carousel',
                                                Object__c='Home',
                                                Page_Type__c='Home');
        toInsert.add(action);
        action = new Actions__c(RecordTypeId=recTypes.get('Popover').getRecordTypeId(),
                                                Name='Test Popover',
                                                Object__c='Contact',
                                                Page_Type__c='Home',
                                                Popover_Text__c='Test');
        toInsert.add(action);
        action = new Actions__c(RecordTypeId=recTypes.get('Rich_Text').getRecordTypeId(),
                                                Name='Test Popover',
                                                Object__c='Case',
                                                Page_Type__c='Home',
                                                Action_Text__c='Test');
        toInsert.add(action);

        action = new Actions__c(RecordTypeId=recTypes.get('Rich_Text').getRecordTypeId(),
                                                Name='Test Only Once',
                                                Object__c='Contact',
                                                Page_Type__c='Home',
                                                Action_Text__c='Test',
                                               	Recurrence__c='Only once');
        toInsert.add(action);
        action = new Actions__c(RecordTypeId=recTypes.get('Rich_Text').getRecordTypeId(),
                                                Name='Test Days after',
                                                Object__c='Campaign',
                                                Page_Type__c='Home',
                                                Action_Text__c='Days after certain date',
                                               	Recurrence__c='Days after certain date',
                                               	Recurrence_Date__c=System.today().addDays(-1),
                                               	Recurrence_Days__c=1
                                                
                                               );
        toInsert.add(action);
        action = new Actions__c(RecordTypeId=recTypes.get('Rich_Text').getRecordTypeId(),
                                                Name='Test Days after 2',
                                                Object__c='Contract',
                                                Page_Type__c='Home',
                                                Action_Text__c='Days after certain date',
                                               	Recurrence__c='Days after certain date',
                                               	Recurrence_Date__c=System.today(),
                                               	Recurrence_Days__c=0
                                                
                                               );
        toInsert.add(action);
        action = new Actions__c(RecordTypeId=recTypes.get('Rich_Text').getRecordTypeId(),
                                                Name='Test Days after 3',
                                                Object__c='Asset',
                                                Page_Type__c='Home',
                                                Action_Text__c='Days after certain date',
                                               	Recurrence__c='Days after certain date',
                                               	Recurrence_Date__c=System.today().addDays(7),
                                               	Recurrence_Days__c=1
                                                
                                               );
        toInsert.add(action);

        insert toInsert;

        action = new Actions__c(RecordTypeId=recTypes.get('Rich_Text').getRecordTypeId(),
                                                Name='Test Sub Tab Action',
                                                Object__c='Actions__c',
                                                Page_Type__c='Record Detail',
                                                Subtab_Name__c='MySubTab',
                                                Record_Id__c=toInsert[0].Id,
                                                Action_Text__c='Test');
        insert action;


        action = new Actions__c(RecordTypeId=recTypes.get('Rich_Text').getRecordTypeId(),
                                                Name='Test Record Detail Rich_Text ',
                                                Object__c='Actions__c',
                                                Page_Type__c='Record Detail',
                                                Record_Id__c=toInsert[0].Id,
                                                Action_Text__c='Test');
        insert action;
        
        action = new Actions__c(RecordTypeId=recTypes.get('Rich_Text').getRecordTypeId(),
                                                Name='Test Record Update Rich_Text ',
                                                Object__c='Actions__c',
                                                Page_Type__c='Record Update',
                                                Action_Text__c='Test');
        insert action;
        
        action = toInsert[2];
        
        Action_User_Preference__c usrPref
            = new Action_User_Preference__c(Action__c=action.Id,
                                                            User__c=UserInfo.getUserId(),
                                                            Unique_Id__c=UserInfo.getUserId()+'_'+action.Id);
        insert usrPref;
        action = toInsert[3];
        usrPref 
            = new Action_User_Preference__c(Action__c=action.Id,
                                                            User__c=UserInfo.getUserId(),
                                                            Unique_Id__c=UserInfo.getUserId()+'_'+action.Id);
        insert usrPref;
        action = toInsert[5];
        usrPref 
            = new Action_User_Preference__c(Action__c=action.Id,
                                                            User__c=UserInfo.getUserId(),
                                                            Unique_Id__c=UserInfo.getUserId()+'_'+action.Id,
                                                           	Dismissed_Date__c=System.today()
                                                           );
        insert usrPref;

    }
    public static testmethod void testGetUserInfo(){
        User usr = LightningBuddyActionController.getLoggedInUser();
        System.assertEquals(UserInfo.getProfileId(),usr.ProfileId,'ProfileId mismatch');
        System.assertEquals(UserInfo.getUserName(),usr.Username,'Username mismatch');
        System.assertEquals(UserInfo.getUserId(),usr.Id,'User Id mismatch');
    }
    
    public static testmethod void testGetPopoverMessageToDisplay(){
        String popoverText = LightningBuddyActionController.getPopoverMessageToDisplay('Contact', 'Home', null);
        //System.assertEquals('Test', popoverText, 'Popover text mismatch');
    }
    public static testmethod void testNullPopoverMessageToDisplay(){
        String popoverText = LightningBuddyActionController.getPopoverMessageToDisplay('Case', 'Home', null);
        System.assertEquals(null, popoverText, 'Popover text NULL mismatch');
    }
    
    public static testmethod void testActionWithRecordId(){
        Actions__c action = [select Id from Actions__c where Name='Test Image Carousel' limit 1];
        
        List<Actions__c> actionsToDisplay = LightningBuddyActionController.getAction('Actions__c',
                                                                                                     'Record Detail',
                                                                                                     action.Id,
                                                                                                     null);
        System.assertEquals(1, actionsToDisplay.size(), 'No actions fetched for Action record detail');
        System.assertEquals('Test', actionsToDisplay[0].Action_Text__c, 'Action text mismatch');
    }

    
    public static testmethod void testActionWithoutRecordId(){
        Actions__c action = [select Id from Actions__c where Name='Test Image Carousel' limit 1];
        
        List<Actions__c> actionsToDisplay = LightningBuddyActionController.getAction('Home',
                                                                                                     'Home',
                                                                                                     null,
                                                                                                     null);
        System.assertEquals(1, actionsToDisplay.size(), 'No actions fetched for Home:Home');
    }    
    public static testmethod void testActionWithUserPreferences(){
        Actions__c action = [select Id from Actions__c where Name='Test Image Carousel' limit 1];
        
        List<Actions__c> actionsToDisplay = LightningBuddyActionController.getAction('Case',
                                                                                                     'Home',
                                                                                                     null,
                                                                                                     null);
        //System.assertEquals(0, actionsToDisplay.size(), 'Actions fetched for Case:Home when not expected');
    }
    public static testmethod void testActionWithRecordUpdate(){
        Actions__c action = [select Id from Actions__c where Name='Test Record Update Rich_Text' limit 1];
        
        List<Actions__c> actionsToDisplay = LightningBuddyActionController.getAction('Actions__c',
                                                                                                     'Record Update',
                                                                                                     action.Id,
                                                                                                     null);
        System.assertEquals(1, actionsToDisplay.size(), 'No actions fetched for Action record detail');
        System.assertEquals('Test', actionsToDisplay[0].Action_Text__c, 'Action text mismatch');
    }
    
    public static testmethod void testNoActions(){
        List<Actions__c> actionsToDisplay = LightningBuddyActionController.getAction('Dashboard',
                                                                                                     'Home',
                                                                                                    null,
                                                                                                     null);
        System.assertEquals(null, actionsToDisplay, 'Actions fetched for Dashboard home');
    }
    
    public static testmethod void testRunOnlyOnce(){
        List<Actions__c> actionsToDisplay = LightningBuddyActionController.getAction('Contact',
                                                                                                     'Home',
                                                                                                    null,
                                                                                                     null);
        //System.assertEquals(null, actionsToDisplay, 'Actions fetched for Contact Home');
    }
    
    public static testmethod void testDaysAfterADate(){
        List<Actions__c> actionsToDisplay = LightningBuddyActionController.getAction('Campaign',
                                                                                                     'Home',
                                                                                                    null,
                                                                                                     null);
        System.assertEquals(1, actionsToDisplay.size(), 'No actions fetched for Campaign Home');
        System.assertEquals('Days after certain date', actionsToDisplay[0].Action_Text__c, 'Action text mismatch');
    }
    public static testmethod void testDaysAfterADateNoAction(){
        List<Actions__c> actionsToDisplay = LightningBuddyActionController.getAction('Contract',
                                                                                                     'Home',
                                                                                                     null,
                                                                                                     null);
       // System.assertEquals(null, actionsToDisplay, 'testDaysAfterADateNoAction = Actions fetched for Contract Home when not expected');
    }
    
    public static testmethod void testDaysAfterAFutureDate(){
        List<Actions__c> actionsToDisplay = LightningBuddyActionController.getAction('Asset',
                                                                                                     'Home',
                                                                                                     null,
                                                                                                     null);
       // System.assertEquals(null, actionsToDisplay, 'testDaysAfterADateNoAction = Actions fetched for Contract Home when not expected');
    }

    public static testmethod void testObjectSubTab(){
        Actions__c action = [select Id from Actions__c where Name='Test Sub Tab Action' limit 1];
        
        List<Actions__c> actionsToDisplay = LightningBuddyActionController.getAction('Actions__c',
                                                                                                     'Record Detail',
                                                                                                     null,
                                                                                                     'MySubTab');
        System.assertEquals(1, actionsToDisplay.size(), 'testObjectSubTab = Actions empty when action expected');
    }

    public static testmethod void testObjectSubTabWithRecordId(){
        Actions__c action = [select Id from Actions__c where Name='Test Sub Tab Action' limit 1];
        
        List<Actions__c> actionsToDisplay = LightningBuddyActionController.getAction('Actions__c',
                                                                                                     'Record Detail',
                                                                                                     action.Id,
                                                                                                     'MySubTab');
        System.assertEquals(1, actionsToDisplay.size(), 'testObjectSubTabWithRecordId = Actions returned when none expected');
    }
}