force-app/main/default/objects/Flex_Control_Center_Config__c/Flex_Control_Center_Config__c.object-meta.xml
<CustomObject>
    <label>Control Center Config</label>
    <nameField>
        <displayFormat>CCC-{00000000}</displayFormat>
        <label>Control Center Config Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Control Center Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Flex_Control_Center_Config__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Whether the record is active</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Flex_Control_Center_Config__c/fields/Geo_Location__c.field-meta.xml
<CustomField>
    <fullName>Geo_Location__c</fullName>
    <label>Geo Location</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Address_Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Flex_Control_Center_Config__c/fields/Max_Active_Contracts__c.field-meta.xml
<CustomField>
    <fullName>Max_Active_Contracts__c</fullName>
    <description>Max allowed active contracts</description>
    <inlineHelpText>Maximum number of active Contracts against the Account that can meet the criteria. If the number of active Contracts is greater than this value, the user will not be able to kickstart the C&amp;R process.</inlineHelpText>
    <label>Max Active Contracts</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Flex_Control_Center_Config__c/fields/Min_Contract_End_Days__c.field-meta.xml
<CustomField>
    <fullName>Min_Contract_End_Days__c</fullName>
    <description>Minimum days before contract end</description>
    <inlineHelpText>Remaining number of days for the Contract</inlineHelpText>
    <label>Min Contract End Days</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Flex_Control_Center_Config__c/fields/Renewal_Prob_Threshold__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Prob_Threshold__c</fullName>
    <description>Renewal probability threshold (%)</description>
    <inlineHelpText>User in the query to exclude Contracts where the Renewal Opp&apos;s Probability is greater than the value set in this field</inlineHelpText>
    <label>Renewal Prob Threshold</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Flex_Control_Center_Config__c/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <description>Account Segment for filtering</description>
    <label>Segment</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>Management</fullName>
            </value>
            <value>
                <fullName>AE3</fullName>
            </value>
            <value>
                <fullName>Small Business</fullName>
            </value>
            <value>
                <fullName>AE1</fullName>
            </value>
            <value>
                <fullName>AE2</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
                <isActive>false</isActive>
                <label>Commercial</label>
            </value>
            <value>
                <fullName>Core</fullName>
                <isActive>false</isActive>
                <label>Core</label>
            </value>
            <value>
                <fullName>Majors</fullName>
                <isActive>false</isActive>
                <label>Majors</label>
            </value>
            <value>
                <fullName>Mid-Market</fullName>
                <isActive>false</isActive>
                <label>Mid-Market</label>
            </value>
            <value>
                <fullName>Select</fullName>
                <isActive>false</isActive>
                <label>Select</label>
            </value>
            <value>
                <fullName>Strategic</fullName>
                <isActive>false</isActive>
                <label>Strategic</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Flex_Control_Center_Config__c/fields/User_Profile__c.field-meta.xml
<CustomField>
    <fullName>User_Profile__c</fullName>
    <description>User Profile for visibility control</description>
    <label>User Profile</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Samsara - Sales Enablement</fullName>
            </value>
            <value>
                <fullName>Samsara SE</fullName>
            </value>
            <value>
                <fullName>System Administrator</fullName>
            </value>
            <value>
                <fullName>Samsara Sales - EMEA IS</fullName>
            </value>
            <value>
                <fullName>Samsara Sales - CPQ</fullName>
            </value>
            <value>
                <fullName>Samsara Sales - NA US AE2</fullName>
            </value>
            <value>
                <fullName>Sales Ops Profile</fullName>
            </value>
            <value>
                <fullName>Sales Insights Integration User</fullName>
            </value>
            <value>
                <fullName>Salesforce Sales - CPQ Mexico</fullName>
            </value>
            <value>
                <fullName>Samsara - Finance</fullName>
            </value>
            <value>
                <fullName>Samsara - Finance Admin</fullName>
            </value>
            <value>
                <fullName>Samsara - Growth Profile</fullName>
            </value>
            <value>
                <fullName>Samsara - Product Management</fullName>
            </value>
            <value>
                <fullName>Samsara - Product Operations</fullName>
            </value>
            <value>
                <fullName>Samsara Account Book ADRs</fullName>
            </value>
            <value>
                <fullName>Samsara ADRs</fullName>
            </value>
            <value>
                <fullName>Samsara API Only</fullName>
            </value>
            <value>
                <fullName>Samsara Channel Account Managers</fullName>
            </value>
            <value>
                <fullName>Samsara CSM</fullName>
            </value>
            <value>
                <fullName>Samsara CSM Management</fullName>
            </value>
            <value>
                <fullName>Samsara Finance Partners Profile</fullName>
            </value>
            <value>
                <fullName>Samsara Inbound ADRs</fullName>
            </value>
            <value>
                <fullName>Samsara Management BVS</fullName>
            </value>
            <value>
                <fullName>Samsara Management SIS</fullName>
            </value>
            <value>
                <fullName>Samsara Marketing - General</fullName>
            </value>
            <value>
                <fullName>Samsara Partner Community Login License User</fullName>
            </value>
            <value>
                <fullName>Samsara Partners Profile</fullName>
            </value>
            <value>
                <fullName>Samsara Project Portal Profile</fullName>
            </value>
            <value>
                <fullName>Samsara Sales - NA  AE1</fullName>
            </value>
            <value>
                <fullName>Samsara Sales - NA ENT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Address_Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia, Plurinational State of</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Bouvet Island</fullName>
    </customValue>
    <customValue>
        <fullName>United States</fullName>
        <default>true</default>
        <label>United States</label>
    </customValue>
    <masterLabel>Address: Country</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestData.cls
@isTest
public class TestData {
    // public static void setupAccounts() {

    // }
    public class ProductsAndPriceBooks {
        public Map<String, Product2> products = new Map<String, Product2>();
        public Map<String, PricebookEntry> pricebookEntries = new Map<String, PricebookEntry>();
    }
    /**
    * @author Groundswell - Henry Zhao - henry@gscloudsolutions.com
    * @date 2020-12-09
    *
    * @description Creates test products and pricebook entries for a specified set of product criteria
     *
     * @return An ProductsAndPriceBooks object that contains a map of products and pricebook
     * entries, mapped by their shortened ProductCode
    */
    @IsTest
    public static ProductsAndPriceBooks createProductsAndPricebookEntries() {
        Map<String, Product2> products = new Map<String, Product2>{
                'vg33' => (Product2) TestFactory.createSObject(new Product2(Name = 'HW-VG33', ProductCode = 'HW-VG33', Family = 'Test')),
                'em11' => (Product2) TestFactory.createSObject(new Product2(Name = 'HW-EM11', ProductCode = 'HW-EM11', Family = 'Test')),
                'vgLicense' => (Product2) TestFactory.createSObject(new Product2(Name = 'LIC-VG-36MO', ProductCode = 'LIC-VG-36MO', Family = 'Test')),
                'emLicense' => (Product2) TestFactory.createSObject(new Product2(Name = 'LIC-EM-36MO', ProductCode = 'LIC-EM-36MO', Family = 'Test')),
                'marketingKit' => (Product2) TestFactory.createSObject(new Product2(Name = 'KIT', ProductCode = 'MK-KT', Family = 'Test'))
        };
        insert products.values();

        Map<String, PricebookEntry> pricebookEntries = new Map<String, PricebookEntry>{
                'vg33' => (PricebookEntry) TestFactory.createSObject(new PricebookEntry(Product2Id = products.get('vg33').Id, UnitPrice = 10000)),
                'em11' => (PricebookEntry) TestFactory.createSObject(new PricebookEntry(Product2Id = products.get('em11').Id, UnitPrice = 10000)),
                'vgLicense' => (PricebookEntry) TestFactory.createSObject(new PricebookEntry(Product2Id = products.get('vgLicense').Id, UnitPrice = 10000)),
                'emLicense' => (PricebookEntry) TestFactory.createSObject(new PricebookEntry(Product2Id = products.get('emLicense').Id, UnitPrice = 10000)),
                'marketingKit' => (PricebookEntry) TestFactory.createSObject(new PricebookEntry(Product2Id = products.get('marketingKit').Id, UnitPrice = 0))
        };
        insert pricebookEntries.values();

        ProductsAndPriceBooks ret = new ProductsAndPriceBooks();
        ret.products = products;
        ret.pricebookEntries = pricebookEntries;
        return ret;
    }

    public static void setupProductsAndPricebooks() {
        // First insert the Standard and Express Pricebooks

        Pricebook2 standardPricebook = new Pricebook2(
                Id = Test.getStandardPricebookId(),
                IsActive = true
        );

        update standardPricebook;

        List<Pricebook2> pbs = new List<Pricebook2>{
                (Pricebook2) TestFactory.createSObject(new Pricebook2(Name = 'Samsara Standard')),
                (Pricebook2) TestFactory.createSObject(new Pricebook2(Name = 'Samsara Express'))
        };
        insert pbs;

        // Next, insert Products
        Product2 freeTrialProduct = (Product2) TestFactory.createSObject(new Product2(Name = 'Standard Free Trial', ProductCode = 'FREE-TRIAL-KIT'));
        Product2 welcomeProduct = (Product2) TestFactory.createSObject(new Product2(Name = 'Standard Welcome Kit', ProductCode = 'WELCOME-KIT'));
        Product2 expressWelcome = (Product2) TestFactory.createSObject(new Product2(Name = 'Express Welcome Kit', ProductCode = 'EXPRESS-WELCOME-KIT'));

        insert freeTrialProduct;
        insert welcomeProduct;
        insert expressWelcome;

        // Finally, add Products to Pricebooks by inserting PricebookEntry records
        List<PricebookEntry> pbes = new List<PricebookEntry>{
                (PricebookEntry) TestFactory.createSObject(new PricebookEntry(Pricebook2Id = standardPricebook.Id, Product2Id = expressWelcome.Id)),
                (PricebookEntry) TestFactory.createSObject(new PricebookEntry(Pricebook2Id = standardPricebook.Id, Product2Id = freeTrialProduct.Id)),
                (PricebookEntry) TestFactory.createSObject(new PricebookEntry(Pricebook2Id = standardPricebook.Id, Product2Id = welcomeProduct.Id)),
                (PricebookEntry) TestFactory.createSObject(new PricebookEntry(Pricebook2Id = pbs[1].Id, Product2Id = expressWelcome.Id)),
                (PricebookEntry) TestFactory.createSObject(new PricebookEntry(Pricebook2Id = pbs[0].Id, Product2Id = freeTrialProduct.Id)),
                (PricebookEntry) TestFactory.createSObject(new PricebookEntry(Pricebook2Id = pbs[0].Id, Product2Id = welcomeProduct.Id))
        };
        insert pbes;

        // Now, add some generic products to the pricebook to crowd it up some
        Product2[] prodList = (Product2[]) TestFactory.createSObjectList(new Product2(), 400);
        insert prodList;

        List<PricebookEntry> pbesGeneric = new List<PricebookEntry>();


        for (Integer i = 0; i < 400; i++) {
            if (i <= 201) {
                pbesGeneric.add((PricebookEntry) TestFactory.createSObject(new PricebookEntry(Pricebook2Id = standardPricebook.Id, Product2Id = prodList[i].Id)));
                pbesGeneric.add((PricebookEntry) TestFactory.createSObject(new PricebookEntry(Pricebook2Id = pbs[0].Id, Product2Id = prodList[i].Id)));
            } else {
                pbesGeneric.add((PricebookEntry) TestFactory.createSObject(new PricebookEntry(Pricebook2Id = standardPricebook.Id, Product2Id = prodList[i].Id)));
                pbesGeneric.add((PricebookEntry) TestFactory.createSObject(new PricebookEntry(Pricebook2Id = pbs[1].Id, Product2Id = prodList[i].Id)));
            }
        }
        insert pbesGeneric;
    }
    
    public static void setupControlCenterData() {
        insert new Flex_Control_Center_Config__c (
        	Active__c = true,
            User_Profile__c = 'System Administrator',
            Segment__c='Enterprise;Management',
            Geo_Location__c='United States',
            Max_Active_Contracts__c=3,
            Renewal_Prob_Threshold__c=40,
            Min_Contract_End_Days__c=90
        );
    }
}