force-app/main/default/objects/Opportunity/fields/ACV_Amount_Multi_Currency__c.field-meta.xml
<CustomField>
    <fullName>ACV_Amount_Multi_Currency__c</fullName>
    <description>This field is created for big deal Alert emails to send USD amount if the currency is not USD - GTMS-16147</description>
    <label>ACV Amount Multi Currency</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ACV_Bookings_SOT__c.field-meta.xml
<CustomField>
    <fullName>ACV_Bookings_SOT__c</fullName>
    <formula>IF(
CloseDate&gt;=DATE(2024,11,03),
(IF(ACV_Bookings__c!=0,
ACV_Bookings__c,
IF(
OR(of_Accessories__c!=0,of_HW_Products__c!=0,of_LIC_Products__c!=0,of_Serialized_Products__c!=0, SKP__c != 0),
0,
IF(OR(ISNULL(License_Term__c),License_Term__c=0),Amount, Amount / License_Term__c *12 )
))),
ACV_Bookings_Copy__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ACV Bookings</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/of_LIC_Products__c.field-meta.xml
<CustomField>
    <fullName>of_LIC_Products__c</fullName>
    <label># of LIC Products</label>
    <summarizedField>OpportunityLineItem.Quantity</summarizedField>
    <summaryFilterItems>
        <field>OpportunityLineItem.Product_Code_Copy__c</field>
        <operation>contains</operation>
        <value>LIC-</value>
    </summaryFilterItems>
    <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/flex_OpenAmendmentOpportunityController.cls
/**
 * @description       : 
 * @author            :
 * @group             : 
 * @last modified on  : 01-17-2025
 * @last modified by  : Anurag Bhatt
**/
public with sharing class flex_OpenAmendmentOpportunityController {
    @AuraEnabled(cacheable=true)
    public static List<Opportunity> getAmendmentOpportunities(List<Id> lstContractIds) {
      
        // Query opportunities for each contractId and add them to the list
       /* List<Opportunity> contractOpportunities = [
                SELECT Id, Name, StageName, CloseDate, Amount, ContractId, ACV_Amount_Multi_Currency__c,
                       Owner.Name,SBQQ__AmendedContract__c, SBQQ__AmendedContract__r.ContractNumber
                FROM Opportunity
                WHERE SBQQ__AmendedContract__c IN :lstContractIds and IsClosed = false];
        

        return contractOpportunities;*/
        List<Opportunity> contractOpportunities = new List<Opportunity>();
        Set<Opportunity> setOfOpportunity = new Set<Opportunity>();
        Set<Id> opptyidFromquoteline = new Set<Id>();
        List<Opportunity> licProductOppty = [SELECT Id, Name, StageName, CloseDate, Amount, ContractId, ACV_Bookings_SOT__c,
                       Owner.Name,SBQQ__AmendedContract__c, SBQQ__AmendedContract__r.ContractNumber FROM Opportunity WHERE SBQQ__AmendedContract__c IN :lstContractIds AND IsClosed=false AND of_LIC_Products__c!=0];
  
        // List<SBQQ__QuoteLine__c> qotlineRecOfLicProduct = [SELECT SBQQ__Quote__r.SBQQ__Opportunity2__c FROM SBQQ__QuoteLine__c WHERE SBQQ__ProductCode__c LIKE 'LIC%' 
	  	// 										 AND  SBQQ__Quote__r.SBQQ__Opportunity2__r.IsClosed=false AND
     	// 										 SBQQ__Quote__r.SBQQ__Opportunity2__r.SBQQ__AmendedContract__c IN : lstContractIds];
        // for(SBQQ__QuoteLine__c qotLine: qotlineRecOfLicProduct){
        //     opptyidFromquoteline.add(qotLine.SBQQ__Quote__r.SBQQ__Opportunity2__c);
        // }
        
        List<Opportunity> opptyIdToCheckForLicProduct = [SELECT Id, Name, StageName, CloseDate, Amount, ContractId, ACV_Bookings_SOT__c,
                       Owner.Name,SBQQ__AmendedContract__c, SBQQ__AmendedContract__r.ContractNumber FROM Opportunity WHERE SBQQ__AmendedContract__c IN :lstContractIds AND IsClosed=false AND Id IN :opptyidFromquoteline];
  	    setOfOpportunity.addAll(licProductOppty);
        setOfOpportunity.addAll(opptyIdToCheckForLicProduct);
        contractOpportunities.addAll(setOfOpportunity);
        return contractOpportunities;
        }
}