force-app/main/default/objects/Opportunity/fields/Equipment_Bookings_ACV__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Bookings_ACV__c</fullName>
    <label>Equipment Bookings ACV</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Forms_ACV__c.field-meta.xml
<CustomField>
    <fullName>Forms_ACV__c</fullName>
    <label>Forms ACV</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SBQQ__PrimaryQuote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__PrimaryQuote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Points to primary quote on this opportunity.</description>
    <inlineHelpText>Salesforce CPQ uses this to point to the primary quote on this opportunity.</inlineHelpText>
    <label>Primary Quote</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>SBQQ__Quote__c.SBQQ__Opportunity2__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>PrimaryOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/ACV_Total_Price_Stamp__c.field-meta.xml
<CustomField>
    <fullName>ACV_Total_Price_Stamp__c</fullName>
    <label>ACV Total Price Stamp</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <formula>TEXT(SBQQ__Product__r.Product_Type__c)</formula>
    <label>Product Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Total_Annual_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Annual_Price__c</fullName>
    <description>total annual price</description>
    <formula>Round(
IF(ISPICKVAL(SBQQ__Quote__r.Configuration_Segment__c,&quot;Express&quot;),
 IF(SBQQ__Quote__r.Renewal__c , (SBQQ__NetPrice__c * 12/SBQQ__Quote__r.SBQQ__SubscriptionTerm__c) , 
   ((SBQQ__NetPrice__c * 12/SBQQ__Quote__r.SBQQ__SubscriptionTerm__c) * 90/100)) ,

IF(SBQQ__Quote__r.SBQQ__SubscriptionTerm__c &lt; 12, SBQQ__NetPrice__c , 
(SBQQ__NetPrice__c * 12/SBQQ__Quote__r.SBQQ__SubscriptionTerm__c) )) *
IF(OR(ISPICKVAL(SBQQ__Quote__r.SBQQ__Opportunity2__r.Type ,&apos;Remorse Refund&apos;),ISPICKVAL(SBQQ__Quote__r.SBQQ__Opportunity2__r.Type ,&apos;Rebate&apos;)) &amp;&amp; CreatedDate &gt;= DATETIMEVALUE(&quot;2024-11-03 00:00:00&quot;) ,
 SBQQ__EffectiveQuantity__c , SBQQ__Quantity__c)
,2)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Annual Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/OpportunityEquipmentACVBatch.cls
/*
* TestClass = OpportunityEquipmentACVBatchTest

NOTE: This should run batch size ONE , as we are hardcoding the index

* This Class is used to update the Equipment ACV amount on Opp based on QLs amount. 
* System.schedule('Scheduled Job OpportunityEquipmentACVBatch 17Mins', '0 17 * * * ?', new OpportunityEquipmentACVBatch());

* Feb-3-2023 Rajesh :- GTMS-11183
* Apr-2-2024 Zakeer : GTMS-18033
*/
global class OpportunityEquipmentACVBatch implements
    Database.Batchable<sObject>, Schedulable{
 
   static gslib_IModuleLogger thisModuleLogger = gslib_LoggerService.getModuleLogger('GTMS');
   static gslib_ILogger thisLogger = thisModuleLogger.getLogger();

   public Database.QueryLocator start(Database.BatchableContext BC){
      String query = System.Label.OpportunityEquipmentACVBatch;
      if(Test.isRunningTest()){
            query = 'SELECT id,SBQQ__PrimaryQuote__c,Equipment_Bookings_ACV__c, Forms_ACV__c FROM Opportunity LIMIT 1';
      }
      return Database.getQueryLocator(query);
   }
    
   public void execute(Database.BatchableContext BC, List<Opportunity> scope){
      //For AGs & Sensors equipmentACV
      List<String> prodCodes = (System.Label.OpptyEquipACVAGSensors+','+System.Label.OpptyEquipACVAGSensors_2).replace(',,',',').replace(',null','').split(',');
      List<String> formsACVCodes = System.Label.OpptyEquipFormsACV.split(',');
      
      //List<String> prodCodes = System.Label.Connected_Equipment_Product_Codes.split(',');//combining these ProdCodes with AGSensors Label
      List<SBQQ__QuoteLine__c> quoteLineList;
      
      if(Test.isRunningTest()){
         quoteLineList = [SELECT Id, Name, Total_Annual_Price__c, ACV_Total_Price_Stamp__c, SBQQ__ProductCode__c, 
                                                SBQQ__Product__r.Sub_Family__c, SBQQ__Quantity__c, 
                                                SBQQ__Product__r.Product_Type__c, SBQQ__Product__r.ProductCode, SBQQ__RequiredBy__c, 
                                                SBQQ__Quote__r.id, 
                                                SBQQ__Quote__r.SBQQ__Opportunity2__c, SBQQ__Quote__r.SBQQ__LineItemCount__c
                                                FROM SBQQ__QuoteLine__c WHERE ((SBQQ__Product__r.ProductCode IN : prodCodes) OR (SBQQ__Product__r.ProductCode IN: formsACVCodes) )];
      }
      else{
         quoteLineList = [SELECT Id, Name, Total_Annual_Price__c, ACV_Total_Price_Stamp__c, SBQQ__ProductCode__c, 
                                                SBQQ__Product__r.Sub_Family__c, SBQQ__Quantity__c, 
                                                SBQQ__Product__r.Product_Type__c, SBQQ__Product__r.ProductCode, SBQQ__RequiredBy__c, 
                                                SBQQ__Quote__r.id, 
                                                SBQQ__Quote__r.SBQQ__Opportunity2__c, SBQQ__Quote__r.SBQQ__LineItemCount__c
                                                FROM SBQQ__QuoteLine__c 
                                                WHERE SBQQ__Quote__c =: scope[0].sbqq__primaryquote__c
                                                AND SBQQ__EffectiveQuantity__c <> 0
                                                AND ((SBQQ__Product__r.ProductCode IN : prodCodes) OR (SBQQ__Product__r.ProductCode IN: formsACVCodes) )];
      }
      
      List<Opportunity> oppsToUpdate = new List<Opportunity>();
     Opportunity newOpp = new Opportunity(Id=scope[0].Id); 
      if(!quoteLineList.isEmpty()) {
         
         Double rollupAmountForAG_Sensors = 0;
         Double rollupAmountForForms = 0;
        
         for(SBQQ__QuoteLine__c ql:quoteLineList) { 
            //GTMS-12278-July19-2023:
            if(ql.SBQQ__ProductCode__c != NULL && prodCodes.contains(ql.SBQQ__ProductCode__c)){
                 rollupAmountForAG_Sensors += ql.ACV_Total_Price_Stamp__c <> null ? ql.ACV_Total_Price_Stamp__c : 0;
            } else if(ql.SBQQ__ProductCode__c != NULL && formsACVCodes.contains(ql.SBQQ__ProductCode__c)){
                 rollupAmountForForms += ql.ACV_Total_Price_Stamp__c <> null ? ql.ACV_Total_Price_Stamp__c : 0;
            }
         }
         
         //GTMS-12278 - July19-2023 -- added if block to check for AG & Sensors products and assign ACV with TotalRollup
             if( rollupAmountForAG_Sensors <> scope[0].Equipment_Bookings_ACV__c){
                    newOpp.Equipment_Bookings_ACV__c = rollupAmountForAG_Sensors;
                 //oppsToUpdate.add(new Opportunity(Id = scope[0].Id, Equipment_Bookings_ACV__c = rollupAmountForAG_Sensors));
             }
             if( rollupAmountForForms <> scope[0].Forms_ACV__c){
                 newOpp.Forms_ACV__c = rollupAmountForForms;
             }
             
         oppsToUpdate.add(newOpp);
      } else {//GTMS-16119
          if(scope[0].Equipment_Bookings_ACV__c <> 0){
              newOpp.Equipment_Bookings_ACV__c =0;
          }
          if(scope[0].Forms_ACV__c <> 0) {//GTMS-18033
          newOpp.Forms_ACV__c =0;
          }
          oppsToUpdate.add(newOpp);
      }
      
        Database.SaveResult[] updatedOpps = Database.update(oppsToUpdate,false);
         for(Integer i = 0; i < updatedOpps.size(); i++){
            if(!updatedOpps[i].isSuccess()){
               for(Database.Error err : updatedOpps[i].getErrors())
               {
                     thisLogger.logError(err.getStatusCode() + ': ' + err.getMessage() + ', Opp fields that affected this error: ' + err.getFields());
               }
               thisLogger.dispatch();
            }
         }  
   }
 
   public void finish(Database.BatchableContext BC){
      
   }

   global void execute(SchedulableContext SC) {
      database.executebatch(new OpportunityEquipmentACVBatch(),1);
   }
}