force-app/main/default/objects/Opportunity/fields/Order_Management_Processor__c.field-meta.xml
<CustomField>
    <fullName>Order_Management_Processor__c</fullName>
    <label>Order Management Processor</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Ship_From_Location__c.field-meta.xml
<CustomField>
    <fullName>Ship_From_Location__c</fullName>
    <label>Ship From Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Samsara HQ</fullName>
            </value>
            <value>
                <fullName>DCL</fullName>
            </value>
            <value>
                <fullName>Samsara UK</fullName>
            </value>
            <value>
                <fullName>Free Trial</fullName>
            </value>
            <value>
                <fullName>VCK</fullName>
            </value>
            <value>
                <fullName>DCL-KY</fullName>
            </value>
            <value>
                <fullName>MX Free Trial</fullName>
            </value>
            <value>
                <fullName>MX-Intransit</fullName>
            </value>
            <value>
                <fullName>Estafeta</fullName>
            </value>
            <value>
                <fullName>DCL-LA</fullName>
                <default>true</default>
                <label>DCL-LA</label>
            </value>
            <value>
                <fullName>Free Trial EU</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
            </value>
            <value>
                <fullName>ON-Logistics</fullName>
            </value>
            <value>
                <fullName>OEM-Fontaine</fullName>
            </value>
            <value>
                <fullName>OEM-Freightliner-CTS</fullName>
            </value>
            <value>
                <fullName>DHL</fullName>
            </value>
            <value>
                <fullName>Work Order</fullName>
                <isActive>false</isActive>
                <label>Work Order</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Shipping_Carrier__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Carrier__c</fullName>
    <label>Shipping Carrier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>UPS</fullName>
                <default>true</default>
                <label>UPS</label>
            </value>
            <value>
                <fullName>FEDEX FREIGHT</fullName>
            </value>
            <value>
                <fullName>DHL</fullName>
            </value>
            <value>
                <fullName>Fedex</fullName>
            </value>
            <value>
                <fullName>Freight Forwarding</fullName>
            </value>
            <value>
                <fullName>Estafeta</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Shipping_Country__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Country__c</fullName>
    <label>Shipping Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Aland Islands</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia, Plurinational State of</fullName>
            </value>
            <value>
                <fullName>Bonaire, Sint Eustatius and Saba</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Bouvet Island</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Shipping_Method__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Method__c</fullName>
    <label>Shipping Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Will Call</fullName>
            </value>
            <value>
                <fullName>UK Standard</fullName>
            </value>
            <value>
                <fullName>UK Express</fullName>
            </value>
            <value>
                <fullName>3 Day Select</fullName>
            </value>
            <value>
                <fullName>Ground</fullName>
                <default>true</default>
                <label>Ground</label>
            </value>
            <value>
                <fullName>Next Day Air</fullName>
            </value>
            <value>
                <fullName>Worldwide Expedited</fullName>
            </value>
            <value>
                <fullName>ECONOMY</fullName>
            </value>
            <value>
                <fullName>Fedex Freight Economy</fullName>
            </value>
            <value>
                <fullName>International Priority</fullName>
            </value>
            <value>
                <fullName>International Economy</fullName>
            </value>
            <value>
                <fullName>Ground - Mexico</fullName>
            </value>
            <value>
                <fullName>MX Standard</fullName>
            </value>
            <value>
                <fullName>MX Express</fullName>
            </value>
            <value>
                <fullName>MX LTL</fullName>
            </value>
            <value>
                <fullName>NEXT DAY AIR RS</fullName>
            </value>
            <value>
                <fullName>GROUND RS</fullName>
            </value>
            <value>
                <fullName>3 DAY SELECT RS</fullName>
            </value>
            <value>
                <fullName>UPS 3 Day Select</fullName>
                <isActive>false</isActive>
                <label>UPS 3 Day Select</label>
            </value>
            <value>
                <fullName>UPS Ground</fullName>
                <isActive>false</isActive>
                <label>UPS Ground</label>
            </value>
            <value>
                <fullName>UPS Next Day Air</fullName>
                <isActive>false</isActive>
                <label>UPS Next Day Air</label>
            </value>
            <value>
                <fullName>UPS Worldwide Expedited</fullName>
                <isActive>false</isActive>
                <label>UPS Worldwide Expedited</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Shipping_Carrier__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Carrier__c</fullName>
    <label>Shipping Carrier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>UPS</fullName>
                <default>true</default>
                <label>UPS</label>
            </value>
            <value>
                <fullName>FEDEX FREIGHT</fullName>
            </value>
            <value>
                <fullName>DHL</fullName>
            </value>
            <value>
                <fullName>Fedex</fullName>
            </value>
            <value>
                <fullName>Freight Forwarding</fullName>
            </value>
            <value>
                <fullName>Estafeta</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Shipping_Method__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Method__c</fullName>
    <label>Shipping Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Will Call</fullName>
            </value>
            <value>
                <fullName>UK Standard</fullName>
            </value>
            <value>
                <fullName>UK Express</fullName>
            </value>
            <value>
                <fullName>3 Day Select</fullName>
            </value>
            <value>
                <fullName>Ground</fullName>
                <default>true</default>
                <label>Ground</label>
            </value>
            <value>
                <fullName>Next Day Air</fullName>
            </value>
            <value>
                <fullName>Worldwide Expedited</fullName>
            </value>
            <value>
                <fullName>ECONOMY</fullName>
            </value>
            <value>
                <fullName>Fedex Freight Economy</fullName>
            </value>
            <value>
                <fullName>Ground - Mexico</fullName>
            </value>
            <value>
                <fullName>MX LTL</fullName>
            </value>
            <value>
                <fullName>MX Standard</fullName>
            </value>
            <value>
                <fullName>MX Express</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OppHelperForOrderAndFinance.cls
/**
* @description       : This class is used to perform opportunity field update for Order and Finance
* @author            : Mayank G
* @group             :
* @last modified on  : 03-26-2025
* @last modified by  : Mayank G
**/
public class OppHelperForOrderAndFinance {
    public static void updateShipFromLocationBasedOnCountry(List<Opportunity> newOppList, Map<Id, Opportunity> oldOppMap){ 
        Set<Id> shippingAddNew = new Set<Id>();
        for (Opportunity oppty : newOppList) {
            if(oppty.Shipping_Country__c != null && oppty.Shipping_Country__c == 'Canada' && (oldOppMap == null || (oldOppMap != null && (oldOppMap.get(oppty.Id).Shipping_Country__c != oppty.Shipping_Country__c)))) { 
                if(HelperClass.shippingCountryDefaults.containskey(oppty.Shipping_Country__c)) {
                 	oppty.Ship_From_Location__c = HelperClass.shippingCountryDefaults.get(oppty.Shipping_Country__c).Ship_From_Location__c;
                    oppty.Shipping_Method__c = HelperClass.shippingCountryDefaults.get(oppty.Shipping_Country__c).Shipping_Method__c;
                    oppty.Shipping_Carrier__c = HelperClass.shippingCountryDefaults.get(oppty.Shipping_Country__c).Shipping_Carrier__c;   
                }
            }
        }
    }
  
  public void updateOrderManagementProcessor(List<Opportunity> newOppList, Map<Id, Opportunity> oldOppMap){
        
        if (UserInfo.getProfileId() == label.Profile_Samsara_Finance){
            for (Opportunity oppty : newOppList) {
                if (oldOppMap != null && oppty.StageName != oldOppMap.get(oppty.Id).StageName && (oppty.StageName == 'Purchase' || oppty.StageName == 'Orders Processing')) { 
                    oppty.Order_Management_Processor__c = UserInfo.getFirstName() + ' ' + UserInfo.getLastName();
                }
            }
        }

    }
}