force-app/main/default/objects/Opportunity/fields/Owner_AVP_Name_Copy__c.field-meta.xml
<CustomField>
    <fullName>Owner_AVP_Name_Copy__c</fullName>
    <label>Owner AVP Name Copy</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Owner_AVP_Role_Copy__c.field-meta.xml
<CustomField>
    <fullName>Owner_AVP_Role_Copy__c</fullName>
    <label>Owner AVP Role Copy</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Owner_Director_Email_Copy__c.field-meta.xml
<CustomField>
    <fullName>Owner_Director_Email_Copy__c</fullName>
    <label>Owner Director Email Copy</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Owner_Director_Name_Copy__c.field-meta.xml
<CustomField>
    <fullName>Owner_Director_Name_Copy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>NOTE: THIS IS USED FOR XACTLY ONLY. Do not use for any SFDC reporting.
Failsafe to bring return opp bookings into the hierarchy.</description>
    <inlineHelpText>NOTE: THIS IS USED FOR XACTLY ONLY. Do not use for any SFDC reporting.
Failsafe to bring return opp bookings into the hierarchy.</inlineHelpText>
    <label>Owner Director Name Copy</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Owner_Director_Role_Copy__c.field-meta.xml
<CustomField>
    <fullName>Owner_Director_Role_Copy__c</fullName>
    <label>Owner Director Role Copy</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Owner_Manager_Email_Copy__c.field-meta.xml
<CustomField>
    <fullName>Owner_Manager_Email_Copy__c</fullName>
    <description>Stores email of the owner&apos;s manager at the time opportunity moves into closing - for email alert purposes</description>
    <label>Owner Manager Email Copy</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Owner_Manager_Name_Copy__c.field-meta.xml
<CustomField>
    <fullName>Owner_Manager_Name_Copy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Stores the name of the owner&apos;s manager at the time opportunity moves into closing</description>
    <label>Owner Manager Name Copy</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Owner_Manager_Role_Copy__c.field-meta.xml
<CustomField>
    <fullName>Owner_Manager_Role_Copy__c</fullName>
    <description>Stores the role of the owner&apos;s manager at the time opportunity moves into closing</description>
    <label>Owner Manager Role Copy</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Owner_Role_Copy__c.field-meta.xml
<CustomField>
    <fullName>Owner_Role_Copy__c</fullName>
    <description>Stores the role of the owner of the opportunity at the time it became a closed won.</description>
    <label>Owner Role Copy</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Rebate_Type__c.field-meta.xml
<CustomField>
    <fullName>Rebate_Type__c</fullName>
    <label>Rebate Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Subsidy</fullName>
            </value>
            <value>
                <fullName>Buyout</fullName>
            </value>
            <value>
                <fullName>Partner Referral</fullName>
            </value>
            <value>
                <fullName>Delinquent</fullName>
            </value>
            <value>
                <fullName>Co-Term Credit</fullName>
                <label>Renewal Credit</label>
            </value>
            <value>
                <fullName>License Term Credit</fullName>
            </value>
            <value>
                <fullName>Non-Commissionable SKU</fullName>
            </value>
            <value>
                <fullName>Installation Costs</fullName>
            </value>
            <value>
                <fullName>Free Months</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Returning_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Returning_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Returning Opportunity</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Opportunity.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Opportunity.StageName</field>
            <operation>equals</operation>
            <value>Closed Won</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Return Opportunities</relationshipLabel>
    <relationshipName>Related_Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RelatedReturnOpportunityController.cls
/* ClassName - RelatedReturnOpportunityController
 * Author - devansh.pathak@samsara.com
 * Functionality - This class is called from Related_Opportunity_Flow to update owner and copy fields
 *                 on Return Opportunity from linked Revenue Opportunity
 * JIRA: GTMS-29334 
 *
 */
public class RelatedReturnOpportunityController {
    
    public Class RelatedReturnWrapper {
        @InvocableVariable 
        public List<String> oppIds; //This will contain return opportunity Id and revenue opportunity Id
    }
    
    @invocableMethod(label = 'CopyFieldsUpdate' description = 'Update copy fields on return opportunity based on swap')
    public static void updateCopyFieldsOnReturn(List<RelatedReturnWrapper> oppIdWrpList) {
        Set<Id> oppIdSet = new Set<Id>();
        
        If(!oppIdWrpList.isEmpty() && oppIdWrpList[0] != null && !oppIdWrpList[0].oppIds.isEmpty()) {
            for (String oppRecId : oppIdWrpList[0].oppIds) {
                If(oppRecId != '' && oppRecId != null) {
                    oppIdSet.add((Id)oppRecId);
                }
            }         

            List<Opportunity> oppDataList = new List<Opportunity>();
            If(!oppIdSet.isEmpty()) {
                oppDataList = [SELECT Id, Type, Rebate_Type__c, Returning_Opportunity__c, ownerId, Owner_Role_Copy__c, 
                                Owner_Manager_Name_Copy__c, Owner_Manager_Role_Copy__c, Owner_Manager_Email_Copy__c, 
                                Owner_Director_Name_Copy__c, Owner_Director_Role_Copy__c, Owner_Director_Email_Copy__c, 
                                Owner_AVP_Name_Copy__c, Owner_AVP_Role_Copy__c
                                FROM Opportunity
                                WHERE Id IN:oppIdSet];
            }
            
            
            Opportunity revenueOpp;
            Opportunity returnOpp;
            
            For(Opportunity oppRec : oppDataList) {
                If(oppRec.type == 'Revenue Opportunity') {
                    revenueOpp = oppRec;
                } else if(oppRec.type == 'Remorse Refund') {
                    returnOpp = oppRec;
                }
            }
            Try {
                Opportunity oldOpp = new Opportunity();
                
                If(revenueOpp != null && returnOpp != null) 
                {
                    //Assign return opportunity owner based on linked revenue opportunity
                    Opportunity updateRetunOpp = ReturnOwnerCopyDataUtility.updateCopyFields(returnOpp, oldOpp, revenueOpp, null, true);
                    //Assign return opportunity copy fields based on linked revenue opportunity
                    updateRetunOpp.ownerId = ReturnOwnerCopyDataUtility.getOwnerForDelinquentRebateOpportunity(new Set<Id>{revenueOpp.Id}).get(revenueOpp.Id);
                    
                    //Setting bypassForCopyDataMechanism as true, so return copy fields are not updated again through OpportunityHelperContext once owner is changed
                    OpportunityTriggerHandlerContext.bypassForCopyDataMechanism = true;
                    update updateRetunOpp;
                }
            } Catch(Exception ex) {
                System.debug('ex.getMessage() ----> ' + ex.getMessage());
                LOGGER.atError().setCLassName('RelatedReturnOpportunityController').setMethod('updateCopyFieldsOnReturn').setRecordId(returnOpp.Id).setExceptionOrMessage(ex.getMessage());
                
                Logger.setFunctionalityType('Copy Fields Update'); 
                Logger.insertMasterLogs(); 
                
            }
        }
    }
}