force-app/main/default/objects/Opportunity/fields/Rebate_Type__c.field-meta.xml
<CustomField>
    <fullName>Rebate_Type__c</fullName>
    <label>Rebate Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Subsidy</fullName>
            </value>
            <value>
                <fullName>Buyout</fullName>
            </value>
            <value>
                <fullName>Partner Referral</fullName>
            </value>
            <value>
                <fullName>Delinquent</fullName>
            </value>
            <value>
                <fullName>Co-Term Credit</fullName>
                <label>Renewal Credit</label>
            </value>
            <value>
                <fullName>License Term Credit</fullName>
            </value>
            <value>
                <fullName>Non-Commissionable SKU</fullName>
            </value>
            <value>
                <fullName>Installation Costs</fullName>
            </value>
            <value>
                <fullName>Free Months</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Tracking_Number__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Number__c</fullName>
    <label>Tracking Number</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Trial.recordType-meta.xml
<RecordType>
    <fullName>Trial</fullName>
    <active>true</active>
    <businessProcess>Standard Opportunities</businessProcess>
    <label>Trial</label>
</RecordType>

force-app/main/default/objects/Return_Shipment__e/Return_Shipment__e.object-meta.xml
<CustomObject>
    <label>Return Shipment</label>
    <pluralLabel>Return Shipments</pluralLabel>
</CustomObject>

force-app/main/default/objects/Return_Shipment__e/fields/Tracking_Id__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Id__c</fullName>
    <label>Tracking Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/zkups__UPSShipment__c/zkups__UPSShipment__c.object-meta.xml
<CustomObject>
    <customHelpPage>zkups__shipmentHelp</customHelpPage>
    <description>UPS Shipment is a collection of data that represents the details of the UPS shipment</description>
    <label>UPS Shipment</label>
    <nameField>
        <displayFormat>UPS-Shipment-{0000000000}</displayFormat>
        <label>UPS Shipment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UPS Shipments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/zkups__UPSShipment__c/fields/Shipmate_Label__c.field-meta.xml
<CustomField>
    <fullName>Shipmate_Label__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipmate Label</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>UPS Shipments (Shipmate Label)</relationshipLabel>
    <relationshipName>UPS_Shipments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/zkups__UPSShipment__c/fields/zkups__MasterTrackingId__c.field-meta.xml
<CustomField>
    <fullName>zkups__MasterTrackingId__c</fullName>
    <label>UPS Tracking Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ReturnShipmentTriggerHandler.cls
//Aug-22-2022  Chinmaya Dash GTMS-6069 Created This class for Updating tracking number of opportunity from return shipment.
public class ReturnShipmentTriggerHandler
{	
    Public static Boolean ExecuteBlock=true;
    
    public void onAfterInsert(List<zkups__UPSShipment__c> triggerNew)
    {
         If(ExecuteBlock==true && System.label.ReturnShipmentLabel=='PE'){
            
            for (zkups__UPSShipment__c shipment : triggerNew){
                
                Return_Shipment__e  event = new Return_Shipment__e ();
                event.Opportunity_Id__c  = shipment.Shipmate_Label__c;
                event.Tracking_Id__c  = shipment.zkups__MasterTrackingId__c;
                EventBus.publish(event); 
            }
        }
        Else{
            List<Id> associatedOpptyIds = new List<Id>();
            Map<Id, String> trackingNumbers = new Map<Id, String>();
            
            for (zkups__UPSShipment__c shipment : triggerNew){
                associatedOpptyIds.add(shipment.Shipmate_Label__c);
                trackingNumbers.put(shipment.Shipmate_Label__c, shipment.zkups__MasterTrackingId__c);
            }
            
            List<Opportunity> returnOpptys = [SELECT Id, Type, Tracking_Number__c FROM Opportunity WHERE ( Type = 'Free Trial Return' OR Type = 'Exchange' OR Type = 'Remorse Refund'
                                                                                                          OR Type = 'Warranty Exchange' OR (Type = 'Rebate' AND (Rebate_Type__c = 'Buyout' OR Rebate_Type__c = 'Partner Referral')) ) AND Id IN :associatedOpptyIds];
            
            if(returnOpptys.size() > 0){
                
                for (Opportunity oppty : returnOpptys){
                    oppty.Tracking_Number__c = trackingNumbers.get(oppty.Id);
                }                
                update returnOpptys;
            }
        }
    }
}