force-app/main/default/objects/Opportunity/fields/Rebate_Type__c.field-meta.xml
<CustomField>
    <fullName>Rebate_Type__c</fullName>
    <label>Rebate Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Subsidy</fullName>
            </value>
            <value>
                <fullName>Buyout</fullName>
            </value>
            <value>
                <fullName>Partner Referral</fullName>
            </value>
            <value>
                <fullName>Delinquent</fullName>
            </value>
            <value>
                <fullName>Co-Term Credit</fullName>
                <label>Renewal Credit</label>
            </value>
            <value>
                <fullName>License Term Credit</fullName>
            </value>
            <value>
                <fullName>Non-Commissionable SKU</fullName>
            </value>
            <value>
                <fullName>Installation Costs</fullName>
            </value>
            <value>
                <fullName>Free Months</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Tracking_Number__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Number__c</fullName>
    <label>Tracking Number</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Trial.recordType-meta.xml
<RecordType>
    <fullName>Trial</fullName>
    <active>true</active>
    <businessProcess>Standard Opportunities</businessProcess>
    <label>Trial</label>
</RecordType>

force-app/main/default/objects/Return_Shipment__e/Return_Shipment__e.object-meta.xml
<CustomObject>
    <label>Return Shipment</label>
    <pluralLabel>Return Shipments</pluralLabel>
</CustomObject>

force-app/main/default/objects/Return_Shipment__e/fields/Tracking_Id__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Id__c</fullName>
    <label>Tracking Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/zkmulti__MCShipment__c/zkmulti__MCShipment__c.object-meta.xml
<CustomObject>
    <label>Shipment</label>
    <nameField>
        <displayFormat>Shipment-{00000000}</displayFormat>
        <label>Shipment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/zkmulti__MCShipment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>UPS Multi Carrier Shipments (Opportunity)</relationshipLabel>
    <relationshipName>Shipments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/zkmulti__MCShipment__c/fields/zkmulti__Tracking_Number__c.field-meta.xml
<CustomField>
    <fullName>zkmulti__Tracking_Number__c</fullName>
    <label>Tracking Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ReturnShipmentTriggerHandlerMC.cls
public class ReturnShipmentTriggerHandlerMC
{   
    Public static Boolean ExecuteBlock=true;
    
    public void onAfterInsert(List<zkmulti__MCShipment__c> triggerNew)
    {
         If(ExecuteBlock==true && System.label.ReturnShipmentLabel=='PE'){
            for (zkmulti__MCShipment__c shipment : triggerNew){
                Return_Shipment__e  event = new Return_Shipment__e (Opportunity_Id__c = shipment.Opportunity__c, Tracking_Id__c  = shipment.zkmulti__Tracking_Number__c);
                EventBus.publish(event); 
            }
        }
        Else{
            List<Id> associatedOpptyIds = new List<Id>();
            Map<Id, String> trackingNumbers = new Map<Id, String>();
            
            for (zkmulti__MCShipment__c shipment : triggerNew){
                associatedOpptyIds.add(shipment.Opportunity__c);
                trackingNumbers.put(shipment.Opportunity__c, shipment.zkmulti__Tracking_Number__c);
            }
            
            List<Opportunity> returnOpptys = [SELECT Id, Type, Tracking_Number__c FROM Opportunity WHERE ( Type = 'Free Trial Return' OR Type = 'Exchange' OR Type = 'Remorse Refund'
                                                                                                          OR Type = 'Warranty Exchange' OR (Type = 'Rebate' AND (Rebate_Type__c = 'Buyout' OR Rebate_Type__c = 'Partner Referral')) ) AND Id IN :associatedOpptyIds];
            
            if(returnOpptys.size() > 0){
                
                for (Opportunity oppty : returnOpptys){
                    oppty.Tracking_Number__c = trackingNumbers.get(oppty.Id);
                }                
                update returnOpptys;
            }
        }
    }
}