force-app/main/default/objects/Opportunity/fields/SBQQ__PrimaryQuote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__PrimaryQuote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Points to primary quote on this opportunity.</description>
    <inlineHelpText>Salesforce CPQ uses this to point to the primary quote on this opportunity.</inlineHelpText>
    <label>Primary Quote</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>SBQQ__Quote__c.SBQQ__Opportunity2__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>PrimaryOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Ship_From_Location__c.field-meta.xml
<CustomField>
    <fullName>Ship_From_Location__c</fullName>
    <label>Ship From Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Samsara HQ</fullName>
            </value>
            <value>
                <fullName>DCL</fullName>
            </value>
            <value>
                <fullName>Samsara UK</fullName>
            </value>
            <value>
                <fullName>Free Trial</fullName>
            </value>
            <value>
                <fullName>VCK</fullName>
            </value>
            <value>
                <fullName>DCL-KY</fullName>
            </value>
            <value>
                <fullName>MX Free Trial</fullName>
            </value>
            <value>
                <fullName>MX-Intransit</fullName>
            </value>
            <value>
                <fullName>Estafeta</fullName>
            </value>
            <value>
                <fullName>DCL-LA</fullName>
                <default>true</default>
                <label>DCL-LA</label>
            </value>
            <value>
                <fullName>Free Trial EU</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
            </value>
            <value>
                <fullName>ON-Logistics</fullName>
            </value>
            <value>
                <fullName>OEM-Fontaine</fullName>
            </value>
            <value>
                <fullName>OEM-Freightliner-CTS</fullName>
            </value>
            <value>
                <fullName>DHL</fullName>
            </value>
            <value>
                <fullName>Work Order</fullName>
                <isActive>false</isActive>
                <label>Work Order</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Shipping_Address_NEW__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Address_NEW__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Shipping Addresses should not include a PO Box.</inlineHelpText>
    <label>Shipping Address</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Shipping_Address__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Shipping_Address__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Shipping_Carrier__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Carrier__c</fullName>
    <label>Shipping Carrier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>UPS</fullName>
                <default>true</default>
                <label>UPS</label>
            </value>
            <value>
                <fullName>FEDEX FREIGHT</fullName>
            </value>
            <value>
                <fullName>DHL</fullName>
            </value>
            <value>
                <fullName>Fedex</fullName>
            </value>
            <value>
                <fullName>Freight Forwarding</fullName>
            </value>
            <value>
                <fullName>Estafeta</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Shipping_Method__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Method__c</fullName>
    <label>Shipping Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Will Call</fullName>
            </value>
            <value>
                <fullName>UK Standard</fullName>
            </value>
            <value>
                <fullName>UK Express</fullName>
            </value>
            <value>
                <fullName>3 Day Select</fullName>
            </value>
            <value>
                <fullName>Ground</fullName>
                <default>true</default>
                <label>Ground</label>
            </value>
            <value>
                <fullName>Next Day Air</fullName>
            </value>
            <value>
                <fullName>Worldwide Expedited</fullName>
            </value>
            <value>
                <fullName>ECONOMY</fullName>
            </value>
            <value>
                <fullName>Fedex Freight Economy</fullName>
            </value>
            <value>
                <fullName>International Priority</fullName>
            </value>
            <value>
                <fullName>International Economy</fullName>
            </value>
            <value>
                <fullName>Ground - Mexico</fullName>
            </value>
            <value>
                <fullName>MX Standard</fullName>
            </value>
            <value>
                <fullName>MX Express</fullName>
            </value>
            <value>
                <fullName>MX LTL</fullName>
            </value>
            <value>
                <fullName>NEXT DAY AIR RS</fullName>
            </value>
            <value>
                <fullName>GROUND RS</fullName>
            </value>
            <value>
                <fullName>3 DAY SELECT RS</fullName>
            </value>
            <value>
                <fullName>UPS 3 Day Select</fullName>
                <isActive>false</isActive>
                <label>UPS 3 Day Select</label>
            </value>
            <value>
                <fullName>UPS Ground</fullName>
                <isActive>false</isActive>
                <label>UPS Ground</label>
            </value>
            <value>
                <fullName>UPS Next Day Air</fullName>
                <isActive>false</isActive>
                <label>UPS Next Day Air</label>
            </value>
            <value>
                <fullName>UPS Worldwide Expedited</fullName>
                <isActive>false</isActive>
                <label>UPS Worldwide Expedited</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Shipping_Address_NEW__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Address_NEW__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping Address</label>
    <referenceTo>Shipping_Address__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Shipping_Carrier__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Carrier__c</fullName>
    <label>Shipping Carrier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>UPS</fullName>
                <default>true</default>
                <label>UPS</label>
            </value>
            <value>
                <fullName>FEDEX FREIGHT</fullName>
            </value>
            <value>
                <fullName>DHL</fullName>
            </value>
            <value>
                <fullName>Fedex</fullName>
            </value>
            <value>
                <fullName>Freight Forwarding</fullName>
            </value>
            <value>
                <fullName>Estafeta</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Shipping_Method__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Method__c</fullName>
    <label>Shipping Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Will Call</fullName>
            </value>
            <value>
                <fullName>UK Standard</fullName>
            </value>
            <value>
                <fullName>UK Express</fullName>
            </value>
            <value>
                <fullName>3 Day Select</fullName>
            </value>
            <value>
                <fullName>Ground</fullName>
                <default>true</default>
                <label>Ground</label>
            </value>
            <value>
                <fullName>Next Day Air</fullName>
            </value>
            <value>
                <fullName>Worldwide Expedited</fullName>
            </value>
            <value>
                <fullName>ECONOMY</fullName>
            </value>
            <value>
                <fullName>Fedex Freight Economy</fullName>
            </value>
            <value>
                <fullName>Ground - Mexico</fullName>
            </value>
            <value>
                <fullName>MX LTL</fullName>
            </value>
            <value>
                <fullName>MX Standard</fullName>
            </value>
            <value>
                <fullName>MX Express</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request_Tracker__c/Request_Tracker__c.object-meta.xml
<CustomObject>
    <label>Request Tracker</label>
    <nameField>
        <displayFormat>RT-{0000}</displayFormat>
        <label>Request Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request Tracker</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Request_Tracker__c/fields/Quote_Id__c.field-meta.xml
<CustomField>
    <fullName>Quote_Id__c</fullName>
    <label>Quote Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Request_Tracker__c/fields/Shipping_Address_Id__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Address_Id__c</fullName>
    <label>Shipping Address Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/BypassQuoteToOptySynDate__c.field-meta.xml
<CustomField>
    <fullName>BypassQuoteToOptySynDate__c</fullName>
    <label>BypassQuoteToOptySynDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Ship_From_Location__c.field-meta.xml
<CustomField>
    <fullName>Ship_From_Location__c</fullName>
    <defaultValue>&quot;DCL&quot;</defaultValue>
    <label>Ship From Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Ship_From</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Shipping_Address_NEW__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Address_NEW__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping Address - NEW</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Shipping_Address__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.SBQQ__Account__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Shipping_Address__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Shipping_Carrier__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Carrier__c</fullName>
    <label>Shipping Carrier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>UPS</fullName>
                <default>true</default>
                <label>UPS</label>
            </value>
            <value>
                <fullName>FEDEX FREIGHT</fullName>
            </value>
            <value>
                <fullName>DHL</fullName>
            </value>
            <value>
                <fullName>Fedex</fullName>
            </value>
            <value>
                <fullName>Freight Forwarding</fullName>
            </value>
            <value>
                <fullName>Estafeta</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Shipping_Method__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Method__c</fullName>
    <label>Shipping Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Will Call</fullName>
            </value>
            <value>
                <fullName>UK Standard</fullName>
            </value>
            <value>
                <fullName>UK Express</fullName>
            </value>
            <value>
                <fullName>3 Day Select</fullName>
            </value>
            <value>
                <fullName>Ground</fullName>
                <default>true</default>
                <label>Ground</label>
            </value>
            <value>
                <fullName>Next Day Air</fullName>
            </value>
            <value>
                <fullName>Worldwide Expedited</fullName>
            </value>
            <value>
                <fullName>ECONOMY</fullName>
            </value>
            <value>
                <fullName>Fedex Freight Economy</fullName>
            </value>
            <value>
                <fullName>Ground - Mexico</fullName>
            </value>
            <value>
                <fullName>MX LTL</fullName>
            </value>
            <value>
                <fullName>MX Standard</fullName>
            </value>
            <value>
                <fullName>MX Express</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Ship_From.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DCL</fullName>
    </customValue>
    <customValue>
        <fullName>Samsara HQ</fullName>
    </customValue>
    <customValue>
        <fullName>Samsara UK</fullName>
    </customValue>
    <customValue>
        <fullName>VCK</fullName>
    </customValue>
    <customValue>
        <fullName>DCL-KY</fullName>
    </customValue>
    <customValue>
        <fullName>Estafeta</fullName>
    </customValue>
    <customValue>
        <fullName>DCL-LA</fullName>
        <default>true</default>
        <label>DCL-LA</label>
    </customValue>
    <customValue>
        <fullName>Free Trial</fullName>
    </customValue>
    <customValue>
        <fullName>MX Free Trial</fullName>
    </customValue>
    <customValue>
        <fullName>Free Trial EU</fullName>
    </customValue>
    <customValue>
        <fullName>OEM</fullName>
    </customValue>
    <customValue>
        <fullName>ON-Logistics</fullName>
    </customValue>
    <customValue>
        <fullName>OEM-Fontaine</fullName>
    </customValue>
    <customValue>
        <fullName>DHL</fullName>
    </customValue>
    <customValue>
        <fullName>OEM-Freightliner-CTS</fullName>
    </customValue>
    <masterLabel>Ship From</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DigitalRenewalQuoteUpdate.cls
public with sharing class DigitalRenewalQuoteUpdate extends QueueableChainJob {
    private Request_Tracker__c tracker;
    private OrderPayload payload;
    private String stepStatus;
    
    public DigitalRenewalQuoteUpdate(Request_Tracker__c tracker, String stepStatus, OrderPayload payload, Integer retryCount) {
        super(retryCount, stepStatus, tracker);
        this.tracker = tracker;
        this.payload = payload;
        this.stepStatus = stepStatus;
    }
    
    public override void processJob() {
        SBQQ__Quote__c quote = JsonToSFDCMapper.mapDigitalRenewalQuoteData(payload);
        Id opportunityId = payload?.opportunity?.id;
        Opportunity opp = OrderProcessorSingleton.getInstance().queryOpportunity(opportunityId);
        if(quote==null){
            createLog('Quote update: no relevant quote values found in the payload.');
            quote=new SBQQ__Quote__c();
        }
        SBQQ__Quote__c quoteDb = OrderProcessorSingleton.getInstance().queryQuote(opp?.SBQQ__PrimaryQuote__r?.Id);
        
        // quote.Shipping_Method__c = opp?.Shipping_Method__c;
        // quote.Shipping_Carrier__c = opp?.Shipping_Carrier__c;
        // quote.Ship_From_Location__c = opp?.Ship_From_Location__c;
        Id shippingAddressId = String.isNotBlank(tracker?.Shipping_Address_Id__c) ? tracker.Shipping_Address_Id__c : opp?.shipping_address_new__c;
        quote.Shipping_Address_NEW__c = String.isNotBlank(shippingAddressId) ? shippingAddressId : quoteDb?.Shipping_Address_NEW__c;

        if(String.isBlank(payload.quote?.id)){
            throw new RequestTrackerException('Quote Id is missing in the request payload. Cannot proceed with order processing.');
        }
        
        /*OrderUtil.initializeUnitOfWork();
        updateRecord(quote);
        DMLWrapper.publishDML();*/
        
        String quoteId = payload.quote?.id;
        tracker.Quote_Id__c = quoteId;
        quote.BypassQuoteToOptySynDate__c = System.now();
        updateQuoteViaRest(quote,quoteId);
        createLog('Finished processing: Quote.'+quoteId);
    }
    /*
    private SObject updateRecord(SObject newRecord) {
        if (newRecord != null) {
            handleDmlUpdate(newRecord, newRecord.getSObjectType().getDescribe().getName());
        }
        return newRecord;
    }

 	private void handleDmlUpdate(SObject newRecord, String objectName) {
        DMLWrapper.doUpdate(newRecord);
        createLog(objectName + ' Updated: ' + newRecord.Id);
    }
    */
    @TestVisible
    protected override Queueable newInstanceWithRetry(Integer retryCount) {
        return new DigitalRenewalQuoteUpdate(tracker, stepStatus, payload, retryCount);
    }
    
    public void updateQuoteViaRest(SBQQ__Quote__c quote,String quoteId) {
        if(String.isBlank(quoteId)){
            throw new RequestTrackerException('Update Quote Job Failed.QuoteId missed in the payload.'); 
        }
        
        String endpoint = System.Url.getOrgDomainUrl().toExternalForm() + orderProcessingSettings.Quote_Endpoint__c  + quoteId;
        
        Map<String, Object> body = quote.getPopulatedFieldsAsMap();
        String jsonBody = JSON.serialize(body);
        
        // Setup HTTP request
        HttpRequest req = new HttpRequest();
        req.setEndpoint(endpoint);
        req.setMethod('PATCH');
        req.setHeader('Authorization', 'Bearer ' + UserInfo.getSessionId()); 
        req.setHeader('Content-Type', 'application/json');
        req.setTimeout(120000); //Default timeout is 10 seconds; customizable per callout (1 ms to 120,000 ms range).
        req.setBody(jsonBody);
        
        // Send request
        Http http = new Http();
        HttpResponse res = http.send(req);
        
        if (res.getStatusCode() >= 200 && res.getStatusCode() < 300) {
            createLog('Quote updated successfully via REST API');
        } else {
            createLog('Update Quote Job Failed.RetryCount '+retryCount+', Status Code:' + res.getStatusCode() + ', Status:'+res.getStatus()+ ', Response Body:' + res.getBody());
            throw new RequestTrackerException('Update Quote Job Failed.retryCount:'+retryCount); 
        }
    }
    
    @TestVisible
    private void createLog(String logMessage) {
        DateTime now = DateTime.now();
        transactionFinalizer.createLog(stepStatus + ': Info', logMessage, now, now);
    }
}