force-app/main/default/objects/Opportunity/fields/Shipping_Address_NEW__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Address_NEW__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Shipping Addresses should not include a PO Box.</inlineHelpText>
    <label>Shipping Address</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Shipping_Address__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Shipping_Address__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Shipping_Address__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Address__c</fullName>
    <description>Opportunity shipping address (use in place of  quote ship-to)</description>
    <formula>Opportunity.Shipping_Address_NEW__r.Shipping_Address_Line_1__c  &amp;&quot;,&quot;&amp; BR()&amp;
 Opportunity.Shipping_Address_NEW__r.Shipping_City__c &amp;&quot;,&quot;&amp;BR()&amp;
TEXT( Opportunity.Shipping_Address_NEW__r.Shipping_State__c )&amp;IF(ISBLANK(TEXT(Opportunity.Shipping_Address_NEW__r.Shipping_State__c)),&quot;&quot;,&quot;, &quot;)&amp; Opportunity.Shipping_Address_NEW__r.Shipping_Zip_Code__c&amp;&quot;, &quot;&amp;BR()&amp;TEXT(Opportunity.Shipping_Address_NEW__r.Shipping_Country__c)</formula>
    <inlineHelpText>Opportunity shipping address</inlineHelpText>
    <label>Shipping Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Request_Tracker__c/Request_Tracker__c.object-meta.xml
<CustomObject>
    <label>Request Tracker</label>
    <nameField>
        <displayFormat>RT-{0000}</displayFormat>
        <label>Request Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request Tracker</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Request_Tracker__c/fields/Opportunity_Id__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Id__c</fullName>
    <label>Opportunity Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Request_Tracker__c/fields/Quote_Id__c.field-meta.xml
<CustomField>
    <fullName>Quote_Id__c</fullName>
    <label>Quote Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Request_Tracker__c/fields/Shipping_Address_Id__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Address_Id__c</fullName>
    <label>Shipping Address Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Shipping_Address_NEW__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Address_NEW__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping Address - NEW</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Shipping_Address__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.SBQQ__Account__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Shipping_Address__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Address__c/Shipping_Address__c.object-meta.xml
<CustomObject>
    <label>Shipping Address</label>
    <nameField>
        <label>Shipping Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipping Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/InsertQuote.cls
public class InsertQuote extends QueueableChainJob {
    private Request_Tracker__c tracker;
    private OrderPayload payload;

    public InsertQuote(Request_Tracker__c tracker, String stepStatus, OrderPayload payload, Integer retryCount) {
        super(retryCount, stepStatus, tracker);
        this.tracker = tracker;
        this.payload = payload;
    }

    public override void processJob() {
        createLog('Starting: Create Quotes.');

        OrderUtil.initializeUnitOfWork();
        processMappingAndDML();
    }

    private void processMappingAndDML() {
        //Shipping_Address__c shippingAddress = new Shipping_Address__c(Id=tracker.Shipping_Address_Id__c);
        //Opportunity opportunty = new Opportunity(Id=tracker.Opportunity_Id__c);
        createLog('Shipping Address Id.'+tracker.Shipping_Address_Id__c);
        createLog('Opportunity ID.'+tracker.Opportunity_Id__c);
        SBQQ__Quote__c quote = JsonToSFDCMapper.mapFirstTimePurchaseQuoteData(payload); 
        createLog('Quote Details.'+quote);
        if (quote == null) {
            throw new RequestTrackerException('Invalid Quote payload. Skipping.');
        }
        quote.Shipping_Address_NEW__c = tracker.Shipping_Address_Id__c;
        quote.SBQQ__Opportunity2__c=tracker.Opportunity_Id__c;
        
        //DMLWrapper.doInsert(quote, SBQQ__Quote__c.SBQQ__Opportunity2__c, opportunty); 
        DMLWrapper.doInsert(quote);
        
        DMLWrapper.publishDML();
        tracker.Quote_Id__c = quote.Id;
        createLog('Quote inserted.'+quote.Id);
    }

    protected override Queueable newInstanceWithRetry(Integer retryCount) {
        return new InsertQuote(tracker, stepStatus, payload, retryCount);
    }

    private void createLog(String logMessage) {
        transactionFinalizer.createLog(stepStatus + ': Info', logMessage, DateTime.now(), DateTime.now());
    }
}