force-app/main/default/objects/Opportunity/fields/Shipping_Address_NEW__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Address_NEW__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Shipping Addresses should not include a PO Box.</inlineHelpText>
    <label>Shipping Address</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Shipping_Address__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Shipping_Address__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Shipping_Contact__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Shipping Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunity_Shipping_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Trial_Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Trial_Primary_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Primary contact for Trial - this is the person who will sign the Trial Agreement</description>
    <inlineHelpText>Person who will sign Trial Agreement</inlineHelpText>
    <label>Trial Primary Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Trial Primary Contact)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Trial.recordType-meta.xml
<RecordType>
    <fullName>Trial</fullName>
    <active>true</active>
    <businessProcess>Standard Opportunities</businessProcess>
    <label>Trial</label>
</RecordType>

force-app/main/default/objects/Order/fields/Shipping_Address_NEW__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Address_NEW__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping Address</label>
    <referenceTo>Shipping_Address__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Shipping_Contact__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request_Tracker__c/Request_Tracker__c.object-meta.xml
<CustomObject>
    <label>Request Tracker</label>
    <nameField>
        <displayFormat>RT-{0000}</displayFormat>
        <label>Request Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request Tracker</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Request_Tracker__c/fields/Opportunity_Id__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Id__c</fullName>
    <label>Opportunity Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Request_Tracker__c/fields/Shipping_Address_Id__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Address_Id__c</fullName>
    <label>Shipping Address Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipping_Address__c/Shipping_Address__c.object-meta.xml
<CustomObject>
    <label>Shipping Address</label>
    <nameField>
        <label>Shipping Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipping Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipping_Address__c/fields/Shipping_Contact__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Shipping Addresses</relationshipLabel>
    <relationshipName>Shipping_Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FreeTrialOpportunityInsert.cls
public with sharing class FreeTrialOpportunityInsert extends QueueableChainJob {
    private Request_Tracker__c tracker;
    private OrderPayload payload;
    private String stepStatus;
    
    public FreeTrialOpportunityInsert(Request_Tracker__c tracker, String stepStatus, OrderPayload payload, Integer retryCount) {
        super(retryCount, stepStatus, tracker);
        this.tracker = tracker;
        this.payload = payload;
        this.stepStatus = stepStatus;
    }
    
    public override void processJob() {
        createLog('Started processing: Free Trial Opportunity Insert Job.');
        OrderUtil.initializeUnitOfWork();
                
        try {
            Account accnt = OrderProcessorSingleton.getInstance().queryAccount(payload?.order?.account_id);
            if (accnt == null) {
                throw new RequestTrackerException('Account not found for the order.');
            }
            
            if (tracker?.Shipping_Address_Id__c == null) {
                throw new RequestTrackerException('Shipping Address Id is missing.');
            }

            Shipping_Address__c shippingAddress = OrderProcessorSingleton.getInstance().queryShiippingAddressById(tracker?.Shipping_Address_Id__c);
        
            // Create free trial opportunity
            Opportunity freeTrialOpportunity = JsonToSFDCMapper.mapFreeTrialOpportunityData(payload);

            if (freeTrialOpportunity == null) {
                throw new RequestTrackerException('Invalid Opportunity payload. Skipping.');
            }

            freeTrialOpportunity.OwnerId = accnt?.OwnerId;
            freeTrialOpportunity.Trial_Primary_Contact__c = shippingAddress.Shipping_Contact__c;
            DMLWrapper.doInsert(freeTrialOpportunity, Opportunity.Shipping_Address_NEW__c, shippingAddress);
            DMLWrapper.publishDML();
            
            // Update tracker with free trial opportunity ID
            tracker.Opportunity_Id__c = freeTrialOpportunity?.Id;
            
            createLog('Finished processing: Free Trial Opportunity Insert. Free Trial Opportunity ID: ' + (freeTrialOpportunity?.Id != null ? freeTrialOpportunity.Id : 'NOT Generated'));
        } catch (RequestTrackerException e) {
            throw e;
        }catch (Exception e) {
            throw new RequestTrackerException('Free Trial Opportunity Insert Job Failed.retryCount:'+retryCount + 'Error Body:' + JSON.serialize(e.getMessage()));
        }
    }

    @TestVisible
    protected override Queueable newInstanceWithRetry(Integer retryCount) {
        return new FreeTrialOpportunityInsert(tracker, stepStatus, payload, retryCount);
    }
    
    private void createLog(String logMessage) {
        DateTime now = DateTime.now();
        transactionFinalizer.createLog(stepStatus + ': Info', logMessage, now, now);
    }
}