force-app/main/default/objects/Opportunity/fields/Shipping_Address_NEW__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Address_NEW__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Shipping Addresses should not include a PO Box.</inlineHelpText>
    <label>Shipping Address</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Shipping_Address__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Shipping_Address__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Trial.recordType-meta.xml
<RecordType>
    <fullName>Trial</fullName>
    <active>true</active>
    <businessProcess>Standard Opportunities</businessProcess>
    <label>Trial</label>
</RecordType>

force-app/main/default/objects/Request_Tracker__c/Request_Tracker__c.object-meta.xml
<CustomObject>
    <label>Request Tracker</label>
    <nameField>
        <displayFormat>RT-{0000}</displayFormat>
        <label>Request Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request Tracker</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Request_Tracker__c/fields/Opportunity_Id__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Id__c</fullName>
    <label>Opportunity Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Request_Tracker__c/fields/Quote_Id__c.field-meta.xml
<CustomField>
    <fullName>Quote_Id__c</fullName>
    <label>Quote Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Request_Tracker__c/fields/Shipping_Address_Id__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Address_Id__c</fullName>
    <label>Shipping Address Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Shipping_Address_NEW__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Address_NEW__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping Address - NEW</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Shipping_Address__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.SBQQ__Account__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Shipping_Address__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/InsertFreeTrialQuoteJob.cls
public with sharing class InsertFreeTrialQuoteJob extends QueueableChainJob {
    private Request_Tracker__c tracker;
    private OrderPayload payload;
    private String stepStatus;
    
    public InsertFreeTrialQuoteJob(Request_Tracker__c tracker, String stepStatus, OrderPayload payload, Integer retryCount) {
        super(retryCount, stepStatus, tracker);
        this.tracker = tracker;
        this.payload = payload;
        this.stepStatus = stepStatus;
    }
    
    public override void processJob() {
        try {
            createLog('Started processing: Insert Free Trial Quote Job.');
            OrderUtil.initializeUnitOfWork();
            
            // Validate opportunity ID from tracker
            if (String.isBlank(tracker?.Opportunity_Id__c)) {
                throw new RequestTrackerException('Opportunity ID is missing in tracker. Cannot proceed with free trial quote insertion.');
            }
            
            // Get the opportunity
            Opportunity opportunity = OrderProcessorSingleton.getInstance().queryOpportunity(tracker.Opportunity_Id__c);
            if (opportunity == null) {
                throw new RequestTrackerException('Opportunity not found with ID: ' + tracker.Opportunity_Id__c);
            }
            
            // Create free trial quote
            SBQQ__Quote__c freeTrialQuote = JsonToSFDCMapper.mapFreeTrialQuoteData(payload);

            if (freeTrialQuote == null) {
                throw new RequestTrackerException('Mapped Quote payload is invalid.');
            }
            
            freeTrialQuote.Shipping_Address_NEW__c = tracker.Shipping_Address_Id__c;
            freeTrialQuote.SBQQ__Opportunity2__c=tracker.Opportunity_Id__c;
            
            DMLWrapper.doInsert(freeTrialQuote);
        
            DMLWrapper.publishDML();
            
            // Update tracker with quote ID
            tracker.Quote_Id__c = freeTrialQuote?.Id;
            
            createLog('Finished processing: Insert Free Trial Quote. Quote ID: ' + freeTrialQuote.Id);
        } catch (RequestTrackerException e) {
            throw e;
        }catch (Exception e) {
            throw new RequestTrackerException('Insert Free Trial Quote Job Failed.retryCount:'+retryCount + 'Error Body:' + JSON.serialize(e.getMessage()));
        }
    }
    
    @TestVisible
    protected override Queueable newInstanceWithRetry(Integer retryCount) {
        return new InsertFreeTrialQuoteJob(tracker, stepStatus, payload, retryCount);
    }
    
    private void createLog(String logMessage) {
        DateTime now = DateTime.now();
        transactionFinalizer.createLog(stepStatus + ': Info', logMessage, now, now);
    }
}