force-app/main/default/objects/Contact/fields/Inbound_Reason_Faulty__c.field-meta.xml
<CustomField>
    <fullName>Inbound_Reason_Faulty__c</fullName>
    <description>Explain why inbound lead is faulty</description>
    <label>Inbound Reason Faulty</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Below minimum number of vehicles/assets</fullName>
            </value>
            <value>
                <fullName>Bogus inquiry - competitor</fullName>
                <isActive>false</isActive>
                <label>Bogus inquiry - competitor</label>
            </value>
            <value>
                <fullName>Bogus inquiry - market research</fullName>
                <isActive>false</isActive>
                <label>Bogus inquiry - market research</label>
            </value>
            <value>
                <fullName>Bogus inquiry - other</fullName>
                <isActive>false</isActive>
                <label>Bogus inquiry - other</label>
            </value>
            <value>
                <fullName>Delete Account</fullName>
            </value>
            <value>
                <fullName>Delete Contact Only</fullName>
            </value>
            <value>
                <fullName>Does not fit criteria - e.g. country,  &lt;7 vehicles, ...</fullName>
                <isActive>false</isActive>
                <label>Does not fit criteria - e.g. country,  &lt;7 vehicles, ...</label>
            </value>
            <value>
                <fullName>Duplicate Account</fullName>
            </value>
            <value>
                <fullName>Duplicate MVF contact in last 6 months</fullName>
                <isActive>false</isActive>
                <label>Duplicate MVF contact in last 6 months</label>
            </value>
            <value>
                <fullName>Inactive - No Longer There</fullName>
            </value>
            <value>
                <fullName>International Lead</fullName>
                <isActive>false</isActive>
                <label>International Lead</label>
            </value>
            <value>
                <fullName>Invalid Contact</fullName>
                <isActive>false</isActive>
                <label>Invalid Contact</label>
            </value>
            <value>
                <fullName>Invalid contact details</fullName>
            </value>
            <value>
                <fullName>Invalid details - name</fullName>
                <isActive>false</isActive>
                <label>Invalid details - name</label>
            </value>
            <value>
                <fullName>Invalid details - phone number</fullName>
                <isActive>false</isActive>
                <label>Invalid details - phone number</label>
            </value>
            <value>
                <fullName>Microfleet</fullName>
                <isActive>false</isActive>
                <label>Microfleet</label>
            </value>
            <value>
                <fullName>Misc/referrals</fullName>
                <isActive>false</isActive>
                <label>Misc/referrals</label>
            </value>
            <value>
                <fullName>--- MVF Faulty Lead Reasons ---</fullName>
                <isActive>false</isActive>
                <label>--- MVF Faulty Lead Reasons ---</label>
            </value>
            <value>
                <fullName>MX No Biz Opp - Fake lead</fullName>
                <isActive>false</isActive>
                <label>MX No Biz Opp - Fake lead</label>
            </value>
            <value>
                <fullName>MX No Biz Opp - Personal tracking</fullName>
                <isActive>false</isActive>
                <label>MX No Biz Opp - Personal tracking</label>
            </value>
            <value>
                <fullName>No Authority</fullName>
            </value>
            <value>
                <fullName>--- Non MVF Faulty Reasons ---</fullName>
                <isActive>false</isActive>
                <label>--- Non MVF Faulty Reasons ---</label>
            </value>
            <value>
                <fullName>No purchase intent (eg test lead)</fullName>
            </value>
            <value>
                <fullName>Not in account owner&apos;s territory</fullName>
            </value>
            <value>
                <fullName>Not in a country Samsara operates</fullName>
            </value>
            <value>
                <fullName>Opt out - Do Not Contact</fullName>
            </value>
            <value>
                <fullName>Test Lead</fullName>
                <isActive>false</isActive>
                <label>Test Lead</label>
            </value>
            <value>
                <fullName>Use case not a fit for Samsara products</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Contact Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Attempting</fullName>
            </value>
            <value>
                <fullName>Demo Scheduled</fullName>
            </value>
            <value>
                <fullName>Demo No Show</fullName>
            </value>
            <value>
                <fullName>Demo Completed - Not Qualified</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Retouch - Did Not Connect</fullName>
            </value>
            <value>
                <fullName>Retouch - Confirmed No Opportunity</fullName>
                <label>Connected-Disqualified</label>
            </value>
            <value>
                <fullName>Send Small Fleet Link</fullName>
            </value>
            <value>
                <fullName>Small Fleet Link Sent</fullName>
            </value>
            <value>
                <fullName>Inactive - See Parent Account</fullName>
            </value>
            <value>
                <fullName>Small Fleet Link Failed - Invalid Email</fullName>
            </value>
            <value>
                <fullName>Small Fleet Link Pending - Manual Review</fullName>
            </value>
            <value>
                <fullName>Faulty Lead</fullName>
            </value>
            <value>
                <fullName>Do Not Contact - Open Conversation</fullName>
            </value>
            <value>
                <fullName>Contact Established</fullName>
                <isActive>false</isActive>
                <label>Contact Established</label>
            </value>
            <value>
                <fullName>Create Webstore Opportunity</fullName>
                <isActive>false</isActive>
                <label>Create Webstore Opportunity</label>
            </value>
            <value>
                <fullName>Delete Account</fullName>
                <isActive>false</isActive>
                <label>Delete Account</label>
            </value>
            <value>
                <fullName>Delete Contact Only</fullName>
                <isActive>false</isActive>
                <label>Delete Contact Only</label>
            </value>
            <value>
                <fullName>GDPR Delete</fullName>
                <isActive>false</isActive>
                <label>GDPR Delete</label>
            </value>
            <value>
                <fullName>Inactive - No Longer There</fullName>
                <isActive>false</isActive>
                <label>Inactive - No Longer There</label>
            </value>
            <value>
                <fullName>Multiple Campaign Interactions</fullName>
                <isActive>false</isActive>
                <label>Multiple Campaign Interactions</label>
            </value>
            <value>
                <fullName>No Authority</fullName>
                <isActive>false</isActive>
                <label>No Authority</label>
            </value>
            <value>
                <fullName>Opt out - Do not contact</fullName>
                <isActive>false</isActive>
                <label>Opt out - Do not contact</label>
            </value>
            <value>
                <fullName>Webstore Opportunity Created</fullName>
                <isActive>false</isActive>
                <label>Webstore Opportunity Created</label>
            </value>
            <value>
                <fullName>Webstore Opportunity Creation In Progress</fullName>
                <isActive>false</isActive>
                <label>Webstore Opportunity Creation In Progress</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event/recordTypes/Demo.recordType-meta.xml
<RecordType>
    <fullName>Demo</fullName>
    <active>true</active>
    <label>Demo</label>
</RecordType>

force-app/main/default/objects/Event/recordTypes/Standard.recordType-meta.xml
<RecordType>
    <fullName>Standard</fullName>
    <active>true</active>
    <label>Standard</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Related_Contact__c.field-meta.xml
<CustomField>
    <fullName>Related_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Related Contact)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>In Fulfillment</fullName>
            </value>
            <value>
                <fullName>Fulfilled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Return Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EventHelper.cls
/*
 * May-31-2023 Siddharth (GTMS-12786): Prevent Contact Status field from being changed if it is in 'Inactive - No Longer There'
*/
public class EventHelper {
    @TestVisible private static Id recordType = Schema.SObjectType.Event.getRecordTypeInfosByName().get('Demo').getRecordTypeId();

    public static void beforeInsertUpdate(List<Event> newEventList, Map<Id, Event> oldEventMap){
        
        for(Event e: newEventList){
            if(e.RecordTypeId == recordType){
                if(oldEventMap == null){
                    if( e.Demo_Status__c.contains('Completed')){
                        e.OwnerId = System.UserInfo.getUserId();
                    }
                }
                else{
                    Event oldEvent = oldEventMap.get(e.Id);
                    if( e.Demo_Status__c.contains('Completed') 
                        && !(oldEvent.Demo_Status__c.contains('Completed'))){
                        e.OwnerId = System.UserInfo.getUserId();
                    }
                }
            }  
        }
    }

    public static void postEventcreationContactUpdate(List<Event> newEventList)  {
        List<Id> ctcid = new List<Id>(); 
        
        for(Event ev: newEventList){
            ctcid.add(ev.Related_Contact__c);
        }

        Map<Id, Contact> updateContact = new Map<Id, Contact>([ SELECT  Id, 
                                                                    Status__c, Inbound_Reason_Faulty__c,
                                                                    Description 
                                                            FROM Contact 
                                                            WHERE Id IN: ctcid]);

        for(Event e: newEventList){
            if(e.RecordTypeId == recordType){
                if(e.Type == 'Standard Demo' && e.Related_Contact__c <> null){
                    Contact ct = updateContact.get(e.Related_Contact__c);
                    	//GTMS-12786
                    //commented as part of GTMS-25351
                    //if(ct.Status__c!='Inactive - No Longer There')	
                    if(ct.Inbound_Reason_Faulty__c!='Inactive - No Longer There')
                        {
                            ct.Status__c = 'Demo Scheduled';
                        }                        
                        ct.Description = String.format('{0}\n\n{1}', new List<String>{e.Description, ct.Description});
                }
            }
        }

        if(updateContact.size() > 0){
            update updateContact.values();
        }
    }

    /*
    public static void attachopptodemo(List<Opportunity> newoppList){
        List<Id> ctcId = new List<Id>();

        for(Opportunity opp: newoppList){
            ctcid.add(opp.Related_Contact__c);
        }

        List<Event> demo = [SELECT Id, 
                                   WhatId, 
                                   WhoId, 
                                   Related_Contact__c
                            FROM Event 
                            WHERE RecordType.Name = 'Demo' 
                            AND WhatId = NULL 
                            AND (WhoId IN : ctcId OR Related_Contact__c IN : ctcId) 
                            ORDER BY CreatedDate DESC];

        for(Opportunity opp: newoppList){
            if(demo.size() > 0 ){
                for(Event dm: demo){
                    if((opp.Related_Contact__c == dm.WhoId) || (opp.Related_Contact__c == dm.Related_Contact__c)){
                        dm.WhatId = opp.Id;
                    }
                }
            }
        }
        update demo;
    }
    */
}