force-app/main/default/objects/CommercialLead_Count__c/CommercialLead_Count__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>CommercialLead Count</label>
</CustomObject>

force-app/main/default/objects/InsuranceLead_Count__c/InsuranceLead_Count__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>InsuranceLead Count</label>
</CustomObject>

force-app/main/default/objects/Lead/fields/Partner_Type__c.field-meta.xml
<CustomField>
    <fullName>Partner_Type__c</fullName>
    <label>Partner Team Alignment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>Partner Services</fullName>
            </value>
            <value>
                <fullName>MNO/FMC</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>ISV</fullName>
            </value>
            <value>
                <fullName>Channel</fullName>
                <isActive>false</isActive>
                <label>Channel</label>
            </value>
            <value>
                <fullName>Ecosystem</fullName>
                <isActive>false</isActive>
                <label>Ecosystem</label>
            </value>
            <value>
                <fullName>Installer</fullName>
                <isActive>false</isActive>
                <label>Installer</label>
            </value>
            <value>
                <fullName>Referral</fullName>
                <isActive>false</isActive>
                <label>Referral</label>
            </value>
            <value>
                <fullName>Resale</fullName>
                <isActive>false</isActive>
                <label>Resale</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UpdateRoundRobinConfigForLead.cls
/* 
* Class Created: 08/01/2023 - @author: Saiteja
* GTMS 10339-Updates to Partner Application lead routing in partner portal
* Test Class: UpdateRoundRobinConfigForLeadTest
* 
*/
public class UpdateRoundRobinConfigForLead {
    @InvocableMethod (Label='Update Lead RoundRobin Configs' Description='Method to update Lead roundrobin configs')
    public static void updateRRLeadConfigs(List<Lead> leads){
        CommercialLead_Count__c leadCommercial = [Select Id, Count__c from CommercialLead_Count__c];
		InsuranceLead_Count__c leadInsurance = [Select Id, Count__c from InsuranceLead_Count__c];
        Decimal commercialleadNum = leadCommercial.Count__c;
        Decimal insuranceleadNum = leadInsurance.Count__c;
        
        for(Lead lead : leads){
            if(lead.Partner_Type__c != null){
                if(lead.Partner_Type__c == System.label.Lead_Insurance_Type){
                    insuranceleadNum = insuranceleadNum + 1;
                }else if(lead.Partner_Type__c == System.label.Lead_Commercial_Type){
                    commercialleadNum = commercialleadNum + 1;
                }
            }
        }
        
        if(leadCommercial.Count__c != commercialleadNum){
            leadCommercial.Count__c = commercialleadNum;
            update leadCommercial;
        }
        
        if(leadInsurance.Count__c != insuranceleadNum){
            leadInsurance.Count__c = insuranceleadNum;
            update leadInsurance; 
        }   
    }
    
}