force-app/main/default/objects/QuoteSettings__mdt/QuoteSettings__mdt.object-meta.xml
<CustomObject>
    <description>This is used to hold all Quote related hardcoded values including SOQL Queries, any static numbers or Ids.</description>
    <label>QuoteSettings</label>
    <pluralLabel>QuoteSettings</pluralLabel>
</CustomObject>

force-app/main/default/objects/QuoteSettings__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteSettings__mdt/fields/ValueLong__c.field-meta.xml
<CustomField>
    <fullName>ValueLong__c</fullName>
    <label>ValueLong</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/QuoteSettings__mdt/fields/ValueSmall__c.field-meta.xml
<CustomField>
    <fullName>ValueSmall__c</fullName>
    <label>ValueSmall</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CallVertexBatch.cls
//Test Vertex batch call from Flow
global class CallVertexBatch {
   @InvocableMethod(Label='Call Vertex Batch')
   public static void invokeVertexBatch(List<String> names) {

      Integer batchSize = 1;
      List<QuoteSettings__mdt> quoteSettings = [select id, DeveloperName, Label, ValueSmall__c,ValueLong__c from QuoteSettings__mdt where Type__c ='Vertex' AND DeveloperName='BatchSize'];
      if(quoteSettings[0].DeveloperName == 'BatchSize'){
         batchSize = Integer.valueOf(quoteSettings[0].ValueSmall__c);
      }

      List<String> names2 = new List<String>();
      names2.addAll(names);

      if(!Test.isRunningTest()){
          database.executebatch(new VertexBatch(),batchSize);
      }
   }
}